/**
 * Assignments Feature Definition
 *
 * Complete assignment creation, submission, and review functionality.
 * Includes plagiarism detection, peer review, and feedback systems.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const ASSIGNMENTS_FEATURE: FeatureDefinition = {
  id: 'assignments',
  name: 'Assignments',
  category: 'content',
  description: 'Create assignments, manage submissions, and provide feedback',
  icon: 'file-text',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'assignment',
    'assignments',
    'homework',
    'coursework',
    'project',
    'projects',
    'submission',
    'submissions',
    'hand in',
    'turn in',
    'upload assignment',
    'peer review',
    'plagiarism',
    'feedback',
    'task',
    'tasks',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'course-management'],
  conflicts: [],

  pages: [
    {
      id: 'assignments-list',
      route: '/assignments',
      section: 'frontend',
      title: 'My Assignments',
      authRequired: true,
      templateId: 'assignments-list',
      components: [
        'assignments-grid',
        'assignment-card',
        'due-date-filter',
        'status-filter',
        'course-filter',
        'upcoming-deadlines',
      ],
      layout: 'default',
    },
    {
      id: 'assignment-detail',
      route: '/assignments/:id',
      section: 'frontend',
      title: 'Assignment Details',
      authRequired: true,
      templateId: 'assignment-detail',
      components: [
        'assignment-header',
        'assignment-description',
        'attachment-list',
        'rubric-view',
        'submission-form',
        'submission-status',
        'due-date-countdown',
      ],
      layout: 'default',
    },
    {
      id: 'submission-view',
      route: '/assignments/:id/submission',
      section: 'frontend',
      title: 'My Submission',
      authRequired: true,
      templateId: 'submission-view',
      components: [
        'submission-details',
        'submitted-files',
        'grade-display',
        'feedback-view',
        'resubmit-button',
        'submission-history',
      ],
      layout: 'default',
    },
    {
      id: 'peer-review',
      route: '/assignments/:id/peer-review',
      section: 'frontend',
      title: 'Peer Review',
      authRequired: true,
      templateId: 'peer-review',
      components: [
        'peer-submission-view',
        'review-form',
        'rubric-reviewer',
        'feedback-editor',
        'anonymous-badge',
      ],
      layout: 'default',
    },
    {
      id: 'admin-assignments',
      route: '/admin/assignments',
      section: 'admin',
      title: 'Manage Assignments',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'admin-assignments',
      components: [
        'assignments-table',
        'assignment-filters',
        'bulk-actions',
        'create-button',
        'export-button',
      ],
      layout: 'admin',
    },
    {
      id: 'assignment-create',
      route: '/admin/assignments/new',
      section: 'admin',
      title: 'Create Assignment',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'assignment-create',
      components: [
        'assignment-form',
        'due-date-picker',
        'attachment-uploader',
        'rubric-selector',
        'submission-settings',
        'publish-options',
      ],
      layout: 'admin',
    },
    {
      id: 'assignment-edit',
      route: '/admin/assignments/:id/edit',
      section: 'admin',
      title: 'Edit Assignment',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'assignment-edit',
      components: [
        'assignment-form',
        'due-date-picker',
        'attachment-uploader',
        'rubric-selector',
        'submission-settings',
        'extend-deadline',
      ],
      layout: 'admin',
    },
    {
      id: 'submissions-review',
      route: '/admin/assignments/:id/submissions',
      section: 'admin',
      title: 'Review Submissions',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'submissions-review',
      components: [
        'submissions-table',
        'submission-viewer',
        'grade-input',
        'feedback-editor',
        'plagiarism-report',
        'batch-grade',
      ],
      layout: 'admin',
    },
    {
      id: 'plagiarism-report',
      route: '/admin/submissions/:id/plagiarism',
      section: 'admin',
      title: 'Plagiarism Report',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'plagiarism-report',
      components: [
        'similarity-score',
        'source-matches',
        'highlighted-text',
        'comparison-view',
        'report-actions',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Assignment list components
    'assignments-grid',
    'assignment-card',
    'due-date-filter',
    'status-filter',
    'course-filter',
    'upcoming-deadlines',

    // Assignment detail components
    'assignment-header',
    'assignment-description',
    'attachment-list',
    'rubric-view',
    'due-date-countdown',

    // Submission components
    'submission-form',
    'submission-uploader',
    'submission-status',
    'submission-details',
    'submitted-files',
    'resubmit-button',
    'submission-history',
    'grade-display',
    'feedback-view',

    // Peer review components
    'peer-submission-view',
    'review-form',
    'rubric-reviewer',
    'feedback-editor',
    'anonymous-badge',

    // Admin components
    'assignments-table',
    'assignment-filters',
    'assignment-form',
    'due-date-picker',
    'attachment-uploader',
    'rubric-selector',
    'submission-settings',
    'publish-options',
    'extend-deadline',

    // Grading components
    'submissions-table',
    'submission-viewer',
    'grade-input',
    'batch-grade',

    // Plagiarism components
    'plagiarism-checker',
    'plagiarism-report',
    'similarity-score',
    'source-matches',
    'highlighted-text',
    'comparison-view',
    'report-actions',

    // Common components
    'bulk-actions',
    'create-button',
    'export-button',
  ],

  entities: [
    {
      name: 'assignments',
      displayName: 'Assignments',
      description: 'Assignment definitions and requirements',
      isCore: true,
    },
    {
      name: 'submissions',
      displayName: 'Submissions',
      description: 'Student assignment submissions',
      isCore: true,
    },
    {
      name: 'feedback',
      displayName: 'Feedback',
      description: 'Instructor feedback on submissions',
      isCore: true,
    },
    {
      name: 'plagiarism_reports',
      displayName: 'Plagiarism Reports',
      description: 'Plagiarism detection results',
      isCore: false,
    },
    {
      name: 'peer_reviews',
      displayName: 'Peer Reviews',
      description: 'Peer review submissions',
      isCore: false,
    },
    {
      name: 'assignment_attachments',
      displayName: 'Assignment Attachments',
      description: 'Files attached to assignments',
      isCore: false,
    },
    {
      name: 'submission_files',
      displayName: 'Submission Files',
      description: 'Files uploaded as submissions',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Assignment CRUD
    {
      method: 'GET',
      path: '/assignments',
      auth: true,
      handler: 'crud',
      entity: 'assignments',
      operation: 'list',
      description: 'List assignments',
    },
    {
      method: 'GET',
      path: '/assignments/:id',
      auth: true,
      handler: 'crud',
      entity: 'assignments',
      operation: 'get',
      description: 'Get assignment details',
    },
    {
      method: 'POST',
      path: '/assignments',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'assignments',
      operation: 'create',
      description: 'Create assignment',
    },
    {
      method: 'PUT',
      path: '/assignments/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'assignments',
      operation: 'update',
      description: 'Update assignment',
    },
    {
      method: 'DELETE',
      path: '/assignments/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'assignments',
      operation: 'delete',
      description: 'Delete assignment',
    },

    // Assignment actions
    {
      method: 'POST',
      path: '/assignments/:id/publish',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'assignments',
      description: 'Publish assignment',
    },
    {
      method: 'POST',
      path: '/assignments/:id/extend',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'assignments',
      description: 'Extend deadline',
    },
    {
      method: 'POST',
      path: '/assignments/:id/clone',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'assignments',
      description: 'Clone assignment',
    },

    // Submissions
    {
      method: 'GET',
      path: '/assignments/:id/submissions',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'submissions',
      operation: 'list',
      description: 'List submissions for assignment',
    },
    {
      method: 'GET',
      path: '/submissions/:id',
      auth: true,
      handler: 'crud',
      entity: 'submissions',
      operation: 'get',
      description: 'Get submission details',
    },
    {
      method: 'POST',
      path: '/assignments/:id/submit',
      auth: true,
      handler: 'custom',
      entity: 'submissions',
      description: 'Submit assignment',
    },
    {
      method: 'PUT',
      path: '/submissions/:id',
      auth: true,
      handler: 'crud',
      entity: 'submissions',
      operation: 'update',
      description: 'Update submission (resubmit)',
    },
    {
      method: 'GET',
      path: '/assignments/:id/my-submission',
      auth: true,
      handler: 'custom',
      entity: 'submissions',
      description: 'Get own submission',
    },

    // Grading submissions
    {
      method: 'POST',
      path: '/submissions/:id/grade',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'submissions',
      description: 'Grade submission',
    },
    {
      method: 'POST',
      path: '/assignments/:id/batch-grade',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'submissions',
      description: 'Batch grade submissions',
    },

    // Feedback
    {
      method: 'GET',
      path: '/submissions/:id/feedback',
      auth: true,
      handler: 'crud',
      entity: 'feedback',
      operation: 'list',
      description: 'Get feedback for submission',
    },
    {
      method: 'POST',
      path: '/submissions/:id/feedback',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'feedback',
      operation: 'create',
      description: 'Add feedback',
    },
    {
      method: 'PUT',
      path: '/feedback/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'feedback',
      operation: 'update',
      description: 'Update feedback',
    },

    // Peer review
    {
      method: 'GET',
      path: '/assignments/:id/peer-reviews',
      auth: true,
      handler: 'crud',
      entity: 'peer_reviews',
      operation: 'list',
      description: 'Get peer review assignments',
    },
    {
      method: 'POST',
      path: '/peer-reviews/:id/submit',
      auth: true,
      handler: 'custom',
      entity: 'peer_reviews',
      description: 'Submit peer review',
    },
    {
      method: 'POST',
      path: '/assignments/:id/assign-peer-reviews',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'peer_reviews',
      description: 'Assign peer reviews',
    },

    // Plagiarism
    {
      method: 'POST',
      path: '/submissions/:id/check-plagiarism',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'plagiarism_reports',
      description: 'Run plagiarism check',
    },
    {
      method: 'GET',
      path: '/submissions/:id/plagiarism-report',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'plagiarism_reports',
      operation: 'get',
      description: 'Get plagiarism report',
    },

    // File management
    {
      method: 'POST',
      path: '/assignments/:id/attachments',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'assignment_attachments',
      description: 'Upload assignment attachment',
    },
    {
      method: 'DELETE',
      path: '/attachments/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'assignment_attachments',
      operation: 'delete',
      description: 'Delete attachment',
    },

    // Export
    {
      method: 'GET',
      path: '/assignments/:id/export-submissions',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'submissions',
      description: 'Export all submissions',
    },
  ],

  config: [
    {
      key: 'allowLateSubmissions',
      label: 'Allow Late Submissions',
      type: 'boolean',
      default: true,
      description: 'Allow students to submit after deadline',
    },
    {
      key: 'latePenaltyPercent',
      label: 'Late Penalty (%)',
      type: 'number',
      default: 10,
      description: 'Percentage deducted per day late',
    },
    {
      key: 'maxLatedays',
      label: 'Maximum Late Days',
      type: 'number',
      default: 7,
      description: 'Maximum days allowed for late submission',
    },
    {
      key: 'allowResubmission',
      label: 'Allow Resubmission',
      type: 'boolean',
      default: true,
      description: 'Allow students to resubmit before deadline',
    },
    {
      key: 'maxSubmissionAttempts',
      label: 'Max Submission Attempts',
      type: 'number',
      default: 3,
      description: 'Maximum resubmission attempts (0 = unlimited)',
    },
    {
      key: 'enablePlagiarismCheck',
      label: 'Enable Plagiarism Detection',
      type: 'boolean',
      default: true,
      description: 'Automatically check submissions for plagiarism',
    },
    {
      key: 'plagiarismThreshold',
      label: 'Plagiarism Threshold (%)',
      type: 'number',
      default: 25,
      description: 'Similarity percentage to flag for review',
    },
    {
      key: 'enablePeerReview',
      label: 'Enable Peer Review',
      type: 'boolean',
      default: false,
      description: 'Allow peer review assignments',
    },
    {
      key: 'peerReviewsPerStudent',
      label: 'Peer Reviews Per Student',
      type: 'number',
      default: 3,
      description: 'Number of peer reviews each student must complete',
    },
    {
      key: 'anonymousPeerReview',
      label: 'Anonymous Peer Review',
      type: 'boolean',
      default: true,
      description: 'Hide reviewer identity from submission author',
    },
    {
      key: 'maxFileSize',
      label: 'Max File Size (MB)',
      type: 'number',
      default: 50,
      description: 'Maximum file size for uploads',
    },
    {
      key: 'allowedFileTypes',
      label: 'Allowed File Types',
      type: 'string',
      default: 'pdf,doc,docx,txt,zip,jpg,png',
      description: 'Comma-separated list of allowed extensions',
    },
  ],
};
