/**
 * Attendance Feature Definition
 *
 * Complete student attendance tracking for educational institutions.
 * Includes check-in, absence management, and attendance analytics.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const ATTENDANCE_FEATURE: FeatureDefinition = {
  id: 'attendance',
  name: 'Attendance Tracking',
  category: 'business',
  description: 'Track student attendance, manage absences, and generate reports',
  icon: 'user-check',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'attendance',
    'attendance tracking',
    'check in',
    'check-in',
    'checkin',
    'absence',
    'absences',
    'absent',
    'present',
    'roll call',
    'attendance sheet',
    'attendance record',
    'tardy',
    'late',
    'excused',
    'unexcused',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'student-records'],
  conflicts: [],

  pages: [
    {
      id: 'attendance-sheet',
      route: '/admin/attendance',
      section: 'admin',
      title: 'Take Attendance',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'attendance-sheet',
      components: [
        'attendance-grid',
        'class-selector',
        'date-picker',
        'student-list',
        'check-in-button',
        'status-toggle',
        'notes-input',
        'save-button',
      ],
      layout: 'admin',
    },
    {
      id: 'attendance-reports',
      route: '/admin/attendance/reports',
      section: 'admin',
      title: 'Attendance Reports',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'attendance-reports',
      components: [
        'report-filters',
        'date-range-picker',
        'attendance-summary',
        'attendance-chart',
        'student-attendance-table',
        'export-button',
      ],
      layout: 'admin',
    },
    {
      id: 'absence-management',
      route: '/admin/attendance/absences',
      section: 'admin',
      title: 'Manage Absences',
      authRequired: true,
      roles: ['admin'],
      templateId: 'absence-management',
      components: [
        'absence-list',
        'absence-filters',
        'excuse-form',
        'documentation-uploader',
        'absence-actions',
      ],
      layout: 'admin',
    },
    {
      id: 'my-attendance',
      route: '/my-attendance',
      section: 'frontend',
      title: 'My Attendance',
      authRequired: true,
      templateId: 'my-attendance',
      components: [
        'attendance-summary',
        'attendance-calendar',
        'attendance-history',
        'absence-list',
        'excuse-request-button',
      ],
      layout: 'default',
    },
    {
      id: 'student-check-in',
      route: '/check-in',
      section: 'frontend',
      title: 'Check In',
      authRequired: true,
      templateId: 'student-check-in',
      components: [
        'check-in-button',
        'qr-scanner',
        'location-check',
        'check-in-confirmation',
      ],
      layout: 'centered',
    },
    {
      id: 'excuse-request',
      route: '/attendance/excuse',
      section: 'frontend',
      title: 'Submit Excuse',
      authRequired: true,
      templateId: 'excuse-request',
      components: [
        'absence-form',
        'date-selector',
        'reason-selector',
        'documentation-uploader',
        'submit-button',
      ],
      layout: 'default',
    },
    {
      id: 'attendance-policies',
      route: '/admin/attendance/policies',
      section: 'admin',
      title: 'Attendance Policies',
      authRequired: true,
      roles: ['admin'],
      templateId: 'attendance-policies',
      components: [
        'policy-list',
        'policy-editor',
        'threshold-settings',
        'notification-rules',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Attendance taking components
    'attendance-grid',
    'class-selector',
    'date-picker',
    'student-list',
    'check-in-button',
    'status-toggle',
    'notes-input',
    'save-button',

    // Report components
    'report-filters',
    'date-range-picker',
    'attendance-summary',
    'attendance-chart',
    'student-attendance-table',
    'export-button',

    // Absence management
    'absence-list',
    'absence-filters',
    'excuse-form',
    'documentation-uploader',
    'absence-actions',

    // Student view
    'attendance-calendar',
    'attendance-history',
    'excuse-request-button',

    // Check-in components
    'qr-scanner',
    'location-check',
    'check-in-confirmation',

    // Excuse request
    'absence-form',
    'date-selector',
    'reason-selector',
    'submit-button',

    // Policy components
    'policy-list',
    'policy-editor',
    'threshold-settings',
    'notification-rules',
  ],

  entities: [
    {
      name: 'attendance_records',
      displayName: 'Attendance Records',
      description: 'Daily attendance entries',
      isCore: true,
    },
    {
      name: 'absences',
      displayName: 'Absences',
      description: 'Absence records with reasons',
      isCore: true,
    },
    {
      name: 'attendance_policies',
      displayName: 'Attendance Policies',
      description: 'Rules and thresholds for attendance',
      isCore: false,
    },
    {
      name: 'excuse_requests',
      displayName: 'Excuse Requests',
      description: 'Student absence excuse submissions',
      isCore: false,
    },
    {
      name: 'check_ins',
      displayName: 'Check-Ins',
      description: 'Self-service check-in records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Attendance records CRUD
    {
      method: 'GET',
      path: '/attendance',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'attendance_records',
      operation: 'list',
      description: 'List attendance records',
    },
    {
      method: 'GET',
      path: '/attendance/:id',
      auth: true,
      handler: 'crud',
      entity: 'attendance_records',
      operation: 'get',
      description: 'Get attendance record',
    },
    {
      method: 'POST',
      path: '/attendance',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'attendance_records',
      operation: 'create',
      description: 'Create attendance record',
    },
    {
      method: 'PUT',
      path: '/attendance/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'attendance_records',
      operation: 'update',
      description: 'Update attendance record',
    },
    {
      method: 'DELETE',
      path: '/attendance/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'attendance_records',
      operation: 'delete',
      description: 'Delete attendance record',
    },

    // Batch operations
    {
      method: 'POST',
      path: '/attendance/batch',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'attendance_records',
      description: 'Submit attendance for multiple students',
    },
    {
      method: 'GET',
      path: '/classes/:classId/attendance/:date',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'attendance_records',
      description: 'Get class attendance for date',
    },

    // Student check-in
    {
      method: 'POST',
      path: '/check-in',
      auth: true,
      handler: 'custom',
      entity: 'check_ins',
      description: 'Student self check-in',
    },
    {
      method: 'POST',
      path: '/check-in/qr',
      auth: true,
      handler: 'custom',
      entity: 'check_ins',
      description: 'Check-in via QR code',
    },
    {
      method: 'GET',
      path: '/check-in/status',
      auth: true,
      handler: 'custom',
      entity: 'check_ins',
      description: 'Get today\'s check-in status',
    },

    // Absences
    {
      method: 'GET',
      path: '/absences',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'absences',
      operation: 'list',
      description: 'List absences',
    },
    {
      method: 'GET',
      path: '/students/:studentId/absences',
      auth: true,
      handler: 'crud',
      entity: 'absences',
      operation: 'list',
      description: 'Get student absences',
    },
    {
      method: 'POST',
      path: '/absences/:id/excuse',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'absences',
      description: 'Mark absence as excused',
    },

    // Excuse requests
    {
      method: 'GET',
      path: '/excuse-requests',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'excuse_requests',
      operation: 'list',
      description: 'List excuse requests',
    },
    {
      method: 'POST',
      path: '/excuse-requests',
      auth: true,
      handler: 'crud',
      entity: 'excuse_requests',
      operation: 'create',
      description: 'Submit excuse request',
    },
    {
      method: 'PUT',
      path: '/excuse-requests/:id/approve',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'excuse_requests',
      description: 'Approve excuse request',
    },
    {
      method: 'PUT',
      path: '/excuse-requests/:id/deny',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'excuse_requests',
      description: 'Deny excuse request',
    },

    // Reports
    {
      method: 'GET',
      path: '/attendance/reports/summary',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'attendance_records',
      description: 'Get attendance summary',
    },
    {
      method: 'GET',
      path: '/students/:studentId/attendance-summary',
      auth: true,
      handler: 'aggregate',
      entity: 'attendance_records',
      description: 'Get student attendance summary',
    },
    {
      method: 'GET',
      path: '/classes/:classId/attendance-report',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'attendance_records',
      description: 'Get class attendance report',
    },
    {
      method: 'GET',
      path: '/attendance/export',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'attendance_records',
      description: 'Export attendance data',
    },

    // My attendance (student)
    {
      method: 'GET',
      path: '/my-attendance',
      auth: true,
      handler: 'custom',
      entity: 'attendance_records',
      description: 'Get own attendance records',
    },
    {
      method: 'GET',
      path: '/my-attendance/summary',
      auth: true,
      handler: 'aggregate',
      entity: 'attendance_records',
      description: 'Get own attendance summary',
    },

    // Policies
    {
      method: 'GET',
      path: '/attendance-policies',
      auth: true,
      handler: 'crud',
      entity: 'attendance_policies',
      operation: 'list',
      description: 'List attendance policies',
    },
    {
      method: 'POST',
      path: '/attendance-policies',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'attendance_policies',
      operation: 'create',
      description: 'Create attendance policy',
    },
    {
      method: 'PUT',
      path: '/attendance-policies/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'attendance_policies',
      operation: 'update',
      description: 'Update attendance policy',
    },
  ],

  config: [
    {
      key: 'attendanceStatuses',
      label: 'Attendance Statuses',
      type: 'string',
      default: 'present,absent,late,excused',
      description: 'Comma-separated list of attendance status options',
    },
    {
      key: 'lateThresholdMinutes',
      label: 'Late Threshold (minutes)',
      type: 'number',
      default: 15,
      description: 'Minutes after class start to mark as late',
    },
    {
      key: 'enableSelfCheckIn',
      label: 'Enable Self Check-In',
      type: 'boolean',
      default: false,
      description: 'Allow students to check themselves in',
    },
    {
      key: 'checkInWindow',
      label: 'Check-In Window (minutes)',
      type: 'number',
      default: 30,
      description: 'Minutes before/after class for check-in',
    },
    {
      key: 'requireLocationCheck',
      label: 'Require Location Check',
      type: 'boolean',
      default: false,
      description: 'Verify student location during check-in',
    },
    {
      key: 'enableQRCheckIn',
      label: 'Enable QR Code Check-In',
      type: 'boolean',
      default: true,
      description: 'Allow check-in via QR code scan',
    },
    {
      key: 'absenceAlertThreshold',
      label: 'Absence Alert Threshold',
      type: 'number',
      default: 3,
      description: 'Number of absences before alerting admin',
    },
    {
      key: 'notifyParentsOnAbsence',
      label: 'Notify Parents on Absence',
      type: 'boolean',
      default: true,
      description: 'Send notification to parents when student is absent',
    },
    {
      key: 'requireExcuseDocumentation',
      label: 'Require Documentation for Excuses',
      type: 'boolean',
      default: false,
      description: 'Require uploaded documentation for excuse requests',
    },
    {
      key: 'excuseApprovalRequired',
      label: 'Require Admin Approval for Excuses',
      type: 'boolean',
      default: true,
      description: 'Require admin approval for excuse requests',
    },
  ],
};
