/**
 * Certificates Feature Definition
 *
 * Certificate and credential management for educational institutions.
 * Includes certificate generation, badge design, and verification.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CERTIFICATES_FEATURE: FeatureDefinition = {
  id: 'certificates',
  name: 'Certificates & Credentials',
  category: 'content',
  description: 'Create, issue, and verify certificates, diplomas, and digital badges',
  icon: 'award',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'certificate',
    'certificates',
    'certification',
    'credential',
    'credentials',
    'diploma',
    'diplomas',
    'badge',
    'badges',
    'digital badge',
    'micro-credential',
    'achievement',
    'award',
    'completion certificate',
    'accreditation',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'course-management'],
  conflicts: [],

  pages: [
    {
      id: 'certificates-list',
      route: '/certificates',
      section: 'frontend',
      title: 'My Certificates',
      authRequired: true,
      templateId: 'certificates-list',
      components: [
        'certificates-grid',
        'certificate-card',
        'badge-display',
        'filter-tabs',
        'search-bar',
        'share-buttons',
      ],
      layout: 'default',
    },
    {
      id: 'certificate-detail',
      route: '/certificates/:id',
      section: 'frontend',
      title: 'Certificate',
      authRequired: true,
      templateId: 'certificate-detail',
      components: [
        'certificate-viewer',
        'certificate-details',
        'verification-info',
        'download-button',
        'share-buttons',
        'print-button',
        'linkedin-add',
      ],
      layout: 'centered',
    },
    {
      id: 'certificate-builder',
      route: '/admin/certificates/builder',
      section: 'admin',
      title: 'Certificate Builder',
      authRequired: true,
      roles: ['admin'],
      templateId: 'certificate-builder',
      components: [
        'template-canvas',
        'element-toolbar',
        'text-editor',
        'image-uploader',
        'variable-inserter',
        'preview-button',
        'save-template-button',
      ],
      layout: 'admin',
    },
    {
      id: 'certificate-templates',
      route: '/admin/certificates/templates',
      section: 'admin',
      title: 'Certificate Templates',
      authRequired: true,
      roles: ['admin'],
      templateId: 'certificate-templates',
      components: [
        'templates-grid',
        'template-card',
        'create-template-button',
        'template-preview',
        'duplicate-button',
      ],
      layout: 'admin',
    },
    {
      id: 'badge-designer',
      route: '/admin/badges/designer',
      section: 'admin',
      title: 'Badge Designer',
      authRequired: true,
      roles: ['admin'],
      templateId: 'badge-designer',
      components: [
        'badge-canvas',
        'shape-selector',
        'color-picker',
        'icon-library',
        'text-overlay',
        'badge-preview',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-badges',
      route: '/admin/badges',
      section: 'admin',
      title: 'Manage Badges',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-badges',
      components: [
        'badges-table',
        'badge-filters',
        'create-badge-button',
        'award-badge-button',
        'bulk-actions',
      ],
      layout: 'admin',
    },
    {
      id: 'credential-verify',
      route: '/verify/:code',
      section: 'frontend',
      title: 'Verify Credential',
      authRequired: false,
      templateId: 'credential-verify',
      components: [
        'verification-form',
        'verification-widget',
        'credential-preview',
        'issuer-info',
        'verification-status',
      ],
      layout: 'centered',
    },
    {
      id: 'issue-certificates',
      route: '/admin/certificates/issue',
      section: 'admin',
      title: 'Issue Certificates',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'issue-certificates',
      components: [
        'recipient-selector',
        'template-selector',
        'batch-issue',
        'preview-certificates',
        'send-options',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-issued-certificates',
      route: '/admin/certificates/issued',
      section: 'admin',
      title: 'Issued Certificates',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-issued-certificates',
      components: [
        'issued-table',
        'issue-filters',
        'revoke-button',
        'resend-button',
        'export-button',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Certificate display
    'certificates-grid',
    'certificate-card',
    'certificate-viewer',
    'certificate-details',
    'download-button',
    'share-buttons',
    'print-button',
    'linkedin-add',

    // Badge display
    'badge-display',
    'badges-table',
    'badge-filters',

    // Certificate builder
    'template-canvas',
    'element-toolbar',
    'text-editor',
    'image-uploader',
    'variable-inserter',
    'preview-button',
    'save-template-button',

    // Template management
    'templates-grid',
    'template-card',
    'template-preview',
    'create-template-button',
    'duplicate-button',

    // Badge designer
    'badge-canvas',
    'shape-selector',
    'color-picker',
    'icon-library',
    'text-overlay',
    'badge-preview',
    'create-badge-button',
    'award-badge-button',

    // Verification
    'verification-form',
    'verification-widget',
    'credential-preview',
    'issuer-info',
    'verification-status',
    'verification-info',

    // Issue certificates
    'recipient-selector',
    'template-selector',
    'batch-issue',
    'preview-certificates',
    'send-options',

    // Admin management
    'issued-table',
    'issue-filters',
    'revoke-button',
    'resend-button',
    'export-button',
    'bulk-actions',

    // Common
    'filter-tabs',
    'search-bar',
    'print-view',
  ],

  entities: [
    {
      name: 'certificates',
      displayName: 'Certificates',
      description: 'Issued certificates and diplomas',
      isCore: true,
    },
    {
      name: 'certificate_templates',
      displayName: 'Certificate Templates',
      description: 'Certificate design templates',
      isCore: true,
    },
    {
      name: 'credentials',
      displayName: 'Credentials',
      description: 'Digital credentials and micro-credentials',
      isCore: true,
    },
    {
      name: 'badges',
      displayName: 'Badges',
      description: 'Digital achievement badges',
      isCore: true,
    },
    {
      name: 'verification_codes',
      displayName: 'Verification Codes',
      description: 'Unique codes for certificate verification',
      isCore: false,
    },
    {
      name: 'badge_awards',
      displayName: 'Badge Awards',
      description: 'Badge award records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // User certificates
    {
      method: 'GET',
      path: '/certificates',
      auth: true,
      handler: 'crud',
      entity: 'certificates',
      operation: 'list',
      description: 'Get user certificates',
    },
    {
      method: 'GET',
      path: '/certificates/:id',
      auth: true,
      handler: 'crud',
      entity: 'certificates',
      operation: 'get',
      description: 'Get certificate details',
    },
    {
      method: 'GET',
      path: '/certificates/:id/download',
      auth: true,
      handler: 'custom',
      entity: 'certificates',
      description: 'Download certificate PDF',
    },
    {
      method: 'GET',
      path: '/certificates/:id/image',
      auth: true,
      handler: 'custom',
      entity: 'certificates',
      description: 'Get certificate as image',
    },

    // Certificate templates
    {
      method: 'GET',
      path: '/certificate-templates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'certificate_templates',
      operation: 'list',
      description: 'List certificate templates',
    },
    {
      method: 'GET',
      path: '/certificate-templates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'certificate_templates',
      operation: 'get',
      description: 'Get template details',
    },
    {
      method: 'POST',
      path: '/certificate-templates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'certificate_templates',
      operation: 'create',
      description: 'Create certificate template',
    },
    {
      method: 'PUT',
      path: '/certificate-templates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'certificate_templates',
      operation: 'update',
      description: 'Update certificate template',
    },
    {
      method: 'DELETE',
      path: '/certificate-templates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'certificate_templates',
      operation: 'delete',
      description: 'Delete certificate template',
    },
    {
      method: 'POST',
      path: '/certificate-templates/:id/duplicate',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'certificate_templates',
      description: 'Duplicate template',
    },

    // Issue certificates
    {
      method: 'POST',
      path: '/certificates/issue',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'certificates',
      description: 'Issue certificate to student',
    },
    {
      method: 'POST',
      path: '/certificates/batch-issue',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'certificates',
      description: 'Batch issue certificates',
    },
    {
      method: 'POST',
      path: '/certificates/:id/revoke',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'certificates',
      description: 'Revoke certificate',
    },
    {
      method: 'POST',
      path: '/certificates/:id/resend',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'certificates',
      description: 'Resend certificate email',
    },

    // Admin certificates
    {
      method: 'GET',
      path: '/admin/certificates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'certificates',
      operation: 'list',
      description: 'List all issued certificates',
    },
    {
      method: 'GET',
      path: '/admin/certificates/export',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'certificates',
      description: 'Export certificates',
    },

    // Badges
    {
      method: 'GET',
      path: '/badges',
      auth: true,
      handler: 'crud',
      entity: 'badges',
      operation: 'list',
      description: 'Get available badges',
    },
    {
      method: 'GET',
      path: '/badges/:id',
      auth: true,
      handler: 'crud',
      entity: 'badges',
      operation: 'get',
      description: 'Get badge details',
    },
    {
      method: 'GET',
      path: '/my-badges',
      auth: true,
      handler: 'custom',
      entity: 'badge_awards',
      description: 'Get earned badges',
    },
    {
      method: 'POST',
      path: '/badges',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'badges',
      operation: 'create',
      description: 'Create badge',
    },
    {
      method: 'PUT',
      path: '/badges/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'badges',
      operation: 'update',
      description: 'Update badge',
    },
    {
      method: 'DELETE',
      path: '/badges/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'badges',
      operation: 'delete',
      description: 'Delete badge',
    },

    // Award badges
    {
      method: 'POST',
      path: '/badges/:id/award',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'badge_awards',
      description: 'Award badge to student',
    },
    {
      method: 'POST',
      path: '/badges/:id/batch-award',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'badge_awards',
      description: 'Batch award badge',
    },
    {
      method: 'DELETE',
      path: '/badge-awards/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'badge_awards',
      operation: 'delete',
      description: 'Revoke badge award',
    },

    // Verification
    {
      method: 'GET',
      path: '/verify/:code',
      auth: false,
      handler: 'custom',
      entity: 'verification_codes',
      description: 'Verify certificate by code',
    },
    {
      method: 'POST',
      path: '/verify',
      auth: false,
      handler: 'custom',
      entity: 'verification_codes',
      description: 'Verify certificate',
    },

    // Credentials
    {
      method: 'GET',
      path: '/credentials',
      auth: true,
      handler: 'crud',
      entity: 'credentials',
      operation: 'list',
      description: 'Get user credentials',
    },
    {
      method: 'POST',
      path: '/credentials',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'credentials',
      operation: 'create',
      description: 'Issue credential',
    },

    // Sharing
    {
      method: 'POST',
      path: '/certificates/:id/share',
      auth: true,
      handler: 'custom',
      entity: 'certificates',
      description: 'Generate shareable link',
    },
    {
      method: 'GET',
      path: '/certificates/:id/linkedin-url',
      auth: true,
      handler: 'custom',
      entity: 'certificates',
      description: 'Get LinkedIn add URL',
    },
  ],

  config: [
    {
      key: 'autoIssueCertificates',
      label: 'Auto-Issue on Completion',
      type: 'boolean',
      default: true,
      description: 'Automatically issue certificates when course is completed',
    },
    {
      key: 'requireMinimumGrade',
      label: 'Require Minimum Grade',
      type: 'boolean',
      default: true,
      description: 'Require minimum grade for certificate',
    },
    {
      key: 'minimumGradePercent',
      label: 'Minimum Grade Percentage',
      type: 'number',
      default: 70,
      description: 'Minimum grade percentage for certificate',
    },
    {
      key: 'certificateExpiry',
      label: 'Certificate Expiry (months)',
      type: 'number',
      default: 0,
      description: 'Certificate validity period (0 = never expires)',
    },
    {
      key: 'enableVerification',
      label: 'Enable Public Verification',
      type: 'boolean',
      default: true,
      description: 'Allow public verification of certificates',
    },
    {
      key: 'includeQRCode',
      label: 'Include QR Code',
      type: 'boolean',
      default: true,
      description: 'Include QR code for verification on certificate',
    },
    {
      key: 'enableBadges',
      label: 'Enable Digital Badges',
      type: 'boolean',
      default: true,
      description: 'Enable digital badge system',
    },
    {
      key: 'badgeStandard',
      label: 'Badge Standard',
      type: 'select',
      default: 'openbadges',
      options: [
        { value: 'openbadges', label: 'Open Badges 2.0' },
        { value: 'custom', label: 'Custom Format' },
      ],
      description: 'Digital badge standard to use',
    },
    {
      key: 'enableLinkedIn',
      label: 'Enable LinkedIn Integration',
      type: 'boolean',
      default: true,
      description: 'Allow adding certificates to LinkedIn',
    },
    {
      key: 'sendEmailOnIssue',
      label: 'Send Email on Issue',
      type: 'boolean',
      default: true,
      description: 'Send email notification when certificate is issued',
    },
    {
      key: 'defaultTemplate',
      label: 'Default Certificate Template',
      type: 'string',
      default: 'standard',
      description: 'Default template for new courses',
    },
  ],
};
