/**
 * Class Roster Feature Definition
 *
 * Class roster management for educational institutions.
 * Includes roster viewing, seating charts, and student grouping.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CLASS_ROSTER_FEATURE: FeatureDefinition = {
  id: 'class-roster',
  name: 'Class Roster',
  category: 'business',
  description: 'Manage class rosters, seating arrangements, and student groups',
  icon: 'users-class',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'roster',
    'class roster',
    'class list',
    'student list',
    'seating',
    'seating chart',
    'seating arrangement',
    'student groups',
    'group',
    'groups',
    'team',
    'teams',
    'class participants',
    'enrolled students',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'student-records', 'enrollment'],
  conflicts: [],

  pages: [
    {
      id: 'roster-view',
      route: '/admin/classes/:classId/roster',
      section: 'admin',
      title: 'Class Roster',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'roster-view',
      components: [
        'roster-table',
        'student-cards',
        'view-toggle',
        'search-filter',
        'export-button',
        'email-all-button',
        'print-roster',
      ],
      layout: 'admin',
    },
    {
      id: 'seating-chart',
      route: '/admin/classes/:classId/seating',
      section: 'admin',
      title: 'Seating Chart',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'seating-chart',
      components: [
        'seating-editor',
        'room-layout',
        'desk-grid',
        'student-tiles',
        'drag-assign',
        'auto-arrange',
        'save-layout',
        'print-chart',
      ],
      layout: 'admin',
    },
    {
      id: 'student-groups',
      route: '/admin/classes/:classId/groups',
      section: 'admin',
      title: 'Student Groups',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'student-groups',
      components: [
        'groups-list',
        'group-card',
        'group-manager',
        'create-group',
        'random-groups',
        'balance-groups',
        'group-assignments',
      ],
      layout: 'admin',
    },
    {
      id: 'my-class-roster',
      route: '/classes/:classId/roster',
      section: 'frontend',
      title: 'Classmates',
      authRequired: true,
      templateId: 'my-class-roster',
      components: [
        'classmate-grid',
        'classmate-card',
        'search-filter',
        'group-filter',
      ],
      layout: 'default',
    },
    {
      id: 'my-group',
      route: '/classes/:classId/my-group',
      section: 'frontend',
      title: 'My Group',
      authRequired: true,
      templateId: 'my-group',
      components: [
        'group-header',
        'group-members',
        'group-chat',
        'group-files',
        'group-tasks',
      ],
      layout: 'default',
    },
    {
      id: 'admin-all-rosters',
      route: '/admin/rosters',
      section: 'admin',
      title: 'All Class Rosters',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-all-rosters',
      components: [
        'classes-list',
        'class-filters',
        'roster-summary',
        'enrollment-stats',
        'bulk-export',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Roster view
    'roster-table',
    'student-cards',
    'view-toggle',
    'search-filter',
    'export-button',
    'email-all-button',
    'print-roster',

    // Seating chart
    'seating-editor',
    'room-layout',
    'desk-grid',
    'student-tiles',
    'drag-assign',
    'auto-arrange',
    'save-layout',
    'print-chart',

    // Student groups
    'groups-list',
    'group-card',
    'group-manager',
    'create-group',
    'random-groups',
    'balance-groups',
    'group-assignments',

    // Student view
    'classmate-grid',
    'classmate-card',
    'group-filter',

    // My group
    'group-header',
    'group-members',
    'group-chat',
    'group-files',
    'group-tasks',

    // Admin
    'classes-list',
    'class-filters',
    'roster-summary',
    'enrollment-stats',
    'bulk-export',
  ],

  entities: [
    {
      name: 'rosters',
      displayName: 'Class Rosters',
      description: 'Class membership lists',
      isCore: true,
    },
    {
      name: 'seating_arrangements',
      displayName: 'Seating Arrangements',
      description: 'Classroom seating layouts',
      isCore: false,
    },
    {
      name: 'student_groups',
      displayName: 'Student Groups',
      description: 'Student group assignments',
      isCore: true,
    },
    {
      name: 'group_members',
      displayName: 'Group Members',
      description: 'Group membership records',
      isCore: true,
    },
    {
      name: 'room_layouts',
      displayName: 'Room Layouts',
      description: 'Classroom layout templates',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Roster CRUD
    {
      method: 'GET',
      path: '/classes/:classId/roster',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'rosters',
      operation: 'get',
      description: 'Get class roster',
    },
    {
      method: 'GET',
      path: '/classes/:classId/roster/students',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'rosters',
      operation: 'list',
      description: 'List roster students',
    },
    {
      method: 'POST',
      path: '/classes/:classId/roster/add',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'rosters',
      description: 'Add student to roster',
    },
    {
      method: 'DELETE',
      path: '/classes/:classId/roster/:studentId',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'rosters',
      description: 'Remove student from roster',
    },

    // Roster actions
    {
      method: 'GET',
      path: '/classes/:classId/roster/export',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'rosters',
      description: 'Export roster',
    },
    {
      method: 'POST',
      path: '/classes/:classId/roster/email',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'rosters',
      description: 'Email all students',
    },
    {
      method: 'GET',
      path: '/classes/:classId/roster/print',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'rosters',
      description: 'Get printable roster',
    },

    // Seating arrangements
    {
      method: 'GET',
      path: '/classes/:classId/seating',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'seating_arrangements',
      operation: 'get',
      description: 'Get seating arrangement',
    },
    {
      method: 'POST',
      path: '/classes/:classId/seating',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'seating_arrangements',
      operation: 'create',
      description: 'Create seating arrangement',
    },
    {
      method: 'PUT',
      path: '/classes/:classId/seating',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'seating_arrangements',
      operation: 'update',
      description: 'Update seating arrangement',
    },
    {
      method: 'POST',
      path: '/classes/:classId/seating/auto-arrange',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'seating_arrangements',
      description: 'Auto-arrange students',
    },
    {
      method: 'GET',
      path: '/classes/:classId/seating/print',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'seating_arrangements',
      description: 'Get printable seating chart',
    },

    // Room layouts
    {
      method: 'GET',
      path: '/room-layouts',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'room_layouts',
      operation: 'list',
      description: 'List room layouts',
    },
    {
      method: 'POST',
      path: '/room-layouts',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'room_layouts',
      operation: 'create',
      description: 'Create room layout',
    },
    {
      method: 'PUT',
      path: '/room-layouts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'room_layouts',
      operation: 'update',
      description: 'Update room layout',
    },
    {
      method: 'DELETE',
      path: '/room-layouts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'room_layouts',
      operation: 'delete',
      description: 'Delete room layout',
    },

    // Student groups
    {
      method: 'GET',
      path: '/classes/:classId/groups',
      auth: true,
      handler: 'crud',
      entity: 'student_groups',
      operation: 'list',
      description: 'List student groups',
    },
    {
      method: 'GET',
      path: '/groups/:groupId',
      auth: true,
      handler: 'crud',
      entity: 'student_groups',
      operation: 'get',
      description: 'Get group details',
    },
    {
      method: 'POST',
      path: '/classes/:classId/groups',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'student_groups',
      operation: 'create',
      description: 'Create group',
    },
    {
      method: 'PUT',
      path: '/groups/:groupId',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'student_groups',
      operation: 'update',
      description: 'Update group',
    },
    {
      method: 'DELETE',
      path: '/groups/:groupId',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'student_groups',
      operation: 'delete',
      description: 'Delete group',
    },

    // Group members
    {
      method: 'GET',
      path: '/groups/:groupId/members',
      auth: true,
      handler: 'crud',
      entity: 'group_members',
      operation: 'list',
      description: 'List group members',
    },
    {
      method: 'POST',
      path: '/groups/:groupId/members',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'group_members',
      operation: 'create',
      description: 'Add member to group',
    },
    {
      method: 'DELETE',
      path: '/groups/:groupId/members/:studentId',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'group_members',
      description: 'Remove member from group',
    },
    {
      method: 'PUT',
      path: '/groups/:groupId/members/:studentId/move',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'group_members',
      description: 'Move member to different group',
    },

    // Auto grouping
    {
      method: 'POST',
      path: '/classes/:classId/groups/random',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'student_groups',
      description: 'Create random groups',
    },
    {
      method: 'POST',
      path: '/classes/:classId/groups/balance',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'student_groups',
      description: 'Balance existing groups',
    },

    // My group (student)
    {
      method: 'GET',
      path: '/classes/:classId/my-group',
      auth: true,
      handler: 'custom',
      entity: 'student_groups',
      description: 'Get my group assignment',
    },
    {
      method: 'GET',
      path: '/classes/:classId/classmates',
      auth: true,
      handler: 'custom',
      entity: 'rosters',
      description: 'Get classmates (student view)',
    },

    // Admin
    {
      method: 'GET',
      path: '/admin/rosters',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'rosters',
      operation: 'list',
      description: 'List all rosters',
    },
    {
      method: 'GET',
      path: '/admin/rosters/export',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'rosters',
      description: 'Bulk export rosters',
    },
    {
      method: 'GET',
      path: '/admin/rosters/stats',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'rosters',
      description: 'Get enrollment statistics',
    },
  ],

  config: [
    {
      key: 'showStudentPhotos',
      label: 'Show Student Photos',
      type: 'boolean',
      default: true,
      description: 'Display student photos in roster view',
    },
    {
      key: 'showStudentEmail',
      label: 'Show Student Email',
      type: 'boolean',
      default: true,
      description: 'Display student emails in roster',
    },
    {
      key: 'allowStudentViewRoster',
      label: 'Students Can View Roster',
      type: 'boolean',
      default: true,
      description: 'Allow students to see their classmates',
    },
    {
      key: 'showStudentContact',
      label: 'Show Contact Info to Students',
      type: 'boolean',
      default: false,
      description: 'Show classmate contact info to students',
    },
    {
      key: 'enableSeatingCharts',
      label: 'Enable Seating Charts',
      type: 'boolean',
      default: true,
      description: 'Enable classroom seating management',
    },
    {
      key: 'enableStudentGroups',
      label: 'Enable Student Groups',
      type: 'boolean',
      default: true,
      description: 'Enable student grouping feature',
    },
    {
      key: 'maxGroupSize',
      label: 'Default Max Group Size',
      type: 'number',
      default: 5,
      description: 'Default maximum students per group',
    },
    {
      key: 'minGroupSize',
      label: 'Default Min Group Size',
      type: 'number',
      default: 2,
      description: 'Default minimum students per group',
    },
    {
      key: 'allowSelfGrouping',
      label: 'Allow Self-Grouping',
      type: 'boolean',
      default: false,
      description: 'Allow students to form their own groups',
    },
    {
      key: 'groupNamingStyle',
      label: 'Group Naming Style',
      type: 'select',
      default: 'numbered',
      options: [
        { value: 'numbered', label: 'Numbered (Group 1, 2, 3...)' },
        { value: 'lettered', label: 'Lettered (Group A, B, C...)' },
        { value: 'colors', label: 'Colors (Red Team, Blue Team...)' },
        { value: 'custom', label: 'Custom Names' },
      ],
      description: 'How to name automatically created groups',
    },
    {
      key: 'enableGroupChat',
      label: 'Enable Group Chat',
      type: 'boolean',
      default: true,
      description: 'Enable chat within student groups',
    },
    {
      key: 'enableGroupFiles',
      label: 'Enable Group File Sharing',
      type: 'boolean',
      default: true,
      description: 'Allow file sharing within groups',
    },
  ],
};
