/**
 * Course Management Feature Definition
 *
 * Complete course creation and management functionality for educational platforms,
 * online academies, schools, and any app requiring structured course content.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const COURSE_MANAGEMENT_FEATURE: FeatureDefinition = {
  id: 'course-management',
  name: 'Course Management',
  category: 'content',
  description: 'Create, organize, and manage courses with modules, lessons, and curriculum',
  icon: 'book-open',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'course',
    'courses',
    'course management',
    'curriculum',
    'lesson',
    'lessons',
    'module',
    'modules',
    'syllabus',
    'course builder',
    'course creation',
    'learning content',
    'educational content',
    'class content',
    'course catalog',
    'course library',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'courses-list',
      route: '/courses',
      section: 'frontend',
      title: 'Browse Courses',
      authRequired: false,
      templateId: 'courses-list',
      components: [
        'course-grid',
        'course-card',
        'course-filters',
        'category-filter',
        'level-filter',
        'search-bar',
      ],
      layout: 'default',
    },
    {
      id: 'course-detail',
      route: '/courses/:id',
      section: 'frontend',
      title: 'Course Details',
      authRequired: false,
      templateId: 'course-detail',
      components: [
        'course-header',
        'course-overview',
        'curriculum-preview',
        'instructor-info',
        'course-reviews',
        'enroll-button',
        'prerequisite-list',
      ],
      layout: 'default',
    },
    {
      id: 'course-builder',
      route: '/admin/courses/new',
      section: 'admin',
      title: 'Create Course',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'course-builder',
      components: [
        'course-form',
        'course-settings',
        'thumbnail-uploader',
        'category-selector',
        'pricing-config',
        'prerequisite-selector',
      ],
      layout: 'admin',
    },
    {
      id: 'course-editor',
      route: '/admin/courses/:id/edit',
      section: 'admin',
      title: 'Edit Course',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'course-editor',
      components: [
        'course-form',
        'course-settings',
        'thumbnail-uploader',
        'category-selector',
        'pricing-config',
        'publish-toggle',
      ],
      layout: 'admin',
    },
    {
      id: 'curriculum-editor',
      route: '/admin/courses/:id/curriculum',
      section: 'admin',
      title: 'Edit Curriculum',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'curriculum-editor',
      components: [
        'module-list',
        'module-editor',
        'lesson-list',
        'lesson-editor',
        'content-block',
        'drag-drop-reorder',
        'prerequisite-tree',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-courses',
      route: '/admin/courses',
      section: 'admin',
      title: 'Manage Courses',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'admin-courses',
      components: [
        'courses-table',
        'course-filters',
        'bulk-actions',
        'course-stats',
        'export-button',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Course display components
    'course-grid',
    'course-card',
    'course-header',
    'course-overview',
    'course-reviews',
    'instructor-info',
    'enroll-button',
    'prerequisite-list',

    // Curriculum components
    'curriculum-preview',
    'module-list',
    'module-editor',
    'lesson-list',
    'lesson-editor',
    'content-block',
    'prerequisite-tree',
    'drag-drop-reorder',

    // Form components
    'course-form',
    'course-settings',
    'thumbnail-uploader',
    'category-selector',
    'pricing-config',
    'publish-toggle',
    'prerequisite-selector',

    // Filter components
    'course-filters',
    'category-filter',
    'level-filter',
    'search-bar',

    // Admin components
    'courses-table',
    'course-stats',
    'bulk-actions',
    'export-button',
  ],

  entities: [
    {
      name: 'courses',
      displayName: 'Courses',
      description: 'Course definitions with metadata and settings',
      isCore: true,
    },
    {
      name: 'modules',
      displayName: 'Modules',
      description: 'Course modules/sections',
      isCore: true,
    },
    {
      name: 'lessons',
      displayName: 'Lessons',
      description: 'Individual lessons within modules',
      isCore: true,
    },
    {
      name: 'course_content',
      displayName: 'Course Content',
      description: 'Content blocks within lessons (text, video, quiz, etc.)',
      isCore: true,
    },
    {
      name: 'course_categories',
      displayName: 'Course Categories',
      description: 'Categories for organizing courses',
      isCore: false,
    },
    {
      name: 'course_prerequisites',
      displayName: 'Course Prerequisites',
      description: 'Prerequisite relationships between courses',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Course CRUD
    {
      method: 'GET',
      path: '/courses',
      auth: false,
      handler: 'crud',
      entity: 'courses',
      operation: 'list',
      description: 'List all published courses',
    },
    {
      method: 'GET',
      path: '/courses/:id',
      auth: false,
      handler: 'crud',
      entity: 'courses',
      operation: 'get',
      description: 'Get course details',
    },
    {
      method: 'POST',
      path: '/courses',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'courses',
      operation: 'create',
      description: 'Create new course',
    },
    {
      method: 'PUT',
      path: '/courses/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'courses',
      operation: 'update',
      description: 'Update course',
    },
    {
      method: 'DELETE',
      path: '/courses/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'courses',
      operation: 'delete',
      description: 'Delete course',
    },

    // Module routes
    {
      method: 'GET',
      path: '/courses/:courseId/modules',
      auth: false,
      handler: 'crud',
      entity: 'modules',
      operation: 'list',
      description: 'List course modules',
    },
    {
      method: 'POST',
      path: '/courses/:courseId/modules',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'modules',
      operation: 'create',
      description: 'Add module to course',
    },
    {
      method: 'PUT',
      path: '/modules/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'modules',
      operation: 'update',
      description: 'Update module',
    },
    {
      method: 'DELETE',
      path: '/modules/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'modules',
      operation: 'delete',
      description: 'Delete module',
    },
    {
      method: 'PUT',
      path: '/courses/:courseId/modules/reorder',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'modules',
      description: 'Reorder modules',
    },

    // Lesson routes
    {
      method: 'GET',
      path: '/modules/:moduleId/lessons',
      auth: false,
      handler: 'crud',
      entity: 'lessons',
      operation: 'list',
      description: 'List module lessons',
    },
    {
      method: 'POST',
      path: '/modules/:moduleId/lessons',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'lessons',
      operation: 'create',
      description: 'Add lesson to module',
    },
    {
      method: 'GET',
      path: '/lessons/:id',
      auth: true,
      handler: 'crud',
      entity: 'lessons',
      operation: 'get',
      description: 'Get lesson details',
    },
    {
      method: 'PUT',
      path: '/lessons/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'lessons',
      operation: 'update',
      description: 'Update lesson',
    },
    {
      method: 'DELETE',
      path: '/lessons/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'lessons',
      operation: 'delete',
      description: 'Delete lesson',
    },
    {
      method: 'PUT',
      path: '/modules/:moduleId/lessons/reorder',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'lessons',
      description: 'Reorder lessons',
    },

    // Content routes
    {
      method: 'GET',
      path: '/lessons/:lessonId/content',
      auth: true,
      handler: 'crud',
      entity: 'course_content',
      operation: 'list',
      description: 'Get lesson content blocks',
    },
    {
      method: 'POST',
      path: '/lessons/:lessonId/content',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'course_content',
      operation: 'create',
      description: 'Add content block',
    },
    {
      method: 'PUT',
      path: '/content/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'course_content',
      operation: 'update',
      description: 'Update content block',
    },
    {
      method: 'DELETE',
      path: '/content/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'course_content',
      operation: 'delete',
      description: 'Delete content block',
    },

    // Category routes
    {
      method: 'GET',
      path: '/course-categories',
      auth: false,
      handler: 'crud',
      entity: 'course_categories',
      operation: 'list',
      description: 'List course categories',
    },
    {
      method: 'POST',
      path: '/course-categories',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'course_categories',
      operation: 'create',
      description: 'Create category',
    },

    // Publish/Unpublish
    {
      method: 'POST',
      path: '/courses/:id/publish',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'courses',
      description: 'Publish course',
    },
    {
      method: 'POST',
      path: '/courses/:id/unpublish',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'courses',
      description: 'Unpublish course',
    },

    // Clone/Duplicate
    {
      method: 'POST',
      path: '/courses/:id/clone',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'courses',
      description: 'Clone/duplicate course',
    },
  ],

  config: [
    {
      key: 'allowDraftPreview',
      label: 'Allow Draft Preview',
      type: 'boolean',
      default: true,
      description: 'Allow instructors to preview draft courses',
    },
    {
      key: 'requireApproval',
      label: 'Require Admin Approval',
      type: 'boolean',
      default: false,
      description: 'Require admin approval before publishing courses',
    },
    {
      key: 'maxModulesPerCourse',
      label: 'Max Modules per Course',
      type: 'number',
      default: 50,
      description: 'Maximum number of modules allowed per course',
    },
    {
      key: 'maxLessonsPerModule',
      label: 'Max Lessons per Module',
      type: 'number',
      default: 30,
      description: 'Maximum number of lessons allowed per module',
    },
    {
      key: 'enablePrerequisites',
      label: 'Enable Prerequisites',
      type: 'boolean',
      default: true,
      description: 'Enable course prerequisite requirements',
    },
    {
      key: 'defaultCourseVisibility',
      label: 'Default Course Visibility',
      type: 'select',
      default: 'draft',
      options: [
        { value: 'draft', label: 'Draft' },
        { value: 'published', label: 'Published' },
        { value: 'private', label: 'Private' },
      ],
      description: 'Default visibility for new courses',
    },
  ],
};
