/**
 * Enrollment Feature Definition
 *
 * Student enrollment and registration system for educational institutions.
 * Includes course selection, waitlists, schedule building, and payment processing.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const ENROLLMENT_FEATURE: FeatureDefinition = {
  id: 'enrollment',
  name: 'Enrollment & Registration',
  category: 'business',
  description: 'Manage student enrollment, course registration, and waitlists',
  icon: 'clipboard-list',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'enrollment',
    'enroll',
    'registration',
    'register',
    'sign up',
    'course registration',
    'class registration',
    'waitlist',
    'drop',
    'add',
    'drop/add',
    'schedule builder',
    'course selection',
    'class selection',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'course-management'],
  conflicts: [],

  pages: [
    {
      id: 'enrollment-wizard',
      route: '/enroll',
      section: 'frontend',
      title: 'Enroll in Courses',
      authRequired: true,
      templateId: 'enrollment-wizard',
      components: [
        'enrollment-steps',
        'course-search',
        'course-catalog',
        'schedule-preview',
        'enrollment-cart',
        'checkout-button',
      ],
      layout: 'default',
    },
    {
      id: 'class-selection',
      route: '/enroll/courses',
      section: 'frontend',
      title: 'Select Courses',
      authRequired: true,
      templateId: 'class-selection',
      components: [
        'course-search',
        'course-filters',
        'course-list',
        'course-card',
        'section-selector',
        'add-to-cart',
        'prerequisites-check',
      ],
      layout: 'default',
    },
    {
      id: 'schedule-builder',
      route: '/enroll/schedule',
      section: 'frontend',
      title: 'Build Schedule',
      authRequired: true,
      templateId: 'schedule-builder',
      components: [
        'schedule-grid',
        'conflict-checker',
        'time-block-view',
        'selected-courses',
        'alternative-sections',
        'schedule-optimizer',
      ],
      layout: 'default',
    },
    {
      id: 'waitlist-manager',
      route: '/enroll/waitlist',
      section: 'frontend',
      title: 'My Waitlists',
      authRequired: true,
      templateId: 'waitlist-manager',
      components: [
        'waitlist-courses',
        'position-display',
        'notification-toggle',
        'remove-waitlist',
        'auto-enroll-toggle',
      ],
      layout: 'default',
    },
    {
      id: 'drop-add',
      route: '/enroll/modify',
      section: 'frontend',
      title: 'Modify Enrollment',
      authRequired: true,
      templateId: 'drop-add',
      components: [
        'current-courses',
        'drop-course-button',
        'add-course-search',
        'swap-course',
        'deadline-warning',
        'refund-calculator',
      ],
      layout: 'default',
    },
    {
      id: 'enrollment-payment',
      route: '/enroll/payment',
      section: 'frontend',
      title: 'Complete Enrollment',
      authRequired: true,
      templateId: 'enrollment-payment',
      components: [
        'enrollment-summary',
        'tuition-breakdown',
        'payment-form',
        'financial-aid',
        'payment-plan',
        'submit-enrollment',
      ],
      layout: 'default',
    },
    {
      id: 'my-enrollments',
      route: '/my-enrollments',
      section: 'frontend',
      title: 'My Enrollments',
      authRequired: true,
      templateId: 'my-enrollments',
      components: [
        'current-enrollments',
        'enrollment-history',
        'upcoming-terms',
        'enrollment-status',
        'print-schedule',
      ],
      layout: 'default',
    },
    {
      id: 'admin-enrollments',
      route: '/admin/enrollments',
      section: 'admin',
      title: 'Manage Enrollments',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-enrollments',
      components: [
        'enrollments-table',
        'enrollment-filters',
        'manual-enroll',
        'bulk-enroll',
        'export-enrollments',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-registration-periods',
      route: '/admin/registration-periods',
      section: 'admin',
      title: 'Registration Periods',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-registration-periods',
      components: [
        'periods-list',
        'period-editor',
        'open-registration',
        'close-registration',
        'priority-groups',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-waitlists',
      route: '/admin/waitlists',
      section: 'admin',
      title: 'Manage Waitlists',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-waitlists',
      components: [
        'waitlists-table',
        'waitlist-details',
        'process-waitlist',
        'clear-waitlist',
        'capacity-override',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Enrollment wizard
    'enrollment-steps',
    'course-search',
    'course-catalog',
    'schedule-preview',
    'enrollment-cart',
    'checkout-button',

    // Course selection
    'course-filters',
    'course-list',
    'course-card',
    'section-selector',
    'add-to-cart',
    'prerequisites-check',

    // Schedule builder
    'schedule-grid',
    'conflict-checker',
    'time-block-view',
    'selected-courses',
    'alternative-sections',
    'schedule-optimizer',

    // Waitlist
    'waitlist-courses',
    'position-display',
    'notification-toggle',
    'remove-waitlist',
    'auto-enroll-toggle',

    // Drop/Add
    'current-courses',
    'drop-course-button',
    'add-course-search',
    'swap-course',
    'deadline-warning',
    'refund-calculator',

    // Payment
    'enrollment-summary',
    'tuition-breakdown',
    'payment-form',
    'financial-aid',
    'payment-plan',
    'submit-enrollment',

    // My enrollments
    'current-enrollments',
    'enrollment-history',
    'upcoming-terms',
    'enrollment-status',
    'print-schedule',

    // Admin components
    'enrollments-table',
    'enrollment-filters',
    'manual-enroll',
    'bulk-enroll',
    'export-enrollments',

    // Registration periods
    'periods-list',
    'period-editor',
    'open-registration',
    'close-registration',
    'priority-groups',

    // Waitlist management
    'waitlists-table',
    'waitlist-details',
    'process-waitlist',
    'clear-waitlist',
    'capacity-override',
  ],

  entities: [
    {
      name: 'enrollments',
      displayName: 'Enrollments',
      description: 'Student course enrollments',
      isCore: true,
    },
    {
      name: 'waitlists',
      displayName: 'Waitlists',
      description: 'Course waitlist entries',
      isCore: true,
    },
    {
      name: 'registration_periods',
      displayName: 'Registration Periods',
      description: 'Open registration periods and deadlines',
      isCore: true,
    },
    {
      name: 'course_sections',
      displayName: 'Course Sections',
      description: 'Individual class sections',
      isCore: true,
    },
    {
      name: 'enrollment_carts',
      displayName: 'Enrollment Carts',
      description: 'Shopping cart for course registration',
      isCore: false,
    },
    {
      name: 'enrollment_history',
      displayName: 'Enrollment History',
      description: 'Historical enrollment changes',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Enrollment CRUD
    {
      method: 'GET',
      path: '/enrollments',
      auth: true,
      handler: 'crud',
      entity: 'enrollments',
      operation: 'list',
      description: 'Get user enrollments',
    },
    {
      method: 'GET',
      path: '/enrollments/:id',
      auth: true,
      handler: 'crud',
      entity: 'enrollments',
      operation: 'get',
      description: 'Get enrollment details',
    },
    {
      method: 'POST',
      path: '/enrollments',
      auth: true,
      handler: 'crud',
      entity: 'enrollments',
      operation: 'create',
      description: 'Create enrollment',
    },
    {
      method: 'DELETE',
      path: '/enrollments/:id',
      auth: true,
      handler: 'crud',
      entity: 'enrollments',
      operation: 'delete',
      description: 'Drop enrollment',
    },

    // Course sections
    {
      method: 'GET',
      path: '/courses/:courseId/sections',
      auth: false,
      handler: 'crud',
      entity: 'course_sections',
      operation: 'list',
      description: 'Get course sections',
    },
    {
      method: 'GET',
      path: '/sections/:id',
      auth: false,
      handler: 'crud',
      entity: 'course_sections',
      operation: 'get',
      description: 'Get section details',
    },
    {
      method: 'GET',
      path: '/sections/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'course_sections',
      description: 'Check section availability',
    },

    // Enroll in course
    {
      method: 'POST',
      path: '/sections/:sectionId/enroll',
      auth: true,
      handler: 'custom',
      entity: 'enrollments',
      description: 'Enroll in section',
    },
    {
      method: 'POST',
      path: '/sections/:sectionId/drop',
      auth: true,
      handler: 'custom',
      entity: 'enrollments',
      description: 'Drop from section',
    },
    {
      method: 'POST',
      path: '/sections/swap',
      auth: true,
      handler: 'custom',
      entity: 'enrollments',
      description: 'Swap sections',
    },

    // Enrollment cart
    {
      method: 'GET',
      path: '/enrollment-cart',
      auth: true,
      handler: 'crud',
      entity: 'enrollment_carts',
      operation: 'get',
      description: 'Get enrollment cart',
    },
    {
      method: 'POST',
      path: '/enrollment-cart/add',
      auth: true,
      handler: 'custom',
      entity: 'enrollment_carts',
      description: 'Add to cart',
    },
    {
      method: 'DELETE',
      path: '/enrollment-cart/:itemId',
      auth: true,
      handler: 'custom',
      entity: 'enrollment_carts',
      description: 'Remove from cart',
    },
    {
      method: 'POST',
      path: '/enrollment-cart/checkout',
      auth: true,
      handler: 'custom',
      entity: 'enrollment_carts',
      description: 'Complete enrollment',
    },

    // Waitlist
    {
      method: 'GET',
      path: '/waitlists',
      auth: true,
      handler: 'crud',
      entity: 'waitlists',
      operation: 'list',
      description: 'Get user waitlists',
    },
    {
      method: 'POST',
      path: '/sections/:sectionId/waitlist',
      auth: true,
      handler: 'custom',
      entity: 'waitlists',
      description: 'Join waitlist',
    },
    {
      method: 'DELETE',
      path: '/waitlists/:id',
      auth: true,
      handler: 'crud',
      entity: 'waitlists',
      operation: 'delete',
      description: 'Leave waitlist',
    },
    {
      method: 'GET',
      path: '/waitlists/:id/position',
      auth: true,
      handler: 'custom',
      entity: 'waitlists',
      description: 'Get waitlist position',
    },

    // Schedule
    {
      method: 'GET',
      path: '/my-schedule',
      auth: true,
      handler: 'custom',
      entity: 'enrollments',
      description: 'Get current schedule',
    },
    {
      method: 'POST',
      path: '/schedule/check-conflicts',
      auth: true,
      handler: 'custom',
      entity: 'course_sections',
      description: 'Check schedule conflicts',
    },
    {
      method: 'POST',
      path: '/schedule/optimize',
      auth: true,
      handler: 'custom',
      entity: 'course_sections',
      description: 'Suggest optimal schedule',
    },

    // Prerequisites
    {
      method: 'GET',
      path: '/courses/:courseId/prerequisites-check',
      auth: true,
      handler: 'custom',
      entity: 'enrollments',
      description: 'Check prerequisites',
    },

    // Registration periods
    {
      method: 'GET',
      path: '/registration-periods',
      auth: true,
      handler: 'crud',
      entity: 'registration_periods',
      operation: 'list',
      description: 'Get registration periods',
    },
    {
      method: 'GET',
      path: '/registration-periods/current',
      auth: true,
      handler: 'custom',
      entity: 'registration_periods',
      description: 'Get current registration period',
    },
    {
      method: 'POST',
      path: '/registration-periods',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'registration_periods',
      operation: 'create',
      description: 'Create registration period',
    },
    {
      method: 'PUT',
      path: '/registration-periods/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'registration_periods',
      operation: 'update',
      description: 'Update registration period',
    },

    // Admin enrollments
    {
      method: 'GET',
      path: '/admin/enrollments',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'enrollments',
      operation: 'list',
      description: 'List all enrollments',
    },
    {
      method: 'POST',
      path: '/admin/enrollments/manual',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'enrollments',
      description: 'Manually enroll student',
    },
    {
      method: 'POST',
      path: '/admin/enrollments/batch',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'enrollments',
      description: 'Batch enroll students',
    },
    {
      method: 'POST',
      path: '/admin/sections/:sectionId/capacity',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'course_sections',
      description: 'Override section capacity',
    },

    // Admin waitlists
    {
      method: 'GET',
      path: '/admin/waitlists',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'waitlists',
      operation: 'list',
      description: 'List all waitlists',
    },
    {
      method: 'POST',
      path: '/admin/waitlists/:id/process',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'waitlists',
      description: 'Process waitlist entry',
    },
    {
      method: 'DELETE',
      path: '/admin/sections/:sectionId/waitlist',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'waitlists',
      description: 'Clear section waitlist',
    },

    // Export
    {
      method: 'GET',
      path: '/admin/enrollments/export',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'enrollments',
      description: 'Export enrollment data',
    },
  ],

  config: [
    {
      key: 'enableSelfEnrollment',
      label: 'Enable Self-Enrollment',
      type: 'boolean',
      default: true,
      description: 'Allow students to self-enroll in courses',
    },
    {
      key: 'requirePayment',
      label: 'Require Payment at Registration',
      type: 'boolean',
      default: false,
      description: 'Require payment to complete enrollment',
    },
    {
      key: 'enableWaitlist',
      label: 'Enable Waitlists',
      type: 'boolean',
      default: true,
      description: 'Allow students to join waitlists for full courses',
    },
    {
      key: 'maxWaitlistSize',
      label: 'Max Waitlist Size',
      type: 'number',
      default: 20,
      description: 'Maximum students per waitlist (0 = unlimited)',
    },
    {
      key: 'autoEnrollFromWaitlist',
      label: 'Auto-Enroll from Waitlist',
      type: 'boolean',
      default: true,
      description: 'Automatically enroll when spot opens',
    },
    {
      key: 'waitlistExpiry',
      label: 'Waitlist Offer Expiry (hours)',
      type: 'number',
      default: 24,
      description: 'Hours to accept waitlist spot before it expires',
    },
    {
      key: 'enforcePrerequisites',
      label: 'Enforce Prerequisites',
      type: 'boolean',
      default: true,
      description: 'Block enrollment without prerequisites',
    },
    {
      key: 'maxCreditsPerTerm',
      label: 'Max Credits Per Term',
      type: 'number',
      default: 18,
      description: 'Maximum credits allowed per term',
    },
    {
      key: 'allowOverload',
      label: 'Allow Credit Overload',
      type: 'boolean',
      default: false,
      description: 'Allow exceeding max credits with approval',
    },
    {
      key: 'dropDeadlineDays',
      label: 'Drop Deadline (days)',
      type: 'number',
      default: 14,
      description: 'Days after start for full refund drop',
    },
    {
      key: 'lateDropPenalty',
      label: 'Late Drop Penalty (%)',
      type: 'number',
      default: 25,
      description: 'Percentage penalty for late drops',
    },
    {
      key: 'enableScheduleBuilder',
      label: 'Enable Schedule Builder',
      type: 'boolean',
      default: true,
      description: 'Enable visual schedule building tool',
    },
  ],
};
