/**
 * Grading Feature Definition
 *
 * Complete grade management and reporting functionality for educational
 * institutions. Includes gradebook, rubrics, GPA calculation, and
 * grade distribution analytics.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const GRADING_FEATURE: FeatureDefinition = {
  id: 'grading',
  name: 'Grading',
  category: 'business',
  description: 'Manage grades, rubrics, GPA calculations, and grade reports',
  icon: 'clipboard-check',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'grade',
    'grades',
    'grading',
    'gradebook',
    'grade book',
    'gpa',
    'marks',
    'scoring',
    'rubric',
    'rubrics',
    'assessment',
    'grade report',
    'report card',
    'grade distribution',
    'academic performance',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'course-management', 'student-records'],
  conflicts: [],

  pages: [
    {
      id: 'gradebook',
      route: '/admin/gradebook',
      section: 'admin',
      title: 'Gradebook',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'gradebook',
      components: [
        'grade-table',
        'course-selector',
        'student-column',
        'assignment-columns',
        'grade-cell',
        'grade-totals',
        'export-grades',
      ],
      layout: 'admin',
    },
    {
      id: 'grade-entry',
      route: '/admin/grades/entry',
      section: 'admin',
      title: 'Enter Grades',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'grade-entry',
      components: [
        'grade-form',
        'student-selector',
        'assignment-selector',
        'score-input',
        'feedback-input',
        'batch-entry',
      ],
      layout: 'admin',
    },
    {
      id: 'grade-reports',
      route: '/admin/grades/reports',
      section: 'admin',
      title: 'Grade Reports',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'grade-reports',
      components: [
        'report-generator',
        'class-average',
        'grade-distribution',
        'performance-trends',
        'export-reports',
      ],
      layout: 'admin',
    },
    {
      id: 'gpa-calculator',
      route: '/gpa-calculator',
      section: 'frontend',
      title: 'GPA Calculator',
      authRequired: false,
      templateId: 'gpa-calculator',
      components: [
        'gpa-form',
        'course-input',
        'credits-input',
        'grade-input',
        'gpa-result',
        'gpa-scale-reference',
      ],
      layout: 'default',
    },
    {
      id: 'my-grades',
      route: '/my-grades',
      section: 'frontend',
      title: 'My Grades',
      authRequired: true,
      templateId: 'my-grades',
      components: [
        'grade-summary',
        'course-grades',
        'gpa-display',
        'grade-history',
        'grade-chart',
      ],
      layout: 'default',
    },
    {
      id: 'rubric-editor',
      route: '/admin/rubrics/:id',
      section: 'admin',
      title: 'Edit Rubric',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'rubric-editor',
      components: [
        'rubric-builder',
        'criteria-editor',
        'level-editor',
        'points-config',
        'rubric-preview',
      ],
      layout: 'admin',
    },
    {
      id: 'rubrics-list',
      route: '/admin/rubrics',
      section: 'admin',
      title: 'Rubrics',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'rubrics-list',
      components: [
        'rubrics-table',
        'rubric-card',
        'create-rubric-button',
        'rubric-filters',
      ],
      layout: 'admin',
    },
    {
      id: 'grade-scales',
      route: '/admin/grade-scales',
      section: 'admin',
      title: 'Grade Scales',
      authRequired: true,
      roles: ['admin'],
      templateId: 'grade-scales',
      components: [
        'scale-list',
        'scale-editor',
        'grade-mapping',
        'gpa-points',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Gradebook components
    'grade-table',
    'course-selector',
    'student-column',
    'assignment-columns',
    'grade-cell',
    'grade-totals',
    'export-grades',

    // Grade entry components
    'grade-form',
    'student-selector',
    'assignment-selector',
    'score-input',
    'feedback-input',
    'batch-entry',

    // Report components
    'report-generator',
    'class-average',
    'grade-distribution',
    'performance-trends',
    'export-reports',

    // GPA components
    'gpa-form',
    'course-input',
    'credits-input',
    'grade-input',
    'gpa-result',
    'gpa-display',
    'gpa-scale-reference',

    // Student grade view
    'grade-summary',
    'course-grades',
    'grade-history',
    'grade-chart',

    // Rubric components
    'rubric-builder',
    'rubric-editor',
    'criteria-editor',
    'level-editor',
    'points-config',
    'rubric-preview',
    'rubrics-table',
    'rubric-card',
    'rubric-filters',
    'create-rubric-button',

    // Grade scale components
    'scale-list',
    'scale-editor',
    'grade-mapping',
    'gpa-points',
  ],

  entities: [
    {
      name: 'grades',
      displayName: 'Grades',
      description: 'Individual grade records',
      isCore: true,
    },
    {
      name: 'grade_scales',
      displayName: 'Grade Scales',
      description: 'Grading scale definitions (A-F, percentage, etc.)',
      isCore: true,
    },
    {
      name: 'rubrics',
      displayName: 'Rubrics',
      description: 'Grading rubric definitions',
      isCore: true,
    },
    {
      name: 'rubric_criteria',
      displayName: 'Rubric Criteria',
      description: 'Individual criteria within rubrics',
      isCore: false,
    },
    {
      name: 'grade_reports',
      displayName: 'Grade Reports',
      description: 'Generated grade reports and report cards',
      isCore: false,
    },
    {
      name: 'grade_comments',
      displayName: 'Grade Comments',
      description: 'Instructor comments on grades',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Grade CRUD
    {
      method: 'GET',
      path: '/grades',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'grades',
      operation: 'list',
      description: 'List grades with filters',
    },
    {
      method: 'GET',
      path: '/grades/:id',
      auth: true,
      handler: 'crud',
      entity: 'grades',
      operation: 'get',
      description: 'Get grade details',
    },
    {
      method: 'POST',
      path: '/grades',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'grades',
      operation: 'create',
      description: 'Create grade entry',
    },
    {
      method: 'PUT',
      path: '/grades/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'grades',
      operation: 'update',
      description: 'Update grade',
    },
    {
      method: 'DELETE',
      path: '/grades/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'grades',
      operation: 'delete',
      description: 'Delete grade',
    },

    // Batch operations
    {
      method: 'POST',
      path: '/grades/batch',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'grades',
      description: 'Batch create/update grades',
    },
    {
      method: 'POST',
      path: '/grades/import',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'grades',
      description: 'Import grades from file',
    },

    // Gradebook views
    {
      method: 'GET',
      path: '/gradebook/:courseId',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'grades',
      description: 'Get full gradebook for course',
    },
    {
      method: 'GET',
      path: '/students/:studentId/grades',
      auth: true,
      handler: 'crud',
      entity: 'grades',
      operation: 'list',
      description: 'Get student grades',
    },

    // GPA
    {
      method: 'GET',
      path: '/students/:studentId/gpa',
      auth: true,
      handler: 'aggregate',
      entity: 'grades',
      description: 'Calculate student GPA',
    },
    {
      method: 'POST',
      path: '/gpa/calculate',
      auth: false,
      handler: 'custom',
      entity: 'grades',
      description: 'Calculate GPA from input',
    },

    // Rubrics
    {
      method: 'GET',
      path: '/rubrics',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'rubrics',
      operation: 'list',
      description: 'List rubrics',
    },
    {
      method: 'GET',
      path: '/rubrics/:id',
      auth: true,
      handler: 'crud',
      entity: 'rubrics',
      operation: 'get',
      description: 'Get rubric details',
    },
    {
      method: 'POST',
      path: '/rubrics',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'rubrics',
      operation: 'create',
      description: 'Create rubric',
    },
    {
      method: 'PUT',
      path: '/rubrics/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'rubrics',
      operation: 'update',
      description: 'Update rubric',
    },
    {
      method: 'DELETE',
      path: '/rubrics/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'rubrics',
      operation: 'delete',
      description: 'Delete rubric',
    },
    {
      method: 'POST',
      path: '/rubrics/:id/clone',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'rubrics',
      description: 'Clone rubric',
    },

    // Grade scales
    {
      method: 'GET',
      path: '/grade-scales',
      auth: true,
      handler: 'crud',
      entity: 'grade_scales',
      operation: 'list',
      description: 'List grade scales',
    },
    {
      method: 'POST',
      path: '/grade-scales',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'grade_scales',
      operation: 'create',
      description: 'Create grade scale',
    },
    {
      method: 'PUT',
      path: '/grade-scales/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'grade_scales',
      operation: 'update',
      description: 'Update grade scale',
    },

    // Reports
    {
      method: 'GET',
      path: '/grade-reports',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'grade_reports',
      operation: 'list',
      description: 'List grade reports',
    },
    {
      method: 'POST',
      path: '/grade-reports/generate',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'grade_reports',
      description: 'Generate grade report',
    },
    {
      method: 'GET',
      path: '/courses/:courseId/grade-distribution',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'grades',
      description: 'Get grade distribution',
    },
    {
      method: 'GET',
      path: '/courses/:courseId/class-average',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'grades',
      description: 'Get class average',
    },

    // Export
    {
      method: 'GET',
      path: '/gradebook/:courseId/export',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'grades',
      description: 'Export gradebook',
    },
  ],

  config: [
    {
      key: 'defaultGradeScale',
      label: 'Default Grade Scale',
      type: 'select',
      default: 'letter',
      options: [
        { value: 'letter', label: 'Letter Grades (A-F)' },
        { value: 'percentage', label: 'Percentage (0-100)' },
        { value: 'points', label: 'Points' },
        { value: 'passfail', label: 'Pass/Fail' },
      ],
      description: 'Default grading scale for new courses',
    },
    {
      key: 'gpaScale',
      label: 'GPA Scale',
      type: 'select',
      default: '4.0',
      options: [
        { value: '4.0', label: '4.0 Scale' },
        { value: '5.0', label: '5.0 Scale' },
        { value: '10.0', label: '10.0 Scale' },
        { value: '100', label: '100 Point Scale' },
      ],
      description: 'GPA calculation scale',
    },
    {
      key: 'allowGradeDecimals',
      label: 'Allow Decimal Grades',
      type: 'boolean',
      default: true,
      description: 'Allow decimal values in grades',
    },
    {
      key: 'gradeReleaseMode',
      label: 'Grade Release Mode',
      type: 'select',
      default: 'immediate',
      options: [
        { value: 'immediate', label: 'Immediate' },
        { value: 'manual', label: 'Manual Release' },
        { value: 'scheduled', label: 'Scheduled Release' },
      ],
      description: 'When grades become visible to students',
    },
    {
      key: 'enableWeightedGrades',
      label: 'Enable Weighted Grades',
      type: 'boolean',
      default: true,
      description: 'Allow assignment categories with different weights',
    },
    {
      key: 'enableCurving',
      label: 'Enable Grade Curving',
      type: 'boolean',
      default: false,
      description: 'Allow instructors to curve grades',
    },
    {
      key: 'showClassRank',
      label: 'Show Class Rank',
      type: 'boolean',
      default: false,
      description: 'Display class rank to students',
    },
    {
      key: 'enableExtraCredit',
      label: 'Enable Extra Credit',
      type: 'boolean',
      default: true,
      description: 'Allow extra credit assignments',
    },
  ],
};
