/**
 * LMS (Learning Management System) Feature Definition
 *
 * Core learning management functionality including course player,
 * progress tracking, quizzes, and certificate generation.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const LMS_FEATURE: FeatureDefinition = {
  id: 'lms',
  name: 'Learning Management System',
  category: 'content',
  description: 'Interactive course player, progress tracking, quizzes, and certificates',
  icon: 'graduation-cap',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'lms',
    'learning management',
    'learning platform',
    'e-learning',
    'elearning',
    'online learning',
    'course player',
    'video course',
    'progress tracking',
    'learning progress',
    'quiz',
    'quizzes',
    'certificate',
    'certificates',
    'completion',
    'online course',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'course-management'],
  conflicts: [],

  pages: [
    {
      id: 'learning-dashboard',
      route: '/learn',
      section: 'frontend',
      title: 'My Learning',
      authRequired: true,
      templateId: 'learning-dashboard',
      components: [
        'enrolled-courses',
        'continue-learning',
        'progress-overview',
        'recent-activity',
        'upcoming-deadlines',
        'achievements-preview',
      ],
      layout: 'dashboard',
    },
    {
      id: 'course-player',
      route: '/learn/:courseId/:lessonId',
      section: 'frontend',
      title: 'Course Player',
      authRequired: true,
      templateId: 'course-player',
      components: [
        'video-player',
        'lesson-content',
        'lesson-sidebar',
        'progress-bar',
        'next-lesson-button',
        'prev-lesson-button',
        'notes-panel',
        'bookmarks',
        'discussion-panel',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'quiz-page',
      route: '/learn/:courseId/quiz/:quizId',
      section: 'frontend',
      title: 'Quiz',
      authRequired: true,
      templateId: 'quiz-page',
      components: [
        'quiz-engine',
        'question-display',
        'answer-options',
        'quiz-timer',
        'progress-indicator',
        'submit-button',
        'quiz-navigation',
      ],
      layout: 'centered',
    },
    {
      id: 'quiz-results',
      route: '/learn/:courseId/quiz/:quizId/results',
      section: 'frontend',
      title: 'Quiz Results',
      authRequired: true,
      templateId: 'quiz-results',
      components: [
        'score-display',
        'answers-review',
        'correct-answers',
        'retry-button',
        'continue-button',
      ],
      layout: 'default',
    },
    {
      id: 'progress-tracker',
      route: '/learn/:courseId/progress',
      section: 'frontend',
      title: 'Course Progress',
      authRequired: true,
      templateId: 'progress-tracker',
      components: [
        'progress-overview',
        'module-progress',
        'lesson-checklist',
        'time-spent',
        'completion-estimate',
        'achievements-earned',
      ],
      layout: 'default',
    },
    {
      id: 'certificates',
      route: '/certificates',
      section: 'frontend',
      title: 'My Certificates',
      authRequired: true,
      templateId: 'certificates',
      components: [
        'certificates-grid',
        'certificate-card',
        'download-button',
        'share-button',
        'linkedin-add',
      ],
      layout: 'default',
    },
    {
      id: 'certificate-view',
      route: '/certificates/:id',
      section: 'frontend',
      title: 'Certificate',
      authRequired: true,
      templateId: 'certificate-view',
      components: [
        'certificate-viewer',
        'certificate-details',
        'verification-code',
        'download-button',
        'share-buttons',
        'print-button',
      ],
      layout: 'centered',
    },
    {
      id: 'admin-quiz-builder',
      route: '/admin/courses/:courseId/quizzes/new',
      section: 'admin',
      title: 'Create Quiz',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'quiz-builder',
      components: [
        'quiz-form',
        'question-builder',
        'answer-editor',
        'quiz-settings',
        'question-bank',
        'preview-button',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-progress-reports',
      route: '/admin/courses/:courseId/progress',
      section: 'admin',
      title: 'Student Progress',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'admin-progress-reports',
      components: [
        'progress-table',
        'completion-stats',
        'engagement-metrics',
        'dropout-analysis',
        'export-progress',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Learning dashboard
    'enrolled-courses',
    'continue-learning',
    'progress-overview',
    'recent-activity',
    'upcoming-deadlines',
    'achievements-preview',

    // Course player
    'video-player',
    'lesson-content',
    'lesson-sidebar',
    'progress-bar',
    'next-lesson-button',
    'prev-lesson-button',
    'notes-panel',
    'bookmarks',
    'discussion-panel',

    // Quiz components
    'quiz-engine',
    'question-display',
    'answer-options',
    'quiz-timer',
    'progress-indicator',
    'submit-button',
    'quiz-navigation',
    'score-display',
    'answers-review',
    'correct-answers',
    'retry-button',
    'continue-button',

    // Quiz builder
    'quiz-form',
    'question-builder',
    'answer-editor',
    'quiz-settings',
    'question-bank',
    'preview-button',

    // Progress components
    'module-progress',
    'lesson-checklist',
    'time-spent',
    'completion-estimate',
    'achievements-earned',

    // Certificate components
    'certificates-grid',
    'certificate-card',
    'certificate-viewer',
    'certificate-details',
    'verification-code',
    'download-button',
    'share-button',
    'share-buttons',
    'linkedin-add',
    'print-button',

    // Admin components
    'progress-table',
    'completion-stats',
    'engagement-metrics',
    'dropout-analysis',
    'export-progress',
  ],

  entities: [
    {
      name: 'enrollments',
      displayName: 'Enrollments',
      description: 'Student course enrollments',
      isCore: true,
    },
    {
      name: 'progress',
      displayName: 'Progress',
      description: 'Lesson and module completion progress',
      isCore: true,
    },
    {
      name: 'completions',
      displayName: 'Completions',
      description: 'Course completion records',
      isCore: true,
    },
    {
      name: 'certificates',
      displayName: 'Certificates',
      description: 'Earned certificates',
      isCore: true,
    },
    {
      name: 'quizzes',
      displayName: 'Quizzes',
      description: 'Quiz definitions',
      isCore: true,
    },
    {
      name: 'quiz_questions',
      displayName: 'Quiz Questions',
      description: 'Questions within quizzes',
      isCore: true,
    },
    {
      name: 'quiz_attempts',
      displayName: 'Quiz Attempts',
      description: 'Student quiz attempts and scores',
      isCore: true,
    },
    {
      name: 'learning_notes',
      displayName: 'Learning Notes',
      description: 'Student notes on lessons',
      isCore: false,
    },
    {
      name: 'bookmarks',
      displayName: 'Bookmarks',
      description: 'Saved lesson bookmarks',
      isCore: false,
    },
    {
      name: 'watch_history',
      displayName: 'Watch History',
      description: 'Video watch progress',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Enrollments
    {
      method: 'GET',
      path: '/enrollments',
      auth: true,
      handler: 'crud',
      entity: 'enrollments',
      operation: 'list',
      description: 'Get user enrollments',
    },
    {
      method: 'POST',
      path: '/courses/:courseId/enroll',
      auth: true,
      handler: 'custom',
      entity: 'enrollments',
      description: 'Enroll in course',
    },
    {
      method: 'DELETE',
      path: '/enrollments/:id',
      auth: true,
      handler: 'crud',
      entity: 'enrollments',
      operation: 'delete',
      description: 'Unenroll from course',
    },
    {
      method: 'GET',
      path: '/courses/:courseId/enrollment',
      auth: true,
      handler: 'custom',
      entity: 'enrollments',
      description: 'Get enrollment status',
    },

    // Progress
    {
      method: 'GET',
      path: '/courses/:courseId/progress',
      auth: true,
      handler: 'aggregate',
      entity: 'progress',
      description: 'Get course progress',
    },
    {
      method: 'POST',
      path: '/lessons/:lessonId/complete',
      auth: true,
      handler: 'custom',
      entity: 'progress',
      description: 'Mark lesson complete',
    },
    {
      method: 'POST',
      path: '/lessons/:lessonId/progress',
      auth: true,
      handler: 'custom',
      entity: 'progress',
      description: 'Update lesson progress',
    },
    {
      method: 'GET',
      path: '/learn/continue',
      auth: true,
      handler: 'custom',
      entity: 'progress',
      description: 'Get continue learning data',
    },

    // Video progress
    {
      method: 'POST',
      path: '/lessons/:lessonId/watch-progress',
      auth: true,
      handler: 'custom',
      entity: 'watch_history',
      description: 'Update video watch progress',
    },
    {
      method: 'GET',
      path: '/lessons/:lessonId/watch-progress',
      auth: true,
      handler: 'custom',
      entity: 'watch_history',
      description: 'Get video watch progress',
    },

    // Quizzes
    {
      method: 'GET',
      path: '/courses/:courseId/quizzes',
      auth: true,
      handler: 'crud',
      entity: 'quizzes',
      operation: 'list',
      description: 'List course quizzes',
    },
    {
      method: 'GET',
      path: '/quizzes/:id',
      auth: true,
      handler: 'crud',
      entity: 'quizzes',
      operation: 'get',
      description: 'Get quiz details',
    },
    {
      method: 'POST',
      path: '/quizzes',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'quizzes',
      operation: 'create',
      description: 'Create quiz',
    },
    {
      method: 'PUT',
      path: '/quizzes/:id',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'quizzes',
      operation: 'update',
      description: 'Update quiz',
    },
    {
      method: 'DELETE',
      path: '/quizzes/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'quizzes',
      operation: 'delete',
      description: 'Delete quiz',
    },

    // Quiz attempts
    {
      method: 'POST',
      path: '/quizzes/:id/start',
      auth: true,
      handler: 'custom',
      entity: 'quiz_attempts',
      description: 'Start quiz attempt',
    },
    {
      method: 'POST',
      path: '/quiz-attempts/:id/submit',
      auth: true,
      handler: 'custom',
      entity: 'quiz_attempts',
      description: 'Submit quiz attempt',
    },
    {
      method: 'GET',
      path: '/quiz-attempts/:id',
      auth: true,
      handler: 'crud',
      entity: 'quiz_attempts',
      operation: 'get',
      description: 'Get quiz attempt results',
    },
    {
      method: 'GET',
      path: '/quizzes/:id/attempts',
      auth: true,
      handler: 'crud',
      entity: 'quiz_attempts',
      operation: 'list',
      description: 'Get all attempts for quiz',
    },

    // Certificates
    {
      method: 'GET',
      path: '/certificates',
      auth: true,
      handler: 'crud',
      entity: 'certificates',
      operation: 'list',
      description: 'Get user certificates',
    },
    {
      method: 'GET',
      path: '/certificates/:id',
      auth: true,
      handler: 'crud',
      entity: 'certificates',
      operation: 'get',
      description: 'Get certificate details',
    },
    {
      method: 'GET',
      path: '/certificates/:id/download',
      auth: true,
      handler: 'custom',
      entity: 'certificates',
      description: 'Download certificate PDF',
    },
    {
      method: 'GET',
      path: '/certificates/verify/:code',
      auth: false,
      handler: 'custom',
      entity: 'certificates',
      description: 'Verify certificate',
    },
    {
      method: 'POST',
      path: '/courses/:courseId/generate-certificate',
      auth: true,
      handler: 'custom',
      entity: 'certificates',
      description: 'Generate certificate on completion',
    },

    // Notes
    {
      method: 'GET',
      path: '/lessons/:lessonId/notes',
      auth: true,
      handler: 'crud',
      entity: 'learning_notes',
      operation: 'list',
      description: 'Get lesson notes',
    },
    {
      method: 'POST',
      path: '/lessons/:lessonId/notes',
      auth: true,
      handler: 'crud',
      entity: 'learning_notes',
      operation: 'create',
      description: 'Create note',
    },
    {
      method: 'PUT',
      path: '/notes/:id',
      auth: true,
      handler: 'crud',
      entity: 'learning_notes',
      operation: 'update',
      description: 'Update note',
    },
    {
      method: 'DELETE',
      path: '/notes/:id',
      auth: true,
      handler: 'crud',
      entity: 'learning_notes',
      operation: 'delete',
      description: 'Delete note',
    },

    // Bookmarks
    {
      method: 'GET',
      path: '/bookmarks',
      auth: true,
      handler: 'crud',
      entity: 'bookmarks',
      operation: 'list',
      description: 'Get bookmarks',
    },
    {
      method: 'POST',
      path: '/lessons/:lessonId/bookmark',
      auth: true,
      handler: 'custom',
      entity: 'bookmarks',
      description: 'Add bookmark',
    },
    {
      method: 'DELETE',
      path: '/bookmarks/:id',
      auth: true,
      handler: 'crud',
      entity: 'bookmarks',
      operation: 'delete',
      description: 'Remove bookmark',
    },

    // Admin reports
    {
      method: 'GET',
      path: '/admin/courses/:courseId/progress-report',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'progress',
      description: 'Get course progress report',
    },
    {
      method: 'GET',
      path: '/admin/courses/:courseId/completion-stats',
      auth: true,
      role: 'instructor',
      handler: 'aggregate',
      entity: 'completions',
      description: 'Get completion statistics',
    },
  ],

  config: [
    {
      key: 'autoMarkComplete',
      label: 'Auto-Mark Lessons Complete',
      type: 'boolean',
      default: true,
      description: 'Automatically mark lessons complete when video ends',
    },
    {
      key: 'completionThreshold',
      label: 'Video Completion Threshold (%)',
      type: 'number',
      default: 90,
      description: 'Percentage of video watched to mark complete',
    },
    {
      key: 'enableQuizRetakes',
      label: 'Enable Quiz Retakes',
      type: 'boolean',
      default: true,
      description: 'Allow students to retake quizzes',
    },
    {
      key: 'maxQuizAttempts',
      label: 'Max Quiz Attempts',
      type: 'number',
      default: 3,
      description: 'Maximum quiz attempts (0 = unlimited)',
    },
    {
      key: 'passingScore',
      label: 'Default Passing Score (%)',
      type: 'number',
      default: 70,
      description: 'Default minimum score to pass quizzes',
    },
    {
      key: 'showCorrectAnswers',
      label: 'Show Correct Answers',
      type: 'select',
      default: 'after_submission',
      options: [
        { value: 'never', label: 'Never' },
        { value: 'after_submission', label: 'After Submission' },
        { value: 'after_deadline', label: 'After Deadline' },
        { value: 'after_passing', label: 'After Passing' },
      ],
      description: 'When to show correct answers',
    },
    {
      key: 'enableCertificates',
      label: 'Enable Certificates',
      type: 'boolean',
      default: true,
      description: 'Generate certificates on course completion',
    },
    {
      key: 'certificateRequirements',
      label: 'Certificate Requirements',
      type: 'select',
      default: 'complete_all',
      options: [
        { value: 'complete_all', label: 'Complete All Lessons' },
        { value: 'pass_quizzes', label: 'Pass All Quizzes' },
        { value: 'both', label: 'Both Lessons and Quizzes' },
      ],
      description: 'Requirements to earn certificate',
    },
    {
      key: 'enableNotes',
      label: 'Enable Student Notes',
      type: 'boolean',
      default: true,
      description: 'Allow students to take notes during lessons',
    },
    {
      key: 'enableBookmarks',
      label: 'Enable Bookmarks',
      type: 'boolean',
      default: true,
      description: 'Allow students to bookmark lessons',
    },
    {
      key: 'enableDiscussions',
      label: 'Enable Lesson Discussions',
      type: 'boolean',
      default: true,
      description: 'Enable discussion threads on lessons',
    },
    {
      key: 'videoPlaybackSpeed',
      label: 'Allow Playback Speed Control',
      type: 'boolean',
      default: true,
      description: 'Allow students to change video playback speed',
    },
  ],
};
