/**
 * Parent Portal Feature Definition
 *
 * Communication portal for parents/guardians to monitor student progress,
 * view grades, communicate with teachers, and access report cards.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PARENT_PORTAL_FEATURE: FeatureDefinition = {
  id: 'parent-portal',
  name: 'Parent Portal',
  category: 'communication',
  description: 'Parent/guardian portal for monitoring student progress and communication',
  icon: 'users',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'parent',
    'parents',
    'parent portal',
    'guardian',
    'guardians',
    'family',
    'parent access',
    'parent login',
    'parent communication',
    'parent view',
    'child progress',
    'parent-teacher',
    'family portal',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'student-records'],
  conflicts: [],

  pages: [
    {
      id: 'parent-dashboard',
      route: '/parent',
      section: 'frontend',
      title: 'Parent Dashboard',
      authRequired: true,
      roles: ['parent'],
      templateId: 'parent-dashboard',
      components: [
        'child-selector',
        'child-overview',
        'recent-grades',
        'attendance-summary',
        'upcoming-assignments',
        'recent-messages',
        'announcements',
      ],
      layout: 'dashboard',
    },
    {
      id: 'child-progress',
      route: '/parent/child/:childId/progress',
      section: 'frontend',
      title: 'Child Progress',
      authRequired: true,
      roles: ['parent'],
      templateId: 'child-progress',
      components: [
        'progress-summary',
        'grade-chart',
        'attendance-chart',
        'course-progress',
        'achievement-list',
        'behavior-notes',
      ],
      layout: 'default',
    },
    {
      id: 'parent-messages',
      route: '/parent/messages',
      section: 'frontend',
      title: 'Messages',
      authRequired: true,
      roles: ['parent'],
      templateId: 'parent-messages',
      components: [
        'message-list',
        'message-thread',
        'compose-message',
        'teacher-selector',
        'message-filters',
      ],
      layout: 'default',
    },
    {
      id: 'report-cards',
      route: '/parent/child/:childId/report-cards',
      section: 'frontend',
      title: 'Report Cards',
      authRequired: true,
      roles: ['parent'],
      templateId: 'report-cards',
      components: [
        'report-card-list',
        'grade-view',
        'term-selector',
        'teacher-comments',
        'download-button',
        'signature-pad',
      ],
      layout: 'default',
    },
    {
      id: 'child-attendance',
      route: '/parent/child/:childId/attendance',
      section: 'frontend',
      title: 'Attendance Record',
      authRequired: true,
      roles: ['parent'],
      templateId: 'child-attendance',
      components: [
        'attendance-calendar',
        'attendance-summary',
        'absence-list',
        'submit-excuse-button',
      ],
      layout: 'default',
    },
    {
      id: 'child-schedule',
      route: '/parent/child/:childId/schedule',
      section: 'frontend',
      title: 'Class Schedule',
      authRequired: true,
      roles: ['parent'],
      templateId: 'child-schedule',
      components: [
        'schedule-view',
        'class-list',
        'teacher-info',
        'room-info',
      ],
      layout: 'default',
    },
    {
      id: 'parent-settings',
      route: '/parent/settings',
      section: 'frontend',
      title: 'Parent Settings',
      authRequired: true,
      roles: ['parent'],
      templateId: 'parent-settings',
      components: [
        'profile-form',
        'notification-preferences',
        'linked-children',
        'contact-preferences',
      ],
      layout: 'default',
    },
    {
      id: 'admin-parent-accounts',
      route: '/admin/parents',
      section: 'admin',
      title: 'Parent Accounts',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-parent-accounts',
      components: [
        'parents-table',
        'parent-filters',
        'link-child-button',
        'invite-parent-button',
        'bulk-actions',
      ],
      layout: 'admin',
    },
    {
      id: 'teacher-parent-messages',
      route: '/admin/parent-messages',
      section: 'admin',
      title: 'Parent Communications',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'teacher-parent-messages',
      components: [
        'conversation-list',
        'message-thread',
        'compose-message',
        'parent-selector',
        'message-templates',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'child-selector',
    'child-overview',
    'recent-grades',
    'attendance-summary',
    'upcoming-assignments',
    'recent-messages',
    'announcements',

    // Progress components
    'progress-summary',
    'grade-chart',
    'attendance-chart',
    'course-progress',
    'achievement-list',
    'behavior-notes',

    // Message components
    'message-list',
    'message-thread',
    'compose-message',
    'teacher-selector',
    'message-filters',
    'message-templates',

    // Report card components
    'report-card-list',
    'grade-view',
    'term-selector',
    'teacher-comments',
    'download-button',
    'signature-pad',

    // Attendance components
    'attendance-calendar',
    'absence-list',
    'submit-excuse-button',

    // Schedule components
    'schedule-view',
    'class-list',
    'teacher-info',
    'room-info',

    // Settings components
    'profile-form',
    'notification-preferences',
    'linked-children',
    'contact-preferences',

    // Admin components
    'parents-table',
    'parent-filters',
    'link-child-button',
    'invite-parent-button',
    'bulk-actions',
    'conversation-list',
    'parent-selector',
  ],

  entities: [
    {
      name: 'parent_accounts',
      displayName: 'Parent Accounts',
      description: 'Parent/guardian user accounts',
      isCore: true,
    },
    {
      name: 'parent_child_links',
      displayName: 'Parent-Child Links',
      description: 'Relationships between parents and students',
      isCore: true,
    },
    {
      name: 'parent_messages',
      displayName: 'Parent Messages',
      description: 'Messages between parents and teachers',
      isCore: true,
    },
    {
      name: 'parent_notifications',
      displayName: 'Parent Notifications',
      description: 'Notifications sent to parents',
      isCore: false,
    },
    {
      name: 'report_card_signatures',
      displayName: 'Report Card Signatures',
      description: 'Digital signatures on report cards',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Parent account management
    {
      method: 'GET',
      path: '/parents',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parent_accounts',
      operation: 'list',
      description: 'List parent accounts',
    },
    {
      method: 'GET',
      path: '/parents/:id',
      auth: true,
      handler: 'crud',
      entity: 'parent_accounts',
      operation: 'get',
      description: 'Get parent account details',
    },
    {
      method: 'POST',
      path: '/parents',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parent_accounts',
      operation: 'create',
      description: 'Create parent account',
    },
    {
      method: 'PUT',
      path: '/parents/:id',
      auth: true,
      handler: 'crud',
      entity: 'parent_accounts',
      operation: 'update',
      description: 'Update parent account',
    },
    {
      method: 'DELETE',
      path: '/parents/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parent_accounts',
      operation: 'delete',
      description: 'Delete parent account',
    },

    // Parent-child links
    {
      method: 'GET',
      path: '/parents/:parentId/children',
      auth: true,
      handler: 'crud',
      entity: 'parent_child_links',
      operation: 'list',
      description: 'Get linked children',
    },
    {
      method: 'POST',
      path: '/parents/:parentId/children',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'parent_child_links',
      description: 'Link child to parent',
    },
    {
      method: 'DELETE',
      path: '/parent-child-links/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parent_child_links',
      operation: 'delete',
      description: 'Remove parent-child link',
    },

    // Parent dashboard data
    {
      method: 'GET',
      path: '/parent/dashboard',
      auth: true,
      role: 'parent',
      handler: 'aggregate',
      entity: 'parent_accounts',
      description: 'Get parent dashboard data',
    },
    {
      method: 'GET',
      path: '/parent/children/:childId/overview',
      auth: true,
      role: 'parent',
      handler: 'aggregate',
      entity: 'parent_child_links',
      description: 'Get child overview',
    },
    {
      method: 'GET',
      path: '/parent/children/:childId/grades',
      auth: true,
      role: 'parent',
      handler: 'aggregate',
      entity: 'parent_child_links',
      description: 'Get child grades',
    },
    {
      method: 'GET',
      path: '/parent/children/:childId/attendance',
      auth: true,
      role: 'parent',
      handler: 'aggregate',
      entity: 'parent_child_links',
      description: 'Get child attendance',
    },
    {
      method: 'GET',
      path: '/parent/children/:childId/schedule',
      auth: true,
      role: 'parent',
      handler: 'aggregate',
      entity: 'parent_child_links',
      description: 'Get child schedule',
    },
    {
      method: 'GET',
      path: '/parent/children/:childId/assignments',
      auth: true,
      role: 'parent',
      handler: 'aggregate',
      entity: 'parent_child_links',
      description: 'Get child assignments',
    },

    // Messages
    {
      method: 'GET',
      path: '/parent/messages',
      auth: true,
      role: 'parent',
      handler: 'crud',
      entity: 'parent_messages',
      operation: 'list',
      description: 'Get parent messages',
    },
    {
      method: 'GET',
      path: '/parent/messages/:id',
      auth: true,
      role: 'parent',
      handler: 'crud',
      entity: 'parent_messages',
      operation: 'get',
      description: 'Get message thread',
    },
    {
      method: 'POST',
      path: '/parent/messages',
      auth: true,
      role: 'parent',
      handler: 'crud',
      entity: 'parent_messages',
      operation: 'create',
      description: 'Send message to teacher',
    },
    {
      method: 'POST',
      path: '/parent/messages/:id/reply',
      auth: true,
      role: 'parent',
      handler: 'custom',
      entity: 'parent_messages',
      description: 'Reply to message',
    },

    // Teacher-side messages
    {
      method: 'GET',
      path: '/teacher/parent-messages',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'parent_messages',
      operation: 'list',
      description: 'Get messages from parents',
    },
    {
      method: 'POST',
      path: '/teacher/parent-messages',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'parent_messages',
      operation: 'create',
      description: 'Send message to parent',
    },

    // Report cards
    {
      method: 'GET',
      path: '/parent/children/:childId/report-cards',
      auth: true,
      role: 'parent',
      handler: 'crud',
      entity: 'report_card_signatures',
      operation: 'list',
      description: 'Get child report cards',
    },
    {
      method: 'POST',
      path: '/report-cards/:id/sign',
      auth: true,
      role: 'parent',
      handler: 'custom',
      entity: 'report_card_signatures',
      description: 'Sign report card',
    },
    {
      method: 'GET',
      path: '/report-cards/:id/download',
      auth: true,
      role: 'parent',
      handler: 'custom',
      entity: 'report_card_signatures',
      description: 'Download report card PDF',
    },

    // Notifications
    {
      method: 'GET',
      path: '/parent/notifications',
      auth: true,
      role: 'parent',
      handler: 'crud',
      entity: 'parent_notifications',
      operation: 'list',
      description: 'Get parent notifications',
    },
    {
      method: 'PUT',
      path: '/parent/notifications/:id/read',
      auth: true,
      role: 'parent',
      handler: 'custom',
      entity: 'parent_notifications',
      description: 'Mark notification as read',
    },
    {
      method: 'PUT',
      path: '/parent/notification-preferences',
      auth: true,
      role: 'parent',
      handler: 'custom',
      entity: 'parent_accounts',
      description: 'Update notification preferences',
    },

    // Invitation
    {
      method: 'POST',
      path: '/parents/invite',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'parent_accounts',
      description: 'Invite parent via email',
    },
    {
      method: 'POST',
      path: '/parents/accept-invite',
      auth: false,
      handler: 'custom',
      entity: 'parent_accounts',
      description: 'Accept parent invitation',
    },
  ],

  config: [
    {
      key: 'allowParentRegistration',
      label: 'Allow Parent Self-Registration',
      type: 'boolean',
      default: false,
      description: 'Allow parents to register themselves',
    },
    {
      key: 'requireAdminApproval',
      label: 'Require Admin Approval',
      type: 'boolean',
      default: true,
      description: 'Require admin approval for parent-child links',
    },
    {
      key: 'enableDirectMessaging',
      label: 'Enable Direct Messaging',
      type: 'boolean',
      default: true,
      description: 'Allow direct messages between parents and teachers',
    },
    {
      key: 'showGrades',
      label: 'Show Grades to Parents',
      type: 'boolean',
      default: true,
      description: 'Allow parents to view student grades',
    },
    {
      key: 'showAttendance',
      label: 'Show Attendance to Parents',
      type: 'boolean',
      default: true,
      description: 'Allow parents to view attendance records',
    },
    {
      key: 'enableReportCardSignature',
      label: 'Enable Digital Report Card Signatures',
      type: 'boolean',
      default: true,
      description: 'Allow parents to digitally sign report cards',
    },
    {
      key: 'notifyOnGrade',
      label: 'Notify Parents on New Grades',
      type: 'boolean',
      default: true,
      description: 'Send notification when new grades are posted',
    },
    {
      key: 'notifyOnAbsence',
      label: 'Notify Parents on Absence',
      type: 'boolean',
      default: true,
      description: 'Send notification when student is absent',
    },
    {
      key: 'notifyOnBehavior',
      label: 'Notify Parents on Behavior Notes',
      type: 'boolean',
      default: true,
      description: 'Send notification for behavior-related notes',
    },
    {
      key: 'multipleGuardiansPerStudent',
      label: 'Allow Multiple Guardians',
      type: 'boolean',
      default: true,
      description: 'Allow multiple parent accounts per student',
    },
  ],
};
