/**
 * Student Records Feature Definition
 *
 * Comprehensive student information management for schools, universities,
 * and educational institutions. Tracks academic history, enrollments,
 * and personal information.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const STUDENT_RECORDS_FEATURE: FeatureDefinition = {
  id: 'student-records',
  name: 'Student Records',
  category: 'business',
  description: 'Manage student profiles, academic records, and enrollment history',
  icon: 'user-graduate',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'student',
    'students',
    'student records',
    'student profile',
    'student information',
    'student management',
    'academic record',
    'academic history',
    'enrollment history',
    'student data',
    'student database',
    'pupil',
    'learner',
    'learner management',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'students-list',
      route: '/admin/students',
      section: 'admin',
      title: 'All Students',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'students-list',
      components: [
        'students-table',
        'student-filters',
        'search-bar',
        'bulk-actions',
        'export-button',
        'import-button',
      ],
      layout: 'admin',
    },
    {
      id: 'student-profile',
      route: '/admin/students/:id',
      section: 'admin',
      title: 'Student Profile',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'student-profile',
      components: [
        'student-header',
        'student-card',
        'profile-tabs',
        'contact-info',
        'guardian-info',
        'notes-section',
      ],
      layout: 'admin',
    },
    {
      id: 'academic-record',
      route: '/admin/students/:id/academic',
      section: 'admin',
      title: 'Academic Record',
      authRequired: true,
      roles: ['admin', 'instructor'],
      templateId: 'academic-record',
      components: [
        'academic-summary',
        'gpa-display',
        'course-history',
        'grade-list',
        'academic-standing',
        'transcript-preview',
      ],
      layout: 'admin',
    },
    {
      id: 'enrollment-history',
      route: '/admin/students/:id/enrollments',
      section: 'admin',
      title: 'Enrollment History',
      authRequired: true,
      roles: ['admin'],
      templateId: 'enrollment-history',
      components: [
        'enrollment-timeline',
        'enrollment-status',
        'enrollment-details',
        'enrollment-actions',
      ],
      layout: 'admin',
    },
    {
      id: 'my-profile',
      route: '/profile',
      section: 'frontend',
      title: 'My Profile',
      authRequired: true,
      templateId: 'my-profile',
      components: [
        'profile-header',
        'profile-form',
        'avatar-uploader',
        'password-change',
        'notification-settings',
      ],
      layout: 'default',
    },
    {
      id: 'my-academic-record',
      route: '/my-academic-record',
      section: 'frontend',
      title: 'My Academic Record',
      authRequired: true,
      templateId: 'my-academic-record',
      components: [
        'academic-summary',
        'gpa-display',
        'course-history',
        'grade-list',
        'transcript-request-button',
      ],
      layout: 'default',
    },
    {
      id: 'student-add',
      route: '/admin/students/new',
      section: 'admin',
      title: 'Add Student',
      authRequired: true,
      roles: ['admin'],
      templateId: 'student-add',
      components: [
        'student-form',
        'guardian-form',
        'enrollment-form',
        'document-uploader',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'students-table',
    'student-filters',
    'student-card',
    'bulk-actions',
    'export-button',
    'import-button',

    // Profile components
    'student-header',
    'profile-form',
    'profile-tabs',
    'contact-info',
    'guardian-info',
    'avatar-uploader',
    'notes-section',

    // Academic components
    'academic-summary',
    'gpa-display',
    'course-history',
    'grade-list',
    'academic-standing',
    'transcript-preview',
    'transcript-request-button',

    // Enrollment components
    'enrollment-timeline',
    'enrollment-status',
    'enrollment-details',
    'enrollment-actions',

    // Form components
    'student-form',
    'guardian-form',
    'enrollment-form',
    'document-uploader',
    'password-change',
    'notification-settings',

    // Search components
    'search-bar',
  ],

  entities: [
    {
      name: 'students',
      displayName: 'Students',
      description: 'Student profiles and personal information',
      isCore: true,
    },
    {
      name: 'academic_records',
      displayName: 'Academic Records',
      description: 'Academic history and performance data',
      isCore: true,
    },
    {
      name: 'enrollments',
      displayName: 'Enrollments',
      description: 'Student enrollment records',
      isCore: true,
    },
    {
      name: 'guardians',
      displayName: 'Guardians',
      description: 'Parent/guardian contact information',
      isCore: false,
    },
    {
      name: 'student_documents',
      displayName: 'Student Documents',
      description: 'Uploaded student documents',
      isCore: false,
    },
    {
      name: 'student_notes',
      displayName: 'Student Notes',
      description: 'Administrative notes about students',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Student CRUD
    {
      method: 'GET',
      path: '/students',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'students',
      operation: 'list',
      description: 'List all students',
    },
    {
      method: 'GET',
      path: '/students/:id',
      auth: true,
      handler: 'crud',
      entity: 'students',
      operation: 'get',
      description: 'Get student details',
    },
    {
      method: 'POST',
      path: '/students',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'students',
      operation: 'create',
      description: 'Create student record',
    },
    {
      method: 'PUT',
      path: '/students/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'students',
      operation: 'update',
      description: 'Update student record',
    },
    {
      method: 'DELETE',
      path: '/students/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'students',
      operation: 'delete',
      description: 'Delete student record',
    },

    // Profile endpoints
    {
      method: 'GET',
      path: '/students/me',
      auth: true,
      handler: 'custom',
      entity: 'students',
      description: 'Get current student profile',
    },
    {
      method: 'PUT',
      path: '/students/me',
      auth: true,
      handler: 'custom',
      entity: 'students',
      description: 'Update own profile',
    },

    // Academic records
    {
      method: 'GET',
      path: '/students/:id/academic-record',
      auth: true,
      handler: 'crud',
      entity: 'academic_records',
      operation: 'get',
      description: 'Get student academic record',
    },
    {
      method: 'PUT',
      path: '/students/:id/academic-record',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'academic_records',
      operation: 'update',
      description: 'Update academic record',
    },

    // Enrollments
    {
      method: 'GET',
      path: '/students/:id/enrollments',
      auth: true,
      handler: 'crud',
      entity: 'enrollments',
      operation: 'list',
      description: 'Get student enrollments',
    },
    {
      method: 'POST',
      path: '/students/:id/enrollments',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'enrollments',
      operation: 'create',
      description: 'Create enrollment',
    },

    // Guardians
    {
      method: 'GET',
      path: '/students/:id/guardians',
      auth: true,
      handler: 'crud',
      entity: 'guardians',
      operation: 'list',
      description: 'Get student guardians',
    },
    {
      method: 'POST',
      path: '/students/:id/guardians',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'guardians',
      operation: 'create',
      description: 'Add guardian',
    },
    {
      method: 'PUT',
      path: '/guardians/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'guardians',
      operation: 'update',
      description: 'Update guardian',
    },
    {
      method: 'DELETE',
      path: '/guardians/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'guardians',
      operation: 'delete',
      description: 'Remove guardian',
    },

    // Documents
    {
      method: 'GET',
      path: '/students/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'student_documents',
      operation: 'list',
      description: 'Get student documents',
    },
    {
      method: 'POST',
      path: '/students/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'student_documents',
      operation: 'create',
      description: 'Upload document',
    },
    {
      method: 'DELETE',
      path: '/documents/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'student_documents',
      operation: 'delete',
      description: 'Delete document',
    },

    // Notes
    {
      method: 'GET',
      path: '/students/:id/notes',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'student_notes',
      operation: 'list',
      description: 'Get student notes',
    },
    {
      method: 'POST',
      path: '/students/:id/notes',
      auth: true,
      role: 'instructor',
      handler: 'crud',
      entity: 'student_notes',
      operation: 'create',
      description: 'Add note',
    },

    // Bulk operations
    {
      method: 'POST',
      path: '/students/import',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'students',
      description: 'Bulk import students',
    },
    {
      method: 'GET',
      path: '/students/export',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'students',
      description: 'Export students',
    },

    // Search
    {
      method: 'GET',
      path: '/students/search',
      auth: true,
      role: 'instructor',
      handler: 'custom',
      entity: 'students',
      description: 'Search students',
    },
  ],

  config: [
    {
      key: 'requireGuardianInfo',
      label: 'Require Guardian Information',
      type: 'boolean',
      default: true,
      description: 'Require at least one guardian for students under 18',
    },
    {
      key: 'studentIdPrefix',
      label: 'Student ID Prefix',
      type: 'string',
      default: 'STU',
      description: 'Prefix for auto-generated student IDs',
    },
    {
      key: 'allowSelfRegistration',
      label: 'Allow Self Registration',
      type: 'boolean',
      default: false,
      description: 'Allow students to register themselves',
    },
    {
      key: 'profileEditableFields',
      label: 'Self-Editable Fields',
      type: 'select',
      default: 'limited',
      options: [
        { value: 'none', label: 'None' },
        { value: 'limited', label: 'Contact Info Only' },
        { value: 'all', label: 'All Fields' },
      ],
      description: 'Which fields students can edit themselves',
    },
    {
      key: 'retentionPeriod',
      label: 'Record Retention (years)',
      type: 'number',
      default: 7,
      description: 'How long to retain student records after graduation',
    },
    {
      key: 'enableStudentPhotos',
      label: 'Enable Student Photos',
      type: 'boolean',
      default: true,
      description: 'Allow student photo uploads',
    },
  ],
};
