/**
 * Transcripts Feature Definition
 *
 * Academic transcript generation, request management, and verification.
 * Supports official and unofficial transcripts with GPA and course history.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TRANSCRIPTS_FEATURE: FeatureDefinition = {
  id: 'transcripts',
  name: 'Academic Transcripts',
  category: 'business',
  description: 'Generate, request, and verify academic transcripts',
  icon: 'file-certificate',

  includedInAppTypes: [
    'lms',
    'online-academy',
    'school',
    'university',
    'tutoring',
    'coding-bootcamp',
    'language-school',
    'trade-school',
    'preschool',
  ],

  activationKeywords: [
    'transcript',
    'transcripts',
    'academic transcript',
    'official transcript',
    'unofficial transcript',
    'course history',
    'academic record',
    'gpa record',
    'grade record',
    'degree audit',
    'academic summary',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'student-records', 'grading'],
  conflicts: [],

  pages: [
    {
      id: 'transcript-request',
      route: '/transcript/request',
      section: 'frontend',
      title: 'Request Transcript',
      authRequired: true,
      templateId: 'transcript-request',
      components: [
        'transcript-type-selector',
        'delivery-method',
        'recipient-form',
        'copies-selector',
        'payment-form',
        'request-summary',
        'submit-button',
      ],
      layout: 'default',
    },
    {
      id: 'transcript-view',
      route: '/transcript/view',
      section: 'frontend',
      title: 'View Transcript',
      authRequired: true,
      templateId: 'transcript-view',
      components: [
        'transcript-generator',
        'student-info-header',
        'course-history',
        'gpa-display',
        'credits-summary',
        'term-breakdown',
        'download-button',
        'print-button',
      ],
      layout: 'default',
    },
    {
      id: 'transcript-send',
      route: '/transcript/send',
      section: 'frontend',
      title: 'Send Transcript',
      authRequired: true,
      templateId: 'transcript-send',
      components: [
        'transcript-preview',
        'recipient-selector',
        'email-form',
        'delivery-options',
        'confirmation-modal',
      ],
      layout: 'default',
    },
    {
      id: 'my-transcript-requests',
      route: '/transcript/my-requests',
      section: 'frontend',
      title: 'My Transcript Requests',
      authRequired: true,
      templateId: 'my-transcript-requests',
      components: [
        'request-list',
        'request-status',
        'request-details',
        'cancel-button',
        'reorder-button',
      ],
      layout: 'default',
    },
    {
      id: 'admin-transcripts',
      route: '/admin/transcripts',
      section: 'admin',
      title: 'Transcript Requests',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-transcripts',
      components: [
        'requests-table',
        'request-filters',
        'status-updater',
        'bulk-actions',
        'export-button',
      ],
      layout: 'admin',
    },
    {
      id: 'transcript-verify',
      route: '/transcript/verify/:code',
      section: 'frontend',
      title: 'Verify Transcript',
      authRequired: false,
      templateId: 'transcript-verify',
      components: [
        'verification-form',
        'verification-result',
        'transcript-preview',
        'verification-seal',
        'institution-info',
      ],
      layout: 'centered',
    },
    {
      id: 'admin-transcript-settings',
      route: '/admin/transcripts/settings',
      section: 'admin',
      title: 'Transcript Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-transcript-settings',
      components: [
        'template-editor',
        'fee-settings',
        'delivery-settings',
        'verification-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Request components
    'transcript-type-selector',
    'delivery-method',
    'recipient-form',
    'copies-selector',
    'payment-form',
    'request-summary',
    'submit-button',

    // View components
    'transcript-generator',
    'student-info-header',
    'course-history',
    'gpa-display',
    'credits-summary',
    'term-breakdown',
    'download-button',
    'print-button',

    // Send components
    'transcript-preview',
    'recipient-selector',
    'email-form',
    'delivery-options',
    'confirmation-modal',

    // Request tracking
    'request-list',
    'request-status',
    'request-details',
    'cancel-button',
    'reorder-button',

    // Admin components
    'requests-table',
    'request-filters',
    'status-updater',
    'bulk-actions',
    'export-button',

    // Verification components
    'verification-form',
    'verification-result',
    'verification-seal',
    'institution-info',

    // Settings components
    'template-editor',
    'fee-settings',
    'delivery-settings',
    'verification-settings',
  ],

  entities: [
    {
      name: 'transcripts',
      displayName: 'Transcripts',
      description: 'Generated academic transcripts',
      isCore: true,
    },
    {
      name: 'transcript_requests',
      displayName: 'Transcript Requests',
      description: 'Student transcript request submissions',
      isCore: true,
    },
    {
      name: 'course_history',
      displayName: 'Course History',
      description: 'Complete course enrollment and grade history',
      isCore: true,
    },
    {
      name: 'transcript_recipients',
      displayName: 'Transcript Recipients',
      description: 'Recipients of sent transcripts',
      isCore: false,
    },
    {
      name: 'transcript_verifications',
      displayName: 'Transcript Verifications',
      description: 'Verification requests and logs',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Transcript viewing
    {
      method: 'GET',
      path: '/transcripts/my',
      auth: true,
      handler: 'custom',
      entity: 'transcripts',
      description: 'Get own unofficial transcript',
    },
    {
      method: 'GET',
      path: '/transcripts/:id',
      auth: true,
      handler: 'crud',
      entity: 'transcripts',
      operation: 'get',
      description: 'Get transcript details',
    },
    {
      method: 'GET',
      path: '/transcripts/:id/download',
      auth: true,
      handler: 'custom',
      entity: 'transcripts',
      description: 'Download transcript PDF',
    },

    // Transcript requests
    {
      method: 'GET',
      path: '/transcript-requests',
      auth: true,
      handler: 'crud',
      entity: 'transcript_requests',
      operation: 'list',
      description: 'Get own transcript requests',
    },
    {
      method: 'GET',
      path: '/transcript-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'transcript_requests',
      operation: 'get',
      description: 'Get request details',
    },
    {
      method: 'POST',
      path: '/transcript-requests',
      auth: true,
      handler: 'crud',
      entity: 'transcript_requests',
      operation: 'create',
      description: 'Submit transcript request',
    },
    {
      method: 'DELETE',
      path: '/transcript-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'transcript_requests',
      operation: 'delete',
      description: 'Cancel transcript request',
    },

    // Admin request management
    {
      method: 'GET',
      path: '/admin/transcript-requests',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'transcript_requests',
      operation: 'list',
      description: 'List all transcript requests',
    },
    {
      method: 'PUT',
      path: '/admin/transcript-requests/:id/status',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'transcript_requests',
      description: 'Update request status',
    },
    {
      method: 'POST',
      path: '/admin/transcript-requests/:id/process',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'transcript_requests',
      description: 'Process and fulfill request',
    },

    // Generate transcript
    {
      method: 'POST',
      path: '/admin/students/:studentId/transcript/generate',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'transcripts',
      description: 'Generate student transcript',
    },
    {
      method: 'GET',
      path: '/admin/students/:studentId/transcript',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'transcripts',
      description: 'Get student transcript',
    },

    // Course history
    {
      method: 'GET',
      path: '/course-history',
      auth: true,
      handler: 'crud',
      entity: 'course_history',
      operation: 'list',
      description: 'Get own course history',
    },
    {
      method: 'GET',
      path: '/admin/students/:studentId/course-history',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'course_history',
      operation: 'list',
      description: 'Get student course history',
    },

    // Send transcript
    {
      method: 'POST',
      path: '/transcripts/send',
      auth: true,
      handler: 'custom',
      entity: 'transcript_recipients',
      description: 'Send transcript to recipient',
    },
    {
      method: 'GET',
      path: '/transcripts/sent',
      auth: true,
      handler: 'crud',
      entity: 'transcript_recipients',
      operation: 'list',
      description: 'Get sent transcripts',
    },

    // Verification
    {
      method: 'POST',
      path: '/transcripts/verify',
      auth: false,
      handler: 'custom',
      entity: 'transcript_verifications',
      description: 'Verify transcript authenticity',
    },
    {
      method: 'GET',
      path: '/transcripts/verify/:code',
      auth: false,
      handler: 'custom',
      entity: 'transcript_verifications',
      description: 'Verify by code',
    },
    {
      method: 'GET',
      path: '/admin/verification-logs',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'transcript_verifications',
      operation: 'list',
      description: 'Get verification logs',
    },

    // Fees and payment
    {
      method: 'GET',
      path: '/transcript-fees',
      auth: true,
      handler: 'custom',
      entity: 'transcript_requests',
      description: 'Get transcript fee structure',
    },
    {
      method: 'POST',
      path: '/transcript-requests/:id/pay',
      auth: true,
      handler: 'custom',
      entity: 'transcript_requests',
      description: 'Process payment for request',
    },

    // Settings
    {
      method: 'GET',
      path: '/admin/transcript-settings',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'transcripts',
      description: 'Get transcript settings',
    },
    {
      method: 'PUT',
      path: '/admin/transcript-settings',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'transcripts',
      description: 'Update transcript settings',
    },
  ],

  config: [
    {
      key: 'enableUnofficialTranscripts',
      label: 'Enable Unofficial Transcripts',
      type: 'boolean',
      default: true,
      description: 'Allow students to view unofficial transcripts',
    },
    {
      key: 'officialTranscriptFee',
      label: 'Official Transcript Fee',
      type: 'number',
      default: 10,
      description: 'Fee for official transcript in dollars',
    },
    {
      key: 'additionalCopyFee',
      label: 'Additional Copy Fee',
      type: 'number',
      default: 5,
      description: 'Fee for each additional copy',
    },
    {
      key: 'electronicDeliveryFee',
      label: 'Electronic Delivery Fee',
      type: 'number',
      default: 0,
      description: 'Fee for electronic delivery (0 = free)',
    },
    {
      key: 'mailedDeliveryFee',
      label: 'Mailed Delivery Fee',
      type: 'number',
      default: 5,
      description: 'Additional fee for mailed transcripts',
    },
    {
      key: 'rushProcessingFee',
      label: 'Rush Processing Fee',
      type: 'number',
      default: 25,
      description: 'Fee for expedited processing',
    },
    {
      key: 'processingDays',
      label: 'Standard Processing Days',
      type: 'number',
      default: 5,
      description: 'Standard processing time in business days',
    },
    {
      key: 'rushProcessingDays',
      label: 'Rush Processing Days',
      type: 'number',
      default: 1,
      description: 'Rush processing time in business days',
    },
    {
      key: 'enableVerification',
      label: 'Enable Online Verification',
      type: 'boolean',
      default: true,
      description: 'Allow third parties to verify transcripts online',
    },
    {
      key: 'verificationCodeExpiry',
      label: 'Verification Code Expiry (days)',
      type: 'number',
      default: 365,
      description: 'How long verification codes remain valid',
    },
    {
      key: 'showInProgressCourses',
      label: 'Show In-Progress Courses',
      type: 'boolean',
      default: true,
      description: 'Include currently enrolled courses on transcript',
    },
    {
      key: 'includeWithdrawnCourses',
      label: 'Include Withdrawn Courses',
      type: 'boolean',
      default: true,
      description: 'Show withdrawn courses on transcript',
    },
  ],
};
