/**
 * Generate App Types Index
 *
 * Creates the index.ts file for all app types in the registry.
 * Run: npx ts-node scripts/generate-app-types-index.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const APP_TYPES_DIR = path.join(__dirname, '../src/modules/app-builder/registries/app-types');

// Manual mapping for special cases
const SPECIAL_EXPORT_NAMES: Record<string, string> = {
  '3d-printing-service': 'THREE_D_PRINTING_SERVICE_APP_TYPE',
  '3pl-provider': 'THREE_PL_PROVIDER_APP_TYPE',
};

function kebabToConstantCase(str: string): string {
  // Check for special cases first
  if (SPECIAL_EXPORT_NAMES[str]) {
    return SPECIAL_EXPORT_NAMES[str];
  }
  // Handle files starting with numbers
  if (/^\d/.test(str)) {
    const numMap: Record<string, string> = {
      '0': 'ZERO', '1': 'ONE', '2': 'TWO', '3': 'THREE',
      '4': 'FOUR', '5': 'FIVE', '6': 'SIX', '7': 'SEVEN',
      '8': 'EIGHT', '9': 'NINE'
    };
    // Replace leading numbers with words
    str = str.replace(/^(\d+)/, (match) => {
      return match.split('').map(d => numMap[d] || d).join('_');
    });
  }
  return str.toUpperCase().replace(/-/g, '_') + '_APP_TYPE';
}

function main() {
  // Get all .ts files except index.ts
  const files = fs.readdirSync(APP_TYPES_DIR)
    .filter(f => f.endsWith('.ts') && f !== 'index.ts')
    .map(f => f.replace('.ts', ''))
    .sort();

  console.log(`Found ${files.length} app type files`);

  // Generate exports
  const exports: string[] = [];
  const imports: string[] = [];

  for (const file of files) {
    const constName = kebabToConstantCase(file);
    exports.push(`export { ${constName} } from './${file}';`);
    imports.push(`  ${constName},`);
  }

  // Generate the index content
  const content = `/**
 * App Types Registry - Master Index
 *
 * Consolidates all app type definitions.
 * Total: ${files.length} app types covering major industries and use cases.
 *
 * Auto-generated by scripts/generate-app-types-index.ts
 */

import { AppTypeDefinition } from '../../interfaces/app-type.interface';

// ─────────────────────────────────────────────────────────────
// EXPORTS - Individual app types (${files.length} total)
// ─────────────────────────────────────────────────────────────

${exports.join('\n')}

// ─────────────────────────────────────────────────────────────
// APP TYPES REGISTRY
// ─────────────────────────────────────────────────────────────

import {
${imports.join('\n')}
} from './index';

/**
 * Complete registry of all app types
 */
export const APP_TYPES_REGISTRY: Record<string, AppTypeDefinition> = {
${files.map(f => `  '${f}': ${kebabToConstantCase(f)},`).join('\n')}
};

/**
 * Get app type by ID
 */
export function getAppType(id: string): AppTypeDefinition | undefined {
  return APP_TYPES_REGISTRY[id];
}

/**
 * Get all app type IDs
 */
export function getAllAppTypeIds(): string[] {
  return Object.keys(APP_TYPES_REGISTRY);
}

/**
 * Get app types by category
 */
export function getAppTypesByCategory(category: string): AppTypeDefinition[] {
  return Object.values(APP_TYPES_REGISTRY).filter(app => app.category === category);
}

/**
 * Get app types by industry
 */
export function getAppTypesByIndustry(industry: string): AppTypeDefinition[] {
  return Object.values(APP_TYPES_REGISTRY).filter(app => app.industry === industry);
}

/**
 * Search app types by keyword
 */
export function searchAppTypes(query: string): AppTypeDefinition[] {
  const q = query.toLowerCase();
  return Object.values(APP_TYPES_REGISTRY).filter(app =>
    app.name.toLowerCase().includes(q) ||
    app.id.includes(q) ||
    app.keywords?.some(k => k.toLowerCase().includes(q)) ||
    app.synonyms?.some(s => s.toLowerCase().includes(q))
  );
}

// ─────────────────────────────────────────────────────────────
// LEGACY EXPORTS (for backward compatibility)
// ─────────────────────────────────────────────────────────────

/**
 * Array of all app types
 * @deprecated Use APP_TYPES_REGISTRY or getAppType() instead
 */
export const ALL_APP_TYPES: AppTypeDefinition[] = Object.values(APP_TYPES_REGISTRY);

/**
 * Map of app types by ID
 * @deprecated Use APP_TYPES_REGISTRY instead
 */
export const APP_TYPES_BY_ID: Map<string, AppTypeDefinition> = new Map(
  Object.entries(APP_TYPES_REGISTRY)
);

/**
 * Get app type by ID
 * @deprecated Use getAppType() instead
 */
export function getAppTypeById(id: string): AppTypeDefinition | undefined {
  return APP_TYPES_REGISTRY[id];
}
`;

  // Write the index file
  fs.writeFileSync(path.join(APP_TYPES_DIR, 'index.ts'), content);
  console.log(`Generated index.ts with ${files.length} app types`);
}

main();
