/**
 * Analytics Feature Definition
 *
 * Complete analytics functionality for dashboard visualization,
 * charts, reports, and data-driven insights.
 */

import { FeatureDefinition } from '../../interfaces/feature.interface';

export const ANALYTICS_FEATURE: FeatureDefinition = {
  id: 'analytics',
  name: 'Analytics',
  category: 'analytics',
  description: 'Dashboard analytics, charts, reports, and data visualization',
  icon: 'bar-chart',

  includedInAppTypes: [
    'ecommerce',
    'saas',
    'crm',
    'marketplace',
    'project-management',
    'social-network',
    'lms',
    'healthcare',
    'fintech',
    'real-estate',
    'booking',
    'erp',
    'hrms',
    'inventory',
    'logistics',
    'marketing',
    'support',
    'agency',
    'freelance',
    'subscription',
    'membership',
    'admin-dashboard',
  ],

  activationKeywords: [
    'analytics',
    'dashboard',
    'charts',
    'reports',
    'statistics',
    'metrics',
    'insights',
    'data visualization',
    'kpi',
    'performance metrics',
    'reporting',
    'graphs',
    'data analysis',
    'business intelligence',
    'tracking',
    'monitoring',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'analytics-dashboard',
      route: '/analytics',
      section: 'frontend',
      title: 'Analytics Dashboard',
      authRequired: true,
      templateId: 'analytics-dashboard',
      components: [
        'stats-card',
        'metrics-grid',
        'line-chart',
        'bar-chart',
        'pie-chart',
        'trend-indicator',
        'date-range-picker',
      ],
      layout: 'dashboard',
    },
    {
      id: 'reports',
      route: '/reports',
      section: 'frontend',
      title: 'Reports',
      authRequired: true,
      templateId: 'reports-list',
      components: [
        'reports-table',
        'report-card',
        'create-report-modal',
        'date-range-picker',
        'export-button',
      ],
      layout: 'default',
    },
    {
      id: 'report-detail',
      route: '/reports/:id',
      section: 'frontend',
      title: 'Report Detail',
      authRequired: true,
      templateId: 'report-detail',
      components: [
        'report-header',
        'report-charts',
        'report-data-table',
        'export-button',
        'share-report-modal',
      ],
      layout: 'default',
    },
    {
      id: 'admin-analytics',
      route: '/admin/analytics',
      section: 'admin',
      title: 'Admin Analytics',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-analytics-dashboard',
      components: [
        'stats-card',
        'metrics-grid',
        'line-chart',
        'bar-chart',
        'pie-chart',
        'user-activity-chart',
        'revenue-chart',
      ],
      layout: 'dashboard',
    },
    {
      id: 'custom-reports',
      route: '/reports/custom',
      section: 'frontend',
      title: 'Custom Reports',
      authRequired: true,
      templateId: 'custom-reports-builder',
      components: [
        'report-builder',
        'metric-selector',
        'dimension-picker',
        'filter-builder',
        'preview-panel',
      ],
      layout: 'default',
    },
  ],

  components: [
    // Stats components
    'stats-card',
    'metrics-grid',
    'trend-indicator',
    'kpi-card',
    'comparison-card',

    // Chart components
    'line-chart',
    'bar-chart',
    'pie-chart',
    'area-chart',
    'donut-chart',
    'sparkline',
    'heatmap',
    'funnel-chart',

    // Date and filter components
    'date-range-picker',
    'period-selector',
    'filter-dropdown',
    'metric-filter',

    // Report components
    'reports-table',
    'report-card',
    'report-header',
    'report-charts',
    'report-data-table',
    'create-report-modal',
    'share-report-modal',
    'export-button',

    // Report builder components
    'report-builder',
    'metric-selector',
    'dimension-picker',
    'filter-builder',
    'preview-panel',

    // Activity components
    'user-activity-chart',
    'revenue-chart',
    'event-timeline',
    'activity-feed',
  ],

  entities: [
    {
      name: 'analytics_events',
      displayName: 'Analytics Events',
      description: 'Raw analytics event data for tracking user actions',
      isCore: true,
    },
    {
      name: 'reports',
      displayName: 'Reports',
      description: 'Saved report configurations and results',
      isCore: true,
    },
    {
      name: 'report_configs',
      displayName: 'Report Configurations',
      description: 'Custom report configuration settings',
      isCore: false,
    },
    {
      name: 'analytics_snapshots',
      displayName: 'Analytics Snapshots',
      description: 'Periodic snapshots of aggregated metrics',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Analytics Overview Routes
    {
      method: 'GET',
      path: '/analytics/overview',
      auth: true,
      handler: 'custom',
      entity: 'analytics_events',
      description: 'Get analytics overview with key metrics',
    },
    {
      method: 'GET',
      path: '/analytics/events',
      auth: true,
      handler: 'crud',
      entity: 'analytics_events',
      operation: 'list',
      description: 'List analytics events with filters',
    },
    {
      method: 'POST',
      path: '/analytics/events',
      auth: true,
      handler: 'crud',
      entity: 'analytics_events',
      operation: 'create',
      description: 'Track a new analytics event',
    },
    {
      method: 'GET',
      path: '/analytics/summary',
      auth: true,
      handler: 'custom',
      entity: 'analytics_events',
      description: 'Get aggregated analytics summary',
    },
    {
      method: 'GET',
      path: '/analytics/trends',
      auth: true,
      handler: 'custom',
      entity: 'analytics_events',
      description: 'Get trend data for specified metrics',
    },
    {
      method: 'GET',
      path: '/analytics/realtime',
      auth: true,
      handler: 'custom',
      entity: 'analytics_events',
      description: 'Get real-time analytics data',
    },

    // Report Routes
    {
      method: 'GET',
      path: '/reports',
      auth: true,
      handler: 'crud',
      entity: 'reports',
      operation: 'list',
      description: 'List all saved reports',
    },
    {
      method: 'POST',
      path: '/reports',
      auth: true,
      handler: 'crud',
      entity: 'reports',
      operation: 'create',
      description: 'Create a new report',
    },
    {
      method: 'GET',
      path: '/reports/:id',
      auth: true,
      handler: 'crud',
      entity: 'reports',
      operation: 'get',
      description: 'Get report details',
    },
    {
      method: 'PUT',
      path: '/reports/:id',
      auth: true,
      handler: 'crud',
      entity: 'reports',
      operation: 'update',
      description: 'Update a report',
    },
    {
      method: 'DELETE',
      path: '/reports/:id',
      auth: true,
      handler: 'crud',
      entity: 'reports',
      operation: 'delete',
      description: 'Delete a report',
    },
    {
      method: 'POST',
      path: '/reports/:id/run',
      auth: true,
      handler: 'custom',
      entity: 'reports',
      description: 'Execute a saved report and get results',
    },
    {
      method: 'POST',
      path: '/reports/:id/export',
      auth: true,
      handler: 'custom',
      entity: 'reports',
      description: 'Export report data in specified format',
    },

    // Report Config Routes
    {
      method: 'GET',
      path: '/report-configs',
      auth: true,
      handler: 'crud',
      entity: 'report_configs',
      operation: 'list',
      description: 'List report configurations',
    },
    {
      method: 'POST',
      path: '/report-configs',
      auth: true,
      handler: 'crud',
      entity: 'report_configs',
      operation: 'create',
      description: 'Create a report configuration',
    },
    {
      method: 'PUT',
      path: '/report-configs/:id',
      auth: true,
      handler: 'crud',
      entity: 'report_configs',
      operation: 'update',
      description: 'Update a report configuration',
    },
    {
      method: 'DELETE',
      path: '/report-configs/:id',
      auth: true,
      handler: 'crud',
      entity: 'report_configs',
      operation: 'delete',
      description: 'Delete a report configuration',
    },

    // Dashboard Stats Routes
    {
      method: 'GET',
      path: '/analytics/stats/users',
      auth: true,
      handler: 'custom',
      entity: 'analytics_events',
      description: 'Get user-related statistics',
    },
    {
      method: 'GET',
      path: '/analytics/stats/revenue',
      auth: true,
      handler: 'custom',
      entity: 'analytics_events',
      description: 'Get revenue statistics',
    },
    {
      method: 'GET',
      path: '/analytics/stats/engagement',
      auth: true,
      handler: 'custom',
      entity: 'analytics_events',
      description: 'Get user engagement metrics',
    },
  ],

  config: [
    {
      key: 'retentionDays',
      label: 'Data Retention (days)',
      type: 'number',
      default: 90,
      description: 'Number of days to retain analytics event data',
    },
    {
      key: 'enableRealtime',
      label: 'Enable Realtime Analytics',
      type: 'boolean',
      default: true,
      description: 'Enable real-time analytics updates via websocket',
    },
    {
      key: 'sampleRate',
      label: 'Event Sampling Rate (%)',
      type: 'number',
      default: 100,
      description: 'Percentage of events to track (for high-traffic apps)',
    },
    {
      key: 'defaultDateRange',
      label: 'Default Date Range',
      type: 'select',
      default: '7d',
      options: [
        { value: '1d', label: 'Last 24 hours' },
        { value: '7d', label: 'Last 7 days' },
        { value: '30d', label: 'Last 30 days' },
        { value: '90d', label: 'Last 90 days' },
      ],
      description: 'Default date range for analytics views',
    },
    {
      key: 'enableExports',
      label: 'Enable Report Exports',
      type: 'boolean',
      default: true,
      description: 'Allow users to export reports as CSV/PDF',
    },
  ],
};
