/**
 * Appointments Feature Definition
 *
 * Complete appointment booking functionality for service businesses,
 * healthcare, salons, and any app requiring scheduled appointments.
 */

import { FeatureDefinition } from '../../interfaces/feature.interface';

export const APPOINTMENTS_FEATURE: FeatureDefinition = {
  id: 'appointments',
  name: 'Appointments',
  category: 'booking',
  description: 'Book and manage appointments with calendar, time slots, and reminders',
  icon: 'calendar-check',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'salon',
    'spa',
    'fitness',
    'dental',
    'veterinary',
    'consulting',
    'coaching',
    'therapy',
    'tutoring',
    'home-services',
    'auto-service',
    'pet-grooming',
    'photography',
    'legal',
    'financial-advisor',
    'real-estate',
    'wellness',
    'massage',
    'beauty',
    'barbershop',
    'clinic',
    'physiotherapy',
    'chiropractic',
    'optometry',
    'dermatology',
  ],

  activationKeywords: [
    'appointment',
    'appointments',
    'booking',
    'book appointment',
    'schedule',
    'scheduling',
    'calendar booking',
    'time slots',
    'service booking',
    'book a slot',
    'appointment scheduler',
    'calendly',
    'acuity',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'appointments-list',
      route: '/appointments',
      section: 'frontend',
      title: 'My Appointments',
      authRequired: true,
      templateId: 'appointments-list',
      components: [
        'appointments-calendar',
        'appointments-list',
        'appointment-card',
        'date-filter',
      ],
      layout: 'default',
    },
    {
      id: 'book-appointment',
      route: '/book',
      section: 'frontend',
      title: 'Book Appointment',
      authRequired: false,
      templateId: 'book-appointment',
      components: [
        'service-selector',
        'provider-selector',
        'date-picker',
        'time-slot-picker',
        'booking-form',
        'booking-summary',
      ],
      layout: 'default',
    },
    {
      id: 'appointment-detail',
      route: '/appointments/:id',
      section: 'frontend',
      title: 'Appointment Details',
      authRequired: true,
      templateId: 'appointment-detail',
      components: [
        'appointment-header',
        'appointment-info',
        'reschedule-button',
        'cancel-button',
        'appointment-notes',
      ],
      layout: 'default',
    },
    {
      id: 'admin-appointments',
      route: '/admin/appointments',
      section: 'admin',
      title: 'Manage Appointments',
      authRequired: true,
      templateId: 'admin-appointments',
      components: [
        'admin-calendar-view',
        'appointments-table',
        'appointment-filters',
        'bulk-actions',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-services',
      route: '/admin/services',
      section: 'admin',
      title: 'Services',
      authRequired: true,
      templateId: 'admin-services',
      components: [
        'services-list',
        'service-form',
        'service-pricing',
        'service-duration',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Booking components
    'appointments-calendar',
    'appointments-list',
    'appointment-card',
    'date-picker',
    'time-slot-picker',
    'service-selector',
    'provider-selector',
    'booking-form',
    'booking-summary',
    'booking-confirmation',

    // Detail components
    'appointment-header',
    'appointment-info',
    'appointment-notes',
    'reschedule-button',
    'cancel-button',

    // Admin components
    'admin-calendar-view',
    'appointments-table',
    'appointment-filters',
    'services-list',
    'service-form',
    'service-pricing',
    'service-duration',
    'bulk-actions',

    // Filter components
    'date-filter',
    'status-filter',
    'provider-filter',
  ],

  entities: [
    {
      name: 'appointments',
      displayName: 'Appointments',
      description: 'Scheduled appointments',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', required: true },
        { name: 'service_id', type: 'uuid', required: true, references: { table: 'services' } },
        { name: 'provider_id', type: 'uuid', references: { table: 'providers' } },
        { name: 'start_time', type: 'timestamptz', required: true },
        { name: 'end_time', type: 'timestamptz', required: true },
        { name: 'status', type: 'text', default: "'pending'" },
        { name: 'notes', type: 'text' },
        { name: 'customer_name', type: 'text' },
        { name: 'customer_email', type: 'text' },
        { name: 'customer_phone', type: 'text' },
        { name: 'cancellation_reason', type: 'text' },
        { name: 'cancelled_at', type: 'timestamptz' },
        { name: 'confirmed_at', type: 'timestamptz' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'services',
      displayName: 'Services',
      description: 'Services that can be booked',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'description', type: 'text' },
        { name: 'duration', type: 'integer', required: true },
        { name: 'price', type: 'numeric' },
        { name: 'currency', type: 'text', default: "'USD'" },
        { name: 'category', type: 'text' },
        { name: 'image_url', type: 'text' },
        { name: 'is_active', type: 'boolean', default: 'true' },
        { name: 'sort_order', type: 'integer', default: '0' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'providers',
      displayName: 'Providers',
      description: 'Service providers/staff',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid' },
        { name: 'name', type: 'text', required: true },
        { name: 'email', type: 'text' },
        { name: 'phone', type: 'text' },
        { name: 'bio', type: 'text' },
        { name: 'avatar_url', type: 'text' },
        { name: 'specialties', type: 'jsonb' },
        { name: 'is_active', type: 'boolean', default: 'true' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'time_slots',
      displayName: 'Time Slots',
      description: 'Available time slots',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'provider_id', type: 'uuid', references: { table: 'providers' } },
        { name: 'date', type: 'date', required: true },
        { name: 'start_time', type: 'time', required: true },
        { name: 'end_time', type: 'time', required: true },
        { name: 'is_available', type: 'boolean', default: 'true' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
  ],

  apiRoutes: [
    // Appointment routes
    {
      method: 'GET',
      path: '/appointments',
      auth: true,
      handler: 'crud',
      entity: 'appointments',
      description: 'List appointments',
    },
    {
      method: 'POST',
      path: '/appointments',
      auth: true,
      handler: 'crud',
      entity: 'appointments',
      description: 'Create appointment',
    },
    {
      method: 'GET',
      path: '/appointments/:id',
      auth: true,
      handler: 'crud',
      entity: 'appointments',
      description: 'Get appointment details',
    },
    {
      method: 'PUT',
      path: '/appointments/:id',
      auth: true,
      handler: 'crud',
      entity: 'appointments',
      description: 'Update appointment',
    },
    {
      method: 'DELETE',
      path: '/appointments/:id',
      auth: true,
      handler: 'crud',
      entity: 'appointments',
      description: 'Cancel appointment',
    },
    {
      method: 'POST',
      path: '/appointments/:id/reschedule',
      auth: true,
      handler: 'custom',
      entity: 'appointments',
      description: 'Reschedule appointment',
    },
    {
      method: 'POST',
      path: '/appointments/:id/confirm',
      auth: true,
      handler: 'custom',
      entity: 'appointments',
      description: 'Confirm appointment',
    },

    // Services routes
    {
      method: 'GET',
      path: '/services',
      auth: false,
      handler: 'crud',
      entity: 'services',
      description: 'List available services',
    },
    {
      method: 'POST',
      path: '/services',
      auth: true,
      handler: 'crud',
      entity: 'services',
      description: 'Create service',
    },
    {
      method: 'PUT',
      path: '/services/:id',
      auth: true,
      handler: 'crud',
      entity: 'services',
      description: 'Update service',
    },

    // Availability routes
    {
      method: 'GET',
      path: '/availability',
      auth: false,
      handler: 'custom',
      entity: 'time_slots',
      description: 'Get available time slots',
    },
    {
      method: 'GET',
      path: '/providers/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'time_slots',
      description: 'Get provider availability',
    },
  ],

  config: [
    {
      key: 'defaultDuration',
      label: 'Default Appointment Duration (minutes)',
      type: 'number',
      default: 30,
      description: 'Default duration for appointments',
    },
    {
      key: 'bufferTime',
      label: 'Buffer Time Between Appointments (minutes)',
      type: 'number',
      default: 15,
      description: 'Buffer time between consecutive appointments',
    },
    {
      key: 'advanceBookingDays',
      label: 'Advance Booking Limit (days)',
      type: 'number',
      default: 30,
      description: 'How far in advance can appointments be booked',
    },
    {
      key: 'cancellationPolicy',
      label: 'Cancellation Notice (hours)',
      type: 'number',
      default: 24,
      description: 'Minimum hours before appointment for free cancellation',
    },
    {
      key: 'requireConfirmation',
      label: 'Require Confirmation',
      type: 'boolean',
      default: true,
      description: 'Require admin confirmation for bookings',
    },
  ],
};
