/**
 * Blog Feature Definition
 *
 * Blog posts, articles, and content publishing with
 * categories, tags, and author management.
 */

import { FeatureDefinition } from '../../interfaces/feature.interface';

export const BLOG_FEATURE: FeatureDefinition = {
  id: 'blog',
  name: 'Blog',
  category: 'content',
  description: 'Blog posts and articles with categories, tags, and publishing workflow',
  icon: 'file-text',

  includedInAppTypes: [
    'blog',
    'news-site',
    'magazine',
    'content-platform',
    'personal-website',
    'portfolio',
    'business-website',
    'nonprofit',
    'church',
    'school',
    'university',
    'community',
    'travel-blog',
    'food-blog',
    'tech-blog',
    'lifestyle',
    'fashion',
    'ecommerce',
    'saas',
    'agency',
  ],

  activationKeywords: [
    'blog',
    'blogging',
    'articles',
    'posts',
    'news',
    'content',
    'publishing',
    'wordpress',
    'medium',
    'substack',
    'write articles',
    'content management',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'blog-list',
      route: '/blog',
      section: 'frontend',
      title: 'Blog',
      authRequired: false,
      templateId: 'blog-list',
      components: [
        'blog-header',
        'featured-posts',
        'posts-grid',
        'category-filter',
        'search-bar',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'blog-post',
      route: '/blog/:slug',
      section: 'frontend',
      title: 'Blog Post',
      authRequired: false,
      templateId: 'blog-post',
      components: [
        'post-header',
        'post-content',
        'author-bio',
        'share-buttons',
        'related-posts',
        'comments-section',
      ],
      layout: 'default',
    },
    {
      id: 'write-post',
      route: '/blog/write',
      section: 'frontend',
      title: 'Write Post',
      authRequired: true,
      templateId: 'write-post',
      components: [
        'post-editor',
        'title-input',
        'slug-input',
        'category-selector',
        'tags-input',
        'featured-image',
        'publish-settings',
      ],
      layout: 'default',
    },
    {
      id: 'admin-posts',
      route: '/admin/posts',
      section: 'admin',
      title: 'Manage Posts',
      authRequired: true,
      templateId: 'admin-posts',
      components: [
        'posts-table',
        'status-filter',
        'bulk-actions',
        'post-stats',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-categories',
      route: '/admin/categories',
      section: 'admin',
      title: 'Categories',
      authRequired: true,
      templateId: 'admin-categories',
      components: [
        'category-tree',
        'category-form',
        'category-stats',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'blog-header',
    'featured-posts',
    'posts-grid',
    'post-card',
    'pagination',

    // Post components
    'post-header',
    'post-content',
    'author-bio',
    'share-buttons',
    'related-posts',

    // Editor components
    'post-editor',
    'title-input',
    'slug-input',
    'category-selector',
    'tags-input',
    'featured-image',
    'publish-settings',

    // Filter components
    'category-filter',
    'search-bar',
    'status-filter',

    // Admin components
    'posts-table',
    'bulk-actions',
    'post-stats',
    'category-tree',
    'category-form',
    'category-stats',

    // Comments
    'comments-section',
    'comment-form',
    'comment-item',
  ],

  entities: [
    {
      name: 'posts',
      displayName: 'Posts',
      description: 'Blog posts',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'title', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'content', type: 'text' },
        { name: 'excerpt', type: 'text' },
        { name: 'featured_image', type: 'text' },
        { name: 'author_id', type: 'string', required: true },
        { name: 'category_id', type: 'uuid', references: { table: 'categories' } },
        { name: 'status', type: 'text', default: "'draft'" },
        { name: 'published_at', type: 'timestamptz' },
        { name: 'view_count', type: 'integer', default: '0' },
        { name: 'is_featured', type: 'boolean', default: 'false' },
        { name: 'meta_title', type: 'text' },
        { name: 'meta_description', type: 'text' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'categories',
      displayName: 'Categories',
      description: 'Post categories',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'description', type: 'text' },
        { name: 'parent_id', type: 'uuid', references: { table: 'categories' } },
        { name: 'image_url', type: 'text' },
        { name: 'sort_order', type: 'integer', default: '0' },
        { name: 'is_active', type: 'boolean', default: 'true' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'tags',
      displayName: 'Tags',
      description: 'Post tags',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'post_tags',
      displayName: 'Post Tags',
      description: 'Junction table for posts and tags',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'post_id', type: 'uuid', required: true, references: { table: 'posts' } },
        { name: 'tag_id', type: 'uuid', required: true, references: { table: 'tags' } },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'comments',
      displayName: 'Comments',
      description: 'Post comments',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'post_id', type: 'uuid', required: true, references: { table: 'posts' } },
        { name: 'user_id', type: 'string', required: true },
        { name: 'parent_id', type: 'uuid', references: { table: 'comments' } },
        { name: 'content', type: 'text', required: true },
        { name: 'status', type: 'text', default: "'pending'" },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
  ],

  apiRoutes: [
    {
      method: 'GET',
      path: '/posts',
      auth: false,
      handler: 'crud',
      entity: 'posts',
      description: 'List published posts',
    },
    {
      method: 'GET',
      path: '/posts/:slug',
      auth: false,
      handler: 'crud',
      entity: 'posts',
      description: 'Get post by slug',
    },
    {
      method: 'POST',
      path: '/posts',
      auth: true,
      handler: 'crud',
      entity: 'posts',
      description: 'Create post',
    },
    {
      method: 'PUT',
      path: '/posts/:id',
      auth: true,
      handler: 'crud',
      entity: 'posts',
      description: 'Update post',
    },
    {
      method: 'DELETE',
      path: '/posts/:id',
      auth: true,
      handler: 'crud',
      entity: 'posts',
      description: 'Delete post',
    },
    {
      method: 'POST',
      path: '/posts/:id/publish',
      auth: true,
      handler: 'custom',
      entity: 'posts',
      description: 'Publish post',
    },
    {
      method: 'GET',
      path: '/categories',
      auth: false,
      handler: 'crud',
      entity: 'categories',
      description: 'List categories',
    },
    {
      method: 'POST',
      path: '/categories',
      auth: true,
      handler: 'crud',
      entity: 'categories',
      description: 'Create category',
    },
    {
      method: 'GET',
      path: '/posts/:id/comments',
      auth: false,
      handler: 'crud',
      entity: 'comments',
      description: 'Get post comments',
    },
    {
      method: 'POST',
      path: '/posts/:id/comments',
      auth: true,
      handler: 'crud',
      entity: 'comments',
      description: 'Add comment',
    },
  ],

  config: [
    {
      key: 'postsPerPage',
      label: 'Posts Per Page',
      type: 'number',
      default: 10,
      description: 'Number of posts to show per page',
    },
    {
      key: 'enableComments',
      label: 'Enable Comments',
      type: 'boolean',
      default: true,
      description: 'Allow comments on posts',
    },
    {
      key: 'moderateComments',
      label: 'Moderate Comments',
      type: 'boolean',
      default: true,
      description: 'Require approval for comments',
    },
    {
      key: 'defaultStatus',
      label: 'Default Post Status',
      type: 'string',
      default: 'draft',
      description: 'Default status for new posts',
    },
  ],
};
