/**
 * CRM Feature Definition
 *
 * Customer relationship management with contacts,
 * deals, pipelines, and activity tracking.
 */

import { FeatureDefinition } from '../../interfaces/feature.interface';

export const CRM_FEATURE: FeatureDefinition = {
  id: 'crm',
  name: 'CRM',
  category: 'business',
  description: 'Customer relationship management with contacts, deals, and pipelines',
  icon: 'users',

  includedInAppTypes: [
    'crm',
    'sales',
    'real-estate',
    'insurance',
    'recruiting',
    'agency',
    'consulting',
    'financial-services',
    'b2b-saas',
    'enterprise',
  ],

  activationKeywords: [
    'crm',
    'customer relationship',
    'contacts',
    'leads',
    'deals',
    'pipeline',
    'salesforce',
    'hubspot',
    'pipedrive',
    'sales management',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'contacts-list',
      route: '/contacts',
      section: 'frontend',
      title: 'Contacts',
      authRequired: true,
      templateId: 'contacts-list',
      components: [
        'contacts-table',
        'contact-card',
        'search-bar',
        'filter-panel',
        'add-contact-button',
      ],
      layout: 'default',
    },
    {
      id: 'contact-detail',
      route: '/contacts/:id',
      section: 'frontend',
      title: 'Contact',
      authRequired: true,
      templateId: 'contact-detail',
      components: [
        'contact-header',
        'contact-info',
        'activity-timeline',
        'related-deals',
        'notes-section',
      ],
      layout: 'default',
    },
    {
      id: 'deals-pipeline',
      route: '/deals',
      section: 'frontend',
      title: 'Deals',
      authRequired: true,
      templateId: 'deals-pipeline',
      components: [
        'pipeline-board',
        'deal-card',
        'stage-column',
        'deal-filters',
        'add-deal-button',
      ],
      layout: 'default',
    },
    {
      id: 'deal-detail',
      route: '/deals/:id',
      section: 'frontend',
      title: 'Deal',
      authRequired: true,
      templateId: 'deal-detail',
      components: [
        'deal-header',
        'deal-info',
        'deal-timeline',
        'related-contacts',
        'deal-documents',
      ],
      layout: 'default',
    },
    {
      id: 'companies-list',
      route: '/companies',
      section: 'frontend',
      title: 'Companies',
      authRequired: true,
      templateId: 'companies-list',
      components: [
        'companies-table',
        'company-card',
        'add-company-button',
      ],
      layout: 'default',
    },
  ],

  components: [
    // Contacts
    'contacts-table',
    'contact-card',
    'contact-header',
    'contact-info',
    'contact-form',
    'add-contact-button',

    // Deals
    'pipeline-board',
    'deal-card',
    'stage-column',
    'deal-header',
    'deal-info',
    'deal-form',
    'add-deal-button',

    // Companies
    'companies-table',
    'company-card',
    'company-form',
    'add-company-button',

    // Activities
    'activity-timeline',
    'activity-form',
    'notes-section',
    'deal-timeline',

    // Related
    'related-deals',
    'related-contacts',
    'deal-documents',

    // Filters
    'search-bar',
    'filter-panel',
    'deal-filters',
  ],

  entities: [
    {
      name: 'contacts',
      displayName: 'Contacts',
      description: 'Contact records',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'first_name', type: 'text', required: true },
        { name: 'last_name', type: 'text' },
        { name: 'email', type: 'text' },
        { name: 'phone', type: 'text' },
        { name: 'company_id', type: 'uuid', references: { table: 'companies' } },
        { name: 'title', type: 'text' },
        { name: 'source', type: 'text' },
        { name: 'status', type: 'text', default: "'active'" },
        { name: 'score', type: 'integer', default: '0' },
        { name: 'tags', type: 'jsonb' },
        { name: 'custom_fields', type: 'jsonb' },
        { name: 'owner_id', type: 'uuid' },
        { name: 'last_contacted_at', type: 'timestamptz' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'deals',
      displayName: 'Deals',
      description: 'Sales deals/opportunities',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'value', type: 'numeric' },
        { name: 'currency', type: 'text', default: "'USD'" },
        { name: 'stage_id', type: 'uuid', references: { table: 'pipeline_stages' } },
        { name: 'contact_id', type: 'uuid', references: { table: 'contacts' } },
        { name: 'company_id', type: 'uuid', references: { table: 'companies' } },
        { name: 'owner_id', type: 'uuid' },
        { name: 'probability', type: 'integer', default: '0' },
        { name: 'expected_close_date', type: 'date' },
        { name: 'closed_at', type: 'timestamptz' },
        { name: 'won', type: 'boolean' },
        { name: 'loss_reason', type: 'text' },
        { name: 'description', type: 'text' },
        { name: 'tags', type: 'jsonb' },
        { name: 'custom_fields', type: 'jsonb' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'companies',
      displayName: 'Companies',
      description: 'Company accounts',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'domain', type: 'text' },
        { name: 'industry', type: 'text' },
        { name: 'size', type: 'text' },
        { name: 'phone', type: 'text' },
        { name: 'address', type: 'jsonb' },
        { name: 'website', type: 'text' },
        { name: 'description', type: 'text' },
        { name: 'logo_url', type: 'text' },
        { name: 'owner_id', type: 'uuid' },
        { name: 'tags', type: 'jsonb' },
        { name: 'custom_fields', type: 'jsonb' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'activities',
      displayName: 'Activities',
      description: 'Activity log',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'type', type: 'text', required: true },
        { name: 'subject', type: 'text' },
        { name: 'description', type: 'text' },
        { name: 'contact_id', type: 'uuid', references: { table: 'contacts' } },
        { name: 'deal_id', type: 'uuid', references: { table: 'deals' } },
        { name: 'company_id', type: 'uuid', references: { table: 'companies' } },
        { name: 'user_id', type: 'uuid', required: true },
        { name: 'scheduled_at', type: 'timestamptz' },
        { name: 'completed_at', type: 'timestamptz' },
        { name: 'metadata', type: 'jsonb' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'pipeline_stages',
      displayName: 'Pipeline Stages',
      description: 'Deal stages',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'color', type: 'text' },
        { name: 'sort_order', type: 'integer', default: '0' },
        { name: 'probability', type: 'integer', default: '0' },
        { name: 'is_won', type: 'boolean', default: 'false' },
        { name: 'is_lost', type: 'boolean', default: 'false' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
  ],

  apiRoutes: [
    {
      method: 'GET',
      path: '/contacts',
      auth: true,
      handler: 'crud',
      entity: 'contacts',
      description: 'List contacts',
    },
    {
      method: 'POST',
      path: '/contacts',
      auth: true,
      handler: 'crud',
      entity: 'contacts',
      description: 'Create contact',
    },
    {
      method: 'GET',
      path: '/contacts/:id',
      auth: true,
      handler: 'crud',
      entity: 'contacts',
      description: 'Get contact',
    },
    {
      method: 'PUT',
      path: '/contacts/:id',
      auth: true,
      handler: 'crud',
      entity: 'contacts',
      description: 'Update contact',
    },
    {
      method: 'DELETE',
      path: '/contacts/:id',
      auth: true,
      handler: 'crud',
      entity: 'contacts',
      description: 'Delete contact',
    },
    {
      method: 'GET',
      path: '/deals',
      auth: true,
      handler: 'crud',
      entity: 'deals',
      description: 'List deals',
    },
    {
      method: 'POST',
      path: '/deals',
      auth: true,
      handler: 'crud',
      entity: 'deals',
      description: 'Create deal',
    },
    {
      method: 'GET',
      path: '/deals/:id',
      auth: true,
      handler: 'crud',
      entity: 'deals',
      description: 'Get deal',
    },
    {
      method: 'PUT',
      path: '/deals/:id',
      auth: true,
      handler: 'crud',
      entity: 'deals',
      description: 'Update deal',
    },
    {
      method: 'POST',
      path: '/deals/:id/move',
      auth: true,
      handler: 'custom',
      entity: 'deals',
      description: 'Move deal stage',
    },
    {
      method: 'GET',
      path: '/companies',
      auth: true,
      handler: 'crud',
      entity: 'companies',
      description: 'List companies',
    },
    {
      method: 'POST',
      path: '/companies',
      auth: true,
      handler: 'crud',
      entity: 'companies',
      description: 'Create company',
    },
    {
      method: 'GET',
      path: '/activities',
      auth: true,
      handler: 'crud',
      entity: 'activities',
      description: 'List activities',
    },
    {
      method: 'POST',
      path: '/activities',
      auth: true,
      handler: 'crud',
      entity: 'activities',
      description: 'Log activity',
    },
  ],

  config: [
    {
      key: 'pipelineStages',
      label: 'Pipeline Stages',
      type: 'string',
      default: 'Lead,Qualified,Proposal,Negotiation,Won,Lost',
      description: 'Comma-separated deal stages',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default deal currency',
    },
    {
      key: 'enableScoring',
      label: 'Enable Lead Scoring',
      type: 'boolean',
      default: false,
      description: 'Enable lead/contact scoring',
    },
    {
      key: 'activityTypes',
      label: 'Activity Types',
      type: 'string',
      default: 'call,email,meeting,note,task',
      description: 'Available activity types',
    },
  ],
};
