/**
 * Product Catalog Feature Definition
 *
 * Core feature for e-commerce apps - product listing and management.
 */

import { FeatureDefinition } from '../../interfaces/feature.interface';

export const PRODUCT_CATALOG_FEATURE: FeatureDefinition = {
  id: 'product-catalog',
  name: 'Product Catalog',
  category: 'commerce',
  description: 'Product listing, categories, and product details',
  icon: 'package',

  includedInAppTypes: ['ecommerce', 'marketplace', 'digital-products'],

  activationKeywords: [
    'product', 'catalog', 'item', 'listing', 'inventory',
    'merchandise', 'goods', 'stock',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: [],
  conflicts: [],

  pages: [
    {
      id: 'products-list',
      route: '/products',
      section: 'frontend',
      title: 'Products',
      authRequired: false,
      templateId: 'list-page',
      components: ['product-grid', 'category-filter', 'search-bar', 'sort-dropdown'],
      layout: 'default',
    },
    {
      id: 'product-detail',
      route: '/products/:id',
      section: 'frontend',
      title: 'Product Details',
      authRequired: false,
      templateId: 'detail-page',
      components: ['product-detail', 'product-gallery', 'add-to-cart-button', 'related-products'],
      layout: 'default',
    },
    {
      id: 'category-products',
      route: '/category/:slug',
      section: 'frontend',
      title: 'Category',
      authRequired: false,
      templateId: 'list-page',
      components: ['product-grid', 'category-filter', 'breadcrumbs'],
      layout: 'default',
    },
    {
      id: 'admin-products',
      route: '/admin/products',
      section: 'admin',
      title: 'Manage Products',
      authRequired: true,
      roles: ['admin'],
      templateId: 'list-page',
      components: ['products-table', 'product-filters', 'bulk-actions'],
      layout: 'dashboard',
    },
    {
      id: 'admin-product-create',
      route: '/admin/products/new',
      section: 'admin',
      title: 'Add Product',
      authRequired: true,
      roles: ['admin'],
      templateId: 'form-page',
      components: ['product-form'],
      layout: 'dashboard',
    },
    {
      id: 'admin-product-edit',
      route: '/admin/products/:id/edit',
      section: 'admin',
      title: 'Edit Product',
      authRequired: true,
      roles: ['admin'],
      templateId: 'form-page',
      components: ['product-form'],
      layout: 'dashboard',
    },
    {
      id: 'admin-categories',
      route: '/admin/categories',
      section: 'admin',
      title: 'Manage Categories',
      authRequired: true,
      roles: ['admin'],
      templateId: 'list-page',
      components: ['categories-table', 'category-form-modal'],
      layout: 'dashboard',
    },
  ],

  components: [
    'product-grid',
    'product-card',
    'product-detail',
    'product-gallery',
    'product-form',
    'products-table',
    'category-filter',
    'search-bar',
    'sort-dropdown',
    'breadcrumbs',
    'add-to-cart-button',
    'related-products',
    'categories-table',
    'category-form-modal',
    'product-filters',
    'bulk-actions',
  ],

  entities: [
    {
      name: 'products',
      displayName: 'Products',
      description: 'Product catalog items',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'description', type: 'text' },
        { name: 'short_description', type: 'text' },
        { name: 'price', type: 'numeric', required: true },
        { name: 'compare_at_price', type: 'numeric' },
        { name: 'cost_price', type: 'numeric' },
        { name: 'sku', type: 'text' },
        { name: 'barcode', type: 'text' },
        { name: 'quantity', type: 'integer', default: '0' },
        { name: 'track_inventory', type: 'boolean', default: 'true' },
        { name: 'category_id', type: 'uuid', references: { table: 'categories' } },
        { name: 'image_url', type: 'text' },
        { name: 'images', type: 'jsonb' },
        { name: 'status', type: 'text', default: "'draft'" },
        { name: 'is_featured', type: 'boolean', default: 'false' },
        { name: 'weight', type: 'numeric' },
        { name: 'dimensions', type: 'jsonb' },
        { name: 'meta_title', type: 'text' },
        { name: 'meta_description', type: 'text' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'categories',
      displayName: 'Categories',
      description: 'Product categories',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'description', type: 'text' },
        { name: 'parent_id', type: 'uuid', references: { table: 'categories' } },
        { name: 'image_url', type: 'text' },
        { name: 'sort_order', type: 'integer', default: '0' },
        { name: 'is_active', type: 'boolean', default: 'true' },
        { name: 'product_count', type: 'integer', default: '0' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'product_images',
      displayName: 'Product Images',
      description: 'Product image gallery',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'product_id', type: 'uuid', required: true, references: { table: 'products' } },
        { name: 'url', type: 'text', required: true },
        { name: 'alt_text', type: 'text' },
        { name: 'sort_order', type: 'integer', default: '0' },
        { name: 'is_primary', type: 'boolean', default: 'false' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
  ],

  apiRoutes: [
    // Public routes
    {
      method: 'GET',
      path: '/products',
      auth: false,
      handler: 'crud',
      entity: 'products',
      operation: 'list',
      description: 'List all products',
    },
    {
      method: 'GET',
      path: '/products/:id',
      auth: false,
      handler: 'crud',
      entity: 'products',
      operation: 'get',
      description: 'Get product by ID',
    },
    {
      method: 'GET',
      path: '/products/featured',
      auth: false,
      handler: 'custom',
      entity: 'products',
      description: 'Get featured products',
    },
    {
      method: 'GET',
      path: '/categories',
      auth: false,
      handler: 'crud',
      entity: 'categories',
      operation: 'list',
      description: 'List all categories',
    },
    {
      method: 'GET',
      path: '/categories/:slug/products',
      auth: false,
      handler: 'custom',
      entity: 'products',
      description: 'Get products by category',
    },
    // Admin routes
    {
      method: 'POST',
      path: '/admin/products',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'products',
      operation: 'create',
      description: 'Create product',
    },
    {
      method: 'PUT',
      path: '/admin/products/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'products',
      operation: 'update',
      description: 'Update product',
    },
    {
      method: 'DELETE',
      path: '/admin/products/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'products',
      operation: 'delete',
      description: 'Delete product',
    },
    {
      method: 'POST',
      path: '/admin/categories',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'categories',
      operation: 'create',
      description: 'Create category',
    },
    {
      method: 'PUT',
      path: '/admin/categories/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'categories',
      operation: 'update',
      description: 'Update category',
    },
    {
      method: 'DELETE',
      path: '/admin/categories/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'categories',
      operation: 'delete',
      description: 'Delete category',
    },
  ],

  config: [
    {
      key: 'enableVariants',
      label: 'Enable Product Variants',
      type: 'boolean',
      default: false,
      description: 'Allow size, color, etc. variants',
    },
    {
      key: 'trackInventory',
      label: 'Track Inventory',
      type: 'boolean',
      default: true,
      description: 'Track product stock levels',
    },
  ],
};
