/**
 * Reservations Feature Definition
 *
 * Table reservations for restaurants, room bookings for hotels,
 * venue reservations for events.
 */

import { FeatureDefinition } from '../../interfaces/feature.interface';

export const RESERVATIONS_FEATURE: FeatureDefinition = {
  id: 'reservations',
  name: 'Reservations',
  category: 'booking',
  description: 'Table, room, and venue reservations with capacity management',
  icon: 'bookmark-check',

  includedInAppTypes: [
    'restaurant',
    'hotel',
    'hospitality',
    'event-venue',
    'conference-center',
    'resort',
    'bed-breakfast',
    'vacation-rental',
    'coworking',
    'meeting-rooms',
    'banquet-hall',
    'wedding-venue',
    'party-venue',
    'sports-facility',
    'golf-course',
    'tennis-club',
    'bowling-alley',
    'escape-room',
    'karaoke',
    'private-dining',
  ],

  activationKeywords: [
    'reservation',
    'reservations',
    'table booking',
    'room booking',
    'book a table',
    'book a room',
    'venue booking',
    'restaurant booking',
    'hotel reservation',
    'opentable',
    'resy',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'reservations-list',
      route: '/reservations',
      section: 'frontend',
      title: 'My Reservations',
      authRequired: true,
      templateId: 'reservations-list',
      components: [
        'reservations-list',
        'reservation-card',
        'reservation-status',
      ],
      layout: 'default',
    },
    {
      id: 'make-reservation',
      route: '/reserve',
      section: 'frontend',
      title: 'Make Reservation',
      authRequired: false,
      templateId: 'make-reservation',
      components: [
        'date-picker',
        'time-picker',
        'guest-count-selector',
        'table-picker',
        'reservation-form',
        'special-requests',
      ],
      layout: 'default',
    },
    {
      id: 'reservation-detail',
      route: '/reservations/:id',
      section: 'frontend',
      title: 'Reservation Details',
      authRequired: true,
      templateId: 'reservation-detail',
      components: [
        'reservation-header',
        'reservation-info',
        'modify-button',
        'cancel-button',
        'qr-code',
      ],
      layout: 'default',
    },
    {
      id: 'admin-reservations',
      route: '/admin/reservations',
      section: 'admin',
      title: 'Manage Reservations',
      authRequired: true,
      templateId: 'admin-reservations',
      components: [
        'reservations-calendar',
        'floor-plan-view',
        'reservations-table',
        'walk-in-button',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-tables',
      route: '/admin/tables',
      section: 'admin',
      title: 'Table Management',
      authRequired: true,
      templateId: 'admin-tables',
      components: [
        'floor-plan-editor',
        'table-list',
        'table-form',
        'capacity-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Booking components
    'reservations-list',
    'reservation-card',
    'reservation-status',
    'date-picker',
    'time-picker',
    'guest-count-selector',
    'table-picker',
    'reservation-form',
    'special-requests',
    'reservation-confirmation',

    // Detail components
    'reservation-header',
    'reservation-info',
    'modify-button',
    'cancel-button',
    'qr-code',

    // Admin components
    'reservations-calendar',
    'floor-plan-view',
    'floor-plan-editor',
    'reservations-table',
    'table-list',
    'table-form',
    'capacity-settings',
    'walk-in-button',
  ],

  entities: [
    {
      name: 'reservations',
      displayName: 'Reservations',
      description: 'Table/room reservations',
      isCore: true,
    },
    {
      name: 'tables',
      displayName: 'Tables',
      description: 'Tables or rooms available for booking',
      isCore: true,
    },
    {
      name: 'floors',
      displayName: 'Floors/Areas',
      description: 'Floor plans or areas',
      isCore: false,
    },
  ],

  apiRoutes: [
    {
      method: 'GET',
      path: '/reservations',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'List reservations',
    },
    {
      method: 'POST',
      path: '/reservations',
      auth: false,
      handler: 'crud',
      entity: 'reservations',
      description: 'Create reservation',
    },
    {
      method: 'GET',
      path: '/reservations/:id',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'Get reservation details',
    },
    {
      method: 'PUT',
      path: '/reservations/:id',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'Update reservation',
    },
    {
      method: 'DELETE',
      path: '/reservations/:id',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'Cancel reservation',
    },
    {
      method: 'GET',
      path: '/tables',
      auth: false,
      handler: 'crud',
      entity: 'tables',
      description: 'List available tables',
    },
    {
      method: 'GET',
      path: '/availability/tables',
      auth: false,
      handler: 'custom',
      entity: 'tables',
      description: 'Check table availability',
    },
    {
      method: 'POST',
      path: '/reservations/:id/confirm',
      auth: true,
      handler: 'custom',
      entity: 'reservations',
      description: 'Confirm reservation',
    },
    {
      method: 'POST',
      path: '/reservations/:id/seat',
      auth: true,
      handler: 'custom',
      entity: 'reservations',
      description: 'Mark as seated',
    },
  ],

  config: [
    {
      key: 'defaultDuration',
      label: 'Default Reservation Duration (minutes)',
      type: 'number',
      default: 90,
      description: 'Default dining duration',
    },
    {
      key: 'maxPartySize',
      label: 'Maximum Party Size',
      type: 'number',
      default: 20,
      description: 'Maximum guests per reservation',
    },
    {
      key: 'advanceBookingDays',
      label: 'Advance Booking (days)',
      type: 'number',
      default: 30,
      description: 'How far in advance reservations can be made',
    },
    {
      key: 'requireDeposit',
      label: 'Require Deposit',
      type: 'boolean',
      default: false,
      description: 'Require deposit for large parties',
    },
  ],
};
