/**
 * Subscriptions Feature Definition
 *
 * This feature adds recurring subscription management, plan selection,
 * billing cycles, and subscription lifecycle handling to applications.
 */

import { FeatureDefinition } from '../../interfaces/feature.interface';

export const SUBSCRIPTIONS_FEATURE: FeatureDefinition = {
  id: 'subscriptions',
  name: 'Subscriptions',
  category: 'commerce',
  description: 'Recurring subscription management with plans, billing cycles, and lifecycle handling',
  icon: 'repeat',

  // ─────────────────────────────────────────────────────────────
  // ACTIVATION
  // ─────────────────────────────────────────────────────────────

  /** App types that include this feature by default */
  includedInAppTypes: [
    'saas',
    'subscription',
    'membership',
    'streaming',
    'fitness',
    'education',
    'news',
    'magazine',
    'podcast',
    'music',
    'video',
    'software',
    'newsletter',
    'community',
    'coaching',
    'content-platform',
    'subscription-box',
    'meal-kit',
    'gaming',
  ],

  /** Keywords that activate this feature from user prompt */
  activationKeywords: [
    'subscription',
    'subscriptions',
    'recurring',
    'membership',
    'member',
    'plan',
    'pricing plan',
    'monthly',
    'yearly',
    'annual',
    'billing cycle',
    'subscribe',
    'subscriber',
    'premium',
    'pro plan',
    'free trial',
    'trial',
    'cancel subscription',
    'upgrade',
    'downgrade',
    'tier',
    'pricing tier',
    'recurring payment',
    'recurring billing',
    'auto-renew',
  ],

  /** Enabled by default for included app types */
  enabledByDefault: true,

  /** User can opt-out */
  optional: false,

  // ─────────────────────────────────────────────────────────────
  // DEPENDENCIES
  // ─────────────────────────────────────────────────────────────

  /** Other features this depends on */
  dependencies: [
    'user-auth',    // Need users to have subscriptions
    'payments',     // Need payment processing for billing
  ],

  /** Incompatible features */
  conflicts: [],

  // ─────────────────────────────────────────────────────────────
  // PAGES - What pages this feature adds
  // ─────────────────────────────────────────────────────────────
  pages: [
    {
      id: 'subscriptions',
      route: '/account/subscription',
      section: 'frontend',
      title: 'My Subscription',
      authRequired: true,
      templateId: 'subscription-page',
      components: [
        'subscription-card',
        'current-plan-details',
        'billing-cycle',
        'next-billing-date',
        'usage-summary',
        'upgrade-banner',
      ],
      layout: 'default',
    },
    {
      id: 'subscription-detail',
      route: '/account/subscription/:id',
      section: 'frontend',
      title: 'Subscription Details',
      authRequired: true,
      templateId: 'detail-page',
      components: [
        'subscription-detail-header',
        'subscription-timeline',
        'invoice-history',
        'payment-method-card',
        'subscription-actions',
      ],
      layout: 'default',
    },
    {
      id: 'manage-subscription',
      route: '/account/subscription/manage',
      section: 'frontend',
      title: 'Manage Subscription',
      authRequired: true,
      templateId: 'settings-page',
      components: [
        'plan-selector',
        'billing-cycle',
        'payment-method-selector',
        'cancel-subscription',
        'pause-subscription',
        'subscription-addons',
      ],
      layout: 'centered',
    },
    {
      id: 'pricing',
      route: '/pricing',
      section: 'frontend',
      title: 'Pricing Plans',
      authRequired: false,
      templateId: 'pricing-page',
      components: [
        'pricing-table',
        'plan-comparison',
        'billing-toggle',
        'plan-features-list',
        'faq-section',
        'testimonials',
      ],
      layout: 'default',
    },
    {
      id: 'checkout-subscription',
      route: '/subscribe/:planId',
      section: 'frontend',
      title: 'Subscribe',
      authRequired: true,
      templateId: 'checkout-page',
      components: [
        'subscription-checkout-form',
        'plan-summary',
        'payment-form',
        'billing-address-form',
        'terms-acceptance',
      ],
      layout: 'centered',
    },
    {
      id: 'admin-subscriptions',
      route: '/admin/subscriptions',
      section: 'admin',
      title: 'Subscriptions',
      authRequired: true,
      roles: ['admin'],
      templateId: 'list-page',
      components: [
        'subscriptions-table',
        'subscription-filters',
        'subscription-stats-cards',
        'mrr-chart',
        'churn-rate-widget',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-plans',
      route: '/admin/subscription-plans',
      section: 'admin',
      title: 'Subscription Plans',
      authRequired: true,
      roles: ['admin'],
      templateId: 'list-page',
      components: [
        'plans-table',
        'create-plan-button',
        'plan-analytics',
        'plan-usage-chart',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-plan-detail',
      route: '/admin/subscription-plans/:id',
      section: 'admin',
      title: 'Plan Details',
      authRequired: true,
      roles: ['admin'],
      templateId: 'detail-page',
      components: [
        'plan-detail-header',
        'plan-features-editor',
        'plan-pricing-editor',
        'plan-subscribers-list',
        'plan-revenue-chart',
      ],
      layout: 'dashboard',
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // COMPONENTS - Components used by this feature
  // ─────────────────────────────────────────────────────────────
  components: [
    'subscription-card',
    'plan-selector',
    'billing-cycle',
    'cancel-subscription',
    'current-plan-details',
    'next-billing-date',
    'usage-summary',
    'upgrade-banner',
    'subscription-detail-header',
    'subscription-timeline',
    'invoice-history',
    'payment-method-card',
    'subscription-actions',
    'pause-subscription',
    'subscription-addons',
    'pricing-table',
    'plan-comparison',
    'billing-toggle',
    'plan-features-list',
    'faq-section',
    'subscription-checkout-form',
    'plan-summary',
    'terms-acceptance',
    'subscriptions-table',
    'subscription-filters',
    'subscription-stats-cards',
    'mrr-chart',
    'churn-rate-widget',
    'plans-table',
    'create-plan-button',
    'plan-analytics',
    'plan-usage-chart',
    'plan-detail-header',
    'plan-features-editor',
    'plan-pricing-editor',
    'plan-subscribers-list',
    'plan-revenue-chart',
    'subscription-badge',
    'trial-countdown',
    'subscription-renewal-notice',
    'plan-limit-indicator',
  ],

  // ─────────────────────────────────────────────────────────────
  // ENTITIES - Database tables required
  // ─────────────────────────────────────────────────────────────
  entities: [
    {
      name: 'subscriptions',
      displayName: 'Subscriptions',
      description: 'User subscriptions with status and billing information',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', required: true },
        { name: 'plan_id', type: 'uuid', required: true, references: { table: 'subscription_plans' } },
        { name: 'status', type: 'text', default: "'active'" },
        { name: 'billing_cycle', type: 'text', default: "'monthly'" },
        { name: 'current_period_start', type: 'timestamptz' },
        { name: 'current_period_end', type: 'timestamptz' },
        { name: 'trial_start', type: 'timestamptz' },
        { name: 'trial_end', type: 'timestamptz' },
        { name: 'cancelled_at', type: 'timestamptz' },
        { name: 'cancel_at_period_end', type: 'boolean', default: 'false' },
        { name: 'paused_at', type: 'timestamptz' },
        { name: 'resume_at', type: 'timestamptz' },
        { name: 'external_id', type: 'text' },
        { name: 'metadata', type: 'jsonb' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'subscription_plans',
      displayName: 'Subscription Plans',
      description: 'Available subscription plans with features and pricing',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'description', type: 'text' },
        { name: 'price_monthly', type: 'numeric' },
        { name: 'price_yearly', type: 'numeric' },
        { name: 'currency', type: 'text', default: "'USD'" },
        { name: 'trial_days', type: 'integer', default: '0' },
        { name: 'features', type: 'jsonb' },
        { name: 'limits', type: 'jsonb' },
        { name: 'is_active', type: 'boolean', default: 'true' },
        { name: 'is_featured', type: 'boolean', default: 'false' },
        { name: 'sort_order', type: 'integer', default: '0' },
        { name: 'external_id', type: 'text' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'subscription_invoices',
      displayName: 'Subscription Invoices',
      description: 'Billing invoices for subscription payments',
      isCore: true,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'subscription_id', type: 'uuid', required: true, references: { table: 'subscriptions' } },
        { name: 'invoice_number', type: 'text', unique: true },
        { name: 'amount', type: 'numeric', required: true },
        { name: 'currency', type: 'text', default: "'USD'" },
        { name: 'status', type: 'text', default: "'pending'" },
        { name: 'period_start', type: 'timestamptz' },
        { name: 'period_end', type: 'timestamptz' },
        { name: 'paid_at', type: 'timestamptz' },
        { name: 'due_date', type: 'timestamptz' },
        { name: 'payment_method', type: 'text' },
        { name: 'external_id', type: 'text' },
        { name: 'pdf_url', type: 'text' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'plan_features',
      displayName: 'Plan Features',
      description: 'Features included in each subscription plan',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'plan_id', type: 'uuid', required: true, references: { table: 'subscription_plans' } },
        { name: 'name', type: 'text', required: true },
        { name: 'key', type: 'text' },
        { name: 'value', type: 'text' },
        { name: 'limit', type: 'integer' },
        { name: 'is_enabled', type: 'boolean', default: 'true' },
        { name: 'sort_order', type: 'integer', default: '0' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'subscription_usage',
      displayName: 'Subscription Usage',
      description: 'Usage tracking for metered subscriptions',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'subscription_id', type: 'uuid', required: true, references: { table: 'subscriptions' } },
        { name: 'metric', type: 'text', required: true },
        { name: 'value', type: 'numeric', required: true },
        { name: 'period_start', type: 'timestamptz' },
        { name: 'period_end', type: 'timestamptz' },
        { name: 'metadata', type: 'jsonb' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
      ],
    },
    {
      name: 'subscription_addons',
      displayName: 'Subscription Add-ons',
      description: 'Optional add-ons that can be added to subscriptions',
      isCore: false,
      fields: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', required: true },
        { name: 'slug', type: 'text', unique: true },
        { name: 'description', type: 'text' },
        { name: 'price', type: 'numeric' },
        { name: 'billing_type', type: 'text', default: "'recurring'" },
        { name: 'is_active', type: 'boolean', default: 'true' },
        { name: 'created_at', type: 'timestamptz', default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', default: 'now()' },
      ],
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // API ROUTES - Backend endpoints
  // ─────────────────────────────────────────────────────────────
  apiRoutes: [
    // Public plan routes
    {
      method: 'GET',
      path: '/plans',
      auth: false,
      handler: 'crud',
      entity: 'subscription_plans',
      operation: 'list',
      description: 'Get all available subscription plans',
    },
    {
      method: 'GET',
      path: '/plans/:id',
      auth: false,
      handler: 'crud',
      entity: 'subscription_plans',
      operation: 'get',
      description: 'Get plan details',
    },
    {
      method: 'GET',
      path: '/plans/compare',
      auth: false,
      handler: 'custom',
      entity: 'subscription_plans',
      description: 'Get plan comparison data',
    },

    // User subscription routes
    {
      method: 'GET',
      path: '/subscription',
      auth: true,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Get current user subscription',
    },
    {
      method: 'GET',
      path: '/subscriptions',
      auth: true,
      handler: 'crud',
      entity: 'subscriptions',
      operation: 'list',
      description: 'Get all user subscriptions',
    },
    {
      method: 'GET',
      path: '/subscriptions/:id',
      auth: true,
      handler: 'crud',
      entity: 'subscriptions',
      operation: 'get',
      description: 'Get subscription details',
    },
    {
      method: 'POST',
      path: '/subscriptions',
      auth: true,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Create new subscription',
    },
    {
      method: 'PUT',
      path: '/subscriptions/:id',
      auth: true,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Update subscription (upgrade/downgrade)',
    },
    {
      method: 'POST',
      path: '/subscriptions/:id/cancel',
      auth: true,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Cancel subscription',
    },
    {
      method: 'POST',
      path: '/subscriptions/:id/pause',
      auth: true,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Pause subscription',
    },
    {
      method: 'POST',
      path: '/subscriptions/:id/resume',
      auth: true,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Resume paused subscription',
    },
    {
      method: 'POST',
      path: '/subscriptions/:id/reactivate',
      auth: true,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Reactivate cancelled subscription',
    },

    // Billing and invoices
    {
      method: 'GET',
      path: '/subscriptions/:id/invoices',
      auth: true,
      handler: 'crud',
      entity: 'subscription_invoices',
      operation: 'list',
      description: 'Get subscription invoices',
    },
    {
      method: 'GET',
      path: '/invoices/:id',
      auth: true,
      handler: 'crud',
      entity: 'subscription_invoices',
      operation: 'get',
      description: 'Get invoice details',
    },
    {
      method: 'GET',
      path: '/invoices/:id/download',
      auth: true,
      handler: 'custom',
      entity: 'subscription_invoices',
      description: 'Download invoice PDF',
    },

    // Usage tracking
    {
      method: 'GET',
      path: '/subscription/usage',
      auth: true,
      handler: 'crud',
      entity: 'subscription_usage',
      operation: 'list',
      description: 'Get current usage statistics',
    },
    {
      method: 'POST',
      path: '/subscription/usage',
      auth: true,
      handler: 'custom',
      entity: 'subscription_usage',
      description: 'Record usage event',
    },

    // Add-ons
    {
      method: 'GET',
      path: '/subscription/addons',
      auth: true,
      handler: 'crud',
      entity: 'subscription_addons',
      operation: 'list',
      description: 'Get available add-ons',
    },
    {
      method: 'POST',
      path: '/subscription/addons/:addonId',
      auth: true,
      handler: 'custom',
      entity: 'subscription_addons',
      description: 'Add add-on to subscription',
    },
    {
      method: 'DELETE',
      path: '/subscription/addons/:addonId',
      auth: true,
      handler: 'custom',
      entity: 'subscription_addons',
      description: 'Remove add-on from subscription',
    },

    // Admin plan management
    {
      method: 'GET',
      path: '/admin/plans',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'subscription_plans',
      operation: 'list',
      description: 'Admin: list all plans',
    },
    {
      method: 'POST',
      path: '/admin/plans',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'subscription_plans',
      operation: 'create',
      description: 'Admin: create new plan',
    },
    {
      method: 'PUT',
      path: '/admin/plans/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'subscription_plans',
      operation: 'update',
      description: 'Admin: update plan',
    },
    {
      method: 'DELETE',
      path: '/admin/plans/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'subscription_plans',
      operation: 'delete',
      description: 'Admin: delete plan',
    },

    // Admin subscription management
    {
      method: 'GET',
      path: '/admin/subscriptions',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'subscriptions',
      operation: 'list',
      description: 'Admin: list all subscriptions',
    },
    {
      method: 'PUT',
      path: '/admin/subscriptions/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'subscriptions',
      operation: 'update',
      description: 'Admin: update subscription',
    },
    {
      method: 'POST',
      path: '/admin/subscriptions/:id/extend',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Admin: extend subscription',
    },
    {
      method: 'POST',
      path: '/admin/subscriptions/:id/refund',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Admin: process refund',
    },

    // Admin analytics
    {
      method: 'GET',
      path: '/admin/subscriptions/analytics',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'subscriptions',
      description: 'Admin: get subscription analytics',
    },
    {
      method: 'GET',
      path: '/admin/subscriptions/mrr',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'subscriptions',
      description: 'Admin: get MRR metrics',
    },
    {
      method: 'GET',
      path: '/admin/subscriptions/churn',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'subscriptions',
      description: 'Admin: get churn metrics',
    },
    {
      method: 'GET',
      path: '/admin/subscriptions/revenue',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'subscription_invoices',
      description: 'Admin: get revenue report',
    },

    // Webhooks
    {
      method: 'POST',
      path: '/webhooks/subscription',
      auth: false,
      handler: 'custom',
      entity: 'subscriptions',
      description: 'Handle subscription webhook events',
    },
  ],

  // ─────────────────────────────────────────────────────────────
  // CONFIGURATION OPTIONS
  // ─────────────────────────────────────────────────────────────
  config: [
    {
      key: 'enableFreeTrial',
      label: 'Enable Free Trial',
      type: 'boolean',
      default: true,
      description: 'Allow new users to start with a free trial',
    },
    {
      key: 'trialDays',
      label: 'Trial Duration (Days)',
      type: 'number',
      default: 14,
      description: 'Number of days for free trial period',
    },
    {
      key: 'allowPause',
      label: 'Allow Subscription Pause',
      type: 'boolean',
      default: true,
      description: 'Allow users to pause their subscription',
    },
    {
      key: 'maxPauseDays',
      label: 'Maximum Pause Duration (Days)',
      type: 'number',
      default: 90,
      description: 'Maximum days a subscription can be paused',
    },
    {
      key: 'gracePeriodDays',
      label: 'Grace Period (Days)',
      type: 'number',
      default: 3,
      description: 'Days after payment failure before suspension',
    },
    {
      key: 'prorationEnabled',
      label: 'Enable Proration',
      type: 'boolean',
      default: true,
      description: 'Prorate charges when changing plans mid-cycle',
    },
    {
      key: 'defaultBillingCycle',
      label: 'Default Billing Cycle',
      type: 'select',
      default: 'monthly',
      options: [
        { value: 'monthly', label: 'Monthly' },
        { value: 'quarterly', label: 'Quarterly' },
        { value: 'yearly', label: 'Yearly' },
      ],
      description: 'Default billing cycle for new subscriptions',
    },
    {
      key: 'annualDiscount',
      label: 'Annual Discount (%)',
      type: 'number',
      default: 20,
      description: 'Percentage discount for annual billing',
    },
    {
      key: 'cancelAtPeriodEnd',
      label: 'Cancel at Period End',
      type: 'boolean',
      default: true,
      description: 'Continue access until end of billing period after cancellation',
    },
    {
      key: 'enableUsageMetering',
      label: 'Enable Usage Metering',
      type: 'boolean',
      default: false,
      description: 'Track and bill based on usage',
    },
    {
      key: 'sendRenewalReminders',
      label: 'Send Renewal Reminders',
      type: 'boolean',
      default: true,
      description: 'Email reminders before subscription renewal',
    },
    {
      key: 'reminderDaysBefore',
      label: 'Reminder Days Before Renewal',
      type: 'number',
      default: 7,
      description: 'Days before renewal to send reminder',
    },
  ],
};
