/**
 * Customs Documentation Feature Definition
 *
 * Customs documentation management for international logistics.
 * Supports customs forms, compliance, and international shipping documents.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CUSTOMS_DOCS_FEATURE: FeatureDefinition = {
  id: 'customs-docs',
  name: 'Customs Documentation',
  category: 'business',
  description: 'Manage customs documentation, compliance forms, and international shipping paperwork',
  icon: 'file-text',

  includedInAppTypes: [
    'logistics',
    'freight',
    'customs-broker',
    'international-shipping',
    'import-export',
    'freight-forwarder',
    'supply-chain',
    'trade',
  ],

  activationKeywords: [
    'customs documentation',
    'customs forms',
    'customs clearance',
    'customs broker',
    'import documentation',
    'export documentation',
    'commercial invoice',
    'packing list',
    'certificate of origin',
    'bill of lading',
    'customs declaration',
    'hs code',
    'tariff',
    'duty',
    'international shipping',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'shipment-tracking'],
  conflicts: [],

  pages: [
    {
      id: 'customs-dashboard',
      route: '/customs',
      section: 'frontend',
      title: 'Customs Dashboard',
      authRequired: true,
      templateId: 'customs-dashboard',
      components: [
        'customs-stats',
        'pending-clearances',
        'compliance-alerts',
        'recent-documents',
        'duty-estimates-widget',
      ],
      layout: 'dashboard',
    },
    {
      id: 'document-create',
      route: '/customs/documents/new',
      section: 'frontend',
      title: 'Create Document',
      authRequired: true,
      templateId: 'document-create',
      components: [
        'document-type-selector',
        'shipment-selector',
        'document-form',
        'item-list-editor',
        'hs-code-lookup',
        'value-calculator',
        'generate-document-button',
      ],
      layout: 'default',
    },
    {
      id: 'documents-list',
      route: '/customs/documents',
      section: 'frontend',
      title: 'Documents',
      authRequired: true,
      templateId: 'documents-list',
      components: [
        'documents-table',
        'document-filters',
        'document-type-tabs',
        'bulk-actions',
        'export-documents',
      ],
      layout: 'dashboard',
    },
    {
      id: 'document-detail',
      route: '/customs/documents/:id',
      section: 'frontend',
      title: 'Document Details',
      authRequired: true,
      templateId: 'document-detail',
      components: [
        'document-header',
        'document-preview',
        'document-items',
        'compliance-status',
        'document-history',
        'download-button',
        'edit-document-button',
      ],
      layout: 'default',
    },
    {
      id: 'clearance-tracker',
      route: '/customs/clearances',
      section: 'frontend',
      title: 'Clearance Status',
      authRequired: true,
      templateId: 'clearance-tracker',
      components: [
        'clearance-table',
        'clearance-timeline',
        'clearance-filters',
        'holds-alerts',
        'clearance-stats',
      ],
      layout: 'dashboard',
    },
    {
      id: 'duty-calculator',
      route: '/customs/duty-calculator',
      section: 'frontend',
      title: 'Duty Calculator',
      authRequired: false,
      templateId: 'duty-calculator',
      components: [
        'duty-calculator-form',
        'hs-code-search',
        'country-selector',
        'duty-breakdown',
        'trade-agreements',
        'save-calculation',
      ],
      layout: 'default',
    },
    {
      id: 'hs-code-lookup',
      route: '/customs/hs-codes',
      section: 'frontend',
      title: 'HS Code Lookup',
      authRequired: false,
      templateId: 'hs-code-lookup',
      components: [
        'hs-code-search',
        'hs-code-tree',
        'hs-code-details',
        'duty-rates',
        'restrictions-info',
      ],
      layout: 'split',
    },
    {
      id: 'admin-customs',
      route: '/admin/customs',
      section: 'admin',
      title: 'Customs Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-customs',
      components: [
        'customs-config',
        'document-templates',
        'compliance-rules',
        'country-settings',
        'integration-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'customs-stats',
    'pending-clearances',
    'compliance-alerts',
    'recent-documents',
    'duty-estimates-widget',

    // Document creation components
    'document-type-selector',
    'shipment-selector',
    'document-form',
    'item-list-editor',
    'hs-code-lookup',
    'value-calculator',
    'generate-document-button',

    // Document list components
    'documents-table',
    'document-filters',
    'document-type-tabs',
    'bulk-actions',
    'export-documents',

    // Document detail components
    'document-header',
    'document-preview',
    'document-items',
    'compliance-status',
    'document-history',
    'download-button',
    'edit-document-button',

    // Clearance components
    'clearance-table',
    'clearance-timeline',
    'clearance-filters',
    'holds-alerts',
    'clearance-stats',

    // Duty calculator components
    'duty-calculator-form',
    'hs-code-search',
    'country-selector',
    'duty-breakdown',
    'trade-agreements',
    'save-calculation',

    // HS code components
    'hs-code-tree',
    'hs-code-details',
    'duty-rates',
    'restrictions-info',

    // Admin components
    'customs-config',
    'document-templates',
    'compliance-rules',
    'country-settings',
    'integration-settings',
  ],

  entities: [
    {
      name: 'customs_documents',
      displayName: 'Customs Documents',
      description: 'Customs documentation records',
      isCore: true,
    },
    {
      name: 'document_items',
      displayName: 'Document Items',
      description: 'Line items on customs documents',
      isCore: true,
    },
    {
      name: 'clearance_records',
      displayName: 'Clearance Records',
      description: 'Customs clearance status and history',
      isCore: true,
    },
    {
      name: 'hs_codes',
      displayName: 'HS Codes',
      description: 'Harmonized System codes reference',
      isCore: true,
    },
    {
      name: 'duty_calculations',
      displayName: 'Duty Calculations',
      description: 'Saved duty estimates',
      isCore: false,
    },
    {
      name: 'document_templates',
      displayName: 'Document Templates',
      description: 'Reusable document templates',
      isCore: false,
    },
    {
      name: 'trade_agreements',
      displayName: 'Trade Agreements',
      description: 'Trade agreement reference data',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Documents CRUD
    {
      method: 'GET',
      path: '/customs/documents',
      auth: true,
      handler: 'crud',
      entity: 'customs_documents',
      operation: 'list',
      description: 'List customs documents',
    },
    {
      method: 'GET',
      path: '/customs/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'customs_documents',
      operation: 'get',
      description: 'Get document details',
    },
    {
      method: 'POST',
      path: '/customs/documents',
      auth: true,
      handler: 'crud',
      entity: 'customs_documents',
      operation: 'create',
      description: 'Create customs document',
    },
    {
      method: 'PUT',
      path: '/customs/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'customs_documents',
      operation: 'update',
      description: 'Update customs document',
    },
    {
      method: 'DELETE',
      path: '/customs/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'customs_documents',
      operation: 'delete',
      description: 'Delete customs document',
    },

    // Document generation
    {
      method: 'POST',
      path: '/customs/documents/:id/generate',
      auth: true,
      handler: 'custom',
      entity: 'customs_documents',
      description: 'Generate document PDF',
    },
    {
      method: 'GET',
      path: '/customs/documents/:id/download',
      auth: true,
      handler: 'custom',
      entity: 'customs_documents',
      description: 'Download document',
    },

    // Document items
    {
      method: 'GET',
      path: '/customs/documents/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'document_items',
      operation: 'list',
      description: 'Get document items',
    },
    {
      method: 'POST',
      path: '/customs/documents/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'document_items',
      operation: 'create',
      description: 'Add document item',
    },
    {
      method: 'PUT',
      path: '/customs/documents/:docId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'document_items',
      operation: 'update',
      description: 'Update document item',
    },
    {
      method: 'DELETE',
      path: '/customs/documents/:docId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'document_items',
      operation: 'delete',
      description: 'Remove document item',
    },

    // Clearance tracking
    {
      method: 'GET',
      path: '/customs/clearances',
      auth: true,
      handler: 'crud',
      entity: 'clearance_records',
      operation: 'list',
      description: 'List clearance records',
    },
    {
      method: 'GET',
      path: '/customs/clearances/:id',
      auth: true,
      handler: 'crud',
      entity: 'clearance_records',
      operation: 'get',
      description: 'Get clearance status',
    },
    {
      method: 'PUT',
      path: '/customs/clearances/:id/status',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'clearance_records',
      description: 'Update clearance status',
    },

    // HS code lookup
    {
      method: 'GET',
      path: '/customs/hs-codes',
      auth: false,
      handler: 'crud',
      entity: 'hs_codes',
      operation: 'list',
      description: 'Search HS codes',
    },
    {
      method: 'GET',
      path: '/customs/hs-codes/:code',
      auth: false,
      handler: 'crud',
      entity: 'hs_codes',
      operation: 'get',
      description: 'Get HS code details',
    },
    {
      method: 'GET',
      path: '/customs/hs-codes/:code/duty',
      auth: false,
      handler: 'custom',
      entity: 'hs_codes',
      description: 'Get duty rates for HS code',
    },

    // Duty calculator
    {
      method: 'POST',
      path: '/customs/calculate-duty',
      auth: false,
      handler: 'custom',
      entity: 'duty_calculations',
      description: 'Calculate duty and taxes',
    },
    {
      method: 'POST',
      path: '/customs/duty-calculations',
      auth: true,
      handler: 'crud',
      entity: 'duty_calculations',
      operation: 'create',
      description: 'Save duty calculation',
    },
    {
      method: 'GET',
      path: '/customs/duty-calculations',
      auth: true,
      handler: 'crud',
      entity: 'duty_calculations',
      operation: 'list',
      description: 'List saved calculations',
    },

    // Templates
    {
      method: 'GET',
      path: '/customs/templates',
      auth: true,
      handler: 'crud',
      entity: 'document_templates',
      operation: 'list',
      description: 'List document templates',
    },
    {
      method: 'POST',
      path: '/customs/templates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'document_templates',
      operation: 'create',
      description: 'Create document template',
    },

    // Trade agreements
    {
      method: 'GET',
      path: '/customs/trade-agreements',
      auth: false,
      handler: 'crud',
      entity: 'trade_agreements',
      operation: 'list',
      description: 'List trade agreements',
    },
  ],

  config: [
    {
      key: 'defaultOriginCountry',
      label: 'Default Origin Country',
      type: 'string',
      default: 'US',
      description: 'Default country of origin',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for valuations',
    },
    {
      key: 'enableAutoHsCode',
      label: 'Enable Auto HS Code Suggestion',
      type: 'boolean',
      default: true,
      description: 'Suggest HS codes based on description',
    },
    {
      key: 'documentTypes',
      label: 'Enabled Document Types',
      type: 'select',
      default: 'all',
      options: [
        { value: 'all', label: 'All Document Types' },
        { value: 'export', label: 'Export Only' },
        { value: 'import', label: 'Import Only' },
        { value: 'custom', label: 'Custom Selection' },
      ],
      description: 'Which document types to enable',
    },
    {
      key: 'enableComplianceChecks',
      label: 'Enable Compliance Checks',
      type: 'boolean',
      default: true,
      description: 'Validate documents against regulations',
    },
    {
      key: 'complianceStrictness',
      label: 'Compliance Strictness',
      type: 'select',
      default: 'standard',
      options: [
        { value: 'relaxed', label: 'Relaxed' },
        { value: 'standard', label: 'Standard' },
        { value: 'strict', label: 'Strict' },
      ],
      description: 'How strictly to enforce compliance',
    },
    {
      key: 'enableDutyEstimates',
      label: 'Enable Duty Estimates',
      type: 'boolean',
      default: true,
      description: 'Calculate estimated duties',
    },
    {
      key: 'documentRetentionYears',
      label: 'Document Retention (years)',
      type: 'number',
      default: 7,
      description: 'How long to retain customs documents',
    },
  ],
};
