/**
 * Fleet Tracking Feature Definition
 *
 * Vehicle fleet GPS tracking for logistics applications.
 * Supports real-time location, driver behavior, and maintenance tracking.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const FLEET_TRACKING_FEATURE: FeatureDefinition = {
  id: 'fleet-tracking',
  name: 'Fleet Tracking',
  category: 'business',
  description: 'Track vehicle fleet with GPS, monitor driver behavior, and manage vehicle maintenance',
  icon: 'map-pin',

  includedInAppTypes: [
    'logistics',
    'fleet-management',
    'delivery',
    'trucking',
    'transportation',
    'courier',
    'field-service',
    'construction',
  ],

  activationKeywords: [
    'fleet tracking',
    'gps tracking',
    'vehicle tracking',
    'fleet management',
    'truck tracking',
    'driver tracking',
    'real-time tracking',
    'vehicle location',
    'fleet gps',
    'telematics',
    'vehicle monitoring',
    'fleet visibility',
    'asset tracking',
    'driver behavior',
    'vehicle management',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'fleet-map',
      route: '/fleet',
      section: 'frontend',
      title: 'Fleet Map',
      authRequired: true,
      roles: ['dispatcher', 'manager', 'admin'],
      templateId: 'fleet-map',
      components: [
        'live-fleet-map',
        'vehicle-list-sidebar',
        'vehicle-popup',
        'vehicle-filters',
        'geofence-layer',
        'traffic-layer',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'vehicles-list',
      route: '/fleet/vehicles',
      section: 'frontend',
      title: 'Vehicles',
      authRequired: true,
      templateId: 'vehicles-list',
      components: [
        'vehicles-grid',
        'vehicle-card',
        'vehicle-filters',
        'vehicle-status-tabs',
        'add-vehicle-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'vehicle-detail',
      route: '/fleet/vehicles/:id',
      section: 'frontend',
      title: 'Vehicle Details',
      authRequired: true,
      templateId: 'vehicle-detail',
      components: [
        'vehicle-header',
        'vehicle-info',
        'current-location-map',
        'trip-history',
        'maintenance-schedule',
        'driver-assignment',
        'vehicle-documents',
      ],
      layout: 'default',
    },
    {
      id: 'trip-history',
      route: '/fleet/trips',
      section: 'frontend',
      title: 'Trip History',
      authRequired: true,
      templateId: 'trip-history',
      components: [
        'trips-table',
        'trip-filters',
        'trip-map-replay',
        'trip-statistics',
        'export-trips',
      ],
      layout: 'dashboard',
    },
    {
      id: 'driver-scorecards',
      route: '/fleet/drivers',
      section: 'frontend',
      title: 'Driver Scorecards',
      authRequired: true,
      roles: ['manager', 'admin'],
      templateId: 'driver-scorecards',
      components: [
        'drivers-list',
        'driver-scorecard',
        'safety-metrics',
        'driving-events',
        'driver-ranking',
      ],
      layout: 'dashboard',
    },
    {
      id: 'geofences',
      route: '/fleet/geofences',
      section: 'frontend',
      title: 'Geofences',
      authRequired: true,
      roles: ['manager', 'admin'],
      templateId: 'geofences',
      components: [
        'geofence-map',
        'geofence-list',
        'geofence-form',
        'geofence-alerts',
        'entry-exit-log',
      ],
      layout: 'split',
    },
    {
      id: 'maintenance',
      route: '/fleet/maintenance',
      section: 'frontend',
      title: 'Maintenance',
      authRequired: true,
      templateId: 'maintenance',
      components: [
        'maintenance-calendar',
        'due-maintenance',
        'maintenance-history',
        'service-reminders',
        'maintenance-form',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-fleet',
      route: '/admin/fleet',
      section: 'admin',
      title: 'Fleet Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-fleet',
      components: [
        'fleet-config',
        'gps-device-settings',
        'alert-rules',
        'fuel-settings',
        'integration-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Map components
    'live-fleet-map',
    'vehicle-list-sidebar',
    'vehicle-popup',
    'vehicle-filters',
    'geofence-layer',
    'traffic-layer',

    // Vehicle components
    'vehicles-grid',
    'vehicle-card',
    'vehicle-status-tabs',
    'add-vehicle-button',
    'vehicle-header',
    'vehicle-info',
    'current-location-map',
    'trip-history',
    'maintenance-schedule',
    'driver-assignment',
    'vehicle-documents',

    // Trip components
    'trips-table',
    'trip-filters',
    'trip-map-replay',
    'trip-statistics',
    'export-trips',

    // Driver components
    'drivers-list',
    'driver-scorecard',
    'safety-metrics',
    'driving-events',
    'driver-ranking',

    // Geofence components
    'geofence-map',
    'geofence-list',
    'geofence-form',
    'geofence-alerts',
    'entry-exit-log',

    // Maintenance components
    'maintenance-calendar',
    'due-maintenance',
    'maintenance-history',
    'service-reminders',
    'maintenance-form',

    // Admin components
    'fleet-config',
    'gps-device-settings',
    'alert-rules',
    'fuel-settings',
    'integration-settings',
  ],

  entities: [
    {
      name: 'vehicles',
      displayName: 'Vehicles',
      description: 'Fleet vehicle records',
      isCore: true,
    },
    {
      name: 'vehicle_locations',
      displayName: 'Vehicle Locations',
      description: 'GPS location history',
      isCore: true,
    },
    {
      name: 'vehicle_trips',
      displayName: 'Vehicle Trips',
      description: 'Trip records with route data',
      isCore: true,
    },
    {
      name: 'driving_events',
      displayName: 'Driving Events',
      description: 'Harsh braking, speeding, etc.',
      isCore: true,
    },
    {
      name: 'geofences',
      displayName: 'Geofences',
      description: 'Geographic boundary definitions',
      isCore: false,
    },
    {
      name: 'geofence_events',
      displayName: 'Geofence Events',
      description: 'Entry/exit event logs',
      isCore: false,
    },
    {
      name: 'vehicle_maintenance',
      displayName: 'Vehicle Maintenance',
      description: 'Maintenance records and schedules',
      isCore: false,
    },
    {
      name: 'fuel_records',
      displayName: 'Fuel Records',
      description: 'Fuel purchase and consumption logs',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Vehicles CRUD
    {
      method: 'GET',
      path: '/vehicles',
      auth: true,
      handler: 'crud',
      entity: 'vehicles',
      operation: 'list',
      description: 'List vehicles',
    },
    {
      method: 'GET',
      path: '/vehicles/:id',
      auth: true,
      handler: 'crud',
      entity: 'vehicles',
      operation: 'get',
      description: 'Get vehicle details',
    },
    {
      method: 'POST',
      path: '/vehicles',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vehicles',
      operation: 'create',
      description: 'Add vehicle',
    },
    {
      method: 'PUT',
      path: '/vehicles/:id',
      auth: true,
      handler: 'crud',
      entity: 'vehicles',
      operation: 'update',
      description: 'Update vehicle',
    },
    {
      method: 'DELETE',
      path: '/vehicles/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vehicles',
      operation: 'delete',
      description: 'Remove vehicle',
    },

    // Live tracking
    {
      method: 'GET',
      path: '/vehicles/locations',
      auth: true,
      handler: 'custom',
      entity: 'vehicle_locations',
      description: 'Get all vehicle locations',
    },
    {
      method: 'GET',
      path: '/vehicles/:id/location',
      auth: true,
      handler: 'custom',
      entity: 'vehicle_locations',
      description: 'Get vehicle current location',
    },
    {
      method: 'GET',
      path: '/vehicles/:id/location/history',
      auth: true,
      handler: 'crud',
      entity: 'vehicle_locations',
      operation: 'list',
      description: 'Get vehicle location history',
    },

    // Trips
    {
      method: 'GET',
      path: '/vehicles/:id/trips',
      auth: true,
      handler: 'crud',
      entity: 'vehicle_trips',
      operation: 'list',
      description: 'Get vehicle trips',
    },
    {
      method: 'GET',
      path: '/trips/:id',
      auth: true,
      handler: 'crud',
      entity: 'vehicle_trips',
      operation: 'get',
      description: 'Get trip details',
    },
    {
      method: 'GET',
      path: '/trips/:id/replay',
      auth: true,
      handler: 'custom',
      entity: 'vehicle_trips',
      description: 'Get trip replay data',
    },

    // Driving events
    {
      method: 'GET',
      path: '/driving-events',
      auth: true,
      handler: 'crud',
      entity: 'driving_events',
      operation: 'list',
      description: 'List driving events',
    },
    {
      method: 'GET',
      path: '/drivers/:id/scorecard',
      auth: true,
      handler: 'custom',
      entity: 'driving_events',
      description: 'Get driver scorecard',
    },

    // Geofences
    {
      method: 'GET',
      path: '/geofences',
      auth: true,
      handler: 'crud',
      entity: 'geofences',
      operation: 'list',
      description: 'List geofences',
    },
    {
      method: 'POST',
      path: '/geofences',
      auth: true,
      role: 'manager',
      handler: 'crud',
      entity: 'geofences',
      operation: 'create',
      description: 'Create geofence',
    },
    {
      method: 'PUT',
      path: '/geofences/:id',
      auth: true,
      handler: 'crud',
      entity: 'geofences',
      operation: 'update',
      description: 'Update geofence',
    },
    {
      method: 'DELETE',
      path: '/geofences/:id',
      auth: true,
      handler: 'crud',
      entity: 'geofences',
      operation: 'delete',
      description: 'Delete geofence',
    },
    {
      method: 'GET',
      path: '/geofences/:id/events',
      auth: true,
      handler: 'crud',
      entity: 'geofence_events',
      operation: 'list',
      description: 'Get geofence events',
    },

    // Maintenance
    {
      method: 'GET',
      path: '/vehicles/:id/maintenance',
      auth: true,
      handler: 'crud',
      entity: 'vehicle_maintenance',
      operation: 'list',
      description: 'Get vehicle maintenance',
    },
    {
      method: 'POST',
      path: '/vehicles/:id/maintenance',
      auth: true,
      handler: 'crud',
      entity: 'vehicle_maintenance',
      operation: 'create',
      description: 'Add maintenance record',
    },
    {
      method: 'GET',
      path: '/maintenance/due',
      auth: true,
      handler: 'custom',
      entity: 'vehicle_maintenance',
      description: 'Get due maintenance',
    },

    // Fuel
    {
      method: 'GET',
      path: '/vehicles/:id/fuel',
      auth: true,
      handler: 'crud',
      entity: 'fuel_records',
      operation: 'list',
      description: 'Get fuel records',
    },
    {
      method: 'POST',
      path: '/vehicles/:id/fuel',
      auth: true,
      handler: 'crud',
      entity: 'fuel_records',
      operation: 'create',
      description: 'Add fuel record',
    },
  ],

  config: [
    {
      key: 'updateInterval',
      label: 'Location Update Interval (seconds)',
      type: 'number',
      default: 30,
      description: 'How often to update vehicle locations',
    },
    {
      key: 'enableRealTimeTracking',
      label: 'Enable Real-Time Tracking',
      type: 'boolean',
      default: true,
      description: 'Use WebSocket for live updates',
    },
    {
      key: 'speedingThreshold',
      label: 'Speeding Threshold (mph)',
      type: 'number',
      default: 70,
      description: 'Speed at which to record speeding events',
    },
    {
      key: 'harshBrakingThreshold',
      label: 'Harsh Braking Threshold (g)',
      type: 'number',
      default: 0.4,
      description: 'G-force threshold for harsh braking',
    },
    {
      key: 'idleTimeThreshold',
      label: 'Idle Time Threshold (minutes)',
      type: 'number',
      default: 5,
      description: 'Minutes before recording idle event',
    },
    {
      key: 'enableGeofenceAlerts',
      label: 'Enable Geofence Alerts',
      type: 'boolean',
      default: true,
      description: 'Send alerts for geofence entry/exit',
    },
    {
      key: 'tripAutoDetection',
      label: 'Auto-Detect Trips',
      type: 'boolean',
      default: true,
      description: 'Automatically detect trip start/end',
    },
    {
      key: 'mapProvider',
      label: 'Map Provider',
      type: 'select',
      default: 'google',
      options: [
        { value: 'google', label: 'Google Maps' },
        { value: 'mapbox', label: 'Mapbox' },
        { value: 'here', label: 'HERE Maps' },
        { value: 'openstreetmap', label: 'OpenStreetMap' },
      ],
      description: 'Map provider for fleet visualization',
    },
    {
      key: 'dataRetentionDays',
      label: 'Data Retention (days)',
      type: 'number',
      default: 90,
      description: 'How long to keep location history',
    },
  ],
};
