/**
 * Freight Quotes Feature Definition
 *
 * Freight rate calculation and quoting for logistics applications.
 * Supports multiple carriers, rate comparison, and quote management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const FREIGHT_QUOTES_FEATURE: FeatureDefinition = {
  id: 'freight-quotes',
  name: 'Freight Quotes',
  category: 'business',
  description: 'Calculate freight rates, compare carrier quotes, and manage shipping cost estimates',
  icon: 'calculator',

  includedInAppTypes: [
    'logistics',
    'freight',
    'shipping',
    'freight-broker',
    'supply-chain',
    '3pl',
    'carrier',
    'trucking',
  ],

  activationKeywords: [
    'freight quote',
    'freight rate',
    'shipping quote',
    'shipping rate',
    'freight calculator',
    'rate calculation',
    'freight cost',
    'shipping cost',
    'freight estimate',
    'carrier rates',
    'ltl quote',
    'ftl quote',
    'trucking rate',
    'cargo rate',
    'freight pricing',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'quote-calculator',
      route: '/quotes/new',
      section: 'frontend',
      title: 'Get Quote',
      authRequired: false,
      templateId: 'quote-calculator',
      components: [
        'quote-form',
        'origin-destination-input',
        'freight-class-selector',
        'dimensions-input',
        'weight-input',
        'accessorial-options',
        'service-level-picker',
      ],
      layout: 'default',
    },
    {
      id: 'quote-results',
      route: '/quotes/results',
      section: 'frontend',
      title: 'Quote Results',
      authRequired: false,
      templateId: 'quote-results',
      components: [
        'carrier-comparison',
        'rate-card',
        'transit-time-display',
        'service-details',
        'book-now-button',
        'save-quote-button',
        'email-quote-button',
      ],
      layout: 'default',
    },
    {
      id: 'my-quotes',
      route: '/quotes',
      section: 'frontend',
      title: 'My Quotes',
      authRequired: true,
      templateId: 'my-quotes',
      components: [
        'quotes-list',
        'quote-filters',
        'quote-status-tabs',
        'quote-card',
        'quote-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'quote-detail',
      route: '/quotes/:id',
      section: 'frontend',
      title: 'Quote Details',
      authRequired: true,
      templateId: 'quote-detail',
      components: [
        'quote-header',
        'shipment-summary',
        'rate-breakdown',
        'carrier-details',
        'quote-timeline',
        'convert-to-shipment',
        'requote-button',
      ],
      layout: 'default',
    },
    {
      id: 'rate-management',
      route: '/admin/rates',
      section: 'admin',
      title: 'Rate Management',
      authRequired: true,
      roles: ['admin'],
      templateId: 'rate-management',
      components: [
        'rate-tables',
        'lane-rates',
        'accessorial-charges',
        'fuel-surcharge',
        'rate-upload',
        'rate-history',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-quotes',
      route: '/admin/quotes',
      section: 'admin',
      title: 'Manage Quotes',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-quotes',
      components: [
        'quotes-table',
        'quote-filters',
        'bulk-actions',
        'quote-analytics',
        'conversion-report',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calculator components
    'quote-form',
    'origin-destination-input',
    'freight-class-selector',
    'dimensions-input',
    'weight-input',
    'accessorial-options',
    'service-level-picker',

    // Results components
    'carrier-comparison',
    'rate-card',
    'transit-time-display',
    'service-details',
    'book-now-button',
    'save-quote-button',
    'email-quote-button',

    // List components
    'quotes-list',
    'quote-filters',
    'quote-status-tabs',
    'quote-card',
    'quote-actions',

    // Detail components
    'quote-header',
    'shipment-summary',
    'rate-breakdown',
    'carrier-details',
    'quote-timeline',
    'convert-to-shipment',
    'requote-button',

    // Admin components
    'rate-tables',
    'lane-rates',
    'accessorial-charges',
    'fuel-surcharge',
    'rate-upload',
    'rate-history',
    'quotes-table',
    'bulk-actions',
    'quote-analytics',
    'conversion-report',
  ],

  entities: [
    {
      name: 'freight_quotes',
      displayName: 'Freight Quotes',
      description: 'Quote requests and results',
      isCore: true,
    },
    {
      name: 'quote_rates',
      displayName: 'Quote Rates',
      description: 'Individual carrier rates for quotes',
      isCore: true,
    },
    {
      name: 'rate_tables',
      displayName: 'Rate Tables',
      description: 'Base rate configurations',
      isCore: true,
    },
    {
      name: 'lane_rates',
      displayName: 'Lane Rates',
      description: 'Origin-destination specific rates',
      isCore: false,
    },
    {
      name: 'accessorial_charges',
      displayName: 'Accessorial Charges',
      description: 'Additional service charges',
      isCore: false,
    },
    {
      name: 'fuel_surcharges',
      displayName: 'Fuel Surcharges',
      description: 'Fuel surcharge schedules',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Quote CRUD
    {
      method: 'GET',
      path: '/quotes',
      auth: true,
      handler: 'crud',
      entity: 'freight_quotes',
      operation: 'list',
      description: 'List user quotes',
    },
    {
      method: 'GET',
      path: '/quotes/:id',
      auth: true,
      handler: 'crud',
      entity: 'freight_quotes',
      operation: 'get',
      description: 'Get quote details',
    },
    {
      method: 'POST',
      path: '/quotes',
      auth: false,
      handler: 'custom',
      entity: 'freight_quotes',
      description: 'Request new quote',
    },
    {
      method: 'DELETE',
      path: '/quotes/:id',
      auth: true,
      handler: 'crud',
      entity: 'freight_quotes',
      operation: 'delete',
      description: 'Delete quote',
    },

    // Rate calculation
    {
      method: 'POST',
      path: '/quotes/calculate',
      auth: false,
      handler: 'custom',
      entity: 'freight_quotes',
      description: 'Calculate freight rates',
    },
    {
      method: 'POST',
      path: '/quotes/:id/requote',
      auth: true,
      handler: 'custom',
      entity: 'freight_quotes',
      description: 'Request updated rates',
    },

    // Quote actions
    {
      method: 'POST',
      path: '/quotes/:id/save',
      auth: true,
      handler: 'custom',
      entity: 'freight_quotes',
      description: 'Save quote for later',
    },
    {
      method: 'POST',
      path: '/quotes/:id/email',
      auth: true,
      handler: 'custom',
      entity: 'freight_quotes',
      description: 'Email quote',
    },
    {
      method: 'POST',
      path: '/quotes/:id/book',
      auth: true,
      handler: 'custom',
      entity: 'freight_quotes',
      description: 'Convert quote to shipment',
    },

    // Rate tables (admin)
    {
      method: 'GET',
      path: '/admin/rate-tables',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'rate_tables',
      operation: 'list',
      description: 'List rate tables',
    },
    {
      method: 'POST',
      path: '/admin/rate-tables',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'rate_tables',
      operation: 'create',
      description: 'Create rate table',
    },
    {
      method: 'PUT',
      path: '/admin/rate-tables/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'rate_tables',
      operation: 'update',
      description: 'Update rate table',
    },
    {
      method: 'POST',
      path: '/admin/rate-tables/upload',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'rate_tables',
      description: 'Upload rate table from file',
    },

    // Lane rates
    {
      method: 'GET',
      path: '/admin/lane-rates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'lane_rates',
      operation: 'list',
      description: 'List lane rates',
    },
    {
      method: 'POST',
      path: '/admin/lane-rates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'lane_rates',
      operation: 'create',
      description: 'Create lane rate',
    },

    // Accessorials
    {
      method: 'GET',
      path: '/accessorials',
      auth: false,
      handler: 'crud',
      entity: 'accessorial_charges',
      operation: 'list',
      description: 'List accessorial options',
    },

    // Fuel surcharge
    {
      method: 'GET',
      path: '/fuel-surcharge/current',
      auth: false,
      handler: 'custom',
      entity: 'fuel_surcharges',
      description: 'Get current fuel surcharge',
    },
  ],

  config: [
    {
      key: 'enableMultiCarrierQuotes',
      label: 'Enable Multi-Carrier Quotes',
      type: 'boolean',
      default: true,
      description: 'Fetch rates from multiple carriers',
    },
    {
      key: 'quoteValidityDays',
      label: 'Quote Validity (days)',
      type: 'number',
      default: 7,
      description: 'How long quotes remain valid',
    },
    {
      key: 'defaultFreightClass',
      label: 'Default Freight Class',
      type: 'select',
      default: '70',
      options: [
        { value: '50', label: 'Class 50' },
        { value: '55', label: 'Class 55' },
        { value: '60', label: 'Class 60' },
        { value: '65', label: 'Class 65' },
        { value: '70', label: 'Class 70' },
        { value: '77.5', label: 'Class 77.5' },
        { value: '85', label: 'Class 85' },
        { value: '92.5', label: 'Class 92.5' },
        { value: '100', label: 'Class 100' },
      ],
      description: 'Default freight class for quotes',
    },
    {
      key: 'enableDimensionalWeight',
      label: 'Enable Dimensional Weight',
      type: 'boolean',
      default: true,
      description: 'Calculate rates using dimensional weight',
    },
    {
      key: 'dimensionalFactor',
      label: 'Dimensional Factor',
      type: 'number',
      default: 139,
      description: 'Dimensional weight divisor',
    },
    {
      key: 'fuelSurchargeMethod',
      label: 'Fuel Surcharge Method',
      type: 'select',
      default: 'doe-index',
      options: [
        { value: 'doe-index', label: 'DOE Index' },
        { value: 'fixed-percentage', label: 'Fixed Percentage' },
        { value: 'per-mile', label: 'Per Mile' },
        { value: 'custom', label: 'Custom Schedule' },
      ],
      description: 'How to calculate fuel surcharges',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for quotes',
    },
  ],
};
