/**
 * Warehouse Management Feature Definition
 *
 * Complete warehouse and inventory management for logistics applications.
 * Supports inventory tracking, bin locations, picking, and receiving.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const WAREHOUSE_MGMT_FEATURE: FeatureDefinition = {
  id: 'warehouse-mgmt',
  name: 'Warehouse Management',
  category: 'business',
  description: 'Manage warehouse operations including inventory, bin locations, picking orders, and receiving',
  icon: 'warehouse',

  includedInAppTypes: [
    'logistics',
    'warehouse',
    'fulfillment',
    'inventory',
    'distribution',
    '3pl',
    'supply-chain',
    'ecommerce',
  ],

  activationKeywords: [
    'warehouse management',
    'warehouse',
    'inventory management',
    'stock management',
    'bin location',
    'storage location',
    'picking',
    'packing',
    'receiving',
    'putaway',
    'wms',
    'warehouse system',
    'stock control',
    'inventory tracking',
    'warehouse inventory',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'inventory'],
  conflicts: [],

  pages: [
    {
      id: 'warehouse-dashboard',
      route: '/warehouse',
      section: 'frontend',
      title: 'Warehouse Dashboard',
      authRequired: true,
      roles: ['warehouse-staff', 'manager', 'admin'],
      templateId: 'warehouse-dashboard',
      components: [
        'warehouse-stats',
        'pending-orders-widget',
        'low-stock-alerts',
        'recent-activity',
        'warehouse-map-overview',
      ],
      layout: 'dashboard',
    },
    {
      id: 'inventory-list',
      route: '/warehouse/inventory',
      section: 'frontend',
      title: 'Inventory',
      authRequired: true,
      templateId: 'inventory-list',
      components: [
        'inventory-table',
        'inventory-filters',
        'stock-level-badges',
        'bulk-actions',
        'export-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'bin-locations',
      route: '/warehouse/locations',
      section: 'frontend',
      title: 'Bin Locations',
      authRequired: true,
      roles: ['warehouse-staff', 'manager', 'admin'],
      templateId: 'bin-locations',
      components: [
        'warehouse-map',
        'location-tree',
        'bin-details',
        'location-form',
        'move-inventory-modal',
      ],
      layout: 'split',
    },
    {
      id: 'picking-queue',
      route: '/warehouse/picking',
      section: 'frontend',
      title: 'Picking Queue',
      authRequired: true,
      roles: ['picker', 'warehouse-staff', 'admin'],
      templateId: 'picking-queue',
      components: [
        'pick-list-queue',
        'pick-order-card',
        'priority-filter',
        'assign-picker-modal',
        'batch-picking-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'picking-detail',
      route: '/warehouse/picking/:id',
      section: 'frontend',
      title: 'Pick Order',
      authRequired: true,
      roles: ['picker', 'warehouse-staff', 'admin'],
      templateId: 'picking-detail',
      components: [
        'pick-header',
        'pick-items-list',
        'scan-input',
        'pick-confirmation',
        'shortage-report',
        'complete-pick-button',
      ],
      layout: 'default',
    },
    {
      id: 'receiving',
      route: '/warehouse/receiving',
      section: 'frontend',
      title: 'Receiving',
      authRequired: true,
      roles: ['receiver', 'warehouse-staff', 'admin'],
      templateId: 'receiving',
      components: [
        'expected-shipments',
        'receiving-form',
        'po-lookup',
        'scan-receiving',
        'discrepancy-report',
        'putaway-assignment',
      ],
      layout: 'dashboard',
    },
    {
      id: 'cycle-count',
      route: '/warehouse/cycle-count',
      section: 'frontend',
      title: 'Cycle Count',
      authRequired: true,
      roles: ['warehouse-staff', 'manager', 'admin'],
      templateId: 'cycle-count',
      components: [
        'count-schedule',
        'count-locations',
        'count-entry-form',
        'variance-report',
        'count-history',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-warehouse',
      route: '/admin/warehouse',
      section: 'admin',
      title: 'Warehouse Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-warehouse',
      components: [
        'warehouse-config',
        'location-setup',
        'workflow-settings',
        'user-permissions',
        'integration-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'warehouse-stats',
    'pending-orders-widget',
    'low-stock-alerts',
    'recent-activity',
    'warehouse-map-overview',

    // Inventory components
    'inventory-table',
    'inventory-filters',
    'stock-level-badges',
    'bulk-actions',
    'export-button',

    // Location components
    'warehouse-map',
    'location-tree',
    'bin-details',
    'location-form',
    'move-inventory-modal',

    // Picking components
    'pick-list-queue',
    'pick-order-card',
    'priority-filter',
    'assign-picker-modal',
    'batch-picking-button',
    'pick-header',
    'pick-items-list',
    'scan-input',
    'pick-confirmation',
    'shortage-report',
    'complete-pick-button',

    // Receiving components
    'expected-shipments',
    'receiving-form',
    'po-lookup',
    'scan-receiving',
    'discrepancy-report',
    'putaway-assignment',

    // Cycle count components
    'count-schedule',
    'count-locations',
    'count-entry-form',
    'variance-report',
    'count-history',

    // Admin components
    'warehouse-config',
    'location-setup',
    'workflow-settings',
    'user-permissions',
    'integration-settings',
  ],

  entities: [
    {
      name: 'warehouses',
      displayName: 'Warehouses',
      description: 'Warehouse facility records',
      isCore: true,
    },
    {
      name: 'bin_locations',
      displayName: 'Bin Locations',
      description: 'Storage locations within warehouses',
      isCore: true,
    },
    {
      name: 'warehouse_inventory',
      displayName: 'Warehouse Inventory',
      description: 'Inventory levels by location',
      isCore: true,
    },
    {
      name: 'pick_orders',
      displayName: 'Pick Orders',
      description: 'Orders to be picked from warehouse',
      isCore: true,
    },
    {
      name: 'pick_items',
      displayName: 'Pick Items',
      description: 'Individual items in pick orders',
      isCore: true,
    },
    {
      name: 'receiving_records',
      displayName: 'Receiving Records',
      description: 'Inbound shipment receiving logs',
      isCore: false,
    },
    {
      name: 'inventory_movements',
      displayName: 'Inventory Movements',
      description: 'History of inventory transfers',
      isCore: false,
    },
    {
      name: 'cycle_counts',
      displayName: 'Cycle Counts',
      description: 'Inventory count records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Warehouse CRUD
    {
      method: 'GET',
      path: '/warehouses',
      auth: true,
      handler: 'crud',
      entity: 'warehouses',
      operation: 'list',
      description: 'List warehouses',
    },
    {
      method: 'GET',
      path: '/warehouses/:id',
      auth: true,
      handler: 'crud',
      entity: 'warehouses',
      operation: 'get',
      description: 'Get warehouse details',
    },
    {
      method: 'POST',
      path: '/warehouses',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'warehouses',
      operation: 'create',
      description: 'Create warehouse',
    },
    {
      method: 'PUT',
      path: '/warehouses/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'warehouses',
      operation: 'update',
      description: 'Update warehouse',
    },

    // Bin locations
    {
      method: 'GET',
      path: '/warehouses/:id/locations',
      auth: true,
      handler: 'crud',
      entity: 'bin_locations',
      operation: 'list',
      description: 'List bin locations',
    },
    {
      method: 'POST',
      path: '/warehouses/:id/locations',
      auth: true,
      role: 'manager',
      handler: 'crud',
      entity: 'bin_locations',
      operation: 'create',
      description: 'Create bin location',
    },
    {
      method: 'PUT',
      path: '/locations/:id',
      auth: true,
      handler: 'crud',
      entity: 'bin_locations',
      operation: 'update',
      description: 'Update bin location',
    },

    // Inventory
    {
      method: 'GET',
      path: '/warehouse/inventory',
      auth: true,
      handler: 'crud',
      entity: 'warehouse_inventory',
      operation: 'list',
      description: 'List warehouse inventory',
    },
    {
      method: 'GET',
      path: '/warehouse/inventory/:sku',
      auth: true,
      handler: 'custom',
      entity: 'warehouse_inventory',
      description: 'Get inventory by SKU across locations',
    },
    {
      method: 'POST',
      path: '/warehouse/inventory/move',
      auth: true,
      role: 'warehouse-staff',
      handler: 'custom',
      entity: 'inventory_movements',
      description: 'Move inventory between locations',
    },
    {
      method: 'POST',
      path: '/warehouse/inventory/adjust',
      auth: true,
      role: 'manager',
      handler: 'custom',
      entity: 'warehouse_inventory',
      description: 'Adjust inventory quantity',
    },

    // Picking
    {
      method: 'GET',
      path: '/warehouse/picking',
      auth: true,
      handler: 'crud',
      entity: 'pick_orders',
      operation: 'list',
      description: 'List pick orders',
    },
    {
      method: 'GET',
      path: '/warehouse/picking/:id',
      auth: true,
      handler: 'crud',
      entity: 'pick_orders',
      operation: 'get',
      description: 'Get pick order details',
    },
    {
      method: 'POST',
      path: '/warehouse/picking/:id/assign',
      auth: true,
      role: 'manager',
      handler: 'custom',
      entity: 'pick_orders',
      description: 'Assign picker to order',
    },
    {
      method: 'PUT',
      path: '/warehouse/picking/:id/items/:itemId/pick',
      auth: true,
      role: 'picker',
      handler: 'custom',
      entity: 'pick_items',
      description: 'Confirm item picked',
    },
    {
      method: 'PUT',
      path: '/warehouse/picking/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'pick_orders',
      description: 'Complete pick order',
    },

    // Receiving
    {
      method: 'GET',
      path: '/warehouse/receiving',
      auth: true,
      handler: 'crud',
      entity: 'receiving_records',
      operation: 'list',
      description: 'List receiving records',
    },
    {
      method: 'POST',
      path: '/warehouse/receiving',
      auth: true,
      role: 'receiver',
      handler: 'crud',
      entity: 'receiving_records',
      operation: 'create',
      description: 'Create receiving record',
    },
    {
      method: 'POST',
      path: '/warehouse/receiving/:id/putaway',
      auth: true,
      role: 'warehouse-staff',
      handler: 'custom',
      entity: 'warehouse_inventory',
      description: 'Putaway received inventory',
    },

    // Cycle count
    {
      method: 'GET',
      path: '/warehouse/cycle-counts',
      auth: true,
      handler: 'crud',
      entity: 'cycle_counts',
      operation: 'list',
      description: 'List cycle counts',
    },
    {
      method: 'POST',
      path: '/warehouse/cycle-counts',
      auth: true,
      role: 'manager',
      handler: 'crud',
      entity: 'cycle_counts',
      operation: 'create',
      description: 'Create cycle count',
    },
    {
      method: 'PUT',
      path: '/warehouse/cycle-counts/:id/count',
      auth: true,
      handler: 'custom',
      entity: 'cycle_counts',
      description: 'Submit count entry',
    },
  ],

  config: [
    {
      key: 'enableBarcodeScanning',
      label: 'Enable Barcode Scanning',
      type: 'boolean',
      default: true,
      description: 'Use barcode scanning for operations',
    },
    {
      key: 'enableBatchPicking',
      label: 'Enable Batch Picking',
      type: 'boolean',
      default: true,
      description: 'Allow picking multiple orders at once',
    },
    {
      key: 'locationNamingScheme',
      label: 'Location Naming Scheme',
      type: 'select',
      default: 'aisle-rack-shelf',
      options: [
        { value: 'aisle-rack-shelf', label: 'Aisle-Rack-Shelf (A01-R02-S03)' },
        { value: 'zone-row-bin', label: 'Zone-Row-Bin (Z1-R01-B001)' },
        { value: 'alphanumeric', label: 'Alphanumeric (ABC123)' },
        { value: 'custom', label: 'Custom Format' },
      ],
      description: 'How to name bin locations',
    },
    {
      key: 'lowStockThreshold',
      label: 'Low Stock Alert Threshold',
      type: 'number',
      default: 10,
      description: 'Alert when stock falls below this level',
    },
    {
      key: 'enableFifoTracking',
      label: 'Enable FIFO Tracking',
      type: 'boolean',
      default: true,
      description: 'Track first-in-first-out for inventory',
    },
    {
      key: 'requirePickConfirmation',
      label: 'Require Pick Confirmation',
      type: 'boolean',
      default: true,
      description: 'Require scan confirmation for each pick',
    },
    {
      key: 'cycleCountFrequency',
      label: 'Cycle Count Frequency',
      type: 'select',
      default: 'weekly',
      options: [
        { value: 'daily', label: 'Daily' },
        { value: 'weekly', label: 'Weekly' },
        { value: 'monthly', label: 'Monthly' },
        { value: 'quarterly', label: 'Quarterly' },
      ],
      description: 'How often to schedule cycle counts',
    },
  ],
};
