/**
 * Body Measurements Feature Definition
 *
 * Complete body composition tracking functionality including
 * measurements, progress photos, and fitness goal tracking.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const BODY_MEASUREMENTS_FEATURE: FeatureDefinition = {
  id: 'body-measurements',
  name: 'Body Measurements',
  category: 'fitness',
  description: 'Track body measurements, progress photos, and fitness goals for transformation tracking',
  icon: 'ruler',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'body measurements',
    'body composition',
    'progress tracking',
    'progress photos',
    'body stats',
    'weight tracking',
    'body fat',
    'measurements log',
    'transformation tracking',
    'before after photos',
    'fitness goals',
    'body metrics',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'file-upload'],
  conflicts: [],

  pages: [
    {
      id: 'measurements-log',
      route: '/measurements',
      section: 'frontend',
      title: 'Body Measurements',
      authRequired: true,
      templateId: 'measurements-log',
      components: [
        'measurement-form',
        'measurements-history',
        'measurement-chart',
        'quick-log',
        'comparison-view',
      ],
      layout: 'dashboard',
    },
    {
      id: 'progress-photos',
      route: '/progress-photos',
      section: 'frontend',
      title: 'Progress Photos',
      authRequired: true,
      templateId: 'progress-photos',
      components: [
        'photo-upload',
        'photo-gallery',
        'photo-comparison',
        'timeline-slider',
        'pose-guide',
      ],
      layout: 'default',
    },
    {
      id: 'body-stats',
      route: '/body-stats',
      section: 'frontend',
      title: 'Body Statistics',
      authRequired: true,
      templateId: 'body-stats',
      components: [
        'stat-chart',
        'bmi-calculator',
        'body-fat-estimator',
        'ideal-weight',
        'progress-summary',
      ],
      layout: 'dashboard',
    },
    {
      id: 'fitness-goals',
      route: '/goals',
      section: 'frontend',
      title: 'Fitness Goals',
      authRequired: true,
      templateId: 'fitness-goals',
      components: [
        'goal-tracker',
        'goal-form',
        'milestone-list',
        'goal-progress',
        'goal-celebration',
      ],
      layout: 'dashboard',
    },
    {
      id: 'transformation-timeline',
      route: '/transformation',
      section: 'frontend',
      title: 'My Transformation',
      authRequired: true,
      templateId: 'transformation-timeline',
      components: [
        'timeline-view',
        'before-after',
        'stats-comparison',
        'achievement-badges',
        'share-button',
      ],
      layout: 'default',
    },
  ],

  components: [
    // Measurement components
    'measurement-form',
    'measurements-history',
    'measurement-chart',
    'quick-log',
    'comparison-view',
    'measurement-card',

    // Photo components
    'photo-upload',
    'photo-gallery',
    'photo-comparison',
    'timeline-slider',
    'pose-guide',
    'photo-overlay',
    'before-after',

    // Stats components
    'stat-chart',
    'bmi-calculator',
    'body-fat-estimator',
    'ideal-weight',
    'progress-summary',
    'trend-indicator',

    // Goal components
    'goal-tracker',
    'goal-form',
    'milestone-list',
    'goal-progress',
    'goal-celebration',
    'goal-card',

    // Timeline components
    'timeline-view',
    'stats-comparison',
    'achievement-badges',
    'share-button',
    'export-report',
  ],

  entities: [
    {
      name: 'body_measurements',
      displayName: 'Body Measurements',
      description: 'Recorded body measurements over time',
      isCore: true,
    },
    {
      name: 'progress_photos',
      displayName: 'Progress Photos',
      description: 'Transformation progress photos',
      isCore: true,
    },
    {
      name: 'fitness_goals',
      displayName: 'Fitness Goals',
      description: 'User fitness goals and targets',
      isCore: true,
    },
    {
      name: 'goal_milestones',
      displayName: 'Goal Milestones',
      description: 'Milestone checkpoints for goals',
      isCore: false,
    },
    {
      name: 'measurement_types',
      displayName: 'Measurement Types',
      description: 'Types of body measurements to track',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Body Measurements routes
    {
      method: 'GET',
      path: '/body-measurements',
      auth: true,
      handler: 'crud',
      entity: 'body_measurements',
      description: 'List user measurements',
    },
    {
      method: 'POST',
      path: '/body-measurements',
      auth: true,
      handler: 'crud',
      entity: 'body_measurements',
      description: 'Log new measurements',
    },
    {
      method: 'GET',
      path: '/body-measurements/:id',
      auth: true,
      handler: 'crud',
      entity: 'body_measurements',
      description: 'Get measurement entry',
    },
    {
      method: 'PUT',
      path: '/body-measurements/:id',
      auth: true,
      handler: 'crud',
      entity: 'body_measurements',
      description: 'Update measurement',
    },
    {
      method: 'DELETE',
      path: '/body-measurements/:id',
      auth: true,
      handler: 'crud',
      entity: 'body_measurements',
      description: 'Delete measurement',
    },
    {
      method: 'GET',
      path: '/body-measurements/latest',
      auth: true,
      handler: 'custom',
      entity: 'body_measurements',
      description: 'Get latest measurements',
    },
    {
      method: 'GET',
      path: '/body-measurements/history',
      auth: true,
      handler: 'custom',
      entity: 'body_measurements',
      description: 'Get measurement history with trends',
    },
    {
      method: 'GET',
      path: '/body-measurements/comparison',
      auth: true,
      handler: 'custom',
      entity: 'body_measurements',
      description: 'Compare measurements between dates',
    },

    // Progress Photos routes
    {
      method: 'GET',
      path: '/progress-photos',
      auth: true,
      handler: 'crud',
      entity: 'progress_photos',
      description: 'List user progress photos',
    },
    {
      method: 'POST',
      path: '/progress-photos',
      auth: true,
      handler: 'crud',
      entity: 'progress_photos',
      description: 'Upload progress photo',
    },
    {
      method: 'GET',
      path: '/progress-photos/:id',
      auth: true,
      handler: 'crud',
      entity: 'progress_photos',
      description: 'Get photo details',
    },
    {
      method: 'PUT',
      path: '/progress-photos/:id',
      auth: true,
      handler: 'crud',
      entity: 'progress_photos',
      description: 'Update photo metadata',
    },
    {
      method: 'DELETE',
      path: '/progress-photos/:id',
      auth: true,
      handler: 'crud',
      entity: 'progress_photos',
      description: 'Delete progress photo',
    },
    {
      method: 'GET',
      path: '/progress-photos/timeline',
      auth: true,
      handler: 'custom',
      entity: 'progress_photos',
      description: 'Get photos timeline',
    },

    // Fitness Goals routes
    {
      method: 'GET',
      path: '/fitness-goals',
      auth: true,
      handler: 'crud',
      entity: 'fitness_goals',
      description: 'List user fitness goals',
    },
    {
      method: 'POST',
      path: '/fitness-goals',
      auth: true,
      handler: 'crud',
      entity: 'fitness_goals',
      description: 'Create fitness goal',
    },
    {
      method: 'GET',
      path: '/fitness-goals/:id',
      auth: true,
      handler: 'crud',
      entity: 'fitness_goals',
      description: 'Get goal details',
    },
    {
      method: 'PUT',
      path: '/fitness-goals/:id',
      auth: true,
      handler: 'crud',
      entity: 'fitness_goals',
      description: 'Update goal',
    },
    {
      method: 'DELETE',
      path: '/fitness-goals/:id',
      auth: true,
      handler: 'crud',
      entity: 'fitness_goals',
      description: 'Delete goal',
    },
    {
      method: 'POST',
      path: '/fitness-goals/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'fitness_goals',
      description: 'Mark goal as complete',
    },
    {
      method: 'GET',
      path: '/fitness-goals/:id/progress',
      auth: true,
      handler: 'custom',
      entity: 'fitness_goals',
      description: 'Get goal progress',
    },

    // Goal Milestones routes
    {
      method: 'GET',
      path: '/fitness-goals/:id/milestones',
      auth: true,
      handler: 'crud',
      entity: 'goal_milestones',
      description: 'Get goal milestones',
    },
    {
      method: 'POST',
      path: '/fitness-goals/:id/milestones',
      auth: true,
      handler: 'crud',
      entity: 'goal_milestones',
      description: 'Add milestone',
    },
    {
      method: 'PUT',
      path: '/goal-milestones/:id',
      auth: true,
      handler: 'crud',
      entity: 'goal_milestones',
      description: 'Update milestone',
    },
    {
      method: 'POST',
      path: '/goal-milestones/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'goal_milestones',
      description: 'Complete milestone',
    },

    // Stats routes
    {
      method: 'GET',
      path: '/body-stats/bmi',
      auth: true,
      handler: 'custom',
      entity: 'body_measurements',
      description: 'Calculate BMI',
    },
    {
      method: 'GET',
      path: '/body-stats/summary',
      auth: true,
      handler: 'aggregate',
      entity: 'body_measurements',
      description: 'Get body stats summary',
    },
  ],

  config: [
    {
      key: 'measurementUnits',
      label: 'Measurement Units',
      type: 'select',
      default: 'metric',
      options: [
        { value: 'metric', label: 'Metric (kg, cm)' },
        { value: 'imperial', label: 'Imperial (lbs, in)' },
      ],
      description: 'Default units for measurements',
    },
    {
      key: 'defaultMeasurements',
      label: 'Default Measurement Types',
      type: 'select',
      default: 'basic',
      options: [
        { value: 'basic', label: 'Basic (weight, waist, hips)' },
        { value: 'extended', label: 'Extended (includes arms, legs, chest)' },
        { value: 'detailed', label: 'Detailed (all measurements)' },
      ],
      description: 'Which measurements to track by default',
    },
    {
      key: 'photoReminders',
      label: 'Photo Reminder Frequency',
      type: 'select',
      default: 'weekly',
      options: [
        { value: 'off', label: 'Off' },
        { value: 'weekly', label: 'Weekly' },
        { value: 'biweekly', label: 'Every 2 Weeks' },
        { value: 'monthly', label: 'Monthly' },
      ],
      description: 'Remind users to take progress photos',
    },
    {
      key: 'measurementReminders',
      label: 'Measurement Reminders',
      type: 'boolean',
      default: true,
      description: 'Send reminders to log measurements',
    },
    {
      key: 'showBodyFat',
      label: 'Show Body Fat Calculations',
      type: 'boolean',
      default: true,
      description: 'Display estimated body fat percentage',
    },
    {
      key: 'privateByDefault',
      label: 'Photos Private by Default',
      type: 'boolean',
      default: true,
      description: 'Progress photos are private by default',
    },
  ],
};
