/**
 * Class Scheduling Feature Definition
 *
 * Complete fitness class scheduling functionality for gyms, yoga studios,
 * CrossFit boxes, and any fitness facility requiring class management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CLASS_SCHEDULING_FEATURE: FeatureDefinition = {
  id: 'class-scheduling',
  name: 'Class Scheduling',
  category: 'fitness',
  description: 'Schedule and manage fitness classes with instructor assignments, capacity limits, and member signups',
  icon: 'calendar-clock',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'class scheduling',
    'fitness classes',
    'class calendar',
    'class signup',
    'group classes',
    'class schedule',
    'yoga classes',
    'spin classes',
    'workout classes',
    'fitness schedule',
    'class timetable',
    'class booking',
    'instructor schedule',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'calendar'],
  conflicts: [],

  pages: [
    {
      id: 'class-calendar',
      route: '/classes',
      section: 'frontend',
      title: 'Class Calendar',
      authRequired: false,
      templateId: 'class-calendar',
      components: [
        'schedule-grid',
        'class-card',
        'class-filter',
        'instructor-filter',
        'date-navigation',
      ],
      layout: 'default',
    },
    {
      id: 'class-detail',
      route: '/classes/:id',
      section: 'frontend',
      title: 'Class Details',
      authRequired: false,
      templateId: 'class-detail',
      components: [
        'class-header',
        'class-info',
        'instructor-card',
        'capacity-indicator',
        'signup-button',
        'waitlist-join',
        'class-reviews',
      ],
      layout: 'default',
    },
    {
      id: 'class-signup',
      route: '/classes/:id/signup',
      section: 'frontend',
      title: 'Class Signup',
      authRequired: true,
      templateId: 'class-signup',
      components: [
        'signup-form',
        'class-summary',
        'payment-options',
        'confirmation-message',
      ],
      layout: 'centered',
    },
    {
      id: 'instructor-schedule',
      route: '/instructors/:id/schedule',
      section: 'frontend',
      title: 'Instructor Schedule',
      authRequired: false,
      templateId: 'instructor-schedule',
      components: [
        'instructor-profile',
        'instructor-calendar',
        'class-list',
        'booking-button',
      ],
      layout: 'default',
    },
    {
      id: 'my-classes',
      route: '/my-classes',
      section: 'frontend',
      title: 'My Classes',
      authRequired: true,
      templateId: 'my-classes',
      components: [
        'upcoming-classes',
        'past-classes',
        'cancel-button',
        'reschedule-button',
      ],
      layout: 'default',
    },
    {
      id: 'admin-classes',
      route: '/admin/classes',
      section: 'admin',
      title: 'Manage Classes',
      authRequired: true,
      templateId: 'admin-classes',
      components: [
        'class-management-table',
        'class-form',
        'schedule-builder',
        'instructor-assignment',
        'capacity-settings',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-instructors',
      route: '/admin/instructors',
      section: 'admin',
      title: 'Manage Instructors',
      authRequired: true,
      templateId: 'admin-instructors',
      components: [
        'instructors-table',
        'instructor-form',
        'availability-editor',
        'certification-tracker',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calendar components
    'schedule-grid',
    'class-card',
    'class-filter',
    'instructor-filter',
    'date-navigation',
    'week-view',
    'day-view',
    'month-view',

    // Class detail components
    'class-header',
    'class-info',
    'instructor-card',
    'capacity-indicator',
    'signup-button',
    'waitlist-join',
    'class-reviews',

    // Signup components
    'signup-form',
    'class-summary',
    'payment-options',
    'confirmation-message',

    // Instructor components
    'instructor-profile',
    'instructor-calendar',
    'instructor-rating',
    'certification-badges',

    // User components
    'upcoming-classes',
    'past-classes',
    'cancel-button',
    'reschedule-button',

    // Admin components
    'class-management-table',
    'class-form',
    'schedule-builder',
    'instructor-assignment',
    'capacity-settings',
    'instructors-table',
    'instructor-form',
    'availability-editor',
    'certification-tracker',
    'attendance-tracker',
  ],

  entities: [
    {
      name: 'fitness_classes',
      displayName: 'Fitness Classes',
      description: 'Class definitions with name, type, duration, and requirements',
      isCore: true,
    },
    {
      name: 'class_schedules',
      displayName: 'Class Schedules',
      description: 'Scheduled instances of classes with date, time, and instructor',
      isCore: true,
    },
    {
      name: 'class_signups',
      displayName: 'Class Signups',
      description: 'Member registrations for scheduled classes',
      isCore: true,
    },
    {
      name: 'instructors',
      displayName: 'Instructors',
      description: 'Fitness instructors with certifications and specialties',
      isCore: true,
    },
    {
      name: 'instructor_availability',
      displayName: 'Instructor Availability',
      description: 'Instructor availability schedules',
      isCore: false,
    },
    {
      name: 'class_waitlist',
      displayName: 'Class Waitlist',
      description: 'Waitlist entries for full classes',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Fitness Classes routes
    {
      method: 'GET',
      path: '/fitness-classes',
      auth: false,
      handler: 'crud',
      entity: 'fitness_classes',
      description: 'List all fitness class types',
    },
    {
      method: 'POST',
      path: '/fitness-classes',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'fitness_classes',
      description: 'Create a new fitness class type',
    },
    {
      method: 'GET',
      path: '/fitness-classes/:id',
      auth: false,
      handler: 'crud',
      entity: 'fitness_classes',
      description: 'Get fitness class details',
    },
    {
      method: 'PUT',
      path: '/fitness-classes/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'fitness_classes',
      description: 'Update fitness class',
    },
    {
      method: 'DELETE',
      path: '/fitness-classes/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'fitness_classes',
      description: 'Delete fitness class',
    },

    // Class Schedules routes
    {
      method: 'GET',
      path: '/class-schedules',
      auth: false,
      handler: 'crud',
      entity: 'class_schedules',
      description: 'List scheduled classes with filters',
    },
    {
      method: 'POST',
      path: '/class-schedules',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'class_schedules',
      description: 'Schedule a class instance',
    },
    {
      method: 'GET',
      path: '/class-schedules/:id',
      auth: false,
      handler: 'crud',
      entity: 'class_schedules',
      description: 'Get scheduled class details',
    },
    {
      method: 'PUT',
      path: '/class-schedules/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'class_schedules',
      description: 'Update scheduled class',
    },
    {
      method: 'DELETE',
      path: '/class-schedules/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'class_schedules',
      description: 'Cancel scheduled class',
    },
    {
      method: 'POST',
      path: '/class-schedules/:id/cancel',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'class_schedules',
      description: 'Cancel class and notify attendees',
    },

    // Class Signups routes
    {
      method: 'GET',
      path: '/class-signups',
      auth: true,
      handler: 'crud',
      entity: 'class_signups',
      description: 'List user class signups',
    },
    {
      method: 'POST',
      path: '/class-signups',
      auth: true,
      handler: 'crud',
      entity: 'class_signups',
      description: 'Sign up for a class',
    },
    {
      method: 'DELETE',
      path: '/class-signups/:id',
      auth: true,
      handler: 'crud',
      entity: 'class_signups',
      description: 'Cancel class signup',
    },
    {
      method: 'POST',
      path: '/class-signups/:id/check-in',
      auth: true,
      handler: 'custom',
      entity: 'class_signups',
      description: 'Check in to class',
    },

    // Instructors routes
    {
      method: 'GET',
      path: '/instructors',
      auth: false,
      handler: 'crud',
      entity: 'instructors',
      description: 'List all instructors',
    },
    {
      method: 'POST',
      path: '/instructors',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'instructors',
      description: 'Create instructor profile',
    },
    {
      method: 'GET',
      path: '/instructors/:id',
      auth: false,
      handler: 'crud',
      entity: 'instructors',
      description: 'Get instructor details',
    },
    {
      method: 'PUT',
      path: '/instructors/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'instructors',
      description: 'Update instructor profile',
    },
    {
      method: 'DELETE',
      path: '/instructors/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'instructors',
      description: 'Remove instructor',
    },
    {
      method: 'GET',
      path: '/instructors/:id/schedule',
      auth: false,
      handler: 'custom',
      entity: 'class_schedules',
      description: 'Get instructor schedule',
    },
    {
      method: 'GET',
      path: '/instructors/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'instructor_availability',
      description: 'Get instructor availability',
    },

    // Waitlist routes
    {
      method: 'POST',
      path: '/class-waitlist',
      auth: true,
      handler: 'crud',
      entity: 'class_waitlist',
      description: 'Join class waitlist',
    },
    {
      method: 'DELETE',
      path: '/class-waitlist/:id',
      auth: true,
      handler: 'crud',
      entity: 'class_waitlist',
      description: 'Leave class waitlist',
    },
    {
      method: 'GET',
      path: '/class-schedules/:id/waitlist',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'class_waitlist',
      description: 'Get class waitlist',
    },
  ],

  config: [
    {
      key: 'defaultClassDuration',
      label: 'Default Class Duration (minutes)',
      type: 'number',
      default: 60,
      description: 'Default duration for fitness classes',
    },
    {
      key: 'maxClassCapacity',
      label: 'Maximum Class Capacity',
      type: 'number',
      default: 30,
      description: 'Default maximum participants per class',
    },
    {
      key: 'waitlistEnabled',
      label: 'Enable Waitlist',
      type: 'boolean',
      default: true,
      description: 'Allow members to join waitlist for full classes',
    },
    {
      key: 'cancellationDeadline',
      label: 'Cancellation Deadline (hours)',
      type: 'number',
      default: 2,
      description: 'Hours before class when cancellation is no longer free',
    },
    {
      key: 'lateCancellationFee',
      label: 'Late Cancellation Penalty',
      type: 'select',
      default: 'credit',
      options: [
        { value: 'none', label: 'No penalty' },
        { value: 'credit', label: 'Deduct class credit' },
        { value: 'fee', label: 'Charge fee' },
      ],
      description: 'Penalty for late cancellations',
    },
    {
      key: 'autoPromoteWaitlist',
      label: 'Auto-Promote from Waitlist',
      type: 'boolean',
      default: true,
      description: 'Automatically promote waitlist members when spots open',
    },
  ],
};
