/**
 * Class Packages Feature Definition
 *
 * Complete class package and credit system functionality including
 * package purchases, credit balance, and usage tracking.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CLASS_PACKAGES_FEATURE: FeatureDefinition = {
  id: 'class-packages',
  name: 'Class Packages',
  category: 'fitness',
  description: 'Manage class packages with credits, bundle pricing, and usage tracking',
  icon: 'ticket',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'class packages',
    'class credits',
    'class packs',
    'class bundles',
    'credit system',
    'class passes',
    'punch card',
    'drop-in classes',
    'class punch card',
    'credit balance',
    'buy credits',
    'class vouchers',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'payments', 'class-scheduling'],
  conflicts: [],

  pages: [
    {
      id: 'packages-list',
      route: '/class-packages',
      section: 'frontend',
      title: 'Class Packages',
      authRequired: false,
      templateId: 'packages-list',
      components: [
        'package-grid',
        'package-card',
        'savings-indicator',
        'comparison-table',
        'popular-badge',
      ],
      layout: 'default',
    },
    {
      id: 'package-detail',
      route: '/class-packages/:id',
      section: 'frontend',
      title: 'Package Details',
      authRequired: false,
      templateId: 'package-detail',
      components: [
        'package-header',
        'credits-breakdown',
        'valid-classes',
        'terms-info',
        'purchase-button',
      ],
      layout: 'default',
    },
    {
      id: 'my-credits',
      route: '/my-credits',
      section: 'frontend',
      title: 'My Credits',
      authRequired: true,
      templateId: 'my-credits',
      components: [
        'credit-balance',
        'package-cards',
        'expiring-credits',
        'usage-history',
        'buy-more-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'package-purchase',
      route: '/class-packages/:id/purchase',
      section: 'frontend',
      title: 'Purchase Package',
      authRequired: true,
      templateId: 'package-purchase',
      components: [
        'package-summary',
        'quantity-selector',
        'payment-form',
        'promo-code',
        'order-total',
      ],
      layout: 'centered',
    },
    {
      id: 'usage-history',
      route: '/my-credits/history',
      section: 'frontend',
      title: 'Credit History',
      authRequired: true,
      templateId: 'usage-history',
      components: [
        'usage-log',
        'usage-filters',
        'usage-chart',
        'export-button',
      ],
      layout: 'default',
    },
    {
      id: 'admin-packages',
      route: '/admin/class-packages',
      section: 'admin',
      title: 'Manage Packages',
      authRequired: true,
      templateId: 'admin-packages',
      components: [
        'packages-table',
        'package-form',
        'pricing-editor',
        'class-assignment',
        'validity-settings',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-credits',
      route: '/admin/credits',
      section: 'admin',
      title: 'Credit Management',
      authRequired: true,
      templateId: 'admin-credits',
      components: [
        'credit-search',
        'member-credits',
        'manual-adjustment',
        'bulk-operations',
        'credit-report',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Package list components
    'package-grid',
    'package-card',
    'savings-indicator',
    'comparison-table',
    'popular-badge',
    'best-value-badge',

    // Package detail components
    'package-header',
    'credits-breakdown',
    'valid-classes',
    'terms-info',
    'purchase-button',

    // Credit components
    'credit-balance',
    'package-cards',
    'expiring-credits',
    'usage-history',
    'buy-more-button',
    'credit-meter',

    // Purchase components
    'package-summary',
    'quantity-selector',
    'payment-form',
    'promo-code',
    'order-total',
    'gift-option',

    // Usage components
    'usage-log',
    'usage-filters',
    'usage-chart',
    'export-button',

    // Admin components
    'packages-table',
    'package-form',
    'pricing-editor',
    'class-assignment',
    'validity-settings',
    'credit-search',
    'member-credits',
    'manual-adjustment',
    'bulk-operations',
    'credit-report',
  ],

  entities: [
    {
      name: 'class_packages',
      displayName: 'Class Packages',
      description: 'Available class package definitions',
      isCore: true,
    },
    {
      name: 'package_purchases',
      displayName: 'Package Purchases',
      description: 'User package purchase records',
      isCore: true,
    },
    {
      name: 'class_credits',
      displayName: 'Class Credits',
      description: 'User class credit balances',
      isCore: true,
    },
    {
      name: 'credit_usage',
      displayName: 'Credit Usage',
      description: 'Class credit usage history',
      isCore: true,
    },
    {
      name: 'package_promos',
      displayName: 'Package Promos',
      description: 'Promotional codes for packages',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Class Packages routes
    {
      method: 'GET',
      path: '/class-packages',
      auth: false,
      handler: 'crud',
      entity: 'class_packages',
      description: 'List all class packages',
    },
    {
      method: 'POST',
      path: '/class-packages',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'class_packages',
      description: 'Create class package',
    },
    {
      method: 'GET',
      path: '/class-packages/:id',
      auth: false,
      handler: 'crud',
      entity: 'class_packages',
      description: 'Get package details',
    },
    {
      method: 'PUT',
      path: '/class-packages/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'class_packages',
      description: 'Update package',
    },
    {
      method: 'DELETE',
      path: '/class-packages/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'class_packages',
      description: 'Archive package',
    },
    {
      method: 'GET',
      path: '/class-packages/compare',
      auth: false,
      handler: 'custom',
      entity: 'class_packages',
      description: 'Get package comparison',
    },

    // Package Purchases routes
    {
      method: 'GET',
      path: '/my-purchases',
      auth: true,
      handler: 'crud',
      entity: 'package_purchases',
      description: 'Get user purchases',
    },
    {
      method: 'POST',
      path: '/package-purchases',
      auth: true,
      handler: 'crud',
      entity: 'package_purchases',
      description: 'Purchase a package',
    },
    {
      method: 'GET',
      path: '/package-purchases/:id',
      auth: true,
      handler: 'crud',
      entity: 'package_purchases',
      description: 'Get purchase details',
    },
    {
      method: 'POST',
      path: '/package-purchases/:id/gift',
      auth: true,
      handler: 'custom',
      entity: 'package_purchases',
      description: 'Gift purchased package',
    },
    {
      method: 'POST',
      path: '/package-purchases/validate-promo',
      auth: true,
      handler: 'custom',
      entity: 'package_purchases',
      description: 'Validate promo code',
    },

    // Class Credits routes
    {
      method: 'GET',
      path: '/my-credits',
      auth: true,
      handler: 'crud',
      entity: 'class_credits',
      description: 'Get user credit balance',
    },
    {
      method: 'GET',
      path: '/my-credits/expiring',
      auth: true,
      handler: 'custom',
      entity: 'class_credits',
      description: 'Get expiring credits',
    },
    {
      method: 'POST',
      path: '/class-credits/adjust',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'class_credits',
      description: 'Manually adjust credits',
    },
    {
      method: 'GET',
      path: '/users/:id/credits',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'class_credits',
      description: 'Get user credits (admin)',
    },

    // Credit Usage routes
    {
      method: 'GET',
      path: '/credit-usage',
      auth: true,
      handler: 'crud',
      entity: 'credit_usage',
      description: 'Get credit usage history',
    },
    {
      method: 'POST',
      path: '/credit-usage',
      auth: true,
      handler: 'crud',
      entity: 'credit_usage',
      description: 'Use credit for class',
    },
    {
      method: 'POST',
      path: '/credit-usage/:id/refund',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'credit_usage',
      description: 'Refund used credit',
    },
    {
      method: 'GET',
      path: '/credit-usage/stats',
      auth: true,
      handler: 'aggregate',
      entity: 'credit_usage',
      description: 'Get usage statistics',
    },

    // Package Promos routes
    {
      method: 'GET',
      path: '/package-promos',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'package_promos',
      description: 'List promo codes',
    },
    {
      method: 'POST',
      path: '/package-promos',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'package_promos',
      description: 'Create promo code',
    },
    {
      method: 'PUT',
      path: '/package-promos/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'package_promos',
      description: 'Update promo code',
    },
    {
      method: 'DELETE',
      path: '/package-promos/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'package_promos',
      description: 'Delete promo code',
    },
  ],

  config: [
    {
      key: 'defaultValidity',
      label: 'Default Package Validity (days)',
      type: 'number',
      default: 90,
      description: 'How long purchased credits remain valid',
    },
    {
      key: 'expiryWarningDays',
      label: 'Expiry Warning (days)',
      type: 'number',
      default: 14,
      description: 'Days before expiry to send warning',
    },
    {
      key: 'allowGifting',
      label: 'Allow Package Gifting',
      type: 'boolean',
      default: true,
      description: 'Allow members to gift packages to others',
    },
    {
      key: 'carryOverCredits',
      label: 'Carry Over Unused Credits',
      type: 'boolean',
      default: false,
      description: 'Allow unused credits to carry over on renewal',
    },
    {
      key: 'creditRefundPolicy',
      label: 'Credit Refund Policy',
      type: 'select',
      default: '24h',
      options: [
        { value: 'no-refund', label: 'No refunds' },
        { value: '2h', label: 'Cancel 2+ hours before class' },
        { value: '24h', label: 'Cancel 24+ hours before class' },
        { value: 'always', label: 'Always refund on cancellation' },
      ],
      description: 'When to refund credits for cancelled bookings',
    },
    {
      key: 'showSavingsPercent',
      label: 'Show Savings Percentage',
      type: 'boolean',
      default: true,
      description: 'Display savings compared to single class price',
    },
  ],
};
