/**
 * Equipment Booking Feature Definition
 *
 * Complete gym equipment reservation functionality including
 * equipment catalog, booking calendar, and QR check-in.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const EQUIPMENT_BOOKING_FEATURE: FeatureDefinition = {
  id: 'equipment-booking',
  name: 'Equipment Booking',
  category: 'fitness',
  description: 'Reserve gym equipment with time slots, booking limits, and QR check-in',
  icon: 'weight',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'equipment booking',
    'equipment reservation',
    'machine booking',
    'gym equipment',
    'reserve equipment',
    'book machine',
    'treadmill booking',
    'equipment slots',
    'equipment schedule',
    'gym reservation',
    'machine reservation',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth', 'membership-plans'],
  conflicts: [],

  pages: [
    {
      id: 'equipment-list',
      route: '/equipment',
      section: 'frontend',
      title: 'Gym Equipment',
      authRequired: false,
      templateId: 'equipment-list',
      components: [
        'equipment-grid',
        'equipment-card',
        'category-filter',
        'availability-indicator',
        'floor-filter',
      ],
      layout: 'default',
    },
    {
      id: 'equipment-detail',
      route: '/equipment/:id',
      section: 'frontend',
      title: 'Equipment Details',
      authRequired: false,
      templateId: 'equipment-detail',
      components: [
        'equipment-header',
        'equipment-image',
        'specifications',
        'usage-instructions',
        'availability-calendar',
        'book-button',
      ],
      layout: 'default',
    },
    {
      id: 'booking-calendar',
      route: '/equipment/:id/book',
      section: 'frontend',
      title: 'Book Equipment',
      authRequired: true,
      templateId: 'booking-calendar',
      components: [
        'date-picker',
        'time-slot-picker',
        'duration-selector',
        'booking-form',
        'confirmation-message',
      ],
      layout: 'centered',
    },
    {
      id: 'my-bookings',
      route: '/my-bookings/equipment',
      section: 'frontend',
      title: 'My Equipment Bookings',
      authRequired: true,
      templateId: 'my-bookings',
      components: [
        'upcoming-bookings',
        'past-bookings',
        'booking-card',
        'qr-checkin',
        'cancel-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'equipment-checkin',
      route: '/equipment/checkin/:bookingId',
      section: 'frontend',
      title: 'Check In',
      authRequired: true,
      templateId: 'equipment-checkin',
      components: [
        'booking-details',
        'checkin-button',
        'countdown-timer',
        'extend-button',
      ],
      layout: 'centered',
    },
    {
      id: 'admin-equipment',
      route: '/admin/equipment',
      section: 'admin',
      title: 'Manage Equipment',
      authRequired: true,
      templateId: 'admin-equipment',
      components: [
        'equipment-table',
        'equipment-form',
        'maintenance-scheduler',
        'usage-stats',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-equipment-bookings',
      route: '/admin/equipment-bookings',
      section: 'admin',
      title: 'Equipment Bookings',
      authRequired: true,
      templateId: 'admin-equipment-bookings',
      components: [
        'bookings-table',
        'calendar-view',
        'booking-filters',
        'utilization-report',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-maintenance',
      route: '/admin/equipment/maintenance',
      section: 'admin',
      title: 'Equipment Maintenance',
      authRequired: true,
      templateId: 'admin-maintenance',
      components: [
        'maintenance-table',
        'maintenance-form',
        'service-history',
        'issue-tracker',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Equipment list components
    'equipment-grid',
    'equipment-card',
    'category-filter',
    'availability-indicator',
    'floor-filter',
    'equipment-search',

    // Equipment detail components
    'equipment-header',
    'equipment-image',
    'specifications',
    'usage-instructions',
    'availability-calendar',
    'book-button',

    // Booking components
    'date-picker',
    'time-slot-picker',
    'duration-selector',
    'booking-form',
    'confirmation-message',

    // User booking components
    'upcoming-bookings',
    'past-bookings',
    'booking-card',
    'qr-checkin',
    'cancel-button',
    'checkin-button',
    'countdown-timer',
    'extend-button',

    // Admin components
    'equipment-table',
    'equipment-form',
    'maintenance-scheduler',
    'usage-stats',
    'bookings-table',
    'calendar-view',
    'booking-filters',
    'utilization-report',
    'maintenance-table',
    'maintenance-form',
    'service-history',
    'issue-tracker',
  ],

  entities: [
    {
      name: 'equipment',
      displayName: 'Equipment',
      description: 'Gym equipment inventory',
      isCore: true,
    },
    {
      name: 'equipment_bookings',
      displayName: 'Equipment Bookings',
      description: 'Equipment reservation records',
      isCore: true,
    },
    {
      name: 'equipment_maintenance',
      displayName: 'Equipment Maintenance',
      description: 'Maintenance and service records',
      isCore: false,
    },
    {
      name: 'equipment_categories',
      displayName: 'Equipment Categories',
      description: 'Categories for organizing equipment',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Equipment routes
    {
      method: 'GET',
      path: '/equipment',
      auth: false,
      handler: 'crud',
      entity: 'equipment',
      description: 'List all equipment',
    },
    {
      method: 'POST',
      path: '/equipment',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment',
      description: 'Add equipment',
    },
    {
      method: 'GET',
      path: '/equipment/:id',
      auth: false,
      handler: 'crud',
      entity: 'equipment',
      description: 'Get equipment details',
    },
    {
      method: 'PUT',
      path: '/equipment/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment',
      description: 'Update equipment',
    },
    {
      method: 'DELETE',
      path: '/equipment/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment',
      description: 'Remove equipment',
    },
    {
      method: 'GET',
      path: '/equipment/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'equipment',
      description: 'Get equipment availability',
    },
    {
      method: 'POST',
      path: '/equipment/:id/maintenance',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'equipment',
      description: 'Mark equipment for maintenance',
    },

    // Equipment Bookings routes
    {
      method: 'GET',
      path: '/equipment-bookings',
      auth: true,
      handler: 'crud',
      entity: 'equipment_bookings',
      description: 'Get user equipment bookings',
    },
    {
      method: 'POST',
      path: '/equipment-bookings',
      auth: true,
      handler: 'crud',
      entity: 'equipment_bookings',
      description: 'Book equipment',
    },
    {
      method: 'GET',
      path: '/equipment-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_bookings',
      description: 'Get booking details',
    },
    {
      method: 'PUT',
      path: '/equipment-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_bookings',
      description: 'Update booking',
    },
    {
      method: 'DELETE',
      path: '/equipment-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_bookings',
      description: 'Cancel booking',
    },
    {
      method: 'POST',
      path: '/equipment-bookings/:id/checkin',
      auth: true,
      handler: 'custom',
      entity: 'equipment_bookings',
      description: 'Check in to booking',
    },
    {
      method: 'POST',
      path: '/equipment-bookings/:id/checkout',
      auth: true,
      handler: 'custom',
      entity: 'equipment_bookings',
      description: 'Check out from booking',
    },
    {
      method: 'POST',
      path: '/equipment-bookings/:id/extend',
      auth: true,
      handler: 'custom',
      entity: 'equipment_bookings',
      description: 'Extend booking duration',
    },
    {
      method: 'GET',
      path: '/equipment-bookings/qr/:code',
      auth: true,
      handler: 'custom',
      entity: 'equipment_bookings',
      description: 'Validate booking QR code',
    },

    // Equipment Maintenance routes
    {
      method: 'GET',
      path: '/equipment-maintenance',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment_maintenance',
      description: 'List maintenance records',
    },
    {
      method: 'POST',
      path: '/equipment-maintenance',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment_maintenance',
      description: 'Create maintenance record',
    },
    {
      method: 'PUT',
      path: '/equipment-maintenance/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment_maintenance',
      description: 'Update maintenance record',
    },
    {
      method: 'POST',
      path: '/equipment-maintenance/:id/complete',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'equipment_maintenance',
      description: 'Complete maintenance',
    },
    {
      method: 'GET',
      path: '/equipment/:id/maintenance-history',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'equipment_maintenance',
      description: 'Get equipment maintenance history',
    },

    // Equipment Categories routes
    {
      method: 'GET',
      path: '/equipment-categories',
      auth: false,
      handler: 'crud',
      entity: 'equipment_categories',
      description: 'List equipment categories',
    },
    {
      method: 'POST',
      path: '/equipment-categories',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment_categories',
      description: 'Create category',
    },
    {
      method: 'PUT',
      path: '/equipment-categories/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment_categories',
      description: 'Update category',
    },
    {
      method: 'DELETE',
      path: '/equipment-categories/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment_categories',
      description: 'Delete category',
    },

    // Utilization routes
    {
      method: 'GET',
      path: '/equipment/stats/utilization',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'equipment_bookings',
      description: 'Get equipment utilization stats',
    },
  ],

  config: [
    {
      key: 'defaultSlotDuration',
      label: 'Default Slot Duration (minutes)',
      type: 'number',
      default: 30,
      description: 'Default booking slot duration',
    },
    {
      key: 'maxBookingDuration',
      label: 'Maximum Booking Duration (minutes)',
      type: 'number',
      default: 60,
      description: 'Maximum allowed booking duration',
    },
    {
      key: 'maxDailyBookings',
      label: 'Max Daily Bookings Per Member',
      type: 'number',
      default: 3,
      description: 'Maximum equipment bookings per day',
    },
    {
      key: 'advanceBookingHours',
      label: 'Advance Booking Limit (hours)',
      type: 'number',
      default: 24,
      description: 'How far in advance equipment can be booked',
    },
    {
      key: 'checkinWindow',
      label: 'Check-in Window (minutes)',
      type: 'number',
      default: 10,
      description: 'Minutes before/after booking to allow check-in',
    },
    {
      key: 'autoReleaseNoShow',
      label: 'Auto-Release No-Shows (minutes)',
      type: 'number',
      default: 15,
      description: 'Minutes after booking start to auto-cancel no-shows',
    },
    {
      key: 'requireQRCheckin',
      label: 'Require QR Check-in',
      type: 'boolean',
      default: true,
      description: 'Require QR code scan to start booking',
    },
  ],
};
