/**
 * Fitness Challenges Feature Definition
 *
 * Complete fitness challenges and competitions functionality including
 * challenges, leaderboards, achievements, and badges.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const FITNESS_CHALLENGES_FEATURE: FeatureDefinition = {
  id: 'fitness-challenges',
  name: 'Fitness Challenges',
  category: 'fitness',
  description: 'Create and participate in fitness challenges with leaderboards, achievements, and badges',
  icon: 'trophy',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'fitness challenges',
    'workout challenges',
    'gym challenges',
    'leaderboard',
    'fitness competition',
    'challenge tracker',
    'achievements',
    'badges',
    'step challenge',
    'weight loss challenge',
    'fitness contest',
    'workout competition',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'workout-tracking'],
  conflicts: [],

  pages: [
    {
      id: 'challenges-list',
      route: '/challenges',
      section: 'frontend',
      title: 'Fitness Challenges',
      authRequired: false,
      templateId: 'challenges-list',
      components: [
        'challenge-grid',
        'challenge-card',
        'challenge-filter',
        'featured-challenge',
        'my-challenges',
      ],
      layout: 'default',
    },
    {
      id: 'challenge-detail',
      route: '/challenges/:id',
      section: 'frontend',
      title: 'Challenge Details',
      authRequired: false,
      templateId: 'challenge-detail',
      components: [
        'challenge-header',
        'challenge-description',
        'challenge-rules',
        'prize-info',
        'join-button',
        'participant-count',
        'countdown-timer',
      ],
      layout: 'default',
    },
    {
      id: 'challenge-leaderboard',
      route: '/challenges/:id/leaderboard',
      section: 'frontend',
      title: 'Leaderboard',
      authRequired: false,
      templateId: 'challenge-leaderboard',
      components: [
        'leaderboard-table',
        'top-performers',
        'my-ranking',
        'progress-chart',
        'time-remaining',
      ],
      layout: 'default',
    },
    {
      id: 'challenge-progress',
      route: '/challenges/:id/progress',
      section: 'frontend',
      title: 'My Progress',
      authRequired: true,
      templateId: 'challenge-progress',
      components: [
        'progress-tracker',
        'daily-log',
        'milestone-progress',
        'streak-counter',
        'encouragement-card',
      ],
      layout: 'dashboard',
    },
    {
      id: 'achievements',
      route: '/achievements',
      section: 'frontend',
      title: 'My Achievements',
      authRequired: true,
      templateId: 'achievements',
      components: [
        'badge-display',
        'achievement-grid',
        'achievement-card',
        'progress-badges',
        'share-achievement',
      ],
      layout: 'default',
    },
    {
      id: 'admin-challenges',
      route: '/admin/challenges',
      section: 'admin',
      title: 'Manage Challenges',
      authRequired: true,
      templateId: 'admin-challenges',
      components: [
        'challenges-table',
        'challenge-form',
        'participant-manager',
        'prize-manager',
        'analytics-dashboard',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-achievements',
      route: '/admin/achievements',
      section: 'admin',
      title: 'Manage Achievements',
      authRequired: true,
      templateId: 'admin-achievements',
      components: [
        'achievements-table',
        'achievement-form',
        'badge-designer',
        'criteria-editor',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Challenge list components
    'challenge-grid',
    'challenge-card',
    'challenge-filter',
    'featured-challenge',
    'my-challenges',
    'active-challenges',

    // Challenge detail components
    'challenge-header',
    'challenge-description',
    'challenge-rules',
    'prize-info',
    'join-button',
    'participant-count',
    'countdown-timer',
    'sponsor-logo',

    // Leaderboard components
    'leaderboard-table',
    'top-performers',
    'my-ranking',
    'progress-chart',
    'time-remaining',
    'rank-change-indicator',

    // Progress components
    'progress-tracker',
    'daily-log',
    'milestone-progress',
    'streak-counter',
    'encouragement-card',
    'check-in-button',

    // Achievement components
    'badge-display',
    'achievement-grid',
    'achievement-card',
    'progress-badges',
    'share-achievement',
    'unlock-animation',

    // Admin components
    'challenges-table',
    'challenge-form',
    'participant-manager',
    'prize-manager',
    'analytics-dashboard',
    'achievements-table',
    'achievement-form',
    'badge-designer',
    'criteria-editor',
  ],

  entities: [
    {
      name: 'challenges',
      displayName: 'Challenges',
      description: 'Fitness challenge definitions',
      isCore: true,
    },
    {
      name: 'challenge_participants',
      displayName: 'Challenge Participants',
      description: 'Users participating in challenges',
      isCore: true,
    },
    {
      name: 'achievements',
      displayName: 'Achievements',
      description: 'Achievement definitions and criteria',
      isCore: true,
    },
    {
      name: 'badges',
      displayName: 'Badges',
      description: 'Visual badges for achievements',
      isCore: true,
    },
    {
      name: 'user_achievements',
      displayName: 'User Achievements',
      description: 'Achievements earned by users',
      isCore: false,
    },
    {
      name: 'challenge_progress',
      displayName: 'Challenge Progress',
      description: 'Daily progress entries for challenges',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Challenges routes
    {
      method: 'GET',
      path: '/challenges',
      auth: false,
      handler: 'crud',
      entity: 'challenges',
      description: 'List all challenges',
    },
    {
      method: 'POST',
      path: '/challenges',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'challenges',
      description: 'Create challenge',
    },
    {
      method: 'GET',
      path: '/challenges/:id',
      auth: false,
      handler: 'crud',
      entity: 'challenges',
      description: 'Get challenge details',
    },
    {
      method: 'PUT',
      path: '/challenges/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'challenges',
      description: 'Update challenge',
    },
    {
      method: 'DELETE',
      path: '/challenges/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'challenges',
      description: 'Delete challenge',
    },
    {
      method: 'GET',
      path: '/challenges/active',
      auth: false,
      handler: 'custom',
      entity: 'challenges',
      description: 'Get active challenges',
    },
    {
      method: 'GET',
      path: '/challenges/featured',
      auth: false,
      handler: 'custom',
      entity: 'challenges',
      description: 'Get featured challenges',
    },

    // Challenge Participants routes
    {
      method: 'POST',
      path: '/challenges/:id/join',
      auth: true,
      handler: 'custom',
      entity: 'challenge_participants',
      description: 'Join a challenge',
    },
    {
      method: 'DELETE',
      path: '/challenges/:id/leave',
      auth: true,
      handler: 'custom',
      entity: 'challenge_participants',
      description: 'Leave a challenge',
    },
    {
      method: 'GET',
      path: '/challenges/:id/participants',
      auth: false,
      handler: 'crud',
      entity: 'challenge_participants',
      description: 'Get challenge participants',
    },
    {
      method: 'GET',
      path: '/challenges/:id/leaderboard',
      auth: false,
      handler: 'custom',
      entity: 'challenge_participants',
      description: 'Get challenge leaderboard',
    },
    {
      method: 'GET',
      path: '/my-challenges',
      auth: true,
      handler: 'custom',
      entity: 'challenge_participants',
      description: 'Get user joined challenges',
    },

    // Challenge Progress routes
    {
      method: 'GET',
      path: '/challenges/:id/progress',
      auth: true,
      handler: 'crud',
      entity: 'challenge_progress',
      description: 'Get user progress in challenge',
    },
    {
      method: 'POST',
      path: '/challenges/:id/progress',
      auth: true,
      handler: 'crud',
      entity: 'challenge_progress',
      description: 'Log progress for challenge',
    },
    {
      method: 'PUT',
      path: '/challenge-progress/:id',
      auth: true,
      handler: 'crud',
      entity: 'challenge_progress',
      description: 'Update progress entry',
    },
    {
      method: 'GET',
      path: '/challenges/:id/my-ranking',
      auth: true,
      handler: 'custom',
      entity: 'challenge_progress',
      description: 'Get user ranking in challenge',
    },

    // Achievements routes
    {
      method: 'GET',
      path: '/achievements',
      auth: false,
      handler: 'crud',
      entity: 'achievements',
      description: 'List all achievements',
    },
    {
      method: 'POST',
      path: '/achievements',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'achievements',
      description: 'Create achievement',
    },
    {
      method: 'GET',
      path: '/achievements/:id',
      auth: false,
      handler: 'crud',
      entity: 'achievements',
      description: 'Get achievement details',
    },
    {
      method: 'PUT',
      path: '/achievements/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'achievements',
      description: 'Update achievement',
    },
    {
      method: 'DELETE',
      path: '/achievements/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'achievements',
      description: 'Delete achievement',
    },

    // User Achievements routes
    {
      method: 'GET',
      path: '/my-achievements',
      auth: true,
      handler: 'crud',
      entity: 'user_achievements',
      description: 'Get user earned achievements',
    },
    {
      method: 'GET',
      path: '/my-achievements/recent',
      auth: true,
      handler: 'custom',
      entity: 'user_achievements',
      description: 'Get recently earned achievements',
    },
    {
      method: 'POST',
      path: '/achievements/:id/claim',
      auth: true,
      handler: 'custom',
      entity: 'user_achievements',
      description: 'Claim an achievement',
    },

    // Badges routes
    {
      method: 'GET',
      path: '/badges',
      auth: false,
      handler: 'crud',
      entity: 'badges',
      description: 'List all badges',
    },
    {
      method: 'POST',
      path: '/badges',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'badges',
      description: 'Create badge',
    },
    {
      method: 'PUT',
      path: '/badges/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'badges',
      description: 'Update badge',
    },
    {
      method: 'GET',
      path: '/my-badges',
      auth: true,
      handler: 'custom',
      entity: 'badges',
      description: 'Get user earned badges',
    },
  ],

  config: [
    {
      key: 'allowUserChallenges',
      label: 'Allow User-Created Challenges',
      type: 'boolean',
      default: false,
      description: 'Allow members to create their own challenges',
    },
    {
      key: 'maxParticipants',
      label: 'Default Max Participants',
      type: 'number',
      default: 100,
      description: 'Default maximum participants per challenge',
    },
    {
      key: 'showLeaderboardNames',
      label: 'Show Names on Leaderboard',
      type: 'boolean',
      default: true,
      description: 'Display participant names on public leaderboard',
    },
    {
      key: 'achievementNotifications',
      label: 'Achievement Notifications',
      type: 'boolean',
      default: true,
      description: 'Notify users when they earn achievements',
    },
    {
      key: 'socialSharing',
      label: 'Enable Social Sharing',
      type: 'boolean',
      default: true,
      description: 'Allow sharing achievements to social media',
    },
    {
      key: 'streakBonuses',
      label: 'Streak Bonuses',
      type: 'boolean',
      default: true,
      description: 'Award bonus points for consecutive day participation',
    },
  ],
};
