/**
 * Group Training Feature Definition
 *
 * Complete group training session functionality including
 * team workouts, bootcamps, and group fitness programs.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const GROUP_TRAINING_FEATURE: FeatureDefinition = {
  id: 'group-training',
  name: 'Group Training',
  category: 'fitness',
  description: 'Manage group training sessions, team workouts, bootcamps, and small group fitness programs',
  icon: 'users',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'group training',
    'small group training',
    'team workouts',
    'bootcamp',
    'group fitness',
    'group sessions',
    'team training',
    'group exercise',
    'semi-private training',
    'partner training',
    'group PT',
    'team fitness',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'class-scheduling'],
  conflicts: [],

  pages: [
    {
      id: 'group-sessions',
      route: '/group-training',
      section: 'frontend',
      title: 'Group Training',
      authRequired: false,
      templateId: 'group-sessions',
      components: [
        'session-grid',
        'session-card',
        'session-filter',
        'level-filter',
        'schedule-calendar',
      ],
      layout: 'default',
    },
    {
      id: 'session-detail',
      route: '/group-training/:id',
      section: 'frontend',
      title: 'Session Details',
      authRequired: false,
      templateId: 'session-detail',
      components: [
        'session-header',
        'session-description',
        'trainer-info',
        'participant-preview',
        'difficulty-indicator',
        'signup-button',
      ],
      layout: 'default',
    },
    {
      id: 'session-signup',
      route: '/group-training/:id/signup',
      section: 'frontend',
      title: 'Join Session',
      authRequired: true,
      templateId: 'session-signup',
      components: [
        'session-summary',
        'participant-form',
        'waiver-agreement',
        'payment-options',
        'confirmation-step',
      ],
      layout: 'centered',
    },
    {
      id: 'team-workouts',
      route: '/team-workouts',
      section: 'frontend',
      title: 'Team Workouts',
      authRequired: true,
      templateId: 'team-workouts',
      components: [
        'team-list',
        'team-card',
        'create-team-button',
        'join-team-button',
        'team-leaderboard',
      ],
      layout: 'default',
    },
    {
      id: 'team-detail',
      route: '/team-workouts/:id',
      section: 'frontend',
      title: 'Team Details',
      authRequired: true,
      templateId: 'team-detail',
      components: [
        'team-header',
        'team-roster',
        'team-schedule',
        'team-stats',
        'team-chat',
      ],
      layout: 'default',
    },
    {
      id: 'bootcamps',
      route: '/bootcamps',
      section: 'frontend',
      title: 'Bootcamp Programs',
      authRequired: false,
      templateId: 'bootcamps',
      components: [
        'bootcamp-grid',
        'bootcamp-card',
        'program-details',
        'enrollment-button',
        'results-gallery',
      ],
      layout: 'default',
    },
    {
      id: 'bootcamp-detail',
      route: '/bootcamps/:id',
      section: 'frontend',
      title: 'Bootcamp Details',
      authRequired: false,
      templateId: 'bootcamp-detail',
      components: [
        'bootcamp-header',
        'schedule-overview',
        'workout-preview',
        'coach-info',
        'testimonials',
        'enroll-button',
      ],
      layout: 'default',
    },
    {
      id: 'my-groups',
      route: '/my-groups',
      section: 'frontend',
      title: 'My Group Sessions',
      authRequired: true,
      templateId: 'my-groups',
      components: [
        'upcoming-sessions',
        'past-sessions',
        'team-memberships',
        'bootcamp-progress',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-group-sessions',
      route: '/admin/group-training',
      section: 'admin',
      title: 'Manage Group Sessions',
      authRequired: true,
      templateId: 'admin-group-sessions',
      components: [
        'sessions-table',
        'session-form',
        'schedule-builder',
        'attendance-manager',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-bootcamps',
      route: '/admin/bootcamps',
      section: 'admin',
      title: 'Manage Bootcamps',
      authRequired: true,
      templateId: 'admin-bootcamps',
      components: [
        'bootcamps-table',
        'bootcamp-form',
        'program-builder',
        'enrollment-manager',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Group session components
    'session-grid',
    'session-card',
    'session-filter',
    'level-filter',
    'schedule-calendar',
    'session-header',
    'session-description',
    'trainer-info',
    'participant-preview',
    'difficulty-indicator',
    'signup-button',

    // Signup components
    'session-summary',
    'participant-form',
    'waiver-agreement',
    'payment-options',
    'confirmation-step',

    // Team components
    'team-list',
    'team-card',
    'create-team-button',
    'join-team-button',
    'team-leaderboard',
    'team-header',
    'team-roster',
    'team-schedule',
    'team-stats',
    'team-chat',

    // Bootcamp components
    'bootcamp-grid',
    'bootcamp-card',
    'program-details',
    'enrollment-button',
    'results-gallery',
    'bootcamp-header',
    'schedule-overview',
    'workout-preview',
    'coach-info',
    'testimonials',
    'enroll-button',

    // User components
    'upcoming-sessions',
    'past-sessions',
    'team-memberships',
    'bootcamp-progress',
    'attendance-checker',

    // Admin components
    'sessions-table',
    'session-form',
    'schedule-builder',
    'attendance-manager',
    'bootcamps-table',
    'bootcamp-form',
    'program-builder',
    'enrollment-manager',
  ],

  entities: [
    {
      name: 'group_sessions',
      displayName: 'Group Sessions',
      description: 'Group training session definitions',
      isCore: true,
    },
    {
      name: 'session_participants',
      displayName: 'Session Participants',
      description: 'Participants in group sessions',
      isCore: true,
    },
    {
      name: 'team_workouts',
      displayName: 'Team Workouts',
      description: 'Team-based workout groups',
      isCore: true,
    },
    {
      name: 'bootcamp_programs',
      displayName: 'Bootcamp Programs',
      description: 'Multi-week bootcamp programs',
      isCore: false,
    },
    {
      name: 'bootcamp_enrollments',
      displayName: 'Bootcamp Enrollments',
      description: 'User enrollments in bootcamps',
      isCore: false,
    },
    {
      name: 'team_members',
      displayName: 'Team Members',
      description: 'Members of workout teams',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Group Sessions routes
    {
      method: 'GET',
      path: '/group-sessions',
      auth: false,
      handler: 'crud',
      entity: 'group_sessions',
      description: 'List group sessions',
    },
    {
      method: 'POST',
      path: '/group-sessions',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'group_sessions',
      description: 'Create group session',
    },
    {
      method: 'GET',
      path: '/group-sessions/:id',
      auth: false,
      handler: 'crud',
      entity: 'group_sessions',
      description: 'Get session details',
    },
    {
      method: 'PUT',
      path: '/group-sessions/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'group_sessions',
      description: 'Update session',
    },
    {
      method: 'DELETE',
      path: '/group-sessions/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'group_sessions',
      description: 'Cancel session',
    },
    {
      method: 'GET',
      path: '/group-sessions/upcoming',
      auth: false,
      handler: 'custom',
      entity: 'group_sessions',
      description: 'Get upcoming sessions',
    },

    // Session Participants routes
    {
      method: 'POST',
      path: '/group-sessions/:id/join',
      auth: true,
      handler: 'custom',
      entity: 'session_participants',
      description: 'Join group session',
    },
    {
      method: 'DELETE',
      path: '/group-sessions/:id/leave',
      auth: true,
      handler: 'custom',
      entity: 'session_participants',
      description: 'Leave group session',
    },
    {
      method: 'GET',
      path: '/group-sessions/:id/participants',
      auth: true,
      handler: 'crud',
      entity: 'session_participants',
      description: 'Get session participants',
    },
    {
      method: 'POST',
      path: '/session-participants/:id/attend',
      auth: true,
      handler: 'custom',
      entity: 'session_participants',
      description: 'Mark attendance',
    },
    {
      method: 'GET',
      path: '/my-group-sessions',
      auth: true,
      handler: 'custom',
      entity: 'session_participants',
      description: 'Get user group sessions',
    },

    // Team Workouts routes
    {
      method: 'GET',
      path: '/team-workouts',
      auth: true,
      handler: 'crud',
      entity: 'team_workouts',
      description: 'List workout teams',
    },
    {
      method: 'POST',
      path: '/team-workouts',
      auth: true,
      handler: 'crud',
      entity: 'team_workouts',
      description: 'Create workout team',
    },
    {
      method: 'GET',
      path: '/team-workouts/:id',
      auth: true,
      handler: 'crud',
      entity: 'team_workouts',
      description: 'Get team details',
    },
    {
      method: 'PUT',
      path: '/team-workouts/:id',
      auth: true,
      handler: 'crud',
      entity: 'team_workouts',
      description: 'Update team',
    },
    {
      method: 'DELETE',
      path: '/team-workouts/:id',
      auth: true,
      handler: 'crud',
      entity: 'team_workouts',
      description: 'Delete team',
    },
    {
      method: 'POST',
      path: '/team-workouts/:id/join',
      auth: true,
      handler: 'custom',
      entity: 'team_members',
      description: 'Join team',
    },
    {
      method: 'DELETE',
      path: '/team-workouts/:id/leave',
      auth: true,
      handler: 'custom',
      entity: 'team_members',
      description: 'Leave team',
    },
    {
      method: 'GET',
      path: '/team-workouts/:id/members',
      auth: true,
      handler: 'crud',
      entity: 'team_members',
      description: 'Get team members',
    },
    {
      method: 'GET',
      path: '/team-workouts/:id/leaderboard',
      auth: true,
      handler: 'custom',
      entity: 'team_workouts',
      description: 'Get team leaderboard',
    },

    // Bootcamp Programs routes
    {
      method: 'GET',
      path: '/bootcamp-programs',
      auth: false,
      handler: 'crud',
      entity: 'bootcamp_programs',
      description: 'List bootcamp programs',
    },
    {
      method: 'POST',
      path: '/bootcamp-programs',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'bootcamp_programs',
      description: 'Create bootcamp program',
    },
    {
      method: 'GET',
      path: '/bootcamp-programs/:id',
      auth: false,
      handler: 'crud',
      entity: 'bootcamp_programs',
      description: 'Get bootcamp details',
    },
    {
      method: 'PUT',
      path: '/bootcamp-programs/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'bootcamp_programs',
      description: 'Update bootcamp',
    },
    {
      method: 'DELETE',
      path: '/bootcamp-programs/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'bootcamp_programs',
      description: 'Archive bootcamp',
    },
    {
      method: 'GET',
      path: '/bootcamp-programs/:id/schedule',
      auth: false,
      handler: 'custom',
      entity: 'bootcamp_programs',
      description: 'Get bootcamp schedule',
    },

    // Bootcamp Enrollments routes
    {
      method: 'POST',
      path: '/bootcamp-enrollments',
      auth: true,
      handler: 'crud',
      entity: 'bootcamp_enrollments',
      description: 'Enroll in bootcamp',
    },
    {
      method: 'GET',
      path: '/bootcamp-enrollments/:id',
      auth: true,
      handler: 'crud',
      entity: 'bootcamp_enrollments',
      description: 'Get enrollment details',
    },
    {
      method: 'DELETE',
      path: '/bootcamp-enrollments/:id',
      auth: true,
      handler: 'crud',
      entity: 'bootcamp_enrollments',
      description: 'Cancel enrollment',
    },
    {
      method: 'GET',
      path: '/my-bootcamps',
      auth: true,
      handler: 'custom',
      entity: 'bootcamp_enrollments',
      description: 'Get user bootcamp enrollments',
    },
    {
      method: 'GET',
      path: '/bootcamp-enrollments/:id/progress',
      auth: true,
      handler: 'custom',
      entity: 'bootcamp_enrollments',
      description: 'Get bootcamp progress',
    },
  ],

  config: [
    {
      key: 'minGroupSize',
      label: 'Minimum Group Size',
      type: 'number',
      default: 3,
      description: 'Minimum participants for a session to run',
    },
    {
      key: 'maxGroupSize',
      label: 'Maximum Group Size',
      type: 'number',
      default: 12,
      description: 'Maximum participants per group session',
    },
    {
      key: 'allowTeamCreation',
      label: 'Allow Member Team Creation',
      type: 'boolean',
      default: true,
      description: 'Allow members to create their own workout teams',
    },
    {
      key: 'bootcampPaymentPlan',
      label: 'Bootcamp Payment Plans',
      type: 'boolean',
      default: true,
      description: 'Allow payment plans for bootcamp programs',
    },
    {
      key: 'attendanceTracking',
      label: 'Attendance Tracking',
      type: 'boolean',
      default: true,
      description: 'Track and report session attendance',
    },
    {
      key: 'cancellationThreshold',
      label: 'Cancellation Threshold (%)',
      type: 'number',
      default: 50,
      description: 'Percentage below which session may be cancelled',
    },
  ],
};
