/**
 * Membership Plans Feature Definition
 *
 * Complete gym membership management functionality including plans,
 * member benefits, freezes, and member portal access.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const MEMBERSHIP_PLANS_FEATURE: FeatureDefinition = {
  id: 'membership-plans',
  name: 'Membership Plans',
  category: 'fitness',
  description: 'Manage gym memberships with tiered plans, benefits, billing, and member portal',
  icon: 'id-card',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'membership',
    'membership plans',
    'gym membership',
    'member portal',
    'subscription plans',
    'membership tiers',
    'gym plans',
    'fitness membership',
    'member benefits',
    'membership freeze',
    'member card',
    'membership signup',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'payments'],
  conflicts: [],

  pages: [
    {
      id: 'plans-list',
      route: '/memberships',
      section: 'frontend',
      title: 'Membership Plans',
      authRequired: false,
      templateId: 'plans-list',
      components: [
        'plan-card',
        'plan-comparison',
        'feature-highlights',
        'pricing-toggle',
        'cta-button',
      ],
      layout: 'default',
    },
    {
      id: 'plan-detail',
      route: '/memberships/:id',
      section: 'frontend',
      title: 'Plan Details',
      authRequired: false,
      templateId: 'plan-detail',
      components: [
        'plan-header',
        'benefits-list',
        'pricing-breakdown',
        'terms-conditions',
        'signup-cta',
      ],
      layout: 'default',
    },
    {
      id: 'membership-signup',
      route: '/memberships/:id/signup',
      section: 'frontend',
      title: 'Join Now',
      authRequired: true,
      templateId: 'membership-signup',
      components: [
        'signup-form',
        'plan-summary',
        'payment-form',
        'contract-agreement',
        'confirmation-step',
      ],
      layout: 'centered',
    },
    {
      id: 'member-portal',
      route: '/member',
      section: 'frontend',
      title: 'Member Portal',
      authRequired: true,
      templateId: 'member-portal',
      components: [
        'member-card',
        'membership-status',
        'benefits-overview',
        'usage-stats',
        'quick-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'member-billing',
      route: '/member/billing',
      section: 'frontend',
      title: 'Billing & Payments',
      authRequired: true,
      templateId: 'member-billing',
      components: [
        'payment-history',
        'next-payment',
        'payment-method',
        'invoice-download',
      ],
      layout: 'dashboard',
    },
    {
      id: 'freeze-request',
      route: '/member/freeze',
      section: 'frontend',
      title: 'Freeze Membership',
      authRequired: true,
      templateId: 'freeze-request',
      components: [
        'freeze-form',
        'freeze-policy',
        'date-picker',
        'confirmation-message',
      ],
      layout: 'centered',
    },
    {
      id: 'admin-memberships',
      route: '/admin/memberships',
      section: 'admin',
      title: 'Manage Memberships',
      authRequired: true,
      templateId: 'admin-memberships',
      components: [
        'memberships-table',
        'membership-filters',
        'member-search',
        'bulk-actions',
        'export-button',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-plans',
      route: '/admin/membership-plans',
      section: 'admin',
      title: 'Manage Plans',
      authRequired: true,
      templateId: 'admin-plans',
      components: [
        'plans-table',
        'plan-form',
        'benefits-editor',
        'pricing-editor',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Plan display components
    'plan-card',
    'plan-comparison',
    'feature-highlights',
    'pricing-toggle',
    'benefits-list',
    'pricing-breakdown',
    'terms-conditions',

    // Signup components
    'signup-form',
    'plan-summary',
    'payment-form',
    'contract-agreement',
    'confirmation-step',

    // Member portal components
    'member-card',
    'membership-status',
    'benefits-overview',
    'usage-stats',
    'quick-actions',
    'qr-code-display',

    // Billing components
    'payment-history',
    'next-payment',
    'payment-method',
    'invoice-download',

    // Freeze components
    'freeze-form',
    'freeze-policy',
    'freeze-status',

    // Admin components
    'memberships-table',
    'membership-filters',
    'member-search',
    'plans-table',
    'plan-form',
    'benefits-editor',
    'pricing-editor',
    'revenue-chart',
    'churn-analytics',
  ],

  entities: [
    {
      name: 'membership_plans',
      displayName: 'Membership Plans',
      description: 'Available membership plan definitions with pricing and benefits',
      isCore: true,
    },
    {
      name: 'memberships',
      displayName: 'Memberships',
      description: 'Active member subscriptions linking users to plans',
      isCore: true,
    },
    {
      name: 'member_benefits',
      displayName: 'Member Benefits',
      description: 'Benefits included in each membership plan',
      isCore: true,
    },
    {
      name: 'membership_freezes',
      displayName: 'Membership Freezes',
      description: 'Temporary membership freeze requests',
      isCore: false,
    },
    {
      name: 'membership_payments',
      displayName: 'Membership Payments',
      description: 'Payment history for memberships',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Membership Plans routes
    {
      method: 'GET',
      path: '/membership-plans',
      auth: false,
      handler: 'crud',
      entity: 'membership_plans',
      description: 'List all available membership plans',
    },
    {
      method: 'POST',
      path: '/membership-plans',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'membership_plans',
      description: 'Create a new membership plan',
    },
    {
      method: 'GET',
      path: '/membership-plans/:id',
      auth: false,
      handler: 'crud',
      entity: 'membership_plans',
      description: 'Get membership plan details',
    },
    {
      method: 'PUT',
      path: '/membership-plans/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'membership_plans',
      description: 'Update membership plan',
    },
    {
      method: 'DELETE',
      path: '/membership-plans/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'membership_plans',
      description: 'Archive membership plan',
    },

    // Memberships routes
    {
      method: 'GET',
      path: '/memberships',
      auth: true,
      handler: 'crud',
      entity: 'memberships',
      description: 'List user memberships',
    },
    {
      method: 'POST',
      path: '/memberships',
      auth: true,
      handler: 'crud',
      entity: 'memberships',
      description: 'Create new membership',
    },
    {
      method: 'GET',
      path: '/memberships/:id',
      auth: true,
      handler: 'crud',
      entity: 'memberships',
      description: 'Get membership details',
    },
    {
      method: 'PUT',
      path: '/memberships/:id',
      auth: true,
      handler: 'crud',
      entity: 'memberships',
      description: 'Update membership',
    },
    {
      method: 'POST',
      path: '/memberships/:id/cancel',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Cancel membership',
    },
    {
      method: 'POST',
      path: '/memberships/:id/upgrade',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Upgrade membership plan',
    },
    {
      method: 'POST',
      path: '/memberships/:id/downgrade',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Downgrade membership plan',
    },
    {
      method: 'GET',
      path: '/memberships/current',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Get current user membership',
    },

    // Member Benefits routes
    {
      method: 'GET',
      path: '/member-benefits',
      auth: false,
      handler: 'crud',
      entity: 'member_benefits',
      description: 'List all available benefits',
    },
    {
      method: 'GET',
      path: '/membership-plans/:id/benefits',
      auth: false,
      handler: 'custom',
      entity: 'member_benefits',
      description: 'Get benefits for a plan',
    },

    // Membership Freezes routes
    {
      method: 'GET',
      path: '/membership-freezes',
      auth: true,
      handler: 'crud',
      entity: 'membership_freezes',
      description: 'List user freeze requests',
    },
    {
      method: 'POST',
      path: '/membership-freezes',
      auth: true,
      handler: 'crud',
      entity: 'membership_freezes',
      description: 'Request membership freeze',
    },
    {
      method: 'PUT',
      path: '/membership-freezes/:id',
      auth: true,
      handler: 'crud',
      entity: 'membership_freezes',
      description: 'Update freeze request',
    },
    {
      method: 'DELETE',
      path: '/membership-freezes/:id',
      auth: true,
      handler: 'crud',
      entity: 'membership_freezes',
      description: 'Cancel freeze request',
    },
    {
      method: 'POST',
      path: '/membership-freezes/:id/approve',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'membership_freezes',
      description: 'Approve freeze request',
    },
    {
      method: 'POST',
      path: '/membership-freezes/:id/unfreeze',
      auth: true,
      handler: 'custom',
      entity: 'membership_freezes',
      description: 'End freeze early',
    },

    // Payment routes
    {
      method: 'GET',
      path: '/memberships/:id/payments',
      auth: true,
      handler: 'custom',
      entity: 'membership_payments',
      description: 'Get membership payment history',
    },
  ],

  config: [
    {
      key: 'trialPeriodDays',
      label: 'Trial Period (days)',
      type: 'number',
      default: 7,
      description: 'Number of days for free trial',
    },
    {
      key: 'freezeMaxDays',
      label: 'Maximum Freeze Duration (days)',
      type: 'number',
      default: 90,
      description: 'Maximum days a membership can be frozen',
    },
    {
      key: 'freezesPerYear',
      label: 'Freezes Allowed Per Year',
      type: 'number',
      default: 2,
      description: 'Number of freeze requests allowed per year',
    },
    {
      key: 'cancellationNoticeDays',
      label: 'Cancellation Notice (days)',
      type: 'number',
      default: 30,
      description: 'Required notice period for cancellation',
    },
    {
      key: 'autoRenewal',
      label: 'Auto-Renewal Default',
      type: 'boolean',
      default: true,
      description: 'Memberships auto-renew by default',
    },
    {
      key: 'proRatedUpgrades',
      label: 'Pro-Rated Upgrades',
      type: 'boolean',
      default: true,
      description: 'Calculate pro-rated amounts for plan changes',
    },
  ],
};
