/**
 * Nutrition Tracking Feature Definition
 *
 * Complete nutrition and meal tracking functionality including
 * food diary, meal plans, macro tracking, and recipe library.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const NUTRITION_TRACKING_FEATURE: FeatureDefinition = {
  id: 'nutrition-tracking',
  name: 'Nutrition Tracking',
  category: 'fitness',
  description: 'Track food intake, manage meal plans, monitor macros, and access healthy recipes',
  icon: 'utensils',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'nutrition tracking',
    'calorie tracking',
    'food diary',
    'meal planning',
    'macro tracking',
    'diet tracker',
    'calorie counter',
    'food log',
    'meal tracker',
    'nutrition log',
    'macros',
    'recipe library',
    'healthy eating',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'food-diary',
      route: '/nutrition',
      section: 'frontend',
      title: 'Food Diary',
      authRequired: true,
      templateId: 'food-diary',
      components: [
        'daily-overview',
        'meal-entry',
        'food-search',
        'calorie-chart',
        'macro-rings',
        'water-tracker',
      ],
      layout: 'dashboard',
    },
    {
      id: 'meal-plans',
      route: '/nutrition/meal-plans',
      section: 'frontend',
      title: 'Meal Plans',
      authRequired: true,
      templateId: 'meal-plans',
      components: [
        'meal-plan-list',
        'meal-plan-card',
        'plan-builder',
        'shopping-list-generator',
        'calorie-calculator',
      ],
      layout: 'default',
    },
    {
      id: 'meal-plan-detail',
      route: '/nutrition/meal-plans/:id',
      section: 'frontend',
      title: 'Meal Plan Details',
      authRequired: true,
      templateId: 'meal-plan-detail',
      components: [
        'plan-overview',
        'daily-meals',
        'nutrition-breakdown',
        'shopping-list',
        'prep-instructions',
      ],
      layout: 'default',
    },
    {
      id: 'macro-tracker',
      route: '/nutrition/macros',
      section: 'frontend',
      title: 'Macro Tracker',
      authRequired: true,
      templateId: 'macro-tracker',
      components: [
        'macro-rings',
        'macro-goals',
        'macro-history',
        'macro-breakdown',
        'goal-adjuster',
      ],
      layout: 'dashboard',
    },
    {
      id: 'recipe-library',
      route: '/nutrition/recipes',
      section: 'frontend',
      title: 'Recipe Library',
      authRequired: false,
      templateId: 'recipe-library',
      components: [
        'recipe-grid',
        'recipe-card',
        'recipe-search',
        'category-filter',
        'nutrition-filter',
        'save-recipe-button',
      ],
      layout: 'default',
    },
    {
      id: 'recipe-detail',
      route: '/nutrition/recipes/:id',
      section: 'frontend',
      title: 'Recipe Details',
      authRequired: false,
      templateId: 'recipe-detail',
      components: [
        'recipe-header',
        'ingredients-list',
        'instructions',
        'nutrition-info',
        'log-meal-button',
        'save-button',
      ],
      layout: 'default',
    },
    {
      id: 'nutrition-goals',
      route: '/nutrition/goals',
      section: 'frontend',
      title: 'Nutrition Goals',
      authRequired: true,
      templateId: 'nutrition-goals',
      components: [
        'goal-form',
        'calorie-calculator',
        'macro-calculator',
        'goal-recommendations',
        'progress-tracker',
      ],
      layout: 'centered',
    },
    {
      id: 'admin-recipes',
      route: '/admin/recipes',
      section: 'admin',
      title: 'Manage Recipes',
      authRequired: true,
      templateId: 'admin-recipes',
      components: [
        'recipes-table',
        'recipe-form',
        'ingredient-editor',
        'nutrition-calculator',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-meal-plans',
      route: '/admin/meal-plans',
      section: 'admin',
      title: 'Manage Meal Plans',
      authRequired: true,
      templateId: 'admin-meal-plans',
      components: [
        'meal-plans-table',
        'meal-plan-builder',
        'template-manager',
        'assignment-tool',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Food diary components
    'daily-overview',
    'meal-entry',
    'food-search',
    'calorie-chart',
    'macro-rings',
    'water-tracker',
    'quick-add-food',
    'barcode-scanner',

    // Meal plan components
    'meal-plan-list',
    'meal-plan-card',
    'plan-builder',
    'shopping-list-generator',
    'calorie-calculator',
    'daily-meals',
    'nutrition-breakdown',
    'shopping-list',
    'prep-instructions',

    // Macro components
    'macro-goals',
    'macro-history',
    'macro-breakdown',
    'goal-adjuster',
    'macro-calculator',

    // Recipe components
    'recipe-grid',
    'recipe-card',
    'recipe-search',
    'category-filter',
    'nutrition-filter',
    'recipe-header',
    'ingredients-list',
    'instructions',
    'nutrition-info',
    'log-meal-button',
    'save-button',

    // Goal components
    'goal-form',
    'goal-recommendations',
    'progress-tracker',

    // Admin components
    'recipes-table',
    'recipe-form',
    'ingredient-editor',
    'nutrition-calculator',
    'meal-plans-table',
    'meal-plan-builder',
    'template-manager',
    'assignment-tool',
  ],

  entities: [
    {
      name: 'food_entries',
      displayName: 'Food Entries',
      description: 'Logged food and meal entries',
      isCore: true,
    },
    {
      name: 'meals',
      displayName: 'Meals',
      description: 'Meal definitions (breakfast, lunch, dinner, snacks)',
      isCore: true,
    },
    {
      name: 'nutrition_goals',
      displayName: 'Nutrition Goals',
      description: 'User calorie and macro goals',
      isCore: true,
    },
    {
      name: 'recipes',
      displayName: 'Recipes',
      description: 'Healthy recipe library',
      isCore: true,
    },
    {
      name: 'meal_plans',
      displayName: 'Meal Plans',
      description: 'Structured meal plans',
      isCore: false,
    },
    {
      name: 'food_database',
      displayName: 'Food Database',
      description: 'Food items with nutritional information',
      isCore: false,
    },
    {
      name: 'saved_recipes',
      displayName: 'Saved Recipes',
      description: 'User saved/favorite recipes',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Food Entries routes
    {
      method: 'GET',
      path: '/food-entries',
      auth: true,
      handler: 'crud',
      entity: 'food_entries',
      description: 'List user food entries',
    },
    {
      method: 'POST',
      path: '/food-entries',
      auth: true,
      handler: 'crud',
      entity: 'food_entries',
      description: 'Log food entry',
    },
    {
      method: 'GET',
      path: '/food-entries/:id',
      auth: true,
      handler: 'crud',
      entity: 'food_entries',
      description: 'Get food entry',
    },
    {
      method: 'PUT',
      path: '/food-entries/:id',
      auth: true,
      handler: 'crud',
      entity: 'food_entries',
      description: 'Update food entry',
    },
    {
      method: 'DELETE',
      path: '/food-entries/:id',
      auth: true,
      handler: 'crud',
      entity: 'food_entries',
      description: 'Delete food entry',
    },
    {
      method: 'GET',
      path: '/food-entries/daily',
      auth: true,
      handler: 'custom',
      entity: 'food_entries',
      description: 'Get daily food log',
    },
    {
      method: 'GET',
      path: '/food-entries/summary',
      auth: true,
      handler: 'aggregate',
      entity: 'food_entries',
      description: 'Get nutrition summary',
    },

    // Meals routes
    {
      method: 'GET',
      path: '/meals',
      auth: true,
      handler: 'crud',
      entity: 'meals',
      description: 'List meals',
    },
    {
      method: 'POST',
      path: '/meals',
      auth: true,
      handler: 'crud',
      entity: 'meals',
      description: 'Create custom meal',
    },
    {
      method: 'PUT',
      path: '/meals/:id',
      auth: true,
      handler: 'crud',
      entity: 'meals',
      description: 'Update meal',
    },

    // Nutrition Goals routes
    {
      method: 'GET',
      path: '/nutrition-goals',
      auth: true,
      handler: 'crud',
      entity: 'nutrition_goals',
      description: 'Get user nutrition goals',
    },
    {
      method: 'POST',
      path: '/nutrition-goals',
      auth: true,
      handler: 'crud',
      entity: 'nutrition_goals',
      description: 'Set nutrition goals',
    },
    {
      method: 'PUT',
      path: '/nutrition-goals/:id',
      auth: true,
      handler: 'crud',
      entity: 'nutrition_goals',
      description: 'Update nutrition goals',
    },
    {
      method: 'GET',
      path: '/nutrition-goals/calculate',
      auth: true,
      handler: 'custom',
      entity: 'nutrition_goals',
      description: 'Calculate recommended goals',
    },

    // Recipes routes
    {
      method: 'GET',
      path: '/recipes',
      auth: false,
      handler: 'crud',
      entity: 'recipes',
      description: 'List recipes',
    },
    {
      method: 'POST',
      path: '/recipes',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recipes',
      description: 'Create recipe',
    },
    {
      method: 'GET',
      path: '/recipes/:id',
      auth: false,
      handler: 'crud',
      entity: 'recipes',
      description: 'Get recipe details',
    },
    {
      method: 'PUT',
      path: '/recipes/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recipes',
      description: 'Update recipe',
    },
    {
      method: 'DELETE',
      path: '/recipes/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recipes',
      description: 'Delete recipe',
    },
    {
      method: 'GET',
      path: '/recipes/search',
      auth: false,
      handler: 'custom',
      entity: 'recipes',
      description: 'Search recipes',
    },

    // Meal Plans routes
    {
      method: 'GET',
      path: '/meal-plans',
      auth: true,
      handler: 'crud',
      entity: 'meal_plans',
      description: 'List meal plans',
    },
    {
      method: 'POST',
      path: '/meal-plans',
      auth: true,
      handler: 'crud',
      entity: 'meal_plans',
      description: 'Create meal plan',
    },
    {
      method: 'GET',
      path: '/meal-plans/:id',
      auth: true,
      handler: 'crud',
      entity: 'meal_plans',
      description: 'Get meal plan',
    },
    {
      method: 'PUT',
      path: '/meal-plans/:id',
      auth: true,
      handler: 'crud',
      entity: 'meal_plans',
      description: 'Update meal plan',
    },
    {
      method: 'DELETE',
      path: '/meal-plans/:id',
      auth: true,
      handler: 'crud',
      entity: 'meal_plans',
      description: 'Delete meal plan',
    },
    {
      method: 'GET',
      path: '/meal-plans/:id/shopping-list',
      auth: true,
      handler: 'custom',
      entity: 'meal_plans',
      description: 'Generate shopping list',
    },

    // Food Database routes
    {
      method: 'GET',
      path: '/food-database/search',
      auth: true,
      handler: 'custom',
      entity: 'food_database',
      description: 'Search food database',
    },
    {
      method: 'GET',
      path: '/food-database/:id',
      auth: true,
      handler: 'crud',
      entity: 'food_database',
      description: 'Get food item details',
    },
    {
      method: 'POST',
      path: '/food-database',
      auth: true,
      handler: 'crud',
      entity: 'food_database',
      description: 'Add custom food item',
    },
    {
      method: 'GET',
      path: '/food-database/barcode/:code',
      auth: true,
      handler: 'custom',
      entity: 'food_database',
      description: 'Lookup food by barcode',
    },

    // Saved Recipes routes
    {
      method: 'GET',
      path: '/saved-recipes',
      auth: true,
      handler: 'crud',
      entity: 'saved_recipes',
      description: 'Get saved recipes',
    },
    {
      method: 'POST',
      path: '/saved-recipes',
      auth: true,
      handler: 'crud',
      entity: 'saved_recipes',
      description: 'Save recipe',
    },
    {
      method: 'DELETE',
      path: '/saved-recipes/:id',
      auth: true,
      handler: 'crud',
      entity: 'saved_recipes',
      description: 'Remove saved recipe',
    },
  ],

  config: [
    {
      key: 'defaultCalorieGoal',
      label: 'Default Calorie Goal',
      type: 'number',
      default: 2000,
      description: 'Default daily calorie goal for new users',
    },
    {
      key: 'macroSplit',
      label: 'Default Macro Split',
      type: 'select',
      default: 'balanced',
      options: [
        { value: 'balanced', label: 'Balanced (40/30/30)' },
        { value: 'lowCarb', label: 'Low Carb (25/40/35)' },
        { value: 'highProtein', label: 'High Protein (40/35/25)' },
        { value: 'keto', label: 'Keto (5/25/70)' },
        { value: 'custom', label: 'Custom' },
      ],
      description: 'Default macro distribution (carbs/protein/fat)',
    },
    {
      key: 'mealTypes',
      label: 'Meal Types',
      type: 'select',
      default: 'standard',
      options: [
        { value: 'standard', label: '3 meals + snacks' },
        { value: 'fiveSmall', label: '5 small meals' },
        { value: 'intermittent', label: 'Intermittent fasting (2 meals)' },
      ],
      description: 'Default meal structure',
    },
    {
      key: 'trackWater',
      label: 'Track Water Intake',
      type: 'boolean',
      default: true,
      description: 'Include water tracking in food diary',
    },
    {
      key: 'mealReminders',
      label: 'Meal Logging Reminders',
      type: 'boolean',
      default: true,
      description: 'Send reminders to log meals',
    },
    {
      key: 'showNutritionDetails',
      label: 'Show Detailed Nutrition',
      type: 'boolean',
      default: true,
      description: 'Show vitamins and minerals in addition to macros',
    },
  ],
};
