/**
 * Trainer Booking Feature Definition
 *
 * Complete personal trainer booking functionality including
 * trainer profiles, session booking, and training packages.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TRAINER_BOOKING_FEATURE: FeatureDefinition = {
  id: 'trainer-booking',
  name: 'Trainer Booking',
  category: 'fitness',
  description: 'Book personal training sessions, purchase packages, and manage trainer relationships',
  icon: 'user-check',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'personal trainer',
    'trainer booking',
    'PT sessions',
    'personal training',
    'trainer appointments',
    'fitness coach',
    'training sessions',
    'book trainer',
    'PT packages',
    'one on one training',
    '1:1 training',
    'private coaching',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'payments', 'calendar'],
  conflicts: [],

  pages: [
    {
      id: 'trainer-list',
      route: '/trainers',
      section: 'frontend',
      title: 'Our Trainers',
      authRequired: false,
      templateId: 'trainer-list',
      components: [
        'trainer-grid',
        'trainer-card',
        'specialty-filter',
        'availability-filter',
        'rating-filter',
      ],
      layout: 'default',
    },
    {
      id: 'trainer-profile',
      route: '/trainers/:id',
      section: 'frontend',
      title: 'Trainer Profile',
      authRequired: false,
      templateId: 'trainer-profile',
      components: [
        'trainer-header',
        'trainer-bio',
        'certifications-list',
        'specialties-badges',
        'trainer-gallery',
        'client-reviews',
        'availability-calendar',
        'booking-cta',
      ],
      layout: 'default',
    },
    {
      id: 'session-booking',
      route: '/trainers/:id/book',
      section: 'frontend',
      title: 'Book Session',
      authRequired: true,
      templateId: 'session-booking',
      components: [
        'session-type-selector',
        'date-picker',
        'time-slot-picker',
        'session-form',
        'package-selector',
        'payment-summary',
      ],
      layout: 'centered',
    },
    {
      id: 'package-purchase',
      route: '/trainers/:id/packages',
      section: 'frontend',
      title: 'Training Packages',
      authRequired: true,
      templateId: 'package-purchase',
      components: [
        'package-card',
        'package-comparison',
        'savings-calculator',
        'purchase-form',
        'payment-processor',
      ],
      layout: 'default',
    },
    {
      id: 'my-sessions',
      route: '/my-sessions',
      section: 'frontend',
      title: 'My Training Sessions',
      authRequired: true,
      templateId: 'my-sessions',
      components: [
        'upcoming-sessions',
        'past-sessions',
        'package-balance',
        'reschedule-button',
        'cancel-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'session-detail',
      route: '/sessions/:id',
      section: 'frontend',
      title: 'Session Details',
      authRequired: true,
      templateId: 'session-detail',
      components: [
        'session-header',
        'session-info',
        'trainer-contact',
        'session-notes',
        'workout-plan',
      ],
      layout: 'default',
    },
    {
      id: 'admin-trainers',
      route: '/admin/trainers',
      section: 'admin',
      title: 'Manage Trainers',
      authRequired: true,
      templateId: 'admin-trainers',
      components: [
        'trainers-table',
        'trainer-form',
        'schedule-manager',
        'commission-settings',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-sessions',
      route: '/admin/training-sessions',
      section: 'admin',
      title: 'All Sessions',
      authRequired: true,
      templateId: 'admin-sessions',
      components: [
        'sessions-table',
        'session-filters',
        'calendar-view',
        'revenue-report',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-packages',
      route: '/admin/training-packages',
      section: 'admin',
      title: 'Training Packages',
      authRequired: true,
      templateId: 'admin-packages',
      components: [
        'packages-table',
        'package-form',
        'pricing-editor',
        'package-analytics',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Trainer list components
    'trainer-grid',
    'trainer-card',
    'specialty-filter',
    'availability-filter',
    'rating-filter',

    // Trainer profile components
    'trainer-header',
    'trainer-bio',
    'certifications-list',
    'specialties-badges',
    'trainer-gallery',
    'client-reviews',
    'booking-cta',

    // Booking components
    'session-type-selector',
    'date-picker',
    'time-slot-picker',
    'session-form',
    'package-selector',
    'payment-summary',
    'availability-calendar',

    // Package components
    'package-card',
    'package-comparison',
    'savings-calculator',
    'purchase-form',
    'payment-processor',
    'package-balance',

    // Session components
    'upcoming-sessions',
    'past-sessions',
    'session-header',
    'session-info',
    'trainer-contact',
    'session-notes',
    'workout-plan',
    'reschedule-button',
    'cancel-button',

    // Admin components
    'trainers-table',
    'trainer-form',
    'schedule-manager',
    'commission-settings',
    'sessions-table',
    'session-filters',
    'calendar-view',
    'revenue-report',
    'packages-table',
    'package-form',
    'pricing-editor',
    'package-analytics',
  ],

  entities: [
    {
      name: 'trainers',
      displayName: 'Trainers',
      description: 'Personal trainer profiles with certifications and specialties',
      isCore: true,
    },
    {
      name: 'training_sessions',
      displayName: 'Training Sessions',
      description: 'Booked personal training sessions',
      isCore: true,
    },
    {
      name: 'training_packages',
      displayName: 'Training Packages',
      description: 'Session packages with discounted pricing',
      isCore: true,
    },
    {
      name: 'trainer_availability',
      displayName: 'Trainer Availability',
      description: 'Trainer schedule and availability',
      isCore: true,
    },
    {
      name: 'package_purchases',
      displayName: 'Package Purchases',
      description: 'User purchased training packages',
      isCore: false,
    },
    {
      name: 'trainer_reviews',
      displayName: 'Trainer Reviews',
      description: 'Client reviews and ratings for trainers',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Trainers routes
    {
      method: 'GET',
      path: '/trainers',
      auth: false,
      handler: 'crud',
      entity: 'trainers',
      description: 'List all trainers',
    },
    {
      method: 'POST',
      path: '/trainers',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'trainers',
      description: 'Create trainer profile',
    },
    {
      method: 'GET',
      path: '/trainers/:id',
      auth: false,
      handler: 'crud',
      entity: 'trainers',
      description: 'Get trainer profile',
    },
    {
      method: 'PUT',
      path: '/trainers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'trainers',
      description: 'Update trainer profile',
    },
    {
      method: 'DELETE',
      path: '/trainers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'trainers',
      description: 'Remove trainer',
    },
    {
      method: 'GET',
      path: '/trainers/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'trainer_availability',
      description: 'Get trainer availability',
    },
    {
      method: 'GET',
      path: '/trainers/:id/reviews',
      auth: false,
      handler: 'custom',
      entity: 'trainer_reviews',
      description: 'Get trainer reviews',
    },

    // Training Sessions routes
    {
      method: 'GET',
      path: '/training-sessions',
      auth: true,
      handler: 'crud',
      entity: 'training_sessions',
      description: 'List user training sessions',
    },
    {
      method: 'POST',
      path: '/training-sessions',
      auth: true,
      handler: 'crud',
      entity: 'training_sessions',
      description: 'Book training session',
    },
    {
      method: 'GET',
      path: '/training-sessions/:id',
      auth: true,
      handler: 'crud',
      entity: 'training_sessions',
      description: 'Get session details',
    },
    {
      method: 'PUT',
      path: '/training-sessions/:id',
      auth: true,
      handler: 'crud',
      entity: 'training_sessions',
      description: 'Update session',
    },
    {
      method: 'DELETE',
      path: '/training-sessions/:id',
      auth: true,
      handler: 'crud',
      entity: 'training_sessions',
      description: 'Cancel session',
    },
    {
      method: 'POST',
      path: '/training-sessions/:id/reschedule',
      auth: true,
      handler: 'custom',
      entity: 'training_sessions',
      description: 'Reschedule session',
    },
    {
      method: 'POST',
      path: '/training-sessions/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'training_sessions',
      description: 'Mark session as complete',
    },
    {
      method: 'POST',
      path: '/training-sessions/:id/notes',
      auth: true,
      handler: 'custom',
      entity: 'training_sessions',
      description: 'Add session notes',
    },

    // Training Packages routes
    {
      method: 'GET',
      path: '/training-packages',
      auth: false,
      handler: 'crud',
      entity: 'training_packages',
      description: 'List available packages',
    },
    {
      method: 'POST',
      path: '/training-packages',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'training_packages',
      description: 'Create training package',
    },
    {
      method: 'GET',
      path: '/training-packages/:id',
      auth: false,
      handler: 'crud',
      entity: 'training_packages',
      description: 'Get package details',
    },
    {
      method: 'PUT',
      path: '/training-packages/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'training_packages',
      description: 'Update package',
    },
    {
      method: 'DELETE',
      path: '/training-packages/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'training_packages',
      description: 'Archive package',
    },
    {
      method: 'GET',
      path: '/trainers/:id/packages',
      auth: false,
      handler: 'custom',
      entity: 'training_packages',
      description: 'Get trainer packages',
    },

    // Package Purchases routes
    {
      method: 'GET',
      path: '/my-packages',
      auth: true,
      handler: 'crud',
      entity: 'package_purchases',
      description: 'Get user purchased packages',
    },
    {
      method: 'POST',
      path: '/package-purchases',
      auth: true,
      handler: 'crud',
      entity: 'package_purchases',
      description: 'Purchase a package',
    },
    {
      method: 'GET',
      path: '/package-purchases/:id',
      auth: true,
      handler: 'crud',
      entity: 'package_purchases',
      description: 'Get purchase details',
    },
    {
      method: 'GET',
      path: '/package-purchases/:id/balance',
      auth: true,
      handler: 'custom',
      entity: 'package_purchases',
      description: 'Get remaining sessions',
    },

    // Trainer Availability routes
    {
      method: 'GET',
      path: '/trainer-availability',
      auth: true,
      handler: 'crud',
      entity: 'trainer_availability',
      description: 'Get availability settings',
    },
    {
      method: 'PUT',
      path: '/trainer-availability',
      auth: true,
      handler: 'crud',
      entity: 'trainer_availability',
      description: 'Update availability',
    },
    {
      method: 'POST',
      path: '/trainer-availability/block',
      auth: true,
      handler: 'custom',
      entity: 'trainer_availability',
      description: 'Block time slots',
    },

    // Trainer Reviews routes
    {
      method: 'POST',
      path: '/trainer-reviews',
      auth: true,
      handler: 'crud',
      entity: 'trainer_reviews',
      description: 'Submit trainer review',
    },
    {
      method: 'PUT',
      path: '/trainer-reviews/:id',
      auth: true,
      handler: 'crud',
      entity: 'trainer_reviews',
      description: 'Update review',
    },
    {
      method: 'DELETE',
      path: '/trainer-reviews/:id',
      auth: true,
      handler: 'crud',
      entity: 'trainer_reviews',
      description: 'Delete review',
    },
  ],

  config: [
    {
      key: 'defaultSessionDuration',
      label: 'Default Session Duration (minutes)',
      type: 'number',
      default: 60,
      description: 'Default duration for training sessions',
    },
    {
      key: 'cancellationPolicy',
      label: 'Cancellation Notice (hours)',
      type: 'number',
      default: 24,
      description: 'Required notice for free cancellation',
    },
    {
      key: 'packageExpiry',
      label: 'Package Expiry (months)',
      type: 'number',
      default: 6,
      description: 'How long purchased packages remain valid',
    },
    {
      key: 'trainerCommission',
      label: 'Trainer Commission (%)',
      type: 'number',
      default: 70,
      description: 'Percentage of session fee that goes to trainer',
    },
    {
      key: 'requireDeposit',
      label: 'Require Booking Deposit',
      type: 'boolean',
      default: false,
      description: 'Require deposit when booking individual sessions',
    },
    {
      key: 'allowGiftPackages',
      label: 'Allow Gift Packages',
      type: 'boolean',
      default: true,
      description: 'Allow purchasing packages as gifts',
    },
  ],
};
