/**
 * Workout Tracking Feature Definition
 *
 * Complete workout logging and tracking functionality including
 * exercise library, workout builder, personal records, and progress charts.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const WORKOUT_TRACKING_FEATURE: FeatureDefinition = {
  id: 'workout-tracking',
  name: 'Workout Tracking',
  category: 'fitness',
  description: 'Log workouts, track exercises, monitor progress, and celebrate personal records',
  icon: 'dumbbell',

  includedInAppTypes: [
    'gym',
    'fitness',
    'yoga-studio',
    'crossfit-gym',
    'martial-arts',
    'dance-studio',
    'swimming-pool',
    'personal-training',
    'sports-club',
  ],

  activationKeywords: [
    'workout tracking',
    'workout log',
    'exercise log',
    'fitness tracking',
    'workout diary',
    'gym tracker',
    'exercise tracker',
    'personal records',
    'PR tracker',
    'weight training log',
    'strength training',
    'workout builder',
    'exercise library',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'workout-log',
      route: '/workouts',
      section: 'frontend',
      title: 'Workout Log',
      authRequired: true,
      templateId: 'workout-log',
      components: [
        'workout-list',
        'workout-card',
        'quick-log-button',
        'date-filter',
        'workout-stats',
      ],
      layout: 'default',
    },
    {
      id: 'workout-builder',
      route: '/workouts/new',
      section: 'frontend',
      title: 'Log Workout',
      authRequired: true,
      templateId: 'workout-builder',
      components: [
        'workout-builder',
        'exercise-picker',
        'set-tracker',
        'rest-timer',
        'notes-input',
      ],
      layout: 'default',
    },
    {
      id: 'workout-detail',
      route: '/workouts/:id',
      section: 'frontend',
      title: 'Workout Details',
      authRequired: true,
      templateId: 'workout-detail',
      components: [
        'workout-header',
        'exercise-list',
        'workout-notes',
        'edit-button',
        'share-button',
      ],
      layout: 'default',
    },
    {
      id: 'exercise-library',
      route: '/exercises',
      section: 'frontend',
      title: 'Exercise Library',
      authRequired: false,
      templateId: 'exercise-library',
      components: [
        'exercise-search',
        'muscle-group-filter',
        'equipment-filter',
        'exercise-card',
        'exercise-demo',
      ],
      layout: 'default',
    },
    {
      id: 'exercise-detail',
      route: '/exercises/:id',
      section: 'frontend',
      title: 'Exercise Details',
      authRequired: false,
      templateId: 'exercise-detail',
      components: [
        'exercise-header',
        'video-demo',
        'instructions',
        'muscles-diagram',
        'exercise-history',
      ],
      layout: 'default',
    },
    {
      id: 'workout-history',
      route: '/workouts/history',
      section: 'frontend',
      title: 'Workout History',
      authRequired: true,
      templateId: 'workout-history',
      components: [
        'calendar-heatmap',
        'workout-timeline',
        'volume-chart',
        'frequency-stats',
      ],
      layout: 'default',
    },
    {
      id: 'personal-records',
      route: '/personal-records',
      section: 'frontend',
      title: 'Personal Records',
      authRequired: true,
      templateId: 'personal-records',
      components: [
        'pr-display',
        'pr-timeline',
        'exercise-prs',
        'recent-prs',
        'pr-goals',
      ],
      layout: 'default',
    },
    {
      id: 'progress-charts',
      route: '/progress',
      section: 'frontend',
      title: 'Progress',
      authRequired: true,
      templateId: 'progress-charts',
      components: [
        'progress-chart',
        'strength-progress',
        'volume-trends',
        'consistency-score',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-exercises',
      route: '/admin/exercises',
      section: 'admin',
      title: 'Manage Exercises',
      authRequired: true,
      templateId: 'admin-exercises',
      components: [
        'exercises-table',
        'exercise-form',
        'video-uploader',
        'muscle-selector',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Workout log components
    'workout-list',
    'workout-card',
    'quick-log-button',
    'workout-stats',

    // Workout builder components
    'workout-builder',
    'exercise-picker',
    'set-tracker',
    'rest-timer',
    'notes-input',
    'superset-builder',
    'template-selector',

    // Exercise library components
    'exercise-search',
    'muscle-group-filter',
    'equipment-filter',
    'exercise-card',
    'exercise-demo',
    'video-demo',
    'instructions',
    'muscles-diagram',
    'exercise-history',

    // Personal records components
    'pr-display',
    'pr-timeline',
    'exercise-prs',
    'recent-prs',
    'pr-goals',
    'pr-celebration',

    // Progress components
    'progress-chart',
    'strength-progress',
    'volume-trends',
    'consistency-score',
    'calendar-heatmap',
    'workout-timeline',
    'volume-chart',
    'frequency-stats',

    // Admin components
    'exercises-table',
    'exercise-form',
    'video-uploader',
    'muscle-selector',
  ],

  entities: [
    {
      name: 'workouts',
      displayName: 'Workouts',
      description: 'Logged workout sessions',
      isCore: true,
    },
    {
      name: 'exercises',
      displayName: 'Exercises',
      description: 'Exercise definitions with instructions and demos',
      isCore: true,
    },
    {
      name: 'workout_sets',
      displayName: 'Workout Sets',
      description: 'Individual sets within a workout',
      isCore: true,
    },
    {
      name: 'personal_records',
      displayName: 'Personal Records',
      description: 'User personal bests for exercises',
      isCore: true,
    },
    {
      name: 'workout_templates',
      displayName: 'Workout Templates',
      description: 'Saved workout routines for quick logging',
      isCore: false,
    },
    {
      name: 'muscle_groups',
      displayName: 'Muscle Groups',
      description: 'Muscle group definitions for exercise categorization',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Workouts routes
    {
      method: 'GET',
      path: '/workouts',
      auth: true,
      handler: 'crud',
      entity: 'workouts',
      description: 'List user workouts',
    },
    {
      method: 'POST',
      path: '/workouts',
      auth: true,
      handler: 'crud',
      entity: 'workouts',
      description: 'Log a new workout',
    },
    {
      method: 'GET',
      path: '/workouts/:id',
      auth: true,
      handler: 'crud',
      entity: 'workouts',
      description: 'Get workout details',
    },
    {
      method: 'PUT',
      path: '/workouts/:id',
      auth: true,
      handler: 'crud',
      entity: 'workouts',
      description: 'Update workout',
    },
    {
      method: 'DELETE',
      path: '/workouts/:id',
      auth: true,
      handler: 'crud',
      entity: 'workouts',
      description: 'Delete workout',
    },
    {
      method: 'GET',
      path: '/workouts/stats',
      auth: true,
      handler: 'aggregate',
      entity: 'workouts',
      description: 'Get workout statistics',
    },
    {
      method: 'GET',
      path: '/workouts/history',
      auth: true,
      handler: 'custom',
      entity: 'workouts',
      description: 'Get workout history with calendar data',
    },

    // Exercises routes
    {
      method: 'GET',
      path: '/exercises',
      auth: false,
      handler: 'crud',
      entity: 'exercises',
      description: 'List all exercises',
    },
    {
      method: 'POST',
      path: '/exercises',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'exercises',
      description: 'Create exercise',
    },
    {
      method: 'GET',
      path: '/exercises/:id',
      auth: false,
      handler: 'crud',
      entity: 'exercises',
      description: 'Get exercise details',
    },
    {
      method: 'PUT',
      path: '/exercises/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'exercises',
      description: 'Update exercise',
    },
    {
      method: 'DELETE',
      path: '/exercises/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'exercises',
      description: 'Delete exercise',
    },
    {
      method: 'GET',
      path: '/exercises/:id/history',
      auth: true,
      handler: 'custom',
      entity: 'workout_sets',
      description: 'Get exercise history for user',
    },

    // Workout Sets routes
    {
      method: 'GET',
      path: '/workouts/:id/sets',
      auth: true,
      handler: 'crud',
      entity: 'workout_sets',
      description: 'Get sets for a workout',
    },
    {
      method: 'POST',
      path: '/workouts/:id/sets',
      auth: true,
      handler: 'crud',
      entity: 'workout_sets',
      description: 'Add set to workout',
    },
    {
      method: 'PUT',
      path: '/workout-sets/:id',
      auth: true,
      handler: 'crud',
      entity: 'workout_sets',
      description: 'Update set',
    },
    {
      method: 'DELETE',
      path: '/workout-sets/:id',
      auth: true,
      handler: 'crud',
      entity: 'workout_sets',
      description: 'Delete set',
    },

    // Personal Records routes
    {
      method: 'GET',
      path: '/personal-records',
      auth: true,
      handler: 'crud',
      entity: 'personal_records',
      description: 'Get user personal records',
    },
    {
      method: 'GET',
      path: '/personal-records/:exerciseId',
      auth: true,
      handler: 'custom',
      entity: 'personal_records',
      description: 'Get PR for specific exercise',
    },
    {
      method: 'GET',
      path: '/personal-records/recent',
      auth: true,
      handler: 'custom',
      entity: 'personal_records',
      description: 'Get recently broken PRs',
    },

    // Workout Templates routes
    {
      method: 'GET',
      path: '/workout-templates',
      auth: true,
      handler: 'crud',
      entity: 'workout_templates',
      description: 'List user workout templates',
    },
    {
      method: 'POST',
      path: '/workout-templates',
      auth: true,
      handler: 'crud',
      entity: 'workout_templates',
      description: 'Save workout as template',
    },
    {
      method: 'PUT',
      path: '/workout-templates/:id',
      auth: true,
      handler: 'crud',
      entity: 'workout_templates',
      description: 'Update template',
    },
    {
      method: 'DELETE',
      path: '/workout-templates/:id',
      auth: true,
      handler: 'crud',
      entity: 'workout_templates',
      description: 'Delete template',
    },

    // Muscle Groups routes
    {
      method: 'GET',
      path: '/muscle-groups',
      auth: false,
      handler: 'crud',
      entity: 'muscle_groups',
      description: 'List muscle groups',
    },
  ],

  config: [
    {
      key: 'defaultRestTime',
      label: 'Default Rest Time (seconds)',
      type: 'number',
      default: 90,
      description: 'Default rest timer duration between sets',
    },
    {
      key: 'autoDetectPR',
      label: 'Auto-Detect Personal Records',
      type: 'boolean',
      default: true,
      description: 'Automatically detect and celebrate new PRs',
    },
    {
      key: 'prMetrics',
      label: 'PR Tracking Metrics',
      type: 'select',
      default: 'weight',
      options: [
        { value: 'weight', label: 'Max Weight' },
        { value: 'volume', label: 'Total Volume' },
        { value: 'reps', label: 'Max Reps' },
        { value: 'all', label: 'All Metrics' },
      ],
      description: 'Which metrics to track for personal records',
    },
    {
      key: 'showExerciseHistory',
      label: 'Show Exercise History in Builder',
      type: 'boolean',
      default: true,
      description: 'Display previous performance when logging exercises',
    },
    {
      key: 'workoutReminders',
      label: 'Workout Reminders',
      type: 'boolean',
      default: true,
      description: 'Send reminders based on workout schedule',
    },
  ],
};
