/**
 * Immunizations Feature Definition
 *
 * Vaccination records and schedule management for healthcare applications.
 * Includes immunization tracking, reminders, and reporting.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const IMMUNIZATIONS_FEATURE: FeatureDefinition = {
  id: 'immunizations',
  name: 'Immunizations',
  category: 'healthcare',
  description: 'Manage vaccination records, schedules, and immunization tracking',
  icon: 'syringe',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'hospital',
    'pediatrics',
    'family-practice',
    'urgent-care',
    'pharmacy',
    'public-health',
    'school-health',
    'occupational-health',
    'travel-medicine',
    'immunization-clinic',
    'vaccination-center',
    'community-health',
  ],

  activationKeywords: [
    'immunizations',
    'immunization',
    'vaccinations',
    'vaccines',
    'vaccine',
    'shots',
    'immunization records',
    'vaccination schedule',
    'vaccine tracking',
    'immunization registry',
    'iis',
    'vaccine history',
    'booster',
    'flu shot',
    'covid vaccine',
    'childhood vaccines',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'patient-records'],
  conflicts: [],

  pages: [
    {
      id: 'immunization-records',
      route: '/immunizations',
      section: 'frontend',
      title: 'Immunization Records',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'pharmacist'],
      templateId: 'immunization-records',
      components: [
        'immunization-table',
        'immunization-filters',
        'due-vaccines-list',
        'patient-search',
        'immunization-stats',
      ],
      layout: 'dashboard',
    },
    {
      id: 'vaccine-schedule',
      route: '/immunizations/schedule',
      section: 'frontend',
      title: 'Vaccine Schedule',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'vaccine-schedule',
      components: [
        'schedule-tracker',
        'recommended-vaccines',
        'age-based-schedule',
        'catch-up-schedule',
        'vaccine-calendar',
      ],
      layout: 'dashboard',
    },
    {
      id: 'immunization-due',
      route: '/immunizations/due',
      section: 'frontend',
      title: 'Immunizations Due',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'immunization-due',
      components: [
        'overdue-list',
        'upcoming-due',
        'outreach-list',
        'reminder-batch',
        'compliance-report',
      ],
      layout: 'dashboard',
    },
    {
      id: 'patient-immunizations',
      route: '/patients/:id/immunizations',
      section: 'frontend',
      title: 'Patient Immunizations',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'patient-immunizations',
      components: [
        'immunization-card',
        'vaccine-form',
        'immunization-timeline',
        'schedule-comparison',
        'exemption-status',
      ],
      layout: 'dashboard',
    },
    {
      id: 'administer-vaccine',
      route: '/immunizations/administer',
      section: 'frontend',
      title: 'Administer Vaccine',
      authRequired: true,
      roles: ['doctor', 'nurse', 'pharmacist'],
      templateId: 'administer-vaccine',
      components: [
        'vaccine-form',
        'patient-selector',
        'lot-number-entry',
        'administration-site',
        'vis-acknowledgment',
        'adverse-reaction-check',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-immunizations',
      route: '/admin/immunizations',
      section: 'admin',
      title: 'Immunization Administration',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-immunizations',
      components: [
        'vaccine-inventory',
        'schedule-manager',
        'registry-settings',
        'reminder-templates',
        'compliance-reports',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Immunization list components
    'immunization-table',
    'immunization-card',
    'immunization-filters',
    'due-vaccines-list',
    'patient-search',
    'immunization-stats',

    // Schedule components
    'schedule-tracker',
    'recommended-vaccines',
    'age-based-schedule',
    'catch-up-schedule',
    'vaccine-calendar',
    'schedule-comparison',

    // Form components
    'vaccine-form',
    'patient-selector',
    'lot-number-entry',
    'administration-site',
    'vis-acknowledgment',
    'adverse-reaction-check',
    'exemption-form',

    // Timeline components
    'immunization-timeline',
    'dose-tracker',
    'series-progress',
    'next-dose-indicator',

    // Due/reminder components
    'overdue-list',
    'upcoming-due',
    'outreach-list',
    'reminder-batch',
    'reminder-list',
    'reminder-card',

    // Compliance components
    'compliance-report',
    'coverage-stats',
    'exemption-status',
    'school-compliance',

    // Admin components
    'vaccine-inventory',
    'schedule-manager',
    'registry-settings',
    'reminder-templates',
    'compliance-reports',
  ],

  entities: [
    {
      name: 'immunizations',
      displayName: 'Immunizations',
      description: 'Administered immunization records',
      isCore: true,
    },
    {
      name: 'vaccines',
      displayName: 'Vaccines',
      description: 'Vaccine product catalog',
      isCore: true,
    },
    {
      name: 'immunization_schedules',
      displayName: 'Immunization Schedules',
      description: 'Recommended vaccine schedules',
      isCore: true,
    },
    {
      name: 'vaccine_inventory',
      displayName: 'Vaccine Inventory',
      description: 'Vaccine stock tracking',
      isCore: false,
    },
    {
      name: 'immunization_reminders',
      displayName: 'Immunization Reminders',
      description: 'Vaccine reminder records',
      isCore: false,
    },
    {
      name: 'vaccine_exemptions',
      displayName: 'Vaccine Exemptions',
      description: 'Patient exemption records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Immunization routes
    {
      method: 'GET',
      path: '/immunizations',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunizations',
      description: 'List immunizations',
    },
    {
      method: 'POST',
      path: '/immunizations',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunizations',
      description: 'Record immunization',
    },
    {
      method: 'GET',
      path: '/immunizations/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunizations',
      description: 'Get immunization details',
    },
    {
      method: 'PUT',
      path: '/immunizations/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunizations',
      description: 'Update immunization',
    },
    {
      method: 'DELETE',
      path: '/immunizations/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'immunizations',
      description: 'Delete immunization',
    },
    {
      method: 'GET',
      path: '/patients/:id/immunizations',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunizations',
      description: 'Get patient immunizations',
    },
    {
      method: 'POST',
      path: '/patients/:id/immunizations',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunizations',
      description: 'Add patient immunization',
    },
    {
      method: 'GET',
      path: '/patients/:id/immunizations/due',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'immunizations',
      description: 'Get due immunizations',
    },
    {
      method: 'GET',
      path: '/patients/:id/immunizations/forecast',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'immunizations',
      description: 'Get vaccine forecast',
    },

    // Vaccine routes
    {
      method: 'GET',
      path: '/vaccines',
      auth: true,
      handler: 'crud',
      entity: 'vaccines',
      description: 'List vaccines',
    },
    {
      method: 'GET',
      path: '/vaccines/search',
      auth: true,
      handler: 'custom',
      entity: 'vaccines',
      description: 'Search vaccines',
    },
    {
      method: 'GET',
      path: '/vaccines/:id',
      auth: true,
      handler: 'crud',
      entity: 'vaccines',
      description: 'Get vaccine details',
    },
    {
      method: 'POST',
      path: '/vaccines',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vaccines',
      description: 'Add vaccine',
    },
    {
      method: 'PUT',
      path: '/vaccines/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vaccines',
      description: 'Update vaccine',
    },

    // Schedule routes
    {
      method: 'GET',
      path: '/immunization-schedules',
      auth: true,
      handler: 'crud',
      entity: 'immunization_schedules',
      description: 'Get schedules',
    },
    {
      method: 'GET',
      path: '/immunization-schedules/:ageGroup',
      auth: true,
      handler: 'custom',
      entity: 'immunization_schedules',
      description: 'Get age-specific schedule',
    },
    {
      method: 'PUT',
      path: '/immunization-schedules/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'immunization_schedules',
      description: 'Update schedule',
    },

    // Inventory routes
    {
      method: 'GET',
      path: '/vaccine-inventory',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vaccine_inventory',
      description: 'Get vaccine inventory',
    },
    {
      method: 'POST',
      path: '/vaccine-inventory',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vaccine_inventory',
      description: 'Add to inventory',
    },
    {
      method: 'PUT',
      path: '/vaccine-inventory/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vaccine_inventory',
      description: 'Update inventory',
    },
    {
      method: 'POST',
      path: '/vaccine-inventory/:id/decrement',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'vaccine_inventory',
      description: 'Decrement inventory',
    },

    // Reminder routes
    {
      method: 'GET',
      path: '/immunization-reminders',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunization_reminders',
      description: 'List reminders',
    },
    {
      method: 'POST',
      path: '/immunization-reminders',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'immunization_reminders',
      description: 'Create reminder',
    },
    {
      method: 'POST',
      path: '/immunization-reminders/batch',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'immunization_reminders',
      description: 'Batch create reminders',
    },
    {
      method: 'POST',
      path: '/immunization-reminders/:id/send',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'immunization_reminders',
      description: 'Send reminder',
    },

    // Exemption routes
    {
      method: 'GET',
      path: '/patients/:id/exemptions',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vaccine_exemptions',
      description: 'Get exemptions',
    },
    {
      method: 'POST',
      path: '/patients/:id/exemptions',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vaccine_exemptions',
      description: 'Add exemption',
    },
    {
      method: 'DELETE',
      path: '/exemptions/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vaccine_exemptions',
      description: 'Remove exemption',
    },

    // Registry routes
    {
      method: 'POST',
      path: '/immunizations/:id/report-to-registry',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'immunizations',
      description: 'Report to IIS registry',
    },
    {
      method: 'GET',
      path: '/patients/:id/registry-history',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'immunizations',
      description: 'Get registry history',
    },

    // Analytics routes
    {
      method: 'GET',
      path: '/immunizations/analytics',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'immunizations',
      description: 'Get immunization analytics',
    },
    {
      method: 'GET',
      path: '/immunizations/coverage-report',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'immunizations',
      description: 'Get coverage report',
    },
  ],

  config: [
    {
      key: 'registryIntegration',
      label: 'IIS Registry Integration',
      type: 'boolean',
      default: true,
      description: 'Enable state immunization registry integration',
    },
    {
      key: 'scheduleStandard',
      label: 'Schedule Standard',
      type: 'select',
      default: 'cdc',
      options: [
        { value: 'cdc', label: 'CDC Recommended' },
        { value: 'aap', label: 'AAP Recommended' },
        { value: 'custom', label: 'Custom Schedule' },
      ],
      description: 'Immunization schedule to follow',
    },
    {
      key: 'reminderEnabled',
      label: 'Automatic Reminders',
      type: 'boolean',
      default: true,
      description: 'Enable automatic vaccine reminders',
    },
    {
      key: 'reminderDaysBefore',
      label: 'Reminder Days Before',
      type: 'number',
      default: 14,
      description: 'Days before due date to send reminder',
    },
    {
      key: 'trackLotNumbers',
      label: 'Track Lot Numbers',
      type: 'boolean',
      default: true,
      description: 'Require lot number tracking',
    },
    {
      key: 'requireVIS',
      label: 'Require VIS Acknowledgment',
      type: 'boolean',
      default: true,
      description: 'Require Vaccine Information Statement acknowledgment',
    },
    {
      key: 'inventoryTracking',
      label: 'Inventory Tracking',
      type: 'boolean',
      default: true,
      description: 'Enable vaccine inventory tracking',
    },
    {
      key: 'lowStockAlert',
      label: 'Low Stock Alert Threshold',
      type: 'number',
      default: 10,
      description: 'Alert when stock falls below this number',
    },
  ],
};
