/**
 * Insurance & Billing Feature Definition
 *
 * Medical insurance verification, claims management, and billing
 * for healthcare applications. Includes payment tracking and coding.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const INSURANCE_BILLING_FEATURE: FeatureDefinition = {
  id: 'insurance-billing',
  name: 'Insurance & Billing',
  category: 'healthcare',
  description: 'Manage insurance claims, billing, coverage verification, and payments',
  icon: 'file-invoice-dollar',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'dental-clinic',
    'hospital',
    'urgent-care',
    'physical-therapy',
    'chiropractic',
    'mental-health',
    'optometry',
    'dermatology',
    'radiology',
    'laboratory',
    'ambulatory-surgery',
    'home-health',
    'durable-medical-equipment',
    'medical-billing',
    'revenue-cycle',
  ],

  activationKeywords: [
    'insurance',
    'medical billing',
    'claims',
    'claim submission',
    'insurance claims',
    'billing',
    'healthcare billing',
    'coverage',
    'insurance verification',
    'eligibility',
    'cpt codes',
    'icd codes',
    'medical coding',
    'revenue cycle',
    'rcm',
    'era',
    'edi',
    'clearinghouse',
    'superbill',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'patient-records'],
  conflicts: [],

  pages: [
    {
      id: 'claims-list',
      route: '/claims',
      section: 'frontend',
      title: 'Insurance Claims',
      authRequired: true,
      roles: ['admin', 'billing', 'manager'],
      templateId: 'claims-list',
      components: [
        'claims-table',
        'claims-filters',
        'claims-status-summary',
        'claim-search',
        'batch-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'claim-detail',
      route: '/claims/:id',
      section: 'frontend',
      title: 'Claim Details',
      authRequired: true,
      roles: ['admin', 'billing', 'manager'],
      templateId: 'claim-detail',
      components: [
        'claim-header',
        'claim-info',
        'service-lines',
        'claim-history',
        'remittance-info',
        'claim-notes',
        'claim-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'billing-dashboard',
      route: '/billing',
      section: 'frontend',
      title: 'Billing Dashboard',
      authRequired: true,
      roles: ['admin', 'billing', 'manager'],
      templateId: 'billing-dashboard',
      components: [
        'revenue-summary',
        'ar-aging',
        'claims-pipeline',
        'denial-stats',
        'payment-tracker',
        'billing-alerts',
      ],
      layout: 'dashboard',
    },
    {
      id: 'insurance-verification',
      route: '/insurance/verify',
      section: 'frontend',
      title: 'Insurance Verification',
      authRequired: true,
      roles: ['admin', 'billing', 'receptionist'],
      templateId: 'insurance-verification',
      components: [
        'verification-form',
        'coverage-checker',
        'eligibility-results',
        'benefits-summary',
        'authorization-status',
      ],
      layout: 'dashboard',
    },
    {
      id: 'new-claim',
      route: '/claims/new',
      section: 'frontend',
      title: 'Create Claim',
      authRequired: true,
      roles: ['admin', 'billing'],
      templateId: 'new-claim',
      components: [
        'claim-form',
        'patient-selector',
        'insurance-card',
        'diagnosis-coder',
        'procedure-coder',
        'service-line-builder',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-billing',
      route: '/admin/billing',
      section: 'admin',
      title: 'Billing Administration',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-billing',
      components: [
        'billing-analytics',
        'fee-schedule-manager',
        'payer-management',
        'code-library',
        'billing-rules',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Claims list components
    'claims-table',
    'claim-card',
    'claims-filters',
    'claims-status-summary',
    'claim-search',
    'batch-actions',
    'claim-status-badge',

    // Claim detail components
    'claim-header',
    'claim-info',
    'service-lines',
    'claim-history',
    'remittance-info',
    'claim-notes',
    'claim-actions',
    'claim-attachments',

    // Form components
    'claim-form',
    'patient-selector',
    'insurance-card',
    'diagnosis-coder',
    'procedure-coder',
    'service-line-builder',
    'modifier-selector',

    // Insurance components
    'verification-form',
    'coverage-checker',
    'eligibility-results',
    'benefits-summary',
    'authorization-status',
    'insurance-info-display',

    // Dashboard components
    'revenue-summary',
    'ar-aging',
    'claims-pipeline',
    'denial-stats',
    'payment-tracker',
    'billing-alerts',

    // Payment components
    'payment-form',
    'payment-history',
    'statement-generator',
    'balance-display',
    'payment-plan-builder',

    // Admin components
    'billing-analytics',
    'fee-schedule-manager',
    'payer-management',
    'code-library',
    'billing-rules',
  ],

  entities: [
    {
      name: 'insurance_claims',
      displayName: 'Insurance Claims',
      description: 'Insurance claim submissions',
      isCore: true,
    },
    {
      name: 'insurance_providers',
      displayName: 'Insurance Providers',
      description: 'Insurance payer information',
      isCore: true,
    },
    {
      name: 'coverage',
      displayName: 'Coverage',
      description: 'Patient insurance coverage',
      isCore: true,
    },
    {
      name: 'billing_codes',
      displayName: 'Billing Codes',
      description: 'CPT, ICD, and other codes',
      isCore: true,
    },
    {
      name: 'claim_service_lines',
      displayName: 'Service Lines',
      description: 'Individual claim line items',
      isCore: false,
    },
    {
      name: 'remittances',
      displayName: 'Remittances',
      description: 'Payment remittance records',
      isCore: false,
    },
    {
      name: 'fee_schedules',
      displayName: 'Fee Schedules',
      description: 'Payer fee schedules',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Claims routes
    {
      method: 'GET',
      path: '/claims',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'insurance_claims',
      description: 'List insurance claims',
    },
    {
      method: 'POST',
      path: '/claims',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'insurance_claims',
      description: 'Create claim',
    },
    {
      method: 'GET',
      path: '/claims/:id',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'insurance_claims',
      description: 'Get claim details',
    },
    {
      method: 'PUT',
      path: '/claims/:id',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'insurance_claims',
      description: 'Update claim',
    },
    {
      method: 'DELETE',
      path: '/claims/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'insurance_claims',
      description: 'Delete claim',
    },
    {
      method: 'POST',
      path: '/claims/:id/submit',
      auth: true,
      role: 'billing',
      handler: 'custom',
      entity: 'insurance_claims',
      description: 'Submit claim to payer',
    },
    {
      method: 'POST',
      path: '/claims/:id/void',
      auth: true,
      role: 'billing',
      handler: 'custom',
      entity: 'insurance_claims',
      description: 'Void claim',
    },
    {
      method: 'POST',
      path: '/claims/:id/resubmit',
      auth: true,
      role: 'billing',
      handler: 'custom',
      entity: 'insurance_claims',
      description: 'Resubmit claim',
    },
    {
      method: 'GET',
      path: '/claims/:id/history',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'insurance_claims',
      description: 'Get claim history',
    },

    // Insurance provider routes
    {
      method: 'GET',
      path: '/insurance-providers',
      auth: true,
      handler: 'crud',
      entity: 'insurance_providers',
      description: 'List insurance providers',
    },
    {
      method: 'POST',
      path: '/insurance-providers',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'insurance_providers',
      description: 'Add insurance provider',
    },
    {
      method: 'GET',
      path: '/insurance-providers/:id',
      auth: true,
      handler: 'crud',
      entity: 'insurance_providers',
      description: 'Get provider details',
    },
    {
      method: 'PUT',
      path: '/insurance-providers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'insurance_providers',
      description: 'Update provider',
    },

    // Coverage routes
    {
      method: 'GET',
      path: '/patients/:id/coverage',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'coverage',
      description: 'Get patient coverage',
    },
    {
      method: 'POST',
      path: '/patients/:id/coverage',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'coverage',
      description: 'Add patient coverage',
    },
    {
      method: 'POST',
      path: '/coverage/verify',
      auth: true,
      role: 'staff',
      handler: 'custom',
      entity: 'coverage',
      description: 'Verify coverage eligibility',
    },
    {
      method: 'GET',
      path: '/coverage/:id/benefits',
      auth: true,
      role: 'staff',
      handler: 'custom',
      entity: 'coverage',
      description: 'Get benefits summary',
    },

    // Billing codes routes
    {
      method: 'GET',
      path: '/billing-codes',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'billing_codes',
      description: 'List billing codes',
    },
    {
      method: 'GET',
      path: '/billing-codes/search',
      auth: true,
      role: 'billing',
      handler: 'custom',
      entity: 'billing_codes',
      description: 'Search billing codes',
    },
    {
      method: 'GET',
      path: '/billing-codes/cpt/:code',
      auth: true,
      role: 'billing',
      handler: 'custom',
      entity: 'billing_codes',
      description: 'Get CPT code details',
    },
    {
      method: 'GET',
      path: '/billing-codes/icd/:code',
      auth: true,
      role: 'billing',
      handler: 'custom',
      entity: 'billing_codes',
      description: 'Get ICD code details',
    },

    // Fee schedule routes
    {
      method: 'GET',
      path: '/fee-schedules',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'fee_schedules',
      description: 'List fee schedules',
    },
    {
      method: 'POST',
      path: '/fee-schedules',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'fee_schedules',
      description: 'Create fee schedule',
    },
    {
      method: 'GET',
      path: '/fee-schedules/:payerId',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'fee_schedules',
      description: 'Get payer fee schedule',
    },

    // Payment routes
    {
      method: 'POST',
      path: '/claims/:id/payment',
      auth: true,
      role: 'billing',
      handler: 'custom',
      entity: 'remittances',
      description: 'Post payment to claim',
    },
    {
      method: 'GET',
      path: '/remittances',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'remittances',
      description: 'List remittances',
    },

    // Analytics routes
    {
      method: 'GET',
      path: '/billing/analytics',
      auth: true,
      role: 'billing',
      handler: 'aggregate',
      entity: 'insurance_claims',
      description: 'Get billing analytics',
    },
    {
      method: 'GET',
      path: '/billing/ar-aging',
      auth: true,
      role: 'billing',
      handler: 'aggregate',
      entity: 'insurance_claims',
      description: 'Get AR aging report',
    },
  ],

  config: [
    {
      key: 'clearinghouseEnabled',
      label: 'Clearinghouse Integration',
      type: 'boolean',
      default: true,
      description: 'Enable clearinghouse for claim submission',
    },
    {
      key: 'eligibilityCheckEnabled',
      label: 'Real-time Eligibility',
      type: 'boolean',
      default: true,
      description: 'Enable real-time eligibility checking',
    },
    {
      key: 'defaultClaimType',
      label: 'Default Claim Type',
      type: 'select',
      default: 'professional',
      options: [
        { value: 'professional', label: 'Professional (CMS-1500)' },
        { value: 'institutional', label: 'Institutional (UB-04)' },
        { value: 'dental', label: 'Dental' },
      ],
      description: 'Default claim form type',
    },
    {
      key: 'autoPostPayments',
      label: 'Auto-Post ERA Payments',
      type: 'boolean',
      default: false,
      description: 'Automatically post ERA payments',
    },
    {
      key: 'arAgingBuckets',
      label: 'AR Aging Buckets (days)',
      type: 'string',
      default: '30,60,90,120',
      description: 'Days for AR aging buckets',
    },
    {
      key: 'requireAuthForClaims',
      label: 'Require Authorization Check',
      type: 'boolean',
      default: true,
      description: 'Require prior auth check before claim submission',
    },
  ],
};
