/**
 * Medical Imaging Feature Definition
 *
 * Radiology and medical imaging management for healthcare applications.
 * Includes DICOM viewing, image ordering, and radiology reports.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const MEDICAL_IMAGING_FEATURE: FeatureDefinition = {
  id: 'medical-imaging',
  name: 'Medical Imaging',
  category: 'healthcare',
  description: 'Manage radiology orders, medical images, and diagnostic imaging reports',
  icon: 'x-ray',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'hospital',
    'radiology',
    'imaging-center',
    'orthopedics',
    'oncology',
    'cardiology',
    'neurology',
    'pulmonology',
    'gastroenterology',
    'emergency-room',
    'urgent-care',
    'veterinary',
    'dental-clinic',
    'chiropractic',
  ],

  activationKeywords: [
    'medical imaging',
    'radiology',
    'x-ray',
    'xray',
    'mri',
    'ct scan',
    'ultrasound',
    'dicom',
    'pacs',
    'imaging orders',
    'radiograph',
    'mammogram',
    'pet scan',
    'fluoroscopy',
    'nuclear medicine',
    'imaging reports',
    'radiology report',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'patient-records'],
  conflicts: [],

  pages: [
    {
      id: 'imaging-orders',
      route: '/imaging',
      section: 'frontend',
      title: 'Imaging Orders',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'radiologist', 'radiology-tech'],
      templateId: 'imaging-orders',
      components: [
        'imaging-order-table',
        'order-status-filter',
        'pending-reads',
        'stat-orders',
        'order-search',
      ],
      layout: 'dashboard',
    },
    {
      id: 'image-viewer',
      route: '/imaging/:id/view',
      section: 'frontend',
      title: 'Image Viewer',
      authRequired: true,
      roles: ['admin', 'doctor', 'radiologist'],
      templateId: 'image-viewer',
      components: [
        'dicom-viewer',
        'image-toolbar',
        'measurement-tools',
        'annotation-panel',
        'series-navigator',
        'comparison-view',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'radiology-reports',
      route: '/imaging/:id/report',
      section: 'frontend',
      title: 'Radiology Report',
      authRequired: true,
      roles: ['admin', 'doctor', 'radiologist'],
      templateId: 'radiology-reports',
      components: [
        'report-header',
        'report-form',
        'findings-section',
        'impression-section',
        'image-thumbnails',
        'report-templates',
        'voice-dictation',
      ],
      layout: 'dashboard',
    },
    {
      id: 'new-imaging-order',
      route: '/imaging/new',
      section: 'frontend',
      title: 'New Imaging Order',
      authRequired: true,
      roles: ['doctor'],
      templateId: 'new-imaging-order',
      components: [
        'imaging-order-form',
        'patient-selector',
        'modality-selector',
        'exam-selector',
        'clinical-indication',
        'contrast-selection',
        'scheduling-options',
      ],
      layout: 'dashboard',
    },
    {
      id: 'radiologist-worklist',
      route: '/radiology/worklist',
      section: 'frontend',
      title: 'Radiologist Worklist',
      authRequired: true,
      roles: ['radiologist'],
      templateId: 'radiologist-worklist',
      components: [
        'worklist-table',
        'priority-filter',
        'modality-filter',
        'pending-queue',
        'study-preview',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-imaging',
      route: '/admin/imaging',
      section: 'admin',
      title: 'Imaging Administration',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-imaging',
      components: [
        'imaging-analytics',
        'modality-management',
        'exam-catalog',
        'pacs-settings',
        'report-templates-manager',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Order list components
    'imaging-order-table',
    'imaging-order-card',
    'order-status-filter',
    'pending-reads',
    'stat-orders',
    'order-search',
    'order-status-badge',

    // Order form components
    'imaging-order-form',
    'patient-selector',
    'modality-selector',
    'exam-selector',
    'clinical-indication',
    'contrast-selection',
    'scheduling-options',
    'prior-auth-check',

    // DICOM viewer components
    'dicom-viewer',
    'image-toolbar',
    'measurement-tools',
    'annotation-panel',
    'series-navigator',
    'comparison-view',
    'window-level-control',
    'zoom-pan-control',
    'cine-player',

    // Report components
    'report-header',
    'report-form',
    'findings-section',
    'impression-section',
    'image-thumbnails',
    'report-templates',
    'voice-dictation',
    'structured-report',

    // Worklist components
    'worklist-table',
    'priority-filter',
    'modality-filter',
    'pending-queue',
    'study-preview',
    'read-status-indicator',

    // Upload components
    'image-upload',
    'dicom-upload',
    'cd-import',
    'external-study-import',

    // Admin components
    'imaging-analytics',
    'modality-management',
    'exam-catalog',
    'pacs-settings',
    'report-templates-manager',
  ],

  entities: [
    {
      name: 'imaging_orders',
      displayName: 'Imaging Orders',
      description: 'Radiology/imaging orders',
      isCore: true,
    },
    {
      name: 'medical_images',
      displayName: 'Medical Images',
      description: 'DICOM images and studies',
      isCore: true,
    },
    {
      name: 'radiology_reports',
      displayName: 'Radiology Reports',
      description: 'Imaging interpretation reports',
      isCore: true,
    },
    {
      name: 'imaging_modalities',
      displayName: 'Imaging Modalities',
      description: 'Types of imaging equipment',
      isCore: false,
    },
    {
      name: 'exam_types',
      displayName: 'Exam Types',
      description: 'Types of imaging exams',
      isCore: false,
    },
    {
      name: 'image_annotations',
      displayName: 'Image Annotations',
      description: 'Annotations on images',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Imaging order routes
    {
      method: 'GET',
      path: '/imaging-orders',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'imaging_orders',
      description: 'List imaging orders',
    },
    {
      method: 'POST',
      path: '/imaging-orders',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'imaging_orders',
      description: 'Create imaging order',
    },
    {
      method: 'GET',
      path: '/imaging-orders/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'imaging_orders',
      description: 'Get imaging order details',
    },
    {
      method: 'PUT',
      path: '/imaging-orders/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'imaging_orders',
      description: 'Update imaging order',
    },
    {
      method: 'DELETE',
      path: '/imaging-orders/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'imaging_orders',
      description: 'Cancel imaging order',
    },
    {
      method: 'POST',
      path: '/imaging-orders/:id/schedule',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'imaging_orders',
      description: 'Schedule imaging exam',
    },
    {
      method: 'POST',
      path: '/imaging-orders/:id/complete',
      auth: true,
      role: 'radiology-tech',
      handler: 'custom',
      entity: 'imaging_orders',
      description: 'Mark exam complete',
    },
    {
      method: 'GET',
      path: '/patients/:id/imaging-orders',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'imaging_orders',
      description: 'Get patient imaging orders',
    },

    // Medical images routes
    {
      method: 'GET',
      path: '/medical-images',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_images',
      description: 'List medical images',
    },
    {
      method: 'GET',
      path: '/medical-images/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_images',
      description: 'Get image details',
    },
    {
      method: 'POST',
      path: '/medical-images',
      auth: true,
      role: 'radiology-tech',
      handler: 'crud',
      entity: 'medical_images',
      description: 'Upload images',
    },
    {
      method: 'GET',
      path: '/medical-images/:id/dicom',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'medical_images',
      description: 'Get DICOM data',
    },
    {
      method: 'GET',
      path: '/medical-images/:id/thumbnail',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'medical_images',
      description: 'Get image thumbnail',
    },
    {
      method: 'GET',
      path: '/imaging-orders/:id/images',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_images',
      description: 'Get order images',
    },
    {
      method: 'GET',
      path: '/patients/:id/images',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_images',
      description: 'Get patient images',
    },

    // Radiology reports routes
    {
      method: 'GET',
      path: '/radiology-reports',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'radiology_reports',
      description: 'List radiology reports',
    },
    {
      method: 'POST',
      path: '/radiology-reports',
      auth: true,
      role: 'radiologist',
      handler: 'crud',
      entity: 'radiology_reports',
      description: 'Create report',
    },
    {
      method: 'GET',
      path: '/radiology-reports/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'radiology_reports',
      description: 'Get report details',
    },
    {
      method: 'PUT',
      path: '/radiology-reports/:id',
      auth: true,
      role: 'radiologist',
      handler: 'crud',
      entity: 'radiology_reports',
      description: 'Update report',
    },
    {
      method: 'POST',
      path: '/radiology-reports/:id/finalize',
      auth: true,
      role: 'radiologist',
      handler: 'custom',
      entity: 'radiology_reports',
      description: 'Finalize report',
    },
    {
      method: 'POST',
      path: '/radiology-reports/:id/addendum',
      auth: true,
      role: 'radiologist',
      handler: 'custom',
      entity: 'radiology_reports',
      description: 'Add addendum',
    },
    {
      method: 'GET',
      path: '/imaging-orders/:id/report',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'radiology_reports',
      description: 'Get order report',
    },

    // Modality routes
    {
      method: 'GET',
      path: '/modalities',
      auth: true,
      handler: 'crud',
      entity: 'imaging_modalities',
      description: 'List modalities',
    },
    {
      method: 'POST',
      path: '/modalities',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'imaging_modalities',
      description: 'Add modality',
    },

    // Exam types routes
    {
      method: 'GET',
      path: '/exam-types',
      auth: true,
      handler: 'crud',
      entity: 'exam_types',
      description: 'List exam types',
    },
    {
      method: 'GET',
      path: '/exam-types/by-modality/:modality',
      auth: true,
      handler: 'custom',
      entity: 'exam_types',
      description: 'Get exams by modality',
    },
    {
      method: 'POST',
      path: '/exam-types',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'exam_types',
      description: 'Add exam type',
    },

    // Annotation routes
    {
      method: 'GET',
      path: '/medical-images/:id/annotations',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'image_annotations',
      description: 'Get image annotations',
    },
    {
      method: 'POST',
      path: '/medical-images/:id/annotations',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'image_annotations',
      description: 'Add annotation',
    },
    {
      method: 'DELETE',
      path: '/annotations/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'image_annotations',
      description: 'Remove annotation',
    },

    // Worklist routes
    {
      method: 'GET',
      path: '/radiology/worklist',
      auth: true,
      role: 'radiologist',
      handler: 'custom',
      entity: 'imaging_orders',
      description: 'Get radiologist worklist',
    },
    {
      method: 'POST',
      path: '/radiology/worklist/:id/assign',
      auth: true,
      role: 'radiologist',
      handler: 'custom',
      entity: 'imaging_orders',
      description: 'Assign study to self',
    },

    // Analytics routes
    {
      method: 'GET',
      path: '/imaging/analytics',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'imaging_orders',
      description: 'Get imaging analytics',
    },
    {
      method: 'GET',
      path: '/imaging/turnaround-times',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'radiology_reports',
      description: 'Get report turnaround times',
    },
  ],

  config: [
    {
      key: 'pacsIntegration',
      label: 'PACS Integration',
      type: 'boolean',
      default: true,
      description: 'Enable PACS integration',
    },
    {
      key: 'dicomViewerType',
      label: 'DICOM Viewer',
      type: 'select',
      default: 'cornerstone',
      options: [
        { value: 'cornerstone', label: 'Cornerstone.js' },
        { value: 'ohif', label: 'OHIF Viewer' },
        { value: 'dwv', label: 'DWV' },
        { value: 'external', label: 'External Viewer' },
      ],
      description: 'DICOM viewer implementation',
    },
    {
      key: 'voiceDictation',
      label: 'Voice Dictation',
      type: 'boolean',
      default: true,
      description: 'Enable voice dictation for reports',
    },
    {
      key: 'autoAssignStudies',
      label: 'Auto-Assign Studies',
      type: 'boolean',
      default: false,
      description: 'Automatically assign studies to radiologists',
    },
    {
      key: 'criticalFindingsAlert',
      label: 'Critical Findings Alert',
      type: 'boolean',
      default: true,
      description: 'Alert on critical findings',
    },
    {
      key: 'priorStudyComparison',
      label: 'Prior Study Comparison',
      type: 'boolean',
      default: true,
      description: 'Enable prior study comparison view',
    },
    {
      key: 'compressImages',
      label: 'Compress Images',
      type: 'boolean',
      default: false,
      description: 'Compress DICOM images for storage',
    },
    {
      key: 'retentionYears',
      label: 'Image Retention (years)',
      type: 'number',
      default: 7,
      description: 'Years to retain medical images',
    },
  ],
};
