/**
 * Patient Records Feature Definition
 *
 * Comprehensive patient health records management including
 * medical history, allergies, medications, and clinical documentation.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PATIENT_RECORDS_FEATURE: FeatureDefinition = {
  id: 'patient-records',
  name: 'Patient Records',
  category: 'healthcare',
  description: 'Manage patient health records, medical history, allergies, and medications',
  icon: 'file-medical',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'dental-clinic',
    'hospital',
    'urgent-care',
    'telemedicine',
    'physical-therapy',
    'chiropractic',
    'optometry',
    'dermatology',
    'pediatrics',
    'cardiology',
    'orthopedics',
    'mental-health',
    'psychiatry',
    'neurology',
    'oncology',
    'radiology',
    'pathology',
    'ehr-system',
    'clinic-management',
  ],

  activationKeywords: [
    'patient records',
    'medical records',
    'health records',
    'ehr',
    'electronic health records',
    'emr',
    'electronic medical records',
    'patient chart',
    'medical history',
    'patient profile',
    'clinical records',
    'patient data',
    'health information',
    'patient management',
    'patient demographics',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'patient-list',
      route: '/patients',
      section: 'frontend',
      title: 'Patients',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'receptionist'],
      templateId: 'patient-list',
      components: [
        'patient-search',
        'patient-table',
        'patient-card',
        'patient-filters',
        'quick-add-patient',
      ],
      layout: 'dashboard',
    },
    {
      id: 'patient-detail',
      route: '/patients/:id',
      section: 'frontend',
      title: 'Patient Details',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'patient-detail',
      components: [
        'patient-header',
        'patient-demographics',
        'patient-tabs',
        'medical-history-summary',
        'allergy-list',
        'medication-list',
        'recent-visits',
      ],
      layout: 'dashboard',
    },
    {
      id: 'patient-chart',
      route: '/patients/:id/chart',
      section: 'frontend',
      title: 'Patient Chart',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'patient-chart',
      components: [
        'chart-header',
        'problem-list',
        'medical-timeline',
        'vitals-summary',
        'notes-section',
        'orders-section',
        'results-section',
      ],
      layout: 'dashboard',
    },
    {
      id: 'medical-history',
      route: '/patients/:id/history',
      section: 'frontend',
      title: 'Medical History',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'medical-history',
      components: [
        'history-timeline',
        'surgical-history',
        'family-history',
        'social-history',
        'past-medical-history',
        'hospitalization-list',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-patients',
      route: '/admin/patients',
      section: 'admin',
      title: 'Patient Management',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-patients',
      components: [
        'admin-patient-table',
        'patient-stats',
        'bulk-patient-actions',
        'patient-export',
        'patient-import',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Patient list components
    'patient-search',
    'patient-table',
    'patient-card',
    'patient-filters',
    'quick-add-patient',
    'patient-avatar',

    // Patient detail components
    'patient-header',
    'patient-demographics',
    'patient-tabs',
    'patient-form',
    'patient-insurance-info',
    'emergency-contacts',

    // Medical history components
    'medical-timeline',
    'medical-history-summary',
    'surgical-history',
    'family-history',
    'social-history',
    'past-medical-history',
    'hospitalization-list',
    'history-timeline',

    // Allergy components
    'allergy-list',
    'allergy-card',
    'allergy-form',
    'allergy-severity-badge',
    'allergy-alert',

    // Medication components
    'medication-list',
    'medication-card',
    'medication-form',
    'medication-history',
    'current-medications',
    'discontinued-medications',

    // Chart components
    'chart-header',
    'problem-list',
    'notes-section',
    'orders-section',
    'results-section',
    'vitals-summary',
    'recent-visits',

    // Admin components
    'admin-patient-table',
    'patient-stats',
    'bulk-patient-actions',
    'patient-export',
    'patient-import',
  ],

  entities: [
    {
      name: 'patients',
      displayName: 'Patients',
      description: 'Patient demographic and contact information',
      isCore: true,
    },
    {
      name: 'medical_records',
      displayName: 'Medical Records',
      description: 'Patient medical record entries',
      isCore: true,
    },
    {
      name: 'allergies',
      displayName: 'Allergies',
      description: 'Patient allergy information',
      isCore: true,
    },
    {
      name: 'medications',
      displayName: 'Medications',
      description: 'Patient medication records',
      isCore: true,
    },
    {
      name: 'medical_history',
      displayName: 'Medical History',
      description: 'Patient past medical history',
      isCore: false,
    },
    {
      name: 'emergency_contacts',
      displayName: 'Emergency Contacts',
      description: 'Patient emergency contact information',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Patient routes
    {
      method: 'GET',
      path: '/patients',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'patients',
      description: 'List all patients',
    },
    {
      method: 'POST',
      path: '/patients',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'patients',
      description: 'Create new patient',
    },
    {
      method: 'GET',
      path: '/patients/:id',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'patients',
      description: 'Get patient details',
    },
    {
      method: 'PUT',
      path: '/patients/:id',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'patients',
      description: 'Update patient',
    },
    {
      method: 'DELETE',
      path: '/patients/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'patients',
      description: 'Delete patient',
    },
    {
      method: 'GET',
      path: '/patients/:id/chart',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'medical_records',
      description: 'Get patient chart',
    },
    {
      method: 'GET',
      path: '/patients/search',
      auth: true,
      role: 'staff',
      handler: 'custom',
      entity: 'patients',
      description: 'Search patients',
    },

    // Medical records routes
    {
      method: 'GET',
      path: '/patients/:id/records',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_records',
      description: 'Get patient medical records',
    },
    {
      method: 'POST',
      path: '/patients/:id/records',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_records',
      description: 'Create medical record entry',
    },
    {
      method: 'PUT',
      path: '/medical-records/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_records',
      description: 'Update medical record',
    },

    // Allergy routes
    {
      method: 'GET',
      path: '/patients/:id/allergies',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'allergies',
      description: 'Get patient allergies',
    },
    {
      method: 'POST',
      path: '/patients/:id/allergies',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'allergies',
      description: 'Add patient allergy',
    },
    {
      method: 'PUT',
      path: '/allergies/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'allergies',
      description: 'Update allergy',
    },
    {
      method: 'DELETE',
      path: '/allergies/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'allergies',
      description: 'Remove allergy',
    },

    // Medication routes
    {
      method: 'GET',
      path: '/patients/:id/medications',
      auth: true,
      role: 'staff',
      handler: 'crud',
      entity: 'medications',
      description: 'Get patient medications',
    },
    {
      method: 'POST',
      path: '/patients/:id/medications',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medications',
      description: 'Add medication',
    },
    {
      method: 'PUT',
      path: '/medications/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medications',
      description: 'Update medication',
    },
    {
      method: 'POST',
      path: '/medications/:id/discontinue',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'medications',
      description: 'Discontinue medication',
    },

    // Medical history routes
    {
      method: 'GET',
      path: '/patients/:id/history',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_history',
      description: 'Get medical history',
    },
    {
      method: 'POST',
      path: '/patients/:id/history',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_history',
      description: 'Add history entry',
    },
    {
      method: 'PUT',
      path: '/medical-history/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medical_history',
      description: 'Update history entry',
    },
  ],

  config: [
    {
      key: 'requireMRN',
      label: 'Require Medical Record Number',
      type: 'boolean',
      default: true,
      description: 'Require MRN for all patients',
    },
    {
      key: 'mrnFormat',
      label: 'MRN Format',
      type: 'string',
      default: 'MRN-######',
      description: 'Format for auto-generated MRNs',
    },
    {
      key: 'allergyAlertLevel',
      label: 'Allergy Alert Level',
      type: 'select',
      default: 'all',
      options: [
        { value: 'all', label: 'Show all allergies' },
        { value: 'severe', label: 'Severe allergies only' },
        { value: 'moderate', label: 'Moderate and severe' },
      ],
      description: 'Which allergy severities trigger alerts',
    },
    {
      key: 'retentionYears',
      label: 'Record Retention (years)',
      type: 'number',
      default: 7,
      description: 'Years to retain medical records',
    },
    {
      key: 'hipaaCompliance',
      label: 'HIPAA Compliance Mode',
      type: 'boolean',
      default: true,
      description: 'Enable HIPAA compliance features',
    },
  ],
};
