/**
 * Prescriptions Feature Definition
 *
 * Prescription management and e-prescribing for healthcare applications.
 * Includes medication ordering, dosage management, and pharmacy integration.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PRESCRIPTIONS_FEATURE: FeatureDefinition = {
  id: 'prescriptions',
  name: 'Prescriptions',
  category: 'healthcare',
  description: 'Manage prescriptions, e-prescribing, and pharmacy integration',
  icon: 'prescription',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'hospital',
    'urgent-care',
    'telemedicine',
    'psychiatry',
    'pain-management',
    'oncology',
    'cardiology',
    'dermatology',
    'pediatrics',
    'geriatrics',
    'internal-medicine',
    'family-practice',
    'pharmacy',
    'ehr-system',
  ],

  activationKeywords: [
    'prescriptions',
    'prescription',
    'e-prescribing',
    'eprescribe',
    'rx',
    'medication orders',
    'pharmacy',
    'drug orders',
    'refills',
    'prescription refill',
    'medication management',
    'controlled substances',
    'surescripts',
    'prescription pad',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'patient-records'],
  conflicts: [],

  pages: [
    {
      id: 'prescriptions-list',
      route: '/prescriptions',
      section: 'frontend',
      title: 'Prescriptions',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'pharmacist'],
      templateId: 'prescriptions-list',
      components: [
        'prescription-table',
        'prescription-filters',
        'pending-refills',
        'prescription-search',
      ],
      layout: 'dashboard',
    },
    {
      id: 'prescription-detail',
      route: '/prescriptions/:id',
      section: 'frontend',
      title: 'Prescription Details',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'pharmacist'],
      templateId: 'prescription-detail',
      components: [
        'prescription-header',
        'prescription-info',
        'dosage-instructions',
        'refill-history',
        'pharmacy-info',
        'prescription-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'pharmacy-portal',
      route: '/pharmacy',
      section: 'frontend',
      title: 'Pharmacy Portal',
      authRequired: true,
      roles: ['admin', 'pharmacist'],
      templateId: 'pharmacy-portal',
      components: [
        'incoming-prescriptions',
        'fill-queue',
        'verification-panel',
        'drug-inventory',
        'patient-pickup',
      ],
      layout: 'dashboard',
    },
    {
      id: 'new-prescription',
      route: '/prescriptions/new',
      section: 'frontend',
      title: 'New Prescription',
      authRequired: true,
      roles: ['doctor'],
      templateId: 'new-prescription',
      components: [
        'prescription-form',
        'medication-search',
        'dosage-calculator',
        'drug-interactions-checker',
        'pharmacy-selector',
        'sig-builder',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-prescriptions',
      route: '/admin/prescriptions',
      section: 'admin',
      title: 'Prescription Management',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-prescriptions',
      components: [
        'admin-prescription-table',
        'controlled-substance-log',
        'prescription-analytics',
        'pharmacy-management',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Prescription list components
    'prescription-table',
    'prescription-card',
    'prescription-filters',
    'prescription-search',
    'pending-refills',
    'prescription-status-badge',

    // Detail components
    'prescription-header',
    'prescription-info',
    'dosage-instructions',
    'refill-history',
    'pharmacy-info',
    'prescription-actions',

    // Form components
    'prescription-form',
    'medication-search',
    'dosage-calculator',
    'drug-interactions-checker',
    'pharmacy-selector',
    'sig-builder',
    'quantity-dispense',

    // Refill components
    'refill-tracker',
    'refill-request-form',
    'refill-approval',
    'refill-history-list',

    // Pharmacy components
    'incoming-prescriptions',
    'fill-queue',
    'verification-panel',
    'drug-inventory',
    'patient-pickup',
    'pharmacy-card',

    // Safety components
    'drug-interactions-alert',
    'allergy-check-alert',
    'duplicate-therapy-alert',
    'controlled-substance-warning',

    // Admin components
    'admin-prescription-table',
    'controlled-substance-log',
    'prescription-analytics',
    'pharmacy-management',
  ],

  entities: [
    {
      name: 'prescriptions',
      displayName: 'Prescriptions',
      description: 'Prescription orders',
      isCore: true,
    },
    {
      name: 'medications',
      displayName: 'Medications',
      description: 'Medication catalog',
      isCore: true,
    },
    {
      name: 'pharmacies',
      displayName: 'Pharmacies',
      description: 'Pharmacy information',
      isCore: true,
    },
    {
      name: 'refills',
      displayName: 'Refills',
      description: 'Prescription refill requests',
      isCore: true,
    },
    {
      name: 'drug_interactions',
      displayName: 'Drug Interactions',
      description: 'Drug interaction database',
      isCore: false,
    },
    {
      name: 'prescription_history',
      displayName: 'Prescription History',
      description: 'Historical prescription records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Prescription routes
    {
      method: 'GET',
      path: '/prescriptions',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'prescriptions',
      description: 'List prescriptions',
    },
    {
      method: 'POST',
      path: '/prescriptions',
      auth: true,
      role: 'doctor',
      handler: 'crud',
      entity: 'prescriptions',
      description: 'Create prescription',
    },
    {
      method: 'GET',
      path: '/prescriptions/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'prescriptions',
      description: 'Get prescription details',
    },
    {
      method: 'PUT',
      path: '/prescriptions/:id',
      auth: true,
      role: 'doctor',
      handler: 'crud',
      entity: 'prescriptions',
      description: 'Update prescription',
    },
    {
      method: 'DELETE',
      path: '/prescriptions/:id',
      auth: true,
      role: 'doctor',
      handler: 'crud',
      entity: 'prescriptions',
      description: 'Cancel prescription',
    },
    {
      method: 'POST',
      path: '/prescriptions/:id/send',
      auth: true,
      role: 'doctor',
      handler: 'custom',
      entity: 'prescriptions',
      description: 'Send to pharmacy',
    },
    {
      method: 'POST',
      path: '/prescriptions/:id/void',
      auth: true,
      role: 'doctor',
      handler: 'custom',
      entity: 'prescriptions',
      description: 'Void prescription',
    },
    {
      method: 'GET',
      path: '/patients/:id/prescriptions',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'prescriptions',
      description: 'Get patient prescriptions',
    },

    // Medication routes
    {
      method: 'GET',
      path: '/medications/search',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'medications',
      description: 'Search medications',
    },
    {
      method: 'GET',
      path: '/medications/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'medications',
      description: 'Get medication details',
    },
    {
      method: 'GET',
      path: '/medications/:id/interactions',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'drug_interactions',
      description: 'Check drug interactions',
    },

    // Refill routes
    {
      method: 'GET',
      path: '/refills',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'refills',
      description: 'List refill requests',
    },
    {
      method: 'POST',
      path: '/prescriptions/:id/refill',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'refills',
      description: 'Request refill',
    },
    {
      method: 'POST',
      path: '/refills/:id/approve',
      auth: true,
      role: 'doctor',
      handler: 'custom',
      entity: 'refills',
      description: 'Approve refill',
    },
    {
      method: 'POST',
      path: '/refills/:id/deny',
      auth: true,
      role: 'doctor',
      handler: 'custom',
      entity: 'refills',
      description: 'Deny refill',
    },

    // Pharmacy routes
    {
      method: 'GET',
      path: '/pharmacies',
      auth: true,
      handler: 'crud',
      entity: 'pharmacies',
      description: 'List pharmacies',
    },
    {
      method: 'GET',
      path: '/pharmacies/search',
      auth: true,
      handler: 'custom',
      entity: 'pharmacies',
      description: 'Search pharmacies',
    },
    {
      method: 'GET',
      path: '/pharmacies/:id',
      auth: true,
      handler: 'crud',
      entity: 'pharmacies',
      description: 'Get pharmacy details',
    },
    {
      method: 'POST',
      path: '/pharmacies',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'pharmacies',
      description: 'Add pharmacy',
    },

    // E-prescribing routes
    {
      method: 'POST',
      path: '/eprescribe/send',
      auth: true,
      role: 'doctor',
      handler: 'custom',
      entity: 'prescriptions',
      description: 'Send e-prescription',
    },
    {
      method: 'GET',
      path: '/eprescribe/eligibility/:patientId',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'prescriptions',
      description: 'Check e-prescribe eligibility',
    },
  ],

  config: [
    {
      key: 'eprescribeEnabled',
      label: 'Enable E-Prescribing',
      type: 'boolean',
      default: true,
      description: 'Enable electronic prescribing',
    },
    {
      key: 'controlledSubstancesEnabled',
      label: 'EPCS Enabled',
      type: 'boolean',
      default: false,
      description: 'Enable electronic prescribing of controlled substances',
    },
    {
      key: 'defaultRefills',
      label: 'Default Refills Allowed',
      type: 'number',
      default: 3,
      description: 'Default number of refills for new prescriptions',
    },
    {
      key: 'drugInteractionCheck',
      label: 'Drug Interaction Checking',
      type: 'select',
      default: 'required',
      options: [
        { value: 'required', label: 'Required - Block if severe' },
        { value: 'warning', label: 'Warning only' },
        { value: 'disabled', label: 'Disabled' },
      ],
      description: 'Drug interaction checking behavior',
    },
    {
      key: 'requireDiagnosis',
      label: 'Require Diagnosis',
      type: 'boolean',
      default: true,
      description: 'Require diagnosis code for prescriptions',
    },
    {
      key: 'autoFavoritePharmacy',
      label: 'Remember Patient Pharmacy',
      type: 'boolean',
      default: true,
      description: 'Automatically save patient preferred pharmacy',
    },
  ],
};
