/**
 * Referrals Feature Definition
 *
 * Patient referral management for healthcare applications.
 * Includes provider directory, referral tracking, and communication.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const REFERRALS_FEATURE: FeatureDefinition = {
  id: 'referrals',
  name: 'Referrals',
  category: 'healthcare',
  description: 'Manage patient referrals, provider directory, and referral tracking',
  icon: 'share-alt',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'hospital',
    'urgent-care',
    'physical-therapy',
    'mental-health',
    'cardiology',
    'orthopedics',
    'neurology',
    'oncology',
    'gastroenterology',
    'pulmonology',
    'rheumatology',
    'urology',
    'dermatology',
    'primary-care',
    'family-practice',
    'pediatrics',
    'referral-management',
  ],

  activationKeywords: [
    'referrals',
    'referral',
    'patient referral',
    'refer patient',
    'specialist referral',
    'provider referral',
    'referral tracking',
    'referral management',
    'provider directory',
    'specialist directory',
    'consult request',
    'consultation request',
    'transfer of care',
    'care coordination',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'patient-records'],
  conflicts: [],

  pages: [
    {
      id: 'referrals-list',
      route: '/referrals',
      section: 'frontend',
      title: 'Referrals',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'care-coordinator'],
      templateId: 'referrals-list',
      components: [
        'referrals-table',
        'referral-filters',
        'pending-referrals',
        'referral-search',
        'referral-stats',
      ],
      layout: 'dashboard',
    },
    {
      id: 'referral-detail',
      route: '/referrals/:id',
      section: 'frontend',
      title: 'Referral Details',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'care-coordinator'],
      templateId: 'referral-detail',
      components: [
        'referral-header',
        'referral-info',
        'referral-status-timeline',
        'referral-documents',
        'referral-notes',
        'referral-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'provider-directory',
      route: '/providers',
      section: 'frontend',
      title: 'Provider Directory',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'care-coordinator', 'receptionist'],
      templateId: 'provider-directory',
      components: [
        'provider-search',
        'provider-filters',
        'provider-list',
        'provider-map',
        'specialty-filter',
      ],
      layout: 'dashboard',
    },
    {
      id: 'new-referral',
      route: '/referrals/new',
      section: 'frontend',
      title: 'Create Referral',
      authRequired: true,
      roles: ['doctor', 'care-coordinator'],
      templateId: 'new-referral',
      components: [
        'referral-form',
        'patient-selector',
        'provider-search',
        'reason-selector',
        'urgency-picker',
        'document-attach',
      ],
      layout: 'dashboard',
    },
    {
      id: 'incoming-referrals',
      route: '/referrals/incoming',
      section: 'frontend',
      title: 'Incoming Referrals',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'receptionist'],
      templateId: 'incoming-referrals',
      components: [
        'incoming-referral-table',
        'referral-acceptance',
        'schedule-appointment',
        'referral-response',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-referrals',
      route: '/admin/referrals',
      section: 'admin',
      title: 'Referral Administration',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-referrals',
      components: [
        'referral-analytics',
        'provider-management',
        'specialty-management',
        'fax-settings',
        'integration-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Referral list components
    'referrals-table',
    'referral-card',
    'referral-filters',
    'pending-referrals',
    'referral-search',
    'referral-stats',
    'referral-status-badge',

    // Referral detail components
    'referral-header',
    'referral-info',
    'referral-status-timeline',
    'referral-documents',
    'referral-notes',
    'referral-actions',
    'referral-response',

    // Form components
    'referral-form',
    'patient-selector',
    'provider-search',
    'reason-selector',
    'urgency-picker',
    'document-attach',
    'clinical-summary',

    // Provider directory components
    'provider-list',
    'provider-card',
    'provider-filters',
    'provider-map',
    'specialty-filter',
    'availability-indicator',
    'provider-detail-modal',

    // Incoming referral components
    'incoming-referral-table',
    'referral-acceptance',
    'schedule-appointment',
    'referral-acknowledge',

    // Communication components
    'fax-integration',
    'secure-message',
    'referral-notification',
    'status-update-form',

    // Admin components
    'referral-analytics',
    'provider-management',
    'specialty-management',
    'fax-settings',
    'integration-settings',
  ],

  entities: [
    {
      name: 'referrals',
      displayName: 'Referrals',
      description: 'Patient referral records',
      isCore: true,
    },
    {
      name: 'referring_providers',
      displayName: 'Referring Providers',
      description: 'Providers who make referrals',
      isCore: true,
    },
    {
      name: 'specialists',
      displayName: 'Specialists',
      description: 'Specialist providers receiving referrals',
      isCore: true,
    },
    {
      name: 'specialties',
      displayName: 'Specialties',
      description: 'Medical specialties',
      isCore: false,
    },
    {
      name: 'referral_documents',
      displayName: 'Referral Documents',
      description: 'Documents attached to referrals',
      isCore: false,
    },
    {
      name: 'referral_messages',
      displayName: 'Referral Messages',
      description: 'Communication about referrals',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Referral routes
    {
      method: 'GET',
      path: '/referrals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referrals',
      description: 'List referrals',
    },
    {
      method: 'POST',
      path: '/referrals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referrals',
      description: 'Create referral',
    },
    {
      method: 'GET',
      path: '/referrals/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referrals',
      description: 'Get referral details',
    },
    {
      method: 'PUT',
      path: '/referrals/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referrals',
      description: 'Update referral',
    },
    {
      method: 'DELETE',
      path: '/referrals/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referrals',
      description: 'Cancel referral',
    },
    {
      method: 'POST',
      path: '/referrals/:id/send',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'referrals',
      description: 'Send referral to specialist',
    },
    {
      method: 'POST',
      path: '/referrals/:id/accept',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'referrals',
      description: 'Accept referral',
    },
    {
      method: 'POST',
      path: '/referrals/:id/decline',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'referrals',
      description: 'Decline referral',
    },
    {
      method: 'POST',
      path: '/referrals/:id/complete',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'referrals',
      description: 'Complete referral',
    },
    {
      method: 'GET',
      path: '/referrals/incoming',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'referrals',
      description: 'Get incoming referrals',
    },
    {
      method: 'GET',
      path: '/referrals/outgoing',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'referrals',
      description: 'Get outgoing referrals',
    },
    {
      method: 'GET',
      path: '/patients/:id/referrals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referrals',
      description: 'Get patient referrals',
    },

    // Provider routes
    {
      method: 'GET',
      path: '/providers',
      auth: true,
      handler: 'crud',
      entity: 'specialists',
      description: 'List providers',
    },
    {
      method: 'GET',
      path: '/providers/search',
      auth: true,
      handler: 'custom',
      entity: 'specialists',
      description: 'Search providers',
    },
    {
      method: 'GET',
      path: '/providers/:id',
      auth: true,
      handler: 'crud',
      entity: 'specialists',
      description: 'Get provider details',
    },
    {
      method: 'POST',
      path: '/providers',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'specialists',
      description: 'Add provider',
    },
    {
      method: 'PUT',
      path: '/providers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'specialists',
      description: 'Update provider',
    },
    {
      method: 'GET',
      path: '/providers/by-specialty/:specialty',
      auth: true,
      handler: 'custom',
      entity: 'specialists',
      description: 'Get providers by specialty',
    },

    // Specialty routes
    {
      method: 'GET',
      path: '/specialties',
      auth: true,
      handler: 'crud',
      entity: 'specialties',
      description: 'List specialties',
    },
    {
      method: 'POST',
      path: '/specialties',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'specialties',
      description: 'Add specialty',
    },

    // Document routes
    {
      method: 'GET',
      path: '/referrals/:id/documents',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referral_documents',
      description: 'Get referral documents',
    },
    {
      method: 'POST',
      path: '/referrals/:id/documents',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referral_documents',
      description: 'Attach document',
    },
    {
      method: 'DELETE',
      path: '/referral-documents/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referral_documents',
      description: 'Remove document',
    },

    // Message routes
    {
      method: 'GET',
      path: '/referrals/:id/messages',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referral_messages',
      description: 'Get referral messages',
    },
    {
      method: 'POST',
      path: '/referrals/:id/messages',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'referral_messages',
      description: 'Send message',
    },

    // Analytics routes
    {
      method: 'GET',
      path: '/referrals/analytics',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'referrals',
      description: 'Get referral analytics',
    },

    // Fax routes
    {
      method: 'POST',
      path: '/referrals/:id/fax',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'referrals',
      description: 'Fax referral',
    },
  ],

  config: [
    {
      key: 'requireAuthorization',
      label: 'Require Prior Authorization',
      type: 'boolean',
      default: false,
      description: 'Require insurance authorization for referrals',
    },
    {
      key: 'autoSendNotification',
      label: 'Auto-Send Notifications',
      type: 'boolean',
      default: true,
      description: 'Automatically notify specialist of new referral',
    },
    {
      key: 'faxEnabled',
      label: 'Fax Integration',
      type: 'boolean',
      default: true,
      description: 'Enable fax sending for referrals',
    },
    {
      key: 'trackingEnabled',
      label: 'Referral Tracking',
      type: 'boolean',
      default: true,
      description: 'Enable referral status tracking',
    },
    {
      key: 'defaultUrgency',
      label: 'Default Urgency',
      type: 'select',
      default: 'routine',
      options: [
        { value: 'routine', label: 'Routine' },
        { value: 'urgent', label: 'Urgent' },
        { value: 'stat', label: 'STAT' },
      ],
      description: 'Default referral urgency',
    },
    {
      key: 'expirationDays',
      label: 'Referral Expiration (days)',
      type: 'number',
      default: 90,
      description: 'Days until referral expires',
    },
    {
      key: 'requireClinicalSummary',
      label: 'Require Clinical Summary',
      type: 'boolean',
      default: true,
      description: 'Require clinical summary with referral',
    },
  ],
};
