/**
 * Telemedicine Feature Definition
 *
 * Virtual consultations and remote care functionality for healthcare
 * applications. Includes video calls, virtual waiting rooms, and remote prescribing.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TELEMEDICINE_FEATURE: FeatureDefinition = {
  id: 'telemedicine',
  name: 'Telemedicine',
  category: 'healthcare',
  description: 'Virtual consultations, video calls, and remote patient care',
  icon: 'video',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'telemedicine',
    'mental-health',
    'psychiatry',
    'dermatology',
    'urgent-care',
    'pediatrics',
    'internal-medicine',
    'family-practice',
    'wellness',
    'behavioral-health',
    'nutrition',
    'physical-therapy',
    'speech-therapy',
    'counseling',
  ],

  activationKeywords: [
    'telemedicine',
    'telehealth',
    'virtual visit',
    'video consultation',
    'remote care',
    'virtual doctor',
    'online consultation',
    'video call',
    'virtual appointment',
    'remote patient',
    'e-visit',
    'tele-visit',
    'virtual care',
    'zoom health',
    'doxy',
    'teladoc',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'patient-records', 'appointments'],
  conflicts: [],

  pages: [
    {
      id: 'virtual-waiting-room',
      route: '/virtual-waiting-room',
      section: 'frontend',
      title: 'Virtual Waiting Room',
      authRequired: true,
      templateId: 'virtual-waiting-room',
      components: [
        'waiting-room-status',
        'queue-position',
        'pre-visit-checklist',
        'device-test',
        'appointment-info',
        'join-call-button',
      ],
      layout: 'centered',
    },
    {
      id: 'video-consultation',
      route: '/consultation/:id',
      section: 'frontend',
      title: 'Video Consultation',
      authRequired: true,
      roles: ['doctor', 'nurse', 'patient'],
      templateId: 'video-consultation',
      components: [
        'video-call',
        'participant-list',
        'chat-panel',
        'screen-share',
        'prescription-pad',
        'notes-panel',
        'call-controls',
        'recording-indicator',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'telehealth-dashboard',
      route: '/telehealth',
      section: 'frontend',
      title: 'Telehealth Dashboard',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'telehealth-dashboard',
      components: [
        'upcoming-virtual-visits',
        'virtual-queue',
        'telehealth-stats',
        'quick-start-visit',
        'patient-check-in-list',
      ],
      layout: 'dashboard',
    },
    {
      id: 'provider-video-room',
      route: '/provider/video-room',
      section: 'frontend',
      title: 'Provider Video Room',
      authRequired: true,
      roles: ['doctor', 'nurse'],
      templateId: 'provider-video-room',
      components: [
        'multi-participant-video',
        'patient-chart-sidebar',
        'quick-actions-panel',
        'consultation-timer',
        'end-visit-workflow',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'admin-telehealth',
      route: '/admin/telehealth',
      section: 'admin',
      title: 'Telehealth Administration',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-telehealth',
      components: [
        'telehealth-analytics',
        'provider-availability',
        'video-settings',
        'integration-settings',
        'quality-metrics',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Waiting room components
    'waiting-room-status',
    'queue-position',
    'pre-visit-checklist',
    'device-test',
    'appointment-info',
    'join-call-button',
    'tech-support-chat',

    // Video call components
    'video-call',
    'video-player',
    'participant-list',
    'participant-tile',
    'chat-panel',
    'screen-share',
    'call-controls',
    'mute-button',
    'camera-toggle',
    'end-call-button',
    'recording-indicator',

    // Consultation components
    'prescription-pad',
    'notes-panel',
    'diagnosis-quick-add',
    'patient-chart-sidebar',
    'consultation-timer',
    'quick-actions-panel',

    // Virtual queue components
    'virtual-queue',
    'queue-card',
    'patient-check-in-list',
    'check-in-notification',

    // Dashboard components
    'upcoming-virtual-visits',
    'telehealth-stats',
    'quick-start-visit',
    'visit-summary',

    // Multi-party components
    'multi-participant-video',
    'add-participant',
    'interpreter-request',
    'family-member-invite',

    // Post-visit components
    'end-visit-workflow',
    'visit-summary-form',
    'follow-up-scheduler',
    'patient-instructions',

    // Admin components
    'telehealth-analytics',
    'provider-availability',
    'video-settings',
    'integration-settings',
    'quality-metrics',
  ],

  entities: [
    {
      name: 'virtual_visits',
      displayName: 'Virtual Visits',
      description: 'Telemedicine visit records',
      isCore: true,
    },
    {
      name: 'consultation_notes',
      displayName: 'Consultation Notes',
      description: 'Notes from virtual consultations',
      isCore: true,
    },
    {
      name: 'telehealth_sessions',
      displayName: 'Telehealth Sessions',
      description: 'Active video session data',
      isCore: true,
    },
    {
      name: 'virtual_waiting_room',
      displayName: 'Virtual Waiting Room',
      description: 'Waiting room queue entries',
      isCore: false,
    },
    {
      name: 'session_recordings',
      displayName: 'Session Recordings',
      description: 'Recorded consultation sessions',
      isCore: false,
    },
    {
      name: 'device_checks',
      displayName: 'Device Checks',
      description: 'Pre-visit device test results',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Virtual visit routes
    {
      method: 'GET',
      path: '/virtual-visits',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'virtual_visits',
      description: 'List virtual visits',
    },
    {
      method: 'POST',
      path: '/virtual-visits',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'virtual_visits',
      description: 'Create virtual visit',
    },
    {
      method: 'GET',
      path: '/virtual-visits/:id',
      auth: true,
      handler: 'crud',
      entity: 'virtual_visits',
      description: 'Get virtual visit details',
    },
    {
      method: 'PUT',
      path: '/virtual-visits/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'virtual_visits',
      description: 'Update virtual visit',
    },
    {
      method: 'POST',
      path: '/virtual-visits/:id/start',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'virtual_visits',
      description: 'Start virtual visit',
    },
    {
      method: 'POST',
      path: '/virtual-visits/:id/end',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'virtual_visits',
      description: 'End virtual visit',
    },
    {
      method: 'GET',
      path: '/patients/:id/virtual-visits',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'virtual_visits',
      description: 'Get patient virtual visits',
    },

    // Session routes
    {
      method: 'POST',
      path: '/telehealth/session',
      auth: true,
      handler: 'custom',
      entity: 'telehealth_sessions',
      description: 'Create video session',
    },
    {
      method: 'GET',
      path: '/telehealth/session/:id',
      auth: true,
      handler: 'crud',
      entity: 'telehealth_sessions',
      description: 'Get session details',
    },
    {
      method: 'POST',
      path: '/telehealth/session/:id/join',
      auth: true,
      handler: 'custom',
      entity: 'telehealth_sessions',
      description: 'Join video session',
    },
    {
      method: 'POST',
      path: '/telehealth/session/:id/leave',
      auth: true,
      handler: 'custom',
      entity: 'telehealth_sessions',
      description: 'Leave video session',
    },
    {
      method: 'GET',
      path: '/telehealth/session/:id/token',
      auth: true,
      handler: 'custom',
      entity: 'telehealth_sessions',
      description: 'Get session access token',
    },

    // Waiting room routes
    {
      method: 'GET',
      path: '/waiting-room',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'virtual_waiting_room',
      description: 'Get waiting room queue',
    },
    {
      method: 'POST',
      path: '/waiting-room/check-in',
      auth: true,
      handler: 'custom',
      entity: 'virtual_waiting_room',
      description: 'Check into waiting room',
    },
    {
      method: 'GET',
      path: '/waiting-room/status',
      auth: true,
      handler: 'custom',
      entity: 'virtual_waiting_room',
      description: 'Get queue position',
    },
    {
      method: 'POST',
      path: '/waiting-room/:id/call',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'virtual_waiting_room',
      description: 'Call patient from queue',
    },

    // Consultation notes routes
    {
      method: 'GET',
      path: '/virtual-visits/:id/notes',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'consultation_notes',
      description: 'Get consultation notes',
    },
    {
      method: 'POST',
      path: '/virtual-visits/:id/notes',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'consultation_notes',
      description: 'Add consultation notes',
    },
    {
      method: 'PUT',
      path: '/consultation-notes/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'consultation_notes',
      description: 'Update consultation notes',
    },

    // Recording routes
    {
      method: 'POST',
      path: '/telehealth/session/:id/record/start',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'session_recordings',
      description: 'Start session recording',
    },
    {
      method: 'POST',
      path: '/telehealth/session/:id/record/stop',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'session_recordings',
      description: 'Stop session recording',
    },
    {
      method: 'GET',
      path: '/recordings/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'session_recordings',
      description: 'Get recording',
    },

    // Device check routes
    {
      method: 'POST',
      path: '/device-check',
      auth: true,
      handler: 'custom',
      entity: 'device_checks',
      description: 'Run device check',
    },
    {
      method: 'GET',
      path: '/device-check/status',
      auth: true,
      handler: 'custom',
      entity: 'device_checks',
      description: 'Get device check status',
    },

    // Analytics routes
    {
      method: 'GET',
      path: '/telehealth/analytics',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'virtual_visits',
      description: 'Get telehealth analytics',
    },
  ],

  config: [
    {
      key: 'videoProvider',
      label: 'Video Provider',
      type: 'select',
      default: 'twilio',
      options: [
        { value: 'twilio', label: 'Twilio Video' },
        { value: 'vonage', label: 'Vonage (TokBox)' },
        { value: 'zoom', label: 'Zoom SDK' },
        { value: 'daily', label: 'Daily.co' },
        { value: 'agora', label: 'Agora' },
      ],
      description: 'Video conferencing provider',
    },
    {
      key: 'recordingEnabled',
      label: 'Session Recording',
      type: 'boolean',
      default: false,
      description: 'Enable session recording',
    },
    {
      key: 'requireConsent',
      label: 'Require Recording Consent',
      type: 'boolean',
      default: true,
      description: 'Require patient consent for recording',
    },
    {
      key: 'maxParticipants',
      label: 'Maximum Participants',
      type: 'number',
      default: 4,
      description: 'Maximum participants per session',
    },
    {
      key: 'sessionTimeout',
      label: 'Session Timeout (minutes)',
      type: 'number',
      default: 60,
      description: 'Maximum session duration',
    },
    {
      key: 'waitingRoomEnabled',
      label: 'Virtual Waiting Room',
      type: 'boolean',
      default: true,
      description: 'Enable virtual waiting room',
    },
    {
      key: 'screenShareEnabled',
      label: 'Screen Sharing',
      type: 'boolean',
      default: true,
      description: 'Allow screen sharing in sessions',
    },
    {
      key: 'chatEnabled',
      label: 'In-Session Chat',
      type: 'boolean',
      default: true,
      description: 'Enable chat during video sessions',
    },
  ],
};
