/**
 * Treatment Plans Feature Definition
 *
 * Treatment planning and tracking for healthcare applications.
 * Includes procedures, goals, and progress monitoring.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TREATMENT_PLANS_FEATURE: FeatureDefinition = {
  id: 'treatment-plans',
  name: 'Treatment Plans',
  category: 'healthcare',
  description: 'Create and track treatment plans, procedures, and patient goals',
  icon: 'clipboard-list',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'dental-clinic',
    'hospital',
    'urgent-care',
    'physical-therapy',
    'chiropractic',
    'mental-health',
    'psychiatry',
    'rehabilitation',
    'oncology',
    'pain-management',
    'wound-care',
    'home-health',
    'skilled-nursing',
    'occupational-therapy',
    'speech-therapy',
  ],

  activationKeywords: [
    'treatment plan',
    'treatment plans',
    'care plan',
    'care planning',
    'treatment protocol',
    'clinical protocol',
    'therapy plan',
    'rehabilitation plan',
    'treatment tracking',
    'procedure planning',
    'patient goals',
    'treatment goals',
    'care coordination',
    'clinical pathway',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'patient-records'],
  conflicts: [],

  pages: [
    {
      id: 'treatment-list',
      route: '/treatment-plans',
      section: 'frontend',
      title: 'Treatment Plans',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'therapist'],
      templateId: 'treatment-list',
      components: [
        'treatment-plan-table',
        'treatment-filters',
        'treatment-status-filter',
        'quick-plan-create',
      ],
      layout: 'dashboard',
    },
    {
      id: 'treatment-detail',
      route: '/treatment-plans/:id',
      section: 'frontend',
      title: 'Treatment Plan Details',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'therapist'],
      templateId: 'treatment-detail',
      components: [
        'treatment-header',
        'treatment-overview',
        'procedure-list',
        'goal-tracker',
        'treatment-timeline',
        'treatment-notes',
        'treatment-attachments',
      ],
      layout: 'dashboard',
    },
    {
      id: 'treatment-progress',
      route: '/treatment-plans/:id/progress',
      section: 'frontend',
      title: 'Treatment Progress',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse', 'therapist'],
      templateId: 'treatment-progress',
      components: [
        'progress-chart',
        'milestone-tracker',
        'outcome-measures',
        'goal-progress-bars',
        'session-history',
        'progress-notes',
      ],
      layout: 'dashboard',
    },
    {
      id: 'treatment-create',
      route: '/treatment-plans/new',
      section: 'frontend',
      title: 'Create Treatment Plan',
      authRequired: true,
      roles: ['admin', 'doctor', 'therapist'],
      templateId: 'treatment-create',
      components: [
        'treatment-form',
        'diagnosis-selector',
        'procedure-builder',
        'goal-builder',
        'timeline-builder',
        'template-selector',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-treatment-plans',
      route: '/admin/treatment-plans',
      section: 'admin',
      title: 'Manage Treatment Plans',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-treatment-plans',
      components: [
        'admin-treatment-table',
        'treatment-analytics',
        'template-manager',
        'protocol-library',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'treatment-plan-table',
    'treatment-plan-card',
    'treatment-filters',
    'treatment-status-filter',
    'quick-plan-create',

    // Detail components
    'treatment-header',
    'treatment-overview',
    'treatment-timeline',
    'treatment-notes',
    'treatment-attachments',
    'treatment-status-badge',

    // Form components
    'treatment-form',
    'diagnosis-selector',
    'procedure-builder',
    'goal-builder',
    'timeline-builder',
    'template-selector',

    // Procedure components
    'procedure-list',
    'procedure-card',
    'procedure-form',
    'procedure-scheduler',
    'procedure-status',

    // Goal components
    'goal-tracker',
    'goal-card',
    'goal-form',
    'goal-progress-bars',
    'outcome-measures',

    // Progress components
    'progress-chart',
    'milestone-tracker',
    'session-history',
    'progress-notes',
    'progress-photos',

    // Admin components
    'admin-treatment-table',
    'treatment-analytics',
    'template-manager',
    'protocol-library',
  ],

  entities: [
    {
      name: 'treatment_plans',
      displayName: 'Treatment Plans',
      description: 'Patient treatment plans',
      isCore: true,
    },
    {
      name: 'procedures',
      displayName: 'Procedures',
      description: 'Treatment procedures',
      isCore: true,
    },
    {
      name: 'treatment_goals',
      displayName: 'Treatment Goals',
      description: 'Goals within treatment plans',
      isCore: true,
    },
    {
      name: 'treatment_sessions',
      displayName: 'Treatment Sessions',
      description: 'Individual treatment sessions',
      isCore: false,
    },
    {
      name: 'treatment_templates',
      displayName: 'Treatment Templates',
      description: 'Reusable treatment plan templates',
      isCore: false,
    },
    {
      name: 'treatment_milestones',
      displayName: 'Treatment Milestones',
      description: 'Treatment progress milestones',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Treatment plan routes
    {
      method: 'GET',
      path: '/treatment-plans',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_plans',
      description: 'List treatment plans',
    },
    {
      method: 'POST',
      path: '/treatment-plans',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_plans',
      description: 'Create treatment plan',
    },
    {
      method: 'GET',
      path: '/treatment-plans/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_plans',
      description: 'Get treatment plan details',
    },
    {
      method: 'PUT',
      path: '/treatment-plans/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_plans',
      description: 'Update treatment plan',
    },
    {
      method: 'DELETE',
      path: '/treatment-plans/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'treatment_plans',
      description: 'Delete treatment plan',
    },
    {
      method: 'POST',
      path: '/treatment-plans/:id/activate',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'treatment_plans',
      description: 'Activate treatment plan',
    },
    {
      method: 'POST',
      path: '/treatment-plans/:id/complete',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'treatment_plans',
      description: 'Complete treatment plan',
    },
    {
      method: 'GET',
      path: '/patients/:id/treatment-plans',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_plans',
      description: 'Get patient treatment plans',
    },

    // Procedure routes
    {
      method: 'GET',
      path: '/treatment-plans/:id/procedures',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'procedures',
      description: 'List procedures in plan',
    },
    {
      method: 'POST',
      path: '/treatment-plans/:id/procedures',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'procedures',
      description: 'Add procedure to plan',
    },
    {
      method: 'PUT',
      path: '/procedures/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'procedures',
      description: 'Update procedure',
    },
    {
      method: 'DELETE',
      path: '/procedures/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'procedures',
      description: 'Remove procedure',
    },
    {
      method: 'POST',
      path: '/procedures/:id/complete',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'procedures',
      description: 'Mark procedure complete',
    },

    // Goal routes
    {
      method: 'GET',
      path: '/treatment-plans/:id/goals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_goals',
      description: 'List treatment goals',
    },
    {
      method: 'POST',
      path: '/treatment-plans/:id/goals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_goals',
      description: 'Add treatment goal',
    },
    {
      method: 'PUT',
      path: '/goals/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_goals',
      description: 'Update goal',
    },
    {
      method: 'POST',
      path: '/goals/:id/progress',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'treatment_goals',
      description: 'Update goal progress',
    },

    // Session routes
    {
      method: 'GET',
      path: '/treatment-plans/:id/sessions',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_sessions',
      description: 'List treatment sessions',
    },
    {
      method: 'POST',
      path: '/treatment-plans/:id/sessions',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_sessions',
      description: 'Log treatment session',
    },

    // Template routes
    {
      method: 'GET',
      path: '/treatment-templates',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'treatment_templates',
      description: 'List treatment templates',
    },
    {
      method: 'POST',
      path: '/treatment-templates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'treatment_templates',
      description: 'Create treatment template',
    },
    {
      method: 'POST',
      path: '/treatment-plans/from-template',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'treatment_plans',
      description: 'Create plan from template',
    },
  ],

  config: [
    {
      key: 'requireDiagnosis',
      label: 'Require Diagnosis',
      type: 'boolean',
      default: true,
      description: 'Require diagnosis for treatment plans',
    },
    {
      key: 'defaultDuration',
      label: 'Default Plan Duration (weeks)',
      type: 'number',
      default: 12,
      description: 'Default duration for new treatment plans',
    },
    {
      key: 'goalTrackingFrequency',
      label: 'Goal Tracking Frequency',
      type: 'select',
      default: 'weekly',
      options: [
        { value: 'daily', label: 'Daily' },
        { value: 'weekly', label: 'Weekly' },
        { value: 'biweekly', label: 'Bi-weekly' },
        { value: 'monthly', label: 'Monthly' },
      ],
      description: 'How often to track goal progress',
    },
    {
      key: 'requireSignature',
      label: 'Require Provider Signature',
      type: 'boolean',
      default: true,
      description: 'Require electronic signature on plans',
    },
    {
      key: 'autoReminders',
      label: 'Automatic Reminders',
      type: 'boolean',
      default: true,
      description: 'Send automatic progress reminders',
    },
  ],
};
