/**
 * Vital Signs Feature Definition
 *
 * Patient vital signs monitoring and tracking for healthcare applications.
 * Includes blood pressure, heart rate, temperature, and other vital measurements.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const VITAL_SIGNS_FEATURE: FeatureDefinition = {
  id: 'vital-signs',
  name: 'Vital Signs',
  category: 'healthcare',
  description: 'Monitor and track patient vital signs with alerts and trending',
  icon: 'heartbeat',

  includedInAppTypes: [
    'healthcare',
    'medical-practice',
    'hospital',
    'urgent-care',
    'nursing-home',
    'home-health',
    'physical-therapy',
    'cardiology',
    'pulmonology',
    'pediatrics',
    'geriatrics',
    'icu',
    'emergency-room',
    'ambulatory-care',
    'remote-monitoring',
    'telehealth',
  ],

  activationKeywords: [
    'vital signs',
    'vitals',
    'blood pressure',
    'bp',
    'heart rate',
    'pulse',
    'temperature',
    'respiration',
    'oxygen saturation',
    'spo2',
    'bmi',
    'weight',
    'height',
    'vital monitoring',
    'patient vitals',
    'vital trends',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'patient-records'],
  conflicts: [],

  pages: [
    {
      id: 'vitals-dashboard',
      route: '/vitals',
      section: 'frontend',
      title: 'Vitals Dashboard',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'vitals-dashboard',
      components: [
        'vitals-overview',
        'recent-vitals-table',
        'abnormal-vitals-alerts',
        'quick-vital-entry',
        'vitals-queue',
      ],
      layout: 'dashboard',
    },
    {
      id: 'vitals-history',
      route: '/patients/:id/vitals',
      section: 'frontend',
      title: 'Vitals History',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'vitals-history',
      components: [
        'vitals-timeline',
        'vitals-chart',
        'vital-comparison',
        'vital-summary-cards',
        'trend-indicators',
      ],
      layout: 'dashboard',
    },
    {
      id: 'vitals-entry',
      route: '/vitals/entry',
      section: 'frontend',
      title: 'Record Vitals',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'vitals-entry',
      components: [
        'vitals-form',
        'patient-quick-search',
        'bp-tracker',
        'glucose-monitor',
        'pain-scale',
        'vital-calculator',
      ],
      layout: 'dashboard',
    },
    {
      id: 'vital-alerts',
      route: '/vitals/alerts',
      section: 'frontend',
      title: 'Vital Alerts',
      authRequired: true,
      roles: ['admin', 'doctor', 'nurse'],
      templateId: 'vital-alerts',
      components: [
        'active-alerts',
        'alert-history',
        'alert-rules',
        'escalation-status',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-vitals',
      route: '/admin/vitals',
      section: 'admin',
      title: 'Vitals Configuration',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-vitals',
      components: [
        'vital-types-manager',
        'threshold-editor',
        'alert-rules-manager',
        'device-integrations',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'vitals-overview',
    'recent-vitals-table',
    'abnormal-vitals-alerts',
    'quick-vital-entry',
    'vitals-queue',
    'vital-summary-cards',

    // Form components
    'vitals-form',
    'patient-quick-search',
    'bp-tracker',
    'glucose-monitor',
    'pain-scale',
    'vital-calculator',
    'bmi-calculator',

    // Individual vital components
    'blood-pressure-input',
    'heart-rate-input',
    'temperature-input',
    'respiratory-rate-input',
    'oxygen-saturation-input',
    'weight-input',
    'height-input',
    'pain-level-input',

    // Chart components
    'vitals-chart',
    'bp-trend-chart',
    'heart-rate-chart',
    'temperature-chart',
    'weight-trend-chart',
    'multi-vital-chart',

    // History components
    'vitals-timeline',
    'vital-comparison',
    'trend-indicators',
    'vital-history-table',

    // Alert components
    'active-alerts',
    'alert-history',
    'alert-rules',
    'escalation-status',
    'vital-alert-badge',
    'critical-alert-modal',

    // Admin components
    'vital-types-manager',
    'threshold-editor',
    'alert-rules-manager',
    'device-integrations',
  ],

  entities: [
    {
      name: 'vital_records',
      displayName: 'Vital Records',
      description: 'Patient vital sign measurements',
      isCore: true,
    },
    {
      name: 'vital_types',
      displayName: 'Vital Types',
      description: 'Types of vital signs tracked',
      isCore: true,
    },
    {
      name: 'vital_alerts',
      displayName: 'Vital Alerts',
      description: 'Vital sign alert records',
      isCore: true,
    },
    {
      name: 'vital_thresholds',
      displayName: 'Vital Thresholds',
      description: 'Normal ranges and alert thresholds',
      isCore: false,
    },
    {
      name: 'vital_devices',
      displayName: 'Vital Devices',
      description: 'Connected monitoring devices',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Vital records routes
    {
      method: 'GET',
      path: '/vitals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_records',
      description: 'List vital records',
    },
    {
      method: 'POST',
      path: '/vitals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_records',
      description: 'Record vitals',
    },
    {
      method: 'GET',
      path: '/vitals/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_records',
      description: 'Get vital record',
    },
    {
      method: 'PUT',
      path: '/vitals/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_records',
      description: 'Update vital record',
    },
    {
      method: 'DELETE',
      path: '/vitals/:id',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_records',
      description: 'Delete vital record',
    },
    {
      method: 'GET',
      path: '/patients/:id/vitals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_records',
      description: 'Get patient vitals',
    },
    {
      method: 'POST',
      path: '/patients/:id/vitals',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_records',
      description: 'Record patient vitals',
    },
    {
      method: 'GET',
      path: '/patients/:id/vitals/latest',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'vital_records',
      description: 'Get latest vitals',
    },
    {
      method: 'GET',
      path: '/patients/:id/vitals/trends',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'vital_records',
      description: 'Get vital trends',
    },
    {
      method: 'GET',
      path: '/patients/:id/vitals/summary',
      auth: true,
      role: 'clinical',
      handler: 'aggregate',
      entity: 'vital_records',
      description: 'Get vitals summary',
    },

    // Vital types routes
    {
      method: 'GET',
      path: '/vital-types',
      auth: true,
      handler: 'crud',
      entity: 'vital_types',
      description: 'List vital types',
    },
    {
      method: 'POST',
      path: '/vital-types',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vital_types',
      description: 'Create vital type',
    },
    {
      method: 'PUT',
      path: '/vital-types/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vital_types',
      description: 'Update vital type',
    },

    // Alert routes
    {
      method: 'GET',
      path: '/vital-alerts',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_alerts',
      description: 'List vital alerts',
    },
    {
      method: 'GET',
      path: '/vital-alerts/active',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'vital_alerts',
      description: 'Get active alerts',
    },
    {
      method: 'POST',
      path: '/vital-alerts/:id/acknowledge',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'vital_alerts',
      description: 'Acknowledge alert',
    },
    {
      method: 'POST',
      path: '/vital-alerts/:id/resolve',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'vital_alerts',
      description: 'Resolve alert',
    },
    {
      method: 'GET',
      path: '/patients/:id/vital-alerts',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_alerts',
      description: 'Get patient alerts',
    },

    // Threshold routes
    {
      method: 'GET',
      path: '/vital-thresholds',
      auth: true,
      handler: 'crud',
      entity: 'vital_thresholds',
      description: 'List thresholds',
    },
    {
      method: 'PUT',
      path: '/vital-thresholds/:vitalType',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vital_thresholds',
      description: 'Update thresholds',
    },
    {
      method: 'GET',
      path: '/patients/:id/vital-thresholds',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_thresholds',
      description: 'Get patient-specific thresholds',
    },
    {
      method: 'POST',
      path: '/patients/:id/vital-thresholds',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_thresholds',
      description: 'Set patient-specific thresholds',
    },

    // Device routes
    {
      method: 'GET',
      path: '/vital-devices',
      auth: true,
      role: 'clinical',
      handler: 'crud',
      entity: 'vital_devices',
      description: 'List monitoring devices',
    },
    {
      method: 'POST',
      path: '/vital-devices',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vital_devices',
      description: 'Register device',
    },
    {
      method: 'POST',
      path: '/vital-devices/:id/sync',
      auth: true,
      role: 'clinical',
      handler: 'custom',
      entity: 'vital_devices',
      description: 'Sync device data',
    },

    // Analytics routes
    {
      method: 'GET',
      path: '/vitals/analytics',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'vital_records',
      description: 'Get vitals analytics',
    },
  ],

  config: [
    {
      key: 'defaultVitals',
      label: 'Default Vital Signs',
      type: 'string',
      default: 'bp,hr,temp,rr,spo2,weight',
      description: 'Comma-separated list of default vitals to capture',
    },
    {
      key: 'alertEnabled',
      label: 'Enable Vital Alerts',
      type: 'boolean',
      default: true,
      description: 'Enable automatic alerting for abnormal vitals',
    },
    {
      key: 'criticalAlertPush',
      label: 'Push Critical Alerts',
      type: 'boolean',
      default: true,
      description: 'Send push notifications for critical values',
    },
    {
      key: 'autoCalculateBMI',
      label: 'Auto-Calculate BMI',
      type: 'boolean',
      default: true,
      description: 'Automatically calculate BMI from height/weight',
    },
    {
      key: 'trendDisplayDays',
      label: 'Trend Display (days)',
      type: 'number',
      default: 90,
      description: 'Days of history to show in trend charts',
    },
    {
      key: 'temperatureUnit',
      label: 'Temperature Unit',
      type: 'select',
      default: 'fahrenheit',
      options: [
        { value: 'fahrenheit', label: 'Fahrenheit' },
        { value: 'celsius', label: 'Celsius' },
      ],
      description: 'Default temperature unit',
    },
    {
      key: 'weightUnit',
      label: 'Weight Unit',
      type: 'select',
      default: 'lbs',
      options: [
        { value: 'lbs', label: 'Pounds (lbs)' },
        { value: 'kg', label: 'Kilograms (kg)' },
      ],
      description: 'Default weight unit',
    },
    {
      key: 'heightUnit',
      label: 'Height Unit',
      type: 'select',
      default: 'inches',
      options: [
        { value: 'inches', label: 'Inches' },
        { value: 'cm', label: 'Centimeters' },
      ],
      description: 'Default height unit',
    },
  ],
};
