/**
 * Blueprint System for App Creator
 *
 * Blueprints define the structure of different app types:
 * - Pages to generate
 * - Layout for each page
 * - Components to use in each section
 * - API endpoints needed
 */

import { EnhancedEntityDefinition } from '../dto/create-app.dto';

// Component types available in app-creator
export type ComponentType =
  // Common
  | 'hero'
  | 'navbar'
  | 'footer'
  | 'sidebar'
  // Data Display
  | 'data-table'
  | 'data-grid'
  | 'data-list'
  | 'detail-view'
  // Forms
  | 'create-form'
  | 'edit-form'
  | 'search-form'
  | 'filter-form'
  | 'search-bar'
  // Ecommerce
  | 'product-grid'
  | 'product-card'
  | 'product-detail'
  | 'product-filters'
  | 'product-form'
  | 'cart'
  | 'checkout'
  | 'order-summary'
  | 'order-detail'
  // Blog
  | 'blog-list'
  | 'blog-card'
  | 'blog-detail'
  | 'blog-sidebar'
  | 'blog-author'
  | 'comment-section'
  // Auth
  | 'login-form'
  | 'register-form'
  | 'profile-view'
  // Charts/Dashboard
  | 'stats-cards'
  | 'chart-widget'
  | 'analytics-charts'
  | 'activity-feed'
  | 'team-list'
  | 'subscription-card'
  // CRM
  | 'pipeline-overview'
  | 'kanban-board'
  | 'contact-profile'
  | 'company-profile'
  | 'task-list'
  | 'activity-timeline'
  | 'notes-list'
  | 'deal-card'
  // Project Management
  | 'project-grid'
  | 'project-header'
  | 'milestone-tracker'
  | 'team-members'
  // Social
  | 'profile-header'
  | 'profile-tabs'
  | 'post-composer'
  | 'post-feed'
  | 'user-grid'
  | 'message-list'
  | 'chat-interface'
  | 'notification-list'
  // Booking
  | 'service-grid'
  | 'staff-grid'
  | 'booking-wizard'
  | 'date-picker'
  | 'time-slots'
  | 'appointment-list'
  | 'appointment-detail'
  | 'booking-confirmation'
  | 'calendar-view'
  // LMS
  | 'course-grid'
  | 'course-filters'
  | 'course-header'
  | 'curriculum-list'
  | 'lesson-player'
  | 'lesson-sidebar'
  | 'progress-tracker'
  | 'enrolled-courses'
  | 'certificate-grid'
  | 'quiz-player'
  // Real Estate
  | 'property-search'
  | 'property-grid'
  | 'property-filters'
  | 'property-gallery'
  | 'property-details'
  | 'inquiry-form'
  | 'agent-grid'
  | 'agent-profile'
  | 'map-list-toggle'
  // Restaurant
  | 'menu-grid'
  | 'menu-categories'
  | 'cart-preview'
  | 'checkout-form'
  | 'order-confirmation'
  | 'order-tracking'
  | 'order-list'
  | 'reservation-form'
  | 'restaurant-info'
  | 'order-queue'
  | 'review-carousel'
  | 'review-list'
  // Job Board
  | 'job-search'
  | 'job-list'
  | 'job-filters'
  | 'job-detail'
  | 'apply-card'
  | 'company-card'
  | 'company-grid'
  | 'application-form'
  | 'application-list'
  | 'candidate-profile-form'
  | 'category-grid'
  // Inventory
  | 'low-stock-alert'
  | 'stock-by-warehouse'
  | 'stock-adjustment-form'
  | 'product-detail-card'
  | 'purchase-order-detail'
  | 'report-list'
  // Additional components
  | 'task-detail'
  | 'contact-form'
  | 'settings-form'
  | 'create-post'
  | 'user-suggestions'
  | 'trending-topics'
  | 'post-detail'
  | 'conversation-list'
  | 'chat-window'
  // Healthcare
  | 'patient-profile'
  | 'medical-history'
  | 'appointment-calendar'
  | 'appointment-form'
  | 'doctor-grid'
  | 'doctor-profile'
  | 'doctor-schedule'
  // Healthcare Specialties - Chiropractic
  | 'chiropractor-stats'
  | 'spine-assessment'
  | 'adjustment-history'
  // Healthcare Specialties - Dermatology
  | 'dermatology-stats'
  | 'skin-condition-tracker'
  | 'biopsy-tracker'
  // Healthcare Specialties - Pediatrics
  | 'pediatrics-stats'
  | 'growth-chart'
  | 'vaccination-schedule'
  // Healthcare Specialties - Mental Health
  | 'mental-health-stats'
  | 'therapy-session-notes'
  | 'mood-tracker'
  // Healthcare Specialties - Radiology
  | 'radiology-stats'
  | 'imaging-queue'
  | 'scan-viewer'
  // Healthcare Specialties - Home Care
  | 'home-care-stats'
  | 'visit-schedule-map'
  | 'caregiver-assignment'
  // Healthcare Specialties - Lab/Diagnostics
  | 'lab-stats'
  | 'lab-results'
  | 'test-order-form'
  // Fitness
  | 'membership-plans'
  | 'class-grid'
  | 'class-schedule'
  | 'class-detail'
  | 'class-filters'
  | 'book-class-form'
  | 'trainer-grid'
  | 'trainer-profile'
  | 'workout-stats'
  | 'workout-list'
  | 'workout-form'
  | 'progress-charts'
  | 'progress-log'
  | 'upcoming-classes'
  // Travel
  | 'travel-search'
  | 'destination-grid'
  | 'destination-filters'
  | 'destination-header'
  | 'hotel-grid'
  | 'hotel-filters'
  | 'hotel-detail'
  | 'room-selector'
  | 'flight-search'
  | 'flight-list'
  | 'tour-grid'
  | 'tour-filters'
  | 'tour-detail'
  | 'tour-itinerary'
  | 'tour-booking-form'
  | 'booking-list'
  | 'booking-detail'
  // Event Management
  | 'event-grid'
  | 'event-filters'
  | 'event-header'
  | 'event-schedule'
  | 'speaker-grid'
  | 'ticket-selector'
  | 'venue-info'
  | 'sponsor-grid'
  | 'event-form'
  | 'ticket-list'
  | 'ticket-detail'
  | 'organizer-events'
  | 'event-stats'
  | 'attendee-list'
  | 'attendee-events'
  // Helpdesk
  | 'kb-search'
  | 'article-grid'
  | 'kb-categories'
  | 'kb-sidebar'
  | 'article-list'
  | 'article-detail'
  | 'article-feedback'
  | 'related-articles'
  | 'article-sidebar'
  | 'ticket-form'
  | 'customer-tickets'
  | 'ticket-replies'
  | 'reply-form'
  | 'ticket-queue'
  | 'ticket-filters'
  | 'ticket-header'
  | 'ticket-info'
  | 'ticket-conversation'
  | 'agent-reply-form'
  | 'article-form'
  // Marketplace
  | 'vendor-grid'
  | 'category-header'
  | 'vendor-card'
  | 'vendor-header'
  | 'vendor-signup'
  | 'seller-orders'
  | 'sales-chart'
  | 'earnings-summary'
  | 'transaction-list'
  // Portfolio/Agency
  | 'cta-section'
  | 'client-logos'
  | 'testimonial-slider'
  | 'page-header'
  | 'work-filters'
  | 'project-hero'
  | 'project-content'
  | 'project-gallery'
  | 'project-testimonial'
  | 'service-list'
  | 'process-section'
  | 'service-header'
  | 'service-content'
  | 'service-features'
  | 'service-cta'
  | 'about-story'
  | 'stats-section'
  | 'team-grid'
  | 'team-member-profile'
  | 'values-section'
  | 'contact-info'
  | 'map-section'
  | 'inquiry-list'
  // Forum/Community
  | 'forum-sidebar'
  | 'announcement-list'
  | 'category-list'
  | 'topic-list'
  | 'forum-header'
  | 'subforum-list'
  | 'topic-header'
  | 'post-list'
  | 'topic-form'
  | 'search-filters'
  | 'search-results'
  | 'member-search'
  | 'member-grid'
  | 'profile-stats'
  | 'badge-list'
  // Banking/Finance
  | 'account-balance-cards'
  | 'account-list'
  | 'account-detail'
  | 'transaction-list'
  | 'transaction-table'
  | 'transaction-filters'
  | 'transfer-form'
  | 'transfer-history'
  | 'beneficiary-list'
  | 'card-list'
  | 'card-detail'
  | 'bill-list'
  | 'bill-payment-form'
  | 'budget-overview'
  | 'budget-categories'
  | 'budget-form'
  | 'spending-chart'
  // Insurance
  | 'insurance-stats'
  | 'policy-list'
  | 'policy-table'
  | 'policy-detail'
  | 'policy-filters'
  | 'policy-form'
  | 'claims-list'
  | 'claims-table'
  | 'claims-stats'
  | 'claim-detail'
  | 'claim-timeline'
  | 'claim-form'
  | 'quote-list'
  | 'quote-wizard'
  | 'customer-profile'
  | 'document-list'
  | 'payment-table'
  // Logistics/Shipping
  | 'logistics-stats'
  | 'shipment-map'
  | 'shipment-list'
  | 'shipment-table'
  | 'shipment-filters'
  | 'shipment-detail'
  | 'shipment-timeline'
  | 'shipment-form'
  | 'driver-list'
  | 'driver-profile'
  | 'driver-form'
  | 'vehicle-list'
  | 'vehicle-detail'
  | 'route-list'
  | 'route-planner'
  | 'delivery-tracker'
  | 'carrier-list'
  // Music Streaming
  | 'music-player'
  | 'now-playing'
  | 'playlist-grid'
  | 'playlist-detail'
  | 'playlist-form'
  | 'album-grid'
  | 'album-detail'
  | 'artist-grid'
  | 'artist-profile'
  | 'track-list'
  | 'search-results-music'
  | 'genre-grid'
  | 'library-tabs'
  | 'queue-list'
  // Video Streaming
  | 'video-player'
  | 'video-grid'
  | 'video-card'
  | 'video-detail'
  | 'channel-header'
  | 'channel-grid'
  | 'channel-tabs'
  | 'video-upload-form'
  | 'video-comments'
  | 'video-recommendations'
  | 'subscription-list'
  | 'watch-history'
  | 'trending-videos'
  // Podcast
  | 'podcast-player'
  | 'show-grid'
  | 'show-detail'
  | 'episode-list'
  | 'episode-card'
  | 'episode-player'
  | 'podcast-search'
  | 'category-pills'
  | 'listening-history'
  | 'podcast-subscriptions'
  | 'episode-queue'
  | 'show-form'
  // Dating
  | 'dating-profile'
  | 'profile-editor'
  | 'photo-gallery'
  | 'swipe-cards'
  | 'match-list'
  | 'match-card'
  | 'chat-list-dating'
  | 'chat-window-dating'
  | 'discovery-filters'
  | 'preferences-form'
  | 'profile-preview'
  | 'icebreakers'
  // Freelance
  | 'freelance-stats'
  | 'project-grid-freelance'
  | 'project-filters'
  | 'project-detail-freelance'
  | 'project-form-freelance'
  | 'proposal-form'
  | 'proposal-list'
  | 'contract-detail'
  | 'contract-form'
  | 'milestone-list'
  | 'time-tracker'
  | 'invoice-list-freelance'
  | 'freelancer-profile'
  | 'client-profile-freelance'
  | 'skill-list'
  // Auction
  | 'auction-grid'
  | 'auction-filters'
  | 'auction-detail'
  | 'bid-form'
  | 'bid-history'
  | 'auction-timer'
  | 'auction-form'
  | 'my-bids'
  | 'won-auctions'
  | 'seller-auctions'
  | 'watchlist'
  | 'live-auction'
  // Crowdfunding
  | 'campaign-grid'
  | 'campaign-filters'
  | 'campaign-header'
  | 'campaign-story'
  | 'reward-tiers'
  | 'backer-list'
  | 'funding-progress'
  | 'campaign-updates'
  | 'pledge-form'
  | 'campaign-form'
  | 'my-campaigns'
  | 'backed-projects'
  | 'campaign-stats'
  // News/Magazine
  | 'featured-article'
  | 'article-grid'
  | 'article-content'
  | 'author-card'
  | 'related-articles'
  | 'category-header'
  | 'author-profile'
  // Recipe
  | 'featured-recipes'
  | 'recipe-grid'
  | 'recipe-header'
  | 'ingredient-list'
  | 'recipe-steps'
  | 'nutrition-info'
  | 'review-list-recipe'
  | 'recipe-form'
  | 'meal-planner'
  | 'shopping-list'
  // Pet/Veterinary
  | 'pet-cards'
  | 'pet-grid'
  | 'pet-profile'
  | 'pet-form'
  | 'vaccination-list'
  | 'vaccination-reminders'
  | 'medical-history-pet'
  | 'vet-search'
  | 'vet-list'
  // Legal/Law Firm
  | 'case-stats'
  | 'case-list'
  | 'deadline-list'
  | 'case-table'
  | 'case-filters'
  | 'case-header'
  | 'case-timeline'
  | 'time-entry-list'
  | 'client-profile-legal'
  | 'billing-summary'
  | 'invoice-list-legal'
  // Subscription Billing
  | 'mrr-stats'
  | 'subscriber-chart'
  | 'subscription-activity'
  | 'plan-grid'
  | 'plan-form'
  | 'subscriber-table'
  | 'subscriber-profile'
  | 'subscription-history'
  | 'invoice-list-subscription'
  | 'invoice-table'
  | 'revenue-chart'
  | 'churn-metrics'
  | 'plan-distribution'
  // Survey/Poll
  | 'survey-stats'
  | 'survey-list'
  | 'survey-filters'
  | 'survey-grid'
  | 'survey-builder'
  | 'survey-header'
  | 'question-list'
  | 'survey-settings'
  | 'survey-editor'
  | 'response-table'
  | 'response-summary'
  | 'survey-form'
  | 'analytics-overview'
  | 'question-analytics'
  | 'response-chart'
  // Referral/Affiliate
  | 'affiliate-stats'
  | 'earnings-chart'
  | 'referral-list'
  | 'referral-filters'
  | 'referral-table'
  | 'commission-summary'
  | 'commission-table'
  | 'link-generator'
  | 'link-list'
  | 'payout-balance'
  | 'payout-history'
  | 'payout-request'
  | 'campaign-list-referral'
  | 'campaign-detail-referral'
  | 'campaign-stats-referral'
  | 'affiliate-leaderboard'
  // Church/Religious
  | 'church-stats'
  | 'donation-summary'
  | 'member-filters'
  | 'member-table'
  | 'member-profile'
  | 'member-groups'
  | 'member-donations'
  | 'event-calendar'
  | 'event-detail-church'
  | 'event-registrations'
  | 'donation-stats'
  | 'donation-table'
  | 'donation-form'
  | 'group-grid'
  | 'group-detail'
  | 'group-members'
  | 'sermon-list'
  | 'sermon-player'
  | 'sermon-notes'
  | 'prayer-list'
  | 'prayer-form'
  // School Admin
  | 'school-stats'
  | 'attendance-summary'
  | 'school-events'
  | 'student-filters'
  | 'student-table'
  | 'student-profile'
  | 'student-grades'
  | 'student-attendance'
  | 'teacher-table'
  | 'teacher-profile'
  | 'teacher-classes'
  | 'class-grid'
  | 'class-header'
  | 'class-students'
  | 'assignment-list'
  | 'grade-filters'
  | 'gradebook'
  | 'attendance-date-picker'
  | 'attendance-form'
  | 'schedule-calendar'
  | 'report-card-generator'
  // Warehouse/3PL
  | 'warehouse-stats'
  | 'order-list-warehouse'
  | 'low-stock-alerts'
  | 'inventory-filters'
  | 'inventory-table'
  | 'product-detail-warehouse'
  | 'stock-levels'
  | 'movement-history'
  | 'order-filters'
  | 'order-table'
  | 'order-header'
  | 'order-items'
  | 'pick-list'
  | 'receiving-list'
  | 'receiving-form'
  | 'shipment-filters-warehouse'
  | 'shipment-table-warehouse'
  | 'shipment-detail-warehouse'
  | 'tracking-info'
  | 'location-map'
  | 'location-list'
  | 'pick-queue'
  | 'inventory-report'
  | 'fulfillment-report'
  // Nonprofit/Charity
  | 'nonprofit-stats'
  | 'donation-chart'
  | 'campaign-list-nonprofit'
  | 'donation-filters-nonprofit'
  | 'donation-table-nonprofit'
  | 'donor-table'
  | 'donor-profile'
  | 'donor-history'
  | 'campaign-grid-nonprofit'
  | 'campaign-header-nonprofit'
  | 'campaign-progress-nonprofit'
  | 'campaign-donors'
  | 'volunteer-table'
  | 'donate-form'
  // Membership/Club
  | 'membership-stats'
  | 'member-growth-chart'
  | 'renewal-list'
  | 'member-filters-club'
  | 'member-table-club'
  | 'member-profile-club'
  | 'member-payments'
  | 'member-activity'
  | 'membership-plan-grid'
  | 'payment-table-club'
  | 'event-calendar-club'
  | 'join-form'
  // Coworking Space
  | 'coworking-stats'
  | 'occupancy-chart'
  | 'booking-list-coworking'
  | 'space-grid'
  | 'space-detail'
  | 'space-calendar'
  | 'booking-calendar-coworking'
  | 'booking-form-coworking'
  | 'member-table-coworking'
  | 'member-profile-coworking'
  | 'member-bookings'
  | 'coworking-plan-grid'
  | 'space-browser'
  // Photography/Studio
  | 'photo-stats'
  | 'session-list'
  | 'gallery-preview'
  | 'booking-calendar-photo'
  | 'session-detail'
  | 'session-gallery'
  | 'gallery-grid-photo'
  | 'gallery-viewer'
  | 'client-table-photo'
  | 'client-profile-photo'
  | 'client-sessions'
  | 'client-galleries'
  | 'package-grid-photo'
  | 'booking-wizard-photo'
  // Wedding Planning
  | 'wedding-countdown'
  | 'wedding-stats'
  | 'task-list-wedding'
  | 'guest-stats'
  | 'guest-table'
  | 'guest-form'
  | 'vendor-grid-wedding'
  | 'vendor-detail-wedding'
  | 'task-board-wedding'
  | 'budget-summary-wedding'
  | 'budget-table-wedding'
  | 'wedding-timeline'
  | 'seating-chart'
  | 'rsvp-form'
  // Car Rental
  | 'rental-stats'
  | 'fleet-status'
  | 'active-rentals'
  | 'vehicle-filters'
  | 'vehicle-grid-rental'
  | 'vehicle-detail-rental'
  | 'vehicle-history'
  | 'booking-filters-rental'
  | 'booking-table-rental'
  | 'booking-detail-rental'
  | 'customer-table-rental'
  | 'customer-profile-rental'
  | 'customer-rentals'
  | 'location-grid-rental'
  | 'rental-search'
  | 'available-vehicles'
  // Hotel Management
  | 'hotel-stats'
  | 'room-status-grid'
  | 'arrivals-list'
  | 'room-filters-hotel'
  | 'room-grid-hotel'
  | 'room-detail-hotel'
  | 'room-calendar'
  | 'reservation-calendar'
  | 'reservation-form-hotel'
  | 'reservation-detail-hotel'
  | 'guest-table-hotel'
  | 'guest-profile-hotel'
  | 'guest-reservations'
  | 'housekeeping-board'
  | 'hotel-booking-search'
  | 'available-rooms'
  // Spa/Wellness
  | 'spa-stats'
  | 'spa-schedule'
  | 'therapist-availability'
  | 'appointment-calendar-spa'
  | 'appointment-form-spa'
  | 'service-grid-spa'
  | 'therapist-grid-spa'
  | 'therapist-profile-spa'
  | 'therapist-schedule'
  | 'client-table-spa'
  | 'client-profile-spa'
  | 'client-history-spa'
  | 'package-grid-spa'
  | 'service-menu'
  | 'spa-booking-form'
  // Dental/Clinic
  | 'dental-stats'
  | 'appointment-list-dental'
  | 'dentist-schedule-overview'
  | 'appointment-calendar-dental'
  | 'appointment-form-dental'
  | 'patient-filters'
  | 'patient-table-dental'
  | 'patient-profile-dental'
  | 'dental-chart'
  | 'treatment-history'
  | 'treatment-catalog'
  | 'dentist-grid'
  | 'dentist-profile'
  | 'dentist-schedule'
  | 'billing-stats-dental'
  | 'invoice-table-dental'
  | 'online-booking-dental'
  // Tutoring
  | 'tutoring-stats'
  | 'session-list-tutoring'
  | 'tutor-availability-overview'
  | 'session-calendar'
  | 'session-detail-tutoring'
  | 'tutor-filters'
  | 'tutor-grid'
  | 'tutor-profile'
  | 'tutor-reviews'
  | 'tutor-schedule'
  | 'student-table-tutoring'
  | 'student-profile-tutoring'
  | 'student-progress'
  | 'subject-grid'
  | 'tutor-search'
  | 'tutor-results'
  // Music School
  | 'music-school-stats'
  | 'lesson-list-music'
  | 'recital-list'
  | 'student-table-music'
  | 'student-profile-music'
  | 'student-lessons'
  | 'student-progress-music'
  | 'instructor-grid-music'
  | 'instructor-profile-music'
  | 'instructor-schedule-music'
  | 'lesson-calendar-music'
  | 'instrument-grid'
  | 'recital-list-full'
  | 'recital-detail'
  | 'recital-performers'
  | 'enrollment-form-music'
  // Dance Studio
  | 'dance-studio-stats'
  | 'class-list-dance'
  | 'performance-list'
  | 'class-filters-dance'
  | 'class-grid-dance'
  | 'class-detail-dance'
  | 'class-roster'
  | 'schedule-calendar-dance'
  | 'student-table-dance'
  | 'student-profile-dance'
  | 'student-enrollments'
  | 'instructor-grid-dance'
  | 'instructor-profile-dance'
  | 'instructor-classes-dance'
  | 'performance-list-full'
  | 'class-browser-dance'
  | 'registration-form-dance'
  // Art Gallery
  | 'gallery-stats'
  | 'exhibition-list'
  | 'sales-list'
  | 'artwork-filters'
  | 'artwork-grid'
  | 'artwork-detail'
  | 'artist-grid-gallery'
  | 'artist-profile-gallery'
  | 'artist-works'
  | 'exhibition-grid'
  | 'exhibition-header'
  | 'exhibition-artworks'
  | 'sales-stats-gallery'
  | 'sales-table'
  | 'collection-grid'
  | 'public-gallery'
  // Library
  | 'library-stats'
  | 'overdue-loans'
  | 'library-activity'
  | 'book-search'
  | 'book-grid'
  | 'book-detail-library'
  | 'book-copies'
  | 'member-table-library'
  | 'member-profile-library'
  | 'member-loans'
  | 'loan-filters'
  | 'loan-table'
  | 'checkout-form-library'
  | 'return-form'
  | 'reservation-table'
  | 'public-catalog'
  // Laundry Service
  | 'laundry-stats'
  | 'order-list-laundry'
  | 'delivery-schedule'
  | 'order-filters-laundry'
  | 'order-table-laundry'
  | 'order-detail-laundry'
  | 'order-timeline-laundry'
  | 'order-form-laundry'
  | 'pickup-list'
  | 'delivery-list-laundry'
  | 'customer-table-laundry'
  | 'customer-profile-laundry'
  | 'customer-orders-laundry'
  | 'pricing-table-laundry'
  | 'booking-form-laundry'
  // Food Truck
  | 'foodtruck-stats'
  | 'active-orders-foodtruck'
  | 'today-location'
  | 'menu-grid-foodtruck'
  | 'menu-item-detail-foodtruck'
  | 'menu-item-form'
  | 'order-queue-foodtruck'
  | 'order-detail-foodtruck'
  | 'schedule-calendar-foodtruck'
  | 'location-list-foodtruck'
  | 'truck-location'
  | 'public-menu-foodtruck'
  | 'order-form-foodtruck'
  // Catering
  | 'catering-stats'
  | 'event-list-catering'
  | 'quote-list-catering'
  | 'event-calendar-catering'
  | 'event-detail-catering'
  | 'event-menu'
  | 'event-form-catering'
  | 'menu-grid-catering'
  | 'menu-detail-catering'
  | 'menu-items-catering'
  | 'quote-table-catering'
  | 'quote-detail-catering'
  | 'order-table-catering'
  | 'client-table-catering'
  | 'client-profile-catering'
  | 'client-events'
  | 'quote-request-form'
  // Interior Design
  | 'design-stats'
  | 'project-list-design'
  | 'quote-list-design'
  | 'project-filters-design'
  | 'project-grid-design'
  | 'project-header-design'
  | 'project-rooms'
  | 'project-products'
  | 'project-form-design'
  | 'client-table-design'
  | 'client-profile-design'
  | 'client-projects-design'
  | 'product-filters-design'
  | 'product-grid-design'
  | 'mood-board-grid'
  | 'mood-board-viewer'
  | 'quote-table-design'
  | 'public-portfolio-design'
  // Consulting
  | 'consulting-stats'
  | 'project-list-consulting'
  | 'recent-time-entries'
  | 'client-table-consulting'
  | 'client-header-consulting'
  | 'client-projects-consulting'
  | 'client-invoices'
  | 'client-form-consulting'
  | 'project-filters-consulting'
  | 'project-table-consulting'
  | 'project-header-consulting'
  | 'project-timeline-consulting'
  | 'project-time-entries'
  | 'time-tracker-consulting'
  | 'time-entry-table'
  | 'invoice-stats-consulting'
  | 'invoice-table-consulting'
  | 'invoice-detail-consulting'
  | 'invoice-form-consulting'
  | 'revenue-report-consulting'
  | 'utilization-report'
  // Veterinary Clinic
  | 'vet-clinic-stats'
  | 'appointment-list-vet'
  | 'vet-schedule-overview'
  | 'appointment-calendar-vet'
  | 'appointment-form-vet'
  | 'appointment-detail-vet'
  | 'patient-filters-vet'
  | 'patient-table-vet'
  | 'patient-profile-vet'
  | 'medical-records-vet'
  | 'vaccination-records'
  | 'owner-table'
  | 'owner-profile'
  | 'owner-pets'
  | 'vet-grid'
  | 'vet-profile'
  | 'vet-schedule'
  | 'billing-stats-vet'
  | 'invoice-table-vet'
  | 'online-booking-vet'
  // Hair Salon/Barbershop
  | 'salon-stats'
  | 'today-appointments'
  | 'stylist-availability'
  | 'appointment-calendar-salon'
  | 'appointment-form-salon'
  | 'appointment-detail-salon'
  | 'stylist-grid'
  | 'stylist-profile'
  | 'stylist-schedule'
  | 'client-table-salon'
  | 'client-profile-salon'
  | 'client-history-salon'
  | 'service-menu-salon'
  | 'product-grid-salon'
  | 'public-booking-salon'
  // Pet Boarding/Daycare
  | 'petboarding-stats'
  | 'current-pets'
  | 'feeding-schedule'
  | 'calendar-petboarding'
  | 'reservation-detail'
  | 'pet-info-card'
  | 'pet-table'
  | 'pet-profile-boarding'
  | 'pet-medical-info'
  | 'pet-activities'
  | 'pet-form-boarding'
  | 'reservation-filters'
  | 'reservation-table-boarding'
  | 'staff-grid-boarding'
  | 'staff-schedule-boarding'
  | 'booking-wizard-boarding'
  // Florist/Flower Shop
  | 'florist-stats'
  | 'pending-orders-florist'
  | 'arrangement-list'
  | 'arrangement-grid'
  | 'arrangement-detail'
  | 'arrangement-form'
  | 'order-filters-florist'
  | 'order-table-florist'
  | 'order-detail-florist'
  | 'order-form-florist'
  | 'customer-table-florist'
  | 'customer-profile-florist'
  | 'customer-orders-florist'
  | 'delivery-schedule-florist'
  | 'delivery-list-florist'
  | 'inventory-table-florist'
  | 'public-catalog-florist'
  | 'custom-order-form-florist'
  // Bakery
  | 'bakery-stats'
  | 'todays-orders'
  | 'custom-order-list'
  | 'product-grid-bakery'
  | 'product-detail-bakery'
  | 'product-form-bakery'
  | 'order-filters-bakery'
  | 'order-table-bakery'
  | 'order-detail-bakery'
  | 'order-form-bakery'
  | 'custom-order-detail'
  | 'custom-order-form'
  | 'customer-table-bakery'
  | 'customer-profile-bakery'
  | 'inventory-table-bakery'
  | 'ingredient-usage'
  | 'public-menu-bakery'
  | 'order-form-public-bakery'
  // Print Shop
  | 'printshop-stats'
  | 'active-jobs'
  | 'quote-requests'
  | 'job-filters'
  | 'job-table'
  | 'job-detail'
  | 'job-timeline'
  | 'job-form'
  | 'customer-table-printshop'
  | 'customer-profile-printshop'
  | 'customer-jobs'
  | 'product-grid-printshop'
  | 'product-detail-printshop'
  | 'equipment-grid'
  | 'equipment-detail'
  | 'quote-table-printshop'
  | 'quote-form'
  | 'public-products-printshop'
  | 'quote-request-form-printshop'
  // Auto Repair
  | 'autorepair-stats'
  | 'active-work-orders'
  | 'service-bay-status'
  | 'work-order-filters'
  | 'work-order-table'
  | 'work-order-detail'
  | 'work-order-timeline'
  | 'work-order-form'
  | 'vehicle-table'
  | 'vehicle-profile'
  | 'vehicle-history'
  | 'vehicle-form'
  | 'customer-table-autorepair'
  | 'customer-profile-autorepair'
  | 'customer-vehicles'
  | 'technician-grid'
  | 'technician-profile'
  | 'technician-schedule'
  | 'parts-inventory'
  | 'appointment-form-autorepair'
  // House Cleaning Service
  | 'cleaning-stats'
  | 'today-schedule'
  | 'cleaner-availability'
  | 'booking-calendar-cleaning'
  | 'booking-detail-cleaning'
  | 'booking-form-cleaning'
  | 'customer-table-cleaning'
  | 'customer-profile-cleaning'
  | 'customer-bookings-cleaning'
  | 'recurring-schedule'
  | 'cleaner-grid'
  | 'cleaner-profile'
  | 'cleaner-schedule'
  | 'service-grid-cleaning'
  | 'booking-form-public-cleaning'
  // Moving Company
  | 'moving-stats'
  | 'upcoming-moves'
  | 'crew-availability'
  | 'estimate-filters'
  | 'estimate-table'
  | 'estimate-detail'
  | 'estimate-form'
  | 'move-calendar'
  | 'move-detail'
  | 'crew-assignment'
  | 'customer-table-moving'
  | 'customer-profile-moving'
  | 'customer-moves'
  | 'truck-grid'
  | 'truck-detail'
  | 'truck-schedule'
  | 'inventory-list-moving'
  | 'estimate-request-form'
  // Self Storage
  | 'storage-stats'
  | 'occupancy-overview'
  | 'expiring-rentals'
  | 'unit-filters'
  | 'unit-grid'
  | 'unit-detail'
  | 'unit-availability'
  | 'rental-filters'
  | 'rental-table'
  | 'rental-detail'
  | 'rental-form'
  | 'customer-table-storage'
  | 'customer-profile-storage'
  | 'customer-units'
  | 'payment-table-storage'
  | 'unit-browser-public'
  | 'rental-form-public'
  // Law Firm
  | 'lawfirm-stats'
  | 'case-list-active'
  | 'deadline-list-lawfirm'
  | 'case-filters-lawfirm'
  | 'case-table-lawfirm'
  | 'case-header-lawfirm'
  | 'case-timeline-lawfirm'
  | 'case-documents'
  | 'case-time-entries'
  | 'client-table-lawfirm'
  | 'client-profile-lawfirm'
  | 'client-cases'
  | 'client-billing'
  | 'matter-table'
  | 'matter-detail'
  | 'attorney-grid'
  | 'attorney-profile'
  | 'attorney-cases'
  | 'time-entry-table-lawfirm'
  | 'time-entry-form'
  | 'billing-overview'
  | 'invoice-table-lawfirm'
  // Accounting Firm
  | 'accounting-stats'
  | 'deadline-list-accounting'
  | 'pending-items'
  | 'client-table-accounting'
  | 'client-profile-accounting'
  | 'client-services'
  | 'client-documents'
  | 'client-form-accounting'
  | 'tax-return-filters'
  | 'tax-return-table'
  | 'tax-return-detail'
  | 'tax-return-form'
  | 'payroll-client-list'
  | 'payroll-detail'
  | 'engagement-table'
  | 'engagement-detail'
  | 'document-list-accounting'
  | 'document-upload'
  | 'calendar-accounting'
  | 'deadline-form'
  // Travel Agency
  | 'travelagency-stats'
  | 'booking-list-travel'
  | 'upcoming-departures'
  | 'trip-filters'
  | 'trip-table'
  | 'trip-detail'
  | 'trip-itinerary'
  | 'trip-form'
  | 'booking-filters-travel'
  | 'booking-table-travel'
  | 'booking-detail-travel'
  | 'booking-form-travel'
  | 'client-table-travel'
  | 'client-profile-travel'
  | 'client-trips'
  | 'supplier-table'
  | 'supplier-profile'
  | 'trip-search-public'
  | 'trip-inquiry-form'
  // Recruitment/HR Agency
  | 'recruitment-stats'
  | 'active-jobs-recruitment'
  | 'placement-pipeline'
  | 'candidate-filters'
  | 'candidate-table'
  | 'candidate-profile'
  | 'candidate-resume'
  | 'candidate-applications'
  | 'candidate-form'
  | 'job-filters-recruitment'
  | 'job-table-recruitment'
  | 'job-detail-recruitment'
  | 'job-candidates'
  | 'client-table-recruitment'
  | 'client-profile-recruitment'
  | 'client-jobs'
  | 'placement-table'
  | 'application-table'
  | 'interview-schedule'
  | 'public-jobs-recruitment'
  | 'apply-form'
  // Marketing Agency
  | 'marketing-stats'
  | 'campaign-list-active'
  | 'task-list-marketing'
  | 'campaign-filters-marketing'
  | 'campaign-grid-marketing'
  | 'campaign-header-marketing'
  | 'campaign-performance'
  | 'campaign-assets'
  | 'campaign-form-marketing'
  | 'client-table-marketing'
  | 'client-header-marketing'
  | 'client-campaigns'
  | 'client-performance-marketing'
  | 'project-board-marketing'
  | 'project-header-marketing'
  | 'project-tasks-marketing'
  | 'asset-browser'
  | 'report-generator'
  // Event Venue
  | 'venue-stats'
  | 'event-list-upcoming'
  | 'inquiry-list'
  | 'venue-calendar'
  | 'booking-filters-venue'
  | 'booking-table-venue'
  | 'booking-header-venue'
  | 'event-details-venue'
  | 'booking-form-venue'
  | 'venue-grid'
  | 'venue-detail'
  | 'venue-bookings'
  | 'client-table-venue'
  | 'client-profile-venue'
  | 'client-bookings-venue'
  | 'package-grid-venue'
  | 'staff-grid-venue'
  | 'public-venue-browser'
  // Cinema/Theater
  | 'cinema-stats'
  | 'screening-list-today'
  | 'ticket-sales-recent'
  | 'movie-filters'
  | 'movie-grid-admin'
  | 'movie-header'
  | 'movie-screenings'
  | 'movie-form'
  | 'screening-calendar'
  | 'screening-detail'
  | 'seat-map-admin'
  | 'theater-grid'
  | 'theater-detail'
  | 'theater-layout'
  | 'ticket-stats'
  | 'ticket-table'
  | 'concession-grid'
  | 'public-movie-grid'
  | 'public-movie-detail'
  | 'public-showtimes'
  | 'seat-selector'
  | 'ticket-checkout'
  // Parking Management
  | 'parking-stats'
  | 'occupancy-overview-parking'
  | 'session-list-active'
  | 'live-parking-map'
  | 'reservation-filters-parking'
  | 'reservation-table-parking'
  | 'reservation-detail-parking'
  | 'lot-grid'
  | 'lot-header'
  | 'lot-space-map'
  | 'lot-stats'
  | 'customer-table-parking'
  | 'customer-profile-parking'
  | 'customer-parking-history'
  | 'payment-stats-parking'
  | 'payment-table-parking'
  | 'parking-finder'
  | 'public-reservation-parking'
  // Security Company
  | 'security-stats'
  | 'guard-list-active'
  | 'incident-list-recent'
  | 'guard-filters'
  | 'guard-table'
  | 'guard-profile'
  | 'guard-schedule'
  | 'guard-incidents'
  | 'guard-form'
  | 'site-grid'
  | 'site-header'
  | 'site-patrol-map'
  | 'site-schedule'
  | 'patrol-live-view'
  | 'patrol-history'
  | 'patrol-detail'
  | 'incident-filters'
  | 'incident-table'
  | 'incident-detail'
  | 'incident-form'
  | 'schedule-calendar-security'
  | 'client-table-security'
  | 'client-profile-security'
  | 'client-sites'
  // Additional missing component types from blueprints
  // Arcade
  | 'arcade-stats'
  | 'party-list-today'
  | 'game-list-popular'
  | 'game-grid-arcade'
  | 'game-detail-arcade'
  | 'game-stats-arcade'
  | 'card-table-arcade'
  | 'card-detail-arcade'
  | 'card-history-arcade'
  | 'party-calendar-arcade'
  | 'party-detail-arcade'
  | 'prize-grid'
  | 'customer-table-arcade'
  | 'public-party-booking-arcade'
  // Accounting
  | 'accounting-stats-extra'
  | 'task-list-accounting'
  | 'client-filters-accounting'
  | 'client-engagements'
  | 'client-documents-accounting'
  | 'engagement-filters'
  | 'engagement-header'
  | 'engagement-tasks'
  | 'task-board-accounting'
  | 'document-browser-accounting'
  | 'billing-stats-accounting'
  | 'invoice-table-accounting'
  | 'client-portal-accounting'
  // Auction
  | 'featured-auctions'
  | 'my-bids-list'
  | 'listing-form'
  // Auto Repair
  | 'repair-stats'
  | 'ticket-list-active'
  | 'technician-workload'
  | 'ticket-filters-repair'
  | 'ticket-table-repair'
  | 'ticket-header-repair'
  | 'ticket-services'
  | 'ticket-parts'
  | 'ticket-form-repair'
  | 'estimate-table-repair'
  | 'estimate-detail-repair'
  | 'vehicle-table-repair'
  | 'vehicle-service-history'
  | 'customer-table-repair'
  | 'customer-profile-repair'
  | 'parts-table'
  | 'service-booking-repair'
  // Bakery
  | 'order-list-bakery'
  | 'custom-order-table'
  | 'public-shop-bakery'
  | 'custom-cake-form'
  // Brewery
  | 'brewery-stats'
  | 'tour-list-today'
  | 'order-list-recent-brewery'
  | 'product-grid-brewery'
  | 'product-detail-brewery'
  | 'tour-calendar-brewery'
  | 'tour-detail-brewery'
  | 'tasting-table'
  | 'event-calendar-brewery'
  | 'member-table-brewery'
  | 'member-profile-brewery'
  | 'member-orders-brewery'
  | 'public-visit-brewery'
  | 'public-shop-brewery'
  // Campground
  | 'campground-stats'
  | 'site-availability-overview'
  | 'arrivals-today-campground'
  | 'site-map-campground'
  | 'site-detail-campground'
  | 'site-calendar-campground'
  | 'reservation-filters-campground'
  | 'reservation-table-campground'
  | 'reservation-detail-campground'
  | 'reservation-form-campground'
  | 'guest-table-campground'
  | 'guest-profile-campground'
  | 'guest-reservations-campground'
  | 'activity-calendar-campground'
  | 'rate-table-campground'
  | 'public-booking-campground'
  // Church
  | 'event-list'
  | 'event-detail'
  // Cleaning
  | 'booking-list-cleaning'
  | 'team-schedule-cleaning'
  | 'customer-properties'
  | 'invoice-table-cleaning'
  | 'public-booking-cleaning'
  // Crossfit
  | 'crossfit-stats'
  | 'wod-today'
  | 'result-list-recent'
  | 'wod-calendar'
  | 'wod-detail'
  | 'wod-results'
  | 'wod-form'
  | 'athlete-table'
  | 'athlete-profile'
  | 'athlete-prs'
  | 'athlete-history'
  | 'leaderboard-crossfit'
  | 'competition-grid'
  | 'competition-detail'
  | 'competition-results'
  | 'public-wod-today'
  // Daycare
  | 'daycare-stats'
  | 'activity-list-today'
  | 'attendance-today'
  | 'child-grid'
  | 'child-profile'
  | 'child-attendance-history'
  | 'activity-calendar-daycare'
  | 'parent-table'
  | 'staff-table-daycare'
  | 'public-enrollment-daycare'
  // Driving School
  | 'driving-stats'
  | 'lesson-list-today-driving'
  | 'test-list-upcoming'
  | 'student-table-driving'
  | 'student-profile-driving'
  | 'student-progress-driving'
  | 'lesson-calendar-driving'
  | 'instructor-grid-driving'
  | 'vehicle-grid-driving'
  | 'vehicle-grid'
  | 'test-table-driving'
  | 'package-grid-driving'
  | 'public-enrollment-driving'
  // Escape Room
  | 'escaperoom-stats'
  | 'booking-list-today-escape'
  | 'room-status-overview'
  | 'room-grid-escape'
  | 'room-detail-escape'
  | 'room-schedule-escape'
  | 'booking-calendar-escape'
  | 'booking-detail-escape'
  | 'customer-table-escape'
  | 'session-table-escape'
  | 'session-detail-escape'
  | 'leaderboard-escape'
  | 'public-rooms-escape'
  | 'public-booking-escape'
  // Flight School
  | 'flight-stats'
  | 'flight-list-today'
  | 'aircraft-status-overview'
  | 'student-table-flight'
  | 'student-profile-flight'
  | 'student-logbook'
  | 'student-certifications'
  | 'flight-calendar'
  | 'flight-detail'
  | 'aircraft-grid'
  | 'aircraft-detail'
  | 'aircraft-maintenance-log'
  | 'instructor-grid-flight'
  | 'ground-school-table'
  | 'public-enrollment-flight'
  // Florist
  | 'florist-stats-extra'
  | 'order-list-florist'
  | 'arrangement-list'
  | 'arrangement-list-recent'
  | 'arrangement-filters'
  | 'arrangement-table'
  | 'arrangement-header'
  | 'arrangement-services'
  | 'arrangement-billing'
  | 'event-table-florist'
  | 'delivery-calendar-florist'
  | 'public-shop-florist'
  // Funeral Home
  | 'funeral-stats'
  | 'service-list-upcoming-funeral'
  | 'service-calendar-funeral'
  | 'preplan-table'
  | 'obituary-list'
  | 'obituary-detail'
  | 'staff-grid-funeral'
  | 'public-memorial'
  // Golf
  | 'golf-stats'
  | 'tee-time-list-today'
  | 'member-handicap'
  | 'tee-time-calendar'
  | 'tee-time-detail'
  | 'member-table-golf'
  | 'member-profile-golf'
  | 'proshop-grid'
  | 'tournament-grid'
  | 'tournament-detail'
  | 'tournament-leaderboard'
  | 'tournament-list-upcoming'
  | 'public-booking-golf'
  // HVAC
  | 'hvac-stats'
  | 'service-call-list-today'
  | 'contract-renewal-due'
  | 'service-call-table'
  | 'service-call-detail'
  | 'installation-table'
  | 'installation-detail'
  | 'contract-table-hvac'
  | 'equipment-table-hvac'
  | 'customer-table-hvac'
  | 'customer-detail-hvac'
  | 'customer-equipment-hvac'
  | 'public-service-request-hvac'
  // Jeweler
  | 'jeweler-stats'
  | 'repair-list-pending'
  | 'custom-order-list-progress'
  | 'product-grid-jeweler'
  | 'product-detail-jeweler'
  | 'product-filters-jeweler'
  | 'repair-filters'
  | 'repair-table'
  | 'repair-detail'
  | 'repair-form'
  | 'custom-order-table-jeweler'
  | 'custom-order-detail-jeweler'
  | 'customer-table-jeweler'
  | 'appraisal-table'
  | 'public-shop-jeweler'
  // Law Firm Extended
  | 'law-stats'
  | 'case-list-law'
  | 'legal-calendar'
  | 'case-filters-law'
  | 'case-table-law'
  | 'case-header-law'
  | 'case-form-law'
  | 'document-browser-law'
  | 'client-table-law'
  | 'client-profile-law'
  | 'client-invoices-law'
  | 'time-tracker-law'
  | 'billing-stats-law'
  | 'invoice-table-law'
  // Marina
  | 'marina-stats'
  | 'slip-availability-overview'
  | 'arrivals-departures'
  | 'slip-map'
  | 'slip-detail'
  | 'slip-reservations'
  | 'reservation-calendar-marina'
  | 'reservation-detail-marina'
  | 'customer-table-marina'
  | 'customer-profile-marina'
  | 'customer-boats'
  | 'boat-table'
  | 'boat-detail'
  | 'service-grid-marina'
  | 'public-booking-marina'
  // Moving Company Extended
  | 'job-filters-moving'
  | 'job-table-moving'
  | 'job-list-moving'
  | 'job-header-moving'
  | 'job-inventory'
  | 'job-form-moving'
  | 'quote-table-moving'
  | 'quote-detail-moving'
  | 'quote-request-moving'
  | 'customer-jobs-moving'
  | 'crew-grid'
  | 'crew-schedule-moving'
  // Music/Podcast Extended
  | 'recently-played'
  | 'continue-listening'
  | 'featured-albums'
  | 'featured-shows'
  | 'show-header'
  | 'episode-notes'
  | 'trending-episodes'
  // Nursery/Garden Center
  | 'nursery-stats'
  | 'order-list-recent-nursery'
  | 'plant-low-stock'
  | 'plant-grid'
  | 'plant-detail'
  | 'plant-filters'
  | 'plant-form'
  | 'plant-care-info'
  | 'order-filters-nursery'
  | 'order-table-nursery'
  | 'order-detail-nursery'
  | 'customer-table-nursery'
  | 'inventory-table-nursery'
  | 'service-grid-nursery'
  | 'public-catalog-nursery'
  // Optician
  | 'optician-stats'
  | 'appointment-list-today-optician'
  | 'order-list-pending-optician'
  | 'appointment-calendar-optician'
  | 'eyewear-grid'
  | 'eyewear-filters'
  | 'customer-table-optician'
  | 'customer-profile-optician'
  | 'customer-prescriptions-optician'
  | 'customer-orders-optician'
  | 'prescription-form-optician'
  | 'order-filters-optician'
  | 'order-table-optician'
  | 'order-detail-optician'
  | 'public-booking-optician'
  // Pet Boarding Extended
  | 'boarding-stats'
  | 'kennel-status-grid'
  | 'reservation-calendar-boarding'
  | 'reservation-detail-boarding'
  | 'reservation-form-boarding'
  | 'pet-table-boarding'
  | 'pet-activity-log'
  | 'pet-reservation-history'
  | 'owner-table-boarding'
  | 'owner-profile-boarding'
  | 'owner-pets-boarding'
  | 'kennel-grid'
  | 'service-grid-boarding'
  | 'online-booking-boarding'
  // Pharmacy
  | 'pharmacy-stats'
  | 'prescription-list-pending'
  | 'medication-low-stock'
  | 'prescription-filters'
  | 'prescription-table'
  | 'prescription-detail'
  | 'medication-grid'
  | 'medication-search'
  | 'medication-detail'
  | 'medication-inventory'
  | 'customer-table-pharmacy'
  | 'customer-profile-pharmacy'
  | 'customer-prescriptions'
  | 'order-table-pharmacy'
  | 'refill-request-form'
  // Plumbing
  | 'plumbing-stats'
  | 'service-call-list-today-plumbing'
  | 'estimate-list-pending'
  | 'service-call-table-plumbing'
  | 'service-call-detail-plumbing'
  | 'customer-table-plumbing'
  | 'customer-detail-plumbing'
  | 'customer-service-history'
  | 'technician-grid-plumbing'
  | 'job-table-plumbing'
  | 'job-detail-plumbing'
  | 'public-service-request-plumbing'
  // Print Shop Extended
  | 'job-filters-printshop'
  | 'job-table-printshop'
  | 'job-list-printshop'
  | 'job-detail-printshop'
  | 'job-form-printshop'
  | 'job-files'
  | 'quote-table-printshop'
  | 'quote-list-printshop'
  | 'quote-detail-printshop'
  | 'quote-request-printshop'
  | 'invoice-table-printshop'
  // Recruitment Extended
  | 'job-filters-recruitment'
  | 'job-table-recruitment'
  | 'job-detail-recruitment'
  | 'job-header-recruitment'
  | 'job-form-recruitment'
  | 'job-pipeline'
  | 'application-detail'
  | 'application-pipeline'
  | 'interview-calendar'
  | 'interview-list-upcoming'
  | 'public-job-board'
  // Rehab/Physical Therapy
  | 'rehab-stats'
  | 'appointment-list-today-rehab'
  | 'patient-progress-overview'
  | 'appointment-calendar-rehab'
  | 'patient-table-rehab'
  | 'patient-profile-rehab'
  | 'patient-treatment-summary'
  | 'patient-progress-chart'
  | 'treatment-table'
  | 'treatment-detail'
  | 'exercise-grid'
  | 'therapist-grid'
  | 'public-booking-rehab'
  // Self Storage Extended
  | 'unit-filters-storage'
  | 'unit-grid-storage'
  | 'unit-detail-storage'
  | 'unit-rental-history'
  | 'rental-filters-storage'
  | 'rental-table-storage'
  | 'rental-detail-storage'
  | 'rental-form-storage'
  | 'customer-rentals-storage'
  | 'unit-browser'
  | 'overdue-rentals'
  // Senior Care
  | 'senior-stats'
  | 'activity-list-today-senior'
  | 'medication-schedule-today'
  | 'resident-grid'
  | 'resident-profile'
  | 'resident-care-summary'
  | 'medication-table-senior'
  | 'care-plan-table'
  | 'care-plan-detail'
  | 'activity-calendar-senior'
  | 'staff-table-senior'
  | 'family-portal-senior'
  // Ski Resort
  | 'skiresort-stats'
  | 'ticket-sales-today'
  | 'trail-status-overview'
  | 'pass-table'
  | 'trail-map'
  | 'trail-conditions'
  | 'rental-table-ski'
  | 'rental-detail-ski'
  | 'lesson-calendar-ski'
  | 'customer-table-ski'
  | 'ticket-sales-ski'
  | 'public-conditions-ski'
  | 'public-tickets-ski'
  // Tailor/Alterations
  | 'tailor-stats'
  | 'order-list-progress-tailor'
  | 'fitting-list-upcoming'
  | 'order-filters-tailor'
  | 'order-table-tailor'
  | 'order-header-tailor'
  | 'order-garments'
  | 'order-fittings'
  | 'order-form-tailor'
  | 'customer-table-tailor'
  | 'customer-profile-tailor'
  | 'customer-measurements'
  | 'customer-orders-tailor'
  | 'fitting-calendar'
  | 'fabric-grid'
  | 'public-booking-tailor'
  // Travel Agency Extended
  | 'travel-stats'
  | 'booking-list-recent'
  | 'trip-list-upcoming'
  | 'trip-filters-agency'
  | 'trip-grid-agency'
  | 'trip-header-agency'
  | 'trip-form-agency'
  | 'booking-filters-agency'
  | 'booking-table-agency'
  | 'booking-header-agency'
  | 'booking-itinerary'
  | 'booking-documents'
  | 'booking-form-agency'
  | 'client-table-agency'
  | 'client-profile-agency'
  | 'payment-table-agency'
  | 'destination-browser'
  // Video Streaming Extended
  | 'video-feed'
  | 'video-info'
  | 'related-videos'
  // Yoga Studio
  | 'yoga-stats'
  | 'class-list-today-yoga'
  | 'booking-list-recent-yoga'
  | 'class-grid-yoga'
  | 'class-detail-yoga'
  | 'class-attendees'
  | 'schedule-calendar-yoga'
  | 'instructor-grid-yoga'
  | 'instructor-profile-yoga'
  | 'instructor-schedule-yoga'
  | 'member-table-yoga'
  | 'member-profile-yoga'
  | 'member-bookings-yoga'
  | 'workshop-grid'
  | 'public-schedule-yoga'
  // Campaign/Marketing Extended
  | 'campaign-list'
  | 'campaign-detail'
  | 'campaign-content'
  | 'campaign-wizard'
  // Dating Extended
  | 'dating-profile-view'
  | 'dating-profile-edit'
  | 'match-grid'
  // Crowdfunding Extended
  | 'pledge-list'
  | 'update-list'
  | 'featured-campaigns'
  | 'reward-list'
  // Misc
  | 'contract-list'
  | 'invoice-list'
  | 'delivery-list'
  | 'gig-list'
  | 'gig-filters'
  | 'gig-detail'
  | 'checkin-list'
  | 'attendance-tracker'
  | 'portfolio-grid'
  | 'tracking-map'
  | 'access-log-table'
  | 'exam-table'
  | 'exam-detail'
  | 'coach-grid'
  | 'artist-header'
  | 'stylist-schedule-overview'
  | 'appointment-list-salon'
  | 'online-booking-salon'
  | 'service-grid-salon'
  | 'client-profile'
  // Final missing types
  | 'consultation-form'
  | 'inventory-table-pharmacy'
  | 'lesson-calendar-golf';

// Layout types
export type LayoutType =
  | 'single-column'      // Full width content
  | 'two-column'         // Sidebar + main content
  | 'three-column'       // Left sidebar + main + right sidebar
  | 'dashboard'          // Header + sidebar + main
  | 'landing';           // Hero + sections

// Page section definition
export interface PageSection {
  id: string;
  component: ComponentType;
  entity?: string;           // Which entity this section displays
  props?: Record<string, any>;  // Static props for the component
  position: 'header' | 'sidebar' | 'main' | 'footer' | 'full';
}

// Page definition
export interface PageDefinition {
  path: string;              // Route path (e.g., '/products', '/products/:id')
  name: string;              // Human-readable name
  layout: LayoutType;
  sections: PageSection[];
  requiresAuth?: boolean;
  adminOnly?: boolean;
}

// API endpoint definition
export interface ApiEndpoint {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  entity: string;
  operation: 'list' | 'get' | 'create' | 'update' | 'delete' | 'custom';
  description?: string;
  requiresAuth?: boolean;
  adminOnly?: boolean;
}

// Blueprint definition
export interface Blueprint {
  appType: string;
  description: string;

  // Core entities for this app type
  coreEntities: string[];

  // Common fields that most entities should have
  commonFields: {
    timestamps: boolean;
    softDelete: boolean;
    userOwnership: boolean;
  };

  // Pages to generate
  pages: PageDefinition[];

  // API endpoints
  endpoints: ApiEndpoint[];

  // Entity-specific configurations
  entityConfig?: Record<string, {
    defaultFields?: Array<{ name: string; type: string; required?: boolean }>;
    relationships?: Array<{ type: string; target: string }>;
  }>;
}

// Function to generate pages from a blueprint
export function generatePagesFromBlueprint(
  blueprint: Blueprint,
  entities: EnhancedEntityDefinition[]
): PageDefinition[] {
  const pages: PageDefinition[] = [];

  // Add blueprint's predefined pages
  pages.push(...blueprint.pages);

  // Generate CRUD pages for each entity
  for (const entity of entities) {
    const entityName = entity.name.toLowerCase();
    const displayName = entity.displayName || entity.name;

    // List page
    pages.push({
      path: `/${entityName}s`,
      name: `${displayName} List`,
      layout: 'single-column',
      sections: [
        {
          id: `${entityName}-list`,
          component: 'data-grid',
          entity: entityName,
          position: 'main',
        },
      ],
    });

    // Detail page
    pages.push({
      path: `/${entityName}s/:id`,
      name: `${displayName} Detail`,
      layout: 'single-column',
      sections: [
        {
          id: `${entityName}-detail`,
          component: 'detail-view',
          entity: entityName,
          position: 'main',
        },
      ],
    });

    // Create page
    pages.push({
      path: `/${entityName}s/new`,
      name: `Create ${displayName}`,
      layout: 'single-column',
      sections: [
        {
          id: `${entityName}-create-form`,
          component: 'create-form',
          entity: entityName,
          position: 'main',
        },
      ],
      requiresAuth: true,
    });

    // Edit page
    pages.push({
      path: `/${entityName}s/:id/edit`,
      name: `Edit ${displayName}`,
      layout: 'single-column',
      sections: [
        {
          id: `${entityName}-edit-form`,
          component: 'edit-form',
          entity: entityName,
          position: 'main',
        },
      ],
      requiresAuth: true,
    });
  }

  return pages;
}

// Function to generate API endpoints from entities
export function generateEndpointsFromEntities(
  entities: EnhancedEntityDefinition[]
): ApiEndpoint[] {
  const endpoints: ApiEndpoint[] = [];

  for (const entity of entities) {
    const entityName = entity.name.toLowerCase();

    // Standard CRUD endpoints
    endpoints.push(
      {
        method: 'GET',
        path: `/${entityName}s`,
        entity: entityName,
        operation: 'list',
        description: `List all ${entityName}s`,
      },
      {
        method: 'GET',
        path: `/${entityName}s/:id`,
        entity: entityName,
        operation: 'get',
        description: `Get ${entityName} by ID`,
      },
      {
        method: 'POST',
        path: `/${entityName}s`,
        entity: entityName,
        operation: 'create',
        description: `Create new ${entityName}`,
        requiresAuth: true,
      },
      {
        method: 'PUT',
        path: `/${entityName}s/:id`,
        entity: entityName,
        operation: 'update',
        description: `Update ${entityName}`,
        requiresAuth: true,
      },
      {
        method: 'DELETE',
        path: `/${entityName}s/:id`,
        entity: entityName,
        operation: 'delete',
        description: `Delete ${entityName}`,
        requiresAuth: true,
      }
    );

    // Relationship endpoints
    if (entity.relationships) {
      for (const rel of entity.relationships) {
        if (rel.type === 'hasMany') {
          endpoints.push({
            method: 'GET',
            path: `/${entityName}s/:id/${rel.targetEntity.toLowerCase()}s`,
            entity: rel.targetEntity.toLowerCase(),
            operation: 'list',
            description: `List ${rel.targetEntity}s for ${entityName}`,
          });
        }
      }
    }
  }

  return endpoints;
}
