/**
 * Schema Deriver Service
 *
 * CRITICAL: Derives database schema from component field definitions.
 * This is the core of the "component-first" approach.
 *
 * The schema is NOT generated by AI - it's derived deterministically
 * from the predefined component field definitions.
 */

import { snakeCase } from 'change-case';
import * as pluralize from 'pluralize';
import {
  ComponentDefinition,
  ComponentField,
  ComponentRegistry,
  FieldMatchResult,
} from '../interfaces/component.interface';
import {
  DatabaseSchema,
  DbTable,
  DbColumn,
  DbRelation,
  DbIndex,
  SchemaDeriveResult,
  FIELD_TYPE_TO_DB,
} from '../interfaces/schema.interface';
import { FeatureDefinition } from '../interfaces/feature.interface';

export interface SchemaDeriveConfig {
  /** Add timestamps (created_at, updated_at) to all tables */
  addTimestamps: boolean;
  /** Add soft delete (deleted_at) to all tables */
  addSoftDelete: boolean;
  /** Add user ownership (user_id) to user-specific tables */
  addUserOwnership: boolean;
  /** Tables that should have user ownership */
  userOwnedTables: string[];
}

const DEFAULT_CONFIG: SchemaDeriveConfig = {
  addTimestamps: true,
  addSoftDelete: false,
  addUserOwnership: true,
  userOwnedTables: [
    'cart_items',
    'orders',
    'order_items',
    'reviews',
    'wishlists',
    'addresses',
    'notifications',
    'bookings',
    'appointments',
    'messages',
  ],
};

export class SchemaDeriverService {
  private componentRegistry: ComponentRegistry;
  private config: SchemaDeriveConfig;

  constructor(
    componentRegistry: ComponentRegistry,
    config: Partial<SchemaDeriveConfig> = {}
  ) {
    this.componentRegistry = componentRegistry;
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * Derive database schema from selected components and features
   */
  derive(
    componentIds: string[],
    entities: FeatureDefinition['entities'],
    appType: string
  ): SchemaDeriveResult {
    const tables = new Map<string, DbTable>();
    const relations: DbRelation[] = [];
    const fallbackFields: SchemaDeriveResult['fallbackFields'] = [];
    const warnings: string[] = [];

    // Step 1: Create tables from feature entities with their fields
    for (const entity of entities) {
      const tableName = this.toSnakeCase(entity.name);
      if (!tables.has(tableName)) {
        tables.set(tableName, this.createEmptyTable(tableName, entity.displayName));
      }

      // Add fields from entity definition if they exist
      if (entity.fields && entity.fields.length > 0) {
        const table = tables.get(tableName)!;
        for (const field of entity.fields) {
          // Skip if column already exists
          if (table.columns.some(c => c.name === field.name)) {
            continue;
          }

          // Map field type to database column type using FIELD_TYPE_TO_DB
          const dbTypeMapping = FIELD_TYPE_TO_DB[field.type] || { type: 'varchar' as const };

          const column: DbColumn = {
            name: field.name,
            type: dbTypeMapping.type,
            constraints: [],
          };

          if (field.primaryKey) {
            column.constraints.push('primary_key');
          }
          if (field.required && !field.primaryKey) {
            column.constraints.push('not_null');
          }
          if (field.unique) {
            column.constraints.push('unique');
          }
          if (field.default !== undefined) {
            column.constraints.push('default');
            column.default = field.default;
          }
          if (field.references) {
            column.constraints.push('foreign_key');
            column.references = {
              table: field.references.table,
              column: 'id',
              onDelete: 'cascade',
              onUpdate: 'cascade',
            };
            // Add relation
            relations.push({
              name: `${tableName}_${field.name}_fk`,
              type: 'one-to-many',
              sourceTable: tableName,
              sourceColumn: field.name,
              targetTable: field.references.table,
              targetColumn: 'id',
              onDelete: 'cascade',
            });
          }

          table.columns.push(column);
        }
      }
    }

    // Step 2: Populate tables from component fields (fallback/additional)
    for (const componentId of componentIds) {
      const component = this.componentRegistry.components.get(componentId);
      if (!component) {
        warnings.push(`Component not found: ${componentId}`);
        continue;
      }

      this.processComponentFields(
        component,
        tables,
        relations,
        fallbackFields,
        warnings
      );
    }

    // Step 3: Add standard columns to all tables
    for (const table of tables.values()) {
      this.addStandardColumns(table);
    }

    // Step 4: Add indexes
    for (const table of tables.values()) {
      this.addStandardIndexes(table, relations);
    }

    // Step 5: Validate and fix relations
    this.validateRelations(relations, tables, warnings);

    const schema: DatabaseSchema = {
      tables: Array.from(tables.values()),
      relations,
      version: 1,
      generatedAt: new Date().toISOString(),
      appType,
      features: [], // Will be filled by caller
    };

    return {
      schema,
      sourceComponents: componentIds,
      fallbackFields,
      warnings,
    };
  }

  /**
   * Process component fields and add to tables
   */
  private processComponentFields(
    component: ComponentDefinition,
    tables: Map<string, DbTable>,
    relations: DbRelation[],
    fallbackFields: SchemaDeriveResult['fallbackFields'],
    warnings: string[]
  ): void {
    // Determine the primary entity for this component
    const primaryEntity = this.inferPrimaryEntity(component);
    if (!primaryEntity) {
      warnings.push(`Could not infer primary entity for component: ${component.id}`);
      return;
    }

    const tableName = this.toSnakeCase(primaryEntity);

    // Create table if not exists
    if (!tables.has(tableName)) {
      tables.set(tableName, this.createEmptyTable(tableName, primaryEntity));
    }

    const table = tables.get(tableName)!;

    // Process required fields
    for (const field of component.requiredFields) {
      this.addFieldToTable(table, field, component, relations, fallbackFields);
    }

    // Process optional fields
    for (const field of component.optionalFields) {
      this.addFieldToTable(table, field, component, relations, fallbackFields);
    }

    // Track source component
    if (!table.sourceComponents.includes(component.id)) {
      table.sourceComponents.push(component.id);
    }
  }

  /**
   * Add a field to a table
   */
  private addFieldToTable(
    table: DbTable,
    field: ComponentField,
    component: ComponentDefinition,
    relations: DbRelation[],
    fallbackFields: SchemaDeriveResult['fallbackFields']
  ): void {
    const columnName = this.toSnakeCase(field.name);

    // Skip if column already exists
    if (table.columns.some((c) => c.name === columnName)) {
      return;
    }

    // Skip special source types
    if (field.source === 'computed' || field.source === 'static') {
      return;
    }

    // Convert field type to database column
    const dbType = FIELD_TYPE_TO_DB[field.type];
    if (!dbType) {
      fallbackFields.push({
        component: component.id,
        field: field.name,
        originalName: field.name,
        mappedTo: 'text',
      });
    }

    const column: DbColumn = {
      name: columnName,
      type: dbType?.type ?? 'text',
      typeParams: dbType?.params,
      constraints: [],
      comment: field.label,
    };

    // Add constraints
    if (field.required && field.source === 'database') {
      column.constraints.push('not_null');
    }

    if (field.default !== undefined) {
      column.constraints.push('default');
      column.default = this.formatDefaultValue(field.default, column.type);
    }

    // Handle relations
    if (field.relationTo) {
      const targetTable = this.toSnakeCase(field.relationTo);
      column.constraints.push('foreign_key');
      column.references = {
        table: targetTable,
        column: 'id',
        onDelete: 'cascade',
        onUpdate: 'cascade',
      };

      // Add relation
      relations.push({
        name: `${table.name}_${columnName}_fk`,
        type: 'one-to-many',
        sourceTable: table.name,
        sourceColumn: columnName,
        targetTable,
        targetColumn: 'id',
        onDelete: 'cascade',
      });
    }

    table.columns.push(column);
  }

  /**
   * Add standard columns to table
   */
  private addStandardColumns(table: DbTable): void {
    // Add ID if not present
    if (!table.columns.some((c) => c.name === 'id')) {
      table.columns.unshift({
        name: 'id',
        type: 'uuid',
        constraints: ['primary_key', 'not_null'],
        default: 'gen_random_uuid()',
      });
    }

    // Add timestamps
    if (this.config.addTimestamps && table.timestamps) {
      if (!table.columns.some((c) => c.name === 'created_at')) {
        table.columns.push({
          name: 'created_at',
          type: 'timestamptz',
          constraints: ['not_null', 'default'],
          default: 'NOW()',
        });
      }

      if (!table.columns.some((c) => c.name === 'updated_at')) {
        table.columns.push({
          name: 'updated_at',
          type: 'timestamptz',
          constraints: ['not_null', 'default'],
          default: 'NOW()',
        });
      }
    }

    // Add soft delete
    if (this.config.addSoftDelete && table.softDelete) {
      if (!table.columns.some((c) => c.name === 'deleted_at')) {
        table.columns.push({
          name: 'deleted_at',
          type: 'timestamptz',
          constraints: [],
        });
      }
    }

    // Add user ownership
    if (
      this.config.addUserOwnership &&
      table.userOwnership &&
      !table.columns.some((c) => c.name === 'user_id')
    ) {
      table.columns.push({
        name: 'user_id',
        type: 'uuid',
        constraints: ['not_null', 'foreign_key'],
        references: {
          table: 'users',
          column: 'id',
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      });
    }
  }

  /**
   * Add standard indexes to table
   */
  private addStandardIndexes(table: DbTable, relations: DbRelation[]): void {
    // Index on created_at for sorting
    if (table.columns.some((c) => c.name === 'created_at')) {
      table.indexes.push({
        name: `idx_${table.name}_created_at`,
        columns: ['created_at'],
        unique: false,
        type: 'btree',
      });
    }

    // Index on user_id for ownership queries
    if (table.columns.some((c) => c.name === 'user_id')) {
      table.indexes.push({
        name: `idx_${table.name}_user_id`,
        columns: ['user_id'],
        unique: false,
        type: 'btree',
      });
    }

    // Index on foreign keys
    for (const relation of relations) {
      if (relation.sourceTable === table.name) {
        const indexName = `idx_${table.name}_${relation.sourceColumn}`;
        if (!table.indexes.some((i) => i.name === indexName)) {
          table.indexes.push({
            name: indexName,
            columns: [relation.sourceColumn],
            unique: false,
            type: 'btree',
          });
        }
      }
    }
  }

  /**
   * Validate relations and ensure target tables exist
   */
  private validateRelations(
    relations: DbRelation[],
    tables: Map<string, DbTable>,
    warnings: string[]
  ): void {
    for (const relation of relations) {
      if (!tables.has(relation.targetTable)) {
        // Create placeholder table for relation target
        if (relation.targetTable !== 'users') {
          // Users table is expected to exist
          tables.set(
            relation.targetTable,
            this.createEmptyTable(relation.targetTable, relation.targetTable)
          );
          warnings.push(
            `Created placeholder table for relation target: ${relation.targetTable}`
          );
        }
      }
    }
  }

  /**
   * Infer the primary entity for a component
   */
  private inferPrimaryEntity(component: ComponentDefinition): string | null {
    // Use category to infer entity
    const categoryEntities: Record<string, string> = {
      ecommerce: 'products',
      forms: 'submissions',
      'data-display': 'items',
      dashboard: 'stats',
      auth: 'users',
      media: 'media',
      social: 'posts',
    };

    // Check for relation fields that indicate entity
    for (const field of [...component.requiredFields, ...component.optionalFields]) {
      if (field.relationTo) {
        return field.relationTo;
      }
    }

    // Check component ID for entity hints
    const entityHints = [
      'product',
      'order',
      'cart',
      'user',
      'post',
      'comment',
      'booking',
      'appointment',
      'item',
      'message',
    ];

    for (const hint of entityHints) {
      // Safety check: ensure component.id is a string before calling includes
      const componentId = typeof component.id === 'string' ? component.id : String(component.id || '');
      if (componentId.includes(hint)) {
        return hint + 's'; // Pluralize
      }
    }

    return categoryEntities[component.category] ?? null;
  }

  /**
   * Create empty table structure
   */
  private createEmptyTable(name: string, displayName: string): DbTable {
    return {
      name,
      displayName,
      columns: [],
      indexes: [],
      timestamps: this.config.addTimestamps,
      softDelete: this.config.addSoftDelete,
      userOwnership: this.config.userOwnedTables.includes(name),
      sourceComponents: [],
    };
  }

  /**
   * Format default value for SQL
   */
  private formatDefaultValue(value: any, type: string): string {
    if (value === null) return 'NULL';
    if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
    if (typeof value === 'number') return String(value);
    if (typeof value === 'string') return `'${value}'`;
    return 'NULL';
  }

  /**
   * Convert camelCase to snake_case using change-case
   */
  private toSnakeCase(str: string): string {
    return snakeCase(str);
  }

  /**
   * Pluralize a word using pluralize package
   */
  private pluralizeWord(word: string): string {
    return pluralize.plural(word);
  }

  /**
   * Singularize a word using pluralize package
   */
  private singularizeWord(word: string): string {
    return pluralize.singular(word);
  }

  /**
   * Generate SQL schema from DatabaseSchema
   */
  generateSQL(schema: DatabaseSchema): string {
    const lines: string[] = [];

    lines.push('-- Auto-generated database schema');
    lines.push(`-- Generated at: ${schema.generatedAt}`);
    lines.push(`-- App type: ${schema.appType}`);
    lines.push('');

    // Create tables
    for (const table of schema.tables) {
      lines.push(this.generateTableSQL(table));
      lines.push('');
    }

    // Create indexes
    for (const table of schema.tables) {
      for (const index of table.indexes) {
        lines.push(this.generateIndexSQL(table.name, index));
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate SQL for a single table
   */
  private generateTableSQL(table: DbTable): string {
    const lines: string[] = [];

    lines.push(`CREATE TABLE IF NOT EXISTS ${table.name} (`);

    const columnDefs: string[] = [];

    for (const column of table.columns) {
      columnDefs.push(this.generateColumnSQL(column));
    }

    lines.push('  ' + columnDefs.join(',\n  '));
    lines.push(');');

    return lines.join('\n');
  }

  /**
   * Generate SQL for a single column
   */
  private generateColumnSQL(column: DbColumn): string {
    const parts: string[] = [];

    parts.push(column.name);

    // Type
    let typeStr = column.type.toUpperCase();
    if (column.typeParams) {
      typeStr += `(${column.typeParams})`;
    }
    parts.push(typeStr);

    // Constraints
    if (column.constraints.includes('primary_key')) {
      parts.push('PRIMARY KEY');
    }
    if (column.constraints.includes('not_null')) {
      parts.push('NOT NULL');
    }
    if (column.constraints.includes('unique')) {
      parts.push('UNIQUE');
    }
    if (column.constraints.includes('default') && column.default) {
      parts.push(`DEFAULT ${column.default}`);
    }
    if (column.references) {
      parts.push(
        `REFERENCES ${column.references.table}(${column.references.column}) ON DELETE ${column.references.onDelete.toUpperCase()}`
      );
    }

    return parts.join(' ');
  }

  /**
   * Generate SQL for an index
   */
  private generateIndexSQL(tableName: string, index: DbIndex): string {
    const unique = index.unique ? 'UNIQUE ' : '';
    const columns = index.columns.join(', ');
    let sql = `CREATE ${unique}INDEX IF NOT EXISTS ${index.name} ON ${tableName} (${columns})`;

    if (index.where) {
      sql += ` WHERE ${index.where}`;
    }

    return sql + ';';
  }
}
