// @ts-nocheck
import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams, useParams } from 'react-router-dom';
import {
  Plus,
  Trash2,
  Save,
  Calendar,
  Dumbbell,
  Search,
  ChevronDown,
  ChevronUp,
  X,
  Sparkles,
  Loader2,
  Edit
} from 'lucide-react';
import Icon from '@mdi/react';
import { mdiTimer, mdiDumbbell, mdiRepeat } from '@mdi/js';
import { Button } from '../../components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { WorkoutPlan, Workout, WorkoutExercise, ExerciseDBEntry, WorkoutSet, UserFitnessProfile, PlanDuration } from '../../types/fitness';
import { cn } from '../../lib/utils';
import { exerciseDatabase, workoutTemplates, generateWorkoutPlan } from '../../lib/workout-recommendations';
import { useCreateWorkoutPlanFromBuilder, useUpdateWorkoutPlanFromBuilder } from '../../hooks/fitness/useWorkoutPlans';
import { useWorkoutPlan } from '../../hooks/fitness/useWorkoutPlansNew';
import { useExercises } from '../../hooks/fitness/useExercises';
import { toast } from '../../components/ui/sonner';

const CustomPlanBuilder: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { id: routePlanId } = useParams();
  const duration = (Number(searchParams.get('duration')) || 30) as PlanDuration;
  const templateName = searchParams.get('template');
  const planId = routePlanId || searchParams.get('id'); // Get ID from route params first, then search params
  const mode = searchParams.get('mode') || (routePlanId ? 'edit' : 'create'); // If ID in route, it's edit mode
  const currentMode = searchParams.get('mode') || localStorage.getItem('workoutMode');
  
  // Helper function to create URLs with mode parameter
  const createUrlWithMode = (baseUrl: string) => {
    if (currentMode) {
      const separator = baseUrl.includes('?') ? '&' : '?';
      return `${baseUrl}${separator}mode=${currentMode}`;
    }
    return baseUrl;
  };
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [isViewMode, setIsViewMode] = useState(mode === 'view');

  const [planName, setPlanName] = useState('');
  const [planDescription, setPlanDescription] = useState('');
  const [workouts, setWorkouts] = useState<Workout[]>([]);
  // Use exercises API instead of local database
  const {
    exercises: exerciseDB,
    loading: exercisesLoading,
    error: exercisesError,
    fetchExercises
  } = useExercises({ limit: 100 }); // Get first 100 exercises
  const [planDuration, setPlanDuration] = useState<PlanDuration>(duration);

  // API Integration for creating plans
  const createWorkoutPlanMutation = useCreateWorkoutPlanFromBuilder({
    exerciseDatabase: exerciseDB,
    planType: currentMode as 'gym' | 'home', // Pass the current mode as plan type
    onSuccess: (workoutPlan) => {
      // Save as active plan in localStorage for offline access
      localStorage.setItem('activeWorkoutPlan', JSON.stringify(workoutPlan));
      navigate(createUrlWithMode('/fitness/dashboard'));
    },
    onError: (error) => {
      console.error('Failed to create workout plan:', error);
      // Fallback to local storage save on API failure
      savePlanLocally();
    }
  });

  // API Integration for viewing existing plans
  const {
    workoutPlan: apiWorkoutPlan,
    loading: isLoadingPlan,
    error: planError,
    isSystemPlan,
    refetch: refetchPlan
  } = useWorkoutPlan(planId || '');

  // API Integration for updating existing plans
  const updateWorkoutPlanMutation = useUpdateWorkoutPlanFromBuilder({
    exerciseDatabase: exerciseDB,
    planType: currentMode as 'gym' | 'home', // Pass the current mode as plan type
    onSuccess: (workoutPlan) => {
      // Navigate back to workout plans page after successful update
      navigate(createUrlWithMode('/fitness/workout-plans'));
    },
    onError: (error) => {
      console.error('Failed to update workout plan:', error);
      // Stay in edit mode on error
    }
  });
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [expandedWorkout, setExpandedWorkout] = useState<string | null>(null);
  const [showDurationConfirm, setShowDurationConfirm] = useState<{ show: boolean; newDuration: PlanDuration }>({ show: false, newDuration: 7 });

  useEffect(() => {
    // Exercises are now loaded via the useExercises hook
    
    // If we have a plan ID, skip template/localStorage loading
    // The API data will be loaded by the useWorkoutPlan hook automatically
    if (planId) {
      return;
    }

    // Check if we have an auto-generated plan in localStorage
    const savedPlan = localStorage.getItem('selectedWorkoutPlan');
    const savedTemplate = localStorage.getItem('selectedWorkoutTemplate');
    
    if (savedPlan && savedTemplate === templateName) {
      // Load the auto-generated plan from localStorage
      const plan: WorkoutPlan = JSON.parse(savedPlan);
      setPlanName(plan.name);
      setPlanDescription(plan.description || '');
      setWorkouts(plan.workouts);
      setIsAutoGenerated(true);
      
      // Clear the saved plan
      localStorage.removeItem('selectedWorkoutPlan');
      localStorage.removeItem('selectedWorkoutTemplate');
    } else if (templateName && duration) {
      // Generate plan based on template name and user profile
      const userProfileStr = localStorage.getItem('fitnessProfile');
      if (userProfileStr) {
        const userProfile: UserFitnessProfile = JSON.parse(userProfileStr);
        const template = workoutTemplates.find(t => t.name === decodeURIComponent(templateName));
        
        if (template) {
          const generatedPlan = generateWorkoutPlan(template, userProfile, duration);
          setPlanName(generatedPlan.name);
          setPlanDescription(generatedPlan.description || '');
          setWorkouts(generatedPlan.workouts);
          setIsAutoGenerated(true);
          
          // Expand first workout by default
          if (generatedPlan.workouts.length > 0) {
            setExpandedWorkout(generatedPlan.workouts[0].id);
          }
        } else {
          // Template not found, initialize empty
          initializeWorkouts();
        }
      } else {
        // No user profile, initialize empty
        initializeWorkouts();
      }
    } else {
      // Custom plan from scratch
      initializeWorkouts();
    }
  }, [templateName, duration, isViewMode, planId]);

  // Effect to populate form data when API workout plan is loaded
  useEffect(() => {
    if (apiWorkoutPlan && !isLoadingPlan) {
      console.log('Loading API workout plan:', apiWorkoutPlan);
      setPlanName(apiWorkoutPlan.name);
      setPlanDescription(apiWorkoutPlan.description || '');
      setWorkouts(apiWorkoutPlan.workouts);
      setIsAutoGenerated(true);
      
      // Expand first workout by default
      if (apiWorkoutPlan.workouts.length > 0) {
        setExpandedWorkout(apiWorkoutPlan.workouts[0].id);
      }
    }
  }, [apiWorkoutPlan, isLoadingPlan]);

  // Exercise database is now loaded via the useExercises hook

  const initializeWorkouts = (dayCount?: number) => {
    const workoutDays = Math.min(dayCount || planDuration, 30); // Max 30 individual workouts
    const newWorkouts: Workout[] = [];

    for (let i = 0; i < workoutDays; i++) {
      newWorkouts.push({
        id: `workout-${i}`,
        name: `Day ${i + 1} Workout`,
        date: new Date(),
        exercises: [],
        duration: 0,
        notes: '',
      });
    }

    setWorkouts(newWorkouts);
  };

  const addExerciseToWorkout = (workoutId: string, exercise: ExerciseDBEntry) => {
    setWorkouts(workouts.map(workout => {
      if (workout.id === workoutId) {
        const newExercise: WorkoutExercise = {
          exerciseId: exercise.id,
          sets: [{ reps: 10, weight: 0 }],
          notes: '',
        };
        return {
          ...workout,
          exercises: [...workout.exercises, newExercise],
        };
      }
      return workout;
    }));
  };

  const removeExerciseFromWorkout = (workoutId: string, exerciseIndex: number) => {
    setWorkouts(workouts.map(workout => {
      if (workout.id === workoutId) {
        return {
          ...workout,
          exercises: workout.exercises.filter((_, index) => index !== exerciseIndex),
        };
      }
      return workout;
    }));
  };

  const updateWorkoutName = (workoutId: string, name: string) => {
    setWorkouts(workouts.map(workout => 
      workout.id === workoutId ? { ...workout, name } : workout
    ));
  };

  const updateExerciseSet = (workoutId: string, exerciseIndex: number, setIndex: number, updates: Partial<WorkoutSet>) => {
    setWorkouts(workouts.map(workout => {
      if (workout.id === workoutId) {
        const updatedExercises = [...workout.exercises];
        const updatedSets = [...updatedExercises[exerciseIndex].sets];
        updatedSets[setIndex] = { ...updatedSets[setIndex], ...updates };
        updatedExercises[exerciseIndex] = { ...updatedExercises[exerciseIndex], sets: updatedSets };
        return { ...workout, exercises: updatedExercises };
      }
      return workout;
    }));
  };

  const addSet = (workoutId: string, exerciseIndex: number) => {
    setWorkouts(workouts.map(workout => {
      if (workout.id === workoutId) {
        const updatedExercises = [...workout.exercises];
        const lastSet = updatedExercises[exerciseIndex].sets[updatedExercises[exerciseIndex].sets.length - 1];
        updatedExercises[exerciseIndex].sets.push({ ...lastSet });
        return { ...workout, exercises: updatedExercises };
      }
      return workout;
    }));
  };

  const handleDurationChange = (newDuration: PlanDuration) => {
    // Check if reducing days and workouts have exercises
    if (newDuration < workouts.length) {
      const workoutsToRemove = workouts.slice(newDuration);
      const hasExercisesInRemovedWorkouts = workoutsToRemove.some(w => w.exercises.length > 0);
      
      if (hasExercisesInRemovedWorkouts) {
        setShowDurationConfirm({ show: true, newDuration });
        return;
      }
    }
    
    // Apply the duration change
    applyDurationChange(newDuration);
  };

  const applyDurationChange = (newDuration: PlanDuration) => {
    setPlanDuration(newDuration);
    
    // If reducing days, remove workouts from the end
    if (newDuration < workouts.length) {
      setWorkouts(workouts.slice(0, newDuration));
    }
    // If increasing days, add new workouts
    else if (newDuration > workouts.length) {
      const newWorkouts = [...workouts];
      for (let i = workouts.length; i < newDuration; i++) {
        newWorkouts.push({
          id: `workout-${i}`,
          name: `Day ${i + 1} Workout`,
          date: new Date(),
          exercises: [],
          duration: 0,
          notes: '',
        });
      }
      setWorkouts(newWorkouts);
    }
  };

  const confirmDurationChange = () => {
    applyDurationChange(showDurationConfirm.newDuration);
    setShowDurationConfirm({ show: false, newDuration: 7 });
  };

  const cancelDurationChange = () => {
    setShowDurationConfirm({ show: false, newDuration: 7 });
  };

  const removeSet = (workoutId: string, exerciseIndex: number, setIndex: number) => {
    setWorkouts(workouts.map(workout => {
      if (workout.id === workoutId) {
        const updatedExercises = [...workout.exercises];
        updatedExercises[exerciseIndex].sets = updatedExercises[exerciseIndex].sets.filter((_, i) => i !== setIndex);
        return { ...workout, exercises: updatedExercises };
      }
      return workout;
    }));
  };

  const savePlanLocally = () => {
    // Validate that the plan has at least one exercise
    const totalExercises = workouts.reduce((total, workout) => total + workout.exercises.length, 0);

    if (totalExercises === 0) {
      toast.error('Cannot create workout plan without exercises. Please add at least one exercise to your workout plan.');
      return;
    }

    const plan: WorkoutPlan = {
      id: Date.now().toString(),
      name: planName || 'My Custom Plan',
      description: planDescription,
      workouts,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    // Save to localStorage as fallback
    const savedPlans = JSON.parse(localStorage.getItem('customWorkoutPlans') || '[]');
    savedPlans.push(plan);
    localStorage.setItem('customWorkoutPlans', JSON.stringify(savedPlans));

    // Also save as active plan
    localStorage.setItem('activeWorkoutPlan', JSON.stringify(plan));

    navigate('/fitness/dashboard');
  };

  const savePlan = () => {
    // Validate that the plan has at least one exercise
    const totalExercises = workouts.reduce((total, workout) => total + workout.exercises.length, 0);

    if (totalExercises === 0) {
      toast.error('Cannot create workout plan without exercises. Please add at least one exercise to your workout plan.');
      return;
    }

    const plan: WorkoutPlan = {
      id: planId || Date.now().toString(),
      name: planName || 'My Custom Plan',
      description: planDescription,
      workouts,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    // If we have a planId, check if it's a system plan or user plan
    if (planId) {
      if (isSystemPlan) {
        // System plans should be saved as NEW user plans (copy/clone)
        // Don't use the system plan ID - create a fresh plan
        const newPlan: WorkoutPlan = {
          ...plan,
          id: Date.now().toString(), // Generate new ID
          name: plan.name.includes('(My Copy)') ? plan.name : `${plan.name} (My Copy)`,
        };
        createWorkoutPlanMutation.mutate(newPlan);
      } else {
        // Update existing user plan
        updateWorkoutPlanMutation.mutate(planId, plan);
      }
    } else {
      // Create new plan
      createWorkoutPlanMutation.mutate(plan);
    }
  };

  // Update exercises when search term or category changes
  useEffect(() => {
    const params = {
      limit: 100,
      ...(searchTerm && { search: searchTerm }),
      ...(selectedCategory !== 'all' && { category: selectedCategory })
    };
    
    // Debounce the search to avoid too many API calls
    const timeoutId = setTimeout(() => {
      fetchExercises(params);
    }, 300);
    
    return () => clearTimeout(timeoutId);
  }, [searchTerm, selectedCategory, fetchExercises]);
  
  const filteredExercises = exerciseDB; // Now filtered by API

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
        {isLoadingPlan ? (
          <div className="text-center py-8">
            <Loader2 className="h-8 w-8 mx-auto animate-spin text-teal-400 mb-2" />
            <p className="text-white/60">Loading workout plan...</p>
          </div>
        ) : planError ? (
          <div className="text-center py-8">
            <p className="text-red-400 mb-4">Failed to load workout plan</p>
            <Button onClick={() => navigate(createUrlWithMode('/fitness/workout-plans'))} className="bg-white/10 border border-white/20 text-white hover:scale-105 transition-all duration-200">
              Back to Workout Plans
            </Button>
          </div>
        ) : (
          <div className="flex items-start justify-between">
            <div className="flex-1">
              {(isAutoGenerated || isViewMode) && (
                <div className="flex items-center gap-2 mb-2">
                  <Sparkles className="h-5 w-5 text-teal-400" />
                  <span className="text-sm text-teal-400 font-medium">
                    {isViewMode
                      ? (isSystemPlan ? 'Pre-built Plan (Read Only)' : 'Your Saved Plan')
                      : 'AI-Generated Plan'}
                  </span>
                </div>
              )}
              {isViewMode ? (
                <>
                  <h1 className="text-2xl font-bold mb-2 text-white">{planName}</h1>
                  <p className="text-white/60">{planDescription}</p>
                </>
              ) : (
                <>
                  <input
                    type="text"
                    placeholder="Plan Name"
                    value={planName}
                    onChange={(e) => setPlanName(e.target.value)}
                    className="text-2xl font-bold bg-transparent border-none outline-none w-full mb-2 text-white placeholder:text-white/40"
                  />
                  <textarea
                    placeholder="Plan Description"
                    value={planDescription}
                    onChange={(e) => setPlanDescription(e.target.value)}
                    className="text-white/60 bg-transparent border-none outline-none w-full resize-none placeholder:text-white/30"
                    rows={2}
                  />
                </>
              )}
            </div>
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1 text-teal-400">
                <Calendar className="h-5 w-5" />
                {isViewMode ? (
                  <span className="font-medium">{workouts.length || planDuration} days</span>
                ) : (
                  <div className="flex items-center gap-1">
                    <Select
                      value={planDuration.toString()}
                      onValueChange={(value) => handleDurationChange(Number(value) as PlanDuration)}
                    >
                      <SelectTrigger className="w-16 h-8 bg-transparent border-none outline-none text-teal-400 font-medium px-1 focus:ring-0 focus:ring-offset-0 hover:bg-teal-500/10 transition-colors">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="7">7</SelectItem>
                        <SelectItem value="15">15</SelectItem>
                        <SelectItem value="30">30</SelectItem>
                        <SelectItem value="90">90</SelectItem>
                        <SelectItem value="180">180</SelectItem>
                      </SelectContent>
                    </Select>
                    <span className="font-medium">days</span>
                  </div>
                )}
              </div>
              {isViewMode ? (
                <div className="flex items-center gap-2">
                  <Button
                    onClick={() => setIsViewMode(false)}
                    className="bg-white/10 border border-white/20 text-white hover:scale-105 transition-all duration-200"
                  >
                    <Edit className="h-4 w-4 mr-2" />
                    Edit Plan
                  </Button>
                  <Button 
                    onClick={() => {
                      localStorage.setItem('activeWorkoutPlan', JSON.stringify({
                        id: planId,
                        name: planName,
                        description: planDescription,
                        workouts,
                        createdAt: new Date(),
                        updatedAt: new Date()
                      }));
                      navigate(createUrlWithMode('/fitness/dashboard'));
                    }}
                  >
                    <Save className="h-4 w-4 mr-2" />
                    Start Workout
                  </Button>
                </div>
              ) : planId ? (
                <div className="flex items-center gap-2">
                  <Button
                    onClick={() => setIsViewMode(true)}
                    className="bg-white/10 border border-white/20 text-white hover:scale-105 transition-all duration-200"
                  >
                    Cancel
                  </Button>
                  <Button
                    onClick={savePlan}
                    disabled={updateWorkoutPlanMutation.isPending || createWorkoutPlanMutation.isPending}
                  >
                    {(updateWorkoutPlanMutation.isPending || createWorkoutPlanMutation.isPending) ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        {isSystemPlan ? 'Saving as My Plan...' : 'Updating Plan...'}
                      </>
                    ) : (
                      <>
                        <Save className="h-4 w-4 mr-2" />
                        {isSystemPlan ? 'Save as My Plan' : 'Save Changes'}
                      </>
                    )}
                  </Button>
                </div>
              ) : (
                <Button 
                  onClick={savePlan} 
                  className="ml-4"
                  disabled={createWorkoutPlanMutation.isPending}
                >
                  {createWorkoutPlanMutation.isPending ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Creating Plan...
                    </>
                  ) : (
                    <>
                      <Save className="h-4 w-4 mr-2" />
                      Save & Start
                    </>
                  )}
                </Button>
              )}
            </div>
          </div>
        )}
      </div>

      <div className={`grid grid-cols-1 lg:grid-cols-${isViewMode ? '1' : '3'} gap-6`}>
        {/* Workouts List */}
        <div className={`${isViewMode ? '' : 'lg:col-span-2'} space-y-4`}>
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-semibold text-white">
              Workouts
              <span className="text-base font-normal text-white/60">({workouts.length} days)</span>
            </h2>
            {isAutoGenerated && workouts.some(w => w.exercises.length > 0) && (
              <div className="flex items-center gap-2 text-sm text-white/60">
                <Sparkles className="h-4 w-4 text-teal-400" />
                <span>Pre-filled based on your profile</span>
              </div>
            )}
          </div>
          <div className="space-y-4">
            {workouts.map((workout) => (
              <div
                key={workout.id}
                className="bg-white/10 backdrop-blur-xl border border-white/20 rounded-xl overflow-hidden"
              >
                <div
                  className="p-4 cursor-pointer hover:bg-white/5 transition-colors"
                  onClick={() => setExpandedWorkout(
                    expandedWorkout === workout.id ? null : workout.id
                  )}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {isViewMode ? (
                        <span className="font-medium text-white">{workout.name}</span>
                      ) : (
                        <input
                          type="text"
                          value={workout.name}
                          onChange={(e) => updateWorkoutName(workout.id, e.target.value)}
                          onClick={(e) => e.stopPropagation()}
                          className="font-medium bg-transparent border-none outline-none text-white"
                        />
                      )}
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-sm text-white/60">
                        {workout.exercises.length} exercises
                      </span>
                      {expandedWorkout === workout.id ? (
                        <ChevronUp className="h-5 w-5 text-white/60" />
                      ) : (
                        <ChevronDown className="h-5 w-5 text-white/60" />
                      )}
                    </div>
                  </div>
                </div>

                {expandedWorkout === workout.id && (
                  <div className="border-t border-white/20 p-4 space-y-3">
                    {workout.exercises.length === 0 ? (
                      <div className="text-center py-8 text-white/60">
                        <Dumbbell className="h-8 w-8 mx-auto mb-2 opacity-50" />
                        <p>No exercises added yet</p>
                        <p className="text-sm">Add exercises from the right panel</p>
                      </div>
                    ) : (
                      workout.exercises.map((exercise, exerciseIndex) => {
                        const exerciseDetails = exerciseDB.find(e => e.id === exercise.exerciseId) ||
                                             exerciseDatabase.find(e => e.id === exercise.exerciseId);
                        return (
                          <div
                            key={exerciseIndex}
                            className="border border-white/20 rounded-lg p-4 space-y-3"
                          >
                            <div className="flex items-start justify-between">
                              <div>
                                <div className="font-medium text-lg text-white">{exerciseDetails?.name}</div>
                                {exerciseDetails?.muscleGroups && (
                                  <div className="text-sm text-white/60">
                                    {exerciseDetails.muscleGroups.join(', ')}
                                  </div>
                                )}
                                {exercise.notes && (
                                  <div className="text-sm text-white/60 italic mt-1">
                                    {exercise.notes}
                                  </div>
                                )}
                              </div>
                              {!isViewMode && (
                                <Button
                                  size="sm"
                                  onClick={() => removeExerciseFromWorkout(workout.id, exerciseIndex)}
                                  className="bg-red-500/10 border border-red-400/30 text-red-400 hover:bg-red-500/20 hover:scale-105 transition-all duration-200"
                                >
                                  <Trash2 className="h-4 w-4" />
                                </Button>
                              )}
                            </div>
                            
                            {/* Sets */}
                            <div className="space-y-2">
                              <div className="flex items-center justify-between">
                                <span className="text-sm font-medium">Sets</span>
                                {!isViewMode && (
                                  <Button
                                    size="sm"
                                    onClick={() => addSet(workout.id, exerciseIndex)}
                                    className="h-7 px-2 bg-teal-500/10 border border-teal-400/30 text-teal-400 hover:bg-teal-500/20 hover:scale-105 transition-all duration-200"
                                  >
                                    <Plus className="h-3 w-3 mr-1" />
                                    Add Set
                                  </Button>
                                )}
                              </div>
                              
                              {exercise.sets.map((set, setIndex) => (
                                <div key={setIndex} className="flex items-center gap-2 text-sm">
                                  <span className="w-12 text-white/60">Set {setIndex + 1}</span>
                                  
                                  {set.duration ? (
                                    <div className="flex items-center gap-2">
                                      <Icon path={mdiTimer} size={0.7} className="text-white/60" />
                                      {isViewMode ? (
                                        <span className="w-16 px-2 py-1 text-center font-medium">{set.duration}</span>
                                      ) : (
                                        <input
                                          type="number"
                                          value={set.duration}
                                          onChange={(e) => updateExerciseSet(workout.id, exerciseIndex, setIndex, { duration: Number(e.target.value) })}
                                          className="w-16 px-2 py-1 border border-white/20 bg-white/10 text-white rounded text-center focus:outline-none focus:ring-2 focus:ring-teal-500/50"
                                          placeholder="sec"
                                        />
                                      )}
                                      <span className="text-white/60">seconds</span>
                                    </div>
                                  ) : (
                                    <>
                                      <div className="flex items-center gap-2">
                                        <Icon path={mdiRepeat} size={0.7} className="text-white/60" />
                                        {isViewMode ? (
                                          <span className="w-16 px-2 py-1 text-center font-medium">{set.reps}</span>
                                        ) : (
                                          <input
                                            type="number"
                                            value={set.reps}
                                            onChange={(e) => updateExerciseSet(workout.id, exerciseIndex, setIndex, { reps: Number(e.target.value) })}
                                            className="w-16 px-2 py-1 border border-white/20 bg-white/10 text-white rounded text-center focus:outline-none focus:ring-2 focus:ring-teal-500/50"
                                            placeholder="reps"
                                          />
                                        )}
                                        <span className="text-white/60">reps</span>
                                      </div>
                                      
                                      {exerciseDetails?.category === 'strength' && (
                                        <div className="flex items-center gap-2">
                                          <Icon path={mdiDumbbell} size={0.7} className="text-white/60" />
                                          {isViewMode ? (
                                            <span className="w-16 px-2 py-1 text-center font-medium">{set.weight || 0}</span>
                                          ) : (
                                            <input
                                              type="number"
                                              value={set.weight || 0}
                                              onChange={(e) => updateExerciseSet(workout.id, exerciseIndex, setIndex, { weight: Number(e.target.value) })}
                                              className="w-16 px-2 py-1 border border-white/20 bg-white/10 text-white rounded text-center focus:outline-none focus:ring-2 focus:ring-teal-500/50"
                                              placeholder="kg"
                                            />
                                          )}
                                          <span className="text-white/60">kg</span>
                                        </div>
                                      )}
                                    </>
                                  )}
                                  
                                  {exercise.sets.length > 1 && !isViewMode && (
                                    <Button
                                      size="sm"
                                      onClick={() => removeSet(workout.id, exerciseIndex, setIndex)}
                                      className="h-7 w-7 p-0 bg-red-500/10 border border-red-400/30 text-red-400 hover:bg-red-500/20 hover:scale-105 transition-all duration-200"
                                    >
                                      <X className="h-3 w-3" />
                                    </Button>
                                  )}
                                </div>
                              ))}
                            </div>
                          </div>
                        );
                      })
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Exercise Database - Only show in create mode */}
        {!isViewMode && (
          <div className="space-y-4">
            <h2 className="text-xl font-semibold text-white">Exercise Library</h2>
          
          {/* Search and Filter */}
          <div className="space-y-3">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-white/60" />
              <input
                type="text"
                placeholder="Search exercises..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 border border-white/20 rounded-lg bg-white/10 text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-teal-500/50"
              />
            </div>

            <Select value={selectedCategory} onValueChange={setSelectedCategory}>
              <SelectTrigger className="w-full p-2 border border-white/20 rounded-lg bg-white/10 text-white focus:outline-none focus:ring-2 focus:ring-teal-500/50">
                <SelectValue placeholder="All Categories" />
              </SelectTrigger>
              <SelectContent className="bg-teal-800/90 border-teal-400/30">
                <SelectItem value="all">All Categories</SelectItem>
                <SelectItem value="chest">Chest</SelectItem>
                <SelectItem value="back">Back</SelectItem>
                <SelectItem value="shoulders">Shoulders</SelectItem>
                <SelectItem value="arms">Arms</SelectItem>
                <SelectItem value="legs">Legs</SelectItem>
                <SelectItem value="core">Core</SelectItem>
                <SelectItem value="cardio">Cardio</SelectItem>
                <SelectItem value="full_body">Full Body</SelectItem>
                <SelectItem value="flexibility">Flexibility</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Exercise List */}
          <div className="space-y-2 max-h-[600px] overflow-y-auto">
            {exercisesLoading ? (
              // Loading skeleton
              [...Array(6)].map((_, index) => (
                <div key={index} className="p-3 bg-white/10 backdrop-blur-xl border border-white/20 rounded-lg animate-pulse">
                  <div className="h-4 bg-white/20 rounded mb-2"></div>
                  <div className="h-3 bg-white/10 rounded w-2/3"></div>
                </div>
              ))
            ) : exercisesError ? (
              // Error state
              <div className="text-center py-8">
                <p className="text-red-400 mb-4">Failed to load exercises</p>
                <Button onClick={() => fetchExercises()} className="bg-white/10 border border-white/20 text-white hover:scale-105 transition-all duration-200">
                  Try Again
                </Button>
              </div>
            ) : filteredExercises.length === 0 ? (
              // No results
              <div className="text-center py-8">
                <p className="text-white/60">No exercises found</p>
                {(searchTerm || selectedCategory !== 'all') && (
                  <Button className="mt-2 bg-white/10 border border-white/20 text-white hover:scale-105 transition-all duration-200" onClick={() => {
                    setSearchTerm('');
                    setSelectedCategory('all');
                  }}>
                    Clear Filters
                  </Button>
                )}
              </div>
            ) : (
              filteredExercises.map((exercise) => (
                <div
                  key={exercise.id}
                  className="p-3 bg-white/10 backdrop-blur-xl border border-white/20 rounded-lg hover:shadow-md transition-all"
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h4 className="font-medium text-white">{exercise.name}</h4>
                      <p className="text-sm text-white/60">
                        {exercise.targetMuscles?.join(', ') || exercise.muscleGroups?.join(', ')}
                      </p>
                      <div className="flex items-center gap-2 mt-1">
                        {exercise.equipment && exercise.equipment !== 'none' && (
                          <span className="text-xs text-white/60">
                            {exercise.equipment}
                          </span>
                        )}
                      </div>
                    </div>
                    {expandedWorkout && (
                      <Button
                        size="sm"
                        onClick={() => addExerciseToWorkout(expandedWorkout, exercise)}
                        className="ml-2 bg-teal-500/10 border border-teal-400/30 text-teal-400 hover:bg-teal-500/20 hover:scale-105 transition-all duration-200"
                      >
                        <Plus className="h-4 w-4" />
                      </Button>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
        )}
      </div>

      {/* Duration Change Confirmation Dialog */}
      {showDurationConfirm.show && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white/10 backdrop-blur-xl border border-white/20 rounded-xl p-6 max-w-md w-full mx-4 shadow-2xl">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-amber-500/20 rounded-full flex items-center justify-center">
                <Calendar className="h-5 w-5 text-amber-400" />
              </div>
              <h3 className="text-lg font-semibold text-white">Change Plan Duration</h3>
            </div>

            <p className="text-white/80 mb-6">
              Reducing the plan duration to {showDurationConfirm.newDuration} days will remove {workouts.length - showDurationConfirm.newDuration} workout days and their exercises. This action cannot be undone.
            </p>

            <div className="flex items-center gap-3 justify-end">
              <Button
                onClick={cancelDurationChange}
                className="bg-white/10 border border-white/20 text-white hover:scale-105 transition-all duration-200"
              >
                Cancel
              </Button>
              <Button
                onClick={confirmDurationChange}
                className="bg-amber-500 hover:bg-amber-600 text-white hover:scale-105 transition-all duration-200"
              >
                Continue
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CustomPlanBuilder;