/**
 * Food Ordering Feature Definition
 *
 * Online food ordering system with menu display,
 * order customization, cart management, and order tracking.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const FOOD_ORDERING_FEATURE: FeatureDefinition = {
  id: 'food-ordering',
  name: 'Food Ordering',
  category: 'hospitality',
  description: 'Online food ordering with menu display, customization, and order tracking',
  icon: 'burger',

  includedInAppTypes: [
    'restaurant',
    'hotel',
    'cafe',
    'bar',
    'bakery',
    'catering',
    'food-truck',
    'hostel',
    'resort',
    'vacation-rental',
    'pizzeria',
    'fast-food',
    'deli',
    'ghost-kitchen',
    'cloud-kitchen',
  ],

  activationKeywords: [
    'food ordering',
    'online ordering',
    'order food',
    'takeout',
    'takeaway',
    'delivery',
    'food delivery',
    'uber eats',
    'doordash',
    'grubhub',
    'order tracking',
    'pickup',
    'curbside pickup',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'menu-display',
      route: '/order',
      section: 'frontend',
      title: 'Order Food',
      authRequired: false,
      templateId: 'menu-display',
      components: [
        'menu-grid',
        'category-nav',
        'search-bar',
        'cart-preview',
      ],
      layout: 'default',
    },
    {
      id: 'order-builder',
      route: '/order/item/:itemId',
      section: 'frontend',
      title: 'Customize Item',
      authRequired: false,
      templateId: 'order-builder',
      components: [
        'item-customizer',
        'modifier-selector',
        'quantity-picker',
        'special-instructions',
      ],
      layout: 'default',
    },
    {
      id: 'cart',
      route: '/order/cart',
      section: 'frontend',
      title: 'Your Cart',
      authRequired: false,
      templateId: 'cart',
      components: [
        'cart-summary',
        'cart-items',
        'promo-input',
        'checkout-button',
      ],
      layout: 'default',
    },
    {
      id: 'checkout',
      route: '/order/checkout',
      section: 'frontend',
      title: 'Checkout',
      authRequired: false,
      templateId: 'checkout',
      components: [
        'delivery-picker',
        'contact-form',
        'payment-form',
        'order-review',
      ],
      layout: 'default',
    },
    {
      id: 'order-tracking',
      route: '/order/track/:orderId',
      section: 'frontend',
      title: 'Track Order',
      authRequired: false,
      templateId: 'order-tracking',
      components: [
        'order-status',
        'status-timeline',
        'eta-display',
        'driver-info',
      ],
      layout: 'default',
    },
    {
      id: 'order-history',
      route: '/orders',
      section: 'frontend',
      title: 'Order History',
      authRequired: true,
      templateId: 'order-history',
      components: [
        'orders-list',
        'order-card',
        'reorder-button',
        'order-filters',
      ],
      layout: 'default',
    },
    {
      id: 'admin-orders',
      route: '/admin/orders',
      section: 'admin',
      title: 'Manage Orders',
      authRequired: true,
      templateId: 'admin-orders',
      components: [
        'orders-queue',
        'order-detail',
        'status-updater',
        'order-actions',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Menu display components
    'menu-grid',
    'category-nav',
    'search-bar',
    'cart-preview',
    'item-card',

    // Order builder components
    'item-customizer',
    'modifier-selector',
    'quantity-picker',
    'special-instructions',
    'add-to-cart',

    // Cart components
    'cart-summary',
    'cart-items',
    'promo-input',
    'checkout-button',
    'cart-total',

    // Checkout components
    'delivery-picker',
    'contact-form',
    'payment-form',
    'order-review',
    'tip-selector',

    // Tracking components
    'order-status',
    'status-timeline',
    'eta-display',
    'driver-info',
    'delivery-map',

    // History components
    'orders-list',
    'order-card',
    'reorder-button',
    'order-filters',

    // Admin components
    'orders-queue',
    'order-detail',
    'status-updater',
    'order-actions',
  ],

  entities: [
    {
      name: 'food_orders',
      displayName: 'Food Orders',
      description: 'Customer food orders',
      isCore: true,
    },
    {
      name: 'order_items',
      displayName: 'Order Items',
      description: 'Items in food orders',
      isCore: true,
    },
    {
      name: 'customizations',
      displayName: 'Customizations',
      description: 'Item customizations and modifiers',
      isCore: true,
    },
    {
      name: 'order_status',
      displayName: 'Order Status',
      description: 'Order status tracking',
      isCore: true,
    },
    {
      name: 'delivery_zones',
      displayName: 'Delivery Zones',
      description: 'Delivery area definitions',
      isCore: false,
    },
    {
      name: 'drivers',
      displayName: 'Drivers',
      description: 'Delivery drivers',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Order routes
    {
      method: 'GET',
      path: '/food-orders',
      auth: true,
      handler: 'crud',
      entity: 'food_orders',
      description: 'List orders',
    },
    {
      method: 'POST',
      path: '/food-orders',
      auth: false,
      handler: 'crud',
      entity: 'food_orders',
      description: 'Create order',
    },
    {
      method: 'GET',
      path: '/food-orders/:id',
      auth: false,
      handler: 'crud',
      entity: 'food_orders',
      description: 'Get order details',
    },
    {
      method: 'PUT',
      path: '/food-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'food_orders',
      description: 'Update order',
    },
    {
      method: 'DELETE',
      path: '/food-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'food_orders',
      description: 'Cancel order',
    },
    {
      method: 'GET',
      path: '/food-orders/:id/status',
      auth: false,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Get order status',
    },
    {
      method: 'PUT',
      path: '/food-orders/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Update order status',
    },
    {
      method: 'POST',
      path: '/food-orders/:id/accept',
      auth: true,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Accept order',
    },
    {
      method: 'POST',
      path: '/food-orders/:id/ready',
      auth: true,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Mark order ready',
    },
    {
      method: 'POST',
      path: '/food-orders/:id/dispatch',
      auth: true,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Dispatch order for delivery',
    },
    {
      method: 'POST',
      path: '/food-orders/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Complete order',
    },
    {
      method: 'GET',
      path: '/food-orders/my-orders',
      auth: true,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Get my orders',
    },
    {
      method: 'POST',
      path: '/food-orders/:id/reorder',
      auth: true,
      handler: 'custom',
      entity: 'food_orders',
      description: 'Reorder previous order',
    },

    // Order items routes
    {
      method: 'GET',
      path: '/food-orders/:orderId/items',
      auth: false,
      handler: 'crud',
      entity: 'order_items',
      description: 'Get order items',
    },
    {
      method: 'POST',
      path: '/food-orders/:orderId/items',
      auth: false,
      handler: 'crud',
      entity: 'order_items',
      description: 'Add item to order',
    },
    {
      method: 'PUT',
      path: '/order-items/:id',
      auth: false,
      handler: 'crud',
      entity: 'order_items',
      description: 'Update order item',
    },
    {
      method: 'DELETE',
      path: '/order-items/:id',
      auth: false,
      handler: 'crud',
      entity: 'order_items',
      description: 'Remove order item',
    },

    // Delivery routes
    {
      method: 'GET',
      path: '/delivery-zones',
      auth: false,
      handler: 'crud',
      entity: 'delivery_zones',
      description: 'Get delivery zones',
    },
    {
      method: 'POST',
      path: '/delivery-zones/check',
      auth: false,
      handler: 'custom',
      entity: 'delivery_zones',
      description: 'Check if address is deliverable',
    },
    {
      method: 'GET',
      path: '/delivery-zones/:id/fee',
      auth: false,
      handler: 'custom',
      entity: 'delivery_zones',
      description: 'Get delivery fee',
    },

    // Order status routes
    {
      method: 'GET',
      path: '/order-status/:orderId',
      auth: false,
      handler: 'crud',
      entity: 'order_status',
      description: 'Get status history',
    },
  ],

  config: [
    {
      key: 'enableDelivery',
      label: 'Enable Delivery',
      type: 'boolean',
      default: true,
      description: 'Offer delivery option',
    },
    {
      key: 'enablePickup',
      label: 'Enable Pickup',
      type: 'boolean',
      default: true,
      description: 'Offer pickup option',
    },
    {
      key: 'enableDineIn',
      label: 'Enable Dine-In',
      type: 'boolean',
      default: false,
      description: 'Offer dine-in ordering',
    },
    {
      key: 'minOrderAmount',
      label: 'Minimum Order Amount',
      type: 'number',
      default: 0,
      description: 'Minimum order amount for checkout',
    },
    {
      key: 'deliveryFee',
      label: 'Base Delivery Fee',
      type: 'number',
      default: 2.99,
      description: 'Base delivery fee',
    },
    {
      key: 'freeDeliveryThreshold',
      label: 'Free Delivery Threshold',
      type: 'number',
      default: 25,
      description: 'Order amount for free delivery',
    },
    {
      key: 'prepTime',
      label: 'Default Prep Time (minutes)',
      type: 'number',
      default: 20,
      description: 'Default food preparation time',
    },
    {
      key: 'scheduledOrders',
      label: 'Allow Scheduled Orders',
      type: 'boolean',
      default: true,
      description: 'Allow customers to schedule orders',
    },
    {
      key: 'maxScheduleDays',
      label: 'Max Schedule Days',
      type: 'number',
      default: 7,
      description: 'How far in advance orders can be scheduled',
    },
    {
      key: 'orderNotifications',
      label: 'Order Notifications',
      type: 'boolean',
      default: true,
      description: 'Send SMS/email order updates',
    },
    {
      key: 'autoAcceptOrders',
      label: 'Auto-Accept Orders',
      type: 'boolean',
      default: false,
      description: 'Automatically accept incoming orders',
    },
    {
      key: 'tipsEnabled',
      label: 'Enable Tips',
      type: 'boolean',
      default: true,
      description: 'Allow customers to add tips',
    },
  ],
};
