/**
 * Guest Services Feature Definition
 *
 * Hotel guest services portal with service requests,
 * amenity booking, concierge, and guest preferences.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const GUEST_SERVICES_FEATURE: FeatureDefinition = {
  id: 'guest-services',
  name: 'Guest Services',
  category: 'hospitality',
  description: 'Guest portal with service requests, amenity booking, and concierge',
  icon: 'concierge-bell',

  includedInAppTypes: [
    'restaurant',
    'hotel',
    'cafe',
    'bar',
    'bakery',
    'catering',
    'food-truck',
    'hostel',
    'resort',
    'vacation-rental',
    'bed-and-breakfast',
    'boutique-hotel',
    'cruise-ship',
    'spa',
  ],

  activationKeywords: [
    'guest services',
    'room service',
    'concierge',
    'guest portal',
    'service request',
    'amenity booking',
    'guest preferences',
    'special requests',
    'hotel services',
    'guest experience',
    'vip services',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'guest-portal',
      route: '/guest',
      section: 'frontend',
      title: 'Guest Portal',
      authRequired: true,
      templateId: 'guest-portal',
      components: [
        'welcome-header',
        'quick-services',
        'my-requests',
        'recommendations',
      ],
      layout: 'default',
    },
    {
      id: 'service-requests',
      route: '/guest/requests',
      section: 'frontend',
      title: 'Service Requests',
      authRequired: true,
      templateId: 'service-requests',
      components: [
        'request-form',
        'request-history',
        'request-status',
        'service-categories',
      ],
      layout: 'default',
    },
    {
      id: 'amenity-booking',
      route: '/guest/amenities',
      section: 'frontend',
      title: 'Book Amenities',
      authRequired: true,
      templateId: 'amenity-booking',
      components: [
        'amenity-calendar',
        'amenity-list',
        'booking-form',
        'my-bookings',
      ],
      layout: 'default',
    },
    {
      id: 'concierge',
      route: '/guest/concierge',
      section: 'frontend',
      title: 'Concierge',
      authRequired: true,
      templateId: 'concierge',
      components: [
        'chat-widget',
        'recommendation-list',
        'local-attractions',
        'restaurant-reservations',
      ],
      layout: 'default',
    },
    {
      id: 'admin-guest-services',
      route: '/admin/guest-services',
      section: 'admin',
      title: 'Manage Guest Services',
      authRequired: true,
      templateId: 'admin-guest-services',
      components: [
        'requests-queue',
        'service-manager',
        'amenity-manager',
        'guest-profiles',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-requests',
      route: '/admin/guest-services/requests',
      section: 'admin',
      title: 'Service Requests',
      authRequired: true,
      templateId: 'admin-requests',
      components: [
        'requests-table',
        'request-detail',
        'assign-staff',
        'request-filters',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Guest portal components
    'welcome-header',
    'quick-services',
    'my-requests',
    'recommendations',

    // Request components
    'request-form',
    'request-history',
    'request-status',
    'service-categories',

    // Amenity components
    'amenity-calendar',
    'amenity-list',
    'booking-form',
    'my-bookings',

    // Concierge components
    'chat-widget',
    'recommendation-list',
    'local-attractions',
    'restaurant-reservations',

    // Admin components
    'requests-queue',
    'service-manager',
    'amenity-manager',
    'guest-profiles',
    'requests-table',
    'request-detail',
    'assign-staff',
    'request-filters',
  ],

  entities: [
    {
      name: 'service_requests',
      displayName: 'Service Requests',
      description: 'Guest service requests',
      isCore: true,
    },
    {
      name: 'guest_preferences',
      displayName: 'Guest Preferences',
      description: 'Stored guest preferences',
      isCore: true,
    },
    {
      name: 'amenity_bookings',
      displayName: 'Amenity Bookings',
      description: 'Bookings for hotel amenities',
      isCore: true,
    },
    {
      name: 'amenities',
      displayName: 'Amenities',
      description: 'Available hotel amenities',
      isCore: true,
    },
    {
      name: 'service_categories',
      displayName: 'Service Categories',
      description: 'Categories of guest services',
      isCore: false,
    },
    {
      name: 'concierge_messages',
      displayName: 'Concierge Messages',
      description: 'Guest-concierge communications',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Service request routes
    {
      method: 'GET',
      path: '/service-requests',
      auth: true,
      handler: 'crud',
      entity: 'service_requests',
      description: 'List service requests',
    },
    {
      method: 'POST',
      path: '/service-requests',
      auth: true,
      handler: 'crud',
      entity: 'service_requests',
      description: 'Create service request',
    },
    {
      method: 'GET',
      path: '/service-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'service_requests',
      description: 'Get request details',
    },
    {
      method: 'PUT',
      path: '/service-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'service_requests',
      description: 'Update request',
    },
    {
      method: 'DELETE',
      path: '/service-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'service_requests',
      description: 'Cancel request',
    },
    {
      method: 'POST',
      path: '/service-requests/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'service_requests',
      description: 'Complete request',
    },
    {
      method: 'POST',
      path: '/service-requests/:id/assign',
      auth: true,
      handler: 'custom',
      entity: 'service_requests',
      description: 'Assign to staff',
    },
    {
      method: 'GET',
      path: '/service-requests/my-requests',
      auth: true,
      handler: 'custom',
      entity: 'service_requests',
      description: 'Get my requests',
    },

    // Guest preferences routes
    {
      method: 'GET',
      path: '/guest-preferences',
      auth: true,
      handler: 'crud',
      entity: 'guest_preferences',
      description: 'Get guest preferences',
    },
    {
      method: 'PUT',
      path: '/guest-preferences',
      auth: true,
      handler: 'crud',
      entity: 'guest_preferences',
      description: 'Update preferences',
    },
    {
      method: 'GET',
      path: '/guest-preferences/:guestId',
      auth: true,
      handler: 'crud',
      entity: 'guest_preferences',
      description: 'Get guest preferences by ID',
    },

    // Amenity booking routes
    {
      method: 'GET',
      path: '/amenity-bookings',
      auth: true,
      handler: 'crud',
      entity: 'amenity_bookings',
      description: 'List amenity bookings',
    },
    {
      method: 'POST',
      path: '/amenity-bookings',
      auth: true,
      handler: 'crud',
      entity: 'amenity_bookings',
      description: 'Create booking',
    },
    {
      method: 'GET',
      path: '/amenity-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'amenity_bookings',
      description: 'Get booking details',
    },
    {
      method: 'PUT',
      path: '/amenity-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'amenity_bookings',
      description: 'Update booking',
    },
    {
      method: 'DELETE',
      path: '/amenity-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'amenity_bookings',
      description: 'Cancel booking',
    },
    {
      method: 'GET',
      path: '/amenity-bookings/availability',
      auth: true,
      handler: 'custom',
      entity: 'amenity_bookings',
      description: 'Check availability',
    },

    // Amenity routes
    {
      method: 'GET',
      path: '/amenities',
      auth: false,
      handler: 'crud',
      entity: 'amenities',
      description: 'List amenities',
    },
    {
      method: 'POST',
      path: '/amenities',
      auth: true,
      handler: 'crud',
      entity: 'amenities',
      description: 'Create amenity',
    },
    {
      method: 'PUT',
      path: '/amenities/:id',
      auth: true,
      handler: 'crud',
      entity: 'amenities',
      description: 'Update amenity',
    },
    {
      method: 'DELETE',
      path: '/amenities/:id',
      auth: true,
      handler: 'crud',
      entity: 'amenities',
      description: 'Delete amenity',
    },
  ],

  config: [
    {
      key: 'enableChat',
      label: 'Enable Concierge Chat',
      type: 'boolean',
      default: true,
      description: 'Enable live chat with concierge',
    },
    {
      key: 'requestTimeout',
      label: 'Request Response Time (minutes)',
      type: 'number',
      default: 15,
      description: 'Target response time for requests',
    },
    {
      key: 'savePreferences',
      label: 'Save Guest Preferences',
      type: 'boolean',
      default: true,
      description: 'Remember guest preferences for future stays',
    },
    {
      key: 'roomServiceHours',
      label: 'Room Service Hours',
      type: 'string',
      default: '06:00-23:00',
      description: 'Hours for room service availability',
    },
    {
      key: 'requireRoomVerification',
      label: 'Require Room Verification',
      type: 'boolean',
      default: true,
      description: 'Verify guest room before processing requests',
    },
    {
      key: 'vipPriority',
      label: 'VIP Priority',
      type: 'boolean',
      default: true,
      description: 'Prioritize VIP guest requests',
    },
    {
      key: 'pushNotifications',
      label: 'Push Notifications',
      type: 'boolean',
      default: true,
      description: 'Send push notifications for request updates',
    },
    {
      key: 'feedbackRequired',
      label: 'Feedback Required',
      type: 'boolean',
      default: false,
      description: 'Request feedback after service completion',
    },
  ],
};
