/**
 * POS System Feature Definition
 *
 * Point of sale system for restaurants and hospitality venues
 * with order entry, payment processing, and end-of-day reporting.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const POS_SYSTEM_FEATURE: FeatureDefinition = {
  id: 'pos-system',
  name: 'Point of Sale',
  category: 'hospitality',
  description: 'POS terminal with order entry, payments, cash drawer, and reporting',
  icon: 'cash-register',

  includedInAppTypes: [
    'restaurant',
    'hotel',
    'cafe',
    'bar',
    'bakery',
    'catering',
    'food-truck',
    'hostel',
    'resort',
    'vacation-rental',
    'fine-dining',
    'bistro',
    'pub',
    'pizzeria',
    'fast-food',
    'retail',
  ],

  activationKeywords: [
    'pos',
    'point of sale',
    'cash register',
    'checkout',
    'payment terminal',
    'order entry',
    'cash drawer',
    'till',
    'register',
    'payment processing',
    'square',
    'clover',
    'toast pos',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'pos-terminal',
      route: '/pos',
      section: 'admin',
      title: 'POS Terminal',
      authRequired: true,
      templateId: 'pos-terminal',
      components: [
        'product-grid',
        'cart-display',
        'quick-keys',
        'payment-panel',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'order-entry',
      route: '/pos/order',
      section: 'admin',
      title: 'Order Entry',
      authRequired: true,
      templateId: 'order-entry',
      components: [
        'menu-grid',
        'order-builder',
        'modifier-selector',
        'seat-assignment',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'cash-drawer',
      route: '/pos/cash',
      section: 'admin',
      title: 'Cash Drawer',
      authRequired: true,
      templateId: 'cash-drawer',
      components: [
        'drawer-status',
        'cash-count',
        'drop-form',
        'payout-form',
      ],
      layout: 'admin',
    },
    {
      id: 'end-of-day',
      route: '/pos/eod',
      section: 'admin',
      title: 'End of Day',
      authRequired: true,
      templateId: 'end-of-day',
      components: [
        'sales-summary',
        'payment-breakdown',
        'closeout-form',
        'variance-report',
      ],
      layout: 'admin',
    },
    {
      id: 'pos-reports',
      route: '/admin/pos/reports',
      section: 'admin',
      title: 'POS Reports',
      authRequired: true,
      templateId: 'pos-reports',
      components: [
        'sales-report',
        'item-report',
        'employee-report',
        'hourly-report',
      ],
      layout: 'admin',
    },
    {
      id: 'pos-settings',
      route: '/admin/pos/settings',
      section: 'admin',
      title: 'POS Settings',
      authRequired: true,
      templateId: 'pos-settings',
      components: [
        'terminal-config',
        'receipt-settings',
        'tax-settings',
        'payment-methods',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Terminal components
    'product-grid',
    'cart-display',
    'quick-keys',
    'payment-panel',
    'payment-terminal',

    // Order components
    'menu-grid',
    'order-builder',
    'modifier-selector',
    'seat-assignment',
    'order-ticket',

    // Cash management components
    'drawer-status',
    'cash-count',
    'drop-form',
    'payout-form',
    'receipt-printer',

    // EOD components
    'sales-summary',
    'payment-breakdown',
    'closeout-form',
    'variance-report',

    // Report components
    'sales-report',
    'item-report',
    'employee-report',
    'hourly-report',

    // Settings components
    'terminal-config',
    'receipt-settings',
    'tax-settings',
    'payment-methods',
  ],

  entities: [
    {
      name: 'pos_orders',
      displayName: 'POS Orders',
      description: 'Point of sale orders',
      isCore: true,
    },
    {
      name: 'transactions',
      displayName: 'Transactions',
      description: 'Payment transactions',
      isCore: true,
    },
    {
      name: 'cash_sessions',
      displayName: 'Cash Sessions',
      description: 'Cash drawer sessions',
      isCore: true,
    },
    {
      name: 'receipts',
      displayName: 'Receipts',
      description: 'Transaction receipts',
      isCore: true,
    },
    {
      name: 'cash_movements',
      displayName: 'Cash Movements',
      description: 'Cash drops and payouts',
      isCore: false,
    },
    {
      name: 'pos_terminals',
      displayName: 'POS Terminals',
      description: 'Registered terminals',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Order routes
    {
      method: 'GET',
      path: '/pos-orders',
      auth: true,
      handler: 'crud',
      entity: 'pos_orders',
      description: 'List orders',
    },
    {
      method: 'POST',
      path: '/pos-orders',
      auth: true,
      handler: 'crud',
      entity: 'pos_orders',
      description: 'Create order',
    },
    {
      method: 'GET',
      path: '/pos-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'pos_orders',
      description: 'Get order details',
    },
    {
      method: 'PUT',
      path: '/pos-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'pos_orders',
      description: 'Update order',
    },
    {
      method: 'DELETE',
      path: '/pos-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'pos_orders',
      description: 'Void order',
    },
    {
      method: 'POST',
      path: '/pos-orders/:id/pay',
      auth: true,
      handler: 'custom',
      entity: 'pos_orders',
      description: 'Process payment',
    },
    {
      method: 'POST',
      path: '/pos-orders/:id/split',
      auth: true,
      handler: 'custom',
      entity: 'pos_orders',
      description: 'Split check',
    },
    {
      method: 'POST',
      path: '/pos-orders/:id/print',
      auth: true,
      handler: 'custom',
      entity: 'pos_orders',
      description: 'Print receipt',
    },

    // Transaction routes
    {
      method: 'GET',
      path: '/transactions',
      auth: true,
      handler: 'crud',
      entity: 'transactions',
      description: 'List transactions',
    },
    {
      method: 'POST',
      path: '/transactions',
      auth: true,
      handler: 'crud',
      entity: 'transactions',
      description: 'Create transaction',
    },
    {
      method: 'GET',
      path: '/transactions/:id',
      auth: true,
      handler: 'crud',
      entity: 'transactions',
      description: 'Get transaction details',
    },
    {
      method: 'POST',
      path: '/transactions/:id/refund',
      auth: true,
      handler: 'custom',
      entity: 'transactions',
      description: 'Process refund',
    },
    {
      method: 'POST',
      path: '/transactions/:id/void',
      auth: true,
      handler: 'custom',
      entity: 'transactions',
      description: 'Void transaction',
    },

    // Cash session routes
    {
      method: 'GET',
      path: '/cash-sessions',
      auth: true,
      handler: 'crud',
      entity: 'cash_sessions',
      description: 'List cash sessions',
    },
    {
      method: 'POST',
      path: '/cash-sessions/open',
      auth: true,
      handler: 'custom',
      entity: 'cash_sessions',
      description: 'Open cash session',
    },
    {
      method: 'POST',
      path: '/cash-sessions/:id/close',
      auth: true,
      handler: 'custom',
      entity: 'cash_sessions',
      description: 'Close cash session',
    },
    {
      method: 'POST',
      path: '/cash-sessions/:id/drop',
      auth: true,
      handler: 'custom',
      entity: 'cash_sessions',
      description: 'Cash drop',
    },
    {
      method: 'POST',
      path: '/cash-sessions/:id/payout',
      auth: true,
      handler: 'custom',
      entity: 'cash_sessions',
      description: 'Cash payout',
    },
    {
      method: 'GET',
      path: '/cash-sessions/:id/count',
      auth: true,
      handler: 'custom',
      entity: 'cash_sessions',
      description: 'Get cash count',
    },

    // Receipt routes
    {
      method: 'GET',
      path: '/receipts',
      auth: true,
      handler: 'crud',
      entity: 'receipts',
      description: 'List receipts',
    },
    {
      method: 'GET',
      path: '/receipts/:id',
      auth: true,
      handler: 'crud',
      entity: 'receipts',
      description: 'Get receipt',
    },
    {
      method: 'POST',
      path: '/receipts/:id/email',
      auth: true,
      handler: 'custom',
      entity: 'receipts',
      description: 'Email receipt',
    },
  ],

  config: [
    {
      key: 'taxRate',
      label: 'Tax Rate (%)',
      type: 'number',
      default: 8.5,
      description: 'Default tax rate for orders',
    },
    {
      key: 'tipEnabled',
      label: 'Enable Tips',
      type: 'boolean',
      default: true,
      description: 'Allow tip entry at checkout',
    },
    {
      key: 'tipSuggestions',
      label: 'Tip Suggestions',
      type: 'string',
      default: '15,18,20,25',
      description: 'Suggested tip percentages',
    },
    {
      key: 'requireCashCount',
      label: 'Require Cash Count',
      type: 'boolean',
      default: true,
      description: 'Require cash count at session open/close',
    },
    {
      key: 'printReceipt',
      label: 'Auto-Print Receipt',
      type: 'boolean',
      default: true,
      description: 'Automatically print receipt after payment',
    },
    {
      key: 'emailReceipt',
      label: 'Offer Email Receipt',
      type: 'boolean',
      default: true,
      description: 'Offer to email receipts',
    },
    {
      key: 'splitCheckEnabled',
      label: 'Enable Split Checks',
      type: 'boolean',
      default: true,
      description: 'Allow splitting checks',
    },
    {
      key: 'requireManagerVoid',
      label: 'Require Manager for Voids',
      type: 'boolean',
      default: true,
      description: 'Require manager approval for voids',
    },
    {
      key: 'refundLimit',
      label: 'Refund Limit ($)',
      type: 'number',
      default: 100,
      description: 'Maximum refund without manager approval',
    },
    {
      key: 'drawerAlertThreshold',
      label: 'Drawer Alert Threshold ($)',
      type: 'number',
      default: 500,
      description: 'Alert when drawer exceeds this amount',
    },
  ],
};
