/**
 * Rate Management Feature Definition
 *
 * Dynamic pricing and rate management with yield management,
 * seasonal pricing, promotions, and rate rules.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const RATE_MANAGEMENT_FEATURE: FeatureDefinition = {
  id: 'rate-management',
  name: 'Rate Management',
  category: 'hospitality',
  description: 'Dynamic pricing with yield management, seasonal rates, and promotions',
  icon: 'chart-line',

  includedInAppTypes: [
    'restaurant',
    'hotel',
    'cafe',
    'bar',
    'bakery',
    'catering',
    'food-truck',
    'hostel',
    'resort',
    'vacation-rental',
    'bed-and-breakfast',
    'motel',
    'boutique-hotel',
    'car-rental',
    'equipment-rental',
  ],

  activationKeywords: [
    'rate management',
    'dynamic pricing',
    'yield management',
    'revenue management',
    'seasonal pricing',
    'promotions',
    'rate rules',
    'pricing strategy',
    'occupancy-based pricing',
    'demand pricing',
    'rate optimizer',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'rate-calendar',
      route: '/admin/rates/calendar',
      section: 'admin',
      title: 'Rate Calendar',
      authRequired: true,
      templateId: 'rate-calendar',
      components: [
        'rate-grid',
        'date-range-picker',
        'bulk-rate-editor',
        'rate-legend',
      ],
      layout: 'admin',
    },
    {
      id: 'rate-rules',
      route: '/admin/rates/rules',
      section: 'admin',
      title: 'Rate Rules',
      authRequired: true,
      templateId: 'rate-rules',
      components: [
        'rule-builder',
        'rule-list',
        'rule-priority',
        'rule-preview',
      ],
      layout: 'admin',
    },
    {
      id: 'seasonal-pricing',
      route: '/admin/rates/seasons',
      section: 'admin',
      title: 'Seasonal Pricing',
      authRequired: true,
      templateId: 'seasonal-pricing',
      components: [
        'season-calendar',
        'season-form',
        'season-rates',
        'holiday-manager',
      ],
      layout: 'admin',
    },
    {
      id: 'promotions',
      route: '/admin/rates/promotions',
      section: 'admin',
      title: 'Promotions',
      authRequired: true,
      templateId: 'promotions',
      components: [
        'promo-form',
        'promo-list',
        'promo-codes',
        'promo-analytics',
      ],
      layout: 'admin',
    },
    {
      id: 'yield-dashboard',
      route: '/admin/rates/yield',
      section: 'admin',
      title: 'Yield Management',
      authRequired: true,
      templateId: 'yield-dashboard',
      components: [
        'yield-chart',
        'occupancy-forecast',
        'rate-recommendations',
        'competitor-rates',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calendar components
    'rate-grid',
    'date-range-picker',
    'bulk-rate-editor',
    'rate-legend',

    // Rule components
    'rule-builder',
    'rule-list',
    'rule-priority',
    'rule-preview',
    'condition-builder',

    // Season components
    'season-calendar',
    'season-form',
    'season-rates',
    'holiday-manager',

    // Promotion components
    'promo-form',
    'promo-list',
    'promo-codes',
    'promo-analytics',

    // Yield components
    'yield-chart',
    'occupancy-forecast',
    'rate-recommendations',
    'competitor-rates',
    'revenue-stats',
  ],

  entities: [
    {
      name: 'rates',
      displayName: 'Rates',
      description: 'Base rates for rooms/services',
      isCore: true,
    },
    {
      name: 'rate_rules',
      displayName: 'Rate Rules',
      description: 'Dynamic pricing rules',
      isCore: true,
    },
    {
      name: 'seasons',
      displayName: 'Seasons',
      description: 'Seasonal rate periods',
      isCore: true,
    },
    {
      name: 'promotions',
      displayName: 'Promotions',
      description: 'Promotional offers and discounts',
      isCore: true,
    },
    {
      name: 'rate_history',
      displayName: 'Rate History',
      description: 'Historical rate data',
      isCore: false,
    },
    {
      name: 'promo_codes',
      displayName: 'Promo Codes',
      description: 'Promotional code definitions',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Rate routes
    {
      method: 'GET',
      path: '/rates',
      auth: true,
      handler: 'crud',
      entity: 'rates',
      description: 'List rates',
    },
    {
      method: 'POST',
      path: '/rates',
      auth: true,
      handler: 'crud',
      entity: 'rates',
      description: 'Create rate',
    },
    {
      method: 'GET',
      path: '/rates/:id',
      auth: true,
      handler: 'crud',
      entity: 'rates',
      description: 'Get rate details',
    },
    {
      method: 'PUT',
      path: '/rates/:id',
      auth: true,
      handler: 'crud',
      entity: 'rates',
      description: 'Update rate',
    },
    {
      method: 'DELETE',
      path: '/rates/:id',
      auth: true,
      handler: 'crud',
      entity: 'rates',
      description: 'Delete rate',
    },
    {
      method: 'PUT',
      path: '/rates/bulk',
      auth: true,
      handler: 'custom',
      entity: 'rates',
      description: 'Bulk update rates',
    },
    {
      method: 'GET',
      path: '/rates/calendar',
      auth: true,
      handler: 'custom',
      entity: 'rates',
      description: 'Get rate calendar',
    },
    {
      method: 'GET',
      path: '/rates/calculate',
      auth: false,
      handler: 'custom',
      entity: 'rates',
      description: 'Calculate rate for dates',
    },

    // Rate rules routes
    {
      method: 'GET',
      path: '/rate-rules',
      auth: true,
      handler: 'crud',
      entity: 'rate_rules',
      description: 'List rate rules',
    },
    {
      method: 'POST',
      path: '/rate-rules',
      auth: true,
      handler: 'crud',
      entity: 'rate_rules',
      description: 'Create rate rule',
    },
    {
      method: 'PUT',
      path: '/rate-rules/:id',
      auth: true,
      handler: 'crud',
      entity: 'rate_rules',
      description: 'Update rate rule',
    },
    {
      method: 'DELETE',
      path: '/rate-rules/:id',
      auth: true,
      handler: 'crud',
      entity: 'rate_rules',
      description: 'Delete rate rule',
    },
    {
      method: 'PUT',
      path: '/rate-rules/reorder',
      auth: true,
      handler: 'custom',
      entity: 'rate_rules',
      description: 'Reorder rules priority',
    },
    {
      method: 'POST',
      path: '/rate-rules/:id/toggle',
      auth: true,
      handler: 'custom',
      entity: 'rate_rules',
      description: 'Toggle rule active status',
    },

    // Season routes
    {
      method: 'GET',
      path: '/seasons',
      auth: true,
      handler: 'crud',
      entity: 'seasons',
      description: 'List seasons',
    },
    {
      method: 'POST',
      path: '/seasons',
      auth: true,
      handler: 'crud',
      entity: 'seasons',
      description: 'Create season',
    },
    {
      method: 'PUT',
      path: '/seasons/:id',
      auth: true,
      handler: 'crud',
      entity: 'seasons',
      description: 'Update season',
    },
    {
      method: 'DELETE',
      path: '/seasons/:id',
      auth: true,
      handler: 'crud',
      entity: 'seasons',
      description: 'Delete season',
    },

    // Promotion routes
    {
      method: 'GET',
      path: '/promotions',
      auth: true,
      handler: 'crud',
      entity: 'promotions',
      description: 'List promotions',
    },
    {
      method: 'POST',
      path: '/promotions',
      auth: true,
      handler: 'crud',
      entity: 'promotions',
      description: 'Create promotion',
    },
    {
      method: 'GET',
      path: '/promotions/:id',
      auth: true,
      handler: 'crud',
      entity: 'promotions',
      description: 'Get promotion details',
    },
    {
      method: 'PUT',
      path: '/promotions/:id',
      auth: true,
      handler: 'crud',
      entity: 'promotions',
      description: 'Update promotion',
    },
    {
      method: 'DELETE',
      path: '/promotions/:id',
      auth: true,
      handler: 'crud',
      entity: 'promotions',
      description: 'Delete promotion',
    },
    {
      method: 'POST',
      path: '/promotions/validate',
      auth: false,
      handler: 'custom',
      entity: 'promotions',
      description: 'Validate promo code',
    },
    {
      method: 'GET',
      path: '/promotions/:id/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'promotions',
      description: 'Get promotion analytics',
    },
  ],

  config: [
    {
      key: 'dynamicPricing',
      label: 'Enable Dynamic Pricing',
      type: 'boolean',
      default: true,
      description: 'Automatically adjust rates based on demand',
    },
    {
      key: 'minRate',
      label: 'Minimum Rate',
      type: 'number',
      default: 0,
      description: 'Minimum allowed rate (0 = no minimum)',
    },
    {
      key: 'maxRateIncrease',
      label: 'Maximum Rate Increase (%)',
      type: 'number',
      default: 200,
      description: 'Maximum percentage increase from base rate',
    },
    {
      key: 'maxRateDecrease',
      label: 'Maximum Rate Decrease (%)',
      type: 'number',
      default: 50,
      description: 'Maximum percentage decrease from base rate',
    },
    {
      key: 'occupancyThreshold',
      label: 'Occupancy Threshold (%)',
      type: 'number',
      default: 70,
      description: 'Occupancy level to trigger rate increase',
    },
    {
      key: 'lastMinuteDiscount',
      label: 'Last Minute Discount (%)',
      type: 'number',
      default: 10,
      description: 'Discount for last-minute bookings',
    },
    {
      key: 'earlyBirdDiscount',
      label: 'Early Bird Discount (%)',
      type: 'number',
      default: 15,
      description: 'Discount for advance bookings',
    },
    {
      key: 'earlyBirdDays',
      label: 'Early Bird Days',
      type: 'number',
      default: 30,
      description: 'Days in advance for early bird discount',
    },
    {
      key: 'lengthOfStayDiscount',
      label: 'Length of Stay Discount',
      type: 'boolean',
      default: true,
      description: 'Offer discounts for longer stays',
    },
    {
      key: 'weekendPremium',
      label: 'Weekend Premium (%)',
      type: 'number',
      default: 10,
      description: 'Rate increase for weekends',
    },
  ],
};
