/**
 * Room Booking Feature Definition
 *
 * Hotel room reservation system with availability search,
 * booking wizard, rate management, and calendar views.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const ROOM_BOOKING_FEATURE: FeatureDefinition = {
  id: 'room-booking',
  name: 'Room Booking',
  category: 'hospitality',
  description: 'Hotel room reservation with availability search, booking wizard, and rate management',
  icon: 'bed',

  includedInAppTypes: [
    'restaurant',
    'hotel',
    'cafe',
    'bar',
    'bakery',
    'catering',
    'food-truck',
    'hostel',
    'resort',
    'vacation-rental',
    'bed-and-breakfast',
    'motel',
    'boutique-hotel',
    'inn',
    'lodge',
    'guest-house',
  ],

  activationKeywords: [
    'room booking',
    'hotel reservation',
    'book room',
    'room availability',
    'hotel rooms',
    'accommodation',
    'check-in',
    'check-out',
    'room types',
    'room rates',
    'booking engine',
    'property management',
    'pms',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'room-search',
      route: '/rooms',
      section: 'frontend',
      title: 'Find a Room',
      authRequired: false,
      templateId: 'room-search',
      components: [
        'date-range-selector',
        'guest-count-picker',
        'room-type-filter',
        'room-results-grid',
        'price-filter',
      ],
      layout: 'default',
    },
    {
      id: 'booking-wizard',
      route: '/book/:roomId',
      section: 'frontend',
      title: 'Book Your Stay',
      authRequired: false,
      templateId: 'booking-wizard',
      components: [
        'room-summary',
        'guest-info-form',
        'payment-step',
        'booking-confirmation',
        'extras-selector',
      ],
      layout: 'default',
    },
    {
      id: 'room-calendar',
      route: '/admin/rooms/calendar',
      section: 'admin',
      title: 'Room Calendar',
      authRequired: true,
      templateId: 'room-calendar',
      components: [
        'availability-calendar',
        'booking-blocks',
        'quick-reservation',
        'room-status-legend',
      ],
      layout: 'admin',
    },
    {
      id: 'rate-manager',
      route: '/admin/rates',
      section: 'admin',
      title: 'Rate Manager',
      authRequired: true,
      templateId: 'rate-manager',
      components: [
        'rate-display',
        'rate-editor',
        'seasonal-rates',
        'rate-calendar',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-rooms',
      route: '/admin/rooms',
      section: 'admin',
      title: 'Manage Rooms',
      authRequired: true,
      templateId: 'admin-rooms',
      components: [
        'rooms-grid',
        'room-form',
        'room-type-manager',
        'amenities-list',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-bookings',
      route: '/admin/bookings',
      section: 'admin',
      title: 'Manage Bookings',
      authRequired: true,
      templateId: 'admin-bookings',
      components: [
        'bookings-table',
        'booking-detail',
        'check-in-out',
        'booking-filters',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Search components
    'room-picker',
    'date-range-selector',
    'guest-count-picker',
    'room-type-filter',
    'room-results-grid',
    'price-filter',

    // Booking components
    'room-summary',
    'guest-info-form',
    'payment-step',
    'booking-confirmation',
    'extras-selector',

    // Rate components
    'rate-display',
    'rate-editor',
    'seasonal-rates',
    'rate-calendar',

    // Room management components
    'rooms-grid',
    'room-form',
    'room-type-manager',
    'amenities-list',
    'room-photos',

    // Calendar components
    'availability-calendar',
    'booking-blocks',
    'quick-reservation',
    'room-status-legend',

    // Admin components
    'bookings-table',
    'booking-detail',
    'check-in-out',
    'booking-filters',
  ],

  entities: [
    {
      name: 'rooms',
      displayName: 'Rooms',
      description: 'Hotel rooms with details and amenities',
      isCore: true,
    },
    {
      name: 'room_bookings',
      displayName: 'Room Bookings',
      description: 'Guest room reservations',
      isCore: true,
    },
    {
      name: 'room_rates',
      displayName: 'Room Rates',
      description: 'Pricing for rooms',
      isCore: true,
    },
    {
      name: 'room_types',
      displayName: 'Room Types',
      description: 'Categories of rooms',
      isCore: true,
    },
    {
      name: 'room_amenities',
      displayName: 'Room Amenities',
      description: 'Amenities available in rooms',
      isCore: false,
    },
    {
      name: 'booking_extras',
      displayName: 'Booking Extras',
      description: 'Additional services with bookings',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Room routes
    {
      method: 'GET',
      path: '/rooms',
      auth: false,
      handler: 'crud',
      entity: 'rooms',
      description: 'List rooms',
    },
    {
      method: 'POST',
      path: '/rooms',
      auth: true,
      handler: 'crud',
      entity: 'rooms',
      description: 'Create room',
    },
    {
      method: 'GET',
      path: '/rooms/:id',
      auth: false,
      handler: 'crud',
      entity: 'rooms',
      description: 'Get room details',
    },
    {
      method: 'PUT',
      path: '/rooms/:id',
      auth: true,
      handler: 'crud',
      entity: 'rooms',
      description: 'Update room',
    },
    {
      method: 'DELETE',
      path: '/rooms/:id',
      auth: true,
      handler: 'crud',
      entity: 'rooms',
      description: 'Delete room',
    },
    {
      method: 'GET',
      path: '/rooms/availability',
      auth: false,
      handler: 'custom',
      entity: 'rooms',
      description: 'Search available rooms',
    },

    // Booking routes
    {
      method: 'GET',
      path: '/room-bookings',
      auth: true,
      handler: 'crud',
      entity: 'room_bookings',
      description: 'List bookings',
    },
    {
      method: 'POST',
      path: '/room-bookings',
      auth: false,
      handler: 'crud',
      entity: 'room_bookings',
      description: 'Create booking',
    },
    {
      method: 'GET',
      path: '/room-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'room_bookings',
      description: 'Get booking details',
    },
    {
      method: 'PUT',
      path: '/room-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'room_bookings',
      description: 'Update booking',
    },
    {
      method: 'DELETE',
      path: '/room-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'room_bookings',
      description: 'Cancel booking',
    },
    {
      method: 'POST',
      path: '/room-bookings/:id/check-in',
      auth: true,
      handler: 'custom',
      entity: 'room_bookings',
      description: 'Check in guest',
    },
    {
      method: 'POST',
      path: '/room-bookings/:id/check-out',
      auth: true,
      handler: 'custom',
      entity: 'room_bookings',
      description: 'Check out guest',
    },
    {
      method: 'POST',
      path: '/room-bookings/:id/extend',
      auth: true,
      handler: 'custom',
      entity: 'room_bookings',
      description: 'Extend stay',
    },

    // Rate routes
    {
      method: 'GET',
      path: '/room-rates',
      auth: false,
      handler: 'crud',
      entity: 'room_rates',
      description: 'List rates',
    },
    {
      method: 'POST',
      path: '/room-rates',
      auth: true,
      handler: 'crud',
      entity: 'room_rates',
      description: 'Create rate',
    },
    {
      method: 'PUT',
      path: '/room-rates/:id',
      auth: true,
      handler: 'crud',
      entity: 'room_rates',
      description: 'Update rate',
    },
    {
      method: 'DELETE',
      path: '/room-rates/:id',
      auth: true,
      handler: 'crud',
      entity: 'room_rates',
      description: 'Delete rate',
    },
    {
      method: 'GET',
      path: '/room-rates/calendar',
      auth: true,
      handler: 'custom',
      entity: 'room_rates',
      description: 'Get rate calendar',
    },

    // Room type routes
    {
      method: 'GET',
      path: '/room-types',
      auth: false,
      handler: 'crud',
      entity: 'room_types',
      description: 'List room types',
    },
    {
      method: 'POST',
      path: '/room-types',
      auth: true,
      handler: 'crud',
      entity: 'room_types',
      description: 'Create room type',
    },
    {
      method: 'PUT',
      path: '/room-types/:id',
      auth: true,
      handler: 'crud',
      entity: 'room_types',
      description: 'Update room type',
    },
    {
      method: 'DELETE',
      path: '/room-types/:id',
      auth: true,
      handler: 'crud',
      entity: 'room_types',
      description: 'Delete room type',
    },
  ],

  config: [
    {
      key: 'checkInTime',
      label: 'Check-In Time',
      type: 'string',
      default: '15:00',
      description: 'Standard check-in time',
    },
    {
      key: 'checkOutTime',
      label: 'Check-Out Time',
      type: 'string',
      default: '11:00',
      description: 'Standard check-out time',
    },
    {
      key: 'minStayNights',
      label: 'Minimum Stay (nights)',
      type: 'number',
      default: 1,
      description: 'Minimum number of nights per booking',
    },
    {
      key: 'maxStayNights',
      label: 'Maximum Stay (nights)',
      type: 'number',
      default: 30,
      description: 'Maximum number of nights per booking',
    },
    {
      key: 'advanceBookingDays',
      label: 'Advance Booking (days)',
      type: 'number',
      default: 365,
      description: 'How far in advance rooms can be booked',
    },
    {
      key: 'cancellationPolicy',
      label: 'Cancellation Policy (hours)',
      type: 'number',
      default: 48,
      description: 'Hours before check-in for free cancellation',
    },
    {
      key: 'requireDeposit',
      label: 'Require Deposit',
      type: 'boolean',
      default: true,
      description: 'Require deposit at booking',
    },
    {
      key: 'depositPercentage',
      label: 'Deposit Percentage',
      type: 'number',
      default: 20,
      description: 'Percentage of total for deposit',
    },
    {
      key: 'allowEarlyCheckIn',
      label: 'Allow Early Check-In',
      type: 'boolean',
      default: true,
      description: 'Allow guests to request early check-in',
    },
    {
      key: 'allowLateCheckOut',
      label: 'Allow Late Check-Out',
      type: 'boolean',
      default: true,
      description: 'Allow guests to request late check-out',
    },
  ],
};
