/**
 * Table Reservations Feature Definition
 *
 * Restaurant table booking functionality with floor plan management,
 * waitlist handling, and party size optimization.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TABLE_RESERVATIONS_FEATURE: FeatureDefinition = {
  id: 'table-reservations',
  name: 'Table Reservations',
  category: 'hospitality',
  description: 'Restaurant table booking with floor plan, waitlist, and party management',
  icon: 'utensils',

  includedInAppTypes: [
    'restaurant',
    'hotel',
    'cafe',
    'bar',
    'bakery',
    'catering',
    'food-truck',
    'hostel',
    'resort',
    'vacation-rental',
    'fine-dining',
    'bistro',
    'pub',
    'club',
    'lounge',
  ],

  activationKeywords: [
    'table reservation',
    'table booking',
    'reserve table',
    'book table',
    'restaurant reservation',
    'dining reservation',
    'floor plan',
    'waitlist',
    'party size',
    'seating',
    'opentable',
    'resy',
    'yelp reservations',
    'table management',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'reservation-widget',
      route: '/reserve',
      section: 'frontend',
      title: 'Make a Reservation',
      authRequired: false,
      templateId: 'reservation-widget',
      components: [
        'booking-form',
        'date-picker',
        'time-slots',
        'party-size-selector',
        'special-requests',
      ],
      layout: 'default',
    },
    {
      id: 'reservations-list',
      route: '/reservations',
      section: 'frontend',
      title: 'My Reservations',
      authRequired: true,
      templateId: 'reservations-list',
      components: [
        'reservation-card',
        'reservation-filters',
        'date-filter',
        'status-badge',
      ],
      layout: 'default',
    },
    {
      id: 'floor-plan',
      route: '/admin/floor-plan',
      section: 'admin',
      title: 'Floor Plan Manager',
      authRequired: true,
      templateId: 'floor-plan',
      components: [
        'floor-plan-editor',
        'table-picker',
        'table-status-grid',
        'drag-drop-tables',
        'zone-manager',
      ],
      layout: 'admin',
    },
    {
      id: 'waitlist',
      route: '/admin/waitlist',
      section: 'admin',
      title: 'Waitlist Management',
      authRequired: true,
      templateId: 'waitlist',
      components: [
        'waitlist-display',
        'waitlist-entry-form',
        'estimated-wait-time',
        'sms-notification',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-reservations',
      route: '/admin/reservations',
      section: 'admin',
      title: 'Manage Reservations',
      authRequired: true,
      templateId: 'admin-reservations',
      components: [
        'reservations-calendar',
        'reservations-table',
        'quick-book',
        'bulk-actions',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Booking components
    'booking-form',
    'table-picker',
    'time-slots',
    'party-size-selector',
    'date-picker',
    'special-requests',
    'reservation-confirmation',

    // Display components
    'reservation-card',
    'reservation-filters',
    'waitlist-display',
    'waitlist-entry-form',
    'estimated-wait-time',
    'status-badge',

    // Floor plan components
    'floor-plan-editor',
    'table-status-grid',
    'drag-drop-tables',
    'zone-manager',

    // Admin components
    'reservations-calendar',
    'reservations-table',
    'quick-book',
    'bulk-actions',
    'sms-notification',
    'date-filter',
  ],

  entities: [
    {
      name: 'reservations',
      displayName: 'Reservations',
      description: 'Table reservation bookings',
      isCore: true,
    },
    {
      name: 'tables',
      displayName: 'Tables',
      description: 'Restaurant tables with capacity and location',
      isCore: true,
    },
    {
      name: 'floor_plans',
      displayName: 'Floor Plans',
      description: 'Restaurant floor layout configurations',
      isCore: true,
    },
    {
      name: 'waitlist_entries',
      displayName: 'Waitlist Entries',
      description: 'Guests waiting for tables',
      isCore: true,
    },
    {
      name: 'table_zones',
      displayName: 'Table Zones',
      description: 'Sections/zones in the restaurant',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Reservation routes
    {
      method: 'GET',
      path: '/reservations',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'List reservations',
    },
    {
      method: 'POST',
      path: '/reservations',
      auth: false,
      handler: 'crud',
      entity: 'reservations',
      description: 'Create reservation',
    },
    {
      method: 'GET',
      path: '/reservations/:id',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'Get reservation details',
    },
    {
      method: 'PUT',
      path: '/reservations/:id',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'Update reservation',
    },
    {
      method: 'DELETE',
      path: '/reservations/:id',
      auth: true,
      handler: 'crud',
      entity: 'reservations',
      description: 'Cancel reservation',
    },
    {
      method: 'POST',
      path: '/reservations/:id/confirm',
      auth: true,
      handler: 'custom',
      entity: 'reservations',
      description: 'Confirm reservation',
    },
    {
      method: 'POST',
      path: '/reservations/:id/seat',
      auth: true,
      handler: 'custom',
      entity: 'reservations',
      description: 'Seat guests',
    },

    // Table routes
    {
      method: 'GET',
      path: '/tables',
      auth: false,
      handler: 'crud',
      entity: 'tables',
      description: 'List tables',
    },
    {
      method: 'POST',
      path: '/tables',
      auth: true,
      handler: 'crud',
      entity: 'tables',
      description: 'Create table',
    },
    {
      method: 'PUT',
      path: '/tables/:id',
      auth: true,
      handler: 'crud',
      entity: 'tables',
      description: 'Update table',
    },
    {
      method: 'DELETE',
      path: '/tables/:id',
      auth: true,
      handler: 'crud',
      entity: 'tables',
      description: 'Delete table',
    },
    {
      method: 'GET',
      path: '/tables/availability',
      auth: false,
      handler: 'custom',
      entity: 'tables',
      description: 'Get table availability for date/time',
    },

    // Floor plan routes
    {
      method: 'GET',
      path: '/floor-plans',
      auth: true,
      handler: 'crud',
      entity: 'floor_plans',
      description: 'List floor plans',
    },
    {
      method: 'POST',
      path: '/floor-plans',
      auth: true,
      handler: 'crud',
      entity: 'floor_plans',
      description: 'Create floor plan',
    },
    {
      method: 'PUT',
      path: '/floor-plans/:id',
      auth: true,
      handler: 'crud',
      entity: 'floor_plans',
      description: 'Update floor plan',
    },

    // Waitlist routes
    {
      method: 'GET',
      path: '/waitlist',
      auth: true,
      handler: 'crud',
      entity: 'waitlist_entries',
      description: 'Get current waitlist',
    },
    {
      method: 'POST',
      path: '/waitlist',
      auth: false,
      handler: 'crud',
      entity: 'waitlist_entries',
      description: 'Add to waitlist',
    },
    {
      method: 'PUT',
      path: '/waitlist/:id',
      auth: true,
      handler: 'crud',
      entity: 'waitlist_entries',
      description: 'Update waitlist entry',
    },
    {
      method: 'DELETE',
      path: '/waitlist/:id',
      auth: true,
      handler: 'crud',
      entity: 'waitlist_entries',
      description: 'Remove from waitlist',
    },
    {
      method: 'POST',
      path: '/waitlist/:id/notify',
      auth: true,
      handler: 'custom',
      entity: 'waitlist_entries',
      description: 'Notify guest table is ready',
    },
  ],

  config: [
    {
      key: 'defaultPartySize',
      label: 'Default Party Size',
      type: 'number',
      default: 2,
      description: 'Default party size for reservations',
    },
    {
      key: 'maxPartySize',
      label: 'Maximum Party Size',
      type: 'number',
      default: 12,
      description: 'Maximum party size allowed for online booking',
    },
    {
      key: 'reservationDuration',
      label: 'Default Reservation Duration (minutes)',
      type: 'number',
      default: 90,
      description: 'How long to hold a table for a reservation',
    },
    {
      key: 'advanceBookingDays',
      label: 'Advance Booking Limit (days)',
      type: 'number',
      default: 30,
      description: 'How far in advance can reservations be made',
    },
    {
      key: 'cancellationNotice',
      label: 'Cancellation Notice (hours)',
      type: 'number',
      default: 2,
      description: 'Minimum hours before reservation for free cancellation',
    },
    {
      key: 'requireConfirmation',
      label: 'Require Confirmation',
      type: 'boolean',
      default: false,
      description: 'Require staff confirmation for reservations',
    },
    {
      key: 'enableWaitlist',
      label: 'Enable Waitlist',
      type: 'boolean',
      default: true,
      description: 'Allow guests to join waitlist when fully booked',
    },
    {
      key: 'smsNotifications',
      label: 'SMS Notifications',
      type: 'boolean',
      default: true,
      description: 'Send SMS notifications for reservations',
    },
  ],
};
