/**
 * Parts Catalog Feature Definition
 *
 * Complete auto parts inventory and ordering for automotive applications.
 * Supports parts lookup, compatibility checking, and order management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PARTS_CATALOG_FEATURE: FeatureDefinition = {
  id: 'parts-catalog',
  name: 'Parts Catalog',
  category: 'business',
  description: 'Manage auto parts inventory with vehicle compatibility, pricing, and order fulfillment',
  icon: 'cog',

  includedInAppTypes: [
    'auto-parts-store',
    'automotive-dealership',
    'auto-repair-shop',
    'parts-warehouse',
    'parts-distributor',
    'online-parts-store',
    'auto-salvage',
  ],

  activationKeywords: [
    'parts catalog',
    'auto parts',
    'car parts',
    'vehicle parts',
    'parts inventory',
    'spare parts',
    'oem parts',
    'aftermarket parts',
    'replacement parts',
    'parts lookup',
    'parts search',
    'parts ordering',
    'parts store',
    'parts warehouse',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'inventory', 'shopping-cart'],
  conflicts: [],

  pages: [
    {
      id: 'parts-search',
      route: '/parts',
      section: 'frontend',
      title: 'Parts Search',
      authRequired: false,
      templateId: 'parts-search',
      components: [
        'vehicle-selector',
        'category-browser',
        'parts-search-bar',
        'parts-grid',
        'parts-filters',
        'compatibility-badge',
        'price-filter',
        'brand-filter',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'part-detail',
      route: '/parts/:id',
      section: 'frontend',
      title: 'Part Details',
      authRequired: false,
      templateId: 'part-detail',
      components: [
        'part-images',
        'part-info',
        'compatibility-list',
        'specifications',
        'pricing-info',
        'availability-status',
        'quantity-selector',
        'add-to-cart',
        'related-parts',
        'interchange-numbers',
        'reviews-section',
      ],
      layout: 'default',
    },
    {
      id: 'parts-by-vehicle',
      route: '/parts/vehicle/:vehicleId',
      section: 'frontend',
      title: 'Parts for Your Vehicle',
      authRequired: false,
      templateId: 'parts-by-vehicle',
      components: [
        'vehicle-summary',
        'category-grid',
        'common-repairs',
        'maintenance-parts',
        'featured-parts',
      ],
      layout: 'default',
    },
    {
      id: 'parts-cart',
      route: '/parts/cart',
      section: 'frontend',
      title: 'Parts Cart',
      authRequired: false,
      templateId: 'parts-cart',
      components: [
        'cart-items',
        'compatibility-warnings',
        'quantity-editor',
        'price-summary',
        'shipping-estimator',
        'promo-code-input',
        'checkout-button',
      ],
      layout: 'default',
    },
    {
      id: 'parts-orders',
      route: '/my-parts-orders',
      section: 'frontend',
      title: 'My Parts Orders',
      authRequired: true,
      templateId: 'parts-orders',
      components: [
        'orders-list',
        'order-tracking',
        'reorder-button',
        'return-request',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-parts-inventory',
      route: '/admin/parts',
      section: 'admin',
      title: 'Parts Inventory',
      authRequired: true,
      roles: ['admin', 'inventory'],
      templateId: 'admin-parts-inventory',
      components: [
        'parts-table',
        'inventory-levels',
        'low-stock-alerts',
        'bulk-import',
        'category-manager',
        'pricing-manager',
        'supplier-info',
      ],
      layout: 'admin',
    },
    {
      id: 'add-part',
      route: '/admin/parts/new',
      section: 'admin',
      title: 'Add Part',
      authRequired: true,
      roles: ['admin', 'inventory'],
      templateId: 'add-part',
      components: [
        'part-form',
        'part-number-input',
        'compatibility-editor',
        'image-uploader',
        'specs-form',
        'pricing-form',
        'inventory-form',
        'interchange-editor',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-parts-orders',
      route: '/admin/parts/orders',
      section: 'admin',
      title: 'Parts Orders',
      authRequired: true,
      roles: ['admin', 'fulfillment'],
      templateId: 'admin-parts-orders',
      components: [
        'orders-table',
        'order-status-filter',
        'fulfillment-queue',
        'shipping-manager',
        'returns-manager',
        'order-analytics',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Search components
    'vehicle-selector',
    'category-browser',
    'parts-search-bar',
    'parts-grid',
    'parts-filters',
    'compatibility-badge',
    'price-filter',
    'brand-filter',
    'sort-dropdown',
    'pagination',

    // Detail components
    'part-images',
    'part-info',
    'compatibility-list',
    'specifications',
    'pricing-info',
    'availability-status',
    'quantity-selector',
    'add-to-cart',
    'related-parts',
    'interchange-numbers',
    'reviews-section',

    // Vehicle-specific components
    'vehicle-summary',
    'category-grid',
    'common-repairs',
    'maintenance-parts',
    'featured-parts',

    // Cart components
    'cart-items',
    'compatibility-warnings',
    'quantity-editor',
    'price-summary',
    'shipping-estimator',
    'promo-code-input',
    'checkout-button',

    // Orders components
    'orders-list',
    'order-tracking',
    'reorder-button',
    'return-request',

    // Admin components
    'parts-table',
    'inventory-levels',
    'low-stock-alerts',
    'bulk-import',
    'category-manager',
    'pricing-manager',
    'supplier-info',

    // Part form components
    'part-form',
    'part-number-input',
    'compatibility-editor',
    'image-uploader',
    'specs-form',
    'pricing-form',
    'inventory-form',
    'interchange-editor',

    // Order management components
    'orders-table',
    'order-status-filter',
    'fulfillment-queue',
    'shipping-manager',
    'returns-manager',
    'order-analytics',
  ],

  entities: [
    {
      name: 'parts',
      displayName: 'Parts',
      description: 'Auto parts inventory',
      isCore: true,
    },
    {
      name: 'parts_categories',
      displayName: 'Parts Categories',
      description: 'Parts category hierarchy',
      isCore: true,
    },
    {
      name: 'parts_compatibility',
      displayName: 'Parts Compatibility',
      description: 'Vehicle compatibility mappings',
      isCore: true,
    },
    {
      name: 'parts_inventory',
      displayName: 'Parts Inventory',
      description: 'Inventory levels and locations',
      isCore: true,
    },
    {
      name: 'parts_orders',
      displayName: 'Parts Orders',
      description: 'Customer parts orders',
      isCore: true,
    },
    {
      name: 'parts_order_items',
      displayName: 'Order Items',
      description: 'Individual items in orders',
      isCore: true,
    },
    {
      name: 'interchange_numbers',
      displayName: 'Interchange Numbers',
      description: 'Cross-reference part numbers',
      isCore: false,
    },
    {
      name: 'parts_suppliers',
      displayName: 'Suppliers',
      description: 'Parts supplier records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Parts search and catalog
    {
      method: 'GET',
      path: '/parts',
      auth: false,
      handler: 'crud',
      entity: 'parts',
      operation: 'list',
      description: 'List parts with filters',
    },
    {
      method: 'GET',
      path: '/parts/:id',
      auth: false,
      handler: 'crud',
      entity: 'parts',
      operation: 'get',
      description: 'Get part details',
    },
    {
      method: 'GET',
      path: '/parts/search',
      auth: false,
      handler: 'custom',
      entity: 'parts',
      description: 'Search parts by keyword',
    },
    {
      method: 'GET',
      path: '/parts/by-part-number/:partNumber',
      auth: false,
      handler: 'custom',
      entity: 'parts',
      description: 'Lookup by part number',
    },
    {
      method: 'GET',
      path: '/parts/vehicle/:vehicleId',
      auth: false,
      handler: 'custom',
      entity: 'parts',
      description: 'Get compatible parts for vehicle',
    },

    // Categories
    {
      method: 'GET',
      path: '/parts/categories',
      auth: false,
      handler: 'crud',
      entity: 'parts_categories',
      operation: 'list',
      description: 'Get parts categories',
    },
    {
      method: 'GET',
      path: '/parts/categories/:id',
      auth: false,
      handler: 'crud',
      entity: 'parts_categories',
      operation: 'get',
      description: 'Get category with parts',
    },

    // Compatibility
    {
      method: 'GET',
      path: '/parts/:id/compatibility',
      auth: false,
      handler: 'crud',
      entity: 'parts_compatibility',
      operation: 'list',
      description: 'Get part compatibility list',
    },
    {
      method: 'GET',
      path: '/parts/check-compatibility',
      auth: false,
      handler: 'custom',
      entity: 'parts_compatibility',
      description: 'Check if part fits vehicle',
    },

    // Interchange
    {
      method: 'GET',
      path: '/parts/:id/interchange',
      auth: false,
      handler: 'crud',
      entity: 'interchange_numbers',
      operation: 'list',
      description: 'Get interchange part numbers',
    },
    {
      method: 'GET',
      path: '/parts/interchange/:partNumber',
      auth: false,
      handler: 'custom',
      entity: 'interchange_numbers',
      description: 'Find parts by interchange number',
    },

    // Inventory
    {
      method: 'GET',
      path: '/parts/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'parts_inventory',
      description: 'Check part availability',
    },
    {
      method: 'PUT',
      path: '/parts/:id/inventory',
      auth: true,
      role: 'inventory',
      handler: 'custom',
      entity: 'parts_inventory',
      description: 'Update inventory levels',
    },

    // Parts CRUD (admin)
    {
      method: 'POST',
      path: '/parts',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parts',
      operation: 'create',
      description: 'Add new part',
    },
    {
      method: 'PUT',
      path: '/parts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parts',
      operation: 'update',
      description: 'Update part',
    },
    {
      method: 'DELETE',
      path: '/parts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parts',
      operation: 'delete',
      description: 'Delete part',
    },
    {
      method: 'POST',
      path: '/parts/bulk-import',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'parts',
      description: 'Bulk import parts',
    },

    // Orders
    {
      method: 'GET',
      path: '/parts/orders',
      auth: true,
      handler: 'crud',
      entity: 'parts_orders',
      operation: 'list',
      description: 'Get user parts orders',
    },
    {
      method: 'GET',
      path: '/parts/orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'parts_orders',
      operation: 'get',
      description: 'Get order details',
    },
    {
      method: 'POST',
      path: '/parts/orders',
      auth: true,
      handler: 'crud',
      entity: 'parts_orders',
      operation: 'create',
      description: 'Create parts order',
    },
    {
      method: 'PUT',
      path: '/parts/orders/:id/cancel',
      auth: true,
      handler: 'custom',
      entity: 'parts_orders',
      description: 'Cancel order',
    },
    {
      method: 'POST',
      path: '/parts/orders/:id/return',
      auth: true,
      handler: 'custom',
      entity: 'parts_orders',
      description: 'Request return',
    },

    // Admin orders
    {
      method: 'GET',
      path: '/admin/parts/orders',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'parts_orders',
      operation: 'list',
      description: 'List all orders (admin)',
    },
    {
      method: 'PUT',
      path: '/admin/parts/orders/:id/status',
      auth: true,
      role: 'fulfillment',
      handler: 'custom',
      entity: 'parts_orders',
      description: 'Update order status',
    },
    {
      method: 'POST',
      path: '/admin/parts/orders/:id/ship',
      auth: true,
      role: 'fulfillment',
      handler: 'custom',
      entity: 'parts_orders',
      description: 'Mark order shipped',
    },

    // Analytics
    {
      method: 'GET',
      path: '/admin/parts/stats',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'parts',
      description: 'Get parts statistics',
    },
    {
      method: 'GET',
      path: '/admin/parts/low-stock',
      auth: true,
      role: 'inventory',
      handler: 'custom',
      entity: 'parts_inventory',
      description: 'Get low stock alerts',
    },
  ],

  config: [
    {
      key: 'enableCompatibilityCheck',
      label: 'Enable Compatibility Check',
      type: 'boolean',
      default: true,
      description: 'Check part compatibility with vehicles',
    },
    {
      key: 'showInterchangeNumbers',
      label: 'Show Interchange Numbers',
      type: 'boolean',
      default: true,
      description: 'Display cross-reference part numbers',
    },
    {
      key: 'lowStockThreshold',
      label: 'Low Stock Threshold',
      type: 'number',
      default: 5,
      description: 'Quantity threshold for low stock alerts',
    },
    {
      key: 'allowBackorders',
      label: 'Allow Backorders',
      type: 'boolean',
      default: true,
      description: 'Allow ordering out-of-stock items',
    },
    {
      key: 'displayCoreCharge',
      label: 'Display Core Charges',
      type: 'boolean',
      default: true,
      description: 'Show core charge for remanufactured parts',
    },
    {
      key: 'showWholesalePricing',
      label: 'Show Wholesale Pricing',
      type: 'boolean',
      default: false,
      description: 'Display wholesale prices for dealers',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for pricing',
    },
    {
      key: 'taxRate',
      label: 'Default Tax Rate (%)',
      type: 'number',
      default: 8.25,
      description: 'Default sales tax rate',
    },
    {
      key: 'freeShippingThreshold',
      label: 'Free Shipping Threshold',
      type: 'number',
      default: 99,
      description: 'Order total for free shipping',
    },
  ],
};
