/**
 * Recalls Tracking Feature Definition
 *
 * Complete recall notification and management for automotive applications.
 * Supports NHTSA integration, recall alerts, and service tracking.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const RECALLS_TRACKING_FEATURE: FeatureDefinition = {
  id: 'recalls-tracking',
  name: 'Recalls Tracking',
  category: 'business',
  description: 'Track and manage vehicle recalls with notifications and service completion tracking',
  icon: 'alert-triangle',

  includedInAppTypes: [
    'automotive-dealership',
    'car-dealership',
    'auto-service-center',
    'auto-repair-shop',
    'vehicle-marketplace',
    'auto-dealer',
    'fleet-management',
    'vehicle-history-service',
  ],

  activationKeywords: [
    'recall',
    'recalls',
    'vehicle recall',
    'car recall',
    'recall check',
    'safety recall',
    'nhtsa recall',
    'manufacturer recall',
    'recall notification',
    'recall alert',
    'recall service',
    'recall tracking',
    'open recalls',
    'recall status',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'notifications'],
  conflicts: [],

  pages: [
    {
      id: 'recall-check',
      route: '/recalls/check',
      section: 'frontend',
      title: 'Check for Recalls',
      authRequired: false,
      templateId: 'recall-check',
      components: [
        'vin-input',
        'license-plate-lookup',
        'make-model-year-selector',
        'recall-check-button',
        'recall-results',
      ],
      layout: 'centered',
    },
    {
      id: 'recall-results',
      route: '/recalls/results/:vin',
      section: 'frontend',
      title: 'Recall Results',
      authRequired: false,
      templateId: 'recall-results',
      components: [
        'vehicle-info-banner',
        'open-recalls-list',
        'completed-recalls',
        'recall-severity-badge',
        'schedule-service-button',
        'sign-up-alerts',
        'share-results',
      ],
      layout: 'default',
    },
    {
      id: 'recall-detail',
      route: '/recalls/:recallId',
      section: 'frontend',
      title: 'Recall Details',
      authRequired: false,
      templateId: 'recall-detail',
      components: [
        'recall-summary',
        'affected-vehicles',
        'remedy-description',
        'safety-risk',
        'manufacturer-contact',
        'find-dealer',
        'schedule-repair',
        'document-download',
      ],
      layout: 'default',
    },
    {
      id: 'my-recalls',
      route: '/my-recalls',
      section: 'frontend',
      title: 'My Vehicles & Recalls',
      authRequired: true,
      templateId: 'my-recalls',
      components: [
        'my-vehicles-list',
        'add-vehicle-button',
        'active-recalls-summary',
        'recall-notifications',
        'service-appointments',
        'notification-preferences',
      ],
      layout: 'dashboard',
    },
    {
      id: 'register-vehicle',
      route: '/my-recalls/register',
      section: 'frontend',
      title: 'Register Vehicle',
      authRequired: true,
      templateId: 'register-vehicle',
      components: [
        'vin-input-form',
        'vehicle-verification',
        'ownership-confirmation',
        'alert-preferences',
        'registration-complete',
      ],
      layout: 'centered',
    },
    {
      id: 'admin-recalls',
      route: '/admin/recalls',
      section: 'admin',
      title: 'Recalls Management',
      authRequired: true,
      roles: ['admin', 'service-manager'],
      templateId: 'admin-recalls',
      components: [
        'recalls-dashboard',
        'affected-inventory',
        'pending-services',
        'completion-stats',
        'customer-outreach',
        'recall-import',
      ],
      layout: 'admin',
    },
    {
      id: 'recall-campaign',
      route: '/admin/recalls/:id',
      section: 'admin',
      title: 'Recall Campaign',
      authRequired: true,
      roles: ['admin', 'service-manager'],
      templateId: 'recall-campaign',
      components: [
        'campaign-header',
        'affected-vehicles-list',
        'notification-queue',
        'service-tracking',
        'parts-availability',
        'completion-rate',
        'customer-communications',
      ],
      layout: 'admin',
    },
    {
      id: 'recall-settings',
      route: '/admin/recalls/settings',
      section: 'admin',
      title: 'Recall Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'recall-settings',
      components: [
        'nhtsa-integration',
        'manufacturer-feeds',
        'notification-templates',
        'auto-check-settings',
        'compliance-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Check components
    'vin-input',
    'license-plate-lookup',
    'make-model-year-selector',
    'recall-check-button',
    'recall-results',

    // Results components
    'vehicle-info-banner',
    'open-recalls-list',
    'completed-recalls',
    'recall-severity-badge',
    'schedule-service-button',
    'sign-up-alerts',
    'share-results',

    // Detail components
    'recall-summary',
    'affected-vehicles',
    'remedy-description',
    'safety-risk',
    'manufacturer-contact',
    'find-dealer',
    'schedule-repair',
    'document-download',

    // User components
    'my-vehicles-list',
    'add-vehicle-button',
    'active-recalls-summary',
    'recall-notifications',
    'service-appointments',
    'notification-preferences',

    // Registration components
    'vin-input-form',
    'vehicle-verification',
    'ownership-confirmation',
    'alert-preferences',
    'registration-complete',

    // Admin components
    'recalls-dashboard',
    'affected-inventory',
    'pending-services',
    'completion-stats',
    'customer-outreach',
    'recall-import',

    // Campaign components
    'campaign-header',
    'affected-vehicles-list',
    'notification-queue',
    'service-tracking',
    'parts-availability',
    'completion-rate',
    'customer-communications',

    // Settings components
    'nhtsa-integration',
    'manufacturer-feeds',
    'notification-templates',
    'auto-check-settings',
    'compliance-settings',
  ],

  entities: [
    {
      name: 'recalls',
      displayName: 'Recalls',
      description: 'Recall campaign records',
      isCore: true,
    },
    {
      name: 'vehicle_recalls',
      displayName: 'Vehicle Recalls',
      description: 'Recalls affecting specific vehicles',
      isCore: true,
    },
    {
      name: 'recall_completions',
      displayName: 'Recall Completions',
      description: 'Completed recall service records',
      isCore: true,
    },
    {
      name: 'registered_vehicles',
      displayName: 'Registered Vehicles',
      description: 'User registered vehicles for alerts',
      isCore: true,
    },
    {
      name: 'recall_notifications',
      displayName: 'Recall Notifications',
      description: 'Recall notification records',
      isCore: false,
    },
    {
      name: 'recall_parts',
      displayName: 'Recall Parts',
      description: 'Parts required for recall repairs',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Recall lookup
    {
      method: 'GET',
      path: '/recalls/check/:vin',
      auth: false,
      handler: 'custom',
      entity: 'recalls',
      description: 'Check recalls for VIN',
    },
    {
      method: 'GET',
      path: '/recalls/check/vehicle',
      auth: false,
      handler: 'custom',
      entity: 'recalls',
      description: 'Check recalls by make/model/year',
    },
    {
      method: 'GET',
      path: '/recalls/:id',
      auth: false,
      handler: 'crud',
      entity: 'recalls',
      operation: 'get',
      description: 'Get recall details',
    },
    {
      method: 'GET',
      path: '/recalls/search',
      auth: false,
      handler: 'custom',
      entity: 'recalls',
      description: 'Search recalls',
    },

    // All recalls list
    {
      method: 'GET',
      path: '/recalls',
      auth: false,
      handler: 'crud',
      entity: 'recalls',
      operation: 'list',
      description: 'List recent recalls',
    },
    {
      method: 'GET',
      path: '/recalls/make/:make',
      auth: false,
      handler: 'custom',
      entity: 'recalls',
      description: 'Get recalls by manufacturer',
    },

    // User vehicles
    {
      method: 'GET',
      path: '/my-vehicles',
      auth: true,
      handler: 'crud',
      entity: 'registered_vehicles',
      operation: 'list',
      description: 'Get user registered vehicles',
    },
    {
      method: 'POST',
      path: '/my-vehicles',
      auth: true,
      handler: 'crud',
      entity: 'registered_vehicles',
      operation: 'create',
      description: 'Register vehicle for alerts',
    },
    {
      method: 'DELETE',
      path: '/my-vehicles/:id',
      auth: true,
      handler: 'crud',
      entity: 'registered_vehicles',
      operation: 'delete',
      description: 'Remove registered vehicle',
    },
    {
      method: 'GET',
      path: '/my-vehicles/:id/recalls',
      auth: true,
      handler: 'custom',
      entity: 'vehicle_recalls',
      description: 'Get recalls for registered vehicle',
    },

    // Recall notifications
    {
      method: 'GET',
      path: '/my-recalls/notifications',
      auth: true,
      handler: 'crud',
      entity: 'recall_notifications',
      operation: 'list',
      description: 'Get user recall notifications',
    },
    {
      method: 'PUT',
      path: '/my-recalls/notifications/:id/read',
      auth: true,
      handler: 'custom',
      entity: 'recall_notifications',
      description: 'Mark notification as read',
    },
    {
      method: 'PUT',
      path: '/my-recalls/preferences',
      auth: true,
      handler: 'custom',
      entity: 'registered_vehicles',
      description: 'Update notification preferences',
    },

    // Recall completions
    {
      method: 'POST',
      path: '/recalls/completions',
      auth: true,
      role: 'service',
      handler: 'crud',
      entity: 'recall_completions',
      operation: 'create',
      description: 'Record recall completion',
    },
    {
      method: 'GET',
      path: '/vehicles/:vin/recall-history',
      auth: false,
      handler: 'custom',
      entity: 'recall_completions',
      description: 'Get recall completion history',
    },

    // Admin
    {
      method: 'GET',
      path: '/admin/recalls',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recalls',
      operation: 'list',
      description: 'List all recalls (admin)',
    },
    {
      method: 'POST',
      path: '/admin/recalls',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recalls',
      operation: 'create',
      description: 'Add recall manually',
    },
    {
      method: 'PUT',
      path: '/admin/recalls/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recalls',
      operation: 'update',
      description: 'Update recall',
    },
    {
      method: 'POST',
      path: '/admin/recalls/import',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'recalls',
      description: 'Import recalls from NHTSA',
    },
    {
      method: 'POST',
      path: '/admin/recalls/sync',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'recalls',
      description: 'Sync with manufacturer feed',
    },

    // Affected inventory
    {
      method: 'GET',
      path: '/admin/recalls/:id/affected-vehicles',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vehicle_recalls',
      operation: 'list',
      description: 'Get affected vehicles in inventory',
    },
    {
      method: 'POST',
      path: '/admin/recalls/:id/notify',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'recall_notifications',
      description: 'Send recall notifications',
    },

    // Parts
    {
      method: 'GET',
      path: '/admin/recalls/:id/parts',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recall_parts',
      operation: 'list',
      description: 'Get recall parts availability',
    },
    {
      method: 'PUT',
      path: '/admin/recalls/:recallId/parts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'recall_parts',
      operation: 'update',
      description: 'Update parts availability',
    },

    // Stats
    {
      method: 'GET',
      path: '/admin/recalls/stats',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'recalls',
      description: 'Get recall statistics',
    },
    {
      method: 'GET',
      path: '/admin/recalls/:id/completion-rate',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'recall_completions',
      description: 'Get recall completion rate',
    },
  ],

  config: [
    {
      key: 'nhtsaApiEnabled',
      label: 'Enable NHTSA API Integration',
      type: 'boolean',
      default: true,
      description: 'Automatically fetch recalls from NHTSA',
    },
    {
      key: 'nhtsaApiKey',
      label: 'NHTSA API Key',
      type: 'string',
      default: '',
      description: 'API key for NHTSA integration',
    },
    {
      key: 'autoSyncFrequency',
      label: 'Auto-Sync Frequency',
      type: 'select',
      default: 'daily',
      options: [
        { value: 'hourly', label: 'Hourly' },
        { value: 'daily', label: 'Daily' },
        { value: 'weekly', label: 'Weekly' },
        { value: 'manual', label: 'Manual Only' },
      ],
      description: 'How often to sync recalls from NHTSA',
    },
    {
      key: 'sendEmailAlerts',
      label: 'Send Email Alerts',
      type: 'boolean',
      default: true,
      description: 'Send email alerts for new recalls',
    },
    {
      key: 'sendSmsAlerts',
      label: 'Send SMS Alerts',
      type: 'boolean',
      default: false,
      description: 'Send SMS alerts for safety recalls',
    },
    {
      key: 'autoCheckInventory',
      label: 'Auto-Check Inventory',
      type: 'boolean',
      default: true,
      description: 'Automatically check inventory for recalls',
    },
    {
      key: 'showRecallBadges',
      label: 'Show Recall Badges on Listings',
      type: 'boolean',
      default: true,
      description: 'Display recall status badges on vehicle listings',
    },
    {
      key: 'requireRecallDisclosure',
      label: 'Require Recall Disclosure',
      type: 'boolean',
      default: true,
      description: 'Require open recalls to be disclosed before sale',
    },
    {
      key: 'partsTrackingEnabled',
      label: 'Enable Parts Tracking',
      type: 'boolean',
      default: false,
      description: 'Track recall parts availability',
    },
  ],
};
