/**
 * Service Scheduling Feature Definition
 *
 * Complete auto service appointment scheduling for automotive applications.
 * Supports service booking, maintenance reminders, and work order management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const SERVICE_SCHEDULING_FEATURE: FeatureDefinition = {
  id: 'service-scheduling',
  name: 'Service Scheduling',
  category: 'business',
  description: 'Schedule and manage auto service appointments with maintenance tracking and reminders',
  icon: 'wrench',

  includedInAppTypes: [
    'automotive-dealership',
    'car-dealership',
    'auto-service-center',
    'auto-repair-shop',
    'tire-shop',
    'oil-change-service',
    'body-shop',
    'auto-dealer',
  ],

  activationKeywords: [
    'service appointment',
    'service scheduling',
    'auto service',
    'car service',
    'maintenance appointment',
    'oil change',
    'tire service',
    'brake service',
    'repair appointment',
    'service booking',
    'schedule service',
    'vehicle maintenance',
    'car repair',
    'auto repair',
    'service center',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'calendar', 'notifications'],
  conflicts: [],

  pages: [
    {
      id: 'schedule-service',
      route: '/service/schedule',
      section: 'frontend',
      title: 'Schedule Service',
      authRequired: false,
      templateId: 'schedule-service',
      components: [
        'vehicle-selector',
        'service-type-selector',
        'service-packages',
        'date-picker',
        'time-slot-selector',
        'advisor-selection',
        'customer-info-form',
        'special-requests',
        'booking-summary',
      ],
      layout: 'default',
    },
    {
      id: 'service-confirmation',
      route: '/service/confirmation/:id',
      section: 'frontend',
      title: 'Appointment Confirmed',
      authRequired: false,
      templateId: 'service-confirmation',
      components: [
        'confirmation-message',
        'appointment-details',
        'service-summary',
        'add-to-calendar',
        'directions-map',
        'what-to-expect',
        'contact-info',
      ],
      layout: 'centered',
    },
    {
      id: 'my-service-appointments',
      route: '/my-service',
      section: 'frontend',
      title: 'My Service Appointments',
      authRequired: true,
      templateId: 'my-service-appointments',
      components: [
        'upcoming-appointments',
        'service-history',
        'vehicle-service-timeline',
        'maintenance-reminders',
        'reschedule-button',
        'cancel-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'service-status',
      route: '/service/status/:id',
      section: 'frontend',
      title: 'Service Status',
      authRequired: true,
      templateId: 'service-status',
      components: [
        'status-tracker',
        'service-progress',
        'technician-notes',
        'additional-recommendations',
        'cost-estimate',
        'approval-buttons',
        'pickup-time',
      ],
      layout: 'default',
    },
    {
      id: 'admin-service-appointments',
      route: '/admin/service',
      section: 'admin',
      title: 'Service Dashboard',
      authRequired: true,
      roles: ['admin', 'service-advisor'],
      templateId: 'admin-service-appointments',
      components: [
        'daily-schedule',
        'appointments-calendar',
        'bay-assignments',
        'technician-workload',
        'work-orders-queue',
        'service-analytics',
      ],
      layout: 'admin',
    },
    {
      id: 'work-order',
      route: '/admin/service/work-order/:id',
      section: 'admin',
      title: 'Work Order',
      authRequired: true,
      roles: ['admin', 'service-advisor', 'technician'],
      templateId: 'work-order',
      components: [
        'work-order-header',
        'customer-vehicle-info',
        'service-items',
        'parts-used',
        'labor-tracking',
        'technician-assignment',
        'inspection-checklist',
        'cost-breakdown',
        'approval-workflow',
      ],
      layout: 'admin',
    },
    {
      id: 'service-settings',
      route: '/admin/service/settings',
      section: 'admin',
      title: 'Service Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'service-settings',
      components: [
        'service-hours',
        'bay-configuration',
        'service-types-manager',
        'pricing-manager',
        'technician-scheduler',
        'reminder-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Booking components
    'vehicle-selector',
    'service-type-selector',
    'service-packages',
    'date-picker',
    'time-slot-selector',
    'advisor-selection',
    'customer-info-form',
    'special-requests',
    'booking-summary',

    // Confirmation components
    'confirmation-message',
    'appointment-details',
    'service-summary',
    'add-to-calendar',
    'directions-map',
    'what-to-expect',
    'contact-info',

    // Customer components
    'upcoming-appointments',
    'service-history',
    'vehicle-service-timeline',
    'maintenance-reminders',
    'reschedule-button',
    'cancel-button',

    // Status components
    'status-tracker',
    'service-progress',
    'technician-notes',
    'additional-recommendations',
    'cost-estimate',
    'approval-buttons',
    'pickup-time',

    // Admin components
    'daily-schedule',
    'appointments-calendar',
    'bay-assignments',
    'technician-workload',
    'work-orders-queue',
    'service-analytics',

    // Work order components
    'work-order-header',
    'customer-vehicle-info',
    'service-items',
    'parts-used',
    'labor-tracking',
    'technician-assignment',
    'inspection-checklist',
    'cost-breakdown',
    'approval-workflow',

    // Settings components
    'service-hours',
    'bay-configuration',
    'service-types-manager',
    'pricing-manager',
    'technician-scheduler',
    'reminder-settings',
  ],

  entities: [
    {
      name: 'service_appointments',
      displayName: 'Service Appointments',
      description: 'Service appointment records',
      isCore: true,
    },
    {
      name: 'work_orders',
      displayName: 'Work Orders',
      description: 'Service work order records',
      isCore: true,
    },
    {
      name: 'service_types',
      displayName: 'Service Types',
      description: 'Available service types and packages',
      isCore: true,
    },
    {
      name: 'service_bays',
      displayName: 'Service Bays',
      description: 'Physical service bay configuration',
      isCore: false,
    },
    {
      name: 'technicians',
      displayName: 'Technicians',
      description: 'Service technician records',
      isCore: false,
    },
    {
      name: 'maintenance_schedules',
      displayName: 'Maintenance Schedules',
      description: 'Vehicle maintenance schedule templates',
      isCore: false,
    },
    {
      name: 'service_reminders',
      displayName: 'Service Reminders',
      description: 'Customer service reminder records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Appointment booking
    {
      method: 'GET',
      path: '/service/appointments',
      auth: true,
      handler: 'crud',
      entity: 'service_appointments',
      operation: 'list',
      description: 'List user service appointments',
    },
    {
      method: 'GET',
      path: '/service/appointments/:id',
      auth: true,
      handler: 'crud',
      entity: 'service_appointments',
      operation: 'get',
      description: 'Get appointment details',
    },
    {
      method: 'POST',
      path: '/service/appointments',
      auth: false,
      handler: 'crud',
      entity: 'service_appointments',
      operation: 'create',
      description: 'Create service appointment',
    },
    {
      method: 'PUT',
      path: '/service/appointments/:id',
      auth: true,
      handler: 'crud',
      entity: 'service_appointments',
      operation: 'update',
      description: 'Update service appointment',
    },
    {
      method: 'DELETE',
      path: '/service/appointments/:id',
      auth: true,
      handler: 'crud',
      entity: 'service_appointments',
      operation: 'delete',
      description: 'Cancel service appointment',
    },

    // Availability
    {
      method: 'GET',
      path: '/service/availability/:date',
      auth: false,
      handler: 'custom',
      entity: 'service_appointments',
      description: 'Get available time slots for date',
    },
    {
      method: 'GET',
      path: '/service/availability/advisors/:date',
      auth: false,
      handler: 'custom',
      entity: 'service_appointments',
      description: 'Get available advisors for date',
    },

    // Appointment actions
    {
      method: 'PUT',
      path: '/service/appointments/:id/reschedule',
      auth: true,
      handler: 'custom',
      entity: 'service_appointments',
      description: 'Reschedule appointment',
    },
    {
      method: 'PUT',
      path: '/service/appointments/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'service_appointments',
      description: 'Update appointment status',
    },
    {
      method: 'PUT',
      path: '/service/appointments/:id/check-in',
      auth: true,
      handler: 'custom',
      entity: 'service_appointments',
      description: 'Check in for appointment',
    },

    // Work orders
    {
      method: 'GET',
      path: '/service/work-orders',
      auth: true,
      role: 'service-advisor',
      handler: 'crud',
      entity: 'work_orders',
      operation: 'list',
      description: 'List work orders',
    },
    {
      method: 'GET',
      path: '/service/work-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'work_orders',
      operation: 'get',
      description: 'Get work order details',
    },
    {
      method: 'POST',
      path: '/service/work-orders',
      auth: true,
      role: 'service-advisor',
      handler: 'crud',
      entity: 'work_orders',
      operation: 'create',
      description: 'Create work order',
    },
    {
      method: 'PUT',
      path: '/service/work-orders/:id',
      auth: true,
      role: 'service-advisor',
      handler: 'crud',
      entity: 'work_orders',
      operation: 'update',
      description: 'Update work order',
    },
    {
      method: 'PUT',
      path: '/service/work-orders/:id/items',
      auth: true,
      role: 'technician',
      handler: 'custom',
      entity: 'work_orders',
      description: 'Update work order service items',
    },
    {
      method: 'POST',
      path: '/service/work-orders/:id/approve',
      auth: true,
      handler: 'custom',
      entity: 'work_orders',
      description: 'Customer approves additional work',
    },

    // Service types
    {
      method: 'GET',
      path: '/service/types',
      auth: false,
      handler: 'crud',
      entity: 'service_types',
      operation: 'list',
      description: 'Get available service types',
    },
    {
      method: 'GET',
      path: '/service/packages',
      auth: false,
      handler: 'custom',
      entity: 'service_types',
      description: 'Get service packages',
    },
    {
      method: 'POST',
      path: '/service/types',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'service_types',
      operation: 'create',
      description: 'Create service type',
    },
    {
      method: 'PUT',
      path: '/service/types/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'service_types',
      operation: 'update',
      description: 'Update service type',
    },

    // Reminders
    {
      method: 'GET',
      path: '/service/reminders',
      auth: true,
      handler: 'crud',
      entity: 'service_reminders',
      operation: 'list',
      description: 'Get user service reminders',
    },
    {
      method: 'POST',
      path: '/service/reminders',
      auth: true,
      handler: 'crud',
      entity: 'service_reminders',
      operation: 'create',
      description: 'Create service reminder',
    },
    {
      method: 'DELETE',
      path: '/service/reminders/:id',
      auth: true,
      handler: 'crud',
      entity: 'service_reminders',
      operation: 'delete',
      description: 'Delete service reminder',
    },

    // Admin
    {
      method: 'GET',
      path: '/admin/service/daily',
      auth: true,
      role: 'service-advisor',
      handler: 'custom',
      entity: 'service_appointments',
      description: 'Get daily service schedule',
    },
    {
      method: 'GET',
      path: '/admin/service/bays',
      auth: true,
      role: 'service-advisor',
      handler: 'crud',
      entity: 'service_bays',
      operation: 'list',
      description: 'Get service bay assignments',
    },
    {
      method: 'PUT',
      path: '/admin/service/bays/:id/assign',
      auth: true,
      role: 'service-advisor',
      handler: 'custom',
      entity: 'service_bays',
      description: 'Assign work order to bay',
    },
    {
      method: 'GET',
      path: '/admin/service/technicians',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'technicians',
      operation: 'list',
      description: 'Get technician list',
    },
    {
      method: 'GET',
      path: '/admin/service/stats',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'service_appointments',
      description: 'Get service center statistics',
    },
  ],

  config: [
    {
      key: 'operatingHoursStart',
      label: 'Operating Hours Start',
      type: 'string',
      default: '07:00',
      description: 'Service center opening time',
    },
    {
      key: 'operatingHoursEnd',
      label: 'Operating Hours End',
      type: 'string',
      default: '18:00',
      description: 'Service center closing time',
    },
    {
      key: 'appointmentDuration',
      label: 'Default Appointment Duration (minutes)',
      type: 'number',
      default: 60,
      description: 'Default duration for service appointments',
    },
    {
      key: 'maxDailyAppointments',
      label: 'Max Daily Appointments',
      type: 'number',
      default: 20,
      description: 'Maximum appointments per day',
    },
    {
      key: 'numberOfBays',
      label: 'Number of Service Bays',
      type: 'number',
      default: 6,
      description: 'Number of available service bays',
    },
    {
      key: 'enableOnlineBooking',
      label: 'Enable Online Booking',
      type: 'boolean',
      default: true,
      description: 'Allow customers to book online',
    },
    {
      key: 'requireAccount',
      label: 'Require Account for Booking',
      type: 'boolean',
      default: false,
      description: 'Require customer account to book',
    },
    {
      key: 'sendReminders',
      label: 'Send Appointment Reminders',
      type: 'boolean',
      default: true,
      description: 'Send reminder notifications',
    },
    {
      key: 'reminderHours',
      label: 'Reminder Hours Before',
      type: 'number',
      default: 24,
      description: 'Hours before appointment to send reminder',
    },
    {
      key: 'allowWalkIns',
      label: 'Allow Walk-Ins',
      type: 'boolean',
      default: true,
      description: 'Accept walk-in customers',
    },
    {
      key: 'requireApprovalForAdditional',
      label: 'Require Approval for Additional Work',
      type: 'boolean',
      default: true,
      description: 'Require customer approval for additional services',
    },
  ],
};
