/**
 * Trade-In Valuation Feature Definition
 *
 * Complete trade-in value estimation for automotive applications.
 * Supports KBB-style valuations, condition assessments, and offer management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TRADE_IN_VALUATION_FEATURE: FeatureDefinition = {
  id: 'trade-in-valuation',
  name: 'Trade-In Valuation',
  category: 'business',
  description: 'Calculate trade-in values with condition assessment and instant offer generation',
  icon: 'dollar-sign',

  includedInAppTypes: [
    'automotive-dealership',
    'car-dealership',
    'used-car-lot',
    'vehicle-marketplace',
    'auto-dealer',
    'vehicle-buying-service',
    'auto-auction',
  ],

  activationKeywords: [
    'trade-in',
    'trade in value',
    'trade-in valuation',
    'car value',
    'vehicle value',
    'kbb value',
    'kelley blue book',
    'what is my car worth',
    'sell my car',
    'instant offer',
    'trade appraisal',
    'vehicle appraisal',
    'car appraisal',
    'trade estimate',
    'vehicle worth',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth'],
  conflicts: [],

  pages: [
    {
      id: 'trade-in-calculator',
      route: '/trade-in',
      section: 'frontend',
      title: 'Trade-In Calculator',
      authRequired: false,
      templateId: 'trade-in-calculator',
      components: [
        'vehicle-selector',
        'year-make-model-form',
        'mileage-input',
        'condition-assessment',
        'feature-checklist',
        'value-estimate',
        'get-offer-button',
      ],
      layout: 'centered',
    },
    {
      id: 'condition-assessment',
      route: '/trade-in/condition',
      section: 'frontend',
      title: 'Vehicle Condition',
      authRequired: false,
      templateId: 'condition-assessment',
      components: [
        'exterior-condition',
        'interior-condition',
        'mechanical-condition',
        'damage-report-form',
        'photo-upload-grid',
        'condition-summary',
      ],
      layout: 'default',
    },
    {
      id: 'trade-in-offer',
      route: '/trade-in/offer/:id',
      section: 'frontend',
      title: 'Your Trade-In Offer',
      authRequired: false,
      templateId: 'trade-in-offer',
      components: [
        'offer-summary',
        'value-breakdown',
        'offer-validity',
        'accept-offer-button',
        'counter-offer-form',
        'schedule-inspection',
        'compare-with-retail',
      ],
      layout: 'centered',
    },
    {
      id: 'my-trade-ins',
      route: '/my-trade-ins',
      section: 'frontend',
      title: 'My Trade-Ins',
      authRequired: true,
      templateId: 'my-trade-ins',
      components: [
        'trade-in-history',
        'pending-offers',
        'offer-status',
        'resubmit-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-trade-ins',
      route: '/admin/trade-ins',
      section: 'admin',
      title: 'Manage Trade-Ins',
      authRequired: true,
      roles: ['admin', 'appraiser'],
      templateId: 'admin-trade-ins',
      components: [
        'trade-ins-table',
        'status-filter',
        'valuation-tools',
        'offer-management',
        'inspection-scheduler',
        'margin-calculator',
      ],
      layout: 'admin',
    },
    {
      id: 'trade-in-detail',
      route: '/admin/trade-ins/:id',
      section: 'admin',
      title: 'Trade-In Details',
      authRequired: true,
      roles: ['admin', 'appraiser'],
      templateId: 'trade-in-detail',
      components: [
        'vehicle-details',
        'condition-report',
        'customer-info',
        'valuation-history',
        'offer-editor',
        'inspection-photos',
        'final-offer-form',
      ],
      layout: 'admin',
    },
    {
      id: 'valuation-settings',
      route: '/admin/trade-ins/settings',
      section: 'admin',
      title: 'Valuation Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'valuation-settings',
      components: [
        'valuation-providers',
        'margin-settings',
        'condition-multipliers',
        'mileage-adjustments',
        'regional-adjustments',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calculator components
    'vehicle-selector',
    'year-make-model-form',
    'mileage-input',
    'condition-assessment',
    'feature-checklist',
    'value-estimate',
    'get-offer-button',

    // Condition components
    'exterior-condition',
    'interior-condition',
    'mechanical-condition',
    'damage-report-form',
    'photo-upload-grid',
    'condition-summary',

    // Offer components
    'offer-summary',
    'value-breakdown',
    'offer-validity',
    'accept-offer-button',
    'counter-offer-form',
    'schedule-inspection',
    'compare-with-retail',

    // User components
    'trade-in-history',
    'pending-offers',
    'offer-status',
    'resubmit-button',

    // Admin components
    'trade-ins-table',
    'status-filter',
    'valuation-tools',
    'offer-management',
    'inspection-scheduler',
    'margin-calculator',
    'vehicle-details',
    'condition-report',
    'customer-info',
    'valuation-history',
    'offer-editor',
    'inspection-photos',
    'final-offer-form',

    // Settings components
    'valuation-providers',
    'margin-settings',
    'condition-multipliers',
    'mileage-adjustments',
    'regional-adjustments',
  ],

  entities: [
    {
      name: 'trade_in_requests',
      displayName: 'Trade-In Requests',
      description: 'Customer trade-in valuation requests',
      isCore: true,
    },
    {
      name: 'trade_in_offers',
      displayName: 'Trade-In Offers',
      description: 'Generated trade-in offers',
      isCore: true,
    },
    {
      name: 'condition_assessments',
      displayName: 'Condition Assessments',
      description: 'Vehicle condition assessment records',
      isCore: true,
    },
    {
      name: 'valuation_history',
      displayName: 'Valuation History',
      description: 'Historical valuation records',
      isCore: false,
    },
    {
      name: 'inspection_appointments',
      displayName: 'Inspection Appointments',
      description: 'In-person inspection appointments',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Valuation
    {
      method: 'POST',
      path: '/trade-in/estimate',
      auth: false,
      handler: 'custom',
      entity: 'trade_in_requests',
      description: 'Get instant trade-in estimate',
    },
    {
      method: 'GET',
      path: '/trade-in/estimate/:vin',
      auth: false,
      handler: 'custom',
      entity: 'trade_in_requests',
      description: 'Get estimate by VIN',
    },
    {
      method: 'POST',
      path: '/trade-in/detailed-estimate',
      auth: false,
      handler: 'custom',
      entity: 'trade_in_requests',
      description: 'Get detailed trade-in estimate with condition',
    },

    // Trade-in requests
    {
      method: 'GET',
      path: '/trade-in/requests',
      auth: true,
      handler: 'crud',
      entity: 'trade_in_requests',
      operation: 'list',
      description: 'List user trade-in requests',
    },
    {
      method: 'GET',
      path: '/trade-in/requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'trade_in_requests',
      operation: 'get',
      description: 'Get trade-in request details',
    },
    {
      method: 'POST',
      path: '/trade-in/requests',
      auth: false,
      handler: 'crud',
      entity: 'trade_in_requests',
      operation: 'create',
      description: 'Submit trade-in request',
    },
    {
      method: 'PUT',
      path: '/trade-in/requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'trade_in_requests',
      operation: 'update',
      description: 'Update trade-in request',
    },

    // Offers
    {
      method: 'GET',
      path: '/trade-in/offers/:id',
      auth: false,
      handler: 'crud',
      entity: 'trade_in_offers',
      operation: 'get',
      description: 'Get trade-in offer details',
    },
    {
      method: 'POST',
      path: '/trade-in/offers',
      auth: true,
      role: 'appraiser',
      handler: 'crud',
      entity: 'trade_in_offers',
      operation: 'create',
      description: 'Create trade-in offer',
    },
    {
      method: 'PUT',
      path: '/trade-in/offers/:id',
      auth: true,
      role: 'appraiser',
      handler: 'crud',
      entity: 'trade_in_offers',
      operation: 'update',
      description: 'Update trade-in offer',
    },
    {
      method: 'PUT',
      path: '/trade-in/offers/:id/accept',
      auth: true,
      handler: 'custom',
      entity: 'trade_in_offers',
      description: 'Accept trade-in offer',
    },
    {
      method: 'PUT',
      path: '/trade-in/offers/:id/decline',
      auth: true,
      handler: 'custom',
      entity: 'trade_in_offers',
      description: 'Decline trade-in offer',
    },
    {
      method: 'POST',
      path: '/trade-in/offers/:id/counter',
      auth: true,
      handler: 'custom',
      entity: 'trade_in_offers',
      description: 'Submit counter offer',
    },

    // Condition assessment
    {
      method: 'GET',
      path: '/trade-in/requests/:id/condition',
      auth: true,
      handler: 'crud',
      entity: 'condition_assessments',
      operation: 'get',
      description: 'Get condition assessment',
    },
    {
      method: 'POST',
      path: '/trade-in/requests/:id/condition',
      auth: false,
      handler: 'crud',
      entity: 'condition_assessments',
      operation: 'create',
      description: 'Submit condition assessment',
    },
    {
      method: 'PUT',
      path: '/trade-in/requests/:id/condition',
      auth: true,
      handler: 'crud',
      entity: 'condition_assessments',
      operation: 'update',
      description: 'Update condition assessment',
    },

    // Inspection appointments
    {
      method: 'POST',
      path: '/trade-in/requests/:id/inspection',
      auth: true,
      handler: 'crud',
      entity: 'inspection_appointments',
      operation: 'create',
      description: 'Schedule inspection appointment',
    },
    {
      method: 'GET',
      path: '/trade-in/inspection-slots',
      auth: false,
      handler: 'custom',
      entity: 'inspection_appointments',
      description: 'Get available inspection time slots',
    },

    // Admin
    {
      method: 'GET',
      path: '/admin/trade-ins',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'trade_in_requests',
      operation: 'list',
      description: 'List all trade-in requests (admin)',
    },
    {
      method: 'GET',
      path: '/admin/trade-ins/stats',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'trade_in_requests',
      description: 'Get trade-in statistics',
    },
    {
      method: 'PUT',
      path: '/admin/trade-ins/:id/status',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'trade_in_requests',
      description: 'Update trade-in status',
    },

    // Valuation lookup
    {
      method: 'GET',
      path: '/trade-in/market-value/:vin',
      auth: true,
      handler: 'custom',
      entity: 'valuation_history',
      description: 'Get market value from providers',
    },
    {
      method: 'GET',
      path: '/trade-in/auction-value/:vin',
      auth: true,
      role: 'appraiser',
      handler: 'custom',
      entity: 'valuation_history',
      description: 'Get auction value estimate',
    },
  ],

  config: [
    {
      key: 'valuationProvider',
      label: 'Valuation Provider',
      type: 'select',
      default: 'internal',
      options: [
        { value: 'internal', label: 'Internal Algorithm' },
        { value: 'kbb', label: 'Kelley Blue Book' },
        { value: 'blackbook', label: 'Black Book' },
        { value: 'nada', label: 'NADA Guides' },
      ],
      description: 'Primary valuation data provider',
    },
    {
      key: 'defaultMargin',
      label: 'Default Margin (%)',
      type: 'number',
      default: 15,
      description: 'Default profit margin percentage',
    },
    {
      key: 'instantOfferEnabled',
      label: 'Enable Instant Offers',
      type: 'boolean',
      default: true,
      description: 'Allow instant offer generation without manual review',
    },
    {
      key: 'offerValidityDays',
      label: 'Offer Validity (days)',
      type: 'number',
      default: 7,
      description: 'Number of days offer remains valid',
    },
    {
      key: 'requirePhotos',
      label: 'Require Photos',
      type: 'boolean',
      default: false,
      description: 'Require photo upload for valuation',
    },
    {
      key: 'minPhotoCount',
      label: 'Minimum Photo Count',
      type: 'number',
      default: 4,
      description: 'Minimum photos required if enabled',
    },
    {
      key: 'requireInspection',
      label: 'Require In-Person Inspection',
      type: 'boolean',
      default: false,
      description: 'Require physical inspection before final offer',
    },
    {
      key: 'mileageAdjustment',
      label: 'Enable Mileage Adjustment',
      type: 'boolean',
      default: true,
      description: 'Adjust value based on mileage variance',
    },
    {
      key: 'conditionMultipliers',
      label: 'Use Condition Multipliers',
      type: 'boolean',
      default: true,
      description: 'Adjust value based on vehicle condition',
    },
  ],
};
