/**
 * Vehicle Inventory Feature Definition
 *
 * Complete vehicle inventory management for automotive applications.
 * Supports new, used, and certified pre-owned vehicle listings.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const VEHICLE_INVENTORY_FEATURE: FeatureDefinition = {
  id: 'vehicle-inventory',
  name: 'Vehicle Inventory',
  category: 'business',
  description: 'Manage vehicle inventory with photos, specifications, pricing, and availability tracking',
  icon: 'car',

  includedInAppTypes: [
    'automotive-dealership',
    'car-dealership',
    'used-car-lot',
    'vehicle-marketplace',
    'auto-dealer',
    'motorcycle-dealership',
    'rv-dealership',
    'truck-dealership',
  ],

  activationKeywords: [
    'vehicle inventory',
    'car inventory',
    'vehicle listing',
    'car listing',
    'auto inventory',
    'vehicle management',
    'car catalog',
    'vehicle catalog',
    'cars for sale',
    'used cars',
    'new cars',
    'certified pre-owned',
    'cpo vehicles',
    'vehicle stock',
    'dealership inventory',
    'fleet inventory',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload'],
  conflicts: [],

  pages: [
    {
      id: 'vehicle-grid',
      route: '/vehicles',
      section: 'frontend',
      title: 'Vehicle Inventory',
      authRequired: false,
      templateId: 'vehicle-grid',
      components: [
        'vehicle-grid',
        'vehicle-card',
        'vehicle-filters',
        'price-range-slider',
        'mileage-filter',
        'year-filter',
        'make-model-filter',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'vehicle-detail',
      route: '/vehicles/:id',
      section: 'frontend',
      title: 'Vehicle Details',
      authRequired: false,
      templateId: 'vehicle-detail',
      components: [
        'vehicle-gallery',
        'vehicle-specs',
        'vehicle-features',
        'vehicle-pricing',
        'financing-calculator',
        'trade-in-estimator',
        'schedule-test-drive',
        'contact-dealer-form',
        'share-vehicle',
        'save-vehicle',
        'vehicle-history-badge',
      ],
      layout: 'default',
    },
    {
      id: 'vehicle-create',
      route: '/vehicles/new',
      section: 'frontend',
      title: 'Add Vehicle',
      authRequired: true,
      roles: ['dealer', 'admin', 'sales'],
      templateId: 'vehicle-create',
      components: [
        'vehicle-form',
        'vin-decoder',
        'make-model-selector',
        'year-selector',
        'photo-uploader',
        'specs-form',
        'features-checklist',
        'pricing-form',
        'description-editor',
      ],
      layout: 'default',
    },
    {
      id: 'vehicle-edit',
      route: '/vehicles/:id/edit',
      section: 'frontend',
      title: 'Edit Vehicle',
      authRequired: true,
      roles: ['dealer', 'admin', 'sales'],
      templateId: 'vehicle-edit',
      components: [
        'vehicle-form',
        'vin-decoder',
        'make-model-selector',
        'year-selector',
        'photo-uploader',
        'photo-manager',
        'specs-form',
        'features-checklist',
        'pricing-form',
        'description-editor',
        'vehicle-status-toggle',
      ],
      layout: 'default',
    },
    {
      id: 'my-inventory',
      route: '/my-inventory',
      section: 'frontend',
      title: 'My Inventory',
      authRequired: true,
      templateId: 'my-inventory',
      components: [
        'vehicles-table',
        'vehicle-status-filter',
        'vehicle-actions',
        'inventory-stats',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-inventory',
      route: '/admin/inventory',
      section: 'admin',
      title: 'Manage Inventory',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-inventory',
      components: [
        'vehicles-table',
        'vehicle-filters',
        'bulk-actions',
        'vehicle-approval',
        'featured-toggle',
        'inventory-analytics',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Grid/List components
    'vehicle-grid',
    'vehicle-card',
    'vehicle-list-item',
    'vehicle-filters',
    'price-range-slider',
    'mileage-filter',
    'year-filter',
    'make-model-filter',
    'sort-dropdown',
    'pagination',

    // Detail components
    'vehicle-gallery',
    'vehicle-specs',
    'vehicle-features',
    'vehicle-pricing',
    'financing-calculator',
    'trade-in-estimator',
    'schedule-test-drive',
    'contact-dealer-form',
    'share-vehicle',
    'save-vehicle',
    'vehicle-history-badge',

    // Form components
    'vehicle-form',
    'vin-decoder',
    'make-model-selector',
    'year-selector',
    'photo-uploader',
    'photo-manager',
    'specs-form',
    'features-checklist',
    'pricing-form',
    'description-editor',
    'vehicle-status-toggle',

    // Management components
    'vehicles-table',
    'vehicle-status-filter',
    'vehicle-actions',
    'inventory-stats',
    'bulk-actions',
    'vehicle-approval',
    'featured-toggle',
    'inventory-analytics',
  ],

  entities: [
    {
      name: 'vehicles',
      displayName: 'Vehicles',
      description: 'Vehicle inventory records',
      isCore: true,
    },
    {
      name: 'vehicle_images',
      displayName: 'Vehicle Images',
      description: 'Images associated with vehicles',
      isCore: true,
    },
    {
      name: 'vehicle_features',
      displayName: 'Vehicle Features',
      description: 'Features and options for vehicles',
      isCore: true,
    },
    {
      name: 'vehicle_specs',
      displayName: 'Vehicle Specifications',
      description: 'Technical specifications for vehicles',
      isCore: true,
    },
    {
      name: 'price_history',
      displayName: 'Price History',
      description: 'Historical price changes for vehicles',
      isCore: false,
    },
    {
      name: 'saved_vehicles',
      displayName: 'Saved Vehicles',
      description: 'User saved/favorited vehicles',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Vehicle CRUD
    {
      method: 'GET',
      path: '/vehicles',
      auth: false,
      handler: 'crud',
      entity: 'vehicles',
      operation: 'list',
      description: 'List all vehicles with filters',
    },
    {
      method: 'GET',
      path: '/vehicles/:id',
      auth: false,
      handler: 'crud',
      entity: 'vehicles',
      operation: 'get',
      description: 'Get vehicle details',
    },
    {
      method: 'POST',
      path: '/vehicles',
      auth: true,
      role: 'dealer',
      handler: 'crud',
      entity: 'vehicles',
      operation: 'create',
      description: 'Create new vehicle listing',
    },
    {
      method: 'PUT',
      path: '/vehicles/:id',
      auth: true,
      handler: 'crud',
      entity: 'vehicles',
      operation: 'update',
      description: 'Update vehicle listing',
    },
    {
      method: 'DELETE',
      path: '/vehicles/:id',
      auth: true,
      handler: 'crud',
      entity: 'vehicles',
      operation: 'delete',
      description: 'Delete vehicle listing',
    },

    // Vehicle Images
    {
      method: 'GET',
      path: '/vehicles/:id/images',
      auth: false,
      handler: 'crud',
      entity: 'vehicle_images',
      operation: 'list',
      description: 'Get vehicle images',
    },
    {
      method: 'POST',
      path: '/vehicles/:id/images',
      auth: true,
      handler: 'crud',
      entity: 'vehicle_images',
      operation: 'create',
      description: 'Add vehicle image',
    },
    {
      method: 'DELETE',
      path: '/vehicles/:vehicleId/images/:id',
      auth: true,
      handler: 'crud',
      entity: 'vehicle_images',
      operation: 'delete',
      description: 'Delete vehicle image',
    },
    {
      method: 'PUT',
      path: '/vehicles/:vehicleId/images/:id/primary',
      auth: true,
      handler: 'custom',
      entity: 'vehicle_images',
      description: 'Set primary image',
    },

    // Vehicle Features
    {
      method: 'GET',
      path: '/vehicles/:id/features',
      auth: false,
      handler: 'crud',
      entity: 'vehicle_features',
      operation: 'list',
      description: 'Get vehicle features',
    },
    {
      method: 'PUT',
      path: '/vehicles/:id/features',
      auth: true,
      handler: 'custom',
      entity: 'vehicle_features',
      description: 'Update vehicle features',
    },

    // VIN Decoder
    {
      method: 'GET',
      path: '/vehicles/decode-vin/:vin',
      auth: true,
      handler: 'custom',
      entity: 'vehicles',
      description: 'Decode VIN to get vehicle info',
    },

    // Saved Vehicles
    {
      method: 'GET',
      path: '/saved-vehicles',
      auth: true,
      handler: 'crud',
      entity: 'saved_vehicles',
      operation: 'list',
      description: 'Get user saved vehicles',
    },
    {
      method: 'POST',
      path: '/vehicles/:id/save',
      auth: true,
      handler: 'custom',
      entity: 'saved_vehicles',
      description: 'Save vehicle to favorites',
    },
    {
      method: 'DELETE',
      path: '/vehicles/:id/save',
      auth: true,
      handler: 'custom',
      entity: 'saved_vehicles',
      description: 'Remove vehicle from favorites',
    },

    // Status management
    {
      method: 'PUT',
      path: '/vehicles/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'vehicles',
      description: 'Update vehicle status',
    },
    {
      method: 'PUT',
      path: '/vehicles/:id/featured',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'vehicles',
      description: 'Toggle featured status',
    },

    // Search and filters
    {
      method: 'GET',
      path: '/vehicles/search',
      auth: false,
      handler: 'custom',
      entity: 'vehicles',
      description: 'Search vehicles',
    },
    {
      method: 'GET',
      path: '/vehicles/makes',
      auth: false,
      handler: 'custom',
      entity: 'vehicles',
      description: 'Get available makes',
    },
    {
      method: 'GET',
      path: '/vehicles/models/:make',
      auth: false,
      handler: 'custom',
      entity: 'vehicles',
      description: 'Get models for a make',
    },
  ],

  config: [
    {
      key: 'allowPublicListings',
      label: 'Allow Public Vehicle Listings',
      type: 'boolean',
      default: false,
      description: 'Allow non-dealers to create listings',
    },
    {
      key: 'requireApproval',
      label: 'Require Admin Approval',
      type: 'boolean',
      default: true,
      description: 'Require admin approval before listings go live',
    },
    {
      key: 'maxImages',
      label: 'Maximum Images Per Vehicle',
      type: 'number',
      default: 50,
      description: 'Maximum number of images allowed per vehicle',
    },
    {
      key: 'defaultListingDuration',
      label: 'Default Listing Duration (days)',
      type: 'number',
      default: 60,
      description: 'How long listings remain active by default',
    },
    {
      key: 'enablePriceHistory',
      label: 'Enable Price History Tracking',
      type: 'boolean',
      default: true,
      description: 'Track historical price changes',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for pricing',
    },
    {
      key: 'vehicleTypes',
      label: 'Vehicle Types',
      type: 'select',
      default: 'all',
      options: [
        { value: 'all', label: 'All Types' },
        { value: 'cars', label: 'Cars Only' },
        { value: 'trucks', label: 'Trucks Only' },
        { value: 'suvs', label: 'SUVs Only' },
        { value: 'motorcycles', label: 'Motorcycles Only' },
      ],
      description: 'Types of vehicles to support',
    },
    {
      key: 'vinDecoder',
      label: 'Enable VIN Decoder',
      type: 'boolean',
      default: true,
      description: 'Enable automatic VIN decoding',
    },
  ],
};
