/**
 * Vehicle Financing Feature Definition
 *
 * Complete auto loan and financing calculator for automotive applications.
 * Supports payment calculation, credit applications, and lender integrations.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const VEHICLE_FINANCING_FEATURE: FeatureDefinition = {
  id: 'vehicle-financing',
  name: 'Vehicle Financing',
  category: 'business',
  description: 'Auto loan calculators, credit applications, and financing management',
  icon: 'credit-card',

  includedInAppTypes: [
    'automotive-dealership',
    'car-dealership',
    'used-car-lot',
    'vehicle-marketplace',
    'auto-dealer',
    'credit-union',
    'auto-lender',
    'buy-here-pay-here',
  ],

  activationKeywords: [
    'auto financing',
    'car financing',
    'vehicle financing',
    'auto loan',
    'car loan',
    'payment calculator',
    'monthly payment',
    'finance application',
    'credit application',
    'auto credit',
    'car payment',
    'loan calculator',
    'apr calculator',
    'buy here pay here',
    'subprime auto',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'vehicle-inventory'],
  conflicts: [],

  pages: [
    {
      id: 'payment-calculator',
      route: '/financing/calculator',
      section: 'frontend',
      title: 'Payment Calculator',
      authRequired: false,
      templateId: 'payment-calculator',
      components: [
        'vehicle-price-input',
        'down-payment-slider',
        'trade-in-input',
        'term-selector',
        'apr-input',
        'payment-breakdown',
        'amortization-preview',
        'pre-qualify-button',
      ],
      layout: 'centered',
    },
    {
      id: 'vehicle-financing',
      route: '/vehicles/:id/financing',
      section: 'frontend',
      title: 'Financing Options',
      authRequired: false,
      templateId: 'vehicle-financing',
      components: [
        'vehicle-summary',
        'payment-scenarios',
        'term-comparison',
        'total-cost-breakdown',
        'special-offers',
        'apply-now-button',
      ],
      layout: 'default',
    },
    {
      id: 'finance-application',
      route: '/financing/apply',
      section: 'frontend',
      title: 'Finance Application',
      authRequired: false,
      templateId: 'finance-application',
      components: [
        'application-progress',
        'personal-info-form',
        'employment-info-form',
        'income-info-form',
        'residence-info-form',
        'co-applicant-form',
        'consent-checkboxes',
        'submit-application',
      ],
      layout: 'default',
    },
    {
      id: 'pre-qualification',
      route: '/financing/pre-qualify',
      section: 'frontend',
      title: 'Pre-Qualification',
      authRequired: false,
      templateId: 'pre-qualification',
      components: [
        'quick-form',
        'soft-credit-notice',
        'estimated-terms',
        'pre-qual-result',
        'next-steps',
      ],
      layout: 'centered',
    },
    {
      id: 'application-status',
      route: '/financing/status/:id',
      section: 'frontend',
      title: 'Application Status',
      authRequired: true,
      templateId: 'application-status',
      components: [
        'status-timeline',
        'application-summary',
        'required-documents',
        'document-upload',
        'approval-details',
        'next-steps-action',
      ],
      layout: 'default',
    },
    {
      id: 'my-applications',
      route: '/my-financing',
      section: 'frontend',
      title: 'My Applications',
      authRequired: true,
      templateId: 'my-applications',
      components: [
        'applications-list',
        'active-loans',
        'payment-schedule',
        'make-payment-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-applications',
      route: '/admin/financing',
      section: 'admin',
      title: 'Finance Applications',
      authRequired: true,
      roles: ['admin', 'finance-manager'],
      templateId: 'admin-applications',
      components: [
        'applications-table',
        'status-filter',
        'credit-decision-panel',
        'lender-submissions',
        'deal-structure',
        'financing-analytics',
      ],
      layout: 'admin',
    },
    {
      id: 'application-review',
      route: '/admin/financing/:id',
      section: 'admin',
      title: 'Application Review',
      authRequired: true,
      roles: ['admin', 'finance-manager'],
      templateId: 'application-review',
      components: [
        'applicant-info',
        'credit-report',
        'income-verification',
        'stipulation-manager',
        'lender-quotes',
        'deal-calculator',
        'decision-actions',
        'contract-generator',
      ],
      layout: 'admin',
    },
    {
      id: 'financing-settings',
      route: '/admin/financing/settings',
      section: 'admin',
      title: 'Financing Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'financing-settings',
      components: [
        'lender-config',
        'rate-markup',
        'term-options',
        'credit-tiers',
        'special-programs',
        'compliance-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calculator components
    'vehicle-price-input',
    'down-payment-slider',
    'trade-in-input',
    'term-selector',
    'apr-input',
    'payment-breakdown',
    'amortization-preview',
    'pre-qualify-button',

    // Vehicle financing components
    'vehicle-summary',
    'payment-scenarios',
    'term-comparison',
    'total-cost-breakdown',
    'special-offers',
    'apply-now-button',

    // Application components
    'application-progress',
    'personal-info-form',
    'employment-info-form',
    'income-info-form',
    'residence-info-form',
    'co-applicant-form',
    'consent-checkboxes',
    'submit-application',

    // Pre-qualification components
    'quick-form',
    'soft-credit-notice',
    'estimated-terms',
    'pre-qual-result',
    'next-steps',

    // Status components
    'status-timeline',
    'application-summary',
    'required-documents',
    'document-upload',
    'approval-details',
    'next-steps-action',

    // Customer components
    'applications-list',
    'active-loans',
    'payment-schedule',
    'make-payment-button',

    // Admin components
    'applications-table',
    'status-filter',
    'credit-decision-panel',
    'lender-submissions',
    'deal-structure',
    'financing-analytics',

    // Review components
    'applicant-info',
    'credit-report',
    'income-verification',
    'stipulation-manager',
    'lender-quotes',
    'deal-calculator',
    'decision-actions',
    'contract-generator',

    // Settings components
    'lender-config',
    'rate-markup',
    'term-options',
    'credit-tiers',
    'special-programs',
    'compliance-settings',
  ],

  entities: [
    {
      name: 'finance_applications',
      displayName: 'Finance Applications',
      description: 'Customer credit applications',
      isCore: true,
    },
    {
      name: 'lender_submissions',
      displayName: 'Lender Submissions',
      description: 'Applications submitted to lenders',
      isCore: true,
    },
    {
      name: 'lender_decisions',
      displayName: 'Lender Decisions',
      description: 'Lender approval/denial decisions',
      isCore: true,
    },
    {
      name: 'loan_contracts',
      displayName: 'Loan Contracts',
      description: 'Finalized loan contracts',
      isCore: true,
    },
    {
      name: 'lenders',
      displayName: 'Lenders',
      description: 'Available lending partners',
      isCore: false,
    },
    {
      name: 'rate_programs',
      displayName: 'Rate Programs',
      description: 'Special rate programs and incentives',
      isCore: false,
    },
    {
      name: 'stipulations',
      displayName: 'Stipulations',
      description: 'Required documents and conditions',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Calculator
    {
      method: 'POST',
      path: '/financing/calculate',
      auth: false,
      handler: 'custom',
      entity: 'finance_applications',
      description: 'Calculate payment options',
    },
    {
      method: 'GET',
      path: '/financing/rates',
      auth: false,
      handler: 'custom',
      entity: 'rate_programs',
      description: 'Get current rate ranges',
    },
    {
      method: 'GET',
      path: '/financing/terms',
      auth: false,
      handler: 'custom',
      entity: 'rate_programs',
      description: 'Get available loan terms',
    },

    // Pre-qualification
    {
      method: 'POST',
      path: '/financing/pre-qualify',
      auth: false,
      handler: 'custom',
      entity: 'finance_applications',
      description: 'Submit pre-qualification request',
    },
    {
      method: 'GET',
      path: '/financing/pre-qualify/:id',
      auth: true,
      handler: 'custom',
      entity: 'finance_applications',
      description: 'Get pre-qualification result',
    },

    // Applications
    {
      method: 'GET',
      path: '/financing/applications',
      auth: true,
      handler: 'crud',
      entity: 'finance_applications',
      operation: 'list',
      description: 'List user applications',
    },
    {
      method: 'GET',
      path: '/financing/applications/:id',
      auth: true,
      handler: 'crud',
      entity: 'finance_applications',
      operation: 'get',
      description: 'Get application details',
    },
    {
      method: 'POST',
      path: '/financing/applications',
      auth: false,
      handler: 'crud',
      entity: 'finance_applications',
      operation: 'create',
      description: 'Submit finance application',
    },
    {
      method: 'PUT',
      path: '/financing/applications/:id',
      auth: true,
      handler: 'crud',
      entity: 'finance_applications',
      operation: 'update',
      description: 'Update application',
    },

    // Documents/Stipulations
    {
      method: 'GET',
      path: '/financing/applications/:id/stipulations',
      auth: true,
      handler: 'crud',
      entity: 'stipulations',
      operation: 'list',
      description: 'Get required stipulations',
    },
    {
      method: 'POST',
      path: '/financing/applications/:id/documents',
      auth: true,
      handler: 'custom',
      entity: 'stipulations',
      description: 'Upload required documents',
    },
    {
      method: 'PUT',
      path: '/financing/applications/:appId/stipulations/:id',
      auth: true,
      role: 'finance-manager',
      handler: 'custom',
      entity: 'stipulations',
      description: 'Update stipulation status',
    },

    // Lender submissions
    {
      method: 'POST',
      path: '/financing/applications/:id/submit-lender',
      auth: true,
      role: 'finance-manager',
      handler: 'custom',
      entity: 'lender_submissions',
      description: 'Submit to lender',
    },
    {
      method: 'GET',
      path: '/financing/applications/:id/lender-decisions',
      auth: true,
      role: 'finance-manager',
      handler: 'crud',
      entity: 'lender_decisions',
      operation: 'list',
      description: 'Get lender decisions',
    },
    {
      method: 'PUT',
      path: '/financing/applications/:id/select-lender',
      auth: true,
      role: 'finance-manager',
      handler: 'custom',
      entity: 'lender_decisions',
      description: 'Select lender offer',
    },

    // Contracts
    {
      method: 'POST',
      path: '/financing/applications/:id/contract',
      auth: true,
      role: 'finance-manager',
      handler: 'crud',
      entity: 'loan_contracts',
      operation: 'create',
      description: 'Generate loan contract',
    },
    {
      method: 'GET',
      path: '/financing/contracts/:id',
      auth: true,
      handler: 'crud',
      entity: 'loan_contracts',
      operation: 'get',
      description: 'Get contract details',
    },
    {
      method: 'PUT',
      path: '/financing/contracts/:id/sign',
      auth: true,
      handler: 'custom',
      entity: 'loan_contracts',
      description: 'Sign contract',
    },

    // Admin
    {
      method: 'GET',
      path: '/admin/financing/applications',
      auth: true,
      role: 'finance-manager',
      handler: 'crud',
      entity: 'finance_applications',
      operation: 'list',
      description: 'List all applications (admin)',
    },
    {
      method: 'PUT',
      path: '/admin/financing/applications/:id/status',
      auth: true,
      role: 'finance-manager',
      handler: 'custom',
      entity: 'finance_applications',
      description: 'Update application status',
    },
    {
      method: 'GET',
      path: '/admin/financing/lenders',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'lenders',
      operation: 'list',
      description: 'Get lender list',
    },
    {
      method: 'POST',
      path: '/admin/financing/lenders',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'lenders',
      operation: 'create',
      description: 'Add lender',
    },
    {
      method: 'PUT',
      path: '/admin/financing/lenders/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'lenders',
      operation: 'update',
      description: 'Update lender',
    },
    {
      method: 'GET',
      path: '/admin/financing/stats',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'finance_applications',
      description: 'Get financing statistics',
    },
  ],

  config: [
    {
      key: 'minDownPayment',
      label: 'Minimum Down Payment (%)',
      type: 'number',
      default: 0,
      description: 'Minimum down payment percentage required',
    },
    {
      key: 'maxLoanTerm',
      label: 'Maximum Loan Term (months)',
      type: 'number',
      default: 84,
      description: 'Maximum loan term in months',
    },
    {
      key: 'defaultAPR',
      label: 'Default APR (%)',
      type: 'number',
      default: 6.99,
      description: 'Default APR for calculator',
    },
    {
      key: 'baseRateMarkup',
      label: 'Base Rate Markup (%)',
      type: 'number',
      default: 2.0,
      description: 'Dealer markup on buy rate',
    },
    {
      key: 'enablePreQualification',
      label: 'Enable Pre-Qualification',
      type: 'boolean',
      default: true,
      description: 'Allow soft credit pull pre-qualification',
    },
    {
      key: 'enableOnlineApplication',
      label: 'Enable Online Application',
      type: 'boolean',
      default: true,
      description: 'Allow online credit application submission',
    },
    {
      key: 'autoSubmitToLenders',
      label: 'Auto-Submit to Lenders',
      type: 'boolean',
      default: false,
      description: 'Automatically submit to lenders upon approval',
    },
    {
      key: 'requireCoApplicant',
      label: 'Require Co-Applicant Option',
      type: 'boolean',
      default: true,
      description: 'Show co-applicant option on applications',
    },
    {
      key: 'creditTiers',
      label: 'Credit Tier System',
      type: 'select',
      default: 'standard',
      options: [
        { value: 'standard', label: 'Standard (Prime/Subprime)' },
        { value: 'detailed', label: 'Detailed (5-tier)' },
        { value: 'custom', label: 'Custom Tiers' },
      ],
      description: 'Credit scoring tier system to use',
    },
  ],
};
