/**
 * Change Orders Feature Definition
 *
 * Change order management for construction projects.
 * Supports change request, approval workflow, and cost tracking.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CHANGE_ORDERS_FEATURE: FeatureDefinition = {
  id: 'change-orders',
  name: 'Change Orders',
  category: 'business',
  description: 'Manage construction change orders with approval workflows and cost impact tracking',
  icon: 'file-diff',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'project-management',
    'contract-management',
    'change-management',
  ],

  activationKeywords: [
    'change order',
    'change orders',
    'co management',
    'change request',
    'construction change',
    'scope change',
    'contract modification',
    'variation order',
    'extra work order',
    'field order',
    'change directive',
    'cost change',
    'schedule change',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'projects', 'contracts'],
  conflicts: [],

  pages: [
    {
      id: 'change-orders-list',
      route: '/change-orders',
      section: 'frontend',
      title: 'Change Orders',
      authRequired: true,
      templateId: 'change-orders-list',
      components: [
        'change-order-grid',
        'change-order-card',
        'change-order-filters',
        'project-filter',
        'status-tabs',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'change-order-detail',
      route: '/change-orders/:id',
      section: 'frontend',
      title: 'Change Order Details',
      authRequired: true,
      templateId: 'change-order-detail',
      components: [
        'change-order-header',
        'change-order-summary',
        'scope-description',
        'cost-breakdown',
        'schedule-impact',
        'justification-section',
        'supporting-documents',
        'approval-workflow',
        'approval-history',
        'change-order-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'change-order-create',
      route: '/change-orders/new',
      section: 'frontend',
      title: 'Create Change Order',
      authRequired: true,
      roles: ['project-manager', 'superintendent', 'admin'],
      templateId: 'change-order-create',
      components: [
        'change-order-form',
        'project-selector',
        'contract-selector',
        'scope-editor',
        'cost-estimator',
        'schedule-impact-form',
        'justification-editor',
        'document-uploader',
        'approvers-selector',
      ],
      layout: 'dashboard',
    },
    {
      id: 'change-order-edit',
      route: '/change-orders/:id/edit',
      section: 'frontend',
      title: 'Edit Change Order',
      authRequired: true,
      roles: ['project-manager', 'admin'],
      templateId: 'change-order-edit',
      components: [
        'change-order-form',
        'scope-editor',
        'cost-estimator',
        'schedule-impact-form',
        'justification-editor',
        'document-manager',
        'revision-history',
        'status-toggle',
      ],
      layout: 'dashboard',
    },
    {
      id: 'change-order-approval',
      route: '/change-orders/:id/approve',
      section: 'frontend',
      title: 'Approve Change Order',
      authRequired: true,
      roles: ['project-manager', 'owner', 'admin'],
      templateId: 'change-order-approval',
      components: [
        'change-order-summary',
        'cost-impact-display',
        'schedule-impact-display',
        'approval-form',
        'signature-pad',
        'rejection-form',
        'approval-comments',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-change-orders',
      route: '/admin/change-orders',
      section: 'admin',
      title: 'Manage Change Orders',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-change-orders',
      components: [
        'change-orders-table',
        'change-order-filters',
        'bulk-actions',
        'cost-analytics',
        'approval-analytics',
        'export-change-orders',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Grid/List components
    'change-order-grid',
    'change-order-card',
    'change-order-list-item',
    'change-order-filters',
    'project-filter',
    'status-tabs',
    'sort-dropdown',
    'pagination',

    // Detail components
    'change-order-header',
    'change-order-summary',
    'scope-description',
    'cost-breakdown',
    'schedule-impact',
    'justification-section',
    'supporting-documents',
    'approval-workflow',
    'approval-history',
    'change-order-actions',

    // Form components
    'change-order-form',
    'project-selector',
    'contract-selector',
    'scope-editor',
    'cost-estimator',
    'schedule-impact-form',
    'justification-editor',
    'document-uploader',
    'document-manager',
    'approvers-selector',
    'revision-history',
    'status-toggle',

    // Approval components
    'cost-impact-display',
    'schedule-impact-display',
    'approval-form',
    'signature-pad',
    'rejection-form',
    'approval-comments',

    // Admin components
    'change-orders-table',
    'bulk-actions',
    'cost-analytics',
    'approval-analytics',
    'export-change-orders',
  ],

  entities: [
    {
      name: 'change_orders',
      displayName: 'Change Orders',
      description: 'Change order records',
      isCore: true,
    },
    {
      name: 'change_order_items',
      displayName: 'Change Order Items',
      description: 'Line items in change orders',
      isCore: true,
    },
    {
      name: 'change_order_documents',
      displayName: 'Change Order Documents',
      description: 'Supporting documents',
      isCore: true,
    },
    {
      name: 'change_order_approvals',
      displayName: 'Change Order Approvals',
      description: 'Approval records and signatures',
      isCore: true,
    },
    {
      name: 'change_order_revisions',
      displayName: 'Change Order Revisions',
      description: 'Historical revisions',
      isCore: false,
    },
    {
      name: 'change_order_templates',
      displayName: 'Change Order Templates',
      description: 'Reusable templates',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Change Orders CRUD
    {
      method: 'GET',
      path: '/change-orders',
      auth: true,
      handler: 'crud',
      entity: 'change_orders',
      operation: 'list',
      description: 'List change orders',
    },
    {
      method: 'GET',
      path: '/change-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'change_orders',
      operation: 'get',
      description: 'Get change order details',
    },
    {
      method: 'POST',
      path: '/change-orders',
      auth: true,
      role: 'project-manager',
      handler: 'crud',
      entity: 'change_orders',
      operation: 'create',
      description: 'Create change order',
    },
    {
      method: 'PUT',
      path: '/change-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'change_orders',
      operation: 'update',
      description: 'Update change order',
    },
    {
      method: 'DELETE',
      path: '/change-orders/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'change_orders',
      operation: 'delete',
      description: 'Delete change order',
    },

    // Change Order Items
    {
      method: 'GET',
      path: '/change-orders/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'change_order_items',
      operation: 'list',
      description: 'Get change order items',
    },
    {
      method: 'POST',
      path: '/change-orders/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'change_order_items',
      operation: 'create',
      description: 'Add item',
    },
    {
      method: 'PUT',
      path: '/change-orders/:coId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'change_order_items',
      operation: 'update',
      description: 'Update item',
    },
    {
      method: 'DELETE',
      path: '/change-orders/:coId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'change_order_items',
      operation: 'delete',
      description: 'Delete item',
    },

    // Documents
    {
      method: 'GET',
      path: '/change-orders/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'change_order_documents',
      operation: 'list',
      description: 'Get documents',
    },
    {
      method: 'POST',
      path: '/change-orders/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'change_order_documents',
      operation: 'create',
      description: 'Add document',
    },
    {
      method: 'DELETE',
      path: '/change-orders/:coId/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'change_order_documents',
      operation: 'delete',
      description: 'Delete document',
    },

    // Approval Workflow
    {
      method: 'GET',
      path: '/change-orders/:id/approvals',
      auth: true,
      handler: 'crud',
      entity: 'change_order_approvals',
      operation: 'list',
      description: 'Get approval history',
    },
    {
      method: 'POST',
      path: '/change-orders/:id/submit',
      auth: true,
      handler: 'custom',
      entity: 'change_orders',
      description: 'Submit for approval',
    },
    {
      method: 'POST',
      path: '/change-orders/:id/approve',
      auth: true,
      role: 'project-manager',
      handler: 'custom',
      entity: 'change_orders',
      description: 'Approve change order',
    },
    {
      method: 'POST',
      path: '/change-orders/:id/reject',
      auth: true,
      role: 'project-manager',
      handler: 'custom',
      entity: 'change_orders',
      description: 'Reject change order',
    },
    {
      method: 'POST',
      path: '/change-orders/:id/revise',
      auth: true,
      handler: 'custom',
      entity: 'change_orders',
      description: 'Request revision',
    },

    // Status and Actions
    {
      method: 'PUT',
      path: '/change-orders/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'change_orders',
      description: 'Update status',
    },
    {
      method: 'POST',
      path: '/change-orders/:id/void',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'change_orders',
      description: 'Void change order',
    },

    // Reports
    {
      method: 'GET',
      path: '/change-orders/:id/export',
      auth: true,
      handler: 'custom',
      entity: 'change_orders',
      description: 'Export change order',
    },
    {
      method: 'GET',
      path: '/projects/:projectId/change-orders/summary',
      auth: true,
      handler: 'custom',
      entity: 'change_orders',
      description: 'Get project CO summary',
    },
  ],

  config: [
    {
      key: 'requireApproval',
      label: 'Require Approval',
      type: 'boolean',
      default: true,
      description: 'Require approval workflow for change orders',
    },
    {
      key: 'approvalThreshold',
      label: 'Owner Approval Threshold',
      type: 'number',
      default: 10000,
      description: 'Amount above which owner approval is required',
    },
    {
      key: 'requireSignature',
      label: 'Require Digital Signature',
      type: 'boolean',
      default: true,
      description: 'Require digital signature on approvals',
    },
    {
      key: 'autoNumbering',
      label: 'Auto Number Change Orders',
      type: 'boolean',
      default: true,
      description: 'Automatically assign CO numbers',
    },
    {
      key: 'numberPrefix',
      label: 'CO Number Prefix',
      type: 'string',
      default: 'CO-',
      description: 'Prefix for change order numbers',
    },
    {
      key: 'trackRevisions',
      label: 'Track Revisions',
      type: 'boolean',
      default: true,
      description: 'Maintain revision history',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for costs',
    },
    {
      key: 'notifyOnSubmission',
      label: 'Notify on Submission',
      type: 'boolean',
      default: true,
      description: 'Send notifications when CO is submitted',
    },
  ],
};
