/**
 * Daily Logs Feature Definition
 *
 * Construction daily report management for tracking work progress.
 * Supports weather, labor, equipment, and activity documentation.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const DAILY_LOGS_FEATURE: FeatureDefinition = {
  id: 'daily-logs',
  name: 'Daily Logs',
  category: 'business',
  description: 'Track daily construction activities, weather, labor hours, and progress reports',
  icon: 'clipboard-list',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'project-management',
    'site-management',
    'field-reporting',
  ],

  activationKeywords: [
    'daily log',
    'daily logs',
    'daily report',
    'daily reports',
    'construction log',
    'field report',
    'site report',
    'progress report',
    'daily diary',
    'superintendent log',
    'foreman report',
    'work log',
    'activity log',
    'job diary',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'projects'],
  conflicts: [],

  pages: [
    {
      id: 'daily-logs-list',
      route: '/daily-logs',
      section: 'frontend',
      title: 'Daily Logs',
      authRequired: true,
      templateId: 'daily-logs-list',
      components: [
        'log-calendar',
        'log-grid',
        'log-card',
        'log-filters',
        'project-filter',
        'date-range-picker',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'daily-log-detail',
      route: '/daily-logs/:id',
      section: 'frontend',
      title: 'Daily Log Details',
      authRequired: true,
      templateId: 'daily-log-detail',
      components: [
        'log-header',
        'weather-summary',
        'work-summary',
        'labor-hours-table',
        'equipment-usage',
        'material-deliveries',
        'visitor-log',
        'activity-timeline',
        'photos-gallery',
        'notes-section',
        'signature-section',
      ],
      layout: 'dashboard',
    },
    {
      id: 'daily-log-create',
      route: '/daily-logs/new',
      section: 'frontend',
      title: 'Create Daily Log',
      authRequired: true,
      roles: ['superintendent', 'foreman', 'project-manager', 'admin'],
      templateId: 'daily-log-create',
      components: [
        'log-form',
        'project-selector',
        'date-picker',
        'weather-form',
        'work-description-editor',
        'labor-hours-form',
        'equipment-form',
        'material-form',
        'visitor-form',
        'photo-uploader',
        'signature-pad',
      ],
      layout: 'dashboard',
    },
    {
      id: 'daily-log-edit',
      route: '/daily-logs/:id/edit',
      section: 'frontend',
      title: 'Edit Daily Log',
      authRequired: true,
      roles: ['superintendent', 'foreman', 'project-manager', 'admin'],
      templateId: 'daily-log-edit',
      components: [
        'log-form',
        'weather-form',
        'work-description-editor',
        'labor-hours-form',
        'equipment-form',
        'material-form',
        'visitor-form',
        'photo-manager',
        'signature-pad',
        'revision-history',
      ],
      layout: 'dashboard',
    },
    {
      id: 'daily-logs-summary',
      route: '/daily-logs/summary',
      section: 'frontend',
      title: 'Logs Summary',
      authRequired: true,
      templateId: 'daily-logs-summary',
      components: [
        'summary-stats',
        'labor-summary-chart',
        'equipment-summary-chart',
        'weather-impact-chart',
        'progress-timeline',
        'export-options',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-daily-logs',
      route: '/admin/daily-logs',
      section: 'admin',
      title: 'Manage Daily Logs',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-daily-logs',
      components: [
        'logs-table',
        'log-filters',
        'bulk-actions',
        'log-analytics',
        'template-manager',
        'export-logs',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List/Calendar components
    'log-calendar',
    'log-grid',
    'log-card',
    'log-list-item',
    'log-filters',
    'project-filter',
    'date-range-picker',
    'pagination',

    // Detail components
    'log-header',
    'weather-summary',
    'work-summary',
    'labor-hours-table',
    'equipment-usage',
    'material-deliveries',
    'visitor-log',
    'activity-timeline',
    'photos-gallery',
    'notes-section',
    'signature-section',

    // Form components
    'log-form',
    'project-selector',
    'date-picker',
    'weather-form',
    'work-description-editor',
    'labor-hours-form',
    'equipment-form',
    'material-form',
    'visitor-form',
    'photo-uploader',
    'photo-manager',
    'signature-pad',
    'revision-history',

    // Summary components
    'summary-stats',
    'labor-summary-chart',
    'equipment-summary-chart',
    'weather-impact-chart',
    'progress-timeline',
    'export-options',

    // Admin components
    'logs-table',
    'bulk-actions',
    'log-analytics',
    'template-manager',
    'export-logs',
  ],

  entities: [
    {
      name: 'daily_logs',
      displayName: 'Daily Logs',
      description: 'Daily construction log records',
      isCore: true,
    },
    {
      name: 'log_labor_entries',
      displayName: 'Labor Entries',
      description: 'Labor hours recorded in logs',
      isCore: true,
    },
    {
      name: 'log_equipment_entries',
      displayName: 'Equipment Entries',
      description: 'Equipment usage in logs',
      isCore: true,
    },
    {
      name: 'log_material_entries',
      displayName: 'Material Entries',
      description: 'Material deliveries in logs',
      isCore: true,
    },
    {
      name: 'log_visitors',
      displayName: 'Log Visitors',
      description: 'Site visitor records',
      isCore: false,
    },
    {
      name: 'log_photos',
      displayName: 'Log Photos',
      description: 'Photos attached to logs',
      isCore: true,
    },
    {
      name: 'log_templates',
      displayName: 'Log Templates',
      description: 'Daily log templates',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Daily Logs CRUD
    {
      method: 'GET',
      path: '/daily-logs',
      auth: true,
      handler: 'crud',
      entity: 'daily_logs',
      operation: 'list',
      description: 'List daily logs',
    },
    {
      method: 'GET',
      path: '/daily-logs/:id',
      auth: true,
      handler: 'crud',
      entity: 'daily_logs',
      operation: 'get',
      description: 'Get daily log details',
    },
    {
      method: 'POST',
      path: '/daily-logs',
      auth: true,
      role: 'foreman',
      handler: 'crud',
      entity: 'daily_logs',
      operation: 'create',
      description: 'Create daily log',
    },
    {
      method: 'PUT',
      path: '/daily-logs/:id',
      auth: true,
      handler: 'crud',
      entity: 'daily_logs',
      operation: 'update',
      description: 'Update daily log',
    },
    {
      method: 'DELETE',
      path: '/daily-logs/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'daily_logs',
      operation: 'delete',
      description: 'Delete daily log',
    },

    // Labor Entries
    {
      method: 'GET',
      path: '/daily-logs/:id/labor',
      auth: true,
      handler: 'crud',
      entity: 'log_labor_entries',
      operation: 'list',
      description: 'Get labor entries',
    },
    {
      method: 'POST',
      path: '/daily-logs/:id/labor',
      auth: true,
      handler: 'crud',
      entity: 'log_labor_entries',
      operation: 'create',
      description: 'Add labor entry',
    },
    {
      method: 'PUT',
      path: '/daily-logs/:logId/labor/:id',
      auth: true,
      handler: 'crud',
      entity: 'log_labor_entries',
      operation: 'update',
      description: 'Update labor entry',
    },
    {
      method: 'DELETE',
      path: '/daily-logs/:logId/labor/:id',
      auth: true,
      handler: 'crud',
      entity: 'log_labor_entries',
      operation: 'delete',
      description: 'Delete labor entry',
    },

    // Equipment Entries
    {
      method: 'GET',
      path: '/daily-logs/:id/equipment',
      auth: true,
      handler: 'crud',
      entity: 'log_equipment_entries',
      operation: 'list',
      description: 'Get equipment entries',
    },
    {
      method: 'POST',
      path: '/daily-logs/:id/equipment',
      auth: true,
      handler: 'crud',
      entity: 'log_equipment_entries',
      operation: 'create',
      description: 'Add equipment entry',
    },
    {
      method: 'PUT',
      path: '/daily-logs/:logId/equipment/:id',
      auth: true,
      handler: 'crud',
      entity: 'log_equipment_entries',
      operation: 'update',
      description: 'Update equipment entry',
    },

    // Material Entries
    {
      method: 'GET',
      path: '/daily-logs/:id/materials',
      auth: true,
      handler: 'crud',
      entity: 'log_material_entries',
      operation: 'list',
      description: 'Get material entries',
    },
    {
      method: 'POST',
      path: '/daily-logs/:id/materials',
      auth: true,
      handler: 'crud',
      entity: 'log_material_entries',
      operation: 'create',
      description: 'Add material entry',
    },

    // Photos
    {
      method: 'GET',
      path: '/daily-logs/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'log_photos',
      operation: 'list',
      description: 'Get log photos',
    },
    {
      method: 'POST',
      path: '/daily-logs/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'log_photos',
      operation: 'create',
      description: 'Add photo',
    },
    {
      method: 'DELETE',
      path: '/daily-logs/:logId/photos/:id',
      auth: true,
      handler: 'crud',
      entity: 'log_photos',
      operation: 'delete',
      description: 'Delete photo',
    },

    // Visitors
    {
      method: 'GET',
      path: '/daily-logs/:id/visitors',
      auth: true,
      handler: 'crud',
      entity: 'log_visitors',
      operation: 'list',
      description: 'Get visitors',
    },
    {
      method: 'POST',
      path: '/daily-logs/:id/visitors',
      auth: true,
      handler: 'crud',
      entity: 'log_visitors',
      operation: 'create',
      description: 'Add visitor',
    },

    // Actions and Reports
    {
      method: 'POST',
      path: '/daily-logs/:id/submit',
      auth: true,
      handler: 'custom',
      entity: 'daily_logs',
      description: 'Submit log for approval',
    },
    {
      method: 'POST',
      path: '/daily-logs/:id/approve',
      auth: true,
      role: 'project-manager',
      handler: 'custom',
      entity: 'daily_logs',
      description: 'Approve daily log',
    },
    {
      method: 'GET',
      path: '/daily-logs/summary',
      auth: true,
      handler: 'custom',
      entity: 'daily_logs',
      description: 'Get logs summary',
    },
    {
      method: 'GET',
      path: '/daily-logs/:id/export',
      auth: true,
      handler: 'custom',
      entity: 'daily_logs',
      description: 'Export log to PDF',
    },

    // Weather
    {
      method: 'GET',
      path: '/weather/current',
      auth: true,
      handler: 'custom',
      entity: 'daily_logs',
      description: 'Get current weather data',
    },
  ],

  config: [
    {
      key: 'requireWeather',
      label: 'Require Weather Information',
      type: 'boolean',
      default: true,
      description: 'Require weather data on daily logs',
    },
    {
      key: 'requirePhotos',
      label: 'Require Photos',
      type: 'boolean',
      default: false,
      description: 'Require at least one photo per log',
    },
    {
      key: 'requireSignature',
      label: 'Require Signature',
      type: 'boolean',
      default: true,
      description: 'Require signature on submission',
    },
    {
      key: 'requireApproval',
      label: 'Require Manager Approval',
      type: 'boolean',
      default: true,
      description: 'Require project manager approval',
    },
    {
      key: 'autoFetchWeather',
      label: 'Auto-Fetch Weather',
      type: 'boolean',
      default: true,
      description: 'Automatically fetch weather from API',
    },
    {
      key: 'defaultStartTime',
      label: 'Default Work Start Time',
      type: 'string',
      default: '07:00',
      description: 'Default start time for work day',
    },
    {
      key: 'defaultEndTime',
      label: 'Default Work End Time',
      type: 'string',
      default: '17:00',
      description: 'Default end time for work day',
    },
    {
      key: 'lockAfterDays',
      label: 'Lock Logs After (days)',
      type: 'number',
      default: 3,
      description: 'Days after which logs cannot be edited',
    },
  ],
};
