/**
 * Equipment Tracking Feature Definition
 *
 * Heavy equipment management for construction projects.
 * Supports tracking, maintenance, utilization, and cost allocation.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const EQUIPMENT_TRACKING_FEATURE: FeatureDefinition = {
  id: 'equipment-tracking',
  name: 'Equipment Tracking',
  category: 'business',
  description: 'Manage heavy equipment with maintenance schedules, utilization tracking, and cost allocation',
  icon: 'truck',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'equipment-rental',
    'fleet-management',
    'asset-management',
  ],

  activationKeywords: [
    'equipment tracking',
    'heavy equipment',
    'equipment management',
    'machinery tracking',
    'fleet management',
    'equipment rental',
    'equipment maintenance',
    'equipment utilization',
    'asset tracking',
    'equipment scheduling',
    'equipment cost',
    'plant equipment',
    'construction equipment',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'projects'],
  conflicts: [],

  pages: [
    {
      id: 'equipment-list',
      route: '/equipment',
      section: 'frontend',
      title: 'Equipment',
      authRequired: true,
      templateId: 'equipment-list',
      components: [
        'equipment-grid',
        'equipment-card',
        'equipment-filters',
        'category-filter',
        'status-filter',
        'location-filter',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'equipment-detail',
      route: '/equipment/:id',
      section: 'frontend',
      title: 'Equipment Details',
      authRequired: true,
      templateId: 'equipment-detail',
      components: [
        'equipment-header',
        'equipment-info',
        'equipment-photos',
        'equipment-specs',
        'current-assignment',
        'maintenance-schedule',
        'maintenance-history',
        'utilization-chart',
        'cost-summary',
        'equipment-documents',
        'equipment-notes',
      ],
      layout: 'dashboard',
    },
    {
      id: 'equipment-create',
      route: '/equipment/new',
      section: 'frontend',
      title: 'Add Equipment',
      authRequired: true,
      roles: ['equipment-manager', 'admin'],
      templateId: 'equipment-create',
      components: [
        'equipment-form',
        'category-selector',
        'specs-form',
        'photo-uploader',
        'document-uploader',
        'cost-rate-form',
        'maintenance-schedule-form',
      ],
      layout: 'dashboard',
    },
    {
      id: 'equipment-edit',
      route: '/equipment/:id/edit',
      section: 'frontend',
      title: 'Edit Equipment',
      authRequired: true,
      roles: ['equipment-manager', 'admin'],
      templateId: 'equipment-edit',
      components: [
        'equipment-form',
        'category-selector',
        'specs-form',
        'photo-manager',
        'document-manager',
        'cost-rate-form',
        'maintenance-schedule-form',
        'status-toggle',
      ],
      layout: 'dashboard',
    },
    {
      id: 'equipment-schedule',
      route: '/equipment/schedule',
      section: 'frontend',
      title: 'Equipment Schedule',
      authRequired: true,
      templateId: 'equipment-schedule',
      components: [
        'equipment-calendar',
        'assignment-list',
        'availability-view',
        'conflict-alerts',
        'quick-assign',
      ],
      layout: 'dashboard',
    },
    {
      id: 'equipment-maintenance',
      route: '/equipment/:id/maintenance',
      section: 'frontend',
      title: 'Maintenance',
      authRequired: true,
      templateId: 'equipment-maintenance',
      components: [
        'maintenance-dashboard',
        'upcoming-maintenance',
        'maintenance-log',
        'service-form',
        'parts-tracker',
        'cost-tracker',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-equipment',
      route: '/admin/equipment',
      section: 'admin',
      title: 'Manage Equipment',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-equipment',
      components: [
        'equipment-table',
        'equipment-filters',
        'bulk-actions',
        'utilization-analytics',
        'cost-analytics',
        'maintenance-analytics',
        'export-equipment',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Grid/List components
    'equipment-grid',
    'equipment-card',
    'equipment-list-item',
    'equipment-filters',
    'category-filter',
    'status-filter',
    'location-filter',
    'sort-dropdown',
    'pagination',

    // Detail components
    'equipment-header',
    'equipment-info',
    'equipment-photos',
    'equipment-specs',
    'current-assignment',
    'maintenance-schedule',
    'maintenance-history',
    'utilization-chart',
    'cost-summary',
    'equipment-documents',
    'equipment-notes',

    // Form components
    'equipment-form',
    'category-selector',
    'specs-form',
    'photo-uploader',
    'photo-manager',
    'document-uploader',
    'document-manager',
    'cost-rate-form',
    'maintenance-schedule-form',
    'status-toggle',

    // Schedule components
    'equipment-calendar',
    'assignment-list',
    'availability-view',
    'conflict-alerts',
    'quick-assign',

    // Maintenance components
    'maintenance-dashboard',
    'upcoming-maintenance',
    'maintenance-log',
    'service-form',
    'parts-tracker',
    'cost-tracker',

    // Admin components
    'equipment-table',
    'bulk-actions',
    'utilization-analytics',
    'cost-analytics',
    'maintenance-analytics',
    'export-equipment',
  ],

  entities: [
    {
      name: 'equipment',
      displayName: 'Equipment',
      description: 'Equipment records',
      isCore: true,
    },
    {
      name: 'equipment_assignments',
      displayName: 'Equipment Assignments',
      description: 'Project assignments for equipment',
      isCore: true,
    },
    {
      name: 'equipment_maintenance',
      displayName: 'Maintenance Records',
      description: 'Maintenance service records',
      isCore: true,
    },
    {
      name: 'equipment_photos',
      displayName: 'Equipment Photos',
      description: 'Photos of equipment',
      isCore: true,
    },
    {
      name: 'equipment_documents',
      displayName: 'Equipment Documents',
      description: 'Manuals, certifications, etc.',
      isCore: true,
    },
    {
      name: 'equipment_categories',
      displayName: 'Equipment Categories',
      description: 'Equipment type categories',
      isCore: true,
    },
    {
      name: 'equipment_utilization',
      displayName: 'Utilization Logs',
      description: 'Usage and hour tracking',
      isCore: false,
    },
    {
      name: 'equipment_costs',
      displayName: 'Equipment Costs',
      description: 'Cost records and allocations',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Equipment CRUD
    {
      method: 'GET',
      path: '/equipment',
      auth: true,
      handler: 'crud',
      entity: 'equipment',
      operation: 'list',
      description: 'List equipment',
    },
    {
      method: 'GET',
      path: '/equipment/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment',
      operation: 'get',
      description: 'Get equipment details',
    },
    {
      method: 'POST',
      path: '/equipment',
      auth: true,
      role: 'equipment-manager',
      handler: 'crud',
      entity: 'equipment',
      operation: 'create',
      description: 'Add equipment',
    },
    {
      method: 'PUT',
      path: '/equipment/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment',
      operation: 'update',
      description: 'Update equipment',
    },
    {
      method: 'DELETE',
      path: '/equipment/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment',
      operation: 'delete',
      description: 'Delete equipment',
    },

    // Assignments
    {
      method: 'GET',
      path: '/equipment/:id/assignments',
      auth: true,
      handler: 'crud',
      entity: 'equipment_assignments',
      operation: 'list',
      description: 'Get equipment assignments',
    },
    {
      method: 'POST',
      path: '/equipment/:id/assignments',
      auth: true,
      handler: 'crud',
      entity: 'equipment_assignments',
      operation: 'create',
      description: 'Assign equipment to project',
    },
    {
      method: 'PUT',
      path: '/equipment/:equipId/assignments/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_assignments',
      operation: 'update',
      description: 'Update assignment',
    },
    {
      method: 'DELETE',
      path: '/equipment/:equipId/assignments/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_assignments',
      operation: 'delete',
      description: 'Remove assignment',
    },

    // Maintenance
    {
      method: 'GET',
      path: '/equipment/:id/maintenance',
      auth: true,
      handler: 'crud',
      entity: 'equipment_maintenance',
      operation: 'list',
      description: 'Get maintenance records',
    },
    {
      method: 'POST',
      path: '/equipment/:id/maintenance',
      auth: true,
      handler: 'crud',
      entity: 'equipment_maintenance',
      operation: 'create',
      description: 'Add maintenance record',
    },
    {
      method: 'PUT',
      path: '/equipment/:equipId/maintenance/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_maintenance',
      operation: 'update',
      description: 'Update maintenance record',
    },
    {
      method: 'GET',
      path: '/equipment/maintenance/upcoming',
      auth: true,
      handler: 'custom',
      entity: 'equipment_maintenance',
      description: 'Get upcoming maintenance',
    },
    {
      method: 'GET',
      path: '/equipment/maintenance/overdue',
      auth: true,
      handler: 'custom',
      entity: 'equipment_maintenance',
      description: 'Get overdue maintenance',
    },

    // Photos
    {
      method: 'GET',
      path: '/equipment/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'equipment_photos',
      operation: 'list',
      description: 'Get equipment photos',
    },
    {
      method: 'POST',
      path: '/equipment/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'equipment_photos',
      operation: 'create',
      description: 'Add photo',
    },
    {
      method: 'DELETE',
      path: '/equipment/:equipId/photos/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_photos',
      operation: 'delete',
      description: 'Delete photo',
    },

    // Documents
    {
      method: 'GET',
      path: '/equipment/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'equipment_documents',
      operation: 'list',
      description: 'Get equipment documents',
    },
    {
      method: 'POST',
      path: '/equipment/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'equipment_documents',
      operation: 'create',
      description: 'Add document',
    },
    {
      method: 'DELETE',
      path: '/equipment/:equipId/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'equipment_documents',
      operation: 'delete',
      description: 'Delete document',
    },

    // Utilization
    {
      method: 'GET',
      path: '/equipment/:id/utilization',
      auth: true,
      handler: 'crud',
      entity: 'equipment_utilization',
      operation: 'list',
      description: 'Get utilization logs',
    },
    {
      method: 'POST',
      path: '/equipment/:id/utilization',
      auth: true,
      handler: 'crud',
      entity: 'equipment_utilization',
      operation: 'create',
      description: 'Log utilization',
    },
    {
      method: 'GET',
      path: '/equipment/:id/utilization/summary',
      auth: true,
      handler: 'custom',
      entity: 'equipment_utilization',
      description: 'Get utilization summary',
    },

    // Costs
    {
      method: 'GET',
      path: '/equipment/:id/costs',
      auth: true,
      handler: 'crud',
      entity: 'equipment_costs',
      operation: 'list',
      description: 'Get cost records',
    },
    {
      method: 'POST',
      path: '/equipment/:id/costs',
      auth: true,
      handler: 'crud',
      entity: 'equipment_costs',
      operation: 'create',
      description: 'Add cost record',
    },

    // Categories
    {
      method: 'GET',
      path: '/equipment-categories',
      auth: true,
      handler: 'crud',
      entity: 'equipment_categories',
      operation: 'list',
      description: 'List categories',
    },
    {
      method: 'POST',
      path: '/equipment-categories',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'equipment_categories',
      operation: 'create',
      description: 'Add category',
    },

    // Status and Availability
    {
      method: 'PUT',
      path: '/equipment/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'equipment',
      description: 'Update equipment status',
    },
    {
      method: 'GET',
      path: '/equipment/available',
      auth: true,
      handler: 'custom',
      entity: 'equipment',
      description: 'Get available equipment',
    },
    {
      method: 'GET',
      path: '/equipment/schedule',
      auth: true,
      handler: 'custom',
      entity: 'equipment_assignments',
      description: 'Get equipment schedule',
    },
  ],

  config: [
    {
      key: 'trackHours',
      label: 'Track Equipment Hours',
      type: 'boolean',
      default: true,
      description: 'Track operating hours for equipment',
    },
    {
      key: 'trackFuel',
      label: 'Track Fuel Usage',
      type: 'boolean',
      default: true,
      description: 'Track fuel consumption',
    },
    {
      key: 'maintenanceAlertDays',
      label: 'Maintenance Alert Days',
      type: 'number',
      default: 7,
      description: 'Days before maintenance to send alert',
    },
    {
      key: 'maintenanceAlertHours',
      label: 'Maintenance Alert Hours',
      type: 'number',
      default: 50,
      description: 'Hours before service to send alert',
    },
    {
      key: 'defaultHourlyRate',
      label: 'Default Hourly Rate',
      type: 'number',
      default: 150,
      description: 'Default cost rate per hour',
    },
    {
      key: 'defaultDailyRate',
      label: 'Default Daily Rate',
      type: 'number',
      default: 1000,
      description: 'Default cost rate per day',
    },
    {
      key: 'enableGpsTracking',
      label: 'Enable GPS Tracking',
      type: 'boolean',
      default: false,
      description: 'Enable GPS location tracking',
    },
    {
      key: 'requireCheckoutInspection',
      label: 'Require Checkout Inspection',
      type: 'boolean',
      default: true,
      description: 'Require inspection before checkout',
    },
  ],
};
