/**
 * Material Takeoffs Feature Definition
 *
 * Material quantity calculations and takeoff management for construction projects.
 * Supports automated calculations, cost estimation, and procurement integration.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const MATERIAL_TAKEOFFS_FEATURE: FeatureDefinition = {
  id: 'material-takeoffs',
  name: 'Material Takeoffs',
  category: 'business',
  description: 'Calculate and manage material quantities with cost estimation and procurement tracking',
  icon: 'calculator',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'project-estimation',
    'material-management',
    'quantity-surveying',
  ],

  activationKeywords: [
    'material takeoff',
    'material takeoffs',
    'quantity takeoff',
    'material quantities',
    'material calculation',
    'quantity calculation',
    'material estimation',
    'bill of materials',
    'bom',
    'quantity surveying',
    'material list',
    'material schedule',
    'takeoff sheet',
    'material requirements',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'projects'],
  conflicts: [],

  pages: [
    {
      id: 'takeoffs-list',
      route: '/takeoffs',
      section: 'frontend',
      title: 'Material Takeoffs',
      authRequired: true,
      templateId: 'takeoffs-list',
      components: [
        'takeoff-grid',
        'takeoff-card',
        'takeoff-filters',
        'project-filter',
        'status-tabs',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'takeoff-detail',
      route: '/takeoffs/:id',
      section: 'frontend',
      title: 'Takeoff Details',
      authRequired: true,
      templateId: 'takeoff-detail',
      components: [
        'takeoff-header',
        'takeoff-summary',
        'material-table',
        'quantity-breakdown',
        'cost-summary',
        'unit-prices',
        'takeoff-notes',
        'drawing-references',
        'export-buttons',
      ],
      layout: 'dashboard',
    },
    {
      id: 'takeoff-create',
      route: '/takeoffs/new',
      section: 'frontend',
      title: 'Create Takeoff',
      authRequired: true,
      roles: ['estimator', 'project-manager', 'admin'],
      templateId: 'takeoff-create',
      components: [
        'takeoff-form',
        'project-selector',
        'material-selector',
        'quantity-input',
        'unit-selector',
        'calculation-helper',
        'drawing-uploader',
        'material-search',
      ],
      layout: 'dashboard',
    },
    {
      id: 'takeoff-edit',
      route: '/takeoffs/:id/edit',
      section: 'frontend',
      title: 'Edit Takeoff',
      authRequired: true,
      roles: ['estimator', 'project-manager', 'admin'],
      templateId: 'takeoff-edit',
      components: [
        'takeoff-form',
        'material-table-editor',
        'quantity-adjuster',
        'waste-factor-input',
        'unit-price-editor',
        'drawing-manager',
        'revision-history',
      ],
      layout: 'dashboard',
    },
    {
      id: 'takeoff-calculator',
      route: '/takeoffs/:id/calculator',
      section: 'frontend',
      title: 'Quantity Calculator',
      authRequired: true,
      templateId: 'takeoff-calculator',
      components: [
        'area-calculator',
        'volume-calculator',
        'linear-calculator',
        'count-calculator',
        'waste-calculator',
        'conversion-tools',
        'formula-library',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-takeoffs',
      route: '/admin/takeoffs',
      section: 'admin',
      title: 'Manage Takeoffs',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-takeoffs',
      components: [
        'takeoffs-table',
        'takeoff-filters',
        'bulk-actions',
        'material-library',
        'pricing-manager',
        'export-takeoffs',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Grid/List components
    'takeoff-grid',
    'takeoff-card',
    'takeoff-list-item',
    'takeoff-filters',
    'project-filter',
    'status-tabs',
    'pagination',

    // Detail components
    'takeoff-header',
    'takeoff-summary',
    'material-table',
    'quantity-breakdown',
    'cost-summary',
    'unit-prices',
    'takeoff-notes',
    'drawing-references',
    'export-buttons',

    // Form components
    'takeoff-form',
    'project-selector',
    'material-selector',
    'quantity-input',
    'unit-selector',
    'calculation-helper',
    'drawing-uploader',
    'drawing-manager',
    'material-search',
    'material-table-editor',
    'quantity-adjuster',
    'waste-factor-input',
    'unit-price-editor',
    'revision-history',

    // Calculator components
    'area-calculator',
    'volume-calculator',
    'linear-calculator',
    'count-calculator',
    'waste-calculator',
    'conversion-tools',
    'formula-library',

    // Management components
    'takeoffs-table',
    'bulk-actions',
    'material-library',
    'pricing-manager',
    'export-takeoffs',
  ],

  entities: [
    {
      name: 'takeoffs',
      displayName: 'Takeoffs',
      description: 'Material takeoff records',
      isCore: true,
    },
    {
      name: 'takeoff_items',
      displayName: 'Takeoff Items',
      description: 'Individual material items in takeoff',
      isCore: true,
    },
    {
      name: 'materials',
      displayName: 'Materials',
      description: 'Material library catalog',
      isCore: true,
    },
    {
      name: 'material_prices',
      displayName: 'Material Prices',
      description: 'Unit pricing for materials',
      isCore: true,
    },
    {
      name: 'takeoff_drawings',
      displayName: 'Takeoff Drawings',
      description: 'Drawing references for takeoffs',
      isCore: false,
    },
    {
      name: 'takeoff_formulas',
      displayName: 'Calculation Formulas',
      description: 'Saved calculation formulas',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Takeoff CRUD
    {
      method: 'GET',
      path: '/takeoffs',
      auth: true,
      handler: 'crud',
      entity: 'takeoffs',
      operation: 'list',
      description: 'List all takeoffs',
    },
    {
      method: 'GET',
      path: '/takeoffs/:id',
      auth: true,
      handler: 'crud',
      entity: 'takeoffs',
      operation: 'get',
      description: 'Get takeoff details',
    },
    {
      method: 'POST',
      path: '/takeoffs',
      auth: true,
      role: 'estimator',
      handler: 'crud',
      entity: 'takeoffs',
      operation: 'create',
      description: 'Create new takeoff',
    },
    {
      method: 'PUT',
      path: '/takeoffs/:id',
      auth: true,
      handler: 'crud',
      entity: 'takeoffs',
      operation: 'update',
      description: 'Update takeoff',
    },
    {
      method: 'DELETE',
      path: '/takeoffs/:id',
      auth: true,
      handler: 'crud',
      entity: 'takeoffs',
      operation: 'delete',
      description: 'Delete takeoff',
    },

    // Takeoff Items
    {
      method: 'GET',
      path: '/takeoffs/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'takeoff_items',
      operation: 'list',
      description: 'Get takeoff items',
    },
    {
      method: 'POST',
      path: '/takeoffs/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'takeoff_items',
      operation: 'create',
      description: 'Add takeoff item',
    },
    {
      method: 'PUT',
      path: '/takeoffs/:takeoffId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'takeoff_items',
      operation: 'update',
      description: 'Update takeoff item',
    },
    {
      method: 'DELETE',
      path: '/takeoffs/:takeoffId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'takeoff_items',
      operation: 'delete',
      description: 'Delete takeoff item',
    },

    // Materials Library
    {
      method: 'GET',
      path: '/materials',
      auth: true,
      handler: 'crud',
      entity: 'materials',
      operation: 'list',
      description: 'List materials',
    },
    {
      method: 'GET',
      path: '/materials/:id',
      auth: true,
      handler: 'crud',
      entity: 'materials',
      operation: 'get',
      description: 'Get material details',
    },
    {
      method: 'POST',
      path: '/materials',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'materials',
      operation: 'create',
      description: 'Add material to library',
    },
    {
      method: 'PUT',
      path: '/materials/:id',
      auth: true,
      handler: 'crud',
      entity: 'materials',
      operation: 'update',
      description: 'Update material',
    },

    // Material Prices
    {
      method: 'GET',
      path: '/materials/:id/prices',
      auth: true,
      handler: 'crud',
      entity: 'material_prices',
      operation: 'list',
      description: 'Get material prices',
    },
    {
      method: 'POST',
      path: '/materials/:id/prices',
      auth: true,
      handler: 'crud',
      entity: 'material_prices',
      operation: 'create',
      description: 'Add material price',
    },
    {
      method: 'PUT',
      path: '/materials/:materialId/prices/:id',
      auth: true,
      handler: 'crud',
      entity: 'material_prices',
      operation: 'update',
      description: 'Update material price',
    },

    // Calculations
    {
      method: 'POST',
      path: '/takeoffs/:id/calculate',
      auth: true,
      handler: 'custom',
      entity: 'takeoffs',
      description: 'Recalculate takeoff totals',
    },
    {
      method: 'POST',
      path: '/takeoffs/:id/apply-waste-factor',
      auth: true,
      handler: 'custom',
      entity: 'takeoffs',
      description: 'Apply waste factor to quantities',
    },

    // Export
    {
      method: 'GET',
      path: '/takeoffs/:id/export',
      auth: true,
      handler: 'custom',
      entity: 'takeoffs',
      description: 'Export takeoff to spreadsheet',
    },

    // Duplicate
    {
      method: 'POST',
      path: '/takeoffs/:id/duplicate',
      auth: true,
      handler: 'custom',
      entity: 'takeoffs',
      description: 'Duplicate takeoff',
    },
  ],

  config: [
    {
      key: 'defaultWasteFactorPercentage',
      label: 'Default Waste Factor (%)',
      type: 'number',
      default: 10,
      description: 'Default waste factor to add to quantities',
    },
    {
      key: 'defaultUnit',
      label: 'Default Unit of Measure',
      type: 'string',
      default: 'each',
      description: 'Default unit for new materials',
    },
    {
      key: 'enablePriceTracking',
      label: 'Enable Price History',
      type: 'boolean',
      default: true,
      description: 'Track historical material prices',
    },
    {
      key: 'autoUpdatePrices',
      label: 'Auto-Update Prices',
      type: 'boolean',
      default: false,
      description: 'Automatically update prices from suppliers',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for pricing',
    },
    {
      key: 'roundingPrecision',
      label: 'Quantity Rounding Precision',
      type: 'number',
      default: 2,
      description: 'Decimal places for quantity rounding',
    },
    {
      key: 'requireDrawingReference',
      label: 'Require Drawing Reference',
      type: 'boolean',
      default: false,
      description: 'Require drawing reference for each item',
    },
  ],
};
