/**
 * Project Bids Feature Definition
 *
 * Comprehensive bid management and estimation for construction projects.
 * Supports bid creation, tracking, comparison, and award management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PROJECT_BIDS_FEATURE: FeatureDefinition = {
  id: 'project-bids',
  name: 'Project Bids',
  category: 'business',
  description: 'Manage construction project bids with estimation, tracking, and comparison tools',
  icon: 'gavel',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'subcontractor-management',
    'project-estimation',
    'bid-management',
  ],

  activationKeywords: [
    'project bid',
    'project bids',
    'bid management',
    'construction bid',
    'bid estimation',
    'cost estimation',
    'bid tracking',
    'bid comparison',
    'rfp management',
    'request for proposal',
    'bid submission',
    'contractor bid',
    'bid award',
    'bid package',
    'estimate',
    'proposal',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'projects'],
  conflicts: [],

  pages: [
    {
      id: 'bids-list',
      route: '/bids',
      section: 'frontend',
      title: 'Project Bids',
      authRequired: true,
      templateId: 'bids-list',
      components: [
        'bid-grid',
        'bid-card',
        'bid-filters',
        'bid-status-tabs',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'bid-detail',
      route: '/bids/:id',
      section: 'frontend',
      title: 'Bid Details',
      authRequired: true,
      templateId: 'bid-detail',
      components: [
        'bid-header',
        'bid-summary',
        'bid-breakdown',
        'cost-line-items',
        'labor-estimates',
        'material-costs',
        'bid-documents',
        'bid-timeline',
        'bid-notes',
        'bid-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'bid-create',
      route: '/bids/new',
      section: 'frontend',
      title: 'Create Bid',
      authRequired: true,
      roles: ['estimator', 'project-manager', 'admin'],
      templateId: 'bid-create',
      components: [
        'bid-form',
        'project-selector',
        'cost-estimator',
        'line-item-builder',
        'markup-calculator',
        'contingency-settings',
        'document-uploader',
        'bid-preview',
      ],
      layout: 'dashboard',
    },
    {
      id: 'bid-edit',
      route: '/bids/:id/edit',
      section: 'frontend',
      title: 'Edit Bid',
      authRequired: true,
      roles: ['estimator', 'project-manager', 'admin'],
      templateId: 'bid-edit',
      components: [
        'bid-form',
        'cost-estimator',
        'line-item-builder',
        'markup-calculator',
        'contingency-settings',
        'document-manager',
        'revision-history',
        'bid-status-toggle',
      ],
      layout: 'dashboard',
    },
    {
      id: 'bid-compare',
      route: '/projects/:projectId/compare-bids',
      section: 'frontend',
      title: 'Compare Bids',
      authRequired: true,
      roles: ['project-manager', 'admin', 'owner'],
      templateId: 'bid-compare',
      components: [
        'bid-comparison-table',
        'cost-comparison-chart',
        'bid-ranking',
        'bid-notes-comparison',
        'award-recommendation',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-bids',
      route: '/admin/bids',
      section: 'admin',
      title: 'Manage Bids',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-bids',
      components: [
        'bids-table',
        'bid-filters',
        'bulk-actions',
        'bid-analytics',
        'export-bids',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Grid/List components
    'bid-grid',
    'bid-card',
    'bid-list-item',
    'bid-filters',
    'bid-status-tabs',
    'sort-dropdown',
    'pagination',

    // Detail components
    'bid-header',
    'bid-summary',
    'bid-breakdown',
    'cost-line-items',
    'labor-estimates',
    'material-costs',
    'bid-documents',
    'bid-timeline',
    'bid-notes',
    'bid-actions',

    // Form components
    'bid-form',
    'project-selector',
    'cost-estimator',
    'line-item-builder',
    'markup-calculator',
    'contingency-settings',
    'document-uploader',
    'document-manager',
    'bid-preview',
    'revision-history',
    'bid-status-toggle',

    // Comparison components
    'bid-comparison-table',
    'cost-comparison-chart',
    'bid-ranking',
    'bid-notes-comparison',
    'award-recommendation',

    // Management components
    'bids-table',
    'bulk-actions',
    'bid-analytics',
    'export-bids',
  ],

  entities: [
    {
      name: 'bids',
      displayName: 'Bids',
      description: 'Project bid records',
      isCore: true,
    },
    {
      name: 'bid_line_items',
      displayName: 'Bid Line Items',
      description: 'Individual cost items within a bid',
      isCore: true,
    },
    {
      name: 'bid_documents',
      displayName: 'Bid Documents',
      description: 'Documents attached to bids',
      isCore: true,
    },
    {
      name: 'bid_revisions',
      displayName: 'Bid Revisions',
      description: 'Historical revisions of bids',
      isCore: false,
    },
    {
      name: 'bid_templates',
      displayName: 'Bid Templates',
      description: 'Reusable bid templates',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Bid CRUD
    {
      method: 'GET',
      path: '/bids',
      auth: true,
      handler: 'crud',
      entity: 'bids',
      operation: 'list',
      description: 'List all bids with filters',
    },
    {
      method: 'GET',
      path: '/bids/:id',
      auth: true,
      handler: 'crud',
      entity: 'bids',
      operation: 'get',
      description: 'Get bid details',
    },
    {
      method: 'POST',
      path: '/bids',
      auth: true,
      role: 'estimator',
      handler: 'crud',
      entity: 'bids',
      operation: 'create',
      description: 'Create new bid',
    },
    {
      method: 'PUT',
      path: '/bids/:id',
      auth: true,
      handler: 'crud',
      entity: 'bids',
      operation: 'update',
      description: 'Update bid',
    },
    {
      method: 'DELETE',
      path: '/bids/:id',
      auth: true,
      handler: 'crud',
      entity: 'bids',
      operation: 'delete',
      description: 'Delete bid',
    },

    // Bid Line Items
    {
      method: 'GET',
      path: '/bids/:id/line-items',
      auth: true,
      handler: 'crud',
      entity: 'bid_line_items',
      operation: 'list',
      description: 'Get bid line items',
    },
    {
      method: 'POST',
      path: '/bids/:id/line-items',
      auth: true,
      handler: 'crud',
      entity: 'bid_line_items',
      operation: 'create',
      description: 'Add line item to bid',
    },
    {
      method: 'PUT',
      path: '/bids/:bidId/line-items/:id',
      auth: true,
      handler: 'crud',
      entity: 'bid_line_items',
      operation: 'update',
      description: 'Update line item',
    },
    {
      method: 'DELETE',
      path: '/bids/:bidId/line-items/:id',
      auth: true,
      handler: 'crud',
      entity: 'bid_line_items',
      operation: 'delete',
      description: 'Delete line item',
    },

    // Bid Documents
    {
      method: 'GET',
      path: '/bids/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'bid_documents',
      operation: 'list',
      description: 'Get bid documents',
    },
    {
      method: 'POST',
      path: '/bids/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'bid_documents',
      operation: 'create',
      description: 'Add document to bid',
    },
    {
      method: 'DELETE',
      path: '/bids/:bidId/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'bid_documents',
      operation: 'delete',
      description: 'Delete bid document',
    },

    // Bid Status and Actions
    {
      method: 'PUT',
      path: '/bids/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'bids',
      description: 'Update bid status',
    },
    {
      method: 'POST',
      path: '/bids/:id/submit',
      auth: true,
      handler: 'custom',
      entity: 'bids',
      description: 'Submit bid for review',
    },
    {
      method: 'POST',
      path: '/bids/:id/award',
      auth: true,
      role: 'project-manager',
      handler: 'custom',
      entity: 'bids',
      description: 'Award bid to contractor',
    },
    {
      method: 'POST',
      path: '/bids/:id/duplicate',
      auth: true,
      handler: 'custom',
      entity: 'bids',
      description: 'Duplicate bid as template',
    },

    // Bid Comparison
    {
      method: 'GET',
      path: '/projects/:projectId/bids/compare',
      auth: true,
      handler: 'custom',
      entity: 'bids',
      description: 'Compare project bids',
    },

    // Bid Templates
    {
      method: 'GET',
      path: '/bid-templates',
      auth: true,
      handler: 'crud',
      entity: 'bid_templates',
      operation: 'list',
      description: 'List bid templates',
    },
    {
      method: 'POST',
      path: '/bid-templates',
      auth: true,
      handler: 'crud',
      entity: 'bid_templates',
      operation: 'create',
      description: 'Create bid template',
    },
  ],

  config: [
    {
      key: 'defaultMarkupPercentage',
      label: 'Default Markup Percentage',
      type: 'number',
      default: 15,
      description: 'Default markup percentage for bids',
    },
    {
      key: 'defaultContingencyPercentage',
      label: 'Default Contingency Percentage',
      type: 'number',
      default: 10,
      description: 'Default contingency percentage for bids',
    },
    {
      key: 'requireApproval',
      label: 'Require Bid Approval',
      type: 'boolean',
      default: true,
      description: 'Require manager approval before bid submission',
    },
    {
      key: 'trackRevisions',
      label: 'Track Bid Revisions',
      type: 'boolean',
      default: true,
      description: 'Maintain history of bid changes',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for bid amounts',
    },
    {
      key: 'bidExpirationDays',
      label: 'Bid Expiration (days)',
      type: 'number',
      default: 30,
      description: 'Default number of days before bid expires',
    },
    {
      key: 'allowMultipleBids',
      label: 'Allow Multiple Bids Per Project',
      type: 'boolean',
      default: true,
      description: 'Allow contractors to submit multiple bids for same project',
    },
  ],
};
