/**
 * Punch Lists Feature Definition
 *
 * Punch list tracking for construction project closeout.
 * Supports item creation, assignment, verification, and closeout.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PUNCH_LISTS_FEATURE: FeatureDefinition = {
  id: 'punch-lists',
  name: 'Punch Lists',
  category: 'business',
  description: 'Track punch list items for construction closeout with assignments and verification',
  icon: 'check-square',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'project-management',
    'quality-control',
    'closeout-management',
  ],

  activationKeywords: [
    'punch list',
    'punch lists',
    'punchlist',
    'snag list',
    'deficiency list',
    'closeout list',
    'final inspection',
    'quality control',
    'defect tracking',
    'completion list',
    'work remaining',
    'outstanding items',
    'project closeout',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'projects'],
  conflicts: [],

  pages: [
    {
      id: 'punch-lists-overview',
      route: '/punch-lists',
      section: 'frontend',
      title: 'Punch Lists',
      authRequired: true,
      templateId: 'punch-lists-overview',
      components: [
        'punch-list-grid',
        'punch-list-card',
        'punch-list-filters',
        'project-filter',
        'status-summary',
        'progress-overview',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'punch-list-detail',
      route: '/punch-lists/:id',
      section: 'frontend',
      title: 'Punch List Details',
      authRequired: true,
      templateId: 'punch-list-detail',
      components: [
        'punch-list-header',
        'punch-list-stats',
        'item-grid',
        'item-card',
        'item-filters',
        'status-filter',
        'location-filter',
        'trade-filter',
        'priority-filter',
        'bulk-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'punch-item-detail',
      route: '/punch-lists/:listId/items/:id',
      section: 'frontend',
      title: 'Punch Item Details',
      authRequired: true,
      templateId: 'punch-item-detail',
      components: [
        'item-header',
        'item-description',
        'item-location',
        'item-photos',
        'item-assignment',
        'item-timeline',
        'item-comments',
        'item-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'punch-list-create',
      route: '/punch-lists/new',
      section: 'frontend',
      title: 'Create Punch List',
      authRequired: true,
      roles: ['project-manager', 'superintendent', 'admin'],
      templateId: 'punch-list-create',
      components: [
        'punch-list-form',
        'project-selector',
        'location-selector',
        'due-date-picker',
        'description-editor',
      ],
      layout: 'dashboard',
    },
    {
      id: 'punch-item-create',
      route: '/punch-lists/:listId/items/new',
      section: 'frontend',
      title: 'Add Punch Item',
      authRequired: true,
      roles: ['project-manager', 'superintendent', 'inspector', 'admin'],
      templateId: 'punch-item-create',
      components: [
        'punch-item-form',
        'location-picker',
        'trade-selector',
        'priority-selector',
        'assignee-selector',
        'photo-capture',
        'description-editor',
        'due-date-picker',
      ],
      layout: 'dashboard',
    },
    {
      id: 'punch-walkthrough',
      route: '/punch-lists/:id/walkthrough',
      section: 'frontend',
      title: 'Punch Walkthrough',
      authRequired: true,
      templateId: 'punch-walkthrough',
      components: [
        'walkthrough-mode',
        'quick-add-item',
        'photo-capture',
        'voice-notes',
        'location-tag',
        'item-list-sidebar',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'admin-punch-lists',
      route: '/admin/punch-lists',
      section: 'admin',
      title: 'Manage Punch Lists',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-punch-lists',
      components: [
        'punch-lists-table',
        'punch-list-filters',
        'bulk-actions',
        'completion-analytics',
        'trade-analytics',
        'export-punch-lists',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Overview components
    'punch-list-grid',
    'punch-list-card',
    'punch-list-list-item',
    'punch-list-filters',
    'project-filter',
    'status-summary',
    'progress-overview',
    'pagination',

    // Detail components
    'punch-list-header',
    'punch-list-stats',
    'item-grid',
    'item-card',
    'item-filters',
    'status-filter',
    'location-filter',
    'trade-filter',
    'priority-filter',
    'bulk-actions',

    // Item detail components
    'item-header',
    'item-description',
    'item-location',
    'item-photos',
    'item-assignment',
    'item-timeline',
    'item-comments',
    'item-actions',

    // Form components
    'punch-list-form',
    'punch-item-form',
    'project-selector',
    'location-selector',
    'location-picker',
    'trade-selector',
    'priority-selector',
    'assignee-selector',
    'photo-capture',
    'description-editor',
    'due-date-picker',

    // Walkthrough components
    'walkthrough-mode',
    'quick-add-item',
    'voice-notes',
    'location-tag',
    'item-list-sidebar',

    // Admin components
    'punch-lists-table',
    'completion-analytics',
    'trade-analytics',
    'export-punch-lists',
  ],

  entities: [
    {
      name: 'punch_lists',
      displayName: 'Punch Lists',
      description: 'Punch list records',
      isCore: true,
    },
    {
      name: 'punch_items',
      displayName: 'Punch Items',
      description: 'Individual punch list items',
      isCore: true,
    },
    {
      name: 'punch_item_photos',
      displayName: 'Punch Item Photos',
      description: 'Photos for punch items',
      isCore: true,
    },
    {
      name: 'punch_item_comments',
      displayName: 'Punch Item Comments',
      description: 'Comments on punch items',
      isCore: false,
    },
    {
      name: 'punch_item_history',
      displayName: 'Punch Item History',
      description: 'Status change history',
      isCore: false,
    },
    {
      name: 'punch_locations',
      displayName: 'Punch Locations',
      description: 'Predefined location tags',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Punch Lists CRUD
    {
      method: 'GET',
      path: '/punch-lists',
      auth: true,
      handler: 'crud',
      entity: 'punch_lists',
      operation: 'list',
      description: 'List punch lists',
    },
    {
      method: 'GET',
      path: '/punch-lists/:id',
      auth: true,
      handler: 'crud',
      entity: 'punch_lists',
      operation: 'get',
      description: 'Get punch list details',
    },
    {
      method: 'POST',
      path: '/punch-lists',
      auth: true,
      role: 'project-manager',
      handler: 'crud',
      entity: 'punch_lists',
      operation: 'create',
      description: 'Create punch list',
    },
    {
      method: 'PUT',
      path: '/punch-lists/:id',
      auth: true,
      handler: 'crud',
      entity: 'punch_lists',
      operation: 'update',
      description: 'Update punch list',
    },
    {
      method: 'DELETE',
      path: '/punch-lists/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'punch_lists',
      operation: 'delete',
      description: 'Delete punch list',
    },

    // Punch Items CRUD
    {
      method: 'GET',
      path: '/punch-lists/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'punch_items',
      operation: 'list',
      description: 'List punch items',
    },
    {
      method: 'GET',
      path: '/punch-lists/:listId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'punch_items',
      operation: 'get',
      description: 'Get punch item details',
    },
    {
      method: 'POST',
      path: '/punch-lists/:id/items',
      auth: true,
      handler: 'crud',
      entity: 'punch_items',
      operation: 'create',
      description: 'Add punch item',
    },
    {
      method: 'PUT',
      path: '/punch-lists/:listId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'punch_items',
      operation: 'update',
      description: 'Update punch item',
    },
    {
      method: 'DELETE',
      path: '/punch-lists/:listId/items/:id',
      auth: true,
      handler: 'crud',
      entity: 'punch_items',
      operation: 'delete',
      description: 'Delete punch item',
    },

    // Item Photos
    {
      method: 'GET',
      path: '/punch-lists/:listId/items/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'punch_item_photos',
      operation: 'list',
      description: 'Get item photos',
    },
    {
      method: 'POST',
      path: '/punch-lists/:listId/items/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'punch_item_photos',
      operation: 'create',
      description: 'Add photo',
    },
    {
      method: 'DELETE',
      path: '/punch-lists/:listId/items/:itemId/photos/:id',
      auth: true,
      handler: 'crud',
      entity: 'punch_item_photos',
      operation: 'delete',
      description: 'Delete photo',
    },

    // Item Comments
    {
      method: 'GET',
      path: '/punch-lists/:listId/items/:id/comments',
      auth: true,
      handler: 'crud',
      entity: 'punch_item_comments',
      operation: 'list',
      description: 'Get item comments',
    },
    {
      method: 'POST',
      path: '/punch-lists/:listId/items/:id/comments',
      auth: true,
      handler: 'crud',
      entity: 'punch_item_comments',
      operation: 'create',
      description: 'Add comment',
    },

    // Item Status Actions
    {
      method: 'POST',
      path: '/punch-lists/:listId/items/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'punch_items',
      description: 'Mark item complete',
    },
    {
      method: 'POST',
      path: '/punch-lists/:listId/items/:id/verify',
      auth: true,
      role: 'inspector',
      handler: 'custom',
      entity: 'punch_items',
      description: 'Verify item completion',
    },
    {
      method: 'POST',
      path: '/punch-lists/:listId/items/:id/reject',
      auth: true,
      role: 'inspector',
      handler: 'custom',
      entity: 'punch_items',
      description: 'Reject item',
    },
    {
      method: 'POST',
      path: '/punch-lists/:listId/items/:id/assign',
      auth: true,
      handler: 'custom',
      entity: 'punch_items',
      description: 'Assign item to trade',
    },

    // Bulk Actions
    {
      method: 'POST',
      path: '/punch-lists/:id/items/bulk-update',
      auth: true,
      handler: 'custom',
      entity: 'punch_items',
      description: 'Bulk update items',
    },
    {
      method: 'POST',
      path: '/punch-lists/:id/items/bulk-assign',
      auth: true,
      handler: 'custom',
      entity: 'punch_items',
      description: 'Bulk assign items',
    },

    // Reports
    {
      method: 'GET',
      path: '/punch-lists/:id/stats',
      auth: true,
      handler: 'custom',
      entity: 'punch_lists',
      description: 'Get punch list stats',
    },
    {
      method: 'GET',
      path: '/punch-lists/:id/export',
      auth: true,
      handler: 'custom',
      entity: 'punch_lists',
      description: 'Export punch list',
    },

    // Locations
    {
      method: 'GET',
      path: '/punch-locations',
      auth: true,
      handler: 'crud',
      entity: 'punch_locations',
      operation: 'list',
      description: 'List locations',
    },
    {
      method: 'POST',
      path: '/punch-locations',
      auth: true,
      handler: 'crud',
      entity: 'punch_locations',
      operation: 'create',
      description: 'Add location',
    },
  ],

  config: [
    {
      key: 'requirePhotos',
      label: 'Require Photos',
      type: 'boolean',
      default: true,
      description: 'Require at least one photo per punch item',
    },
    {
      key: 'requireVerification',
      label: 'Require Verification',
      type: 'boolean',
      default: true,
      description: 'Require inspector verification before closing items',
    },
    {
      key: 'defaultPriority',
      label: 'Default Priority',
      type: 'select',
      default: 'medium',
      options: [
        { value: 'low', label: 'Low' },
        { value: 'medium', label: 'Medium' },
        { value: 'high', label: 'High' },
        { value: 'critical', label: 'Critical' },
      ],
      description: 'Default priority for new items',
    },
    {
      key: 'dueDateFromList',
      label: 'Inherit Due Date from List',
      type: 'boolean',
      default: true,
      description: 'Items inherit due date from parent list',
    },
    {
      key: 'notifyOnAssignment',
      label: 'Notify on Assignment',
      type: 'boolean',
      default: true,
      description: 'Send notification when items are assigned',
    },
    {
      key: 'notifyOnCompletion',
      label: 'Notify on Completion',
      type: 'boolean',
      default: true,
      description: 'Send notification when items are marked complete',
    },
    {
      key: 'enableVoiceNotes',
      label: 'Enable Voice Notes',
      type: 'boolean',
      default: true,
      description: 'Allow voice notes on punch items',
    },
  ],
};
