/**
 * Site Safety Feature Definition
 *
 * Comprehensive safety compliance tracking for construction sites.
 * Supports inspections, incidents, training, and OSHA compliance.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const SITE_SAFETY_FEATURE: FeatureDefinition = {
  id: 'site-safety',
  name: 'Site Safety',
  category: 'business',
  description: 'Track safety compliance, inspections, incidents, and training for construction sites',
  icon: 'shield-check',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'safety-management',
    'compliance-management',
    'site-management',
  ],

  activationKeywords: [
    'site safety',
    'safety management',
    'safety compliance',
    'osha compliance',
    'safety inspection',
    'safety incident',
    'accident report',
    'safety training',
    'hazard report',
    'safety checklist',
    'toolbox talk',
    'jsa',
    'job safety analysis',
    'ppe tracking',
    'safety audit',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'projects'],
  conflicts: [],

  pages: [
    {
      id: 'safety-dashboard',
      route: '/safety',
      section: 'frontend',
      title: 'Safety Dashboard',
      authRequired: true,
      templateId: 'safety-dashboard',
      components: [
        'safety-stats',
        'incident-summary',
        'inspection-calendar',
        'training-status',
        'hazard-alerts',
        'compliance-score',
        'recent-inspections',
        'upcoming-training',
      ],
      layout: 'dashboard',
    },
    {
      id: 'inspections-list',
      route: '/safety/inspections',
      section: 'frontend',
      title: 'Safety Inspections',
      authRequired: true,
      templateId: 'inspections-list',
      components: [
        'inspection-grid',
        'inspection-card',
        'inspection-filters',
        'site-filter',
        'status-tabs',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'inspection-detail',
      route: '/safety/inspections/:id',
      section: 'frontend',
      title: 'Inspection Details',
      authRequired: true,
      templateId: 'inspection-detail',
      components: [
        'inspection-header',
        'inspection-checklist',
        'findings-list',
        'corrective-actions',
        'inspection-photos',
        'inspector-signature',
        'inspection-notes',
      ],
      layout: 'dashboard',
    },
    {
      id: 'inspection-create',
      route: '/safety/inspections/new',
      section: 'frontend',
      title: 'New Inspection',
      authRequired: true,
      roles: ['safety-officer', 'project-manager', 'admin'],
      templateId: 'inspection-create',
      components: [
        'inspection-form',
        'site-selector',
        'checklist-selector',
        'checklist-items',
        'finding-form',
        'photo-capture',
        'signature-pad',
      ],
      layout: 'dashboard',
    },
    {
      id: 'incidents-list',
      route: '/safety/incidents',
      section: 'frontend',
      title: 'Incident Reports',
      authRequired: true,
      templateId: 'incidents-list',
      components: [
        'incident-grid',
        'incident-card',
        'incident-filters',
        'severity-filter',
        'status-tabs',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'incident-report',
      route: '/safety/incidents/new',
      section: 'frontend',
      title: 'Report Incident',
      authRequired: true,
      templateId: 'incident-report',
      components: [
        'incident-form',
        'incident-type-selector',
        'injury-details-form',
        'witness-form',
        'root-cause-analysis',
        'photo-uploader',
        'corrective-action-form',
      ],
      layout: 'dashboard',
    },
    {
      id: 'training-list',
      route: '/safety/training',
      section: 'frontend',
      title: 'Safety Training',
      authRequired: true,
      templateId: 'training-list',
      components: [
        'training-grid',
        'training-card',
        'training-filters',
        'certification-tracker',
        'expiration-alerts',
        'training-calendar',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-safety',
      route: '/admin/safety',
      section: 'admin',
      title: 'Safety Administration',
      authRequired: true,
      roles: ['admin', 'safety-officer'],
      templateId: 'admin-safety',
      components: [
        'safety-analytics',
        'inspection-templates',
        'checklist-manager',
        'training-manager',
        'compliance-reports',
        'osha-reports',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'safety-stats',
    'incident-summary',
    'inspection-calendar',
    'training-status',
    'hazard-alerts',
    'compliance-score',
    'recent-inspections',
    'upcoming-training',

    // Inspection components
    'inspection-grid',
    'inspection-card',
    'inspection-filters',
    'site-filter',
    'status-tabs',
    'inspection-header',
    'inspection-checklist',
    'findings-list',
    'corrective-actions',
    'inspection-photos',
    'inspector-signature',
    'inspection-notes',
    'inspection-form',
    'site-selector',
    'checklist-selector',
    'checklist-items',
    'finding-form',
    'photo-capture',
    'signature-pad',

    // Incident components
    'incident-grid',
    'incident-card',
    'incident-filters',
    'severity-filter',
    'incident-form',
    'incident-type-selector',
    'injury-details-form',
    'witness-form',
    'root-cause-analysis',
    'photo-uploader',
    'corrective-action-form',

    // Training components
    'training-grid',
    'training-card',
    'training-filters',
    'certification-tracker',
    'expiration-alerts',
    'training-calendar',

    // Admin components
    'safety-analytics',
    'inspection-templates',
    'checklist-manager',
    'training-manager',
    'compliance-reports',
    'osha-reports',
    'pagination',
  ],

  entities: [
    {
      name: 'safety_inspections',
      displayName: 'Safety Inspections',
      description: 'Site safety inspection records',
      isCore: true,
    },
    {
      name: 'inspection_findings',
      displayName: 'Inspection Findings',
      description: 'Findings from inspections',
      isCore: true,
    },
    {
      name: 'safety_incidents',
      displayName: 'Safety Incidents',
      description: 'Incident and accident reports',
      isCore: true,
    },
    {
      name: 'incident_witnesses',
      displayName: 'Incident Witnesses',
      description: 'Witness statements for incidents',
      isCore: true,
    },
    {
      name: 'safety_training',
      displayName: 'Safety Training',
      description: 'Training records and certifications',
      isCore: true,
    },
    {
      name: 'safety_checklists',
      displayName: 'Safety Checklists',
      description: 'Inspection checklist templates',
      isCore: true,
    },
    {
      name: 'corrective_actions',
      displayName: 'Corrective Actions',
      description: 'Corrective actions for findings',
      isCore: false,
    },
    {
      name: 'toolbox_talks',
      displayName: 'Toolbox Talks',
      description: 'Daily safety meeting records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Inspections CRUD
    {
      method: 'GET',
      path: '/safety/inspections',
      auth: true,
      handler: 'crud',
      entity: 'safety_inspections',
      operation: 'list',
      description: 'List safety inspections',
    },
    {
      method: 'GET',
      path: '/safety/inspections/:id',
      auth: true,
      handler: 'crud',
      entity: 'safety_inspections',
      operation: 'get',
      description: 'Get inspection details',
    },
    {
      method: 'POST',
      path: '/safety/inspections',
      auth: true,
      role: 'safety-officer',
      handler: 'crud',
      entity: 'safety_inspections',
      operation: 'create',
      description: 'Create inspection',
    },
    {
      method: 'PUT',
      path: '/safety/inspections/:id',
      auth: true,
      handler: 'crud',
      entity: 'safety_inspections',
      operation: 'update',
      description: 'Update inspection',
    },
    {
      method: 'DELETE',
      path: '/safety/inspections/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'safety_inspections',
      operation: 'delete',
      description: 'Delete inspection',
    },

    // Inspection Findings
    {
      method: 'GET',
      path: '/safety/inspections/:id/findings',
      auth: true,
      handler: 'crud',
      entity: 'inspection_findings',
      operation: 'list',
      description: 'Get inspection findings',
    },
    {
      method: 'POST',
      path: '/safety/inspections/:id/findings',
      auth: true,
      handler: 'crud',
      entity: 'inspection_findings',
      operation: 'create',
      description: 'Add finding',
    },
    {
      method: 'PUT',
      path: '/safety/inspections/:inspectionId/findings/:id',
      auth: true,
      handler: 'crud',
      entity: 'inspection_findings',
      operation: 'update',
      description: 'Update finding',
    },

    // Incidents CRUD
    {
      method: 'GET',
      path: '/safety/incidents',
      auth: true,
      handler: 'crud',
      entity: 'safety_incidents',
      operation: 'list',
      description: 'List incidents',
    },
    {
      method: 'GET',
      path: '/safety/incidents/:id',
      auth: true,
      handler: 'crud',
      entity: 'safety_incidents',
      operation: 'get',
      description: 'Get incident details',
    },
    {
      method: 'POST',
      path: '/safety/incidents',
      auth: true,
      handler: 'crud',
      entity: 'safety_incidents',
      operation: 'create',
      description: 'Report incident',
    },
    {
      method: 'PUT',
      path: '/safety/incidents/:id',
      auth: true,
      handler: 'crud',
      entity: 'safety_incidents',
      operation: 'update',
      description: 'Update incident',
    },

    // Training CRUD
    {
      method: 'GET',
      path: '/safety/training',
      auth: true,
      handler: 'crud',
      entity: 'safety_training',
      operation: 'list',
      description: 'List training records',
    },
    {
      method: 'GET',
      path: '/safety/training/:id',
      auth: true,
      handler: 'crud',
      entity: 'safety_training',
      operation: 'get',
      description: 'Get training details',
    },
    {
      method: 'POST',
      path: '/safety/training',
      auth: true,
      handler: 'crud',
      entity: 'safety_training',
      operation: 'create',
      description: 'Add training record',
    },
    {
      method: 'PUT',
      path: '/safety/training/:id',
      auth: true,
      handler: 'crud',
      entity: 'safety_training',
      operation: 'update',
      description: 'Update training record',
    },

    // Checklists
    {
      method: 'GET',
      path: '/safety/checklists',
      auth: true,
      handler: 'crud',
      entity: 'safety_checklists',
      operation: 'list',
      description: 'List checklists',
    },
    {
      method: 'POST',
      path: '/safety/checklists',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'safety_checklists',
      operation: 'create',
      description: 'Create checklist',
    },

    // Corrective Actions
    {
      method: 'GET',
      path: '/safety/corrective-actions',
      auth: true,
      handler: 'crud',
      entity: 'corrective_actions',
      operation: 'list',
      description: 'List corrective actions',
    },
    {
      method: 'POST',
      path: '/safety/corrective-actions',
      auth: true,
      handler: 'crud',
      entity: 'corrective_actions',
      operation: 'create',
      description: 'Create corrective action',
    },
    {
      method: 'PUT',
      path: '/safety/corrective-actions/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'corrective_actions',
      description: 'Mark action complete',
    },

    // Dashboard and Reports
    {
      method: 'GET',
      path: '/safety/dashboard',
      auth: true,
      handler: 'custom',
      entity: 'safety_inspections',
      description: 'Get safety dashboard data',
    },
    {
      method: 'GET',
      path: '/safety/compliance-score',
      auth: true,
      handler: 'custom',
      entity: 'safety_inspections',
      description: 'Calculate compliance score',
    },
    {
      method: 'GET',
      path: '/safety/osha-report',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'safety_incidents',
      description: 'Generate OSHA 300 report',
    },
  ],

  config: [
    {
      key: 'requirePhotosOnInspection',
      label: 'Require Photos on Inspections',
      type: 'boolean',
      default: true,
      description: 'Require photo documentation for inspections',
    },
    {
      key: 'requireSignatureOnInspection',
      label: 'Require Signature on Inspections',
      type: 'boolean',
      default: true,
      description: 'Require inspector signature',
    },
    {
      key: 'incidentNotificationEmails',
      label: 'Incident Notification Emails',
      type: 'string',
      default: '',
      description: 'Comma-separated emails for incident notifications',
    },
    {
      key: 'trainingExpirationWarningDays',
      label: 'Training Expiration Warning (days)',
      type: 'number',
      default: 30,
      description: 'Days before training expiration to warn',
    },
    {
      key: 'correctiveActionDueDays',
      label: 'Default Corrective Action Due (days)',
      type: 'number',
      default: 7,
      description: 'Default days to resolve corrective actions',
    },
    {
      key: 'enableToolboxTalks',
      label: 'Enable Toolbox Talks',
      type: 'boolean',
      default: true,
      description: 'Track daily toolbox talk meetings',
    },
    {
      key: 'oshaReporting',
      label: 'Enable OSHA Reporting',
      type: 'boolean',
      default: true,
      description: 'Generate OSHA-compliant reports',
    },
  ],
};
