/**
 * Subcontractor Management Feature Definition
 *
 * Complete subcontractor management for construction projects.
 * Supports subcontractor onboarding, performance tracking, and compliance.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const SUBCONTRACTOR_MGMT_FEATURE: FeatureDefinition = {
  id: 'subcontractor-mgmt',
  name: 'Subcontractor Management',
  category: 'business',
  description: 'Manage subcontractors with onboarding, compliance tracking, and performance metrics',
  icon: 'users',

  includedInAppTypes: [
    'construction',
    'construction-management',
    'general-contractor',
    'subcontractor-management',
    'project-management',
    'contractor-portal',
  ],

  activationKeywords: [
    'subcontractor',
    'subcontractors',
    'subcontractor management',
    'sub management',
    'contractor management',
    'trade contractor',
    'specialty contractor',
    'vendor management',
    'contractor compliance',
    'contractor onboarding',
    'contractor performance',
    'contractor directory',
    'trade partners',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'documents'],
  conflicts: [],

  pages: [
    {
      id: 'subcontractors-list',
      route: '/subcontractors',
      section: 'frontend',
      title: 'Subcontractors',
      authRequired: true,
      templateId: 'subcontractors-list',
      components: [
        'subcontractor-grid',
        'subcontractor-card',
        'subcontractor-filters',
        'trade-filter',
        'status-tabs',
        'search-bar',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'subcontractor-detail',
      route: '/subcontractors/:id',
      section: 'frontend',
      title: 'Subcontractor Details',
      authRequired: true,
      templateId: 'subcontractor-detail',
      components: [
        'subcontractor-header',
        'subcontractor-info',
        'contact-details',
        'trade-specialties',
        'compliance-status',
        'insurance-documents',
        'license-documents',
        'performance-metrics',
        'project-history',
        'notes-section',
      ],
      layout: 'dashboard',
    },
    {
      id: 'subcontractor-create',
      route: '/subcontractors/new',
      section: 'frontend',
      title: 'Add Subcontractor',
      authRequired: true,
      roles: ['project-manager', 'admin'],
      templateId: 'subcontractor-create',
      components: [
        'subcontractor-form',
        'company-info-form',
        'contact-form',
        'trade-selector',
        'document-uploader',
        'insurance-form',
        'license-form',
      ],
      layout: 'dashboard',
    },
    {
      id: 'subcontractor-edit',
      route: '/subcontractors/:id/edit',
      section: 'frontend',
      title: 'Edit Subcontractor',
      authRequired: true,
      roles: ['project-manager', 'admin'],
      templateId: 'subcontractor-edit',
      components: [
        'subcontractor-form',
        'company-info-form',
        'contact-form',
        'trade-selector',
        'document-manager',
        'insurance-manager',
        'license-manager',
        'status-toggle',
      ],
      layout: 'dashboard',
    },
    {
      id: 'subcontractor-compliance',
      route: '/subcontractors/:id/compliance',
      section: 'frontend',
      title: 'Compliance Dashboard',
      authRequired: true,
      templateId: 'subcontractor-compliance',
      components: [
        'compliance-overview',
        'insurance-tracker',
        'license-tracker',
        'certification-tracker',
        'expiration-alerts',
        'compliance-history',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-subcontractors',
      route: '/admin/subcontractors',
      section: 'admin',
      title: 'Manage Subcontractors',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-subcontractors',
      components: [
        'subcontractors-table',
        'subcontractor-filters',
        'bulk-actions',
        'compliance-dashboard',
        'performance-analytics',
        'export-subcontractors',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Grid/List components
    'subcontractor-grid',
    'subcontractor-card',
    'subcontractor-list-item',
    'subcontractor-filters',
    'trade-filter',
    'status-tabs',
    'search-bar',
    'pagination',

    // Detail components
    'subcontractor-header',
    'subcontractor-info',
    'contact-details',
    'trade-specialties',
    'compliance-status',
    'insurance-documents',
    'license-documents',
    'performance-metrics',
    'project-history',
    'notes-section',

    // Form components
    'subcontractor-form',
    'company-info-form',
    'contact-form',
    'trade-selector',
    'document-uploader',
    'document-manager',
    'insurance-form',
    'insurance-manager',
    'license-form',
    'license-manager',
    'status-toggle',

    // Compliance components
    'compliance-overview',
    'insurance-tracker',
    'license-tracker',
    'certification-tracker',
    'expiration-alerts',
    'compliance-history',

    // Management components
    'subcontractors-table',
    'bulk-actions',
    'compliance-dashboard',
    'performance-analytics',
    'export-subcontractors',
  ],

  entities: [
    {
      name: 'subcontractors',
      displayName: 'Subcontractors',
      description: 'Subcontractor company records',
      isCore: true,
    },
    {
      name: 'subcontractor_contacts',
      displayName: 'Subcontractor Contacts',
      description: 'Contact persons for subcontractors',
      isCore: true,
    },
    {
      name: 'subcontractor_trades',
      displayName: 'Subcontractor Trades',
      description: 'Trade specialties for subcontractors',
      isCore: true,
    },
    {
      name: 'subcontractor_documents',
      displayName: 'Subcontractor Documents',
      description: 'Compliance and other documents',
      isCore: true,
    },
    {
      name: 'subcontractor_insurance',
      displayName: 'Insurance Records',
      description: 'Insurance policies and certificates',
      isCore: true,
    },
    {
      name: 'subcontractor_licenses',
      displayName: 'License Records',
      description: 'Trade licenses and certifications',
      isCore: true,
    },
    {
      name: 'subcontractor_ratings',
      displayName: 'Performance Ratings',
      description: 'Performance ratings and reviews',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Subcontractor CRUD
    {
      method: 'GET',
      path: '/subcontractors',
      auth: true,
      handler: 'crud',
      entity: 'subcontractors',
      operation: 'list',
      description: 'List all subcontractors',
    },
    {
      method: 'GET',
      path: '/subcontractors/:id',
      auth: true,
      handler: 'crud',
      entity: 'subcontractors',
      operation: 'get',
      description: 'Get subcontractor details',
    },
    {
      method: 'POST',
      path: '/subcontractors',
      auth: true,
      role: 'project-manager',
      handler: 'crud',
      entity: 'subcontractors',
      operation: 'create',
      description: 'Add new subcontractor',
    },
    {
      method: 'PUT',
      path: '/subcontractors/:id',
      auth: true,
      handler: 'crud',
      entity: 'subcontractors',
      operation: 'update',
      description: 'Update subcontractor',
    },
    {
      method: 'DELETE',
      path: '/subcontractors/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'subcontractors',
      operation: 'delete',
      description: 'Delete subcontractor',
    },

    // Contacts
    {
      method: 'GET',
      path: '/subcontractors/:id/contacts',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_contacts',
      operation: 'list',
      description: 'Get subcontractor contacts',
    },
    {
      method: 'POST',
      path: '/subcontractors/:id/contacts',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_contacts',
      operation: 'create',
      description: 'Add contact',
    },
    {
      method: 'PUT',
      path: '/subcontractors/:subId/contacts/:id',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_contacts',
      operation: 'update',
      description: 'Update contact',
    },
    {
      method: 'DELETE',
      path: '/subcontractors/:subId/contacts/:id',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_contacts',
      operation: 'delete',
      description: 'Delete contact',
    },

    // Insurance
    {
      method: 'GET',
      path: '/subcontractors/:id/insurance',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_insurance',
      operation: 'list',
      description: 'Get insurance records',
    },
    {
      method: 'POST',
      path: '/subcontractors/:id/insurance',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_insurance',
      operation: 'create',
      description: 'Add insurance record',
    },
    {
      method: 'PUT',
      path: '/subcontractors/:subId/insurance/:id',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_insurance',
      operation: 'update',
      description: 'Update insurance record',
    },

    // Licenses
    {
      method: 'GET',
      path: '/subcontractors/:id/licenses',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_licenses',
      operation: 'list',
      description: 'Get license records',
    },
    {
      method: 'POST',
      path: '/subcontractors/:id/licenses',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_licenses',
      operation: 'create',
      description: 'Add license record',
    },
    {
      method: 'PUT',
      path: '/subcontractors/:subId/licenses/:id',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_licenses',
      operation: 'update',
      description: 'Update license record',
    },

    // Compliance
    {
      method: 'GET',
      path: '/subcontractors/:id/compliance',
      auth: true,
      handler: 'custom',
      entity: 'subcontractors',
      description: 'Get compliance status',
    },
    {
      method: 'GET',
      path: '/subcontractors/expiring-documents',
      auth: true,
      handler: 'custom',
      entity: 'subcontractor_documents',
      description: 'Get expiring documents',
    },

    // Performance
    {
      method: 'GET',
      path: '/subcontractors/:id/ratings',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_ratings',
      operation: 'list',
      description: 'Get performance ratings',
    },
    {
      method: 'POST',
      path: '/subcontractors/:id/ratings',
      auth: true,
      handler: 'crud',
      entity: 'subcontractor_ratings',
      operation: 'create',
      description: 'Add performance rating',
    },

    // Search and Filters
    {
      method: 'GET',
      path: '/subcontractors/by-trade/:tradeId',
      auth: true,
      handler: 'custom',
      entity: 'subcontractors',
      description: 'Get subcontractors by trade',
    },
    {
      method: 'GET',
      path: '/subcontractors/search',
      auth: true,
      handler: 'custom',
      entity: 'subcontractors',
      description: 'Search subcontractors',
    },
  ],

  config: [
    {
      key: 'requireInsurance',
      label: 'Require Insurance Documentation',
      type: 'boolean',
      default: true,
      description: 'Require valid insurance before activation',
    },
    {
      key: 'requireLicense',
      label: 'Require Trade License',
      type: 'boolean',
      default: true,
      description: 'Require valid trade license',
    },
    {
      key: 'insuranceExpirationWarningDays',
      label: 'Insurance Expiration Warning (days)',
      type: 'number',
      default: 30,
      description: 'Days before expiration to send warning',
    },
    {
      key: 'licenseExpirationWarningDays',
      label: 'License Expiration Warning (days)',
      type: 'number',
      default: 60,
      description: 'Days before expiration to send warning',
    },
    {
      key: 'minimumInsuranceAmount',
      label: 'Minimum Insurance Amount',
      type: 'number',
      default: 1000000,
      description: 'Minimum required insurance coverage amount',
    },
    {
      key: 'enablePerformanceRatings',
      label: 'Enable Performance Ratings',
      type: 'boolean',
      default: true,
      description: 'Allow rating subcontractor performance',
    },
    {
      key: 'autoDeactivateExpired',
      label: 'Auto-Deactivate on Expired Docs',
      type: 'boolean',
      default: false,
      description: 'Automatically deactivate subcontractors with expired documents',
    },
  ],
};
