/**
 * Billing & Timekeeping Feature Definition
 *
 * Legal billing and time tracking for law firms.
 * Supports time entries, expense tracking, invoice generation, and trust accounting.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const BILLING_TIMEKEEPING_FEATURE: FeatureDefinition = {
  id: 'billing-timekeeping',
  name: 'Billing & Timekeeping',
  category: 'business',
  description: 'Track billable hours, expenses, and generate invoices with trust account management',
  icon: 'clock',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'paralegal-services',
    'corporate-legal',
    'consulting-firm',
    'professional-services',
  ],

  activationKeywords: [
    'legal billing',
    'time tracking',
    'timekeeping',
    'billable hours',
    'time entry',
    'legal invoicing',
    'trust accounting',
    'iolta',
    'retainer',
    'hourly billing',
    'expense tracking',
    'billing rates',
    'fee arrangement',
    'contingency fee',
    'flat fee billing',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'case-management', 'clients'],
  conflicts: [],

  pages: [
    {
      id: 'time-entries',
      route: '/time',
      section: 'frontend',
      title: 'Time Entries',
      authRequired: true,
      templateId: 'time-entries',
      components: [
        'time-entries-table',
        'time-entry-card',
        'date-range-filter',
        'case-filter',
        'status-filter',
        'timer-widget',
        'quick-entry-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'time-entry-create',
      route: '/time/new',
      section: 'frontend',
      title: 'New Time Entry',
      authRequired: true,
      templateId: 'time-entry-create',
      components: [
        'time-entry-form',
        'case-selector',
        'task-selector',
        'duration-input',
        'rate-display',
        'description-editor',
        'billable-toggle',
      ],
      layout: 'dashboard',
    },
    {
      id: 'timer',
      route: '/time/timer',
      section: 'frontend',
      title: 'Timer',
      authRequired: true,
      templateId: 'timer',
      components: [
        'active-timer',
        'timer-controls',
        'recent-timers',
        'case-quick-select',
      ],
      layout: 'dashboard',
    },
    {
      id: 'expenses',
      route: '/expenses',
      section: 'frontend',
      title: 'Expenses',
      authRequired: true,
      templateId: 'expenses',
      components: [
        'expenses-table',
        'expense-card',
        'expense-filters',
        'receipt-upload',
        'expense-categories',
      ],
      layout: 'dashboard',
    },
    {
      id: 'expense-create',
      route: '/expenses/new',
      section: 'frontend',
      title: 'New Expense',
      authRequired: true,
      templateId: 'expense-create',
      components: [
        'expense-form',
        'case-selector',
        'category-selector',
        'amount-input',
        'receipt-upload',
        'reimbursable-toggle',
      ],
      layout: 'dashboard',
    },
    {
      id: 'invoices-list',
      route: '/invoices',
      section: 'frontend',
      title: 'Invoices',
      authRequired: true,
      roles: ['attorney', 'billing', 'admin'],
      templateId: 'invoices-list',
      components: [
        'invoices-table',
        'invoice-card',
        'invoice-filters',
        'payment-status-filter',
        'create-invoice-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'invoice-detail',
      route: '/invoices/:id',
      section: 'frontend',
      title: 'Invoice Details',
      authRequired: true,
      templateId: 'invoice-detail',
      components: [
        'invoice-header',
        'invoice-summary',
        'time-entries-list',
        'expenses-list',
        'payment-history',
        'invoice-actions',
        'payment-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'invoice-create',
      route: '/invoices/new',
      section: 'frontend',
      title: 'Create Invoice',
      authRequired: true,
      roles: ['attorney', 'billing', 'admin'],
      templateId: 'invoice-create',
      components: [
        'invoice-builder',
        'client-selector',
        'case-selector',
        'unbilled-entries',
        'unbilled-expenses',
        'discount-input',
        'invoice-preview',
      ],
      layout: 'dashboard',
    },
    {
      id: 'trust-accounts',
      route: '/trust',
      section: 'frontend',
      title: 'Trust Accounts',
      authRequired: true,
      roles: ['attorney', 'billing', 'admin'],
      templateId: 'trust-accounts',
      components: [
        'trust-accounts-list',
        'account-balance',
        'trust-ledger',
        'transfer-form',
        'reconciliation-panel',
      ],
      layout: 'dashboard',
    },
    {
      id: 'billing-rates',
      route: '/admin/billing-rates',
      section: 'admin',
      title: 'Billing Rates',
      authRequired: true,
      roles: ['admin'],
      templateId: 'billing-rates',
      components: [
        'rates-table',
        'rate-form',
        'attorney-rates',
        'matter-rates',
        'rate-history',
      ],
      layout: 'admin',
    },
    {
      id: 'billing-reports',
      route: '/admin/billing-reports',
      section: 'admin',
      title: 'Billing Reports',
      authRequired: true,
      roles: ['admin', 'billing'],
      templateId: 'billing-reports',
      components: [
        'revenue-report',
        'collection-report',
        'ar-aging-report',
        'productivity-report',
        'report-filters',
        'export-options',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Time entry components
    'time-entries-table',
    'time-entry-card',
    'date-range-filter',
    'case-filter',
    'status-filter',
    'timer-widget',
    'quick-entry-button',
    'time-entry-form',
    'task-selector',
    'duration-input',
    'rate-display',
    'description-editor',
    'billable-toggle',

    // Timer components
    'active-timer',
    'timer-controls',
    'recent-timers',
    'case-quick-select',

    // Expense components
    'expenses-table',
    'expense-card',
    'expense-filters',
    'receipt-upload',
    'expense-categories',
    'expense-form',
    'category-selector',
    'amount-input',
    'reimbursable-toggle',

    // Invoice components
    'invoices-table',
    'invoice-card',
    'invoice-filters',
    'payment-status-filter',
    'create-invoice-button',
    'invoice-header',
    'invoice-summary',
    'time-entries-list',
    'expenses-list',
    'payment-history',
    'invoice-actions',
    'payment-button',
    'invoice-builder',
    'unbilled-entries',
    'unbilled-expenses',
    'discount-input',
    'invoice-preview',

    // Trust account components
    'trust-accounts-list',
    'account-balance',
    'trust-ledger',
    'transfer-form',
    'reconciliation-panel',

    // Admin components
    'rates-table',
    'rate-form',
    'attorney-rates',
    'matter-rates',
    'rate-history',
    'revenue-report',
    'collection-report',
    'ar-aging-report',
    'productivity-report',
    'report-filters',
    'export-options',
  ],

  entities: [
    {
      name: 'time_entries',
      displayName: 'Time Entries',
      description: 'Billable time records',
      isCore: true,
    },
    {
      name: 'expenses',
      displayName: 'Expenses',
      description: 'Case-related expenses',
      isCore: true,
    },
    {
      name: 'invoices',
      displayName: 'Invoices',
      description: 'Client invoices',
      isCore: true,
    },
    {
      name: 'payments',
      displayName: 'Payments',
      description: 'Payment records',
      isCore: true,
    },
    {
      name: 'trust_accounts',
      displayName: 'Trust Accounts',
      description: 'Client trust/IOLTA accounts',
      isCore: false,
    },
    {
      name: 'billing_rates',
      displayName: 'Billing Rates',
      description: 'Attorney and matter billing rates',
      isCore: false,
    },
    {
      name: 'trust_transactions',
      displayName: 'Trust Transactions',
      description: 'Trust account transactions',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Time Entries CRUD
    {
      method: 'GET',
      path: '/time-entries',
      auth: true,
      handler: 'crud',
      entity: 'time_entries',
      operation: 'list',
      description: 'List time entries',
    },
    {
      method: 'GET',
      path: '/time-entries/:id',
      auth: true,
      handler: 'crud',
      entity: 'time_entries',
      operation: 'get',
      description: 'Get time entry details',
    },
    {
      method: 'POST',
      path: '/time-entries',
      auth: true,
      handler: 'crud',
      entity: 'time_entries',
      operation: 'create',
      description: 'Create time entry',
    },
    {
      method: 'PUT',
      path: '/time-entries/:id',
      auth: true,
      handler: 'crud',
      entity: 'time_entries',
      operation: 'update',
      description: 'Update time entry',
    },
    {
      method: 'DELETE',
      path: '/time-entries/:id',
      auth: true,
      handler: 'crud',
      entity: 'time_entries',
      operation: 'delete',
      description: 'Delete time entry',
    },

    // Timer
    {
      method: 'POST',
      path: '/time-entries/timer/start',
      auth: true,
      handler: 'custom',
      entity: 'time_entries',
      description: 'Start timer',
    },
    {
      method: 'POST',
      path: '/time-entries/timer/stop',
      auth: true,
      handler: 'custom',
      entity: 'time_entries',
      description: 'Stop timer and create entry',
    },
    {
      method: 'GET',
      path: '/time-entries/timer/active',
      auth: true,
      handler: 'custom',
      entity: 'time_entries',
      description: 'Get active timer',
    },

    // Expenses CRUD
    {
      method: 'GET',
      path: '/expenses',
      auth: true,
      handler: 'crud',
      entity: 'expenses',
      operation: 'list',
      description: 'List expenses',
    },
    {
      method: 'GET',
      path: '/expenses/:id',
      auth: true,
      handler: 'crud',
      entity: 'expenses',
      operation: 'get',
      description: 'Get expense details',
    },
    {
      method: 'POST',
      path: '/expenses',
      auth: true,
      handler: 'crud',
      entity: 'expenses',
      operation: 'create',
      description: 'Create expense',
    },
    {
      method: 'PUT',
      path: '/expenses/:id',
      auth: true,
      handler: 'crud',
      entity: 'expenses',
      operation: 'update',
      description: 'Update expense',
    },
    {
      method: 'DELETE',
      path: '/expenses/:id',
      auth: true,
      handler: 'crud',
      entity: 'expenses',
      operation: 'delete',
      description: 'Delete expense',
    },

    // Invoices CRUD
    {
      method: 'GET',
      path: '/invoices',
      auth: true,
      handler: 'crud',
      entity: 'invoices',
      operation: 'list',
      description: 'List invoices',
    },
    {
      method: 'GET',
      path: '/invoices/:id',
      auth: true,
      handler: 'crud',
      entity: 'invoices',
      operation: 'get',
      description: 'Get invoice details',
    },
    {
      method: 'POST',
      path: '/invoices',
      auth: true,
      role: 'billing',
      handler: 'crud',
      entity: 'invoices',
      operation: 'create',
      description: 'Create invoice',
    },
    {
      method: 'PUT',
      path: '/invoices/:id',
      auth: true,
      handler: 'crud',
      entity: 'invoices',
      operation: 'update',
      description: 'Update invoice',
    },
    {
      method: 'DELETE',
      path: '/invoices/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'invoices',
      operation: 'delete',
      description: 'Delete invoice',
    },

    // Invoice Actions
    {
      method: 'POST',
      path: '/invoices/:id/send',
      auth: true,
      handler: 'custom',
      entity: 'invoices',
      description: 'Send invoice to client',
    },
    {
      method: 'POST',
      path: '/invoices/:id/finalize',
      auth: true,
      handler: 'custom',
      entity: 'invoices',
      description: 'Finalize invoice',
    },
    {
      method: 'GET',
      path: '/invoices/:id/pdf',
      auth: true,
      handler: 'custom',
      entity: 'invoices',
      description: 'Download invoice PDF',
    },

    // Payments
    {
      method: 'GET',
      path: '/payments',
      auth: true,
      handler: 'crud',
      entity: 'payments',
      operation: 'list',
      description: 'List payments',
    },
    {
      method: 'POST',
      path: '/payments',
      auth: true,
      handler: 'crud',
      entity: 'payments',
      operation: 'create',
      description: 'Record payment',
    },
    {
      method: 'POST',
      path: '/invoices/:id/pay',
      auth: true,
      handler: 'custom',
      entity: 'payments',
      description: 'Apply payment to invoice',
    },

    // Trust Accounts
    {
      method: 'GET',
      path: '/trust-accounts',
      auth: true,
      handler: 'crud',
      entity: 'trust_accounts',
      operation: 'list',
      description: 'List trust accounts',
    },
    {
      method: 'GET',
      path: '/trust-accounts/:id',
      auth: true,
      handler: 'crud',
      entity: 'trust_accounts',
      operation: 'get',
      description: 'Get trust account details',
    },
    {
      method: 'POST',
      path: '/trust-accounts',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'trust_accounts',
      operation: 'create',
      description: 'Create trust account',
    },
    {
      method: 'POST',
      path: '/trust-accounts/:id/deposit',
      auth: true,
      handler: 'custom',
      entity: 'trust_transactions',
      description: 'Deposit to trust account',
    },
    {
      method: 'POST',
      path: '/trust-accounts/:id/withdraw',
      auth: true,
      handler: 'custom',
      entity: 'trust_transactions',
      description: 'Withdraw from trust account',
    },
    {
      method: 'GET',
      path: '/trust-accounts/:id/ledger',
      auth: true,
      handler: 'crud',
      entity: 'trust_transactions',
      operation: 'list',
      description: 'Get trust account ledger',
    },

    // Billing Rates
    {
      method: 'GET',
      path: '/billing-rates',
      auth: true,
      handler: 'crud',
      entity: 'billing_rates',
      operation: 'list',
      description: 'List billing rates',
    },
    {
      method: 'POST',
      path: '/billing-rates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'billing_rates',
      operation: 'create',
      description: 'Create billing rate',
    },
    {
      method: 'PUT',
      path: '/billing-rates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'billing_rates',
      operation: 'update',
      description: 'Update billing rate',
    },

    // Reports
    {
      method: 'GET',
      path: '/billing/reports/revenue',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'invoices',
      description: 'Get revenue report',
    },
    {
      method: 'GET',
      path: '/billing/reports/ar-aging',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'invoices',
      description: 'Get AR aging report',
    },
    {
      method: 'GET',
      path: '/billing/reports/productivity',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'time_entries',
      description: 'Get productivity report',
    },

    // Unbilled Items
    {
      method: 'GET',
      path: '/billing/unbilled/time',
      auth: true,
      handler: 'custom',
      entity: 'time_entries',
      description: 'Get unbilled time entries',
    },
    {
      method: 'GET',
      path: '/billing/unbilled/expenses',
      auth: true,
      handler: 'custom',
      entity: 'expenses',
      description: 'Get unbilled expenses',
    },
  ],

  config: [
    {
      key: 'defaultBillingRate',
      label: 'Default Hourly Rate',
      type: 'number',
      default: 250,
      description: 'Default billing rate per hour',
    },
    {
      key: 'billingIncrement',
      label: 'Billing Increment (minutes)',
      type: 'select',
      default: '6',
      options: [
        { value: '1', label: '1 minute' },
        { value: '6', label: '6 minutes (1/10 hour)' },
        { value: '10', label: '10 minutes' },
        { value: '15', label: '15 minutes (1/4 hour)' },
      ],
      description: 'Minimum billing increment',
    },
    {
      key: 'enableTrustAccounting',
      label: 'Enable Trust Accounting',
      type: 'boolean',
      default: true,
      description: 'Enable IOLTA/trust account management',
    },
    {
      key: 'autoRoundTime',
      label: 'Auto-round Time Entries',
      type: 'boolean',
      default: true,
      description: 'Automatically round time to billing increment',
    },
    {
      key: 'requireDescriptions',
      label: 'Require Time Entry Descriptions',
      type: 'boolean',
      default: true,
      description: 'Require descriptions for all time entries',
    },
    {
      key: 'invoiceNumberPrefix',
      label: 'Invoice Number Prefix',
      type: 'string',
      default: 'INV',
      description: 'Prefix for auto-generated invoice numbers',
    },
    {
      key: 'paymentTermsDays',
      label: 'Payment Terms (days)',
      type: 'number',
      default: 30,
      description: 'Default payment terms in days',
    },
    {
      key: 'enableOnlinePayments',
      label: 'Enable Online Payments',
      type: 'boolean',
      default: true,
      description: 'Allow clients to pay invoices online',
    },
  ],
};
