/**
 * Case Management Feature Definition
 *
 * Complete legal case tracking and management for law firms.
 * Supports case lifecycle, status tracking, and matter organization.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CASE_MANAGEMENT_FEATURE: FeatureDefinition = {
  id: 'case-management',
  name: 'Case Management',
  category: 'business',
  description: 'Track and manage legal cases with status updates, deadlines, and matter organization',
  icon: 'briefcase',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'paralegal-services',
    'corporate-legal',
    'litigation-support',
    'immigration-law',
    'family-law',
    'criminal-defense',
  ],

  activationKeywords: [
    'case management',
    'legal case',
    'matter management',
    'case tracking',
    'legal matter',
    'case file',
    'lawsuit tracking',
    'litigation management',
    'case status',
    'legal case tracking',
    'court case',
    'case docket',
    'matter tracking',
    'case workflow',
    'case lifecycle',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'clients'],
  conflicts: [],

  pages: [
    {
      id: 'cases-list',
      route: '/cases',
      section: 'frontend',
      title: 'Cases',
      authRequired: true,
      templateId: 'cases-list',
      components: [
        'cases-table',
        'case-card',
        'case-filters',
        'case-search',
        'status-filter',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'case-detail',
      route: '/cases/:id',
      section: 'frontend',
      title: 'Case Details',
      authRequired: true,
      templateId: 'case-detail',
      components: [
        'case-header',
        'case-summary',
        'case-timeline',
        'case-parties',
        'case-documents',
        'case-deadlines',
        'case-notes',
        'case-billing-summary',
        'related-cases',
      ],
      layout: 'dashboard',
    },
    {
      id: 'case-create',
      route: '/cases/new',
      section: 'frontend',
      title: 'New Case',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin'],
      templateId: 'case-create',
      components: [
        'case-form',
        'client-selector',
        'case-type-selector',
        'practice-area-selector',
        'attorney-assignment',
        'jurisdiction-selector',
        'deadline-manager',
      ],
      layout: 'dashboard',
    },
    {
      id: 'case-edit',
      route: '/cases/:id/edit',
      section: 'frontend',
      title: 'Edit Case',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin'],
      templateId: 'case-edit',
      components: [
        'case-form',
        'client-selector',
        'case-type-selector',
        'practice-area-selector',
        'attorney-assignment',
        'jurisdiction-selector',
        'deadline-manager',
        'case-status-toggle',
      ],
      layout: 'dashboard',
    },
    {
      id: 'my-cases',
      route: '/my-cases',
      section: 'frontend',
      title: 'My Cases',
      authRequired: true,
      templateId: 'my-cases',
      components: [
        'cases-table',
        'case-stats',
        'upcoming-deadlines',
        'case-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-cases',
      route: '/admin/cases',
      section: 'admin',
      title: 'Manage Cases',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-cases',
      components: [
        'cases-table',
        'case-filters',
        'bulk-actions',
        'case-assignment',
        'case-analytics',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'cases-table',
    'case-card',
    'case-filters',
    'case-search',
    'status-filter',
    'sort-dropdown',
    'pagination',

    // Detail components
    'case-header',
    'case-summary',
    'case-timeline',
    'case-parties',
    'case-documents',
    'case-deadlines',
    'case-notes',
    'case-billing-summary',
    'related-cases',

    // Form components
    'case-form',
    'client-selector',
    'case-type-selector',
    'practice-area-selector',
    'attorney-assignment',
    'jurisdiction-selector',
    'deadline-manager',
    'case-status-toggle',

    // Management components
    'case-stats',
    'upcoming-deadlines',
    'case-actions',
    'bulk-actions',
    'case-assignment',
    'case-analytics',
  ],

  entities: [
    {
      name: 'cases',
      displayName: 'Cases',
      description: 'Legal case records',
      isCore: true,
    },
    {
      name: 'case_parties',
      displayName: 'Case Parties',
      description: 'Parties involved in cases (plaintiffs, defendants, etc.)',
      isCore: true,
    },
    {
      name: 'case_deadlines',
      displayName: 'Case Deadlines',
      description: 'Important deadlines and due dates for cases',
      isCore: true,
    },
    {
      name: 'case_status_history',
      displayName: 'Case Status History',
      description: 'Historical status changes for cases',
      isCore: false,
    },
    {
      name: 'practice_areas',
      displayName: 'Practice Areas',
      description: 'Legal practice area categories',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Case CRUD
    {
      method: 'GET',
      path: '/cases',
      auth: true,
      handler: 'crud',
      entity: 'cases',
      operation: 'list',
      description: 'List all cases with filters',
    },
    {
      method: 'GET',
      path: '/cases/:id',
      auth: true,
      handler: 'crud',
      entity: 'cases',
      operation: 'get',
      description: 'Get case details',
    },
    {
      method: 'POST',
      path: '/cases',
      auth: true,
      role: 'attorney',
      handler: 'crud',
      entity: 'cases',
      operation: 'create',
      description: 'Create new case',
    },
    {
      method: 'PUT',
      path: '/cases/:id',
      auth: true,
      handler: 'crud',
      entity: 'cases',
      operation: 'update',
      description: 'Update case',
    },
    {
      method: 'DELETE',
      path: '/cases/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'cases',
      operation: 'delete',
      description: 'Delete case',
    },

    // Case Parties
    {
      method: 'GET',
      path: '/cases/:id/parties',
      auth: true,
      handler: 'crud',
      entity: 'case_parties',
      operation: 'list',
      description: 'Get case parties',
    },
    {
      method: 'POST',
      path: '/cases/:id/parties',
      auth: true,
      handler: 'crud',
      entity: 'case_parties',
      operation: 'create',
      description: 'Add party to case',
    },
    {
      method: 'PUT',
      path: '/cases/:caseId/parties/:id',
      auth: true,
      handler: 'crud',
      entity: 'case_parties',
      operation: 'update',
      description: 'Update case party',
    },
    {
      method: 'DELETE',
      path: '/cases/:caseId/parties/:id',
      auth: true,
      handler: 'crud',
      entity: 'case_parties',
      operation: 'delete',
      description: 'Remove party from case',
    },

    // Case Deadlines
    {
      method: 'GET',
      path: '/cases/:id/deadlines',
      auth: true,
      handler: 'crud',
      entity: 'case_deadlines',
      operation: 'list',
      description: 'Get case deadlines',
    },
    {
      method: 'POST',
      path: '/cases/:id/deadlines',
      auth: true,
      handler: 'crud',
      entity: 'case_deadlines',
      operation: 'create',
      description: 'Add deadline to case',
    },
    {
      method: 'PUT',
      path: '/cases/:caseId/deadlines/:id',
      auth: true,
      handler: 'crud',
      entity: 'case_deadlines',
      operation: 'update',
      description: 'Update case deadline',
    },
    {
      method: 'DELETE',
      path: '/cases/:caseId/deadlines/:id',
      auth: true,
      handler: 'crud',
      entity: 'case_deadlines',
      operation: 'delete',
      description: 'Remove deadline from case',
    },

    // Status management
    {
      method: 'PUT',
      path: '/cases/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'cases',
      description: 'Update case status',
    },
    {
      method: 'GET',
      path: '/cases/:id/status-history',
      auth: true,
      handler: 'crud',
      entity: 'case_status_history',
      operation: 'list',
      description: 'Get case status history',
    },

    // Assignment
    {
      method: 'PUT',
      path: '/cases/:id/assign',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'cases',
      description: 'Assign attorney to case',
    },

    // Search and filters
    {
      method: 'GET',
      path: '/cases/search',
      auth: true,
      handler: 'custom',
      entity: 'cases',
      description: 'Search cases',
    },
    {
      method: 'GET',
      path: '/cases/my-cases',
      auth: true,
      handler: 'custom',
      entity: 'cases',
      description: 'Get current user cases',
    },
    {
      method: 'GET',
      path: '/cases/upcoming-deadlines',
      auth: true,
      handler: 'custom',
      entity: 'case_deadlines',
      description: 'Get upcoming deadlines across all cases',
    },

    // Practice Areas
    {
      method: 'GET',
      path: '/practice-areas',
      auth: true,
      handler: 'crud',
      entity: 'practice_areas',
      operation: 'list',
      description: 'List practice areas',
    },
  ],

  config: [
    {
      key: 'caseNumberPrefix',
      label: 'Case Number Prefix',
      type: 'string',
      default: 'CASE',
      description: 'Prefix for auto-generated case numbers',
    },
    {
      key: 'autoGenerateCaseNumber',
      label: 'Auto-generate Case Numbers',
      type: 'boolean',
      default: true,
      description: 'Automatically generate sequential case numbers',
    },
    {
      key: 'requireClientForCase',
      label: 'Require Client for Cases',
      type: 'boolean',
      default: true,
      description: 'Require a client to be associated with each case',
    },
    {
      key: 'defaultCaseStatus',
      label: 'Default Case Status',
      type: 'select',
      default: 'open',
      options: [
        { value: 'open', label: 'Open' },
        { value: 'pending', label: 'Pending' },
        { value: 'active', label: 'Active' },
      ],
      description: 'Default status for new cases',
    },
    {
      key: 'deadlineReminderDays',
      label: 'Deadline Reminder Days',
      type: 'number',
      default: 7,
      description: 'Days before deadline to send reminders',
    },
    {
      key: 'enableCaseTimeline',
      label: 'Enable Case Timeline',
      type: 'boolean',
      default: true,
      description: 'Track and display case activity timeline',
    },
    {
      key: 'caseStatuses',
      label: 'Case Statuses',
      type: 'select',
      default: 'standard',
      options: [
        { value: 'standard', label: 'Standard (Open, Active, Closed)' },
        { value: 'detailed', label: 'Detailed (with sub-statuses)' },
        { value: 'custom', label: 'Custom statuses' },
      ],
      description: 'Case status configuration',
    },
  ],
};
