/**
 * Client Portal Feature Definition
 *
 * Client communication portal for law firms.
 * Supports secure messaging, document sharing, and case status viewing.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CLIENT_PORTAL_FEATURE: FeatureDefinition = {
  id: 'client-portal',
  name: 'Client Portal',
  category: 'business',
  description: 'Provide clients with secure access to case updates, documents, invoices, and messaging',
  icon: 'users',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'paralegal-services',
    'corporate-legal',
    'immigration-law',
    'family-law',
    'estate-planning',
    'tax-law',
  ],

  activationKeywords: [
    'client portal',
    'client access',
    'client login',
    'secure portal',
    'client communication',
    'client messaging',
    'document portal',
    'case portal',
    'client dashboard',
    'client area',
    'secure messaging',
    'client collaboration',
    'client self-service',
    'client hub',
    'legal portal',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'case-management', 'clients'],
  conflicts: [],

  pages: [
    {
      id: 'portal-dashboard',
      route: '/portal',
      section: 'frontend',
      title: 'My Portal',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-dashboard',
      components: [
        'welcome-header',
        'case-summary-cards',
        'recent-activity',
        'unread-messages',
        'pending-actions',
        'upcoming-events',
        'quick-links',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-cases',
      route: '/portal/cases',
      section: 'frontend',
      title: 'My Cases',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-cases',
      components: [
        'cases-list',
        'case-card',
        'status-indicator',
        'case-timeline-preview',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-case-detail',
      route: '/portal/cases/:id',
      section: 'frontend',
      title: 'Case Details',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-case-detail',
      components: [
        'case-header',
        'case-status-tracker',
        'attorney-info',
        'case-timeline',
        'next-steps',
        'case-documents',
        'message-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-documents',
      route: '/portal/documents',
      section: 'frontend',
      title: 'My Documents',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-documents',
      components: [
        'documents-list',
        'document-card',
        'folder-tree',
        'upload-button',
        'download-button',
        'search-bar',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-document-upload',
      route: '/portal/documents/upload',
      section: 'frontend',
      title: 'Upload Documents',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-document-upload',
      components: [
        'upload-zone',
        'case-selector',
        'document-type-selector',
        'description-input',
        'upload-progress',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-messages',
      route: '/portal/messages',
      section: 'frontend',
      title: 'Messages',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-messages',
      components: [
        'conversations-list',
        'conversation-preview',
        'new-message-button',
        'search-messages',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-conversation',
      route: '/portal/messages/:id',
      section: 'frontend',
      title: 'Conversation',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-conversation',
      components: [
        'message-thread',
        'message-composer',
        'attachment-button',
        'case-context',
        'participant-info',
      ],
      layout: 'chat',
    },
    {
      id: 'portal-invoices',
      route: '/portal/invoices',
      section: 'frontend',
      title: 'My Invoices',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-invoices',
      components: [
        'invoices-list',
        'invoice-card',
        'payment-status',
        'balance-summary',
        'pay-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-invoice-detail',
      route: '/portal/invoices/:id',
      section: 'frontend',
      title: 'Invoice Details',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-invoice-detail',
      components: [
        'invoice-header',
        'invoice-items',
        'payment-history',
        'download-pdf',
        'pay-now-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-payment',
      route: '/portal/invoices/:id/pay',
      section: 'frontend',
      title: 'Make Payment',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-payment',
      components: [
        'payment-summary',
        'payment-form',
        'payment-methods',
        'amount-input',
        'submit-payment',
      ],
      layout: 'centered',
    },
    {
      id: 'portal-calendar',
      route: '/portal/calendar',
      section: 'frontend',
      title: 'My Calendar',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-calendar',
      components: [
        'calendar-view',
        'event-list',
        'event-card',
        'add-to-calendar',
      ],
      layout: 'dashboard',
    },
    {
      id: 'portal-profile',
      route: '/portal/profile',
      section: 'frontend',
      title: 'My Profile',
      authRequired: true,
      roles: ['client'],
      templateId: 'portal-profile',
      components: [
        'profile-header',
        'personal-info-form',
        'contact-info-form',
        'notification-preferences',
        'change-password',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-portal-settings',
      route: '/admin/portal',
      section: 'admin',
      title: 'Portal Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-portal-settings',
      components: [
        'portal-branding',
        'access-settings',
        'feature-toggles',
        'notification-settings',
        'portal-analytics',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'welcome-header',
    'case-summary-cards',
    'recent-activity',
    'unread-messages',
    'pending-actions',
    'upcoming-events',
    'quick-links',

    // Cases components
    'cases-list',
    'case-card',
    'status-indicator',
    'case-timeline-preview',
    'case-header',
    'case-status-tracker',
    'attorney-info',
    'case-timeline',
    'next-steps',
    'case-documents',
    'message-button',

    // Documents components
    'documents-list',
    'document-card',
    'folder-tree',
    'upload-button',
    'download-button',
    'search-bar',
    'upload-zone',
    'case-selector',
    'document-type-selector',
    'description-input',
    'upload-progress',

    // Messages components
    'conversations-list',
    'conversation-preview',
    'new-message-button',
    'search-messages',
    'message-thread',
    'message-composer',
    'attachment-button',
    'case-context',
    'participant-info',

    // Invoices components
    'invoices-list',
    'invoice-card',
    'payment-status',
    'balance-summary',
    'pay-button',
    'invoice-header',
    'invoice-items',
    'payment-history',
    'download-pdf',
    'pay-now-button',

    // Payment components
    'payment-summary',
    'payment-form',
    'payment-methods',
    'amount-input',
    'submit-payment',

    // Calendar components
    'calendar-view',
    'event-list',
    'event-card',
    'add-to-calendar',

    // Profile components
    'profile-header',
    'personal-info-form',
    'contact-info-form',
    'notification-preferences',
    'change-password',

    // Admin components
    'portal-branding',
    'access-settings',
    'feature-toggles',
    'notification-settings',
    'portal-analytics',
  ],

  entities: [
    {
      name: 'portal_messages',
      displayName: 'Portal Messages',
      description: 'Secure messages between clients and attorneys',
      isCore: true,
    },
    {
      name: 'portal_conversations',
      displayName: 'Portal Conversations',
      description: 'Message conversation threads',
      isCore: true,
    },
    {
      name: 'portal_documents',
      displayName: 'Portal Documents',
      description: 'Documents shared through client portal',
      isCore: true,
    },
    {
      name: 'portal_activity',
      displayName: 'Portal Activity',
      description: 'Client portal activity log',
      isCore: false,
    },
    {
      name: 'portal_settings',
      displayName: 'Portal Settings',
      description: 'Client-specific portal settings',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Portal Dashboard
    {
      method: 'GET',
      path: '/portal/dashboard',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'portal_activity',
      description: 'Get portal dashboard data',
    },
    {
      method: 'GET',
      path: '/portal/activity',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_activity',
      operation: 'list',
      description: 'Get recent activity',
    },

    // Portal Cases
    {
      method: 'GET',
      path: '/portal/cases',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'cases',
      description: 'Get client cases',
    },
    {
      method: 'GET',
      path: '/portal/cases/:id',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'cases',
      description: 'Get case details for client',
    },
    {
      method: 'GET',
      path: '/portal/cases/:id/timeline',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'cases',
      description: 'Get case timeline for client',
    },

    // Portal Messages
    {
      method: 'GET',
      path: '/portal/conversations',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_conversations',
      operation: 'list',
      description: 'Get conversations',
    },
    {
      method: 'GET',
      path: '/portal/conversations/:id',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_conversations',
      operation: 'get',
      description: 'Get conversation',
    },
    {
      method: 'POST',
      path: '/portal/conversations',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_conversations',
      operation: 'create',
      description: 'Start new conversation',
    },
    {
      method: 'GET',
      path: '/portal/conversations/:id/messages',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_messages',
      operation: 'list',
      description: 'Get messages in conversation',
    },
    {
      method: 'POST',
      path: '/portal/conversations/:id/messages',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_messages',
      operation: 'create',
      description: 'Send message',
    },
    {
      method: 'PUT',
      path: '/portal/messages/:id/read',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'portal_messages',
      description: 'Mark message as read',
    },

    // Portal Documents
    {
      method: 'GET',
      path: '/portal/documents',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_documents',
      operation: 'list',
      description: 'Get shared documents',
    },
    {
      method: 'GET',
      path: '/portal/documents/:id',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_documents',
      operation: 'get',
      description: 'Get document details',
    },
    {
      method: 'POST',
      path: '/portal/documents',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_documents',
      operation: 'create',
      description: 'Upload document',
    },
    {
      method: 'GET',
      path: '/portal/documents/:id/download',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'portal_documents',
      description: 'Download document',
    },

    // Portal Invoices
    {
      method: 'GET',
      path: '/portal/invoices',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'invoices',
      description: 'Get client invoices',
    },
    {
      method: 'GET',
      path: '/portal/invoices/:id',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'invoices',
      description: 'Get invoice details',
    },
    {
      method: 'POST',
      path: '/portal/invoices/:id/pay',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'payments',
      description: 'Pay invoice',
    },
    {
      method: 'GET',
      path: '/portal/invoices/:id/pdf',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'invoices',
      description: 'Download invoice PDF',
    },
    {
      method: 'GET',
      path: '/portal/balance',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'invoices',
      description: 'Get account balance',
    },

    // Portal Calendar
    {
      method: 'GET',
      path: '/portal/calendar',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'court_events',
      description: 'Get client calendar events',
    },
    {
      method: 'GET',
      path: '/portal/events/:id/ical',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'court_events',
      description: 'Export event to iCal',
    },

    // Portal Profile
    {
      method: 'GET',
      path: '/portal/profile',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'clients',
      description: 'Get client profile',
    },
    {
      method: 'PUT',
      path: '/portal/profile',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'clients',
      description: 'Update client profile',
    },
    {
      method: 'PUT',
      path: '/portal/profile/password',
      auth: true,
      role: 'client',
      handler: 'custom',
      entity: 'clients',
      description: 'Change password',
    },
    {
      method: 'GET',
      path: '/portal/settings',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_settings',
      operation: 'get',
      description: 'Get portal settings',
    },
    {
      method: 'PUT',
      path: '/portal/settings',
      auth: true,
      role: 'client',
      handler: 'crud',
      entity: 'portal_settings',
      operation: 'update',
      description: 'Update portal settings',
    },

    // Share document with client (attorney side)
    {
      method: 'POST',
      path: '/portal/share-document',
      auth: true,
      role: 'attorney',
      handler: 'custom',
      entity: 'portal_documents',
      description: 'Share document with client',
    },

    // Admin endpoints
    {
      method: 'GET',
      path: '/admin/portal/analytics',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'portal_activity',
      description: 'Get portal analytics',
    },
  ],

  config: [
    {
      key: 'enableClientDocumentUpload',
      label: 'Allow Client Document Upload',
      type: 'boolean',
      default: true,
      description: 'Allow clients to upload documents',
    },
    {
      key: 'enableSecureMessaging',
      label: 'Enable Secure Messaging',
      type: 'boolean',
      default: true,
      description: 'Allow secure messaging with clients',
    },
    {
      key: 'enableOnlinePayments',
      label: 'Enable Online Payments',
      type: 'boolean',
      default: true,
      description: 'Allow clients to pay invoices online',
    },
    {
      key: 'showCaseTimeline',
      label: 'Show Case Timeline',
      type: 'boolean',
      default: true,
      description: 'Display case timeline to clients',
    },
    {
      key: 'showBillingDetails',
      label: 'Show Billing Details',
      type: 'boolean',
      default: true,
      description: 'Show detailed billing information to clients',
    },
    {
      key: 'notifyOnNewDocument',
      label: 'Notify on New Document',
      type: 'boolean',
      default: true,
      description: 'Email clients when new documents are shared',
    },
    {
      key: 'notifyOnCaseUpdate',
      label: 'Notify on Case Update',
      type: 'boolean',
      default: true,
      description: 'Email clients when case status changes',
    },
    {
      key: 'portalBranding',
      label: 'Portal Branding',
      type: 'select',
      default: 'firm',
      options: [
        { value: 'firm', label: 'Firm Branding' },
        { value: 'minimal', label: 'Minimal' },
        { value: 'custom', label: 'Custom' },
      ],
      description: 'Portal branding style',
    },
    {
      key: 'sessionTimeout',
      label: 'Session Timeout (minutes)',
      type: 'number',
      default: 30,
      description: 'Client session timeout duration',
    },
  ],
};
