/**
 * Client Intake Feature Definition
 *
 * Client onboarding and intake process for law firms.
 * Supports intake forms, conflict screening, and client qualification.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CLIENT_INTAKE_FEATURE: FeatureDefinition = {
  id: 'client-intake',
  name: 'Client Intake',
  category: 'business',
  description: 'Manage client onboarding with intake forms, document collection, and qualification workflows',
  icon: 'user-plus',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'paralegal-services',
    'corporate-legal',
    'immigration-law',
    'family-law',
    'criminal-defense',
    'personal-injury',
  ],

  activationKeywords: [
    'client intake',
    'client onboarding',
    'intake form',
    'new client',
    'client registration',
    'intake process',
    'client qualification',
    'prospective client',
    'lead intake',
    'client screening',
    'intake questionnaire',
    'client application',
    'onboarding workflow',
    'client signup',
    'legal intake',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'clients', 'file-upload'],
  conflicts: [],

  pages: [
    {
      id: 'intake-form-public',
      route: '/intake',
      section: 'frontend',
      title: 'Client Intake',
      authRequired: false,
      templateId: 'intake-form-public',
      components: [
        'intake-wizard',
        'personal-info-form',
        'case-description-form',
        'document-upload',
        'consent-checkbox',
        'intake-progress',
      ],
      layout: 'centered',
    },
    {
      id: 'intake-submissions',
      route: '/intakes',
      section: 'frontend',
      title: 'Intake Submissions',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin', 'intake-coordinator'],
      templateId: 'intake-submissions',
      components: [
        'intakes-table',
        'intake-card',
        'intake-filters',
        'status-filter',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'dashboard',
    },
    {
      id: 'intake-detail',
      route: '/intakes/:id',
      section: 'frontend',
      title: 'Intake Details',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin', 'intake-coordinator'],
      templateId: 'intake-detail',
      components: [
        'intake-header',
        'intake-summary',
        'intake-documents',
        'intake-notes',
        'intake-actions',
        'conflict-check-results',
        'convert-to-client',
      ],
      layout: 'dashboard',
    },
    {
      id: 'intake-review',
      route: '/intakes/:id/review',
      section: 'frontend',
      title: 'Review Intake',
      authRequired: true,
      roles: ['attorney', 'admin'],
      templateId: 'intake-review',
      components: [
        'intake-summary',
        'qualification-checklist',
        'conflict-check-panel',
        'intake-decision',
        'rejection-reason',
        'attorney-notes',
      ],
      layout: 'dashboard',
    },
    {
      id: 'intake-form-builder',
      route: '/admin/intake-forms',
      section: 'admin',
      title: 'Intake Form Builder',
      authRequired: true,
      roles: ['admin'],
      templateId: 'intake-form-builder',
      components: [
        'form-builder',
        'field-library',
        'form-preview',
        'conditional-logic',
        'form-settings',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-intakes',
      route: '/admin/intakes',
      section: 'admin',
      title: 'Manage Intakes',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-intakes',
      components: [
        'intakes-table',
        'intake-filters',
        'bulk-actions',
        'intake-analytics',
        'conversion-stats',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Public intake form
    'intake-wizard',
    'personal-info-form',
    'case-description-form',
    'document-upload',
    'consent-checkbox',
    'intake-progress',

    // List components
    'intakes-table',
    'intake-card',
    'intake-filters',
    'status-filter',
    'sort-dropdown',
    'pagination',

    // Detail components
    'intake-header',
    'intake-summary',
    'intake-documents',
    'intake-notes',
    'intake-actions',
    'conflict-check-results',
    'convert-to-client',

    // Review components
    'qualification-checklist',
    'conflict-check-panel',
    'intake-decision',
    'rejection-reason',
    'attorney-notes',

    // Admin components
    'form-builder',
    'field-library',
    'form-preview',
    'conditional-logic',
    'form-settings',
    'bulk-actions',
    'intake-analytics',
    'conversion-stats',
  ],

  entities: [
    {
      name: 'intakes',
      displayName: 'Intakes',
      description: 'Client intake submissions',
      isCore: true,
    },
    {
      name: 'intake_forms',
      displayName: 'Intake Forms',
      description: 'Customizable intake form templates',
      isCore: true,
    },
    {
      name: 'intake_documents',
      displayName: 'Intake Documents',
      description: 'Documents uploaded during intake',
      isCore: true,
    },
    {
      name: 'intake_notes',
      displayName: 'Intake Notes',
      description: 'Internal notes on intake submissions',
      isCore: false,
    },
    {
      name: 'intake_form_fields',
      displayName: 'Intake Form Fields',
      description: 'Custom fields for intake forms',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Public Intake Submission
    {
      method: 'POST',
      path: '/intakes/submit',
      auth: false,
      handler: 'custom',
      entity: 'intakes',
      description: 'Submit new intake form',
    },
    {
      method: 'GET',
      path: '/intakes/form/:formId',
      auth: false,
      handler: 'custom',
      entity: 'intake_forms',
      description: 'Get intake form structure',
    },

    // Intake CRUD
    {
      method: 'GET',
      path: '/intakes',
      auth: true,
      handler: 'crud',
      entity: 'intakes',
      operation: 'list',
      description: 'List all intakes',
    },
    {
      method: 'GET',
      path: '/intakes/:id',
      auth: true,
      handler: 'crud',
      entity: 'intakes',
      operation: 'get',
      description: 'Get intake details',
    },
    {
      method: 'PUT',
      path: '/intakes/:id',
      auth: true,
      handler: 'crud',
      entity: 'intakes',
      operation: 'update',
      description: 'Update intake',
    },
    {
      method: 'DELETE',
      path: '/intakes/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'intakes',
      operation: 'delete',
      description: 'Delete intake',
    },

    // Intake Status and Actions
    {
      method: 'PUT',
      path: '/intakes/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'intakes',
      description: 'Update intake status',
    },
    {
      method: 'POST',
      path: '/intakes/:id/approve',
      auth: true,
      role: 'attorney',
      handler: 'custom',
      entity: 'intakes',
      description: 'Approve intake and create client',
    },
    {
      method: 'POST',
      path: '/intakes/:id/reject',
      auth: true,
      role: 'attorney',
      handler: 'custom',
      entity: 'intakes',
      description: 'Reject intake',
    },
    {
      method: 'POST',
      path: '/intakes/:id/convert',
      auth: true,
      handler: 'custom',
      entity: 'intakes',
      description: 'Convert intake to client and case',
    },

    // Intake Documents
    {
      method: 'GET',
      path: '/intakes/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'intake_documents',
      operation: 'list',
      description: 'Get intake documents',
    },
    {
      method: 'POST',
      path: '/intakes/:id/documents',
      auth: false,
      handler: 'crud',
      entity: 'intake_documents',
      operation: 'create',
      description: 'Upload intake document',
    },
    {
      method: 'DELETE',
      path: '/intakes/:intakeId/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'intake_documents',
      operation: 'delete',
      description: 'Delete intake document',
    },

    // Intake Notes
    {
      method: 'GET',
      path: '/intakes/:id/notes',
      auth: true,
      handler: 'crud',
      entity: 'intake_notes',
      operation: 'list',
      description: 'Get intake notes',
    },
    {
      method: 'POST',
      path: '/intakes/:id/notes',
      auth: true,
      handler: 'crud',
      entity: 'intake_notes',
      operation: 'create',
      description: 'Add note to intake',
    },

    // Intake Forms (Admin)
    {
      method: 'GET',
      path: '/intake-forms',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'intake_forms',
      operation: 'list',
      description: 'List intake forms',
    },
    {
      method: 'POST',
      path: '/intake-forms',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'intake_forms',
      operation: 'create',
      description: 'Create intake form',
    },
    {
      method: 'PUT',
      path: '/intake-forms/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'intake_forms',
      operation: 'update',
      description: 'Update intake form',
    },
    {
      method: 'DELETE',
      path: '/intake-forms/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'intake_forms',
      operation: 'delete',
      description: 'Delete intake form',
    },

    // Analytics
    {
      method: 'GET',
      path: '/intakes/analytics',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'intakes',
      description: 'Get intake analytics',
    },
  ],

  config: [
    {
      key: 'requireConsentCheckbox',
      label: 'Require Consent Checkbox',
      type: 'boolean',
      default: true,
      description: 'Require users to accept terms before submitting',
    },
    {
      key: 'enableDocumentUpload',
      label: 'Enable Document Upload',
      type: 'boolean',
      default: true,
      description: 'Allow document uploads during intake',
    },
    {
      key: 'maxDocumentSize',
      label: 'Max Document Size (MB)',
      type: 'number',
      default: 10,
      description: 'Maximum file size for uploaded documents',
    },
    {
      key: 'autoConflictCheck',
      label: 'Auto Conflict Check',
      type: 'boolean',
      default: true,
      description: 'Automatically run conflict check on new intakes',
    },
    {
      key: 'notifyOnNewIntake',
      label: 'Notify on New Intake',
      type: 'boolean',
      default: true,
      description: 'Send notification when new intake is submitted',
    },
    {
      key: 'defaultIntakeForm',
      label: 'Default Intake Form',
      type: 'string',
      default: 'general',
      description: 'Default intake form to use',
    },
    {
      key: 'intakeExpirationDays',
      label: 'Intake Expiration Days',
      type: 'number',
      default: 30,
      description: 'Days before pending intake expires',
    },
    {
      key: 'requireAttorneyReview',
      label: 'Require Attorney Review',
      type: 'boolean',
      default: true,
      description: 'Require attorney approval before converting to client',
    },
  ],
};
