/**
 * Conflict Check Feature Definition
 *
 * Conflict of interest checking for law firms.
 * Supports party screening, conflict detection, and waiver management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const CONFLICT_CHECK_FEATURE: FeatureDefinition = {
  id: 'conflict-check',
  name: 'Conflict Check',
  category: 'business',
  description: 'Screen for conflicts of interest with party matching, conflict detection, and waiver tracking',
  icon: 'shield',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'corporate-legal',
    'litigation-support',
    'ethics-compliance',
  ],

  activationKeywords: [
    'conflict check',
    'conflict of interest',
    'conflicts screening',
    'party screening',
    'conflict detection',
    'ethics check',
    'conflict search',
    'new matter conflict',
    'adverse party',
    'related party',
    'conflict waiver',
    'ethical screen',
    'conflict report',
    'conflicts database',
    'conflicts clearance',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'case-management', 'clients'],
  conflicts: [],

  pages: [
    {
      id: 'conflict-search',
      route: '/conflicts/search',
      section: 'frontend',
      title: 'Conflict Search',
      authRequired: true,
      templateId: 'conflict-search',
      components: [
        'conflict-search-form',
        'party-input',
        'search-options',
        'search-button',
        'recent-searches',
      ],
      layout: 'dashboard',
    },
    {
      id: 'conflict-results',
      route: '/conflicts/results/:searchId',
      section: 'frontend',
      title: 'Conflict Results',
      authRequired: true,
      templateId: 'conflict-results',
      components: [
        'results-summary',
        'matches-list',
        'match-card',
        'match-details',
        'conflict-severity',
        'action-buttons',
        'generate-report',
      ],
      layout: 'dashboard',
    },
    {
      id: 'conflict-detail',
      route: '/conflicts/:id',
      section: 'frontend',
      title: 'Conflict Details',
      authRequired: true,
      templateId: 'conflict-detail',
      components: [
        'conflict-header',
        'conflict-parties',
        'related-matters',
        'conflict-timeline',
        'resolution-status',
        'waiver-info',
        'conflict-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'conflicts-list',
      route: '/conflicts',
      section: 'frontend',
      title: 'Conflicts',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin', 'conflicts-analyst'],
      templateId: 'conflicts-list',
      components: [
        'conflicts-table',
        'conflict-card',
        'status-filter',
        'severity-filter',
        'date-range-filter',
        'sort-dropdown',
      ],
      layout: 'dashboard',
    },
    {
      id: 'waiver-create',
      route: '/conflicts/:id/waiver',
      section: 'frontend',
      title: 'Request Waiver',
      authRequired: true,
      roles: ['attorney', 'admin'],
      templateId: 'waiver-create',
      components: [
        'waiver-form',
        'conflict-summary',
        'affected-parties',
        'waiver-terms',
        'signature-request',
        'submit-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'waivers-list',
      route: '/conflicts/waivers',
      section: 'frontend',
      title: 'Conflict Waivers',
      authRequired: true,
      roles: ['attorney', 'admin'],
      templateId: 'waivers-list',
      components: [
        'waivers-table',
        'waiver-card',
        'status-filter',
        'expiration-filter',
      ],
      layout: 'dashboard',
    },
    {
      id: 'parties-database',
      route: '/conflicts/parties',
      section: 'frontend',
      title: 'Parties Database',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin', 'conflicts-analyst'],
      templateId: 'parties-database',
      components: [
        'parties-table',
        'party-card',
        'party-search',
        'add-party-button',
        'import-parties',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-conflicts',
      route: '/admin/conflicts',
      section: 'admin',
      title: 'Conflict Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-conflicts',
      components: [
        'conflict-rules',
        'matching-settings',
        'severity-levels',
        'notification-settings',
        'reporting-options',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Search components
    'conflict-search-form',
    'party-input',
    'search-options',
    'search-button',
    'recent-searches',

    // Results components
    'results-summary',
    'matches-list',
    'match-card',
    'match-details',
    'conflict-severity',
    'action-buttons',
    'generate-report',

    // Detail components
    'conflict-header',
    'conflict-parties',
    'related-matters',
    'conflict-timeline',
    'resolution-status',
    'waiver-info',
    'conflict-actions',

    // List components
    'conflicts-table',
    'conflict-card',
    'status-filter',
    'severity-filter',
    'date-range-filter',
    'sort-dropdown',

    // Waiver components
    'waiver-form',
    'conflict-summary',
    'affected-parties',
    'waiver-terms',
    'signature-request',
    'submit-button',
    'waivers-table',
    'waiver-card',
    'expiration-filter',

    // Parties database components
    'parties-table',
    'party-card',
    'party-search',
    'add-party-button',
    'import-parties',

    // Admin components
    'conflict-rules',
    'matching-settings',
    'severity-levels',
    'notification-settings',
    'reporting-options',
  ],

  entities: [
    {
      name: 'conflict_searches',
      displayName: 'Conflict Searches',
      description: 'Conflict search records',
      isCore: true,
    },
    {
      name: 'conflicts',
      displayName: 'Conflicts',
      description: 'Identified conflicts of interest',
      isCore: true,
    },
    {
      name: 'conflict_parties',
      displayName: 'Conflict Parties',
      description: 'Parties database for conflict checking',
      isCore: true,
    },
    {
      name: 'conflict_waivers',
      displayName: 'Conflict Waivers',
      description: 'Conflict waiver records',
      isCore: false,
    },
    {
      name: 'conflict_matches',
      displayName: 'Conflict Matches',
      description: 'Matches found during conflict searches',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Conflict Search
    {
      method: 'POST',
      path: '/conflicts/search',
      auth: true,
      handler: 'custom',
      entity: 'conflict_searches',
      description: 'Run conflict search',
    },
    {
      method: 'GET',
      path: '/conflicts/search/:id',
      auth: true,
      handler: 'crud',
      entity: 'conflict_searches',
      operation: 'get',
      description: 'Get search results',
    },
    {
      method: 'GET',
      path: '/conflicts/search/recent',
      auth: true,
      handler: 'custom',
      entity: 'conflict_searches',
      description: 'Get recent searches',
    },

    // Conflicts CRUD
    {
      method: 'GET',
      path: '/conflicts',
      auth: true,
      handler: 'crud',
      entity: 'conflicts',
      operation: 'list',
      description: 'List conflicts',
    },
    {
      method: 'GET',
      path: '/conflicts/:id',
      auth: true,
      handler: 'crud',
      entity: 'conflicts',
      operation: 'get',
      description: 'Get conflict details',
    },
    {
      method: 'POST',
      path: '/conflicts',
      auth: true,
      handler: 'crud',
      entity: 'conflicts',
      operation: 'create',
      description: 'Create conflict record',
    },
    {
      method: 'PUT',
      path: '/conflicts/:id',
      auth: true,
      handler: 'crud',
      entity: 'conflicts',
      operation: 'update',
      description: 'Update conflict',
    },
    {
      method: 'DELETE',
      path: '/conflicts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'conflicts',
      operation: 'delete',
      description: 'Delete conflict',
    },

    // Conflict Status
    {
      method: 'PUT',
      path: '/conflicts/:id/resolve',
      auth: true,
      handler: 'custom',
      entity: 'conflicts',
      description: 'Resolve conflict',
    },
    {
      method: 'PUT',
      path: '/conflicts/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'conflicts',
      description: 'Update conflict status',
    },

    // Conflict Report
    {
      method: 'GET',
      path: '/conflicts/:id/report',
      auth: true,
      handler: 'custom',
      entity: 'conflicts',
      description: 'Generate conflict report',
    },

    // Waivers
    {
      method: 'GET',
      path: '/conflict-waivers',
      auth: true,
      handler: 'crud',
      entity: 'conflict_waivers',
      operation: 'list',
      description: 'List waivers',
    },
    {
      method: 'GET',
      path: '/conflict-waivers/:id',
      auth: true,
      handler: 'crud',
      entity: 'conflict_waivers',
      operation: 'get',
      description: 'Get waiver details',
    },
    {
      method: 'POST',
      path: '/conflicts/:id/waivers',
      auth: true,
      handler: 'crud',
      entity: 'conflict_waivers',
      operation: 'create',
      description: 'Request waiver',
    },
    {
      method: 'PUT',
      path: '/conflict-waivers/:id',
      auth: true,
      handler: 'crud',
      entity: 'conflict_waivers',
      operation: 'update',
      description: 'Update waiver',
    },
    {
      method: 'POST',
      path: '/conflict-waivers/:id/approve',
      auth: true,
      role: 'attorney',
      handler: 'custom',
      entity: 'conflict_waivers',
      description: 'Approve waiver',
    },
    {
      method: 'POST',
      path: '/conflict-waivers/:id/reject',
      auth: true,
      role: 'attorney',
      handler: 'custom',
      entity: 'conflict_waivers',
      description: 'Reject waiver',
    },

    // Parties Database
    {
      method: 'GET',
      path: '/conflict-parties',
      auth: true,
      handler: 'crud',
      entity: 'conflict_parties',
      operation: 'list',
      description: 'List parties',
    },
    {
      method: 'GET',
      path: '/conflict-parties/:id',
      auth: true,
      handler: 'crud',
      entity: 'conflict_parties',
      operation: 'get',
      description: 'Get party details',
    },
    {
      method: 'POST',
      path: '/conflict-parties',
      auth: true,
      handler: 'crud',
      entity: 'conflict_parties',
      operation: 'create',
      description: 'Add party',
    },
    {
      method: 'PUT',
      path: '/conflict-parties/:id',
      auth: true,
      handler: 'crud',
      entity: 'conflict_parties',
      operation: 'update',
      description: 'Update party',
    },
    {
      method: 'DELETE',
      path: '/conflict-parties/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'conflict_parties',
      operation: 'delete',
      description: 'Delete party',
    },
    {
      method: 'POST',
      path: '/conflict-parties/import',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'conflict_parties',
      description: 'Import parties from file',
    },

    // Matches
    {
      method: 'GET',
      path: '/conflicts/search/:searchId/matches',
      auth: true,
      handler: 'crud',
      entity: 'conflict_matches',
      operation: 'list',
      description: 'Get search matches',
    },
  ],

  config: [
    {
      key: 'matchingThreshold',
      label: 'Matching Threshold (%)',
      type: 'number',
      default: 80,
      description: 'Minimum similarity percentage for fuzzy matching',
    },
    {
      key: 'enableFuzzyMatching',
      label: 'Enable Fuzzy Matching',
      type: 'boolean',
      default: true,
      description: 'Use fuzzy string matching for party names',
    },
    {
      key: 'searchHistoryDays',
      label: 'Search History Retention (days)',
      type: 'number',
      default: 365,
      description: 'Days to retain conflict search history',
    },
    {
      key: 'autoCheckNewMatters',
      label: 'Auto-check New Matters',
      type: 'boolean',
      default: true,
      description: 'Automatically run conflict check for new matters',
    },
    {
      key: 'autoCheckNewIntakes',
      label: 'Auto-check New Intakes',
      type: 'boolean',
      default: true,
      description: 'Automatically run conflict check for new intakes',
    },
    {
      key: 'requireClearanceBeforeMatter',
      label: 'Require Clearance Before Opening Matter',
      type: 'boolean',
      default: true,
      description: 'Require conflict clearance before opening new matter',
    },
    {
      key: 'notifyOnPotentialConflict',
      label: 'Notify on Potential Conflict',
      type: 'boolean',
      default: true,
      description: 'Send notification when potential conflict is found',
    },
    {
      key: 'waiverExpirationDays',
      label: 'Waiver Expiration (days)',
      type: 'number',
      default: 0,
      description: 'Days until waiver expires (0 = never)',
    },
  ],
};
