/**
 * Court Calendar Feature Definition
 *
 * Court date tracking and scheduling for law firms.
 * Supports court appearances, deadlines, and calendar synchronization.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const COURT_CALENDAR_FEATURE: FeatureDefinition = {
  id: 'court-calendar',
  name: 'Court Calendar',
  category: 'business',
  description: 'Track court dates, hearings, deadlines, and legal appointments with calendar integration',
  icon: 'calendar',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'litigation-support',
    'criminal-defense',
    'family-law',
    'immigration-law',
    'personal-injury',
    'civil-litigation',
  ],

  activationKeywords: [
    'court calendar',
    'court dates',
    'hearing schedule',
    'court appearance',
    'legal calendar',
    'docket calendar',
    'court scheduling',
    'trial date',
    'motion hearing',
    'court deadline',
    'legal deadlines',
    'court events',
    'appearance calendar',
    'litigation calendar',
    'judicial calendar',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'case-management', 'calendar'],
  conflicts: [],

  pages: [
    {
      id: 'court-calendar-view',
      route: '/court-calendar',
      section: 'frontend',
      title: 'Court Calendar',
      authRequired: true,
      templateId: 'court-calendar-view',
      components: [
        'calendar-view',
        'event-list',
        'date-navigator',
        'view-toggle',
        'filter-panel',
        'attorney-filter',
        'case-filter',
      ],
      layout: 'dashboard',
    },
    {
      id: 'court-event-detail',
      route: '/court-calendar/:id',
      section: 'frontend',
      title: 'Court Event Details',
      authRequired: true,
      templateId: 'court-event-detail',
      components: [
        'event-header',
        'event-details',
        'case-link',
        'location-map',
        'attendees-list',
        'event-notes',
        'reminder-settings',
        'event-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'court-event-create',
      route: '/court-calendar/new',
      section: 'frontend',
      title: 'Add Court Event',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin'],
      templateId: 'court-event-create',
      components: [
        'event-form',
        'case-selector',
        'court-selector',
        'judge-selector',
        'date-time-picker',
        'recurrence-options',
        'attendee-selector',
        'reminder-setup',
      ],
      layout: 'dashboard',
    },
    {
      id: 'court-event-edit',
      route: '/court-calendar/:id/edit',
      section: 'frontend',
      title: 'Edit Court Event',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin'],
      templateId: 'court-event-edit',
      components: [
        'event-form',
        'case-selector',
        'court-selector',
        'judge-selector',
        'date-time-picker',
        'recurrence-options',
        'attendee-selector',
        'reminder-setup',
        'cancellation-options',
      ],
      layout: 'dashboard',
    },
    {
      id: 'upcoming-events',
      route: '/court-calendar/upcoming',
      section: 'frontend',
      title: 'Upcoming Court Dates',
      authRequired: true,
      templateId: 'upcoming-events',
      components: [
        'events-list',
        'event-card',
        'countdown-timer',
        'quick-filters',
        'export-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'court-directory',
      route: '/courts',
      section: 'frontend',
      title: 'Court Directory',
      authRequired: true,
      templateId: 'court-directory',
      components: [
        'courts-list',
        'court-card',
        'court-search',
        'jurisdiction-filter',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-court-calendar',
      route: '/admin/court-calendar',
      section: 'admin',
      title: 'Manage Court Calendar',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-court-calendar',
      components: [
        'events-table',
        'calendar-settings',
        'court-manager',
        'judge-manager',
        'sync-settings',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calendar components
    'calendar-view',
    'event-list',
    'date-navigator',
    'view-toggle',
    'filter-panel',
    'attorney-filter',
    'case-filter',

    // Event detail components
    'event-header',
    'event-details',
    'case-link',
    'location-map',
    'attendees-list',
    'event-notes',
    'reminder-settings',
    'event-actions',

    // Form components
    'event-form',
    'case-selector',
    'court-selector',
    'judge-selector',
    'date-time-picker',
    'recurrence-options',
    'attendee-selector',
    'reminder-setup',
    'cancellation-options',

    // List components
    'events-list',
    'event-card',
    'countdown-timer',
    'quick-filters',
    'export-button',

    // Court directory components
    'courts-list',
    'court-card',
    'court-search',
    'jurisdiction-filter',

    // Admin components
    'events-table',
    'calendar-settings',
    'court-manager',
    'judge-manager',
    'sync-settings',
  ],

  entities: [
    {
      name: 'court_events',
      displayName: 'Court Events',
      description: 'Court dates and appearances',
      isCore: true,
    },
    {
      name: 'courts',
      displayName: 'Courts',
      description: 'Court directory',
      isCore: true,
    },
    {
      name: 'judges',
      displayName: 'Judges',
      description: 'Judge directory',
      isCore: false,
    },
    {
      name: 'event_attendees',
      displayName: 'Event Attendees',
      description: 'Attendees for court events',
      isCore: false,
    },
    {
      name: 'event_reminders',
      displayName: 'Event Reminders',
      description: 'Reminder settings for events',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Court Events CRUD
    {
      method: 'GET',
      path: '/court-events',
      auth: true,
      handler: 'crud',
      entity: 'court_events',
      operation: 'list',
      description: 'List court events',
    },
    {
      method: 'GET',
      path: '/court-events/:id',
      auth: true,
      handler: 'crud',
      entity: 'court_events',
      operation: 'get',
      description: 'Get court event details',
    },
    {
      method: 'POST',
      path: '/court-events',
      auth: true,
      handler: 'crud',
      entity: 'court_events',
      operation: 'create',
      description: 'Create court event',
    },
    {
      method: 'PUT',
      path: '/court-events/:id',
      auth: true,
      handler: 'crud',
      entity: 'court_events',
      operation: 'update',
      description: 'Update court event',
    },
    {
      method: 'DELETE',
      path: '/court-events/:id',
      auth: true,
      handler: 'crud',
      entity: 'court_events',
      operation: 'delete',
      description: 'Delete court event',
    },

    // Calendar Views
    {
      method: 'GET',
      path: '/court-events/calendar',
      auth: true,
      handler: 'custom',
      entity: 'court_events',
      description: 'Get events for calendar view',
    },
    {
      method: 'GET',
      path: '/court-events/upcoming',
      auth: true,
      handler: 'custom',
      entity: 'court_events',
      description: 'Get upcoming court events',
    },
    {
      method: 'GET',
      path: '/court-events/by-case/:caseId',
      auth: true,
      handler: 'custom',
      entity: 'court_events',
      description: 'Get events for a specific case',
    },
    {
      method: 'GET',
      path: '/court-events/by-attorney/:attorneyId',
      auth: true,
      handler: 'custom',
      entity: 'court_events',
      description: 'Get events for a specific attorney',
    },

    // Event Attendees
    {
      method: 'GET',
      path: '/court-events/:id/attendees',
      auth: true,
      handler: 'crud',
      entity: 'event_attendees',
      operation: 'list',
      description: 'Get event attendees',
    },
    {
      method: 'POST',
      path: '/court-events/:id/attendees',
      auth: true,
      handler: 'crud',
      entity: 'event_attendees',
      operation: 'create',
      description: 'Add attendee to event',
    },
    {
      method: 'DELETE',
      path: '/court-events/:eventId/attendees/:id',
      auth: true,
      handler: 'crud',
      entity: 'event_attendees',
      operation: 'delete',
      description: 'Remove attendee from event',
    },

    // Reminders
    {
      method: 'GET',
      path: '/court-events/:id/reminders',
      auth: true,
      handler: 'crud',
      entity: 'event_reminders',
      operation: 'list',
      description: 'Get event reminders',
    },
    {
      method: 'POST',
      path: '/court-events/:id/reminders',
      auth: true,
      handler: 'crud',
      entity: 'event_reminders',
      operation: 'create',
      description: 'Add reminder to event',
    },
    {
      method: 'PUT',
      path: '/court-events/:eventId/reminders/:id',
      auth: true,
      handler: 'crud',
      entity: 'event_reminders',
      operation: 'update',
      description: 'Update reminder',
    },

    // Courts Directory
    {
      method: 'GET',
      path: '/courts',
      auth: true,
      handler: 'crud',
      entity: 'courts',
      operation: 'list',
      description: 'List courts',
    },
    {
      method: 'GET',
      path: '/courts/:id',
      auth: true,
      handler: 'crud',
      entity: 'courts',
      operation: 'get',
      description: 'Get court details',
    },
    {
      method: 'POST',
      path: '/courts',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'courts',
      operation: 'create',
      description: 'Add court to directory',
    },
    {
      method: 'PUT',
      path: '/courts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'courts',
      operation: 'update',
      description: 'Update court info',
    },

    // Judges Directory
    {
      method: 'GET',
      path: '/judges',
      auth: true,
      handler: 'crud',
      entity: 'judges',
      operation: 'list',
      description: 'List judges',
    },
    {
      method: 'POST',
      path: '/judges',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'judges',
      operation: 'create',
      description: 'Add judge to directory',
    },

    // Calendar Sync
    {
      method: 'GET',
      path: '/court-events/export/ical',
      auth: true,
      handler: 'custom',
      entity: 'court_events',
      description: 'Export events as iCal',
    },
    {
      method: 'POST',
      path: '/court-events/sync/google',
      auth: true,
      handler: 'custom',
      entity: 'court_events',
      description: 'Sync with Google Calendar',
    },
    {
      method: 'POST',
      path: '/court-events/sync/outlook',
      auth: true,
      handler: 'custom',
      entity: 'court_events',
      description: 'Sync with Outlook Calendar',
    },
  ],

  config: [
    {
      key: 'defaultView',
      label: 'Default Calendar View',
      type: 'select',
      default: 'week',
      options: [
        { value: 'day', label: 'Day' },
        { value: 'week', label: 'Week' },
        { value: 'month', label: 'Month' },
        { value: 'agenda', label: 'Agenda' },
      ],
      description: 'Default view for court calendar',
    },
    {
      key: 'defaultReminderMinutes',
      label: 'Default Reminder (minutes before)',
      type: 'number',
      default: 60,
      description: 'Default reminder time before court events',
    },
    {
      key: 'enableRecurringEvents',
      label: 'Enable Recurring Events',
      type: 'boolean',
      default: true,
      description: 'Allow creation of recurring court events',
    },
    {
      key: 'enableCalendarSync',
      label: 'Enable Calendar Sync',
      type: 'boolean',
      default: true,
      description: 'Allow syncing with external calendars',
    },
    {
      key: 'workingHoursStart',
      label: 'Working Hours Start',
      type: 'string',
      default: '08:00',
      description: 'Start of working hours for calendar display',
    },
    {
      key: 'workingHoursEnd',
      label: 'Working Hours End',
      type: 'string',
      default: '18:00',
      description: 'End of working hours for calendar display',
    },
    {
      key: 'eventTypes',
      label: 'Event Types',
      type: 'select',
      default: 'standard',
      options: [
        { value: 'standard', label: 'Standard (Hearing, Trial, Motion)' },
        { value: 'extended', label: 'Extended (with custom types)' },
      ],
      description: 'Available court event types',
    },
    {
      key: 'conflictDetection',
      label: 'Enable Conflict Detection',
      type: 'boolean',
      default: true,
      description: 'Detect scheduling conflicts for attorneys',
    },
  ],
};
