/**
 * Document Assembly Feature Definition
 *
 * Legal document generation and template management for law firms.
 * Supports document templates, automated generation, and e-signatures.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const DOCUMENT_ASSEMBLY_FEATURE: FeatureDefinition = {
  id: 'document-assembly',
  name: 'Document Assembly',
  category: 'business',
  description: 'Generate legal documents from templates with automated data population and e-signatures',
  icon: 'file-text',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'paralegal-services',
    'corporate-legal',
    'real-estate-law',
    'estate-planning',
    'contract-management',
    'notary-services',
  ],

  activationKeywords: [
    'document assembly',
    'document generation',
    'legal documents',
    'document templates',
    'contract generation',
    'form generation',
    'legal forms',
    'document automation',
    'pleading generation',
    'court documents',
    'legal drafting',
    'template management',
    'document builder',
    'automated documents',
    'e-signature',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload', 'case-management'],
  conflicts: [],

  pages: [
    {
      id: 'documents-list',
      route: '/documents',
      section: 'frontend',
      title: 'Documents',
      authRequired: true,
      templateId: 'documents-list',
      components: [
        'documents-table',
        'document-card',
        'document-filters',
        'category-filter',
        'sort-dropdown',
        'pagination',
        'generate-document-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'document-detail',
      route: '/documents/:id',
      section: 'frontend',
      title: 'Document Details',
      authRequired: true,
      templateId: 'document-detail',
      components: [
        'document-header',
        'document-viewer',
        'document-metadata',
        'version-history',
        'document-actions',
        'signature-status',
        'related-case',
      ],
      layout: 'dashboard',
    },
    {
      id: 'document-generate',
      route: '/documents/generate',
      section: 'frontend',
      title: 'Generate Document',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin'],
      templateId: 'document-generate',
      components: [
        'template-selector',
        'case-selector',
        'client-selector',
        'data-mapper',
        'field-editor',
        'document-preview',
        'generate-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'document-edit',
      route: '/documents/:id/edit',
      section: 'frontend',
      title: 'Edit Document',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin'],
      templateId: 'document-edit',
      components: [
        'document-editor',
        'field-panel',
        'document-preview',
        'save-button',
        'version-notes',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'document-sign',
      route: '/documents/:id/sign',
      section: 'frontend',
      title: 'Sign Document',
      authRequired: true,
      templateId: 'document-sign',
      components: [
        'document-viewer',
        'signature-pad',
        'signature-placement',
        'signer-info',
        'submit-signature',
      ],
      layout: 'centered',
    },
    {
      id: 'templates-list',
      route: '/templates',
      section: 'frontend',
      title: 'Document Templates',
      authRequired: true,
      roles: ['attorney', 'paralegal', 'admin'],
      templateId: 'templates-list',
      components: [
        'templates-grid',
        'template-card',
        'category-filter',
        'template-search',
      ],
      layout: 'dashboard',
    },
    {
      id: 'template-builder',
      route: '/admin/templates/builder',
      section: 'admin',
      title: 'Template Builder',
      authRequired: true,
      roles: ['admin'],
      templateId: 'template-builder',
      components: [
        'template-editor',
        'variable-inserter',
        'conditional-logic',
        'template-preview',
        'template-settings',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-documents',
      route: '/admin/documents',
      section: 'admin',
      title: 'Manage Documents',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-documents',
      components: [
        'documents-table',
        'document-filters',
        'bulk-actions',
        'document-analytics',
        'storage-usage',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'documents-table',
    'document-card',
    'document-filters',
    'category-filter',
    'sort-dropdown',
    'pagination',
    'generate-document-button',

    // Detail components
    'document-header',
    'document-viewer',
    'document-metadata',
    'version-history',
    'document-actions',
    'signature-status',
    'related-case',

    // Generation components
    'template-selector',
    'case-selector',
    'client-selector',
    'data-mapper',
    'field-editor',
    'document-preview',
    'generate-button',

    // Editor components
    'document-editor',
    'field-panel',
    'save-button',
    'version-notes',

    // Signature components
    'signature-pad',
    'signature-placement',
    'signer-info',
    'submit-signature',

    // Template components
    'templates-grid',
    'template-card',
    'template-search',
    'template-editor',
    'variable-inserter',
    'conditional-logic',
    'template-preview',
    'template-settings',

    // Admin components
    'bulk-actions',
    'document-analytics',
    'storage-usage',
  ],

  entities: [
    {
      name: 'documents',
      displayName: 'Documents',
      description: 'Generated legal documents',
      isCore: true,
    },
    {
      name: 'document_templates',
      displayName: 'Document Templates',
      description: 'Reusable document templates',
      isCore: true,
    },
    {
      name: 'document_versions',
      displayName: 'Document Versions',
      description: 'Version history for documents',
      isCore: true,
    },
    {
      name: 'document_signatures',
      displayName: 'Document Signatures',
      description: 'E-signature records',
      isCore: false,
    },
    {
      name: 'template_variables',
      displayName: 'Template Variables',
      description: 'Variables used in templates',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Document CRUD
    {
      method: 'GET',
      path: '/documents',
      auth: true,
      handler: 'crud',
      entity: 'documents',
      operation: 'list',
      description: 'List all documents',
    },
    {
      method: 'GET',
      path: '/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'documents',
      operation: 'get',
      description: 'Get document details',
    },
    {
      method: 'POST',
      path: '/documents',
      auth: true,
      handler: 'crud',
      entity: 'documents',
      operation: 'create',
      description: 'Create document',
    },
    {
      method: 'PUT',
      path: '/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'documents',
      operation: 'update',
      description: 'Update document',
    },
    {
      method: 'DELETE',
      path: '/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'documents',
      operation: 'delete',
      description: 'Delete document',
    },

    // Document Generation
    {
      method: 'POST',
      path: '/documents/generate',
      auth: true,
      handler: 'custom',
      entity: 'documents',
      description: 'Generate document from template',
    },
    {
      method: 'POST',
      path: '/documents/generate/preview',
      auth: true,
      handler: 'custom',
      entity: 'documents',
      description: 'Preview generated document',
    },

    // Document Download
    {
      method: 'GET',
      path: '/documents/:id/download',
      auth: true,
      handler: 'custom',
      entity: 'documents',
      description: 'Download document',
    },
    {
      method: 'GET',
      path: '/documents/:id/pdf',
      auth: true,
      handler: 'custom',
      entity: 'documents',
      description: 'Get document as PDF',
    },

    // Document Versions
    {
      method: 'GET',
      path: '/documents/:id/versions',
      auth: true,
      handler: 'crud',
      entity: 'document_versions',
      operation: 'list',
      description: 'Get document versions',
    },
    {
      method: 'POST',
      path: '/documents/:id/versions',
      auth: true,
      handler: 'crud',
      entity: 'document_versions',
      operation: 'create',
      description: 'Create new version',
    },
    {
      method: 'GET',
      path: '/documents/:docId/versions/:id',
      auth: true,
      handler: 'crud',
      entity: 'document_versions',
      operation: 'get',
      description: 'Get specific version',
    },

    // Signatures
    {
      method: 'POST',
      path: '/documents/:id/sign',
      auth: true,
      handler: 'custom',
      entity: 'document_signatures',
      description: 'Sign document',
    },
    {
      method: 'GET',
      path: '/documents/:id/signatures',
      auth: true,
      handler: 'crud',
      entity: 'document_signatures',
      operation: 'list',
      description: 'Get document signatures',
    },
    {
      method: 'POST',
      path: '/documents/:id/request-signature',
      auth: true,
      handler: 'custom',
      entity: 'document_signatures',
      description: 'Request signature from signer',
    },

    // Templates CRUD
    {
      method: 'GET',
      path: '/templates',
      auth: true,
      handler: 'crud',
      entity: 'document_templates',
      operation: 'list',
      description: 'List templates',
    },
    {
      method: 'GET',
      path: '/templates/:id',
      auth: true,
      handler: 'crud',
      entity: 'document_templates',
      operation: 'get',
      description: 'Get template',
    },
    {
      method: 'POST',
      path: '/templates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'document_templates',
      operation: 'create',
      description: 'Create template',
    },
    {
      method: 'PUT',
      path: '/templates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'document_templates',
      operation: 'update',
      description: 'Update template',
    },
    {
      method: 'DELETE',
      path: '/templates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'document_templates',
      operation: 'delete',
      description: 'Delete template',
    },

    // Template Variables
    {
      method: 'GET',
      path: '/templates/:id/variables',
      auth: true,
      handler: 'crud',
      entity: 'template_variables',
      operation: 'list',
      description: 'Get template variables',
    },
  ],

  config: [
    {
      key: 'enableESignatures',
      label: 'Enable E-Signatures',
      type: 'boolean',
      default: true,
      description: 'Allow electronic signatures on documents',
    },
    {
      key: 'defaultOutputFormat',
      label: 'Default Output Format',
      type: 'select',
      default: 'pdf',
      options: [
        { value: 'pdf', label: 'PDF' },
        { value: 'docx', label: 'Word Document' },
        { value: 'both', label: 'Both PDF and Word' },
      ],
      description: 'Default format for generated documents',
    },
    {
      key: 'enableVersioning',
      label: 'Enable Version History',
      type: 'boolean',
      default: true,
      description: 'Track document version history',
    },
    {
      key: 'maxVersions',
      label: 'Max Versions to Keep',
      type: 'number',
      default: 10,
      description: 'Maximum number of versions to retain per document',
    },
    {
      key: 'watermarkDrafts',
      label: 'Watermark Draft Documents',
      type: 'boolean',
      default: true,
      description: 'Add DRAFT watermark to unsigned documents',
    },
    {
      key: 'autoSaveInterval',
      label: 'Auto-save Interval (seconds)',
      type: 'number',
      default: 30,
      description: 'Auto-save interval when editing documents',
    },
    {
      key: 'signatureProvider',
      label: 'Signature Provider',
      type: 'select',
      default: 'built-in',
      options: [
        { value: 'built-in', label: 'Built-in' },
        { value: 'docusign', label: 'DocuSign' },
        { value: 'hellosign', label: 'HelloSign' },
      ],
      description: 'E-signature service provider',
    },
    {
      key: 'requireSignerVerification',
      label: 'Require Signer Verification',
      type: 'boolean',
      default: false,
      description: 'Require identity verification before signing',
    },
  ],
};
