/**
 * Matter Notes Feature Definition
 *
 * Case notes and memo management for law firms.
 * Supports note categorization, tagging, and collaboration.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const MATTER_NOTES_FEATURE: FeatureDefinition = {
  id: 'matter-notes',
  name: 'Matter Notes',
  category: 'business',
  description: 'Create and manage case notes, memos, and annotations with categorization and search',
  icon: 'file-text',

  includedInAppTypes: [
    'law-firm',
    'legal-practice',
    'legal-services',
    'attorney-office',
    'paralegal-services',
    'corporate-legal',
    'litigation-support',
    'legal-research',
  ],

  activationKeywords: [
    'matter notes',
    'case notes',
    'legal notes',
    'case memo',
    'legal memo',
    'attorney notes',
    'research notes',
    'client notes',
    'deposition notes',
    'meeting notes',
    'note taking',
    'case diary',
    'legal annotations',
    'work notes',
    'internal memo',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'case-management'],
  conflicts: [],

  pages: [
    {
      id: 'notes-list',
      route: '/notes',
      section: 'frontend',
      title: 'Notes',
      authRequired: true,
      templateId: 'notes-list',
      components: [
        'notes-grid',
        'note-card',
        'notes-sidebar',
        'category-filter',
        'tag-filter',
        'search-bar',
        'sort-options',
        'create-note-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'note-detail',
      route: '/notes/:id',
      section: 'frontend',
      title: 'Note',
      authRequired: true,
      templateId: 'note-detail',
      components: [
        'note-viewer',
        'note-header',
        'note-metadata',
        'related-case-link',
        'note-tags',
        'note-attachments',
        'note-history',
        'note-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'note-create',
      route: '/notes/new',
      section: 'frontend',
      title: 'New Note',
      authRequired: true,
      templateId: 'note-create',
      components: [
        'note-editor',
        'title-input',
        'case-selector',
        'category-selector',
        'tag-input',
        'attachment-upload',
        'privacy-toggle',
        'save-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'note-edit',
      route: '/notes/:id/edit',
      section: 'frontend',
      title: 'Edit Note',
      authRequired: true,
      templateId: 'note-edit',
      components: [
        'note-editor',
        'title-input',
        'case-selector',
        'category-selector',
        'tag-input',
        'attachment-upload',
        'privacy-toggle',
        'save-button',
        'version-info',
      ],
      layout: 'dashboard',
    },
    {
      id: 'case-notes',
      route: '/cases/:caseId/notes',
      section: 'frontend',
      title: 'Case Notes',
      authRequired: true,
      templateId: 'case-notes',
      components: [
        'notes-timeline',
        'note-card',
        'quick-note-form',
        'category-tabs',
        'add-note-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'notes-search',
      route: '/notes/search',
      section: 'frontend',
      title: 'Search Notes',
      authRequired: true,
      templateId: 'notes-search',
      components: [
        'advanced-search-form',
        'search-results',
        'result-card',
        'search-filters',
        'date-range-picker',
      ],
      layout: 'dashboard',
    },
    {
      id: 'note-templates',
      route: '/admin/note-templates',
      section: 'admin',
      title: 'Note Templates',
      authRequired: true,
      roles: ['admin'],
      templateId: 'note-templates',
      components: [
        'templates-list',
        'template-editor',
        'template-variables',
        'template-preview',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'notes-grid',
    'note-card',
    'notes-sidebar',
    'category-filter',
    'tag-filter',
    'search-bar',
    'sort-options',
    'create-note-button',

    // Detail components
    'note-viewer',
    'note-header',
    'note-metadata',
    'related-case-link',
    'note-tags',
    'note-attachments',
    'note-history',
    'note-actions',

    // Editor components
    'note-editor',
    'title-input',
    'case-selector',
    'category-selector',
    'tag-input',
    'attachment-upload',
    'privacy-toggle',
    'save-button',
    'version-info',

    // Case notes components
    'notes-timeline',
    'quick-note-form',
    'category-tabs',
    'add-note-button',

    // Search components
    'advanced-search-form',
    'search-results',
    'result-card',
    'search-filters',
    'date-range-picker',

    // Template components
    'templates-list',
    'template-editor',
    'template-variables',
    'template-preview',
  ],

  entities: [
    {
      name: 'notes',
      displayName: 'Notes',
      description: 'Case notes and memos',
      isCore: true,
    },
    {
      name: 'note_categories',
      displayName: 'Note Categories',
      description: 'Categories for organizing notes',
      isCore: true,
    },
    {
      name: 'note_tags',
      displayName: 'Note Tags',
      description: 'Tags for notes',
      isCore: false,
    },
    {
      name: 'note_attachments',
      displayName: 'Note Attachments',
      description: 'Files attached to notes',
      isCore: false,
    },
    {
      name: 'note_versions',
      displayName: 'Note Versions',
      description: 'Version history for notes',
      isCore: false,
    },
    {
      name: 'note_templates',
      displayName: 'Note Templates',
      description: 'Reusable note templates',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Notes CRUD
    {
      method: 'GET',
      path: '/notes',
      auth: true,
      handler: 'crud',
      entity: 'notes',
      operation: 'list',
      description: 'List notes',
    },
    {
      method: 'GET',
      path: '/notes/:id',
      auth: true,
      handler: 'crud',
      entity: 'notes',
      operation: 'get',
      description: 'Get note details',
    },
    {
      method: 'POST',
      path: '/notes',
      auth: true,
      handler: 'crud',
      entity: 'notes',
      operation: 'create',
      description: 'Create note',
    },
    {
      method: 'PUT',
      path: '/notes/:id',
      auth: true,
      handler: 'crud',
      entity: 'notes',
      operation: 'update',
      description: 'Update note',
    },
    {
      method: 'DELETE',
      path: '/notes/:id',
      auth: true,
      handler: 'crud',
      entity: 'notes',
      operation: 'delete',
      description: 'Delete note',
    },

    // Case Notes
    {
      method: 'GET',
      path: '/cases/:caseId/notes',
      auth: true,
      handler: 'custom',
      entity: 'notes',
      description: 'Get notes for case',
    },
    {
      method: 'POST',
      path: '/cases/:caseId/notes',
      auth: true,
      handler: 'custom',
      entity: 'notes',
      description: 'Add note to case',
    },

    // Note Search
    {
      method: 'GET',
      path: '/notes/search',
      auth: true,
      handler: 'custom',
      entity: 'notes',
      description: 'Search notes',
    },
    {
      method: 'POST',
      path: '/notes/search/advanced',
      auth: true,
      handler: 'custom',
      entity: 'notes',
      description: 'Advanced note search',
    },

    // Note Categories
    {
      method: 'GET',
      path: '/note-categories',
      auth: true,
      handler: 'crud',
      entity: 'note_categories',
      operation: 'list',
      description: 'List note categories',
    },
    {
      method: 'POST',
      path: '/note-categories',
      auth: true,
      handler: 'crud',
      entity: 'note_categories',
      operation: 'create',
      description: 'Create note category',
    },
    {
      method: 'PUT',
      path: '/note-categories/:id',
      auth: true,
      handler: 'crud',
      entity: 'note_categories',
      operation: 'update',
      description: 'Update note category',
    },
    {
      method: 'DELETE',
      path: '/note-categories/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'note_categories',
      operation: 'delete',
      description: 'Delete note category',
    },

    // Note Tags
    {
      method: 'GET',
      path: '/note-tags',
      auth: true,
      handler: 'crud',
      entity: 'note_tags',
      operation: 'list',
      description: 'List note tags',
    },
    {
      method: 'POST',
      path: '/notes/:id/tags',
      auth: true,
      handler: 'custom',
      entity: 'note_tags',
      description: 'Add tag to note',
    },
    {
      method: 'DELETE',
      path: '/notes/:noteId/tags/:tagId',
      auth: true,
      handler: 'custom',
      entity: 'note_tags',
      description: 'Remove tag from note',
    },

    // Note Attachments
    {
      method: 'GET',
      path: '/notes/:id/attachments',
      auth: true,
      handler: 'crud',
      entity: 'note_attachments',
      operation: 'list',
      description: 'Get note attachments',
    },
    {
      method: 'POST',
      path: '/notes/:id/attachments',
      auth: true,
      handler: 'crud',
      entity: 'note_attachments',
      operation: 'create',
      description: 'Add attachment to note',
    },
    {
      method: 'DELETE',
      path: '/notes/:noteId/attachments/:id',
      auth: true,
      handler: 'crud',
      entity: 'note_attachments',
      operation: 'delete',
      description: 'Delete attachment',
    },

    // Note Versions
    {
      method: 'GET',
      path: '/notes/:id/versions',
      auth: true,
      handler: 'crud',
      entity: 'note_versions',
      operation: 'list',
      description: 'Get note versions',
    },
    {
      method: 'GET',
      path: '/notes/:noteId/versions/:versionId',
      auth: true,
      handler: 'crud',
      entity: 'note_versions',
      operation: 'get',
      description: 'Get specific version',
    },
    {
      method: 'POST',
      path: '/notes/:id/restore/:versionId',
      auth: true,
      handler: 'custom',
      entity: 'note_versions',
      description: 'Restore note to version',
    },

    // Note Templates
    {
      method: 'GET',
      path: '/note-templates',
      auth: true,
      handler: 'crud',
      entity: 'note_templates',
      operation: 'list',
      description: 'List note templates',
    },
    {
      method: 'GET',
      path: '/note-templates/:id',
      auth: true,
      handler: 'crud',
      entity: 'note_templates',
      operation: 'get',
      description: 'Get note template',
    },
    {
      method: 'POST',
      path: '/note-templates',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'note_templates',
      operation: 'create',
      description: 'Create note template',
    },
    {
      method: 'PUT',
      path: '/note-templates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'note_templates',
      operation: 'update',
      description: 'Update note template',
    },
    {
      method: 'DELETE',
      path: '/note-templates/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'note_templates',
      operation: 'delete',
      description: 'Delete note template',
    },

    // Create note from template
    {
      method: 'POST',
      path: '/notes/from-template/:templateId',
      auth: true,
      handler: 'custom',
      entity: 'notes',
      description: 'Create note from template',
    },
  ],

  config: [
    {
      key: 'enableRichTextEditor',
      label: 'Enable Rich Text Editor',
      type: 'boolean',
      default: true,
      description: 'Use rich text editor for notes',
    },
    {
      key: 'enableVersionHistory',
      label: 'Enable Version History',
      type: 'boolean',
      default: true,
      description: 'Track version history for notes',
    },
    {
      key: 'maxVersions',
      label: 'Max Versions to Keep',
      type: 'number',
      default: 20,
      description: 'Maximum number of versions to retain per note',
    },
    {
      key: 'autoSaveInterval',
      label: 'Auto-save Interval (seconds)',
      type: 'number',
      default: 30,
      description: 'Auto-save interval when editing notes',
    },
    {
      key: 'enableAttachments',
      label: 'Enable Attachments',
      type: 'boolean',
      default: true,
      description: 'Allow file attachments on notes',
    },
    {
      key: 'maxAttachmentSize',
      label: 'Max Attachment Size (MB)',
      type: 'number',
      default: 25,
      description: 'Maximum file size for attachments',
    },
    {
      key: 'defaultPrivacy',
      label: 'Default Note Privacy',
      type: 'select',
      default: 'team',
      options: [
        { value: 'private', label: 'Private (only me)' },
        { value: 'team', label: 'Team (matter team)' },
        { value: 'firm', label: 'Firm-wide' },
      ],
      description: 'Default visibility for new notes',
    },
    {
      key: 'enableQuickNotes',
      label: 'Enable Quick Notes',
      type: 'boolean',
      default: true,
      description: 'Allow quick note creation from case view',
    },
  ],
};
