/**
 * Lease Management Feature Definition
 *
 * Rental lease management for property management applications.
 * Supports lease creation, tracking, renewals, and document management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const LEASE_MANAGEMENT_FEATURE: FeatureDefinition = {
  id: 'lease-management',
  name: 'Lease Management',
  category: 'real-estate',
  description: 'Manage rental leases with terms, renewals, documents, and tenant information',
  icon: 'file-contract',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'lease',
    'leases',
    'lease management',
    'rental agreement',
    'rental contract',
    'lease agreement',
    'lease terms',
    'lease renewal',
    'lease expiration',
    'tenant lease',
    'commercial lease',
    'residential lease',
    'lease tracking',
    'move in',
    'move out',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'property-listings', 'documents'],
  conflicts: [],

  pages: [
    {
      id: 'leases-list',
      route: '/leases',
      section: 'frontend',
      title: 'Leases',
      authRequired: true,
      templateId: 'leases-list',
      components: [
        'leases-table',
        'lease-card',
        'lease-filters',
        'lease-status-badges',
        'expiration-alerts',
        'quick-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'lease-detail',
      route: '/leases/:id',
      section: 'frontend',
      title: 'Lease Details',
      authRequired: true,
      templateId: 'lease-detail',
      components: [
        'lease-header',
        'lease-summary',
        'tenant-info',
        'lease-terms',
        'rent-schedule',
        'lease-documents',
        'payment-history',
        'lease-timeline',
        'renewal-options',
      ],
      layout: 'default',
    },
    {
      id: 'lease-create',
      route: '/leases/new',
      section: 'frontend',
      title: 'Create Lease',
      authRequired: true,
      roles: ['agent', 'admin', 'owner'],
      templateId: 'lease-create',
      components: [
        'lease-form',
        'property-selector',
        'tenant-selector',
        'lease-term-picker',
        'rent-configuration',
        'deposit-configuration',
        'lease-clauses',
        'document-upload',
      ],
      layout: 'default',
    },
    {
      id: 'lease-edit',
      route: '/leases/:id/edit',
      section: 'frontend',
      title: 'Edit Lease',
      authRequired: true,
      roles: ['agent', 'admin', 'owner'],
      templateId: 'lease-edit',
      components: [
        'lease-form',
        'tenant-selector',
        'lease-term-picker',
        'rent-configuration',
        'deposit-configuration',
        'lease-clauses',
        'document-upload',
        'amendment-log',
      ],
      layout: 'default',
    },
    {
      id: 'renewal-tracker',
      route: '/leases/renewals',
      section: 'frontend',
      title: 'Lease Renewals',
      authRequired: true,
      templateId: 'renewal-tracker',
      components: [
        'renewals-list',
        'renewal-card',
        'expiring-soon',
        'renewal-offers',
        'renewal-analytics',
      ],
      layout: 'dashboard',
    },
    {
      id: 'move-in-out',
      route: '/leases/:id/move',
      section: 'frontend',
      title: 'Move-In/Out',
      authRequired: true,
      templateId: 'move-in-out',
      components: [
        'inspection-checklist',
        'condition-report',
        'photo-documentation',
        'key-tracking',
        'deposit-reconciliation',
        'final-walkthrough',
      ],
      layout: 'default',
    },
    {
      id: 'admin-leases',
      route: '/admin/leases',
      section: 'admin',
      title: 'Manage Leases',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-leases',
      components: [
        'leases-table',
        'lease-analytics',
        'bulk-actions',
        'lease-templates',
        'compliance-check',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'leases-table',
    'lease-card',
    'lease-filters',
    'lease-status-badges',
    'expiration-alerts',
    'quick-actions',

    // Detail components
    'lease-header',
    'lease-summary',
    'tenant-info',
    'lease-terms',
    'rent-schedule',
    'lease-documents',
    'payment-history',
    'lease-timeline',
    'renewal-options',

    // Form components
    'lease-form',
    'property-selector',
    'tenant-selector',
    'lease-term-picker',
    'rent-configuration',
    'deposit-configuration',
    'lease-clauses',
    'document-upload',
    'amendment-log',

    // Renewal components
    'renewals-list',
    'renewal-card',
    'expiring-soon',
    'renewal-offers',
    'renewal-analytics',

    // Move-in/out components
    'inspection-checklist',
    'condition-report',
    'photo-documentation',
    'key-tracking',
    'deposit-reconciliation',
    'final-walkthrough',

    // Admin components
    'lease-analytics',
    'bulk-actions',
    'lease-templates',
    'compliance-check',
  ],

  entities: [
    {
      name: 'leases',
      displayName: 'Leases',
      description: 'Lease agreement records',
      isCore: true,
    },
    {
      name: 'lease_terms',
      displayName: 'Lease Terms',
      description: 'Individual lease terms and clauses',
      isCore: true,
    },
    {
      name: 'rent_payments',
      displayName: 'Rent Payments',
      description: 'Rent payment records for leases',
      isCore: true,
    },
    {
      name: 'lease_documents',
      displayName: 'Lease Documents',
      description: 'Documents attached to leases',
      isCore: false,
    },
    {
      name: 'lease_renewals',
      displayName: 'Lease Renewals',
      description: 'Lease renewal offers and history',
      isCore: false,
    },
    {
      name: 'inspections',
      displayName: 'Inspections',
      description: 'Move-in/out inspection records',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Leases CRUD
    {
      method: 'GET',
      path: '/leases',
      auth: true,
      handler: 'crud',
      entity: 'leases',
      operation: 'list',
      description: 'List all leases',
    },
    {
      method: 'GET',
      path: '/leases/:id',
      auth: true,
      handler: 'crud',
      entity: 'leases',
      operation: 'get',
      description: 'Get lease details',
    },
    {
      method: 'POST',
      path: '/leases',
      auth: true,
      handler: 'crud',
      entity: 'leases',
      operation: 'create',
      description: 'Create new lease',
    },
    {
      method: 'PUT',
      path: '/leases/:id',
      auth: true,
      handler: 'crud',
      entity: 'leases',
      operation: 'update',
      description: 'Update lease',
    },
    {
      method: 'DELETE',
      path: '/leases/:id',
      auth: true,
      handler: 'crud',
      entity: 'leases',
      operation: 'delete',
      description: 'Delete lease',
    },

    // Lease actions
    {
      method: 'POST',
      path: '/leases/:id/activate',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Activate lease',
    },
    {
      method: 'POST',
      path: '/leases/:id/terminate',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Terminate lease',
    },
    {
      method: 'POST',
      path: '/leases/:id/amend',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Amend lease terms',
    },

    // Lease Terms
    {
      method: 'GET',
      path: '/leases/:id/terms',
      auth: true,
      handler: 'crud',
      entity: 'lease_terms',
      operation: 'list',
      description: 'Get lease terms',
    },
    {
      method: 'PUT',
      path: '/leases/:id/terms',
      auth: true,
      handler: 'custom',
      entity: 'lease_terms',
      description: 'Update lease terms',
    },

    // Rent Payments
    {
      method: 'GET',
      path: '/leases/:id/payments',
      auth: true,
      handler: 'crud',
      entity: 'rent_payments',
      operation: 'list',
      description: 'Get lease payments',
    },
    {
      method: 'POST',
      path: '/leases/:id/payments',
      auth: true,
      handler: 'crud',
      entity: 'rent_payments',
      operation: 'create',
      description: 'Record payment',
    },
    {
      method: 'GET',
      path: '/leases/:id/rent-schedule',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Get rent schedule',
    },

    // Lease Documents
    {
      method: 'GET',
      path: '/leases/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'lease_documents',
      operation: 'list',
      description: 'Get lease documents',
    },
    {
      method: 'POST',
      path: '/leases/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'lease_documents',
      operation: 'create',
      description: 'Upload lease document',
    },
    {
      method: 'DELETE',
      path: '/leases/:leaseId/documents/:id',
      auth: true,
      handler: 'crud',
      entity: 'lease_documents',
      operation: 'delete',
      description: 'Delete lease document',
    },

    // Lease Renewals
    {
      method: 'GET',
      path: '/leases/renewals',
      auth: true,
      handler: 'crud',
      entity: 'lease_renewals',
      operation: 'list',
      description: 'List lease renewals',
    },
    {
      method: 'GET',
      path: '/leases/expiring',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Get expiring leases',
    },
    {
      method: 'POST',
      path: '/leases/:id/renewal-offer',
      auth: true,
      handler: 'custom',
      entity: 'lease_renewals',
      description: 'Send renewal offer',
    },
    {
      method: 'POST',
      path: '/leases/:id/renew',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Renew lease',
    },

    // Inspections
    {
      method: 'GET',
      path: '/leases/:id/inspections',
      auth: true,
      handler: 'crud',
      entity: 'inspections',
      operation: 'list',
      description: 'Get lease inspections',
    },
    {
      method: 'POST',
      path: '/leases/:id/move-in',
      auth: true,
      handler: 'custom',
      entity: 'inspections',
      description: 'Record move-in inspection',
    },
    {
      method: 'POST',
      path: '/leases/:id/move-out',
      auth: true,
      handler: 'custom',
      entity: 'inspections',
      description: 'Record move-out inspection',
    },

    // Property leases
    {
      method: 'GET',
      path: '/properties/:id/leases',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Get leases for property',
    },
    {
      method: 'GET',
      path: '/properties/:id/current-lease',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Get current active lease',
    },

    // Tenant leases
    {
      method: 'GET',
      path: '/tenants/:id/leases',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Get leases for tenant',
    },

    // Analytics
    {
      method: 'GET',
      path: '/leases/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'leases',
      description: 'Get lease analytics',
    },

    // Templates
    {
      method: 'GET',
      path: '/lease-templates',
      auth: true,
      handler: 'custom',
      entity: 'leases',
      description: 'Get lease templates',
    },
    {
      method: 'POST',
      path: '/leases/:id/generate-document',
      auth: true,
      handler: 'custom',
      entity: 'lease_documents',
      description: 'Generate lease document from template',
    },
  ],

  config: [
    {
      key: 'defaultLeaseTermMonths',
      label: 'Default Lease Term (months)',
      type: 'number',
      default: 12,
      description: 'Default lease duration',
    },
    {
      key: 'renewalNoticedays',
      label: 'Renewal Notice Period (days)',
      type: 'number',
      default: 60,
      description: 'Days before expiration to send renewal notice',
    },
    {
      key: 'lateFeeGracePeriod',
      label: 'Late Fee Grace Period (days)',
      type: 'number',
      default: 5,
      description: 'Days before late fee applies',
    },
    {
      key: 'lateFeeType',
      label: 'Late Fee Type',
      type: 'select',
      default: 'flat',
      options: [
        { value: 'flat', label: 'Flat Fee' },
        { value: 'percentage', label: 'Percentage of Rent' },
        { value: 'daily', label: 'Daily Fee' },
      ],
      description: 'How late fees are calculated',
    },
    {
      key: 'lateFeeAmount',
      label: 'Late Fee Amount',
      type: 'number',
      default: 50,
      description: 'Late fee amount (or percentage)',
    },
    {
      key: 'securityDepositMonths',
      label: 'Security Deposit (months of rent)',
      type: 'number',
      default: 1,
      description: 'Security deposit in months of rent',
    },
    {
      key: 'requireMoveInInspection',
      label: 'Require Move-In Inspection',
      type: 'boolean',
      default: true,
      description: 'Require documented move-in inspection',
    },
    {
      key: 'requireMoveOutInspection',
      label: 'Require Move-Out Inspection',
      type: 'boolean',
      default: true,
      description: 'Require documented move-out inspection',
    },
    {
      key: 'autoRenewal',
      label: 'Enable Auto-Renewal',
      type: 'boolean',
      default: false,
      description: 'Automatically renew leases',
    },
    {
      key: 'eSignatureRequired',
      label: 'Require E-Signature',
      type: 'boolean',
      default: true,
      description: 'Require electronic signature on leases',
    },
  ],
};
