/**
 * Maintenance Requests Feature Definition
 *
 * Property maintenance request and work order management for property management.
 * Supports tenant requests, vendor assignment, work orders, and tracking.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const MAINTENANCE_REQUESTS_FEATURE: FeatureDefinition = {
  id: 'maintenance-requests',
  name: 'Maintenance Requests',
  category: 'real-estate',
  description: 'Manage property maintenance requests, work orders, and vendor assignments',
  icon: 'wrench',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'maintenance',
    'maintenance request',
    'work order',
    'repair',
    'repair request',
    'fix request',
    'property maintenance',
    'tenant request',
    'service request',
    'maintenance ticket',
    'vendor management',
    'contractor',
    'handyman',
    'facility maintenance',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'property-listings', 'file-upload'],
  conflicts: [],

  pages: [
    {
      id: 'maintenance-list',
      route: '/maintenance',
      section: 'frontend',
      title: 'Maintenance Requests',
      authRequired: true,
      templateId: 'maintenance-list',
      components: [
        'requests-list',
        'request-card',
        'request-filters',
        'priority-badges',
        'status-tracker',
        'quick-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'work-order-detail',
      route: '/maintenance/:id',
      section: 'frontend',
      title: 'Work Order Details',
      authRequired: true,
      templateId: 'work-order-detail',
      components: [
        'work-order-header',
        'request-info',
        'photo-gallery',
        'vendor-info',
        'work-timeline',
        'cost-summary',
        'communication-log',
        'status-update',
      ],
      layout: 'default',
    },
    {
      id: 'submit-request',
      route: '/maintenance/new',
      section: 'frontend',
      title: 'Submit Request',
      authRequired: true,
      templateId: 'submit-request',
      components: [
        'request-form',
        'category-selector',
        'priority-selector',
        'location-picker',
        'photo-upload',
        'availability-picker',
        'request-summary',
      ],
      layout: 'default',
    },
    {
      id: 'vendor-management',
      route: '/maintenance/vendors',
      section: 'frontend',
      title: 'Vendor Management',
      authRequired: true,
      roles: ['admin', 'owner'],
      templateId: 'vendor-management',
      components: [
        'vendors-list',
        'vendor-card',
        'vendor-form',
        'vendor-categories',
        'vendor-ratings',
        'vendor-availability',
      ],
      layout: 'dashboard',
    },
    {
      id: 'vendor-detail',
      route: '/maintenance/vendors/:id',
      section: 'frontend',
      title: 'Vendor Details',
      authRequired: true,
      templateId: 'vendor-detail',
      components: [
        'vendor-header',
        'vendor-info',
        'work-history',
        'performance-stats',
        'reviews-list',
        'contact-info',
      ],
      layout: 'default',
    },
    {
      id: 'admin-maintenance',
      route: '/admin/maintenance',
      section: 'admin',
      title: 'Maintenance Management',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-maintenance',
      components: [
        'maintenance-overview',
        'requests-table',
        'work-orders-queue',
        'vendor-assign',
        'cost-tracking',
        'maintenance-analytics',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // List components
    'requests-list',
    'request-card',
    'work-order-card',
    'request-filters',
    'priority-badges',
    'status-tracker',
    'quick-actions',

    // Detail components
    'work-order-header',
    'request-info',
    'photo-gallery',
    'vendor-info',
    'work-timeline',
    'cost-summary',
    'communication-log',
    'status-update',
    'photo-upload',

    // Form components
    'request-form',
    'category-selector',
    'priority-selector',
    'location-picker',
    'availability-picker',
    'request-summary',

    // Vendor components
    'vendors-list',
    'vendor-card',
    'vendor-form',
    'vendor-categories',
    'vendor-ratings',
    'vendor-availability',
    'vendor-header',
    'work-history',
    'performance-stats',
    'reviews-list',
    'contact-info',
    'vendor-assign',

    // Admin components
    'maintenance-overview',
    'requests-table',
    'work-orders-queue',
    'cost-tracking',
    'maintenance-analytics',
  ],

  entities: [
    {
      name: 'maintenance_requests',
      displayName: 'Maintenance Requests',
      description: 'Tenant maintenance requests',
      isCore: true,
    },
    {
      name: 'work_orders',
      displayName: 'Work Orders',
      description: 'Work orders for maintenance',
      isCore: true,
    },
    {
      name: 'vendors',
      displayName: 'Vendors',
      description: 'Maintenance vendors and contractors',
      isCore: true,
    },
    {
      name: 'maintenance_photos',
      displayName: 'Maintenance Photos',
      description: 'Photos attached to requests',
      isCore: false,
    },
    {
      name: 'maintenance_comments',
      displayName: 'Maintenance Comments',
      description: 'Communication on requests',
      isCore: false,
    },
    {
      name: 'vendor_reviews',
      displayName: 'Vendor Reviews',
      description: 'Reviews for vendors',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Maintenance Requests CRUD
    {
      method: 'GET',
      path: '/maintenance-requests',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_requests',
      operation: 'list',
      description: 'List maintenance requests',
    },
    {
      method: 'GET',
      path: '/maintenance-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_requests',
      operation: 'get',
      description: 'Get request details',
    },
    {
      method: 'POST',
      path: '/maintenance-requests',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_requests',
      operation: 'create',
      description: 'Submit maintenance request',
    },
    {
      method: 'PUT',
      path: '/maintenance-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_requests',
      operation: 'update',
      description: 'Update request',
    },
    {
      method: 'DELETE',
      path: '/maintenance-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_requests',
      operation: 'delete',
      description: 'Delete request',
    },

    // Request actions
    {
      method: 'PUT',
      path: '/maintenance-requests/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'maintenance_requests',
      description: 'Update request status',
    },
    {
      method: 'PUT',
      path: '/maintenance-requests/:id/priority',
      auth: true,
      handler: 'custom',
      entity: 'maintenance_requests',
      description: 'Update request priority',
    },
    {
      method: 'POST',
      path: '/maintenance-requests/:id/assign',
      auth: true,
      handler: 'custom',
      entity: 'maintenance_requests',
      description: 'Assign to vendor',
    },

    // Work Orders
    {
      method: 'GET',
      path: '/work-orders',
      auth: true,
      handler: 'crud',
      entity: 'work_orders',
      operation: 'list',
      description: 'List work orders',
    },
    {
      method: 'GET',
      path: '/work-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'work_orders',
      operation: 'get',
      description: 'Get work order details',
    },
    {
      method: 'POST',
      path: '/work-orders',
      auth: true,
      handler: 'crud',
      entity: 'work_orders',
      operation: 'create',
      description: 'Create work order',
    },
    {
      method: 'PUT',
      path: '/work-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'work_orders',
      operation: 'update',
      description: 'Update work order',
    },
    {
      method: 'POST',
      path: '/work-orders/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'work_orders',
      description: 'Mark work order complete',
    },
    {
      method: 'POST',
      path: '/work-orders/:id/invoice',
      auth: true,
      handler: 'custom',
      entity: 'work_orders',
      description: 'Add invoice to work order',
    },

    // Vendors CRUD
    {
      method: 'GET',
      path: '/vendors',
      auth: true,
      handler: 'crud',
      entity: 'vendors',
      operation: 'list',
      description: 'List vendors',
    },
    {
      method: 'GET',
      path: '/vendors/:id',
      auth: true,
      handler: 'crud',
      entity: 'vendors',
      operation: 'get',
      description: 'Get vendor details',
    },
    {
      method: 'POST',
      path: '/vendors',
      auth: true,
      handler: 'crud',
      entity: 'vendors',
      operation: 'create',
      description: 'Add vendor',
    },
    {
      method: 'PUT',
      path: '/vendors/:id',
      auth: true,
      handler: 'crud',
      entity: 'vendors',
      operation: 'update',
      description: 'Update vendor',
    },
    {
      method: 'DELETE',
      path: '/vendors/:id',
      auth: true,
      handler: 'crud',
      entity: 'vendors',
      operation: 'delete',
      description: 'Remove vendor',
    },
    {
      method: 'GET',
      path: '/vendors/:id/work-orders',
      auth: true,
      handler: 'custom',
      entity: 'work_orders',
      description: 'Get vendor work orders',
    },

    // Photos
    {
      method: 'GET',
      path: '/maintenance-requests/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_photos',
      operation: 'list',
      description: 'Get request photos',
    },
    {
      method: 'POST',
      path: '/maintenance-requests/:id/photos',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_photos',
      operation: 'create',
      description: 'Upload photo',
    },
    {
      method: 'DELETE',
      path: '/maintenance-requests/:requestId/photos/:id',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_photos',
      operation: 'delete',
      description: 'Delete photo',
    },

    // Comments
    {
      method: 'GET',
      path: '/maintenance-requests/:id/comments',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_comments',
      operation: 'list',
      description: 'Get request comments',
    },
    {
      method: 'POST',
      path: '/maintenance-requests/:id/comments',
      auth: true,
      handler: 'crud',
      entity: 'maintenance_comments',
      operation: 'create',
      description: 'Add comment',
    },

    // Vendor Reviews
    {
      method: 'GET',
      path: '/vendors/:id/reviews',
      auth: true,
      handler: 'crud',
      entity: 'vendor_reviews',
      operation: 'list',
      description: 'Get vendor reviews',
    },
    {
      method: 'POST',
      path: '/vendors/:id/reviews',
      auth: true,
      handler: 'crud',
      entity: 'vendor_reviews',
      operation: 'create',
      description: 'Add vendor review',
    },

    // Property maintenance
    {
      method: 'GET',
      path: '/properties/:id/maintenance',
      auth: true,
      handler: 'custom',
      entity: 'maintenance_requests',
      description: 'Get property maintenance requests',
    },

    // Analytics
    {
      method: 'GET',
      path: '/maintenance/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'maintenance_requests',
      description: 'Get maintenance analytics',
    },
    {
      method: 'GET',
      path: '/maintenance/costs',
      auth: true,
      handler: 'aggregate',
      entity: 'work_orders',
      description: 'Get maintenance cost summary',
    },

    // Categories
    {
      method: 'GET',
      path: '/maintenance/categories',
      auth: true,
      handler: 'custom',
      entity: 'maintenance_requests',
      description: 'Get maintenance categories',
    },
  ],

  config: [
    {
      key: 'allowTenantRequests',
      label: 'Allow Tenant Requests',
      type: 'boolean',
      default: true,
      description: 'Allow tenants to submit maintenance requests',
    },
    {
      key: 'requirePhotos',
      label: 'Require Photos',
      type: 'boolean',
      default: false,
      description: 'Require photos with maintenance requests',
    },
    {
      key: 'autoAssignVendor',
      label: 'Auto-Assign Vendors',
      type: 'boolean',
      default: false,
      description: 'Automatically assign vendors based on category',
    },
    {
      key: 'emergencyContactEnabled',
      label: 'Enable Emergency Contact',
      type: 'boolean',
      default: true,
      description: 'Enable emergency maintenance contact',
    },
    {
      key: 'notifyOnNewRequest',
      label: 'Notify on New Request',
      type: 'boolean',
      default: true,
      description: 'Send notification when new request submitted',
    },
    {
      key: 'notifyOnStatusChange',
      label: 'Notify on Status Change',
      type: 'boolean',
      default: true,
      description: 'Send notification when status changes',
    },
    {
      key: 'defaultPriority',
      label: 'Default Priority',
      type: 'select',
      default: 'normal',
      options: [
        { value: 'low', label: 'Low' },
        { value: 'normal', label: 'Normal' },
        { value: 'high', label: 'High' },
        { value: 'urgent', label: 'Urgent' },
      ],
      description: 'Default priority for new requests',
    },
    {
      key: 'responseTimeHours',
      label: 'Response Time Target (hours)',
      type: 'number',
      default: 24,
      description: 'Target response time in hours',
    },
    {
      key: 'resolutionTimeDays',
      label: 'Resolution Time Target (days)',
      type: 'number',
      default: 7,
      description: 'Target resolution time in days',
    },
    {
      key: 'enableCostTracking',
      label: 'Enable Cost Tracking',
      type: 'boolean',
      default: true,
      description: 'Track maintenance costs',
    },
    {
      key: 'requireApprovalAbove',
      label: 'Require Approval Above Amount',
      type: 'number',
      default: 500,
      description: 'Require approval for costs above this amount',
    },
  ],
};
