/**
 * MLS Integration Feature Definition
 *
 * Multiple Listing Service (MLS) feed integration for real estate applications.
 * Supports importing, syncing, and managing listings from MLS data feeds.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const MLS_INTEGRATION_FEATURE: FeatureDefinition = {
  id: 'mls-integration',
  name: 'MLS Integration',
  category: 'real-estate',
  description: 'Import and sync property listings from MLS data feeds',
  icon: 'cloud-sync',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'mls',
    'mls integration',
    'mls feed',
    'mls sync',
    'rets',
    'reso',
    'idx',
    'idx integration',
    'listing sync',
    'listing import',
    'data feed',
    'property feed',
    'real estate feed',
    'multiple listing service',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth', 'property-listings'],
  conflicts: [],

  pages: [
    {
      id: 'mls-dashboard',
      route: '/admin/mls',
      section: 'admin',
      title: 'MLS Dashboard',
      authRequired: true,
      roles: ['admin'],
      templateId: 'mls-dashboard',
      components: [
        'mls-overview',
        'sync-status-card',
        'feed-health-monitor',
        'recent-syncs',
        'sync-schedule',
        'error-log',
      ],
      layout: 'admin',
    },
    {
      id: 'mls-import',
      route: '/admin/mls/import',
      section: 'admin',
      title: 'Import Listings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'mls-import',
      components: [
        'import-wizard',
        'import-mapper',
        'field-mapping-table',
        'listing-preview',
        'import-progress',
        'import-results',
      ],
      layout: 'admin',
    },
    {
      id: 'sync-settings',
      route: '/admin/mls/settings',
      section: 'admin',
      title: 'Sync Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'sync-settings',
      components: [
        'feed-configuration',
        'sync-schedule-editor',
        'field-mapping-editor',
        'filter-rules',
        'webhook-settings',
        'api-credentials',
      ],
      layout: 'admin',
    },
    {
      id: 'mls-feeds',
      route: '/admin/mls/feeds',
      section: 'admin',
      title: 'Manage Feeds',
      authRequired: true,
      roles: ['admin'],
      templateId: 'mls-feeds',
      components: [
        'feeds-list',
        'feed-form',
        'feed-test',
        'feed-status',
      ],
      layout: 'admin',
    },
    {
      id: 'sync-history',
      route: '/admin/mls/history',
      section: 'admin',
      title: 'Sync History',
      authRequired: true,
      roles: ['admin'],
      templateId: 'sync-history',
      components: [
        'sync-history-table',
        'sync-detail-modal',
        'sync-stats',
        'error-resolution',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'mls-overview',
    'sync-status-card',
    'feed-health-monitor',
    'recent-syncs',
    'sync-schedule',
    'error-log',

    // Import components
    'import-wizard',
    'import-mapper',
    'field-mapping-table',
    'listing-preview',
    'import-progress',
    'import-results',

    // Settings components
    'feed-configuration',
    'sync-schedule-editor',
    'field-mapping-editor',
    'filter-rules',
    'webhook-settings',
    'api-credentials',

    // Feed management components
    'feeds-list',
    'feed-form',
    'feed-test',
    'feed-status',
    'mls-sync-status',

    // History components
    'sync-history-table',
    'sync-detail-modal',
    'sync-stats',
    'error-resolution',
  ],

  entities: [
    {
      name: 'mls_feeds',
      displayName: 'MLS Feeds',
      description: 'MLS feed configurations',
      isCore: true,
    },
    {
      name: 'mls_listings',
      displayName: 'MLS Listings',
      description: 'Raw listings from MLS feeds',
      isCore: true,
    },
    {
      name: 'sync_logs',
      displayName: 'Sync Logs',
      description: 'Sync operation history and logs',
      isCore: true,
    },
    {
      name: 'field_mappings',
      displayName: 'Field Mappings',
      description: 'MLS to property field mappings',
      isCore: false,
    },
    {
      name: 'sync_errors',
      displayName: 'Sync Errors',
      description: 'Errors encountered during syncs',
      isCore: false,
    },
  ],

  apiRoutes: [
    // MLS Feeds CRUD
    {
      method: 'GET',
      path: '/mls/feeds',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'mls_feeds',
      operation: 'list',
      description: 'List all MLS feeds',
    },
    {
      method: 'GET',
      path: '/mls/feeds/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'mls_feeds',
      operation: 'get',
      description: 'Get feed details',
    },
    {
      method: 'POST',
      path: '/mls/feeds',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'mls_feeds',
      operation: 'create',
      description: 'Create new MLS feed',
    },
    {
      method: 'PUT',
      path: '/mls/feeds/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'mls_feeds',
      operation: 'update',
      description: 'Update MLS feed',
    },
    {
      method: 'DELETE',
      path: '/mls/feeds/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'mls_feeds',
      operation: 'delete',
      description: 'Delete MLS feed',
    },

    // Feed operations
    {
      method: 'POST',
      path: '/mls/feeds/:id/test',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'mls_feeds',
      description: 'Test feed connection',
    },
    {
      method: 'POST',
      path: '/mls/feeds/:id/sync',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'mls_feeds',
      description: 'Trigger manual sync',
    },
    {
      method: 'GET',
      path: '/mls/feeds/:id/status',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'mls_feeds',
      description: 'Get feed sync status',
    },

    // MLS Listings
    {
      method: 'GET',
      path: '/mls/listings',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'mls_listings',
      operation: 'list',
      description: 'List MLS listings',
    },
    {
      method: 'GET',
      path: '/mls/listings/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'mls_listings',
      operation: 'get',
      description: 'Get MLS listing details',
    },
    {
      method: 'POST',
      path: '/mls/listings/:id/import',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'mls_listings',
      description: 'Import MLS listing to properties',
    },
    {
      method: 'POST',
      path: '/mls/listings/bulk-import',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'mls_listings',
      description: 'Bulk import MLS listings',
    },

    // Sync Logs
    {
      method: 'GET',
      path: '/mls/sync-logs',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'sync_logs',
      operation: 'list',
      description: 'List sync logs',
    },
    {
      method: 'GET',
      path: '/mls/sync-logs/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'sync_logs',
      operation: 'get',
      description: 'Get sync log details',
    },

    // Field Mappings
    {
      method: 'GET',
      path: '/mls/feeds/:id/mappings',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'field_mappings',
      operation: 'list',
      description: 'Get field mappings for feed',
    },
    {
      method: 'PUT',
      path: '/mls/feeds/:id/mappings',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'field_mappings',
      description: 'Update field mappings',
    },

    // Sync Errors
    {
      method: 'GET',
      path: '/mls/errors',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'sync_errors',
      operation: 'list',
      description: 'List sync errors',
    },
    {
      method: 'PUT',
      path: '/mls/errors/:id/resolve',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'sync_errors',
      description: 'Mark error as resolved',
    },
    {
      method: 'POST',
      path: '/mls/errors/:id/retry',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'sync_errors',
      description: 'Retry failed operation',
    },

    // Dashboard stats
    {
      method: 'GET',
      path: '/mls/stats',
      auth: true,
      role: 'admin',
      handler: 'aggregate',
      entity: 'sync_logs',
      description: 'Get MLS sync statistics',
    },

    // Webhooks
    {
      method: 'POST',
      path: '/mls/webhook',
      auth: false,
      handler: 'custom',
      entity: 'mls_listings',
      description: 'Receive MLS webhook updates',
    },
  ],

  config: [
    {
      key: 'autoSync',
      label: 'Enable Auto-Sync',
      type: 'boolean',
      default: true,
      description: 'Automatically sync MLS listings on schedule',
    },
    {
      key: 'syncInterval',
      label: 'Sync Interval (minutes)',
      type: 'number',
      default: 60,
      description: 'How often to sync with MLS feeds',
    },
    {
      key: 'autoPublish',
      label: 'Auto-Publish Imported Listings',
      type: 'boolean',
      default: false,
      description: 'Automatically publish imported listings',
    },
    {
      key: 'retainDeletedListings',
      label: 'Retain Deleted Listings (days)',
      type: 'number',
      default: 30,
      description: 'Days to keep listings deleted from MLS',
    },
    {
      key: 'importImages',
      label: 'Import Images',
      type: 'boolean',
      default: true,
      description: 'Download and import listing images',
    },
    {
      key: 'overwriteManualEdits',
      label: 'Overwrite Manual Edits',
      type: 'boolean',
      default: false,
      description: 'Overwrite manual edits during sync',
    },
    {
      key: 'feedFormat',
      label: 'Default Feed Format',
      type: 'select',
      default: 'reso',
      options: [
        { value: 'reso', label: 'RESO Web API' },
        { value: 'rets', label: 'RETS (Legacy)' },
        { value: 'xml', label: 'XML Feed' },
        { value: 'csv', label: 'CSV Import' },
      ],
      description: 'Default MLS feed format',
    },
    {
      key: 'notifyOnError',
      label: 'Notify on Sync Errors',
      type: 'boolean',
      default: true,
      description: 'Send notifications when sync errors occur',
    },
  ],
};
