/**
 * Open Houses Feature Definition
 *
 * Open house event management for real estate applications.
 * Supports event scheduling, visitor sign-in, and follow-up management.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const OPEN_HOUSES_FEATURE: FeatureDefinition = {
  id: 'open-houses',
  name: 'Open Houses',
  category: 'real-estate',
  description: 'Manage open house events with scheduling, visitor sign-in, and follow-up tracking',
  icon: 'door-open',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'open house',
    'open houses',
    'open home',
    'property event',
    'house event',
    'visitor sign in',
    'sign in sheet',
    'visitor registration',
    'open house sign in',
    'open house event',
    'broker open',
    'caravan',
    'property showing event',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth', 'property-listings', 'calendar'],
  conflicts: [],

  pages: [
    {
      id: 'open-house-calendar',
      route: '/open-houses',
      section: 'frontend',
      title: 'Open House Calendar',
      authRequired: true,
      templateId: 'open-house-calendar',
      components: [
        'open-house-calendar-view',
        'event-card',
        'upcoming-events',
        'event-filters',
        'create-event-button',
        'calendar-sync',
      ],
      layout: 'dashboard',
    },
    {
      id: 'event-detail',
      route: '/open-houses/:id',
      section: 'frontend',
      title: 'Open House Details',
      authRequired: true,
      templateId: 'event-detail',
      components: [
        'event-header',
        'event-info',
        'property-preview',
        'visitor-list',
        'visitor-stats',
        'follow-up-status',
        'event-actions',
        'share-event',
      ],
      layout: 'default',
    },
    {
      id: 'create-event',
      route: '/open-houses/new',
      section: 'frontend',
      title: 'Create Open House',
      authRequired: true,
      roles: ['agent', 'admin', 'owner'],
      templateId: 'create-event',
      components: [
        'event-form',
        'property-selector',
        'date-time-picker',
        'duration-picker',
        'marketing-options',
        'sign-in-settings',
        'notification-settings',
      ],
      layout: 'default',
    },
    {
      id: 'visitor-sign-in',
      route: '/open-houses/:id/sign-in',
      section: 'frontend',
      title: 'Visitor Sign-In',
      authRequired: false,
      templateId: 'visitor-sign-in',
      components: [
        'sign-in-kiosk',
        'visitor-registration',
        'contact-form',
        'interest-survey',
        'disclosure-form',
        'thank-you-message',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'follow-up-list',
      route: '/open-houses/follow-ups',
      section: 'frontend',
      title: 'Follow-Ups',
      authRequired: true,
      templateId: 'follow-up-list',
      components: [
        'follow-up-table',
        'follow-up-card',
        'follow-up-filters',
        'priority-badges',
        'quick-actions',
        'email-templates',
      ],
      layout: 'dashboard',
    },
    {
      id: 'public-event',
      route: '/events/:slug',
      section: 'frontend',
      title: 'Open House',
      authRequired: false,
      templateId: 'public-event',
      components: [
        'public-event-header',
        'property-preview',
        'event-details',
        'rsvp-form',
        'directions-map',
        'agent-contact',
      ],
      layout: 'default',
    },
    {
      id: 'admin-open-houses',
      route: '/admin/open-houses',
      section: 'admin',
      title: 'Manage Open Houses',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-open-houses',
      components: [
        'events-table',
        'visitor-analytics',
        'agent-performance',
        'event-templates',
        'marketing-integration',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calendar components
    'open-house-calendar-view',
    'event-card',
    'upcoming-events',
    'event-filters',
    'create-event-button',
    'calendar-sync',

    // Detail components
    'event-header',
    'event-info',
    'property-preview',
    'visitor-list',
    'visitor-stats',
    'follow-up-status',
    'event-actions',
    'share-event',

    // Form components
    'event-form',
    'property-selector',
    'date-time-picker',
    'duration-picker',
    'marketing-options',
    'sign-in-settings',
    'notification-settings',

    // Sign-in components
    'sign-in-kiosk',
    'visitor-registration',
    'contact-form',
    'interest-survey',
    'disclosure-form',
    'thank-you-message',

    // Follow-up components
    'follow-up-table',
    'follow-up-card',
    'follow-up-filters',
    'priority-badges',
    'quick-actions',
    'email-templates',
    'follow-up-list',

    // Public event components
    'public-event-header',
    'event-details',
    'rsvp-form',
    'directions-map',
    'agent-contact',

    // Admin components
    'events-table',
    'visitor-analytics',
    'agent-performance',
    'event-templates',
    'marketing-integration',
  ],

  entities: [
    {
      name: 'open_houses',
      displayName: 'Open Houses',
      description: 'Open house event records',
      isCore: true,
    },
    {
      name: 'visitors',
      displayName: 'Visitors',
      description: 'Open house visitor registrations',
      isCore: true,
    },
    {
      name: 'follow_ups',
      displayName: 'Follow-Ups',
      description: 'Visitor follow-up tasks',
      isCore: true,
    },
    {
      name: 'rsvps',
      displayName: 'RSVPs',
      description: 'Event RSVPs',
      isCore: false,
    },
    {
      name: 'visitor_surveys',
      displayName: 'Visitor Surveys',
      description: 'Visitor interest surveys',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Open Houses CRUD
    {
      method: 'GET',
      path: '/open-houses',
      auth: true,
      handler: 'crud',
      entity: 'open_houses',
      operation: 'list',
      description: 'List open house events',
    },
    {
      method: 'GET',
      path: '/open-houses/:id',
      auth: false,
      handler: 'crud',
      entity: 'open_houses',
      operation: 'get',
      description: 'Get event details',
    },
    {
      method: 'POST',
      path: '/open-houses',
      auth: true,
      handler: 'crud',
      entity: 'open_houses',
      operation: 'create',
      description: 'Create open house event',
    },
    {
      method: 'PUT',
      path: '/open-houses/:id',
      auth: true,
      handler: 'crud',
      entity: 'open_houses',
      operation: 'update',
      description: 'Update event',
    },
    {
      method: 'DELETE',
      path: '/open-houses/:id',
      auth: true,
      handler: 'crud',
      entity: 'open_houses',
      operation: 'delete',
      description: 'Cancel event',
    },

    // Event actions
    {
      method: 'POST',
      path: '/open-houses/:id/publish',
      auth: true,
      handler: 'custom',
      entity: 'open_houses',
      description: 'Publish event',
    },
    {
      method: 'POST',
      path: '/open-houses/:id/unpublish',
      auth: true,
      handler: 'custom',
      entity: 'open_houses',
      description: 'Unpublish event',
    },
    {
      method: 'GET',
      path: '/open-houses/:id/share-link',
      auth: true,
      handler: 'custom',
      entity: 'open_houses',
      description: 'Get shareable link',
    },
    {
      method: 'GET',
      path: '/open-houses/:id/sign-in-qr',
      auth: true,
      handler: 'custom',
      entity: 'open_houses',
      description: 'Get sign-in QR code',
    },

    // Public event
    {
      method: 'GET',
      path: '/events/:slug',
      auth: false,
      handler: 'custom',
      entity: 'open_houses',
      description: 'Get public event page',
    },
    {
      method: 'GET',
      path: '/open-houses/upcoming',
      auth: false,
      handler: 'custom',
      entity: 'open_houses',
      description: 'Get upcoming public events',
    },

    // Visitors
    {
      method: 'GET',
      path: '/open-houses/:id/visitors',
      auth: true,
      handler: 'crud',
      entity: 'visitors',
      operation: 'list',
      description: 'Get event visitors',
    },
    {
      method: 'POST',
      path: '/open-houses/:id/visitors',
      auth: false,
      handler: 'crud',
      entity: 'visitors',
      operation: 'create',
      description: 'Register visitor',
    },
    {
      method: 'GET',
      path: '/visitors/:id',
      auth: true,
      handler: 'crud',
      entity: 'visitors',
      operation: 'get',
      description: 'Get visitor details',
    },
    {
      method: 'PUT',
      path: '/visitors/:id',
      auth: true,
      handler: 'crud',
      entity: 'visitors',
      operation: 'update',
      description: 'Update visitor info',
    },
    {
      method: 'GET',
      path: '/visitors',
      auth: true,
      handler: 'crud',
      entity: 'visitors',
      operation: 'list',
      description: 'List all visitors',
    },

    // RSVPs
    {
      method: 'GET',
      path: '/open-houses/:id/rsvps',
      auth: true,
      handler: 'crud',
      entity: 'rsvps',
      operation: 'list',
      description: 'Get event RSVPs',
    },
    {
      method: 'POST',
      path: '/open-houses/:id/rsvp',
      auth: false,
      handler: 'crud',
      entity: 'rsvps',
      operation: 'create',
      description: 'RSVP to event',
    },
    {
      method: 'DELETE',
      path: '/open-houses/:id/rsvp/:rsvpId',
      auth: false,
      handler: 'crud',
      entity: 'rsvps',
      operation: 'delete',
      description: 'Cancel RSVP',
    },

    // Follow-ups
    {
      method: 'GET',
      path: '/follow-ups',
      auth: true,
      handler: 'crud',
      entity: 'follow_ups',
      operation: 'list',
      description: 'List follow-ups',
    },
    {
      method: 'GET',
      path: '/open-houses/:id/follow-ups',
      auth: true,
      handler: 'custom',
      entity: 'follow_ups',
      description: 'Get event follow-ups',
    },
    {
      method: 'POST',
      path: '/visitors/:id/follow-up',
      auth: true,
      handler: 'crud',
      entity: 'follow_ups',
      operation: 'create',
      description: 'Create follow-up',
    },
    {
      method: 'PUT',
      path: '/follow-ups/:id',
      auth: true,
      handler: 'crud',
      entity: 'follow_ups',
      operation: 'update',
      description: 'Update follow-up',
    },
    {
      method: 'POST',
      path: '/follow-ups/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'follow_ups',
      description: 'Mark follow-up complete',
    },
    {
      method: 'POST',
      path: '/follow-ups/bulk-email',
      auth: true,
      handler: 'custom',
      entity: 'follow_ups',
      description: 'Send bulk follow-up email',
    },

    // Visitor Surveys
    {
      method: 'POST',
      path: '/visitors/:id/survey',
      auth: false,
      handler: 'crud',
      entity: 'visitor_surveys',
      operation: 'create',
      description: 'Submit visitor survey',
    },
    {
      method: 'GET',
      path: '/open-houses/:id/survey-results',
      auth: true,
      handler: 'aggregate',
      entity: 'visitor_surveys',
      description: 'Get survey results',
    },

    // Property events
    {
      method: 'GET',
      path: '/properties/:id/open-houses',
      auth: true,
      handler: 'custom',
      entity: 'open_houses',
      description: 'Get property open houses',
    },

    // Analytics
    {
      method: 'GET',
      path: '/open-houses/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'open_houses',
      description: 'Get open house analytics',
    },
    {
      method: 'GET',
      path: '/open-houses/:id/stats',
      auth: true,
      handler: 'aggregate',
      entity: 'visitors',
      description: 'Get event statistics',
    },

    // Export
    {
      method: 'GET',
      path: '/open-houses/:id/visitors/export',
      auth: true,
      handler: 'custom',
      entity: 'visitors',
      description: 'Export visitor list',
    },
  ],

  config: [
    {
      key: 'defaultDuration',
      label: 'Default Event Duration (hours)',
      type: 'number',
      default: 2,
      description: 'Default duration for open house events',
    },
    {
      key: 'requireSignIn',
      label: 'Require Visitor Sign-In',
      type: 'boolean',
      default: true,
      description: 'Require visitors to sign in',
    },
    {
      key: 'collectPhone',
      label: 'Collect Phone Numbers',
      type: 'boolean',
      default: true,
      description: 'Collect visitor phone numbers',
    },
    {
      key: 'collectEmail',
      label: 'Collect Email Addresses',
      type: 'boolean',
      default: true,
      description: 'Collect visitor email addresses',
    },
    {
      key: 'enableSurvey',
      label: 'Enable Interest Survey',
      type: 'boolean',
      default: true,
      description: 'Show interest survey to visitors',
    },
    {
      key: 'enableRSVP',
      label: 'Enable RSVP',
      type: 'boolean',
      default: true,
      description: 'Allow visitors to RSVP',
    },
    {
      key: 'autoFollowUp',
      label: 'Auto-Create Follow-Ups',
      type: 'boolean',
      default: true,
      description: 'Automatically create follow-ups for visitors',
    },
    {
      key: 'followUpDelay',
      label: 'Follow-Up Delay (hours)',
      type: 'number',
      default: 24,
      description: 'Hours after event to send follow-up',
    },
    {
      key: 'sendConfirmation',
      label: 'Send RSVP Confirmation',
      type: 'boolean',
      default: true,
      description: 'Send confirmation email for RSVPs',
    },
    {
      key: 'sendReminder',
      label: 'Send Event Reminder',
      type: 'boolean',
      default: true,
      description: 'Send reminder before event',
    },
    {
      key: 'reminderHours',
      label: 'Reminder Hours Before',
      type: 'number',
      default: 24,
      description: 'Hours before event to send reminder',
    },
    {
      key: 'enableKioskMode',
      label: 'Enable Kiosk Mode',
      type: 'boolean',
      default: true,
      description: 'Enable tablet kiosk mode for sign-in',
    },
  ],
};
