/**
 * Property Valuation Feature Definition
 *
 * Property value estimation and market analysis for real estate applications.
 * Supports automated valuations, comparable sales analysis, and market trends.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PROPERTY_VALUATION_FEATURE: FeatureDefinition = {
  id: 'property-valuation',
  name: 'Property Valuation',
  category: 'real-estate',
  description: 'Estimate property values with market analysis, comparables, and automated valuations',
  icon: 'chart-line',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'property valuation',
    'home value',
    'house value',
    'property estimate',
    'cma',
    'comparative market analysis',
    'comps',
    'comparable sales',
    'avm',
    'automated valuation',
    'zestimate',
    'home worth',
    'property appraisal',
    'market value',
    'price estimate',
    'equity calculator',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth', 'property-listings'],
  conflicts: [],

  pages: [
    {
      id: 'valuation-tool',
      route: '/valuation',
      section: 'frontend',
      title: 'Property Valuation',
      authRequired: false,
      templateId: 'valuation-tool',
      components: [
        'valuation-form',
        'address-lookup',
        'property-details-input',
        'value-estimate-display',
        'value-range',
        'confidence-indicator',
        'save-valuation',
      ],
      layout: 'default',
    },
    {
      id: 'market-analysis',
      route: '/market-analysis',
      section: 'frontend',
      title: 'Market Analysis',
      authRequired: false,
      templateId: 'market-analysis',
      components: [
        'market-overview',
        'market-trends-chart',
        'price-per-sqft-chart',
        'inventory-chart',
        'days-on-market-chart',
        'neighborhood-stats',
        'market-forecast',
      ],
      layout: 'default',
    },
    {
      id: 'comp-search',
      route: '/comps',
      section: 'frontend',
      title: 'Comparable Sales',
      authRequired: true,
      templateId: 'comp-search',
      components: [
        'comp-search-form',
        'comp-filters',
        'comp-table',
        'comp-map',
        'comp-comparison',
        'export-comps',
        'save-comp-report',
      ],
      layout: 'dashboard',
    },
    {
      id: 'valuation-detail',
      route: '/valuations/:id',
      section: 'frontend',
      title: 'Valuation Report',
      authRequired: true,
      templateId: 'valuation-detail',
      components: [
        'valuation-header',
        'value-breakdown',
        'comp-list',
        'adjustment-table',
        'market-context',
        'print-report',
        'share-report',
      ],
      layout: 'default',
    },
    {
      id: 'my-valuations',
      route: '/my-valuations',
      section: 'frontend',
      title: 'My Valuations',
      authRequired: true,
      templateId: 'my-valuations',
      components: [
        'valuations-list',
        'valuation-card',
        'valuation-filters',
        'value-tracking',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-valuations',
      route: '/admin/valuations',
      section: 'admin',
      title: 'Valuation Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-valuations',
      components: [
        'valuation-model-settings',
        'data-source-config',
        'adjustment-factors',
        'valuation-logs',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Valuation tool components
    'valuation-form',
    'address-lookup',
    'property-details-input',
    'value-estimate-display',
    'value-range',
    'confidence-indicator',
    'save-valuation',

    // Market analysis components
    'market-overview',
    'market-trends-chart',
    'price-per-sqft-chart',
    'inventory-chart',
    'days-on-market-chart',
    'neighborhood-stats',
    'market-forecast',

    // Comp search components
    'comp-search-form',
    'comp-filters',
    'comp-table',
    'comp-map',
    'comp-comparison',
    'export-comps',
    'save-comp-report',

    // Report components
    'valuation-header',
    'value-breakdown',
    'comp-list',
    'adjustment-table',
    'market-context',
    'print-report',
    'share-report',

    // List components
    'valuations-list',
    'valuation-card',
    'valuation-filters',
    'value-tracking',

    // Admin components
    'valuation-model-settings',
    'data-source-config',
    'adjustment-factors',
    'valuation-logs',
  ],

  entities: [
    {
      name: 'valuations',
      displayName: 'Valuations',
      description: 'Property valuation records',
      isCore: true,
    },
    {
      name: 'comparables',
      displayName: 'Comparables',
      description: 'Comparable property sales',
      isCore: true,
    },
    {
      name: 'market_data',
      displayName: 'Market Data',
      description: 'Market statistics and trends',
      isCore: true,
    },
    {
      name: 'valuation_adjustments',
      displayName: 'Valuation Adjustments',
      description: 'Value adjustment factors',
      isCore: false,
    },
    {
      name: 'value_history',
      displayName: 'Value History',
      description: 'Historical value estimates',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Valuations CRUD
    {
      method: 'GET',
      path: '/valuations',
      auth: true,
      handler: 'crud',
      entity: 'valuations',
      operation: 'list',
      description: 'List user valuations',
    },
    {
      method: 'GET',
      path: '/valuations/:id',
      auth: true,
      handler: 'crud',
      entity: 'valuations',
      operation: 'get',
      description: 'Get valuation details',
    },
    {
      method: 'POST',
      path: '/valuations',
      auth: false,
      handler: 'crud',
      entity: 'valuations',
      operation: 'create',
      description: 'Create new valuation',
    },
    {
      method: 'PUT',
      path: '/valuations/:id',
      auth: true,
      handler: 'crud',
      entity: 'valuations',
      operation: 'update',
      description: 'Update valuation',
    },
    {
      method: 'DELETE',
      path: '/valuations/:id',
      auth: true,
      handler: 'crud',
      entity: 'valuations',
      operation: 'delete',
      description: 'Delete valuation',
    },

    // Quick valuation
    {
      method: 'POST',
      path: '/valuations/estimate',
      auth: false,
      handler: 'custom',
      entity: 'valuations',
      description: 'Get quick property estimate',
    },
    {
      method: 'POST',
      path: '/valuations/address-lookup',
      auth: false,
      handler: 'custom',
      entity: 'valuations',
      description: 'Lookup property by address',
    },

    // Comparables
    {
      method: 'GET',
      path: '/comparables',
      auth: true,
      handler: 'crud',
      entity: 'comparables',
      operation: 'list',
      description: 'Search comparable sales',
    },
    {
      method: 'GET',
      path: '/comparables/:id',
      auth: true,
      handler: 'crud',
      entity: 'comparables',
      operation: 'get',
      description: 'Get comparable details',
    },
    {
      method: 'GET',
      path: '/valuations/:id/comps',
      auth: true,
      handler: 'custom',
      entity: 'comparables',
      description: 'Get comps for valuation',
    },
    {
      method: 'POST',
      path: '/valuations/:id/comps',
      auth: true,
      handler: 'custom',
      entity: 'comparables',
      description: 'Add comp to valuation',
    },
    {
      method: 'DELETE',
      path: '/valuations/:valuationId/comps/:id',
      auth: true,
      handler: 'custom',
      entity: 'comparables',
      description: 'Remove comp from valuation',
    },

    // Market Data
    {
      method: 'GET',
      path: '/market-data',
      auth: false,
      handler: 'crud',
      entity: 'market_data',
      operation: 'list',
      description: 'Get market data',
    },
    {
      method: 'GET',
      path: '/market-data/trends',
      auth: false,
      handler: 'custom',
      entity: 'market_data',
      description: 'Get market trends',
    },
    {
      method: 'GET',
      path: '/market-data/neighborhood/:zip',
      auth: false,
      handler: 'custom',
      entity: 'market_data',
      description: 'Get neighborhood market data',
    },
    {
      method: 'GET',
      path: '/market-data/forecast',
      auth: true,
      handler: 'custom',
      entity: 'market_data',
      description: 'Get market forecast',
    },

    // Value History
    {
      method: 'GET',
      path: '/properties/:id/value-history',
      auth: true,
      handler: 'crud',
      entity: 'value_history',
      operation: 'list',
      description: 'Get property value history',
    },
    {
      method: 'GET',
      path: '/valuations/:id/history',
      auth: true,
      handler: 'custom',
      entity: 'value_history',
      description: 'Get valuation history',
    },

    // Reports
    {
      method: 'GET',
      path: '/valuations/:id/report',
      auth: true,
      handler: 'custom',
      entity: 'valuations',
      description: 'Generate valuation report',
    },
    {
      method: 'GET',
      path: '/valuations/:id/report/pdf',
      auth: true,
      handler: 'custom',
      entity: 'valuations',
      description: 'Download PDF report',
    },
    {
      method: 'POST',
      path: '/valuations/:id/share',
      auth: true,
      handler: 'custom',
      entity: 'valuations',
      description: 'Share valuation report',
    },

    // CMA (Comparative Market Analysis)
    {
      method: 'POST',
      path: '/cma',
      auth: true,
      handler: 'custom',
      entity: 'valuations',
      description: 'Generate CMA report',
    },
    {
      method: 'GET',
      path: '/cma/:id',
      auth: true,
      handler: 'custom',
      entity: 'valuations',
      description: 'Get CMA report',
    },
  ],

  config: [
    {
      key: 'valuationModel',
      label: 'Valuation Model',
      type: 'select',
      default: 'hybrid',
      options: [
        { value: 'avm', label: 'Automated Valuation Model (AVM)' },
        { value: 'cma', label: 'Comparative Market Analysis' },
        { value: 'hybrid', label: 'Hybrid (AVM + CMA)' },
      ],
      description: 'Primary valuation methodology',
    },
    {
      key: 'compRadius',
      label: 'Default Comp Radius (miles)',
      type: 'number',
      default: 1,
      description: 'Default radius for comparable search',
    },
    {
      key: 'compTimeframe',
      label: 'Comp Timeframe (months)',
      type: 'number',
      default: 6,
      description: 'How far back to search for comps',
    },
    {
      key: 'minComps',
      label: 'Minimum Comparables',
      type: 'number',
      default: 3,
      description: 'Minimum number of comps required',
    },
    {
      key: 'maxComps',
      label: 'Maximum Comparables',
      type: 'number',
      default: 10,
      description: 'Maximum number of comps to include',
    },
    {
      key: 'enableAutoAdjustments',
      label: 'Enable Auto Adjustments',
      type: 'boolean',
      default: true,
      description: 'Automatically calculate value adjustments',
    },
    {
      key: 'confidenceThreshold',
      label: 'Confidence Threshold (%)',
      type: 'number',
      default: 80,
      description: 'Minimum confidence score for estimates',
    },
    {
      key: 'refreshInterval',
      label: 'Value Refresh Interval (days)',
      type: 'number',
      default: 30,
      description: 'How often to refresh saved valuations',
    },
    {
      key: 'enableMarketForecast',
      label: 'Enable Market Forecast',
      type: 'boolean',
      default: true,
      description: 'Show market value forecasts',
    },
  ],
};
