/**
 * Property Listings Feature Definition
 *
 * Complete property listing management for real estate applications.
 * Supports residential, commercial, and rental property listings.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PROPERTY_LISTINGS_FEATURE: FeatureDefinition = {
  id: 'property-listings',
  name: 'Property Listings',
  category: 'real-estate',
  description: 'Manage property listings with photos, details, pricing, and status tracking',
  icon: 'home',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'property listing',
    'property listings',
    'real estate listing',
    'house listing',
    'home listing',
    'property for sale',
    'property for rent',
    'mls listing',
    'listing management',
    'property catalog',
    'homes for sale',
    'rental listing',
    'commercial listing',
    'property inventory',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload'],
  conflicts: [],

  pages: [
    {
      id: 'listings-grid',
      route: '/listings',
      section: 'frontend',
      title: 'Property Listings',
      authRequired: false,
      templateId: 'listings-grid',
      components: [
        'property-grid',
        'property-card',
        'listing-filters',
        'map-view-toggle',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'listing-detail',
      route: '/listings/:id',
      section: 'frontend',
      title: 'Property Details',
      authRequired: false,
      templateId: 'listing-detail',
      components: [
        'property-gallery',
        'property-details',
        'property-features',
        'property-map',
        'price-history',
        'contact-agent-form',
        'schedule-showing-button',
        'mortgage-calculator',
        'share-listing',
        'save-listing',
      ],
      layout: 'default',
    },
    {
      id: 'listing-create',
      route: '/listings/new',
      section: 'frontend',
      title: 'Create Listing',
      authRequired: true,
      roles: ['agent', 'admin', 'owner'],
      templateId: 'listing-create',
      components: [
        'listing-form',
        'property-type-selector',
        'address-autocomplete',
        'photo-uploader',
        'features-checklist',
        'pricing-form',
        'description-editor',
      ],
      layout: 'default',
    },
    {
      id: 'listing-edit',
      route: '/listings/:id/edit',
      section: 'frontend',
      title: 'Edit Listing',
      authRequired: true,
      roles: ['agent', 'admin', 'owner'],
      templateId: 'listing-edit',
      components: [
        'listing-form',
        'property-type-selector',
        'address-autocomplete',
        'photo-uploader',
        'photo-manager',
        'features-checklist',
        'pricing-form',
        'description-editor',
        'listing-status-toggle',
      ],
      layout: 'default',
    },
    {
      id: 'my-listings',
      route: '/my-listings',
      section: 'frontend',
      title: 'My Listings',
      authRequired: true,
      templateId: 'my-listings',
      components: [
        'listings-table',
        'listing-status-filter',
        'listing-actions',
        'listing-stats',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-listings',
      route: '/admin/listings',
      section: 'admin',
      title: 'Manage Listings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-listings',
      components: [
        'listings-table',
        'listing-filters',
        'bulk-actions',
        'listing-approval',
        'featured-toggle',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Grid/List components
    'property-grid',
    'property-card',
    'property-list-item',
    'listing-filters',
    'map-view-toggle',
    'sort-dropdown',
    'pagination',

    // Detail components
    'property-gallery',
    'property-details',
    'property-features',
    'property-map',
    'price-history',
    'contact-agent-form',
    'schedule-showing-button',
    'mortgage-calculator',
    'share-listing',
    'save-listing',

    // Form components
    'listing-form',
    'property-type-selector',
    'address-autocomplete',
    'photo-uploader',
    'photo-manager',
    'features-checklist',
    'pricing-form',
    'description-editor',
    'listing-status-toggle',

    // Management components
    'listings-table',
    'listing-status-filter',
    'listing-actions',
    'listing-stats',
    'bulk-actions',
    'listing-approval',
    'featured-toggle',
  ],

  entities: [
    {
      name: 'properties',
      displayName: 'Properties',
      description: 'Property listing records',
      isCore: true,
    },
    {
      name: 'property_images',
      displayName: 'Property Images',
      description: 'Images associated with properties',
      isCore: true,
    },
    {
      name: 'property_features',
      displayName: 'Property Features',
      description: 'Amenities and features for properties',
      isCore: true,
    },
    {
      name: 'price_history',
      displayName: 'Price History',
      description: 'Historical price changes for properties',
      isCore: false,
    },
    {
      name: 'saved_listings',
      displayName: 'Saved Listings',
      description: 'User saved/favorited listings',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Property CRUD
    {
      method: 'GET',
      path: '/properties',
      auth: false,
      handler: 'crud',
      entity: 'properties',
      operation: 'list',
      description: 'List all properties with filters',
    },
    {
      method: 'GET',
      path: '/properties/:id',
      auth: false,
      handler: 'crud',
      entity: 'properties',
      operation: 'get',
      description: 'Get property details',
    },
    {
      method: 'POST',
      path: '/properties',
      auth: true,
      role: 'agent',
      handler: 'crud',
      entity: 'properties',
      operation: 'create',
      description: 'Create new property listing',
    },
    {
      method: 'PUT',
      path: '/properties/:id',
      auth: true,
      handler: 'crud',
      entity: 'properties',
      operation: 'update',
      description: 'Update property listing',
    },
    {
      method: 'DELETE',
      path: '/properties/:id',
      auth: true,
      handler: 'crud',
      entity: 'properties',
      operation: 'delete',
      description: 'Delete property listing',
    },

    // Property Images
    {
      method: 'GET',
      path: '/properties/:id/images',
      auth: false,
      handler: 'crud',
      entity: 'property_images',
      operation: 'list',
      description: 'Get property images',
    },
    {
      method: 'POST',
      path: '/properties/:id/images',
      auth: true,
      handler: 'crud',
      entity: 'property_images',
      operation: 'create',
      description: 'Add property image',
    },
    {
      method: 'DELETE',
      path: '/properties/:propertyId/images/:id',
      auth: true,
      handler: 'crud',
      entity: 'property_images',
      operation: 'delete',
      description: 'Delete property image',
    },
    {
      method: 'PUT',
      path: '/properties/:propertyId/images/:id/primary',
      auth: true,
      handler: 'custom',
      entity: 'property_images',
      description: 'Set primary image',
    },

    // Property Features
    {
      method: 'GET',
      path: '/properties/:id/features',
      auth: false,
      handler: 'crud',
      entity: 'property_features',
      operation: 'list',
      description: 'Get property features',
    },
    {
      method: 'PUT',
      path: '/properties/:id/features',
      auth: true,
      handler: 'custom',
      entity: 'property_features',
      description: 'Update property features',
    },

    // Price History
    {
      method: 'GET',
      path: '/properties/:id/price-history',
      auth: false,
      handler: 'crud',
      entity: 'price_history',
      operation: 'list',
      description: 'Get price history',
    },

    // Saved Listings
    {
      method: 'GET',
      path: '/saved-listings',
      auth: true,
      handler: 'crud',
      entity: 'saved_listings',
      operation: 'list',
      description: 'Get user saved listings',
    },
    {
      method: 'POST',
      path: '/properties/:id/save',
      auth: true,
      handler: 'custom',
      entity: 'saved_listings',
      description: 'Save listing to favorites',
    },
    {
      method: 'DELETE',
      path: '/properties/:id/save',
      auth: true,
      handler: 'custom',
      entity: 'saved_listings',
      description: 'Remove listing from favorites',
    },

    // Status management
    {
      method: 'PUT',
      path: '/properties/:id/status',
      auth: true,
      handler: 'custom',
      entity: 'properties',
      description: 'Update listing status',
    },
    {
      method: 'PUT',
      path: '/properties/:id/featured',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'properties',
      description: 'Toggle featured status',
    },

    // Search and filters
    {
      method: 'GET',
      path: '/properties/search',
      auth: false,
      handler: 'custom',
      entity: 'properties',
      description: 'Search properties',
    },
    {
      method: 'GET',
      path: '/properties/nearby',
      auth: false,
      handler: 'custom',
      entity: 'properties',
      description: 'Get nearby properties',
    },
  ],

  config: [
    {
      key: 'allowPublicListings',
      label: 'Allow Public Listing Creation',
      type: 'boolean',
      default: false,
      description: 'Allow non-agents to create listings',
    },
    {
      key: 'requireApproval',
      label: 'Require Admin Approval',
      type: 'boolean',
      default: true,
      description: 'Require admin approval before listings go live',
    },
    {
      key: 'maxImages',
      label: 'Maximum Images Per Listing',
      type: 'number',
      default: 30,
      description: 'Maximum number of images allowed per listing',
    },
    {
      key: 'defaultListingDuration',
      label: 'Default Listing Duration (days)',
      type: 'number',
      default: 90,
      description: 'How long listings remain active by default',
    },
    {
      key: 'enablePriceHistory',
      label: 'Enable Price History Tracking',
      type: 'boolean',
      default: true,
      description: 'Track historical price changes',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for pricing',
    },
    {
      key: 'propertyTypes',
      label: 'Property Types',
      type: 'select',
      default: 'all',
      options: [
        { value: 'all', label: 'All Types' },
        { value: 'residential', label: 'Residential Only' },
        { value: 'commercial', label: 'Commercial Only' },
        { value: 'land', label: 'Land Only' },
      ],
      description: 'Types of properties to support',
    },
  ],
};
