/**
 * Rent Collection Feature Definition
 *
 * Rent payment collection and tracking for property management applications.
 * Supports online payments, automatic reminders, late fees, and payment history.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const RENT_COLLECTION_FEATURE: FeatureDefinition = {
  id: 'rent-collection',
  name: 'Rent Collection',
  category: 'real-estate',
  description: 'Collect rent payments online with automatic reminders, late fees, and payment tracking',
  icon: 'credit-card',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'rent collection',
    'rent payment',
    'collect rent',
    'pay rent',
    'online rent',
    'rent portal',
    'tenant payment',
    'rent tracker',
    'payment collection',
    'late rent',
    'late fee',
    'rent due',
    'rent reminder',
    'automatic payment',
    'autopay rent',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'property-listings', 'lease-management', 'payments'],
  conflicts: [],

  pages: [
    {
      id: 'rent-dashboard',
      route: '/rent',
      section: 'frontend',
      title: 'Rent Dashboard',
      authRequired: true,
      templateId: 'rent-dashboard',
      components: [
        'rent-overview',
        'upcoming-payments',
        'recent-collections',
        'rent-tracker',
        'collection-stats',
        'delinquency-alerts',
      ],
      layout: 'dashboard',
    },
    {
      id: 'payment-history',
      route: '/rent/history',
      section: 'frontend',
      title: 'Payment History',
      authRequired: true,
      templateId: 'payment-history',
      components: [
        'payments-table',
        'payment-filters',
        'payment-search',
        'export-payments',
        'payment-analytics',
      ],
      layout: 'dashboard',
    },
    {
      id: 'late-payments',
      route: '/rent/late',
      section: 'frontend',
      title: 'Late Payments',
      authRequired: true,
      templateId: 'late-payments',
      components: [
        'late-payments-list',
        'late-payment-card',
        'late-fee-summary',
        'collection-actions',
        'payment-plan-options',
      ],
      layout: 'dashboard',
    },
    {
      id: 'make-payment',
      route: '/rent/pay',
      section: 'frontend',
      title: 'Pay Rent',
      authRequired: true,
      templateId: 'make-payment',
      components: [
        'payment-form',
        'amount-display',
        'payment-method-selector',
        'autopay-setup',
        'payment-confirmation',
        'receipt-display',
      ],
      layout: 'default',
    },
    {
      id: 'payment-methods',
      route: '/rent/methods',
      section: 'frontend',
      title: 'Payment Methods',
      authRequired: true,
      templateId: 'payment-methods',
      components: [
        'saved-methods-list',
        'add-payment-method',
        'bank-account-form',
        'card-form',
        'autopay-settings',
      ],
      layout: 'default',
    },
    {
      id: 'admin-rent',
      route: '/admin/rent',
      section: 'admin',
      title: 'Rent Management',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-rent',
      components: [
        'rent-overview-admin',
        'collections-table',
        'payment-processing',
        'late-fee-management',
        'payout-settings',
        'rent-reports',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'rent-overview',
    'upcoming-payments',
    'recent-collections',
    'rent-tracker',
    'collection-stats',
    'delinquency-alerts',

    // Payment history components
    'payments-table',
    'payment-filters',
    'payment-search',
    'export-payments',
    'payment-analytics',

    // Late payments components
    'late-payments-list',
    'late-payment-card',
    'late-fee-summary',
    'late-fee-calculator',
    'collection-actions',
    'payment-plan-options',
    'payment-reminder',

    // Payment form components
    'payment-form',
    'amount-display',
    'payment-method-selector',
    'autopay-setup',
    'payment-confirmation',
    'receipt-display',

    // Payment methods components
    'saved-methods-list',
    'add-payment-method',
    'bank-account-form',
    'card-form',
    'autopay-settings',

    // Admin components
    'rent-overview-admin',
    'collections-table',
    'payment-processing',
    'late-fee-management',
    'payout-settings',
    'rent-reports',
  ],

  entities: [
    {
      name: 'rent_payments',
      displayName: 'Rent Payments',
      description: 'Rent payment transactions',
      isCore: true,
    },
    {
      name: 'late_fees',
      displayName: 'Late Fees',
      description: 'Late fee assessments',
      isCore: true,
    },
    {
      name: 'payment_methods',
      displayName: 'Payment Methods',
      description: 'Saved tenant payment methods',
      isCore: true,
    },
    {
      name: 'autopay_settings',
      displayName: 'Autopay Settings',
      description: 'Automatic payment configurations',
      isCore: false,
    },
    {
      name: 'payment_reminders',
      displayName: 'Payment Reminders',
      description: 'Scheduled payment reminders',
      isCore: false,
    },
    {
      name: 'payment_plans',
      displayName: 'Payment Plans',
      description: 'Custom payment arrangements',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Rent Payments CRUD
    {
      method: 'GET',
      path: '/rent-payments',
      auth: true,
      handler: 'crud',
      entity: 'rent_payments',
      operation: 'list',
      description: 'List rent payments',
    },
    {
      method: 'GET',
      path: '/rent-payments/:id',
      auth: true,
      handler: 'crud',
      entity: 'rent_payments',
      operation: 'get',
      description: 'Get payment details',
    },
    {
      method: 'POST',
      path: '/rent-payments',
      auth: true,
      handler: 'crud',
      entity: 'rent_payments',
      operation: 'create',
      description: 'Record rent payment',
    },
    {
      method: 'PUT',
      path: '/rent-payments/:id',
      auth: true,
      handler: 'crud',
      entity: 'rent_payments',
      operation: 'update',
      description: 'Update payment',
    },
    {
      method: 'DELETE',
      path: '/rent-payments/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'rent_payments',
      operation: 'delete',
      description: 'Delete payment',
    },

    // Payment processing
    {
      method: 'POST',
      path: '/rent-payments/process',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Process rent payment',
    },
    {
      method: 'POST',
      path: '/rent-payments/:id/refund',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Refund payment',
    },
    {
      method: 'GET',
      path: '/rent-payments/:id/receipt',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Get payment receipt',
    },

    // Late Fees
    {
      method: 'GET',
      path: '/late-fees',
      auth: true,
      handler: 'crud',
      entity: 'late_fees',
      operation: 'list',
      description: 'List late fees',
    },
    {
      method: 'POST',
      path: '/late-fees',
      auth: true,
      handler: 'crud',
      entity: 'late_fees',
      operation: 'create',
      description: 'Assess late fee',
    },
    {
      method: 'PUT',
      path: '/late-fees/:id/waive',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'late_fees',
      description: 'Waive late fee',
    },
    {
      method: 'GET',
      path: '/late-fees/calculate',
      auth: true,
      handler: 'custom',
      entity: 'late_fees',
      description: 'Calculate late fees',
    },

    // Payment Methods
    {
      method: 'GET',
      path: '/payment-methods',
      auth: true,
      handler: 'crud',
      entity: 'payment_methods',
      operation: 'list',
      description: 'List payment methods',
    },
    {
      method: 'POST',
      path: '/payment-methods',
      auth: true,
      handler: 'crud',
      entity: 'payment_methods',
      operation: 'create',
      description: 'Add payment method',
    },
    {
      method: 'DELETE',
      path: '/payment-methods/:id',
      auth: true,
      handler: 'crud',
      entity: 'payment_methods',
      operation: 'delete',
      description: 'Remove payment method',
    },
    {
      method: 'PUT',
      path: '/payment-methods/:id/default',
      auth: true,
      handler: 'custom',
      entity: 'payment_methods',
      description: 'Set default payment method',
    },

    // Autopay
    {
      method: 'GET',
      path: '/autopay',
      auth: true,
      handler: 'crud',
      entity: 'autopay_settings',
      operation: 'get',
      description: 'Get autopay settings',
    },
    {
      method: 'POST',
      path: '/autopay',
      auth: true,
      handler: 'crud',
      entity: 'autopay_settings',
      operation: 'create',
      description: 'Enable autopay',
    },
    {
      method: 'PUT',
      path: '/autopay',
      auth: true,
      handler: 'crud',
      entity: 'autopay_settings',
      operation: 'update',
      description: 'Update autopay settings',
    },
    {
      method: 'DELETE',
      path: '/autopay',
      auth: true,
      handler: 'crud',
      entity: 'autopay_settings',
      operation: 'delete',
      description: 'Disable autopay',
    },

    // Payment Plans
    {
      method: 'GET',
      path: '/payment-plans',
      auth: true,
      handler: 'crud',
      entity: 'payment_plans',
      operation: 'list',
      description: 'List payment plans',
    },
    {
      method: 'POST',
      path: '/payment-plans',
      auth: true,
      handler: 'crud',
      entity: 'payment_plans',
      operation: 'create',
      description: 'Create payment plan',
    },
    {
      method: 'PUT',
      path: '/payment-plans/:id',
      auth: true,
      handler: 'crud',
      entity: 'payment_plans',
      operation: 'update',
      description: 'Update payment plan',
    },

    // Lease payments
    {
      method: 'GET',
      path: '/leases/:id/payments',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Get payments for lease',
    },
    {
      method: 'GET',
      path: '/leases/:id/balance',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Get lease balance due',
    },

    // Property payments
    {
      method: 'GET',
      path: '/properties/:id/payments',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Get payments for property',
    },

    // Tenant payments
    {
      method: 'GET',
      path: '/tenants/:id/payments',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Get payments for tenant',
    },

    // Reminders
    {
      method: 'POST',
      path: '/rent-payments/send-reminder',
      auth: true,
      handler: 'custom',
      entity: 'payment_reminders',
      description: 'Send payment reminder',
    },
    {
      method: 'POST',
      path: '/rent-payments/send-late-notice',
      auth: true,
      handler: 'custom',
      entity: 'payment_reminders',
      description: 'Send late payment notice',
    },

    // Analytics
    {
      method: 'GET',
      path: '/rent-payments/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'rent_payments',
      description: 'Get payment analytics',
    },
    {
      method: 'GET',
      path: '/rent-payments/delinquency-report',
      auth: true,
      handler: 'aggregate',
      entity: 'rent_payments',
      description: 'Get delinquency report',
    },

    // Reports
    {
      method: 'GET',
      path: '/rent-payments/report',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Generate payment report',
    },
    {
      method: 'GET',
      path: '/rent-payments/export',
      auth: true,
      handler: 'custom',
      entity: 'rent_payments',
      description: 'Export payments',
    },
  ],

  config: [
    {
      key: 'paymentProcessor',
      label: 'Payment Processor',
      type: 'select',
      default: 'stripe',
      options: [
        { value: 'stripe', label: 'Stripe' },
        { value: 'plaid', label: 'Plaid' },
        { value: 'paypal', label: 'PayPal' },
        { value: 'square', label: 'Square' },
      ],
      description: 'Payment processing provider',
    },
    {
      key: 'allowACH',
      label: 'Allow ACH Payments',
      type: 'boolean',
      default: true,
      description: 'Accept bank account payments',
    },
    {
      key: 'allowCard',
      label: 'Allow Card Payments',
      type: 'boolean',
      default: true,
      description: 'Accept credit/debit card payments',
    },
    {
      key: 'convenienceFee',
      label: 'Convenience Fee',
      type: 'number',
      default: 0,
      description: 'Fee charged for online payments',
    },
    {
      key: 'convenienceFeeType',
      label: 'Convenience Fee Type',
      type: 'select',
      default: 'flat',
      options: [
        { value: 'flat', label: 'Flat Fee' },
        { value: 'percentage', label: 'Percentage' },
      ],
      description: 'How convenience fee is calculated',
    },
    {
      key: 'sendReminders',
      label: 'Send Payment Reminders',
      type: 'boolean',
      default: true,
      description: 'Automatically send payment reminders',
    },
    {
      key: 'reminderDaysBefore',
      label: 'Reminder Days Before Due',
      type: 'number',
      default: 5,
      description: 'Days before due date to send reminder',
    },
    {
      key: 'lateFeeGracePeriod',
      label: 'Late Fee Grace Period (days)',
      type: 'number',
      default: 5,
      description: 'Days after due date before late fee applies',
    },
    {
      key: 'autoLateFee',
      label: 'Auto-Assess Late Fees',
      type: 'boolean',
      default: true,
      description: 'Automatically assess late fees',
    },
    {
      key: 'allowPartialPayments',
      label: 'Allow Partial Payments',
      type: 'boolean',
      default: true,
      description: 'Allow tenants to make partial payments',
    },
    {
      key: 'requireFullPayment',
      label: 'Require Full Amount When Late',
      type: 'boolean',
      default: false,
      description: 'Require full payment when past due',
    },
  ],
};
