/**
 * Showing Management Feature Definition
 *
 * Property showing scheduling and management for real estate applications.
 * Supports scheduling, tracking, and collecting feedback for property viewings.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const SHOWING_MANAGEMENT_FEATURE: FeatureDefinition = {
  id: 'showing-management',
  name: 'Showing Management',
  category: 'real-estate',
  description: 'Schedule and manage property showings with availability, requests, and feedback',
  icon: 'calendar-event',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'showing',
    'showings',
    'property showing',
    'schedule showing',
    'viewing',
    'property viewing',
    'house showing',
    'home tour',
    'walkthrough',
    'property tour',
    'showing request',
    'book viewing',
    'schedule tour',
    'lockbox',
    'showing feedback',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'property-listings', 'calendar'],
  conflicts: [],

  pages: [
    {
      id: 'showings-calendar',
      route: '/showings',
      section: 'frontend',
      title: 'Showings Calendar',
      authRequired: true,
      templateId: 'showings-calendar',
      components: [
        'showings-calendar-view',
        'showing-card',
        'day-agenda',
        'availability-indicator',
        'quick-add-showing',
        'calendar-filters',
      ],
      layout: 'dashboard',
    },
    {
      id: 'showing-requests',
      route: '/showings/requests',
      section: 'frontend',
      title: 'Showing Requests',
      authRequired: true,
      templateId: 'showing-requests',
      components: [
        'requests-list',
        'request-card',
        'request-filters',
        'approve-reject-actions',
        'reschedule-modal',
        'bulk-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'showing-feedback',
      route: '/showings/feedback',
      section: 'frontend',
      title: 'Showing Feedback',
      authRequired: true,
      templateId: 'showing-feedback',
      components: [
        'feedback-list',
        'feedback-card',
        'feedback-summary',
        'feedback-trends',
        'feedback-export',
      ],
      layout: 'dashboard',
    },
    {
      id: 'schedule-showing',
      route: '/properties/:id/schedule',
      section: 'frontend',
      title: 'Schedule Showing',
      authRequired: false,
      templateId: 'schedule-showing',
      components: [
        'showing-scheduler',
        'availability-picker',
        'contact-form',
        'property-preview',
        'confirmation-display',
      ],
      layout: 'default',
    },
    {
      id: 'showing-detail',
      route: '/showings/:id',
      section: 'frontend',
      title: 'Showing Details',
      authRequired: true,
      templateId: 'showing-detail',
      components: [
        'showing-header',
        'showing-info',
        'attendee-list',
        'lockbox-info',
        'showing-notes',
        'feedback-form',
        'reschedule-button',
        'cancel-button',
      ],
      layout: 'default',
    },
    {
      id: 'admin-showings',
      route: '/admin/showings',
      section: 'admin',
      title: 'Manage Showings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-showings',
      components: [
        'showings-table',
        'showing-filters',
        'showing-analytics',
        'agent-performance',
        'bulk-actions',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Calendar components
    'showings-calendar-view',
    'showing-card',
    'day-agenda',
    'availability-indicator',
    'quick-add-showing',
    'calendar-filters',

    // Request components
    'requests-list',
    'request-card',
    'request-filters',
    'approve-reject-actions',
    'reschedule-modal',

    // Feedback components
    'feedback-list',
    'feedback-card',
    'feedback-summary',
    'feedback-trends',
    'feedback-export',
    'feedback-form',

    // Scheduling components
    'showing-scheduler',
    'availability-picker',
    'contact-form',
    'property-preview',
    'confirmation-display',

    // Detail components
    'showing-header',
    'showing-info',
    'attendee-list',
    'lockbox-info',
    'showing-notes',
    'reschedule-button',
    'cancel-button',

    // Admin components
    'showings-table',
    'showing-filters',
    'showing-analytics',
    'agent-performance',
    'bulk-actions',
  ],

  entities: [
    {
      name: 'showings',
      displayName: 'Showings',
      description: 'Scheduled property showings',
      isCore: true,
    },
    {
      name: 'showing_requests',
      displayName: 'Showing Requests',
      description: 'Pending showing requests',
      isCore: true,
    },
    {
      name: 'showing_feedback',
      displayName: 'Showing Feedback',
      description: 'Feedback from property showings',
      isCore: true,
    },
    {
      name: 'showing_attendees',
      displayName: 'Showing Attendees',
      description: 'Attendees for group showings',
      isCore: false,
    },
    {
      name: 'lockbox_codes',
      displayName: 'Lockbox Codes',
      description: 'Lockbox access codes for showings',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Showings CRUD
    {
      method: 'GET',
      path: '/showings',
      auth: true,
      handler: 'crud',
      entity: 'showings',
      operation: 'list',
      description: 'List all showings',
    },
    {
      method: 'GET',
      path: '/showings/:id',
      auth: true,
      handler: 'crud',
      entity: 'showings',
      operation: 'get',
      description: 'Get showing details',
    },
    {
      method: 'POST',
      path: '/showings',
      auth: true,
      handler: 'crud',
      entity: 'showings',
      operation: 'create',
      description: 'Create new showing',
    },
    {
      method: 'PUT',
      path: '/showings/:id',
      auth: true,
      handler: 'crud',
      entity: 'showings',
      operation: 'update',
      description: 'Update showing',
    },
    {
      method: 'DELETE',
      path: '/showings/:id',
      auth: true,
      handler: 'crud',
      entity: 'showings',
      operation: 'delete',
      description: 'Cancel showing',
    },

    // Showing actions
    {
      method: 'POST',
      path: '/showings/:id/confirm',
      auth: true,
      handler: 'custom',
      entity: 'showings',
      description: 'Confirm showing',
    },
    {
      method: 'POST',
      path: '/showings/:id/reschedule',
      auth: true,
      handler: 'custom',
      entity: 'showings',
      description: 'Reschedule showing',
    },
    {
      method: 'POST',
      path: '/showings/:id/complete',
      auth: true,
      handler: 'custom',
      entity: 'showings',
      description: 'Mark showing as completed',
    },
    {
      method: 'POST',
      path: '/showings/:id/no-show',
      auth: true,
      handler: 'custom',
      entity: 'showings',
      description: 'Mark as no-show',
    },

    // Showing Requests
    {
      method: 'GET',
      path: '/showing-requests',
      auth: true,
      handler: 'crud',
      entity: 'showing_requests',
      operation: 'list',
      description: 'List showing requests',
    },
    {
      method: 'GET',
      path: '/showing-requests/:id',
      auth: true,
      handler: 'crud',
      entity: 'showing_requests',
      operation: 'get',
      description: 'Get request details',
    },
    {
      method: 'POST',
      path: '/showing-requests',
      auth: false,
      handler: 'crud',
      entity: 'showing_requests',
      operation: 'create',
      description: 'Submit showing request',
    },
    {
      method: 'PUT',
      path: '/showing-requests/:id/approve',
      auth: true,
      handler: 'custom',
      entity: 'showing_requests',
      description: 'Approve showing request',
    },
    {
      method: 'PUT',
      path: '/showing-requests/:id/reject',
      auth: true,
      handler: 'custom',
      entity: 'showing_requests',
      description: 'Reject showing request',
    },

    // Showing Feedback
    {
      method: 'GET',
      path: '/showings/:id/feedback',
      auth: true,
      handler: 'crud',
      entity: 'showing_feedback',
      operation: 'list',
      description: 'Get feedback for showing',
    },
    {
      method: 'POST',
      path: '/showings/:id/feedback',
      auth: true,
      handler: 'crud',
      entity: 'showing_feedback',
      operation: 'create',
      description: 'Submit showing feedback',
    },
    {
      method: 'GET',
      path: '/properties/:id/feedback',
      auth: true,
      handler: 'custom',
      entity: 'showing_feedback',
      description: 'Get all feedback for property',
    },
    {
      method: 'GET',
      path: '/feedback/summary',
      auth: true,
      handler: 'aggregate',
      entity: 'showing_feedback',
      description: 'Get feedback summary',
    },

    // Property showings
    {
      method: 'GET',
      path: '/properties/:id/showings',
      auth: true,
      handler: 'custom',
      entity: 'showings',
      description: 'Get showings for property',
    },
    {
      method: 'GET',
      path: '/properties/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'showings',
      description: 'Get available showing times',
    },

    // Lockbox
    {
      method: 'GET',
      path: '/showings/:id/lockbox',
      auth: true,
      handler: 'crud',
      entity: 'lockbox_codes',
      operation: 'get',
      description: 'Get lockbox code for showing',
    },
    {
      method: 'POST',
      path: '/properties/:id/lockbox',
      auth: true,
      handler: 'crud',
      entity: 'lockbox_codes',
      operation: 'create',
      description: 'Set lockbox code',
    },

    // Analytics
    {
      method: 'GET',
      path: '/showings/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'showings',
      description: 'Get showing analytics',
    },
    {
      method: 'GET',
      path: '/agents/:id/showings/stats',
      auth: true,
      handler: 'aggregate',
      entity: 'showings',
      description: 'Get agent showing stats',
    },
  ],

  config: [
    {
      key: 'defaultShowingDuration',
      label: 'Default Showing Duration (minutes)',
      type: 'number',
      default: 30,
      description: 'Default duration for property showings',
    },
    {
      key: 'bufferBetweenShowings',
      label: 'Buffer Between Showings (minutes)',
      type: 'number',
      default: 15,
      description: 'Buffer time between consecutive showings',
    },
    {
      key: 'requireApproval',
      label: 'Require Showing Approval',
      type: 'boolean',
      default: true,
      description: 'Require agent/owner approval for showings',
    },
    {
      key: 'allowInstantBooking',
      label: 'Allow Instant Booking',
      type: 'boolean',
      default: false,
      description: 'Allow immediate showing confirmation',
    },
    {
      key: 'advanceBookingDays',
      label: 'Advance Booking Limit (days)',
      type: 'number',
      default: 14,
      description: 'How far in advance can showings be booked',
    },
    {
      key: 'minimumNotice',
      label: 'Minimum Notice (hours)',
      type: 'number',
      default: 24,
      description: 'Minimum hours notice required',
    },
    {
      key: 'enableLockboxCodes',
      label: 'Enable Lockbox Codes',
      type: 'boolean',
      default: true,
      description: 'Send lockbox codes for self-showings',
    },
    {
      key: 'feedbackRequired',
      label: 'Require Showing Feedback',
      type: 'boolean',
      default: true,
      description: 'Require feedback after showings',
    },
    {
      key: 'sendReminders',
      label: 'Send Showing Reminders',
      type: 'boolean',
      default: true,
      description: 'Send reminder notifications before showings',
    },
    {
      key: 'reminderHours',
      label: 'Reminder Hours Before',
      type: 'number',
      default: 24,
      description: 'Hours before showing to send reminder',
    },
  ],
};
