/**
 * Tenant Screening Feature Definition
 *
 * Tenant background screening and application management for property management.
 * Supports credit checks, background checks, income verification, and rental history.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TENANT_SCREENING_FEATURE: FeatureDefinition = {
  id: 'tenant-screening',
  name: 'Tenant Screening',
  category: 'real-estate',
  description: 'Screen tenant applications with credit checks, background checks, and income verification',
  icon: 'user-check',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'tenant screening',
    'background check',
    'credit check',
    'rental application',
    'tenant application',
    'income verification',
    'employment verification',
    'rental history',
    'eviction check',
    'criminal check',
    'tenant verification',
    'applicant screening',
    'renter screening',
    'tenant report',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth', 'property-listings', 'lease-management'],
  conflicts: [],

  pages: [
    {
      id: 'screening-dashboard',
      route: '/screening',
      section: 'frontend',
      title: 'Tenant Screening',
      authRequired: true,
      templateId: 'screening-dashboard',
      components: [
        'screening-overview',
        'pending-applications',
        'recent-screenings',
        'screening-stats',
        'quick-actions',
      ],
      layout: 'dashboard',
    },
    {
      id: 'application-review',
      route: '/screening/applications/:id',
      section: 'frontend',
      title: 'Application Review',
      authRequired: true,
      templateId: 'application-review',
      components: [
        'application-header',
        'applicant-info',
        'screening-status',
        'credit-check',
        'background-check',
        'income-verification',
        'rental-history',
        'references',
        'decision-actions',
        'notes-section',
      ],
      layout: 'default',
    },
    {
      id: 'screening-report',
      route: '/screening/reports/:id',
      section: 'frontend',
      title: 'Screening Report',
      authRequired: true,
      templateId: 'screening-report',
      components: [
        'report-header',
        'credit-report-summary',
        'background-summary',
        'income-summary',
        'risk-assessment',
        'recommendation',
        'download-report',
      ],
      layout: 'default',
    },
    {
      id: 'apply-online',
      route: '/apply/:propertyId',
      section: 'frontend',
      title: 'Rental Application',
      authRequired: false,
      templateId: 'apply-online',
      components: [
        'application-form',
        'personal-info-form',
        'employment-form',
        'income-form',
        'rental-history-form',
        'references-form',
        'consent-form',
        'document-upload',
        'application-fee-payment',
      ],
      layout: 'default',
    },
    {
      id: 'applications-list',
      route: '/screening/applications',
      section: 'frontend',
      title: 'Applications',
      authRequired: true,
      templateId: 'applications-list',
      components: [
        'applications-table',
        'application-filters',
        'status-badges',
        'bulk-actions',
        'export-applications',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-screening',
      route: '/admin/screening',
      section: 'admin',
      title: 'Screening Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-screening',
      components: [
        'screening-criteria',
        'provider-settings',
        'fee-configuration',
        'compliance-settings',
        'screening-templates',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Dashboard components
    'screening-overview',
    'pending-applications',
    'recent-screenings',
    'screening-stats',
    'quick-actions',

    // Application review components
    'application-header',
    'applicant-info',
    'screening-status',
    'credit-check',
    'background-check',
    'income-verification',
    'rental-history',
    'references',
    'decision-actions',
    'notes-section',

    // Report components
    'report-header',
    'credit-report-summary',
    'background-summary',
    'income-summary',
    'risk-assessment',
    'recommendation',
    'download-report',

    // Application form components
    'application-form',
    'personal-info-form',
    'employment-form',
    'income-form',
    'rental-history-form',
    'references-form',
    'consent-form',
    'document-upload',
    'application-fee-payment',

    // List components
    'applications-table',
    'application-filters',
    'status-badges',
    'bulk-actions',
    'export-applications',

    // Admin components
    'screening-criteria',
    'provider-settings',
    'fee-configuration',
    'compliance-settings',
    'screening-templates',
  ],

  entities: [
    {
      name: 'tenant_applications',
      displayName: 'Tenant Applications',
      description: 'Rental application submissions',
      isCore: true,
    },
    {
      name: 'screening_reports',
      displayName: 'Screening Reports',
      description: 'Background and credit check reports',
      isCore: true,
    },
    {
      name: 'verification_results',
      displayName: 'Verification Results',
      description: 'Income and employment verification results',
      isCore: true,
    },
    {
      name: 'application_documents',
      displayName: 'Application Documents',
      description: 'Documents uploaded with applications',
      isCore: false,
    },
    {
      name: 'references',
      displayName: 'References',
      description: 'Applicant references and verifications',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Applications CRUD
    {
      method: 'GET',
      path: '/applications',
      auth: true,
      handler: 'crud',
      entity: 'tenant_applications',
      operation: 'list',
      description: 'List tenant applications',
    },
    {
      method: 'GET',
      path: '/applications/:id',
      auth: true,
      handler: 'crud',
      entity: 'tenant_applications',
      operation: 'get',
      description: 'Get application details',
    },
    {
      method: 'POST',
      path: '/applications',
      auth: false,
      handler: 'crud',
      entity: 'tenant_applications',
      operation: 'create',
      description: 'Submit rental application',
    },
    {
      method: 'PUT',
      path: '/applications/:id',
      auth: true,
      handler: 'crud',
      entity: 'tenant_applications',
      operation: 'update',
      description: 'Update application',
    },
    {
      method: 'DELETE',
      path: '/applications/:id',
      auth: true,
      handler: 'crud',
      entity: 'tenant_applications',
      operation: 'delete',
      description: 'Delete application',
    },

    // Application actions
    {
      method: 'POST',
      path: '/applications/:id/approve',
      auth: true,
      handler: 'custom',
      entity: 'tenant_applications',
      description: 'Approve application',
    },
    {
      method: 'POST',
      path: '/applications/:id/reject',
      auth: true,
      handler: 'custom',
      entity: 'tenant_applications',
      description: 'Reject application',
    },
    {
      method: 'POST',
      path: '/applications/:id/request-info',
      auth: true,
      handler: 'custom',
      entity: 'tenant_applications',
      description: 'Request additional information',
    },

    // Screening
    {
      method: 'POST',
      path: '/applications/:id/screen',
      auth: true,
      handler: 'custom',
      entity: 'screening_reports',
      description: 'Initiate screening',
    },
    {
      method: 'GET',
      path: '/applications/:id/screening-status',
      auth: true,
      handler: 'custom',
      entity: 'screening_reports',
      description: 'Get screening status',
    },

    // Screening Reports
    {
      method: 'GET',
      path: '/screening-reports',
      auth: true,
      handler: 'crud',
      entity: 'screening_reports',
      operation: 'list',
      description: 'List screening reports',
    },
    {
      method: 'GET',
      path: '/screening-reports/:id',
      auth: true,
      handler: 'crud',
      entity: 'screening_reports',
      operation: 'get',
      description: 'Get screening report',
    },
    {
      method: 'GET',
      path: '/applications/:id/credit-report',
      auth: true,
      handler: 'custom',
      entity: 'screening_reports',
      description: 'Get credit report',
    },
    {
      method: 'GET',
      path: '/applications/:id/background-report',
      auth: true,
      handler: 'custom',
      entity: 'screening_reports',
      description: 'Get background report',
    },

    // Verification
    {
      method: 'POST',
      path: '/applications/:id/verify-income',
      auth: true,
      handler: 'custom',
      entity: 'verification_results',
      description: 'Verify income',
    },
    {
      method: 'POST',
      path: '/applications/:id/verify-employment',
      auth: true,
      handler: 'custom',
      entity: 'verification_results',
      description: 'Verify employment',
    },
    {
      method: 'GET',
      path: '/applications/:id/verifications',
      auth: true,
      handler: 'crud',
      entity: 'verification_results',
      operation: 'list',
      description: 'Get verification results',
    },

    // Documents
    {
      method: 'GET',
      path: '/applications/:id/documents',
      auth: true,
      handler: 'crud',
      entity: 'application_documents',
      operation: 'list',
      description: 'Get application documents',
    },
    {
      method: 'POST',
      path: '/applications/:id/documents',
      auth: false,
      handler: 'crud',
      entity: 'application_documents',
      operation: 'create',
      description: 'Upload application document',
    },

    // References
    {
      method: 'GET',
      path: '/applications/:id/references',
      auth: true,
      handler: 'crud',
      entity: 'references',
      operation: 'list',
      description: 'Get references',
    },
    {
      method: 'POST',
      path: '/applications/:id/references/:refId/verify',
      auth: true,
      handler: 'custom',
      entity: 'references',
      description: 'Verify reference',
    },

    // Property applications
    {
      method: 'GET',
      path: '/properties/:id/applications',
      auth: true,
      handler: 'custom',
      entity: 'tenant_applications',
      description: 'Get applications for property',
    },

    // Application fee
    {
      method: 'POST',
      path: '/applications/:id/pay-fee',
      auth: false,
      handler: 'custom',
      entity: 'tenant_applications',
      description: 'Pay application fee',
    },

    // Analytics
    {
      method: 'GET',
      path: '/screening/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'tenant_applications',
      description: 'Get screening analytics',
    },
  ],

  config: [
    {
      key: 'screeningProvider',
      label: 'Screening Provider',
      type: 'select',
      default: 'transunion',
      options: [
        { value: 'transunion', label: 'TransUnion SmartMove' },
        { value: 'experian', label: 'Experian RentBureau' },
        { value: 'equifax', label: 'Equifax' },
        { value: 'rentprep', label: 'RentPrep' },
      ],
      description: 'Background check provider',
    },
    {
      key: 'applicationFee',
      label: 'Application Fee',
      type: 'number',
      default: 50,
      description: 'Fee charged per application',
    },
    {
      key: 'requireCreditCheck',
      label: 'Require Credit Check',
      type: 'boolean',
      default: true,
      description: 'Require credit report',
    },
    {
      key: 'requireBackgroundCheck',
      label: 'Require Background Check',
      type: 'boolean',
      default: true,
      description: 'Require criminal background check',
    },
    {
      key: 'requireIncomeVerification',
      label: 'Require Income Verification',
      type: 'boolean',
      default: true,
      description: 'Require income verification',
    },
    {
      key: 'minimumCreditScore',
      label: 'Minimum Credit Score',
      type: 'number',
      default: 620,
      description: 'Minimum acceptable credit score',
    },
    {
      key: 'incomeToRentRatio',
      label: 'Income to Rent Ratio',
      type: 'number',
      default: 3,
      description: 'Required income to rent ratio (e.g., 3x rent)',
    },
    {
      key: 'evictionLookback',
      label: 'Eviction Lookback (years)',
      type: 'number',
      default: 7,
      description: 'Years to check for eviction history',
    },
    {
      key: 'criminalLookback',
      label: 'Criminal Lookback (years)',
      type: 'number',
      default: 7,
      description: 'Years to check for criminal history',
    },
    {
      key: 'requireReferences',
      label: 'Require References',
      type: 'boolean',
      default: true,
      description: 'Require landlord/personal references',
    },
    {
      key: 'numReferences',
      label: 'Number of References Required',
      type: 'number',
      default: 2,
      description: 'Minimum number of references',
    },
    {
      key: 'autoReject',
      label: 'Auto-Reject Failed Screens',
      type: 'boolean',
      default: false,
      description: 'Automatically reject applications that fail criteria',
    },
  ],
};
