/**
 * Virtual Tours Feature Definition
 *
 * 3D virtual tours and immersive media experience for real estate properties.
 * Supports 360-degree photos, video tours, and interactive floor plans.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const VIRTUAL_TOURS_FEATURE: FeatureDefinition = {
  id: 'virtual-tours',
  name: 'Virtual Tours',
  category: 'real-estate',
  description: 'Create and view 3D virtual tours, 360-degree photos, and interactive floor plans',
  icon: 'view-360',

  includedInAppTypes: [
    'real-estate',
    'property-management',
    'vacation-rental',
    'commercial-real-estate',
    'real-estate-agency',
    'mortgage-broker',
  ],

  activationKeywords: [
    'virtual tour',
    'virtual tours',
    '3d tour',
    '360 tour',
    '360 degree',
    'walkthrough',
    'virtual walkthrough',
    'matterport',
    'floor plan',
    'interactive tour',
    'video tour',
    'property tour',
    'home tour',
    'virtual viewing',
    'immersive tour',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth', 'property-listings', 'file-upload'],
  conflicts: [],

  pages: [
    {
      id: 'tour-viewer',
      route: '/tours/:id',
      section: 'frontend',
      title: 'Virtual Tour',
      authRequired: false,
      templateId: 'tour-viewer',
      components: [
        '360-viewer',
        'tour-navigation',
        'tour-hotspot',
        'floor-plan-overlay',
        'tour-controls',
        'fullscreen-toggle',
        'share-tour',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'tour-builder',
      route: '/tours/create',
      section: 'frontend',
      title: 'Create Virtual Tour',
      authRequired: true,
      roles: ['agent', 'admin', 'owner'],
      templateId: 'tour-builder',
      components: [
        'tour-uploader',
        'panorama-editor',
        'hotspot-placer',
        'tour-sequencer',
        'floor-plan-uploader',
        'room-labeler',
        'tour-preview',
      ],
      layout: 'dashboard',
    },
    {
      id: 'tour-edit',
      route: '/tours/:id/edit',
      section: 'frontend',
      title: 'Edit Virtual Tour',
      authRequired: true,
      roles: ['agent', 'admin', 'owner'],
      templateId: 'tour-edit',
      components: [
        'tour-uploader',
        'panorama-editor',
        'hotspot-placer',
        'tour-sequencer',
        'floor-plan-uploader',
        'room-labeler',
        'tour-preview',
        'tour-settings',
      ],
      layout: 'dashboard',
    },
    {
      id: 'media-library',
      route: '/media',
      section: 'frontend',
      title: 'Media Library',
      authRequired: true,
      templateId: 'media-library',
      components: [
        'media-grid',
        'media-uploader',
        'media-filters',
        'video-player',
        'image-viewer',
        'media-organizer',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-tours',
      route: '/admin/tours',
      section: 'admin',
      title: 'Manage Tours',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-tours',
      components: [
        'tours-table',
        'tour-analytics',
        'tour-moderation',
        'bulk-tour-actions',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Viewer components
    '360-viewer',
    'tour-navigation',
    'tour-hotspot',
    'floor-plan-overlay',
    'tour-controls',
    'fullscreen-toggle',
    'share-tour',
    'video-player',
    'image-viewer',

    // Builder components
    'tour-uploader',
    'panorama-editor',
    'hotspot-placer',
    'tour-sequencer',
    'floor-plan-uploader',
    'floor-plan-viewer',
    'room-labeler',
    'tour-preview',
    'tour-settings',

    // Media library components
    'media-grid',
    'media-uploader',
    'media-filters',
    'media-organizer',

    // Admin components
    'tours-table',
    'tour-analytics',
    'tour-moderation',
    'bulk-tour-actions',
  ],

  entities: [
    {
      name: 'virtual_tours',
      displayName: 'Virtual Tours',
      description: 'Virtual tour records',
      isCore: true,
    },
    {
      name: 'tour_media',
      displayName: 'Tour Media',
      description: '360 photos, videos, and panoramas for tours',
      isCore: true,
    },
    {
      name: 'hotspots',
      displayName: 'Hotspots',
      description: 'Interactive hotspots within tours',
      isCore: true,
    },
    {
      name: 'floor_plans',
      displayName: 'Floor Plans',
      description: 'Floor plan images and layouts',
      isCore: false,
    },
    {
      name: 'tour_views',
      displayName: 'Tour Views',
      description: 'Analytics for tour views',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Virtual Tours CRUD
    {
      method: 'GET',
      path: '/tours',
      auth: false,
      handler: 'crud',
      entity: 'virtual_tours',
      operation: 'list',
      description: 'List all virtual tours',
    },
    {
      method: 'GET',
      path: '/tours/:id',
      auth: false,
      handler: 'crud',
      entity: 'virtual_tours',
      operation: 'get',
      description: 'Get tour details',
    },
    {
      method: 'POST',
      path: '/tours',
      auth: true,
      handler: 'crud',
      entity: 'virtual_tours',
      operation: 'create',
      description: 'Create new virtual tour',
    },
    {
      method: 'PUT',
      path: '/tours/:id',
      auth: true,
      handler: 'crud',
      entity: 'virtual_tours',
      operation: 'update',
      description: 'Update virtual tour',
    },
    {
      method: 'DELETE',
      path: '/tours/:id',
      auth: true,
      handler: 'crud',
      entity: 'virtual_tours',
      operation: 'delete',
      description: 'Delete virtual tour',
    },

    // Tour Media
    {
      method: 'GET',
      path: '/tours/:id/media',
      auth: false,
      handler: 'crud',
      entity: 'tour_media',
      operation: 'list',
      description: 'Get tour media',
    },
    {
      method: 'POST',
      path: '/tours/:id/media',
      auth: true,
      handler: 'crud',
      entity: 'tour_media',
      operation: 'create',
      description: 'Add media to tour',
    },
    {
      method: 'PUT',
      path: '/tours/:tourId/media/:id',
      auth: true,
      handler: 'crud',
      entity: 'tour_media',
      operation: 'update',
      description: 'Update tour media',
    },
    {
      method: 'DELETE',
      path: '/tours/:tourId/media/:id',
      auth: true,
      handler: 'crud',
      entity: 'tour_media',
      operation: 'delete',
      description: 'Delete tour media',
    },
    {
      method: 'PUT',
      path: '/tours/:id/media/reorder',
      auth: true,
      handler: 'custom',
      entity: 'tour_media',
      description: 'Reorder tour media',
    },

    // Hotspots
    {
      method: 'GET',
      path: '/tours/:id/hotspots',
      auth: false,
      handler: 'crud',
      entity: 'hotspots',
      operation: 'list',
      description: 'Get tour hotspots',
    },
    {
      method: 'POST',
      path: '/tours/:id/hotspots',
      auth: true,
      handler: 'crud',
      entity: 'hotspots',
      operation: 'create',
      description: 'Add hotspot to tour',
    },
    {
      method: 'PUT',
      path: '/tours/:tourId/hotspots/:id',
      auth: true,
      handler: 'crud',
      entity: 'hotspots',
      operation: 'update',
      description: 'Update hotspot',
    },
    {
      method: 'DELETE',
      path: '/tours/:tourId/hotspots/:id',
      auth: true,
      handler: 'crud',
      entity: 'hotspots',
      operation: 'delete',
      description: 'Delete hotspot',
    },

    // Floor Plans
    {
      method: 'GET',
      path: '/tours/:id/floor-plan',
      auth: false,
      handler: 'crud',
      entity: 'floor_plans',
      operation: 'get',
      description: 'Get tour floor plan',
    },
    {
      method: 'POST',
      path: '/tours/:id/floor-plan',
      auth: true,
      handler: 'crud',
      entity: 'floor_plans',
      operation: 'create',
      description: 'Upload floor plan',
    },
    {
      method: 'DELETE',
      path: '/tours/:id/floor-plan',
      auth: true,
      handler: 'crud',
      entity: 'floor_plans',
      operation: 'delete',
      description: 'Delete floor plan',
    },

    // Property tours
    {
      method: 'GET',
      path: '/properties/:id/tours',
      auth: false,
      handler: 'custom',
      entity: 'virtual_tours',
      description: 'Get tours for a property',
    },
    {
      method: 'POST',
      path: '/properties/:id/tours',
      auth: true,
      handler: 'custom',
      entity: 'virtual_tours',
      description: 'Create tour for property',
    },

    // Analytics
    {
      method: 'POST',
      path: '/tours/:id/view',
      auth: false,
      handler: 'custom',
      entity: 'tour_views',
      description: 'Record tour view',
    },
    {
      method: 'GET',
      path: '/tours/:id/analytics',
      auth: true,
      handler: 'aggregate',
      entity: 'tour_views',
      description: 'Get tour analytics',
    },

    // Embed
    {
      method: 'GET',
      path: '/tours/:id/embed',
      auth: false,
      handler: 'custom',
      entity: 'virtual_tours',
      description: 'Get embed code for tour',
    },
  ],

  config: [
    {
      key: 'maxPanoramasPerTour',
      label: 'Maximum Panoramas Per Tour',
      type: 'number',
      default: 50,
      description: 'Maximum number of 360 photos per tour',
    },
    {
      key: 'enableFloorPlans',
      label: 'Enable Floor Plans',
      type: 'boolean',
      default: true,
      description: 'Allow floor plan uploads and overlay',
    },
    {
      key: 'enableVideoTours',
      label: 'Enable Video Tours',
      type: 'boolean',
      default: true,
      description: 'Allow video tour uploads',
    },
    {
      key: 'enableAutoRotate',
      label: 'Enable Auto-Rotate',
      type: 'boolean',
      default: true,
      description: 'Auto-rotate panoramas when idle',
    },
    {
      key: 'defaultStartScene',
      label: 'Default Start Scene',
      type: 'select',
      default: 'first',
      options: [
        { value: 'first', label: 'First Scene' },
        { value: 'exterior', label: 'Exterior' },
        { value: 'living', label: 'Living Room' },
      ],
      description: 'Default starting scene for tours',
    },
    {
      key: 'enableBranding',
      label: 'Enable Custom Branding',
      type: 'boolean',
      default: false,
      description: 'Allow custom branding on tour viewer',
    },
    {
      key: 'maxVideoSize',
      label: 'Maximum Video Size (MB)',
      type: 'number',
      default: 500,
      description: 'Maximum video file size in megabytes',
    },
  ],
};
