import { AppBlueprint } from '../../../interfaces/app-builder.types';

export function generatePackageJson(blueprint: AppBlueprint): string {
  return JSON.stringify({
    name: blueprint.metadata.name.toLowerCase().replace(/\s+/g, '-'),
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc && vite build',
      preview: 'vite preview',
      lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0',
    },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      'react-router-dom': '^6.20.0',
      '@tanstack/react-query': '^5.12.0',
      '@tanstack/react-query-devtools': '^5.12.0',
      'lucide-react': '^0.294.0',
      'class-variance-authority': '^0.7.0',
      clsx: '^2.0.0',
      'tailwind-merge': '^2.0.0',
      'tailwindcss-animate': '^1.0.7',
      '@radix-ui/react-accordion': '^1.1.2',
      '@radix-ui/react-alert-dialog': '^1.0.5',
      '@radix-ui/react-avatar': '^1.0.4',
      '@radix-ui/react-checkbox': '^1.0.4',
      '@radix-ui/react-dialog': '^1.0.5',
      '@radix-ui/react-dropdown-menu': '^2.0.6',
      '@radix-ui/react-label': '^2.0.2',
      '@radix-ui/react-popover': '^1.0.7',
      '@radix-ui/react-select': '^2.0.0',
      '@radix-ui/react-separator': '^1.0.3',
      '@radix-ui/react-slider': '^1.1.2',
      '@radix-ui/react-switch': '^1.0.3',
      '@radix-ui/react-tabs': '^1.0.4',
      '@radix-ui/react-tooltip': '^1.0.7',
      sonner: '^1.3.1',
      'date-fns': '^2.30.0',
      recharts: '^2.10.0',
      'react-markdown': '^9.0.0',
      'react-syntax-highlighter': '^15.5.0',
    },
    devDependencies: {
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      '@types/node': '^20.10.0',
      '@types/react-syntax-highlighter': '^15.5.0',
      '@typescript-eslint/eslint-plugin': '^6.13.0',
      '@typescript-eslint/parser': '^6.13.0',
      '@vitejs/plugin-react': '^4.2.0',
      autoprefixer: '^10.4.16',
      eslint: '^8.55.0',
      'eslint-plugin-react-hooks': '^4.6.0',
      'eslint-plugin-react-refresh': '^0.4.5',
      postcss: '^8.4.32',
      tailwindcss: '^3.3.6',
      typescript: '^5.3.0',
      vite: '^5.0.0',
    },
  }, null, 2);
}
