/**
 * Backstage Access Feature Definition
 *
 * VIP and backstage pass management for entertainment venues.
 * Supports meet-and-greets, VIP experiences, backstage tours, and premium access.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const BACKSTAGE_ACCESS_FEATURE: FeatureDefinition = {
  id: 'backstage-access',
  name: 'Backstage Access',
  category: 'business',
  description: 'Manage VIP experiences and backstage passes with scheduling, capacity limits, and access control',
  icon: 'key',

  includedInAppTypes: [
    'entertainment',
    'concert-venue',
    'theater',
    'music-venue',
    'festival',
    'arena',
    'sports-venue',
    'event-management',
    'vip-experiences',
  ],

  activationKeywords: [
    'backstage access',
    'backstage pass',
    'vip access',
    'vip pass',
    'meet and greet',
    'vip experience',
    'backstage tour',
    'premium access',
    'all access pass',
    'vip package',
    'exclusive access',
    'artist meet',
    'green room access',
    'vip lounge',
    'premium experience',
  ],

  enabledByDefault: false,
  optional: true,

  dependencies: ['user-auth', 'ticket-sales', 'notifications'],
  conflicts: [],

  pages: [
    {
      id: 'vip-experiences-browse',
      route: '/vip-experiences',
      section: 'frontend',
      title: 'VIP Experiences',
      authRequired: false,
      templateId: 'vip-experiences-browse',
      components: [
        'experiences-grid',
        'experience-card',
        'event-filter',
        'experience-type-filter',
        'price-filter',
        'availability-indicator',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'vip-experience-detail',
      route: '/vip-experiences/:id',
      section: 'frontend',
      title: 'VIP Experience Details',
      authRequired: false,
      templateId: 'vip-experience-detail',
      components: [
        'experience-header',
        'experience-gallery',
        'experience-description',
        'whats-included',
        'experience-timeline',
        'terms-conditions',
        'pricing-display',
        'availability-calendar',
        'purchase-button',
        'share-experience',
      ],
      layout: 'default',
    },
    {
      id: 'vip-purchase',
      route: '/vip-experiences/:id/purchase',
      section: 'frontend',
      title: 'Purchase VIP Experience',
      authRequired: true,
      templateId: 'vip-purchase',
      components: [
        'experience-summary',
        'date-time-selector',
        'guest-count-selector',
        'guest-info-form',
        'special-requests',
        'waiver-agreement',
        'payment-form',
        'order-summary',
      ],
      layout: 'default',
    },
    {
      id: 'my-vip-passes',
      route: '/my-vip-passes',
      section: 'frontend',
      title: 'My VIP Passes',
      authRequired: true,
      templateId: 'my-vip-passes',
      components: [
        'passes-list',
        'pass-card',
        'upcoming-experiences',
        'past-experiences',
        'pass-qr-code',
        'check-in-instructions',
        'contact-vip-support',
      ],
      layout: 'dashboard',
    },
    {
      id: 'vip-check-in',
      route: '/vip-check-in',
      section: 'frontend',
      title: 'VIP Check-In',
      authRequired: true,
      roles: ['admin', 'vip-staff'],
      templateId: 'vip-check-in',
      components: [
        'pass-scanner',
        'manual-lookup',
        'guest-verification',
        'check-in-confirmation',
        'wristband-assignment',
        'group-check-in',
        'late-arrival-handling',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'admin-vip-experiences',
      route: '/admin/vip-experiences',
      section: 'admin',
      title: 'Manage VIP Experiences',
      authRequired: true,
      roles: ['admin', 'vip-manager'],
      templateId: 'admin-vip-experiences',
      components: [
        'experiences-table',
        'experience-stats',
        'revenue-summary',
        'capacity-overview',
        'status-filter',
        'event-filter',
        'bulk-actions',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-vip-experience-create',
      route: '/admin/vip-experiences/create',
      section: 'admin',
      title: 'Create VIP Experience',
      authRequired: true,
      roles: ['admin', 'vip-manager'],
      templateId: 'admin-vip-experience-create',
      components: [
        'experience-form',
        'description-editor',
        'inclusions-builder',
        'timeline-builder',
        'pricing-config',
        'capacity-settings',
        'availability-config',
        'media-uploader',
        'terms-editor',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-vip-guests',
      route: '/admin/vip-experiences/:experienceId/guests',
      section: 'admin',
      title: 'Guest Management',
      authRequired: true,
      roles: ['admin', 'vip-manager', 'vip-staff'],
      templateId: 'admin-vip-guests',
      components: [
        'guest-list',
        'check-in-status',
        'guest-details-modal',
        'special-requests-view',
        'dietary-restrictions',
        'communication-panel',
        'add-guest-modal',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-vip-schedule',
      route: '/admin/vip-experiences/schedule',
      section: 'admin',
      title: 'VIP Schedule',
      authRequired: true,
      roles: ['admin', 'vip-manager'],
      templateId: 'admin-vip-schedule',
      components: [
        'vip-calendar',
        'day-schedule',
        'staff-assignments',
        'venue-allocation',
        'timing-manager',
        'run-of-show',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Browse components
    'experiences-grid',
    'experience-card',
    'event-filter',
    'experience-type-filter',
    'price-filter',
    'availability-indicator',
    'sort-dropdown',
    'pagination',

    // Detail components
    'experience-header',
    'experience-gallery',
    'experience-description',
    'whats-included',
    'experience-timeline',
    'terms-conditions',
    'pricing-display',
    'availability-calendar',
    'purchase-button',
    'share-experience',

    // Purchase components
    'experience-summary',
    'date-time-selector',
    'guest-count-selector',
    'guest-info-form',
    'special-requests',
    'waiver-agreement',
    'payment-form',
    'order-summary',

    // My passes components
    'passes-list',
    'pass-card',
    'upcoming-experiences',
    'past-experiences',
    'pass-qr-code',
    'check-in-instructions',
    'contact-vip-support',

    // Check-in components
    'pass-scanner',
    'manual-lookup',
    'guest-verification',
    'check-in-confirmation',
    'wristband-assignment',
    'group-check-in',
    'late-arrival-handling',

    // Admin management components
    'experiences-table',
    'experience-stats',
    'revenue-summary',
    'capacity-overview',
    'status-filter',
    'bulk-actions',

    // Experience creation components
    'experience-form',
    'description-editor',
    'inclusions-builder',
    'timeline-builder',
    'pricing-config',
    'capacity-settings',
    'availability-config',
    'media-uploader',
    'terms-editor',

    // Guest management components
    'guest-list',
    'check-in-status',
    'guest-details-modal',
    'special-requests-view',
    'dietary-restrictions',
    'communication-panel',
    'add-guest-modal',

    // Schedule components
    'vip-calendar',
    'day-schedule',
    'staff-assignments',
    'venue-allocation',
    'timing-manager',
    'run-of-show',
  ],

  entities: [
    {
      name: 'vip_experiences',
      displayName: 'VIP Experiences',
      description: 'VIP and backstage experience offerings',
      isCore: true,
    },
    {
      name: 'vip_passes',
      displayName: 'VIP Passes',
      description: 'Purchased VIP/backstage passes',
      isCore: true,
    },
    {
      name: 'vip_guests',
      displayName: 'VIP Guests',
      description: 'Guest records for VIP experiences',
      isCore: true,
    },
    {
      name: 'vip_check_ins',
      displayName: 'VIP Check-ins',
      description: 'Check-in records for VIP guests',
      isCore: true,
    },
    {
      name: 'experience_inclusions',
      displayName: 'Experience Inclusions',
      description: 'Items and perks included in experiences',
      isCore: true,
    },
    {
      name: 'vip_schedules',
      displayName: 'VIP Schedules',
      description: 'Scheduling for VIP experiences',
      isCore: false,
    },
    {
      name: 'vip_waivers',
      displayName: 'VIP Waivers',
      description: 'Signed waivers for VIP experiences',
      isCore: false,
    },
    {
      name: 'vip_staff_assignments',
      displayName: 'Staff Assignments',
      description: 'Staff assigned to VIP experiences',
      isCore: false,
    },
  ],

  apiRoutes: [
    // VIP Experiences
    {
      method: 'GET',
      path: '/vip-experiences',
      auth: false,
      handler: 'crud',
      entity: 'vip_experiences',
      operation: 'list',
      description: 'List VIP experiences',
    },
    {
      method: 'GET',
      path: '/vip-experiences/:id',
      auth: false,
      handler: 'crud',
      entity: 'vip_experiences',
      operation: 'get',
      description: 'Get experience details',
    },
    {
      method: 'POST',
      path: '/vip-experiences',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vip_experiences',
      operation: 'create',
      description: 'Create VIP experience',
    },
    {
      method: 'PUT',
      path: '/vip-experiences/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vip_experiences',
      operation: 'update',
      description: 'Update VIP experience',
    },
    {
      method: 'DELETE',
      path: '/vip-experiences/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'vip_experiences',
      operation: 'delete',
      description: 'Delete VIP experience',
    },

    // VIP Passes
    {
      method: 'GET',
      path: '/vip-passes',
      auth: true,
      handler: 'crud',
      entity: 'vip_passes',
      operation: 'list',
      description: 'List user VIP passes',
    },
    {
      method: 'GET',
      path: '/vip-passes/:id',
      auth: true,
      handler: 'crud',
      entity: 'vip_passes',
      operation: 'get',
      description: 'Get pass details',
    },
    {
      method: 'POST',
      path: '/vip-passes',
      auth: true,
      handler: 'crud',
      entity: 'vip_passes',
      operation: 'create',
      description: 'Purchase VIP pass',
    },

    // VIP Guests
    {
      method: 'GET',
      path: '/vip-passes/:passId/guests',
      auth: true,
      handler: 'crud',
      entity: 'vip_guests',
      operation: 'list',
      description: 'List pass guests',
    },
    {
      method: 'POST',
      path: '/vip-passes/:passId/guests',
      auth: true,
      handler: 'crud',
      entity: 'vip_guests',
      operation: 'create',
      description: 'Add guest to pass',
    },
    {
      method: 'PUT',
      path: '/vip-passes/:passId/guests/:id',
      auth: true,
      handler: 'crud',
      entity: 'vip_guests',
      operation: 'update',
      description: 'Update guest info',
    },
    {
      method: 'DELETE',
      path: '/vip-passes/:passId/guests/:id',
      auth: true,
      handler: 'crud',
      entity: 'vip_guests',
      operation: 'delete',
      description: 'Remove guest from pass',
    },

    // Check-in
    {
      method: 'POST',
      path: '/vip-check-in/scan',
      auth: true,
      role: 'vip-staff',
      handler: 'custom',
      entity: 'vip_check_ins',
      description: 'Scan and check in pass',
    },
    {
      method: 'POST',
      path: '/vip-check-in/manual',
      auth: true,
      role: 'vip-staff',
      handler: 'custom',
      entity: 'vip_check_ins',
      description: 'Manual check-in lookup',
    },
    {
      method: 'GET',
      path: '/vip-experiences/:experienceId/check-ins',
      auth: true,
      role: 'vip-staff',
      handler: 'crud',
      entity: 'vip_check_ins',
      operation: 'list',
      description: 'List check-ins for experience',
    },

    // Availability
    {
      method: 'GET',
      path: '/vip-experiences/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'vip_experiences',
      description: 'Get experience availability',
    },

    // Waivers
    {
      method: 'GET',
      path: '/vip-passes/:passId/waiver',
      auth: true,
      handler: 'crud',
      entity: 'vip_waivers',
      operation: 'get',
      description: 'Get waiver status',
    },
    {
      method: 'POST',
      path: '/vip-passes/:passId/waiver',
      auth: true,
      handler: 'crud',
      entity: 'vip_waivers',
      operation: 'create',
      description: 'Sign waiver',
    },

    // Inclusions
    {
      method: 'GET',
      path: '/vip-experiences/:experienceId/inclusions',
      auth: false,
      handler: 'crud',
      entity: 'experience_inclusions',
      operation: 'list',
      description: 'List experience inclusions',
    },
    {
      method: 'PUT',
      path: '/vip-experiences/:experienceId/inclusions',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'experience_inclusions',
      description: 'Update inclusions',
    },

    // Staff Assignments
    {
      method: 'GET',
      path: '/vip-experiences/:experienceId/staff',
      auth: true,
      role: 'vip-manager',
      handler: 'crud',
      entity: 'vip_staff_assignments',
      operation: 'list',
      description: 'List staff assignments',
    },
    {
      method: 'POST',
      path: '/vip-experiences/:experienceId/staff',
      auth: true,
      role: 'vip-manager',
      handler: 'crud',
      entity: 'vip_staff_assignments',
      operation: 'create',
      description: 'Assign staff',
    },

    // Schedule
    {
      method: 'GET',
      path: '/vip-schedule',
      auth: true,
      role: 'vip-staff',
      handler: 'custom',
      entity: 'vip_schedules',
      description: 'Get VIP schedule',
    },
    {
      method: 'GET',
      path: '/vip-schedule/:date',
      auth: true,
      role: 'vip-staff',
      handler: 'custom',
      entity: 'vip_schedules',
      description: 'Get schedule for date',
    },

    // Admin Reports
    {
      method: 'GET',
      path: '/vip-experiences/reports/revenue',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'vip_passes',
      description: 'Get VIP revenue report',
    },
    {
      method: 'GET',
      path: '/vip-experiences/reports/attendance',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'vip_check_ins',
      description: 'Get attendance report',
    },
  ],

  config: [
    {
      key: 'requireWaiver',
      label: 'Require Waiver Signature',
      type: 'boolean',
      default: true,
      description: 'Require waiver before VIP experience',
    },
    {
      key: 'checkInWindowMinutes',
      label: 'Check-in Window (minutes)',
      type: 'number',
      default: 30,
      description: 'Minutes before experience when check-in opens',
    },
    {
      key: 'lateArrivalGraceMinutes',
      label: 'Late Arrival Grace Period (minutes)',
      type: 'number',
      default: 15,
      description: 'Minutes late arrival is permitted',
    },
    {
      key: 'maxGuestsPerPass',
      label: 'Maximum Guests Per Pass',
      type: 'number',
      default: 4,
      description: 'Maximum guests allowed per VIP pass',
    },
    {
      key: 'enableSpecialRequests',
      label: 'Enable Special Requests',
      type: 'boolean',
      default: true,
      description: 'Allow guests to submit special requests',
    },
    {
      key: 'enableDietaryInfo',
      label: 'Collect Dietary Information',
      type: 'boolean',
      default: true,
      description: 'Collect dietary restrictions for catered experiences',
    },
    {
      key: 'photoOpDuration',
      label: 'Default Photo Op Duration (minutes)',
      type: 'number',
      default: 5,
      description: 'Default duration for photo opportunities',
    },
    {
      key: 'requireIdVerification',
      label: 'Require ID Verification',
      type: 'boolean',
      default: true,
      description: 'Require ID verification at check-in',
    },
  ],
};
