/**
 * Box Office Feature Definition
 *
 * Complete box office management for entertainment venues.
 * Supports walk-up sales, will-call, refunds, and daily reconciliation.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const BOX_OFFICE_FEATURE: FeatureDefinition = {
  id: 'box-office',
  name: 'Box Office',
  category: 'business',
  description: 'Manage box office operations including walk-up sales, will-call, and daily reporting',
  icon: 'store',

  includedInAppTypes: [
    'entertainment',
    'theater',
    'concert-venue',
    'sports-venue',
    'cinema',
    'arena',
    'performing-arts',
    'event-venue',
    'ticketing-platform',
  ],

  activationKeywords: [
    'box office',
    'ticket window',
    'walk-up sales',
    'will call',
    'ticket booth',
    'box office sales',
    'cash register',
    'ticket counter',
    'point of sale',
    'ticket pos',
    'day of sales',
    'door sales',
    'on-site sales',
    'ticket pickup',
    'box office management',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'ticket-sales', 'payments'],
  conflicts: [],

  pages: [
    {
      id: 'box-office-pos',
      route: '/box-office',
      section: 'frontend',
      title: 'Box Office',
      authRequired: true,
      roles: ['admin', 'box-office-staff'],
      templateId: 'box-office-pos',
      components: [
        'event-selector',
        'quick-sale-panel',
        'ticket-type-buttons',
        'quantity-keypad',
        'cart-summary',
        'payment-processor',
        'receipt-printer',
        'customer-lookup',
        'will-call-search',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'box-office-will-call',
      route: '/box-office/will-call',
      section: 'frontend',
      title: 'Will Call',
      authRequired: true,
      roles: ['admin', 'box-office-staff'],
      templateId: 'box-office-will-call',
      components: [
        'will-call-search',
        'order-lookup',
        'ticket-verification',
        'id-check-form',
        'ticket-release',
        'reprint-ticket',
        'will-call-queue',
      ],
      layout: 'default',
    },
    {
      id: 'box-office-refunds',
      route: '/box-office/refunds',
      section: 'frontend',
      title: 'Refunds & Exchanges',
      authRequired: true,
      roles: ['admin', 'box-office-manager'],
      templateId: 'box-office-refunds',
      components: [
        'order-search',
        'ticket-scanner',
        'refund-form',
        'exchange-form',
        'refund-reason-selector',
        'refund-approval',
        'refund-receipt',
      ],
      layout: 'default',
    },
    {
      id: 'box-office-reports',
      route: '/box-office/reports',
      section: 'frontend',
      title: 'Box Office Reports',
      authRequired: true,
      roles: ['admin', 'box-office-manager'],
      templateId: 'box-office-reports',
      components: [
        'daily-sales-summary',
        'event-sales-report',
        'staff-sales-report',
        'payment-method-breakdown',
        'cash-drawer-reconciliation',
        'report-export',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-box-office',
      route: '/admin/box-office',
      section: 'admin',
      title: 'Box Office Management',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-box-office',
      components: [
        'station-management',
        'staff-management',
        'shift-scheduler',
        'drawer-management',
        'pricing-override',
        'comp-ticket-manager',
        'audit-log',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-box-office-settings',
      route: '/admin/box-office/settings',
      section: 'admin',
      title: 'Box Office Settings',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-box-office-settings',
      components: [
        'station-config',
        'printer-config',
        'payment-config',
        'receipt-template',
        'shift-settings',
        'security-settings',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-cash-reconciliation',
      route: '/admin/box-office/reconciliation',
      section: 'admin',
      title: 'Cash Reconciliation',
      authRequired: true,
      roles: ['admin', 'box-office-manager'],
      templateId: 'admin-cash-reconciliation',
      components: [
        'shift-selector',
        'expected-vs-actual',
        'variance-report',
        'drawer-count-form',
        'reconciliation-notes',
        'manager-approval',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // POS components
    'event-selector',
    'quick-sale-panel',
    'ticket-type-buttons',
    'quantity-keypad',
    'cart-summary',
    'payment-processor',
    'receipt-printer',
    'customer-lookup',
    'will-call-search',

    // Will-call components
    'order-lookup',
    'ticket-verification',
    'id-check-form',
    'ticket-release',
    'reprint-ticket',
    'will-call-queue',

    // Refund components
    'order-search',
    'ticket-scanner',
    'refund-form',
    'exchange-form',
    'refund-reason-selector',
    'refund-approval',
    'refund-receipt',

    // Report components
    'daily-sales-summary',
    'event-sales-report',
    'staff-sales-report',
    'payment-method-breakdown',
    'cash-drawer-reconciliation',
    'report-export',

    // Admin management components
    'station-management',
    'staff-management',
    'shift-scheduler',
    'drawer-management',
    'pricing-override',
    'comp-ticket-manager',
    'audit-log',

    // Settings components
    'station-config',
    'printer-config',
    'payment-config',
    'receipt-template',
    'shift-settings',
    'security-settings',

    // Reconciliation components
    'shift-selector',
    'expected-vs-actual',
    'variance-report',
    'drawer-count-form',
    'reconciliation-notes',
    'manager-approval',
  ],

  entities: [
    {
      name: 'box_office_stations',
      displayName: 'Box Office Stations',
      description: 'Physical box office station/terminal records',
      isCore: true,
    },
    {
      name: 'box_office_transactions',
      displayName: 'Box Office Transactions',
      description: 'All box office sales transactions',
      isCore: true,
    },
    {
      name: 'box_office_shifts',
      displayName: 'Box Office Shifts',
      description: 'Staff shift records with drawer assignments',
      isCore: true,
    },
    {
      name: 'cash_drawers',
      displayName: 'Cash Drawers',
      description: 'Cash drawer tracking and reconciliation',
      isCore: true,
    },
    {
      name: 'will_call_orders',
      displayName: 'Will Call Orders',
      description: 'Orders designated for will-call pickup',
      isCore: true,
    },
    {
      name: 'refund_requests',
      displayName: 'Refund Requests',
      description: 'Ticket refund and exchange requests',
      isCore: false,
    },
    {
      name: 'comp_tickets',
      displayName: 'Comp Tickets',
      description: 'Complimentary ticket issuance records',
      isCore: false,
    },
    {
      name: 'box_office_audit_log',
      displayName: 'Audit Log',
      description: 'Audit trail for box office operations',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Transactions
    {
      method: 'GET',
      path: '/box-office/transactions',
      auth: true,
      role: 'box-office-staff',
      handler: 'crud',
      entity: 'box_office_transactions',
      operation: 'list',
      description: 'List transactions',
    },
    {
      method: 'GET',
      path: '/box-office/transactions/:id',
      auth: true,
      role: 'box-office-staff',
      handler: 'crud',
      entity: 'box_office_transactions',
      operation: 'get',
      description: 'Get transaction details',
    },
    {
      method: 'POST',
      path: '/box-office/transactions',
      auth: true,
      role: 'box-office-staff',
      handler: 'crud',
      entity: 'box_office_transactions',
      operation: 'create',
      description: 'Create sale transaction',
    },

    // Quick Sale
    {
      method: 'POST',
      path: '/box-office/quick-sale',
      auth: true,
      role: 'box-office-staff',
      handler: 'custom',
      entity: 'box_office_transactions',
      description: 'Process quick sale',
    },

    // Will Call
    {
      method: 'GET',
      path: '/box-office/will-call',
      auth: true,
      role: 'box-office-staff',
      handler: 'crud',
      entity: 'will_call_orders',
      operation: 'list',
      description: 'List will-call orders',
    },
    {
      method: 'GET',
      path: '/box-office/will-call/search',
      auth: true,
      role: 'box-office-staff',
      handler: 'custom',
      entity: 'will_call_orders',
      description: 'Search will-call orders',
    },
    {
      method: 'PUT',
      path: '/box-office/will-call/:id/release',
      auth: true,
      role: 'box-office-staff',
      handler: 'custom',
      entity: 'will_call_orders',
      description: 'Release will-call tickets',
    },

    // Refunds
    {
      method: 'GET',
      path: '/box-office/refunds',
      auth: true,
      role: 'box-office-manager',
      handler: 'crud',
      entity: 'refund_requests',
      operation: 'list',
      description: 'List refund requests',
    },
    {
      method: 'POST',
      path: '/box-office/refunds',
      auth: true,
      role: 'box-office-staff',
      handler: 'crud',
      entity: 'refund_requests',
      operation: 'create',
      description: 'Create refund request',
    },
    {
      method: 'PUT',
      path: '/box-office/refunds/:id/approve',
      auth: true,
      role: 'box-office-manager',
      handler: 'custom',
      entity: 'refund_requests',
      description: 'Approve refund',
    },
    {
      method: 'PUT',
      path: '/box-office/refunds/:id/process',
      auth: true,
      role: 'box-office-manager',
      handler: 'custom',
      entity: 'refund_requests',
      description: 'Process refund',
    },

    // Shifts
    {
      method: 'GET',
      path: '/box-office/shifts',
      auth: true,
      role: 'box-office-staff',
      handler: 'crud',
      entity: 'box_office_shifts',
      operation: 'list',
      description: 'List shifts',
    },
    {
      method: 'POST',
      path: '/box-office/shifts/start',
      auth: true,
      role: 'box-office-staff',
      handler: 'custom',
      entity: 'box_office_shifts',
      description: 'Start shift',
    },
    {
      method: 'PUT',
      path: '/box-office/shifts/:id/end',
      auth: true,
      role: 'box-office-staff',
      handler: 'custom',
      entity: 'box_office_shifts',
      description: 'End shift',
    },

    // Cash Drawers
    {
      method: 'GET',
      path: '/box-office/drawers',
      auth: true,
      role: 'box-office-staff',
      handler: 'crud',
      entity: 'cash_drawers',
      operation: 'list',
      description: 'List cash drawers',
    },
    {
      method: 'POST',
      path: '/box-office/drawers/:id/count',
      auth: true,
      role: 'box-office-staff',
      handler: 'custom',
      entity: 'cash_drawers',
      description: 'Submit drawer count',
    },
    {
      method: 'PUT',
      path: '/box-office/drawers/:id/reconcile',
      auth: true,
      role: 'box-office-manager',
      handler: 'custom',
      entity: 'cash_drawers',
      description: 'Reconcile drawer',
    },

    // Comp Tickets
    {
      method: 'GET',
      path: '/box-office/comps',
      auth: true,
      role: 'box-office-manager',
      handler: 'crud',
      entity: 'comp_tickets',
      operation: 'list',
      description: 'List comp tickets',
    },
    {
      method: 'POST',
      path: '/box-office/comps',
      auth: true,
      role: 'box-office-manager',
      handler: 'crud',
      entity: 'comp_tickets',
      operation: 'create',
      description: 'Issue comp tickets',
    },

    // Reports
    {
      method: 'GET',
      path: '/box-office/reports/daily',
      auth: true,
      role: 'box-office-manager',
      handler: 'custom',
      entity: 'box_office_transactions',
      description: 'Get daily report',
    },
    {
      method: 'GET',
      path: '/box-office/reports/event/:eventId',
      auth: true,
      role: 'box-office-manager',
      handler: 'custom',
      entity: 'box_office_transactions',
      description: 'Get event report',
    },
    {
      method: 'GET',
      path: '/box-office/reports/staff/:staffId',
      auth: true,
      role: 'box-office-manager',
      handler: 'custom',
      entity: 'box_office_transactions',
      description: 'Get staff report',
    },

    // Stations
    {
      method: 'GET',
      path: '/box-office/stations',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'box_office_stations',
      operation: 'list',
      description: 'List stations',
    },
    {
      method: 'POST',
      path: '/box-office/stations',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'box_office_stations',
      operation: 'create',
      description: 'Create station',
    },
  ],

  config: [
    {
      key: 'requireManagerApprovalForRefunds',
      label: 'Require Manager Approval for Refunds',
      type: 'boolean',
      default: true,
      description: 'Require manager approval for all refunds',
    },
    {
      key: 'maxRefundAmount',
      label: 'Maximum Refund Without Approval',
      type: 'number',
      default: 100,
      description: 'Maximum refund amount without manager approval',
    },
    {
      key: 'enableCashPayments',
      label: 'Enable Cash Payments',
      type: 'boolean',
      default: true,
      description: 'Accept cash payments at box office',
    },
    {
      key: 'enableCardPayments',
      label: 'Enable Card Payments',
      type: 'boolean',
      default: true,
      description: 'Accept card payments at box office',
    },
    {
      key: 'startingDrawerAmount',
      label: 'Starting Drawer Amount',
      type: 'number',
      default: 200,
      description: 'Default starting cash amount for drawers',
    },
    {
      key: 'requireIdForWillCall',
      label: 'Require ID for Will Call',
      type: 'boolean',
      default: true,
      description: 'Require ID verification for will-call pickup',
    },
    {
      key: 'printReceiptByDefault',
      label: 'Print Receipt by Default',
      type: 'boolean',
      default: true,
      description: 'Automatically print receipts for sales',
    },
    {
      key: 'shiftAutoCloseHours',
      label: 'Shift Auto-Close Hours',
      type: 'number',
      default: 12,
      description: 'Automatically close shifts after this many hours',
    },
  ],
};
