/**
 * Performer Profiles Feature Definition
 *
 * Artist and performer management for entertainment applications.
 * Supports musicians, actors, comedians, speakers, and all performance artists.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const PERFORMER_PROFILES_FEATURE: FeatureDefinition = {
  id: 'performer-profiles',
  name: 'Performer Profiles',
  category: 'business',
  description: 'Manage artist and performer profiles with bios, media, and booking information',
  icon: 'user-star',

  includedInAppTypes: [
    'entertainment',
    'talent-agency',
    'event-management',
    'theater',
    'concert-venue',
    'music-venue',
    'comedy-club',
    'booking-agency',
    'artist-management',
  ],

  activationKeywords: [
    'performer profile',
    'artist profile',
    'talent profile',
    'musician profile',
    'actor profile',
    'performer management',
    'artist management',
    'talent management',
    'entertainer profile',
    'performer bio',
    'artist bio',
    'performer roster',
    'talent roster',
    'artist roster',
    'performer directory',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'file-upload'],
  conflicts: [],

  pages: [
    {
      id: 'performers-browse',
      route: '/performers',
      section: 'frontend',
      title: 'Browse Performers',
      authRequired: false,
      templateId: 'performers-browse',
      components: [
        'performer-grid',
        'performer-card',
        'genre-filter',
        'performance-type-filter',
        'location-filter',
        'availability-filter',
        'search-bar',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'performer-detail',
      route: '/performers/:id',
      section: 'frontend',
      title: 'Performer Profile',
      authRequired: false,
      templateId: 'performer-detail',
      components: [
        'performer-header',
        'performer-bio',
        'performer-gallery',
        'performer-videos',
        'performer-music-player',
        'upcoming-shows',
        'past-performances',
        'reviews-section',
        'booking-inquiry-form',
        'social-links',
        'share-profile',
      ],
      layout: 'default',
    },
    {
      id: 'performer-dashboard',
      route: '/performer/dashboard',
      section: 'frontend',
      title: 'Performer Dashboard',
      authRequired: true,
      roles: ['performer'],
      templateId: 'performer-dashboard',
      components: [
        'upcoming-shows-widget',
        'booking-requests-widget',
        'profile-views-stats',
        'earnings-summary',
        'quick-actions',
        'recent-reviews',
      ],
      layout: 'dashboard',
    },
    {
      id: 'performer-profile-edit',
      route: '/performer/profile/edit',
      section: 'frontend',
      title: 'Edit Profile',
      authRequired: true,
      roles: ['performer'],
      templateId: 'performer-profile-edit',
      components: [
        'basic-info-form',
        'bio-editor',
        'genre-tags-selector',
        'photo-gallery-manager',
        'video-links-manager',
        'music-links-manager',
        'social-links-manager',
        'booking-info-form',
        'availability-calendar',
        'rider-requirements',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-performers',
      route: '/admin/performers',
      section: 'admin',
      title: 'Manage Performers',
      authRequired: true,
      roles: ['admin', 'talent-manager'],
      templateId: 'admin-performers',
      components: [
        'performers-table',
        'performer-status-filter',
        'verification-status',
        'bulk-actions',
        'performer-stats',
        'featured-toggle',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-performer-create',
      route: '/admin/performers/create',
      section: 'admin',
      title: 'Add Performer',
      authRequired: true,
      roles: ['admin', 'talent-manager'],
      templateId: 'admin-performer-create',
      components: [
        'performer-form',
        'account-setup',
        'profile-setup',
        'media-upload',
        'verification-process',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-performer-detail',
      route: '/admin/performers/:id',
      section: 'admin',
      title: 'Performer Details',
      authRequired: true,
      roles: ['admin', 'talent-manager'],
      templateId: 'admin-performer-detail',
      components: [
        'performer-overview',
        'booking-history',
        'earnings-report',
        'performance-metrics',
        'reviews-moderation',
        'account-actions',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Browse components
    'performer-grid',
    'performer-card',
    'genre-filter',
    'performance-type-filter',
    'location-filter',
    'availability-filter',
    'search-bar',
    'sort-dropdown',
    'pagination',

    // Profile detail components
    'performer-header',
    'performer-bio',
    'performer-gallery',
    'performer-videos',
    'performer-music-player',
    'upcoming-shows',
    'past-performances',
    'reviews-section',
    'booking-inquiry-form',
    'social-links',
    'share-profile',

    // Dashboard components
    'upcoming-shows-widget',
    'booking-requests-widget',
    'profile-views-stats',
    'earnings-summary',
    'quick-actions',
    'recent-reviews',

    // Profile edit components
    'basic-info-form',
    'bio-editor',
    'genre-tags-selector',
    'photo-gallery-manager',
    'video-links-manager',
    'music-links-manager',
    'social-links-manager',
    'booking-info-form',
    'availability-calendar',
    'rider-requirements',

    // Admin components
    'performers-table',
    'performer-status-filter',
    'verification-status',
    'bulk-actions',
    'performer-stats',
    'featured-toggle',
    'performer-form',
    'account-setup',
    'profile-setup',
    'media-upload',
    'verification-process',
    'performer-overview',
    'booking-history',
    'earnings-report',
    'performance-metrics',
    'reviews-moderation',
    'account-actions',
  ],

  entities: [
    {
      name: 'performers',
      displayName: 'Performers',
      description: 'Artist and performer profile records',
      isCore: true,
    },
    {
      name: 'performer_media',
      displayName: 'Performer Media',
      description: 'Photos, videos, and audio for performers',
      isCore: true,
    },
    {
      name: 'performer_genres',
      displayName: 'Performer Genres',
      description: 'Genre tags associated with performers',
      isCore: true,
    },
    {
      name: 'performer_availability',
      displayName: 'Performer Availability',
      description: 'Availability schedules for performers',
      isCore: false,
    },
    {
      name: 'performer_reviews',
      displayName: 'Performer Reviews',
      description: 'Reviews and ratings for performers',
      isCore: false,
    },
    {
      name: 'booking_inquiries',
      displayName: 'Booking Inquiries',
      description: 'Booking inquiry requests for performers',
      isCore: false,
    },
    {
      name: 'performer_riders',
      displayName: 'Performer Riders',
      description: 'Technical and hospitality rider requirements',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Performers CRUD
    {
      method: 'GET',
      path: '/performers',
      auth: false,
      handler: 'crud',
      entity: 'performers',
      operation: 'list',
      description: 'List all performers',
    },
    {
      method: 'GET',
      path: '/performers/:id',
      auth: false,
      handler: 'crud',
      entity: 'performers',
      operation: 'get',
      description: 'Get performer profile',
    },
    {
      method: 'POST',
      path: '/performers',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'performers',
      operation: 'create',
      description: 'Create performer profile',
    },
    {
      method: 'PUT',
      path: '/performers/:id',
      auth: true,
      handler: 'crud',
      entity: 'performers',
      operation: 'update',
      description: 'Update performer profile',
    },
    {
      method: 'DELETE',
      path: '/performers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'performers',
      operation: 'delete',
      description: 'Delete performer profile',
    },

    // Performer Media
    {
      method: 'GET',
      path: '/performers/:id/media',
      auth: false,
      handler: 'crud',
      entity: 'performer_media',
      operation: 'list',
      description: 'Get performer media',
    },
    {
      method: 'POST',
      path: '/performers/:id/media',
      auth: true,
      handler: 'crud',
      entity: 'performer_media',
      operation: 'create',
      description: 'Add performer media',
    },
    {
      method: 'DELETE',
      path: '/performers/:performerId/media/:id',
      auth: true,
      handler: 'crud',
      entity: 'performer_media',
      operation: 'delete',
      description: 'Delete performer media',
    },

    // Availability
    {
      method: 'GET',
      path: '/performers/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'performer_availability',
      description: 'Get performer availability',
    },
    {
      method: 'PUT',
      path: '/performers/:id/availability',
      auth: true,
      handler: 'custom',
      entity: 'performer_availability',
      description: 'Update performer availability',
    },

    // Reviews
    {
      method: 'GET',
      path: '/performers/:id/reviews',
      auth: false,
      handler: 'crud',
      entity: 'performer_reviews',
      operation: 'list',
      description: 'Get performer reviews',
    },
    {
      method: 'POST',
      path: '/performers/:id/reviews',
      auth: true,
      handler: 'crud',
      entity: 'performer_reviews',
      operation: 'create',
      description: 'Add performer review',
    },

    // Booking Inquiries
    {
      method: 'GET',
      path: '/performers/:id/inquiries',
      auth: true,
      handler: 'crud',
      entity: 'booking_inquiries',
      operation: 'list',
      description: 'Get booking inquiries',
    },
    {
      method: 'POST',
      path: '/performers/:id/inquiries',
      auth: true,
      handler: 'crud',
      entity: 'booking_inquiries',
      operation: 'create',
      description: 'Submit booking inquiry',
    },
    {
      method: 'PUT',
      path: '/performers/:performerId/inquiries/:id/respond',
      auth: true,
      handler: 'custom',
      entity: 'booking_inquiries',
      description: 'Respond to booking inquiry',
    },

    // Riders
    {
      method: 'GET',
      path: '/performers/:id/rider',
      auth: true,
      handler: 'crud',
      entity: 'performer_riders',
      operation: 'get',
      description: 'Get performer rider',
    },
    {
      method: 'PUT',
      path: '/performers/:id/rider',
      auth: true,
      handler: 'crud',
      entity: 'performer_riders',
      operation: 'update',
      description: 'Update performer rider',
    },

    // Profile Actions
    {
      method: 'PUT',
      path: '/performers/:id/verify',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'performers',
      description: 'Verify performer profile',
    },
    {
      method: 'PUT',
      path: '/performers/:id/featured',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'performers',
      description: 'Toggle featured status',
    },

    // Search
    {
      method: 'GET',
      path: '/performers/search',
      auth: false,
      handler: 'custom',
      entity: 'performers',
      description: 'Search performers',
    },
  ],

  config: [
    {
      key: 'requireVerification',
      label: 'Require Profile Verification',
      type: 'boolean',
      default: true,
      description: 'Require admin verification for new profiles',
    },
    {
      key: 'allowSelfRegistration',
      label: 'Allow Self Registration',
      type: 'boolean',
      default: true,
      description: 'Allow performers to create their own profiles',
    },
    {
      key: 'maxPhotos',
      label: 'Maximum Photos',
      type: 'number',
      default: 20,
      description: 'Maximum photos per performer profile',
    },
    {
      key: 'maxVideos',
      label: 'Maximum Videos',
      type: 'number',
      default: 10,
      description: 'Maximum video links per profile',
    },
    {
      key: 'enableReviews',
      label: 'Enable Reviews',
      type: 'boolean',
      default: true,
      description: 'Allow reviews on performer profiles',
    },
    {
      key: 'reviewModeration',
      label: 'Review Moderation',
      type: 'select',
      default: 'post',
      options: [
        { value: 'none', label: 'No moderation' },
        { value: 'pre', label: 'Pre-moderation (approve before publishing)' },
        { value: 'post', label: 'Post-moderation (publish then review)' },
      ],
      description: 'How reviews are moderated',
    },
    {
      key: 'showBookingRates',
      label: 'Show Booking Rates',
      type: 'boolean',
      default: false,
      description: 'Display performer booking rates publicly',
    },
    {
      key: 'enableRider',
      label: 'Enable Rider Requirements',
      type: 'boolean',
      default: true,
      description: 'Allow performers to specify rider requirements',
    },
  ],
};
