/**
 * Season Passes Feature Definition
 *
 * Season pass and membership sales for entertainment venues.
 * Supports annual passes, memberships, subscription packages, and multi-show bundles.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const SEASON_PASSES_FEATURE: FeatureDefinition = {
  id: 'season-passes',
  name: 'Season Passes',
  category: 'business',
  description: 'Manage season passes and memberships with benefits, renewals, and member perks',
  icon: 'badge',

  includedInAppTypes: [
    'entertainment',
    'theater',
    'concert-venue',
    'sports-venue',
    'theme-park',
    'museum',
    'performing-arts',
    'zoo',
    'aquarium',
    'membership-organization',
  ],

  activationKeywords: [
    'season pass',
    'season ticket',
    'annual pass',
    'membership',
    'member pass',
    'subscriber',
    'subscription package',
    'season subscription',
    'multi-show pass',
    'flex pass',
    'member benefits',
    'loyalty program',
    'pass holder',
    'season ticket holder',
    'annual membership',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'payments', 'notifications'],
  conflicts: [],

  pages: [
    {
      id: 'memberships-browse',
      route: '/memberships',
      section: 'frontend',
      title: 'Memberships & Passes',
      authRequired: false,
      templateId: 'memberships-browse',
      components: [
        'membership-tiers-grid',
        'tier-card',
        'benefits-comparison',
        'pricing-table',
        'testimonials',
        'faq-section',
        'join-cta',
      ],
      layout: 'default',
    },
    {
      id: 'membership-purchase',
      route: '/memberships/:tierId/purchase',
      section: 'frontend',
      title: 'Purchase Membership',
      authRequired: true,
      templateId: 'membership-purchase',
      components: [
        'tier-summary',
        'member-info-form',
        'add-on-members',
        'payment-options',
        'gift-membership-toggle',
        'promo-code-input',
        'terms-acceptance',
        'purchase-button',
      ],
      layout: 'default',
    },
    {
      id: 'member-portal',
      route: '/member',
      section: 'frontend',
      title: 'Member Portal',
      authRequired: true,
      roles: ['member'],
      templateId: 'member-portal',
      components: [
        'membership-card',
        'member-benefits',
        'upcoming-events-member',
        'member-discounts',
        'ticket-reservations',
        'guest-passes',
        'renewal-reminder',
        'member-newsletter',
      ],
      layout: 'dashboard',
    },
    {
      id: 'member-account',
      route: '/member/account',
      section: 'frontend',
      title: 'My Membership',
      authRequired: true,
      roles: ['member'],
      templateId: 'member-account',
      components: [
        'membership-status',
        'member-info-edit',
        'additional-members',
        'payment-history',
        'auto-renewal-settings',
        'cancel-membership',
        'upgrade-membership',
      ],
      layout: 'dashboard',
    },
    {
      id: 'member-benefits',
      route: '/member/benefits',
      section: 'frontend',
      title: 'Member Benefits',
      authRequired: true,
      roles: ['member'],
      templateId: 'member-benefits',
      components: [
        'benefits-list',
        'exclusive-offers',
        'partner-discounts',
        'early-access-events',
        'member-events',
        'redeemable-perks',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-memberships',
      route: '/admin/memberships',
      section: 'admin',
      title: 'Manage Memberships',
      authRequired: true,
      roles: ['admin', 'membership-manager'],
      templateId: 'admin-memberships',
      components: [
        'members-table',
        'membership-stats',
        'renewal-rate-chart',
        'revenue-chart',
        'status-filter',
        'tier-filter',
        'bulk-actions',
        'export-members',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-membership-tiers',
      route: '/admin/memberships/tiers',
      section: 'admin',
      title: 'Membership Tiers',
      authRequired: true,
      roles: ['admin'],
      templateId: 'admin-membership-tiers',
      components: [
        'tiers-list',
        'tier-form',
        'benefits-builder',
        'pricing-config',
        'tier-comparison-editor',
        'tier-availability',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-member-detail',
      route: '/admin/memberships/members/:id',
      section: 'admin',
      title: 'Member Details',
      authRequired: true,
      roles: ['admin', 'membership-manager'],
      templateId: 'admin-member-detail',
      components: [
        'member-overview',
        'membership-history',
        'visit-history',
        'ticket-usage',
        'communication-log',
        'member-actions',
        'notes-section',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-renewals',
      route: '/admin/memberships/renewals',
      section: 'admin',
      title: 'Renewals',
      authRequired: true,
      roles: ['admin', 'membership-manager'],
      templateId: 'admin-renewals',
      components: [
        'upcoming-renewals',
        'lapsed-members',
        'renewal-campaigns',
        'auto-renewal-failures',
        'renewal-reports',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Browse components
    'membership-tiers-grid',
    'tier-card',
    'benefits-comparison',
    'pricing-table',
    'testimonials',
    'faq-section',
    'join-cta',

    // Purchase components
    'tier-summary',
    'member-info-form',
    'add-on-members',
    'payment-options',
    'gift-membership-toggle',
    'promo-code-input',
    'terms-acceptance',
    'purchase-button',

    // Member portal components
    'membership-card',
    'member-benefits',
    'upcoming-events-member',
    'member-discounts',
    'ticket-reservations',
    'guest-passes',
    'renewal-reminder',
    'member-newsletter',

    // Member account components
    'membership-status',
    'member-info-edit',
    'additional-members',
    'payment-history',
    'auto-renewal-settings',
    'cancel-membership',
    'upgrade-membership',

    // Benefits components
    'benefits-list',
    'exclusive-offers',
    'partner-discounts',
    'early-access-events',
    'member-events',
    'redeemable-perks',

    // Admin components
    'members-table',
    'membership-stats',
    'renewal-rate-chart',
    'revenue-chart',
    'status-filter',
    'tier-filter',
    'bulk-actions',
    'export-members',
    'tiers-list',
    'tier-form',
    'benefits-builder',
    'pricing-config',
    'tier-comparison-editor',
    'tier-availability',
    'member-overview',
    'membership-history',
    'visit-history',
    'ticket-usage',
    'communication-log',
    'member-actions',
    'notes-section',
    'upcoming-renewals',
    'lapsed-members',
    'renewal-campaigns',
    'auto-renewal-failures',
    'renewal-reports',
  ],

  entities: [
    {
      name: 'membership_tiers',
      displayName: 'Membership Tiers',
      description: 'Different levels of membership/season passes',
      isCore: true,
    },
    {
      name: 'memberships',
      displayName: 'Memberships',
      description: 'Active member/pass holder records',
      isCore: true,
    },
    {
      name: 'membership_benefits',
      displayName: 'Membership Benefits',
      description: 'Benefits included with each tier',
      isCore: true,
    },
    {
      name: 'member_cards',
      displayName: 'Member Cards',
      description: 'Physical or digital membership cards',
      isCore: true,
    },
    {
      name: 'membership_transactions',
      displayName: 'Membership Transactions',
      description: 'Purchase and renewal transactions',
      isCore: true,
    },
    {
      name: 'guest_passes',
      displayName: 'Guest Passes',
      description: 'Guest passes included with memberships',
      isCore: false,
    },
    {
      name: 'member_visits',
      displayName: 'Member Visits',
      description: 'Visit/check-in records for members',
      isCore: false,
    },
    {
      name: 'gift_memberships',
      displayName: 'Gift Memberships',
      description: 'Gift membership purchases',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Membership Tiers
    {
      method: 'GET',
      path: '/membership-tiers',
      auth: false,
      handler: 'crud',
      entity: 'membership_tiers',
      operation: 'list',
      description: 'List membership tiers',
    },
    {
      method: 'GET',
      path: '/membership-tiers/:id',
      auth: false,
      handler: 'crud',
      entity: 'membership_tiers',
      operation: 'get',
      description: 'Get tier details',
    },
    {
      method: 'POST',
      path: '/membership-tiers',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'membership_tiers',
      operation: 'create',
      description: 'Create membership tier',
    },
    {
      method: 'PUT',
      path: '/membership-tiers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'membership_tiers',
      operation: 'update',
      description: 'Update membership tier',
    },
    {
      method: 'DELETE',
      path: '/membership-tiers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'membership_tiers',
      operation: 'delete',
      description: 'Delete membership tier',
    },

    // Memberships
    {
      method: 'GET',
      path: '/memberships',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'memberships',
      operation: 'list',
      description: 'List all memberships',
    },
    {
      method: 'GET',
      path: '/memberships/my',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Get current user membership',
    },
    {
      method: 'GET',
      path: '/memberships/:id',
      auth: true,
      handler: 'crud',
      entity: 'memberships',
      operation: 'get',
      description: 'Get membership details',
    },
    {
      method: 'POST',
      path: '/memberships',
      auth: true,
      handler: 'crud',
      entity: 'memberships',
      operation: 'create',
      description: 'Create/purchase membership',
    },
    {
      method: 'PUT',
      path: '/memberships/:id',
      auth: true,
      handler: 'crud',
      entity: 'memberships',
      operation: 'update',
      description: 'Update membership',
    },

    // Membership Actions
    {
      method: 'POST',
      path: '/memberships/:id/renew',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Renew membership',
    },
    {
      method: 'POST',
      path: '/memberships/:id/upgrade',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Upgrade membership tier',
    },
    {
      method: 'PUT',
      path: '/memberships/:id/cancel',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Cancel membership',
    },
    {
      method: 'PUT',
      path: '/memberships/:id/auto-renew',
      auth: true,
      handler: 'custom',
      entity: 'memberships',
      description: 'Toggle auto-renewal',
    },

    // Member Cards
    {
      method: 'GET',
      path: '/memberships/:id/card',
      auth: true,
      handler: 'custom',
      entity: 'member_cards',
      description: 'Get digital member card',
    },
    {
      method: 'POST',
      path: '/memberships/:id/card/replace',
      auth: true,
      handler: 'custom',
      entity: 'member_cards',
      description: 'Request replacement card',
    },

    // Guest Passes
    {
      method: 'GET',
      path: '/memberships/:id/guest-passes',
      auth: true,
      handler: 'crud',
      entity: 'guest_passes',
      operation: 'list',
      description: 'List available guest passes',
    },
    {
      method: 'POST',
      path: '/memberships/:id/guest-passes/redeem',
      auth: true,
      handler: 'custom',
      entity: 'guest_passes',
      description: 'Redeem guest pass',
    },

    // Benefits
    {
      method: 'GET',
      path: '/membership-tiers/:tierId/benefits',
      auth: false,
      handler: 'crud',
      entity: 'membership_benefits',
      operation: 'list',
      description: 'List tier benefits',
    },
    {
      method: 'GET',
      path: '/memberships/:id/benefits',
      auth: true,
      handler: 'custom',
      entity: 'membership_benefits',
      description: 'Get member benefits',
    },

    // Gift Memberships
    {
      method: 'POST',
      path: '/memberships/gift',
      auth: true,
      handler: 'crud',
      entity: 'gift_memberships',
      operation: 'create',
      description: 'Purchase gift membership',
    },
    {
      method: 'POST',
      path: '/memberships/gift/:code/redeem',
      auth: true,
      handler: 'custom',
      entity: 'gift_memberships',
      description: 'Redeem gift membership',
    },

    // Visits
    {
      method: 'POST',
      path: '/memberships/:id/check-in',
      auth: true,
      handler: 'custom',
      entity: 'member_visits',
      description: 'Record member visit',
    },
    {
      method: 'GET',
      path: '/memberships/:id/visits',
      auth: true,
      handler: 'crud',
      entity: 'member_visits',
      operation: 'list',
      description: 'Get visit history',
    },

    // Admin Reports
    {
      method: 'GET',
      path: '/memberships/reports/renewals',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'memberships',
      description: 'Get renewal report',
    },
    {
      method: 'GET',
      path: '/memberships/reports/revenue',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'membership_transactions',
      description: 'Get revenue report',
    },
  ],

  config: [
    {
      key: 'enableAutoRenewal',
      label: 'Enable Auto-Renewal',
      type: 'boolean',
      default: true,
      description: 'Allow members to enable automatic renewal',
    },
    {
      key: 'renewalReminderDays',
      label: 'Renewal Reminder Days',
      type: 'number',
      default: 30,
      description: 'Days before expiration to send renewal reminders',
    },
    {
      key: 'gracePeriodDays',
      label: 'Grace Period Days',
      type: 'number',
      default: 14,
      description: 'Days after expiration to allow renewal at same rate',
    },
    {
      key: 'enableGiftMemberships',
      label: 'Enable Gift Memberships',
      type: 'boolean',
      default: true,
      description: 'Allow purchasing memberships as gifts',
    },
    {
      key: 'enableGuestPasses',
      label: 'Enable Guest Passes',
      type: 'boolean',
      default: true,
      description: 'Include guest passes with memberships',
    },
    {
      key: 'defaultGuestPasses',
      label: 'Default Guest Passes Per Year',
      type: 'number',
      default: 4,
      description: 'Number of guest passes included annually',
    },
    {
      key: 'enableDigitalCard',
      label: 'Enable Digital Member Card',
      type: 'boolean',
      default: true,
      description: 'Provide digital membership cards',
    },
    {
      key: 'memberDiscountPercentage',
      label: 'Member Discount Percentage',
      type: 'number',
      default: 10,
      description: 'Default discount percentage for members',
    },
  ],
};
