/**
 * Seating Charts Feature Definition
 *
 * Interactive seat selection and seating chart management for entertainment venues.
 * Supports theaters, stadiums, concert halls, and reserved seating events.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const SEATING_CHARTS_FEATURE: FeatureDefinition = {
  id: 'seating-charts',
  name: 'Seating Charts',
  category: 'business',
  description: 'Interactive seat selection with visual seating charts and real-time availability',
  icon: 'layout-grid',

  includedInAppTypes: [
    'entertainment',
    'theater',
    'concert-venue',
    'sports-venue',
    'cinema',
    'arena',
    'stadium',
    'auditorium',
    'ticketing-platform',
  ],

  activationKeywords: [
    'seating chart',
    'seat selection',
    'choose seat',
    'select seat',
    'seat map',
    'seat layout',
    'reserved seating',
    'seat picker',
    'interactive seating',
    'seat availability',
    'venue seating',
    'theater seats',
    'stadium seats',
    'arena seating',
    'assigned seating',
  ],

  enabledByDefault: true,
  optional: true,

  dependencies: ['user-auth', 'venue-booking'],
  conflicts: [],

  pages: [
    {
      id: 'seat-selection',
      route: '/events/:eventId/seats',
      section: 'frontend',
      title: 'Select Seats',
      authRequired: false,
      templateId: 'seat-selection',
      components: [
        'seating-chart-viewer',
        'section-selector',
        'seat-legend',
        'zoom-controls',
        'selected-seats-panel',
        'price-tier-indicator',
        'accessibility-filter',
        'best-available-button',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'seat-confirmation',
      route: '/events/:eventId/seats/confirm',
      section: 'frontend',
      title: 'Confirm Seats',
      authRequired: true,
      templateId: 'seat-confirmation',
      components: [
        'selected-seats-summary',
        'seat-details-list',
        'price-breakdown',
        'seat-upgrade-options',
        'proceed-to-checkout',
      ],
      layout: 'default',
    },
    {
      id: 'admin-seating-charts',
      route: '/admin/seating-charts',
      section: 'admin',
      title: 'Manage Seating Charts',
      authRequired: true,
      roles: ['admin', 'venue-manager'],
      templateId: 'admin-seating-charts',
      components: [
        'charts-list',
        'chart-preview',
        'chart-actions',
        'venue-selector',
        'chart-stats',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-chart-editor',
      route: '/admin/seating-charts/:id/edit',
      section: 'admin',
      title: 'Edit Seating Chart',
      authRequired: true,
      roles: ['admin', 'venue-manager'],
      templateId: 'admin-chart-editor',
      components: [
        'chart-canvas',
        'section-builder',
        'row-builder',
        'seat-builder',
        'seat-properties-panel',
        'pricing-tier-manager',
        'accessibility-markers',
        'stage-position',
        'chart-preview-mode',
        'import-export-tools',
      ],
      layout: 'fullscreen',
    },
    {
      id: 'admin-chart-create',
      route: '/admin/seating-charts/create',
      section: 'admin',
      title: 'Create Seating Chart',
      authRequired: true,
      roles: ['admin', 'venue-manager'],
      templateId: 'admin-chart-create',
      components: [
        'venue-selector',
        'template-gallery',
        'chart-wizard',
        'basic-info-form',
        'section-setup',
        'row-configuration',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-seat-inventory',
      route: '/admin/events/:eventId/seats',
      section: 'admin',
      title: 'Seat Inventory',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-seat-inventory',
      components: [
        'inventory-overview',
        'seat-status-chart',
        'held-seats-manager',
        'blocked-seats-manager',
        'bulk-seat-actions',
        'seat-search',
        'inventory-reports',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Seat selection components
    'seating-chart-viewer',
    'section-selector',
    'seat-legend',
    'zoom-controls',
    'selected-seats-panel',
    'price-tier-indicator',
    'accessibility-filter',
    'best-available-button',

    // Confirmation components
    'selected-seats-summary',
    'seat-details-list',
    'price-breakdown',
    'seat-upgrade-options',
    'proceed-to-checkout',

    // Admin list components
    'charts-list',
    'chart-preview',
    'chart-actions',
    'venue-selector',
    'chart-stats',

    // Chart editor components
    'chart-canvas',
    'section-builder',
    'row-builder',
    'seat-builder',
    'seat-properties-panel',
    'pricing-tier-manager',
    'accessibility-markers',
    'stage-position',
    'chart-preview-mode',
    'import-export-tools',

    // Chart creation components
    'template-gallery',
    'chart-wizard',
    'basic-info-form',
    'section-setup',
    'row-configuration',

    // Inventory components
    'inventory-overview',
    'seat-status-chart',
    'held-seats-manager',
    'blocked-seats-manager',
    'bulk-seat-actions',
    'seat-search',
    'inventory-reports',
  ],

  entities: [
    {
      name: 'seating_charts',
      displayName: 'Seating Charts',
      description: 'Venue seating chart configurations',
      isCore: true,
    },
    {
      name: 'seating_sections',
      displayName: 'Seating Sections',
      description: 'Sections within a seating chart (Orchestra, Balcony, etc.)',
      isCore: true,
    },
    {
      name: 'seating_rows',
      displayName: 'Seating Rows',
      description: 'Rows within seating sections',
      isCore: true,
    },
    {
      name: 'seats',
      displayName: 'Seats',
      description: 'Individual seat records with positions and attributes',
      isCore: true,
    },
    {
      name: 'seat_pricing_tiers',
      displayName: 'Pricing Tiers',
      description: 'Price tiers for different seat categories',
      isCore: true,
    },
    {
      name: 'seat_holds',
      displayName: 'Seat Holds',
      description: 'Temporarily held seats during selection',
      isCore: false,
    },
    {
      name: 'seat_blocks',
      displayName: 'Seat Blocks',
      description: 'Blocked or unavailable seats',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Seating Charts
    {
      method: 'GET',
      path: '/seating-charts',
      auth: false,
      handler: 'crud',
      entity: 'seating_charts',
      operation: 'list',
      description: 'List seating charts',
    },
    {
      method: 'GET',
      path: '/seating-charts/:id',
      auth: false,
      handler: 'crud',
      entity: 'seating_charts',
      operation: 'get',
      description: 'Get seating chart details',
    },
    {
      method: 'POST',
      path: '/seating-charts',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'seating_charts',
      operation: 'create',
      description: 'Create seating chart',
    },
    {
      method: 'PUT',
      path: '/seating-charts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'seating_charts',
      operation: 'update',
      description: 'Update seating chart',
    },
    {
      method: 'DELETE',
      path: '/seating-charts/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'seating_charts',
      operation: 'delete',
      description: 'Delete seating chart',
    },

    // Sections
    {
      method: 'GET',
      path: '/seating-charts/:chartId/sections',
      auth: false,
      handler: 'crud',
      entity: 'seating_sections',
      operation: 'list',
      description: 'Get chart sections',
    },
    {
      method: 'POST',
      path: '/seating-charts/:chartId/sections',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'seating_sections',
      operation: 'create',
      description: 'Add section to chart',
    },
    {
      method: 'PUT',
      path: '/seating-charts/:chartId/sections/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'seating_sections',
      operation: 'update',
      description: 'Update section',
    },

    // Seats
    {
      method: 'GET',
      path: '/events/:eventId/seats',
      auth: false,
      handler: 'custom',
      entity: 'seats',
      description: 'Get seats with availability for event',
    },
    {
      method: 'GET',
      path: '/events/:eventId/seats/best-available',
      auth: false,
      handler: 'custom',
      entity: 'seats',
      description: 'Get best available seats',
    },

    // Seat Holds
    {
      method: 'POST',
      path: '/events/:eventId/seats/hold',
      auth: false,
      handler: 'custom',
      entity: 'seat_holds',
      description: 'Hold seats temporarily',
    },
    {
      method: 'DELETE',
      path: '/events/:eventId/seats/hold',
      auth: false,
      handler: 'custom',
      entity: 'seat_holds',
      description: 'Release held seats',
    },
    {
      method: 'PUT',
      path: '/events/:eventId/seats/hold/extend',
      auth: false,
      handler: 'custom',
      entity: 'seat_holds',
      description: 'Extend seat hold timer',
    },

    // Seat Blocks
    {
      method: 'POST',
      path: '/events/:eventId/seats/block',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'seat_blocks',
      description: 'Block seats from sale',
    },
    {
      method: 'DELETE',
      path: '/events/:eventId/seats/block',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'seat_blocks',
      description: 'Unblock seats',
    },

    // Pricing Tiers
    {
      method: 'GET',
      path: '/seating-charts/:chartId/pricing-tiers',
      auth: false,
      handler: 'crud',
      entity: 'seat_pricing_tiers',
      operation: 'list',
      description: 'Get pricing tiers',
    },
    {
      method: 'POST',
      path: '/seating-charts/:chartId/pricing-tiers',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'seat_pricing_tiers',
      operation: 'create',
      description: 'Create pricing tier',
    },
    {
      method: 'PUT',
      path: '/seating-charts/:chartId/pricing-tiers/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'seat_pricing_tiers',
      operation: 'update',
      description: 'Update pricing tier',
    },

    // Inventory
    {
      method: 'GET',
      path: '/events/:eventId/seats/inventory',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'seats',
      description: 'Get seat inventory status',
    },
  ],

  config: [
    {
      key: 'holdDurationMinutes',
      label: 'Seat Hold Duration (minutes)',
      type: 'number',
      default: 10,
      description: 'How long seats are held during selection',
    },
    {
      key: 'maxSeatsPerTransaction',
      label: 'Maximum Seats Per Transaction',
      type: 'number',
      default: 8,
      description: 'Maximum seats that can be selected at once',
    },
    {
      key: 'enableBestAvailable',
      label: 'Enable Best Available',
      type: 'boolean',
      default: true,
      description: 'Allow automatic best seat selection',
    },
    {
      key: 'showPricesOnChart',
      label: 'Show Prices on Chart',
      type: 'boolean',
      default: true,
      description: 'Display prices on the seating chart',
    },
    {
      key: 'enableAccessibilityFilter',
      label: 'Enable Accessibility Filter',
      type: 'boolean',
      default: true,
      description: 'Allow filtering for accessible seats',
    },
    {
      key: 'seatLabelFormat',
      label: 'Seat Label Format',
      type: 'select',
      default: 'section-row-seat',
      options: [
        { value: 'section-row-seat', label: 'Section, Row, Seat (A-1-12)' },
        { value: 'row-seat', label: 'Row, Seat (A-12)' },
        { value: 'sequential', label: 'Sequential Number (123)' },
      ],
      description: 'How seats are labeled and displayed',
    },
    {
      key: 'enableSocialDistancing',
      label: 'Enable Social Distancing Mode',
      type: 'boolean',
      default: false,
      description: 'Automatically space out seat selections',
    },
    {
      key: 'orphanSeatPrevention',
      label: 'Prevent Orphan Seats',
      type: 'boolean',
      default: true,
      description: 'Prevent leaving single seats between selections',
    },
  ],
};
