/**
 * Show Scheduling Feature Definition
 *
 * Show and event scheduling management for entertainment applications.
 * Supports concerts, theater productions, recurring shows, and special events.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const SHOW_SCHEDULING_FEATURE: FeatureDefinition = {
  id: 'show-scheduling',
  name: 'Show Scheduling',
  category: 'business',
  description: 'Manage show and event schedules with recurring events, calendar views, and conflict detection',
  icon: 'calendar-clock',

  includedInAppTypes: [
    'entertainment',
    'theater',
    'concert-venue',
    'music-venue',
    'comedy-club',
    'event-management',
    'festival',
    'performing-arts',
    'nightclub',
  ],

  activationKeywords: [
    'show scheduling',
    'event scheduling',
    'show calendar',
    'event calendar',
    'performance schedule',
    'show times',
    'event times',
    'schedule shows',
    'schedule events',
    'show management',
    'event management',
    'recurring shows',
    'show planner',
    'event planner',
    'performance calendar',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'calendar', 'notifications'],
  conflicts: [],

  pages: [
    {
      id: 'shows-calendar',
      route: '/shows',
      section: 'frontend',
      title: 'Show Calendar',
      authRequired: false,
      templateId: 'shows-calendar',
      components: [
        'shows-calendar-view',
        'shows-list-view',
        'view-toggle',
        'date-navigator',
        'category-filter',
        'venue-filter',
        'price-filter',
        'show-card',
        'upcoming-shows-sidebar',
      ],
      layout: 'default',
    },
    {
      id: 'show-detail',
      route: '/shows/:id',
      section: 'frontend',
      title: 'Show Details',
      authRequired: false,
      templateId: 'show-detail',
      components: [
        'show-header',
        'show-description',
        'show-dates-times',
        'performer-lineup',
        'venue-info',
        'ticket-options',
        'buy-tickets-button',
        'add-to-calendar',
        'share-show',
        'related-shows',
      ],
      layout: 'default',
    },
    {
      id: 'admin-shows',
      route: '/admin/shows',
      section: 'admin',
      title: 'Manage Shows',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-shows',
      components: [
        'shows-table',
        'shows-calendar-admin',
        'status-filter',
        'venue-filter',
        'date-range-filter',
        'bulk-actions',
        'show-stats',
        'conflict-alerts',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-show-create',
      route: '/admin/shows/create',
      section: 'admin',
      title: 'Create Show',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-show-create',
      components: [
        'show-basic-info-form',
        'show-description-editor',
        'venue-selector',
        'date-time-picker',
        'recurring-schedule-builder',
        'performer-selector',
        'ticket-type-config',
        'pricing-setup',
        'media-uploader',
        'publish-settings',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-show-edit',
      route: '/admin/shows/:id/edit',
      section: 'admin',
      title: 'Edit Show',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-show-edit',
      components: [
        'show-basic-info-form',
        'show-description-editor',
        'venue-selector',
        'date-time-picker',
        'recurring-schedule-builder',
        'performer-selector',
        'ticket-type-config',
        'pricing-setup',
        'media-uploader',
        'publish-settings',
        'cancel-show-modal',
        'reschedule-modal',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-show-instances',
      route: '/admin/shows/:id/instances',
      section: 'admin',
      title: 'Show Instances',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-show-instances',
      components: [
        'instances-calendar',
        'instances-list',
        'instance-status-manager',
        'instance-ticket-sales',
        'instance-actions',
        'add-instance-modal',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-schedule-conflicts',
      route: '/admin/shows/conflicts',
      section: 'admin',
      title: 'Schedule Conflicts',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-schedule-conflicts',
      components: [
        'conflicts-list',
        'conflict-detail',
        'resolution-options',
        'venue-timeline',
        'performer-timeline',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Public calendar components
    'shows-calendar-view',
    'shows-list-view',
    'view-toggle',
    'date-navigator',
    'category-filter',
    'venue-filter',
    'price-filter',
    'show-card',
    'upcoming-shows-sidebar',

    // Show detail components
    'show-header',
    'show-description',
    'show-dates-times',
    'performer-lineup',
    'venue-info',
    'ticket-options',
    'buy-tickets-button',
    'add-to-calendar',
    'share-show',
    'related-shows',

    // Admin list components
    'shows-table',
    'shows-calendar-admin',
    'status-filter',
    'date-range-filter',
    'bulk-actions',
    'show-stats',
    'conflict-alerts',

    // Show form components
    'show-basic-info-form',
    'show-description-editor',
    'venue-selector',
    'date-time-picker',
    'recurring-schedule-builder',
    'performer-selector',
    'ticket-type-config',
    'pricing-setup',
    'media-uploader',
    'publish-settings',
    'cancel-show-modal',
    'reschedule-modal',

    // Instance management components
    'instances-calendar',
    'instances-list',
    'instance-status-manager',
    'instance-ticket-sales',
    'instance-actions',
    'add-instance-modal',

    // Conflict resolution components
    'conflicts-list',
    'conflict-detail',
    'resolution-options',
    'venue-timeline',
    'performer-timeline',
  ],

  entities: [
    {
      name: 'shows',
      displayName: 'Shows',
      description: 'Show/event master records',
      isCore: true,
    },
    {
      name: 'show_instances',
      displayName: 'Show Instances',
      description: 'Individual occurrences of shows (specific dates/times)',
      isCore: true,
    },
    {
      name: 'show_performers',
      displayName: 'Show Performers',
      description: 'Performers associated with shows',
      isCore: true,
    },
    {
      name: 'show_categories',
      displayName: 'Show Categories',
      description: 'Categories/genres for shows',
      isCore: true,
    },
    {
      name: 'recurring_schedules',
      displayName: 'Recurring Schedules',
      description: 'Recurring schedule patterns for shows',
      isCore: false,
    },
    {
      name: 'schedule_conflicts',
      displayName: 'Schedule Conflicts',
      description: 'Detected scheduling conflicts',
      isCore: false,
    },
    {
      name: 'show_media',
      displayName: 'Show Media',
      description: 'Images and promotional media for shows',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Shows CRUD
    {
      method: 'GET',
      path: '/shows',
      auth: false,
      handler: 'crud',
      entity: 'shows',
      operation: 'list',
      description: 'List all shows',
    },
    {
      method: 'GET',
      path: '/shows/:id',
      auth: false,
      handler: 'crud',
      entity: 'shows',
      operation: 'get',
      description: 'Get show details',
    },
    {
      method: 'POST',
      path: '/shows',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'shows',
      operation: 'create',
      description: 'Create new show',
    },
    {
      method: 'PUT',
      path: '/shows/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'shows',
      operation: 'update',
      description: 'Update show',
    },
    {
      method: 'DELETE',
      path: '/shows/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'shows',
      operation: 'delete',
      description: 'Delete show',
    },

    // Show Instances
    {
      method: 'GET',
      path: '/shows/:showId/instances',
      auth: false,
      handler: 'crud',
      entity: 'show_instances',
      operation: 'list',
      description: 'Get show instances',
    },
    {
      method: 'GET',
      path: '/show-instances/:id',
      auth: false,
      handler: 'crud',
      entity: 'show_instances',
      operation: 'get',
      description: 'Get instance details',
    },
    {
      method: 'POST',
      path: '/shows/:showId/instances',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'show_instances',
      operation: 'create',
      description: 'Add show instance',
    },
    {
      method: 'PUT',
      path: '/show-instances/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'show_instances',
      operation: 'update',
      description: 'Update show instance',
    },
    {
      method: 'DELETE',
      path: '/show-instances/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'show_instances',
      operation: 'delete',
      description: 'Cancel show instance',
    },

    // Recurring Schedules
    {
      method: 'GET',
      path: '/shows/:showId/schedule',
      auth: false,
      handler: 'crud',
      entity: 'recurring_schedules',
      operation: 'get',
      description: 'Get recurring schedule',
    },
    {
      method: 'PUT',
      path: '/shows/:showId/schedule',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'recurring_schedules',
      description: 'Update recurring schedule',
    },
    {
      method: 'POST',
      path: '/shows/:showId/schedule/generate',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'show_instances',
      description: 'Generate instances from schedule',
    },

    // Show Performers
    {
      method: 'GET',
      path: '/shows/:showId/performers',
      auth: false,
      handler: 'crud',
      entity: 'show_performers',
      operation: 'list',
      description: 'Get show performers',
    },
    {
      method: 'POST',
      path: '/shows/:showId/performers',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'show_performers',
      operation: 'create',
      description: 'Add performer to show',
    },
    {
      method: 'DELETE',
      path: '/shows/:showId/performers/:performerId',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'show_performers',
      operation: 'delete',
      description: 'Remove performer from show',
    },

    // Schedule Actions
    {
      method: 'PUT',
      path: '/shows/:id/publish',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'shows',
      description: 'Publish show',
    },
    {
      method: 'PUT',
      path: '/shows/:id/cancel',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'shows',
      description: 'Cancel show',
    },
    {
      method: 'POST',
      path: '/shows/:id/reschedule',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'shows',
      description: 'Reschedule show',
    },

    // Conflicts
    {
      method: 'GET',
      path: '/schedule/conflicts',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'schedule_conflicts',
      description: 'Get schedule conflicts',
    },
    {
      method: 'POST',
      path: '/schedule/check-conflicts',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'schedule_conflicts',
      description: 'Check for conflicts',
    },

    // Calendar
    {
      method: 'GET',
      path: '/shows/calendar',
      auth: false,
      handler: 'custom',
      entity: 'show_instances',
      description: 'Get calendar data',
    },
    {
      method: 'GET',
      path: '/shows/upcoming',
      auth: false,
      handler: 'custom',
      entity: 'show_instances',
      description: 'Get upcoming shows',
    },
  ],

  config: [
    {
      key: 'defaultShowDuration',
      label: 'Default Show Duration (minutes)',
      type: 'number',
      default: 120,
      description: 'Default duration for new shows',
    },
    {
      key: 'minimumAdvanceNotice',
      label: 'Minimum Advance Notice (hours)',
      type: 'number',
      default: 24,
      description: 'Minimum hours before show for scheduling',
    },
    {
      key: 'enableRecurringShows',
      label: 'Enable Recurring Shows',
      type: 'boolean',
      default: true,
      description: 'Allow recurring show schedules',
    },
    {
      key: 'maxRecurringInstances',
      label: 'Maximum Recurring Instances',
      type: 'number',
      default: 52,
      description: 'Maximum instances to generate for recurring shows',
    },
    {
      key: 'conflictDetection',
      label: 'Conflict Detection',
      type: 'select',
      default: 'warn',
      options: [
        { value: 'off', label: 'Off - No conflict detection' },
        { value: 'warn', label: 'Warn - Show warnings but allow' },
        { value: 'block', label: 'Block - Prevent conflicting schedules' },
      ],
      description: 'How to handle scheduling conflicts',
    },
    {
      key: 'setupTimeMinutes',
      label: 'Setup Time Buffer (minutes)',
      type: 'number',
      default: 60,
      description: 'Buffer time before shows for setup',
    },
    {
      key: 'teardownTimeMinutes',
      label: 'Teardown Time Buffer (minutes)',
      type: 'number',
      default: 30,
      description: 'Buffer time after shows for cleanup',
    },
    {
      key: 'defaultTimezone',
      label: 'Default Timezone',
      type: 'string',
      default: 'America/New_York',
      description: 'Default timezone for show times',
    },
  ],
};
