/**
 * Ticket Sales Feature Definition
 *
 * Complete event ticketing and sales management for entertainment applications.
 * Supports concerts, shows, theater, sports events, and more.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const TICKET_SALES_FEATURE: FeatureDefinition = {
  id: 'ticket-sales',
  name: 'Ticket Sales',
  category: 'business',
  description: 'Manage event ticketing with pricing tiers, inventory tracking, and sales analytics',
  icon: 'ticket',

  includedInAppTypes: [
    'entertainment',
    'event-management',
    'theater',
    'concert-venue',
    'sports-venue',
    'theme-park',
    'museum',
    'festival',
    'ticketing-platform',
  ],

  activationKeywords: [
    'ticket sales',
    'event tickets',
    'ticketing',
    'buy tickets',
    'sell tickets',
    'ticket booking',
    'event ticketing',
    'concert tickets',
    'show tickets',
    'admission tickets',
    'entry tickets',
    'ticket purchase',
    'ticket management',
    'ticket inventory',
    'ticket pricing',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'payments', 'notifications'],
  conflicts: [],

  pages: [
    {
      id: 'tickets-browse',
      route: '/tickets',
      section: 'frontend',
      title: 'Browse Tickets',
      authRequired: false,
      templateId: 'tickets-browse',
      components: [
        'event-ticket-grid',
        'ticket-card',
        'event-filters',
        'date-picker',
        'price-range-filter',
        'category-filter',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'ticket-purchase',
      route: '/tickets/:eventId/purchase',
      section: 'frontend',
      title: 'Purchase Tickets',
      authRequired: false,
      templateId: 'ticket-purchase',
      components: [
        'event-details-header',
        'ticket-type-selector',
        'quantity-picker',
        'price-breakdown',
        'promo-code-input',
        'ticket-checkout-form',
        'payment-method-selector',
        'order-summary',
      ],
      layout: 'default',
    },
    {
      id: 'ticket-confirmation',
      route: '/tickets/confirmation/:orderId',
      section: 'frontend',
      title: 'Order Confirmation',
      authRequired: true,
      templateId: 'ticket-confirmation',
      components: [
        'order-confirmation-header',
        'ticket-details',
        'qr-code-display',
        'download-ticket-button',
        'add-to-calendar',
        'share-tickets',
      ],
      layout: 'centered',
    },
    {
      id: 'my-tickets',
      route: '/my-tickets',
      section: 'frontend',
      title: 'My Tickets',
      authRequired: true,
      templateId: 'my-tickets',
      components: [
        'tickets-list',
        'ticket-card-detailed',
        'ticket-status-filter',
        'upcoming-events',
        'past-events',
        'ticket-transfer-button',
        'ticket-refund-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-tickets',
      route: '/admin/tickets',
      section: 'admin',
      title: 'Manage Tickets',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-tickets',
      components: [
        'tickets-table',
        'sales-overview',
        'inventory-status',
        'ticket-type-manager',
        'pricing-manager',
        'bulk-actions',
        'sales-reports',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-ticket-create',
      route: '/admin/tickets/create',
      section: 'admin',
      title: 'Create Ticket Type',
      authRequired: true,
      roles: ['admin', 'event-manager'],
      templateId: 'admin-ticket-create',
      components: [
        'ticket-type-form',
        'pricing-tiers-builder',
        'inventory-settings',
        'sales-window-config',
        'restrictions-config',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Browse components
    'event-ticket-grid',
    'ticket-card',
    'event-filters',
    'date-picker',
    'price-range-filter',
    'category-filter',
    'sort-dropdown',
    'pagination',

    // Purchase components
    'event-details-header',
    'ticket-type-selector',
    'quantity-picker',
    'price-breakdown',
    'promo-code-input',
    'ticket-checkout-form',
    'payment-method-selector',
    'order-summary',

    // Confirmation components
    'order-confirmation-header',
    'ticket-details',
    'qr-code-display',
    'download-ticket-button',
    'add-to-calendar',
    'share-tickets',

    // My tickets components
    'tickets-list',
    'ticket-card-detailed',
    'ticket-status-filter',
    'upcoming-events',
    'past-events',
    'ticket-transfer-button',
    'ticket-refund-button',

    // Admin components
    'tickets-table',
    'sales-overview',
    'inventory-status',
    'ticket-type-manager',
    'pricing-manager',
    'bulk-actions',
    'sales-reports',
    'ticket-type-form',
    'pricing-tiers-builder',
    'inventory-settings',
    'sales-window-config',
    'restrictions-config',
  ],

  entities: [
    {
      name: 'ticket_types',
      displayName: 'Ticket Types',
      description: 'Types of tickets available for events (VIP, General, etc.)',
      isCore: true,
    },
    {
      name: 'tickets',
      displayName: 'Tickets',
      description: 'Individual ticket records with unique identifiers',
      isCore: true,
    },
    {
      name: 'ticket_orders',
      displayName: 'Ticket Orders',
      description: 'Customer ticket purchase orders',
      isCore: true,
    },
    {
      name: 'ticket_order_items',
      displayName: 'Order Items',
      description: 'Individual items within a ticket order',
      isCore: true,
    },
    {
      name: 'promo_codes',
      displayName: 'Promo Codes',
      description: 'Discount and promotional codes for tickets',
      isCore: false,
    },
    {
      name: 'ticket_transfers',
      displayName: 'Ticket Transfers',
      description: 'Records of ticket transfers between users',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Ticket Types
    {
      method: 'GET',
      path: '/ticket-types',
      auth: false,
      handler: 'crud',
      entity: 'ticket_types',
      operation: 'list',
      description: 'List all ticket types',
    },
    {
      method: 'GET',
      path: '/ticket-types/:id',
      auth: false,
      handler: 'crud',
      entity: 'ticket_types',
      operation: 'get',
      description: 'Get ticket type details',
    },
    {
      method: 'POST',
      path: '/ticket-types',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'ticket_types',
      operation: 'create',
      description: 'Create new ticket type',
    },
    {
      method: 'PUT',
      path: '/ticket-types/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'ticket_types',
      operation: 'update',
      description: 'Update ticket type',
    },
    {
      method: 'DELETE',
      path: '/ticket-types/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'ticket_types',
      operation: 'delete',
      description: 'Delete ticket type',
    },

    // Ticket Orders
    {
      method: 'GET',
      path: '/ticket-orders',
      auth: true,
      handler: 'crud',
      entity: 'ticket_orders',
      operation: 'list',
      description: 'List user ticket orders',
    },
    {
      method: 'GET',
      path: '/ticket-orders/:id',
      auth: true,
      handler: 'crud',
      entity: 'ticket_orders',
      operation: 'get',
      description: 'Get order details',
    },
    {
      method: 'POST',
      path: '/ticket-orders',
      auth: true,
      handler: 'crud',
      entity: 'ticket_orders',
      operation: 'create',
      description: 'Create ticket order',
    },

    // Tickets
    {
      method: 'GET',
      path: '/tickets/my-tickets',
      auth: true,
      handler: 'custom',
      entity: 'tickets',
      description: 'Get user purchased tickets',
    },
    {
      method: 'GET',
      path: '/tickets/:id',
      auth: true,
      handler: 'crud',
      entity: 'tickets',
      operation: 'get',
      description: 'Get ticket details',
    },
    {
      method: 'GET',
      path: '/tickets/:id/qr-code',
      auth: true,
      handler: 'custom',
      entity: 'tickets',
      description: 'Generate ticket QR code',
    },

    // Ticket Transfer
    {
      method: 'POST',
      path: '/tickets/:id/transfer',
      auth: true,
      handler: 'custom',
      entity: 'ticket_transfers',
      description: 'Transfer ticket to another user',
    },
    {
      method: 'POST',
      path: '/tickets/:id/transfer/accept',
      auth: true,
      handler: 'custom',
      entity: 'ticket_transfers',
      description: 'Accept ticket transfer',
    },

    // Promo Codes
    {
      method: 'POST',
      path: '/promo-codes/validate',
      auth: false,
      handler: 'custom',
      entity: 'promo_codes',
      description: 'Validate promo code',
    },
    {
      method: 'GET',
      path: '/promo-codes',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'promo_codes',
      operation: 'list',
      description: 'List all promo codes',
    },
    {
      method: 'POST',
      path: '/promo-codes',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'promo_codes',
      operation: 'create',
      description: 'Create promo code',
    },

    // Sales Analytics
    {
      method: 'GET',
      path: '/tickets/analytics/sales',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'ticket_orders',
      description: 'Get sales analytics',
    },
    {
      method: 'GET',
      path: '/tickets/analytics/inventory',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'tickets',
      description: 'Get inventory status',
    },
  ],

  config: [
    {
      key: 'allowGuestCheckout',
      label: 'Allow Guest Checkout',
      type: 'boolean',
      default: true,
      description: 'Allow ticket purchase without account',
    },
    {
      key: 'maxTicketsPerOrder',
      label: 'Maximum Tickets Per Order',
      type: 'number',
      default: 10,
      description: 'Maximum number of tickets in a single order',
    },
    {
      key: 'enableTicketTransfer',
      label: 'Enable Ticket Transfer',
      type: 'boolean',
      default: true,
      description: 'Allow users to transfer tickets to others',
    },
    {
      key: 'enableRefunds',
      label: 'Enable Refunds',
      type: 'boolean',
      default: true,
      description: 'Allow ticket refund requests',
    },
    {
      key: 'refundDeadlineHours',
      label: 'Refund Deadline (hours before event)',
      type: 'number',
      default: 24,
      description: 'Hours before event when refunds are no longer allowed',
    },
    {
      key: 'enableWaitlist',
      label: 'Enable Waitlist',
      type: 'boolean',
      default: true,
      description: 'Allow waitlist when tickets are sold out',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for ticket pricing',
    },
    {
      key: 'serviceFeePercentage',
      label: 'Service Fee Percentage',
      type: 'number',
      default: 10,
      description: 'Service fee percentage added to ticket price',
    },
  ],
};
