/**
 * Venue Booking Feature Definition
 *
 * Complete venue and theater reservation management for entertainment applications.
 * Supports theaters, concert halls, event spaces, and multi-purpose venues.
 */

import { FeatureDefinition } from '../../../interfaces/feature.interface';

export const VENUE_BOOKING_FEATURE: FeatureDefinition = {
  id: 'venue-booking',
  name: 'Venue Booking',
  category: 'business',
  description: 'Manage venue and theater reservations with availability, pricing, and booking workflows',
  icon: 'building',

  includedInAppTypes: [
    'entertainment',
    'event-management',
    'theater',
    'concert-venue',
    'event-space',
    'conference-center',
    'wedding-venue',
    'banquet-hall',
    'community-center',
  ],

  activationKeywords: [
    'venue booking',
    'venue reservation',
    'theater booking',
    'hall rental',
    'event space',
    'venue rental',
    'book venue',
    'reserve venue',
    'venue availability',
    'venue hire',
    'space rental',
    'auditorium booking',
    'concert hall',
    'event venue',
    'venue management',
  ],

  enabledByDefault: true,
  optional: false,

  dependencies: ['user-auth', 'calendar', 'notifications'],
  conflicts: [],

  pages: [
    {
      id: 'venues-browse',
      route: '/venues',
      section: 'frontend',
      title: 'Browse Venues',
      authRequired: false,
      templateId: 'venues-browse',
      components: [
        'venue-grid',
        'venue-card',
        'venue-filters',
        'capacity-filter',
        'amenities-filter',
        'location-filter',
        'date-availability-picker',
        'sort-dropdown',
        'pagination',
      ],
      layout: 'default',
    },
    {
      id: 'venue-detail',
      route: '/venues/:id',
      section: 'frontend',
      title: 'Venue Details',
      authRequired: false,
      templateId: 'venue-detail',
      components: [
        'venue-gallery',
        'venue-details',
        'venue-amenities',
        'venue-floor-plan',
        'venue-availability-calendar',
        'venue-pricing',
        'venue-reviews',
        'booking-request-form',
        'contact-venue-button',
      ],
      layout: 'default',
    },
    {
      id: 'venue-booking-request',
      route: '/venues/:id/book',
      section: 'frontend',
      title: 'Book Venue',
      authRequired: true,
      templateId: 'venue-booking-request',
      components: [
        'venue-summary',
        'date-time-selector',
        'event-details-form',
        'services-addons',
        'catering-options',
        'equipment-rental',
        'pricing-calculator',
        'booking-terms',
        'payment-deposit',
      ],
      layout: 'default',
    },
    {
      id: 'my-venue-bookings',
      route: '/my-bookings/venues',
      section: 'frontend',
      title: 'My Venue Bookings',
      authRequired: true,
      templateId: 'my-venue-bookings',
      components: [
        'bookings-list',
        'booking-card',
        'booking-status-filter',
        'upcoming-bookings',
        'past-bookings',
        'booking-actions',
        'modify-booking-button',
        'cancel-booking-button',
      ],
      layout: 'dashboard',
    },
    {
      id: 'admin-venues',
      route: '/admin/venues',
      section: 'admin',
      title: 'Manage Venues',
      authRequired: true,
      roles: ['admin', 'venue-manager'],
      templateId: 'admin-venues',
      components: [
        'venues-table',
        'venue-status-manager',
        'availability-manager',
        'pricing-manager',
        'bookings-overview',
        'revenue-reports',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-venue-create',
      route: '/admin/venues/create',
      section: 'admin',
      title: 'Add Venue',
      authRequired: true,
      roles: ['admin', 'venue-manager'],
      templateId: 'admin-venue-create',
      components: [
        'venue-form',
        'venue-gallery-uploader',
        'floor-plan-uploader',
        'amenities-selector',
        'capacity-config',
        'pricing-config',
        'availability-rules',
        'booking-policies',
      ],
      layout: 'admin',
    },
    {
      id: 'admin-booking-management',
      route: '/admin/venues/bookings',
      section: 'admin',
      title: 'Booking Management',
      authRequired: true,
      roles: ['admin', 'venue-manager'],
      templateId: 'admin-booking-management',
      components: [
        'bookings-table',
        'booking-calendar-view',
        'booking-approval',
        'booking-details-modal',
        'conflict-resolver',
        'communication-panel',
      ],
      layout: 'admin',
    },
  ],

  components: [
    // Browse components
    'venue-grid',
    'venue-card',
    'venue-filters',
    'capacity-filter',
    'amenities-filter',
    'location-filter',
    'date-availability-picker',
    'sort-dropdown',
    'pagination',

    // Detail components
    'venue-gallery',
    'venue-details',
    'venue-amenities',
    'venue-floor-plan',
    'venue-availability-calendar',
    'venue-pricing',
    'venue-reviews',
    'booking-request-form',
    'contact-venue-button',

    // Booking components
    'venue-summary',
    'date-time-selector',
    'event-details-form',
    'services-addons',
    'catering-options',
    'equipment-rental',
    'pricing-calculator',
    'booking-terms',
    'payment-deposit',

    // My bookings components
    'bookings-list',
    'booking-card',
    'booking-status-filter',
    'upcoming-bookings',
    'past-bookings',
    'booking-actions',
    'modify-booking-button',
    'cancel-booking-button',

    // Admin components
    'venues-table',
    'venue-status-manager',
    'availability-manager',
    'pricing-manager',
    'bookings-overview',
    'revenue-reports',
    'venue-form',
    'venue-gallery-uploader',
    'floor-plan-uploader',
    'amenities-selector',
    'capacity-config',
    'pricing-config',
    'availability-rules',
    'booking-policies',
    'bookings-table',
    'booking-calendar-view',
    'booking-approval',
    'booking-details-modal',
    'conflict-resolver',
    'communication-panel',
  ],

  entities: [
    {
      name: 'venues',
      displayName: 'Venues',
      description: 'Venue/location records with details and capacity',
      isCore: true,
    },
    {
      name: 'venue_images',
      displayName: 'Venue Images',
      description: 'Photos and media for venues',
      isCore: true,
    },
    {
      name: 'venue_amenities',
      displayName: 'Venue Amenities',
      description: 'Available amenities and features for venues',
      isCore: true,
    },
    {
      name: 'venue_bookings',
      displayName: 'Venue Bookings',
      description: 'Venue reservation records',
      isCore: true,
    },
    {
      name: 'venue_availability',
      displayName: 'Venue Availability',
      description: 'Availability schedules and blocked dates',
      isCore: true,
    },
    {
      name: 'venue_pricing',
      displayName: 'Venue Pricing',
      description: 'Pricing rules and rates for venues',
      isCore: false,
    },
    {
      name: 'venue_addons',
      displayName: 'Venue Add-ons',
      description: 'Additional services and equipment for venues',
      isCore: false,
    },
  ],

  apiRoutes: [
    // Venues CRUD
    {
      method: 'GET',
      path: '/venues',
      auth: false,
      handler: 'crud',
      entity: 'venues',
      operation: 'list',
      description: 'List all venues',
    },
    {
      method: 'GET',
      path: '/venues/:id',
      auth: false,
      handler: 'crud',
      entity: 'venues',
      operation: 'get',
      description: 'Get venue details',
    },
    {
      method: 'POST',
      path: '/venues',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'venues',
      operation: 'create',
      description: 'Create new venue',
    },
    {
      method: 'PUT',
      path: '/venues/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'venues',
      operation: 'update',
      description: 'Update venue',
    },
    {
      method: 'DELETE',
      path: '/venues/:id',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'venues',
      operation: 'delete',
      description: 'Delete venue',
    },

    // Venue Images
    {
      method: 'GET',
      path: '/venues/:id/images',
      auth: false,
      handler: 'crud',
      entity: 'venue_images',
      operation: 'list',
      description: 'Get venue images',
    },
    {
      method: 'POST',
      path: '/venues/:id/images',
      auth: true,
      role: 'admin',
      handler: 'crud',
      entity: 'venue_images',
      operation: 'create',
      description: 'Add venue image',
    },

    // Availability
    {
      method: 'GET',
      path: '/venues/:id/availability',
      auth: false,
      handler: 'custom',
      entity: 'venue_availability',
      description: 'Get venue availability for date range',
    },
    {
      method: 'PUT',
      path: '/venues/:id/availability',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'venue_availability',
      description: 'Update venue availability',
    },

    // Bookings
    {
      method: 'GET',
      path: '/venue-bookings',
      auth: true,
      handler: 'crud',
      entity: 'venue_bookings',
      operation: 'list',
      description: 'List user venue bookings',
    },
    {
      method: 'GET',
      path: '/venue-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'venue_bookings',
      operation: 'get',
      description: 'Get booking details',
    },
    {
      method: 'POST',
      path: '/venue-bookings',
      auth: true,
      handler: 'crud',
      entity: 'venue_bookings',
      operation: 'create',
      description: 'Create venue booking request',
    },
    {
      method: 'PUT',
      path: '/venue-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'venue_bookings',
      operation: 'update',
      description: 'Update venue booking',
    },
    {
      method: 'DELETE',
      path: '/venue-bookings/:id',
      auth: true,
      handler: 'crud',
      entity: 'venue_bookings',
      operation: 'delete',
      description: 'Cancel venue booking',
    },

    // Booking Status
    {
      method: 'PUT',
      path: '/venue-bookings/:id/approve',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'venue_bookings',
      description: 'Approve booking request',
    },
    {
      method: 'PUT',
      path: '/venue-bookings/:id/reject',
      auth: true,
      role: 'admin',
      handler: 'custom',
      entity: 'venue_bookings',
      description: 'Reject booking request',
    },

    // Pricing
    {
      method: 'GET',
      path: '/venues/:id/pricing',
      auth: false,
      handler: 'custom',
      entity: 'venue_pricing',
      description: 'Get venue pricing',
    },
    {
      method: 'POST',
      path: '/venues/:id/pricing/calculate',
      auth: false,
      handler: 'custom',
      entity: 'venue_pricing',
      description: 'Calculate booking price',
    },
  ],

  config: [
    {
      key: 'requireApproval',
      label: 'Require Booking Approval',
      type: 'boolean',
      default: true,
      description: 'Require admin approval for bookings',
    },
    {
      key: 'minBookingNotice',
      label: 'Minimum Booking Notice (hours)',
      type: 'number',
      default: 48,
      description: 'Minimum hours in advance for booking',
    },
    {
      key: 'maxBookingAdvance',
      label: 'Maximum Booking Advance (days)',
      type: 'number',
      default: 365,
      description: 'Maximum days in advance for booking',
    },
    {
      key: 'depositPercentage',
      label: 'Deposit Percentage',
      type: 'number',
      default: 25,
      description: 'Required deposit percentage for bookings',
    },
    {
      key: 'cancellationPolicy',
      label: 'Cancellation Policy',
      type: 'select',
      default: 'moderate',
      options: [
        { value: 'flexible', label: 'Flexible - Full refund 24h before' },
        { value: 'moderate', label: 'Moderate - Full refund 7 days before' },
        { value: 'strict', label: 'Strict - 50% refund 14 days before' },
        { value: 'non-refundable', label: 'Non-refundable' },
      ],
      description: 'Cancellation and refund policy',
    },
    {
      key: 'enableSetupTime',
      label: 'Include Setup Time',
      type: 'boolean',
      default: true,
      description: 'Allow booking setup and breakdown time',
    },
    {
      key: 'defaultSetupHours',
      label: 'Default Setup Time (hours)',
      type: 'number',
      default: 2,
      description: 'Default setup time before events',
    },
    {
      key: 'defaultCurrency',
      label: 'Default Currency',
      type: 'string',
      default: 'USD',
      description: 'Default currency for pricing',
    },
  ],
};
