/**
 * Shared Tool Icons Utility
 * Provides consistent icon mapping across all tool-related components
 */

import {
  Calculator,
  Code,
  Code2,
  Type,
  Lock,
  Repeat,
  Sparkles,
  Clock,
  Image,
  Palette,
  Heart,
  Activity,
  Home,
  Car,
  Star,
  Music,
  Wrench,
  Hash,
  Eye,
  GitCompare,
  FileJson,
  FlipHorizontal,
  SortAsc,
  Replace,
  Filter,
  FileDiff,
  Link,
  Shield,
  Key,
  Binary,
  Percent,
  Tag,
  Calendar,
  Receipt,
  Banknote,
  CalendarRange,
  BarChart,
  FunctionSquare,
  Landmark,
  Divide,
  Ratio,
  Thermometer,
  Ruler,
  Scale,
  Timer,
  Footprints,
  HardDrive,
  Gauge,
  QrCode,
  AlignLeft,
  Wifi,
  Barcode,
  User,
  Text,
  AlarmClock,
  Globe,
  CalendarCheck,
  Cake,
  FileMinus,
  Pipette,
  Wand2,
  Eraser,
  Maximize,
  Droplets,
  Stamp,
  Paintbrush,
  Trash2,
  RefreshCw,
  Droplet,
  Film,
  Scan,
  Mail,
  BookOpen,
  Newspaper,
  Share2,
  Languages,
  SpellCheck,
  FileText,
  Linkedin,
  Mic,
  Book,
  Quote,
  Hexagon,
  Video,
  UserCircle,
  Layout,
  Box,
  PieChart,
  FileSpreadsheet,
  Presentation,
  TrendingUp,
  Target,
  Lightbulb,
  MessageSquare,
  Briefcase,
  Megaphone,
  Bot,
  Brain,
  Zap,
  Network,
  Database,
  Server,
  Terminal,
  GitBranch,
  FileCode,
  Bug,
  TestTube,
  Package,
  Settings,
  Stethoscope,
  Apple,
  Moon,
  Bed,
  Dumbbell,
  Bike,
  Trophy,
  Flame,
  Waves,
  CreditCard,
  Wallet,
  PiggyBank,
  TrendingDown,
  LineChart,
  Coins,
  Beef,
  Coffee,
  Cookie,
  UtensilsCrossed,
  Hammer,
  Sofa,
  Leaf,
  TreePine,
  Sun,
  CloudRain,
  Snowflake,
  Wind,
  Cloud,
  Fuel,
  Truck,
  CarFront,
  PawPrint,
  Dog,
  Cat,
  Fish,
  Bird,
  Plane,
  MapPin,
  Compass,
  Luggage,
  Hotel,
  Camera,
  Umbrella,
  Map,
  Navigation,
  Anchor,
  Ship,
  Train,
  Bus,
  Gem,
  Gift,
  CalendarDays,
  Smartphone,
  Laptop,
  Watch,
  Headphones,
  Tv,
  BookMarked,
  Pencil,
  Gamepad2,
  Puzzle,
  Dice1,
  Spade,
  PartyPopper,
  Clapperboard,
  Popcorn,
  Ticket,
  Radio,
  Podcast,
  Guitar,
  Piano,
  Drum,
  Volume2,
  Mic2,
  CheckSquare,
  ListTodo,
  ClipboardList,
  FolderKanban,
  ClipboardCheck,
  ListChecks,
  Building2,
  Building,
  Store,
  Factory,
  Gavel,
  UserCheck,
  BadgeCheck,
  UserPlus,
  UserCog,
  FileCheck,
  FileSignature,
  Clipboard,
  Phone,
  AtSign,
  Send,
  Bell,
  AlertCircle,
  Info,
  HelpCircle,
  CheckCircle,
  XCircle,
  AlertTriangle,
  ShieldCheck,
  ShieldAlert,
  Unlock,
  KeyRound,
  Medal,
  Award,
  Crown,
  Swords,
  Rocket,
  Mountain,
  Tent,
  Backpack,
  Grid3X3,
  LayoutGrid,
  LayoutList,
  Table,
  Layers,
  Sliders,
  SlidersHorizontal,
  Scissors,
  Hand,
  Fingerprint,
  Smile,
  ThumbsUp,
  Handshake,
  ShoppingCart,
  ShoppingBag,
  Archive,
  FolderOpen,
  Files,
  Boxes,
  Cog,
  Settings2,
  PenTool,
  DollarSign,
  ChefHat,
  Flower,
  GraduationCap,
  Users,
  CircleDot,
  Baby,
  Frame,
  MailPlus,
  ListOrdered,
  Feather,
  Monitor,
  // Additional icons for full coverage
  Aperture,
  Atom,
  Bath,
  Beaker,
  Beer,
  BrickWall,
  CloudLightning,
  Croissant,
  Cross,
  CupSoda,
  Dice6,
  Disc,
  Egg,
  Fan,
  Fence,
  File,
  Folder,
  GanttChart,
  Grid,
  HardHat,
  Headset,
  HeartPulse,
  Keyboard,
  List,
  MessageCircle,
  Minimize,
  PersonStanding,
  Pill,
  Pizza,
  Recycle,
  Route,
  Scroll,
  Sprout,
  Square,
  Sticker,
  StickyNote,
  StretchHorizontal,
  Subtitles,
  Syringe,
  Twitter,
  Utensils,
  Volume,
  Wine,
  Youtube,
  Columns,
  LayoutDashboard,
} from 'lucide-react';

// Comprehensive icon mapping for all tools
const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // Basic
  'calculator': Calculator,
  'code': Code,
  'code-2': Code2,
  'type': Type,
  'lock': Lock,
  'sparkles': Sparkles,
  'clock': Clock,
  'image': Image,
  'palette': Palette,
  'heart': Heart,
  'activity': Activity,
  'home': Home,
  'car': Car,
  'star': Star,
  'music': Music,
  'wrench': Wrench,
  'tool': Wrench,

  // Text tools
  'hash': Hash,
  'eye': Eye,
  'git-compare': GitCompare,
  'file-json': FileJson,
  'flip-horizontal': FlipHorizontal,
  'sort-asc': SortAsc,
  'replace': Replace,
  'filter': Filter,
  'file-diff': FileDiff,
  'regex': Code2,

  // Encoding
  'link': Link,
  'shield': Shield,
  'key': Key,
  'binary': Binary,

  // Calculators
  'percent': Percent,
  'tag': Tag,
  'calendar': Calendar,
  'receipt': Receipt,
  'banknote': Banknote,
  'calendar-range': CalendarRange,
  'bar-chart': BarChart,
  'function-square': FunctionSquare,
  'landmark': Landmark,
  'graduation-cap': GraduationCap,
  'divide': Divide,
  'ratio': Ratio,

  // Converters
  'thermometer': Thermometer,
  'ruler': Ruler,
  'scale': Scale,
  'timer': Timer,
  'dollar-sign': DollarSign,
  'footprints': Footprints,
  'hard-drive': HardDrive,
  'gauge': Gauge,
  'chef-hat': ChefHat,

  // Generators
  'qr-code': QrCode,
  'align-left': AlignLeft,
  'wifi': Wifi,
  'barcode': Barcode,
  'user': User,
  'text': Text,
  'pen-tool': PenTool,

  // Date & Time
  'alarm-clock': AlarmClock,
  'globe': Globe,
  'calendar-check': CalendarCheck,
  'cake': Cake,
  'users': Users,

  // Image tools
  'file-minus': FileMinus,
  'pipette': Pipette,
  'wand-2': Wand2,
  'eraser': Eraser,
  'maximize': Maximize,
  'droplets': Droplets,
  'stamp': Stamp,
  'paintbrush': Paintbrush,
  'trash-2': Trash2,
  'refresh-cw': RefreshCw,
  'droplet': Droplet,
  'film': Film,
  'scan': Scan,

  // AI Writing
  'mail': Mail,
  'book-open': BookOpen,
  'newspaper': Newspaper,
  'share-2': Share2,
  'repeat': Repeat,
  'languages': Languages,
  'spell-check': SpellCheck,
  'file-text': FileText,
  'linkedin': Linkedin,
  'mic': Mic,
  'book': Book,
  'quote': Quote,
  'feather': Feather,

  // AI Creative
  'hexagon': Hexagon,
  'video': Video,
  'user-circle': UserCircle,
  'layout': Layout,
  'box': Box,
  'frame': Frame,
  'file-image': Image,

  // AI Business
  'pie-chart': PieChart,
  'file-spreadsheet': FileSpreadsheet,
  'presentation': Presentation,
  'trending-up': TrendingUp,
  'target': Target,
  'lightbulb': Lightbulb,
  'message-square': MessageSquare,
  'briefcase': Briefcase,
  'list-ordered': ListOrdered,
  'help-circle': HelpCircle,
  'mail-plus': MailPlus,

  // AI Marketing
  'megaphone': Megaphone,
  'bot': Bot,
  'shopping-bag': ShoppingBag,

  // Developer
  'brain': Brain,
  'zap': Zap,
  'network': Network,
  'database': Database,
  'server': Server,
  'terminal': Terminal,
  'git-branch': GitBranch,
  'file-code': FileCode,
  'bug': Bug,
  'test-tube': TestTube,
  'package': Package,
  'settings': Settings,

  // Health & Wellness
  'stethoscope': Stethoscope,
  'apple': Apple,
  'moon': Moon,
  'bed': Bed,
  'baby': Baby,
  'paint-bucket': Paintbrush,
  'circle-dot': CircleDot,
  'monitor': Monitor,

  // Fitness & Sports
  'dumbbell': Dumbbell,
  'bike': Bike,
  'trophy': Trophy,
  'flame': Flame,
  'waves': Waves,

  // Finance
  'credit-card': CreditCard,
  'wallet': Wallet,
  'piggy-bank': PiggyBank,
  'trending-down': TrendingDown,
  'line-chart': LineChart,
  'coins': Coins,

  // Cooking
  'beef': Beef,
  'coffee': Coffee,
  'cookie': Cookie,
  'utensils-crossed': UtensilsCrossed,

  // Home & DIY
  'hammer': Hammer,
  'paint': Paintbrush,
  'sofa': Sofa,
  'water-drop': Droplet,

  // Gardening
  'flower': Flower,
  'leaf': Leaf,
  'tree-pine': TreePine,
  'sun': Sun,
  'cloud-rain': CloudRain,
  'snowflake': Snowflake,
  'wind': Wind,
  'cloud': Cloud,

  // Automotive
  'fuel': Fuel,
  'car-wrench': Wrench,
  'truck': Truck,
  'car-front': CarFront,
  'circle': CircleDot,

  // Pet Care
  'paw-print': PawPrint,
  'dog': Dog,
  'cat': Cat,
  'fish': Fish,
  'bird': Bird,

  // Travel
  'plane': Plane,
  'map-pin': MapPin,
  'compass': Compass,
  'luggage': Luggage,
  'hotel': Hotel,
  'camera': Camera,
  'umbrella': Umbrella,
  'map': Map,
  'navigation': Navigation,
  'anchor': Anchor,
  'ship': Ship,
  'train': Train,
  'bus': Bus,

  // Lifestyle
  'gem': Gem,
  'gift': Gift,
  'calendar-days': CalendarDays,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'watch': Watch,
  'headphones': Headphones,
  'tv': Tv,
  'ticket': Ticket,

  // Education
  'book-marked': BookMarked,
  'pencil': Pencil,

  // Entertainment
  'gamepad-2': Gamepad2,
  'puzzle': Puzzle,
  'dice-1': Dice1,
  'spade': Spade,
  'party-popper': PartyPopper,
  'clapperboard': Clapperboard,
  'popcorn': Popcorn,
  'smile': Smile,

  // Music
  'radio': Radio,
  'podcast': Podcast,
  'guitar': Guitar,
  'piano': Piano,
  'drum': Drum,
  'volume-2': Volume2,
  'mic-2': Mic2,

  // Productivity
  'check-square': CheckSquare,
  'list-todo': ListTodo,
  'clipboard-list': ClipboardList,
  'folder-kanban': FolderKanban,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,

  // Business
  'building-2': Building2,
  'building': Building,
  'store': Store,
  'factory': Factory,
  'gavel': Gavel,

  // Professional
  'user-check': UserCheck,
  'badge-check': BadgeCheck,
  'user-plus': UserPlus,
  'user-cog': UserCog,
  'file-check': FileCheck,
  'file-signature': FileSignature,
  'clipboard': Clipboard,

  // Communication
  'phone': Phone,
  'at-sign': AtSign,
  'send': Send,
  'bell': Bell,

  // Status
  'alert-circle': AlertCircle,
  'info': Info,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,

  // Security
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'unlock': Unlock,
  'key-round': KeyRound,

  // Sports & Games
  'medal': Medal,
  'award': Award,
  'crown': Crown,
  'swords': Swords,
  'rocket': Rocket,
  'mountain': Mountain,
  'tent': Tent,
  'backpack': Backpack,

  // UI
  'grid-3x3': Grid3X3,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  'table': Table,
  'layers': Layers,
  'sliders': Sliders,
  'sliders-horizontal': SlidersHorizontal,

  // Misc
  'scissors': Scissors,
  'hand': Hand,
  'fingerprint': Fingerprint,
  'thumbs-up': ThumbsUp,
  'handshake': Handshake,
  'shopping-cart': ShoppingCart,
  'archive': Archive,
  'folder-open': FolderOpen,
  'files': Files,
  'boxes': Boxes,
  'cog': Cog,
  'settings-2': Settings2,

  // Additional icons for full toolsData coverage
  'aperture': Aperture,
  'atom': Atom,
  'bath': Bath,
  'beaker': Beaker,
  'beer': Beer,
  'brick-wall': BrickWall,
  'cloud-lightning': CloudLightning,
  'croissant': Croissant,
  'cross': Cross,
  'cup-soda': CupSoda,
  'dice-6': Dice6,
  'disc': Disc,
  'egg': Egg,
  'fan': Fan,
  'fence': Fence,
  'file': File,
  'folder': Folder,
  'gantt-chart': GanttChart,
  'grid': Grid,
  'hard-hat': HardHat,
  'headset': Headset,
  'heart-pulse': HeartPulse,
  'keyboard': Keyboard,
  'list': List,
  'message-circle': MessageCircle,
  'minimize': Minimize,
  'person-standing': PersonStanding,
  'pill': Pill,
  'pizza': Pizza,
  'recycle': Recycle,
  'route': Route,
  'scroll': Scroll,
  'sprout': Sprout,
  'square': Square,
  'sticker': Sticker,
  'sticky-note': StickyNote,
  'stretch-horizontal': StretchHorizontal,
  'subtitles': Subtitles,
  'syringe': Syringe,
  'twitter': Twitter,
  'utensils': Utensils,
  'volume': Volume,
  'wine': Wine,
  'youtube': Youtube,
  'columns': Columns,
  'cards': LayoutDashboard,
  'martini': Wine,
  'steps': Footprints,
  'needle': Syringe,
  'iron': Settings,
  'jar': Beaker,
  'golf': Target,
  'dish': Utensils,
  'flower-2': Flower,
};

/**
 * Get the icon component for a given icon name
 * @param iconName - The name of the icon (e.g., 'calculator', 'code', 'hash')
 * @returns The React component for the icon, or Calculator as fallback
 */
export const getToolIcon = (iconName: string | undefined): React.ComponentType<{ className?: string }> => {
  if (!iconName) return Calculator;
  return iconMap[iconName] || Calculator;
};

/**
 * Get the icon component for a tool ID using the toolIcons mapping from ContextualUI
 */
export const getToolIconById = (toolId: string, toolIcons: Record<string, string>): React.ComponentType<{ className?: string }> => {
  const iconName = toolIcons[toolId];
  return getToolIcon(iconName);
};

export default getToolIcon;
